### ISSUE TITLE
Show release version number in lnb area

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1]
**Is your feature request related to a problem? Please describe.**
설치후, 릴리즈 버젼에 대한 정보를 알수가 없어 배포시 UI를 통해 확인할수 있는 방법이 없습니다.

**Describe the solution you'd like**
LNB 영역 하단에 버젼명을 표시합니다.  
![lnb_version](https://user-images.githubusercontent.com/822255/43999166-f5618752-9e41-11e8-885c-919b6cabc5d4.png)

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by alchan-lee** [comment]
@kyungtaak 55635fc 이게 maven replacer로 artifacts(chunk.js)의 토큰을 치환하는 방식이고
613443f 이게 angular 빌드 전에 nodejs 단계를 추가(node prebuild)해서 환경변수를 넘기는 방식인데요..

두 방법 다 기능 구현에는 문제 없는데 어떤 방식이 더 좋을 지.. 의견 부탁드립니다

방법이 정해지면 둘 중 하나로 Pull Request 생성할게요

**Comment by kyungtaak** [comment]
@alchan-lee 환경변수를 넘기는 방식으로 진행하는게 좋을것 같습니다. 확인 부탁드려요.
