### ISSUE TITLE
Add missed Chinese label

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#1008]
**Describe the bug**
중국어 label 반영 후 수정된 이슈들에서 추가된 label 대해 중국어 추가

**To Reproduce**

**Expected behavior**
중국어가 나타나야 함

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
3.1.0 에서 합쳐진 이슈이므로 이슈를 종료합니다.
