### ISSUE TITLE
Missing link on network chart

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#101]
**Describe the bug**
네트워크 차트내에서 source 와 target의 정보가 모두 존재하지만, 단방향으로만 표시됩니다.

(데이터 예시)
```
{
  "nodes": [
  	...,
    {
      "field": "AwayTeam",
      "name": "Korea Republic",
      "value": 964.0
    },
    ...,
    {
      "field": "HomeTeam",
      "name": "Korea Republic",
      "value": 836.0
    }
    ...
  ],
  "links": [
  	...,
    {
      "sourceField": "HomeTeam",
      "source": "Argentina",
      "targetField": "AwayTeam",
      "target": "Korea Republic",
      "value": 2
    },
    ...
    {
      "sourceField": "HomeTeam",
      "source": "Korea Republic",
      "targetField": "AwayTeam",
      "target": "Algeria",
      "value": 1
    },
    ...
  ]
}
```

**To Reproduce**
1. Go to [DemoLink](https://discovery.metatron.app/app/v2/workbook/57cad565-7616-40ba-a81d-a92fece63d99)
2. Click on 'Network' Dashboard
3. Mouse over 'Korea Republic' Node

**Expected behavior**
source 와 target의 정보가 모두 존재한다면 양방향으로 표시되어야합니다.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 68.0

**Additional context**
@esezin  대시보드에서 노드클릭시 셀렉션 필터링의 정책은 어떻게 되는지 추가확인 부탁드립니다.

**Comment by esezin** [comment]
@kyungtaak  
셀랙션 필터는 echart dependency가 좀 있는 것으로 알고 있어서.. 개발쪽과의 논의도 필요할 것 같습니다. 논의 하고 추가로 답변 드리겠습니다.

**Comment by kyungtaak** [comment]
@esezin @juheeko9 network 차트의 경우 source / target의 필드 구분과 상관없이 node 값이 같으면 하나의 노드로 인식하고 링크를 표시하는게 기획의도가 아니었나요?

**Comment by esezin** [comment]
@kyungtaak 
1. 기획의도는 source와 target이 동일한 노드인 경우, 양방향으로 표시된는 것이 맞습니다.
2. 관련된 논의가 되겠습니다만, 대시보드에서의 셀랙션 필터 동작은 노드 선택시에는 해당 노드만 선택, 연결선을 선택시에는 연결된 양쪽 노드를 모두 선택하게 하는 것이 필요합니다. (생키와 동일)

**Comment by kyungtaak** [comment]
@juheeko9 위 @esezin 의견 확인해주시고요. 구현 가능여부 확인 부탁드립니다.

**Comment by juheeko9** [comment]
@kyungtaak 
1. source / target 필드 구분과 상관없이 node값이 같은경우 하나의 노드로 인식하고 링크를 표시하는것은 가능합니다.
하나의 노드로 인식하고 링크를 표시하기위해서는 현재  nodes에서 name이 같은경우 nodes가 각각 리턴되고있는데, 

- 해당 중복되는 노드를 단일개로 구성

- 중복된 노드의 field값 리스트로 구성

되게 수정이 필요합니다. 수정 부탁드립니다.

[데이터예시]
<현재값>
```
{
  "nodes": [
    {
      "field": "AwayTeam",
      "name": "Korea Republic",
      "value": 964.0
    },
    {
      "field": "HomeTeam",
      "name": "Korea Republic",
      "value": 836.0
    },
    ...,
    
  ],
  "links": [
    ...,
    
  ]
}
```
<변경요청값>
```
{
  "nodes": [
    {
      "name": "Korea Republic",
      "value": 1800,
      "fields": [
        "AwayTeam",
        "HomeTeam"
      ]
    },
    ...,
    
  ],
  "links": [
    ...,
  ]
}
```

@esezin 
2. source / target 필드 구분과 상관없이 node값이 같은경우
툴팁에서 어느 dimension에 해당하는지 알 수 없기때문에 Node Name의 경우 어떻게 표시할지 논의가 필요합니다.

**Comment by kyungtaak** [comment]
@juheeko9 이미 내부적으로  중복체크로직이 들어있는것으로 알고 있는데요. Client 상에서 처리하는 것이 좋을것 같은데요. 어떻게 생각하시나요?

**Comment by dave-taeho** [comment]
@kyungtaak 클라이언트의 중복체크 로직은 따로 없습니다.
노드명이 중복되는 데이터가 네트워크 차트에 전달시 echart에러가 발생하기 때문에
필드명+노드명으로 display되는 이름과 다른 이름으로 설정해주는 로직이 들어가 있습니다.
클라이언트에서 루프를 여러번 돈다면 처리가 가능한 사항이지만 네트워크 차트 성능을 위해서라도 
데이터 가공은 서버쪽에서 해주시는게 좋을거 같은데.. 확인 부탁드립니다.

**Comment by esezin** [comment]
@juheeko9 
툴팁에서는 해당되는 Dimension이 모두 표시 되면 될 것 같습니다. Source / Target 모두에 해당되는 경우 두 개 다 표시가 되겠지요. 
(e.g.)
hometeam : republic of korea
awayteam : republic of korea

**Comment by kyungtaak** [comment]
@dave-taeho 넵 제안해주신 형태로 전달하겠습니다.

**Comment by kyungtaak** [comment]
@dave-taeho  f#101-network_chart_link 브렌치에 제안주신 결과값을 처리하였습니다.
Search Query 호출시 아래와 같이 호출해주세요.
```
{
    ...,
    "resultFormat": {
        "type": "graph",
        "useLinkCount": true,
        "mergeNode": true
    }
}
```

**Comment by esezin** [comment]
셀랙션 필터링 동작에 대한 이슈는 아래의 이슈로 분리해서 별도 등록해두었습니다.
https://github.com/metatron-app/metatron-discovery/issues/255

**Comment by juheeko9** [comment]
@kyungtaak #250 PR에 올렸던 내용이 정상적으로 반영되지 않았습니다.
로컬에서는 mergeNode 파라미터값이 정상적으로 설정되어 nodes값에서 fields값으로 리턴되는것을 확인하였으나
테스트서버 4에서는 설정된 파라미터값이 반영되지 않은것으로 확인하였습니다. 
확인부탁드립니다.

[로컬에서 확인시]
![screen shot 2018-09-18 at 2 04 41 pm](https://user-images.githubusercontent.com/42233502/45665525-41c2e380-bb4c-11e8-9dd1-643ca2bf9337.png)
![screen shot 2018-09-18 at 2 04 48 pm](https://user-images.githubusercontent.com/42233502/45665528-44253d80-bb4c-11e8-8e93-e7cb32076e61.png)
