### ISSUE TITLE
Timestamp type column error when deleting

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1019]
**Describe the bug**
When column type is TIMESTAMP and timestamp format does't have year(YYYY)
delete and keep fails in context menu.

**To Reproduce**
Dataflow main grid -> Add Setformat to timestamp type column. Format is `MM-dd` -> click histogram (column that you just added setformat to) ->  context menu ->  delete -> see error

**Expected behavior**
Selected row must be deleted.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
It seems like better having the server deliver the timestamp format string to be used in conditional expressions.
@ mh0203 will work on it.

_서버에서 조건문에 사용할 timestamp format string을 함께 내리는 것이 좋겠습니다.
@mh0203 님께서 작업하실 예정입니다._

**Comment by mh0203** [comment]
This request is resolved as follows
  1. Histogram gives labels and real timestamp value both.
  2. Add a new function to determine if a given time value is within range.

**Comment by mh0203** [comment]
<img width="1024" alt="screen shot 2018-12-13 at 4 38 39 pm" src="https://user-images.githubusercontent.com/8232266/49923246-3afeff00-fef6-11e8-92a8-3f4c57ae3853.png">
