### ISSUE TITLE
 The heatmap chart is not rendered properly

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#102]
**Describe the bug**
히트 맵 차트가 정상적으로 표현되지 않는 경우가 있습니다.
- 열/행 차원값 1개씩, 측정값 1개 인경우 Y 축 최상단에 추가적인 열이 생성됩니다. (Screenshot 1)
- Data Lable/ToolTip 설정시 Preview 와 일치하지 않습니다. (Screenshot 1)
- 열 차원값 1개, 측정값 1개 인경우 X/Y 축에 불필요한 열/행이 생성됩니다. (Screenshot 2)

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Create Chart'
3. 위 설명에 나오는 오류나는 조건에 따라 선반위치 (2건)

**Expected behavior**

**Screenshots**
(1)
![image](https://user-images.githubusercontent.com/822255/44888022-ffa34080-ad09-11e8-8ff3-306a0ea05f27.png)

(2)
![image](https://user-images.githubusercontent.com/822255/44888090-4d1fad80-ad0a-11e8-914f-4b44ae2677dc.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser : Chrome
 - Version : 68.0

**Additional context**
@esezin 선반 조건 및 데이터 레이블 및 툴팁 표시 방식 점검이 필요합니다.

**Comment by kyungtaak** [comment]
@eltriny f#102-heatmap_not_rendered 브랜치에 서버 처리 오류 수정해두었습니다.

**Comment by kyungtaak** [comment]
@metatron-app/design 해당 이슈관련해서  선반 조건 및 데이터 레이블 및 툴팁 표시 방식 점검요청을 드렸는데요.
아직 답변이 없어 @juheeko9 님께서 올리신 PR건을 취소하였습니다.

**Comment by AnnieHwang** [comment]
@juheeko9 @kyungtaak  해당 내용 점검이 늦어 죄송합니다. 다시 PR을 올려주시고 Reviewer를 design팀으로 지정해주시면 점검 후 피드백 달겠습니다.

**Comment by esezin** [comment]
@kyungtaak @AnnieHwang 
기획적인 측면에서의 선반 조건과 표시 방식 자체는 문제가 없음을 확인하였습니다.
