### ISSUE TITLE
Messages not translated in Korean

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#1036]
**Describe the bug**
웹브라우져 한글 설정을 해 놓았지만, 영문으로 보여지는 곳이 있습니다.

**To Reproduce**

**Expected behavior**

**Screenshots**
1. 데이터소스 > 상세 > 모니터링
![_ _](https://user-images.githubusercontent.com/6300003/49621100-2064eb80-fa07-11e8-91a1-e73d428b6a0b.JPG)

2.데이터소스 > 생성 (Staging DB)
![_ staging db](https://user-images.githubusercontent.com/6300003/49621111-2bb81700-fa07-11e8-96a7-6131b06f30e8.JPG)

3.데이터소스 > 생성
![_ _1](https://user-images.githubusercontent.com/6300003/49621116-2eb30780-fa07-11e8-98b1-63832b8318fd.JPG)

4. 데이터소스 > 생성
![_ _2](https://user-images.githubusercontent.com/6300003/49621131-3c688d00-fa07-11e8-8819-07fa86755929.JPG)

5. 데이터플로우 > 룰_extract
![_ _extract](https://user-images.githubusercontent.com/6300003/49621150-5013f380-fa07-11e8-9277-7c4089ac849a.JPG)

6. 데이터플로우 > 룰_split
![_ _split_0](https://user-images.githubusercontent.com/6300003/49621158-599d5b80-fa07-11e8-900d-e964b99c976f.JPG)

7. 데이터플로우 > 룰_split
![_ _split_1](https://user-images.githubusercontent.com/6300003/49621174-64f08700-fa07-11e8-8360-f471e34a8241.JPG)

8. 데이터플로우 > 룰_Union
![_ _union_00](https://user-images.githubusercontent.com/6300003/49621188-6fab1c00-fa07-11e8-9055-008b0b451d46.JPG)

9. 데이터플로우 > 스냅샷 생성
![_](https://user-images.githubusercontent.com/6300003/49621197-7a65b100-fa07-11e8-91e9-fa206330e970.JPG)

**Desktop (please complete the following information):**

**Additional context**

**Comment by brandon-wonjune** [comment]
f#1036-translate_message_to_korean 브랜치 생성하였습니다
