### ISSUE TITLE
Improve legend design in map view

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#1047]
**Is your feature request related to a problem? Please describe.**
맵뷰 범례 영역이 너무 커서 맵차트를 보기가 힘듭니다.
위치와 스타일 조정이 필요하며,
다른 차트와 동일하게 범례를 껐을때 레이어가 없어지는 등의 UX결을 맞춰야 할 것 같습니다.

**Additional context**
![image](https://user-images.githubusercontent.com/6300003/49634175-48704100-fa3f-11e8-84fd-02952f6583c0.png)
![image](https://user-images.githubusercontent.com/6300003/49634236-70f83b00-fa3f-11e8-9e48-e0f10bffcef5.png)

**Comment by esezin** [comment]
@kyungtaak @AnnieHwang 

당 이슈에 대해서는 두 가지로 접근하려 합니다. 
1. 여백 등을 최소로 하여, 범례 레이어의 디자인 자체를 최대한 더 작게.
2. 대시보드에서 접기 기능을 두어, 사용자의 필요에 따라 fold/unfold할 수 있도록. (숨기는 것이 아니라 접어두는 것)
3. 대시보드에서 드래그 기능을 두어, 사용자의 필요에 따라 위치를 옮길 수 있도록. (대시보드에 옮긴 위치가 저장되지는 않음)

3번에 대해서는 구현 가능성을 검토 중입니다만, 최소 1,2번은 개선되어야 할 것으로 생각합니다.
그리고 조금은 별건입니다만, 기존 Openstreet맵 뿐아니라, 다른 맵타일을 사용하게 될 경우, 지도내 UI(줌인아웃 등)의 위치를 특정할 수 없기 때문에, 범례 위치를 우측상/하단 뿐 아니라 좌측 상/하단도 사용할 수 있도록 하였습니다.

관련 기획서를 업데이트 하였으니, 참고 부탁드립니다. (해당 페이지 31,32)

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다
- 범례 여백 최소화, 투명도 90% 
- 범례 접기/펴기 버튼 추가 (범례위치에 따라 범례버튼은 맵뷰의 좌측상,하단, 우측 상,하단에 위치) 
![image](https://user-images.githubusercontent.com/42256760/49909408-256fe200-fec2-11e8-930a-f5c9721fe101.png)

**Comment by eltriny** [comment]
@kyungtaak @AnnieHwang
위 내용대로 진행해도 되는지 확인 부탁드립니다.

**Comment by AnnieHwang** [comment]
@eltriny 디자인 조금만 더 손보고 다시 @koeun222 님이 올려주실꺼예요.

**Comment by esezin** [comment]
@kyungtaak @AnnieHwang 
가장 급한 fold/unfold기능 + 변경된 디자인 뷰를 적용하는 것으로 이 이슈는 정리하고, 드래그 기능은 분리해서 진행하는 것이 어떨까 합니다.

**Comment by kyungtaak** [comment]
@esezin 네 좋습니다. 시간되실때 별도로 이슈등록 부탁드립니다.

**Comment by juheeko9** [comment]
f#1047-improve_legend_map 브랜치 생성하였습니다.

**Comment by alchan-lee** [comment]
fixed in #1093
