### ISSUE TITLE
No preview of Geo type values for linked data

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#1049]
**Is your feature request related to a problem? Please describe.**
연결형 데이터로 Geo 컬럼 생성시 데이터 미리보기를 지원하지 않습니다.
이에 따라 데이터값 노출 영역에 가이드문구 노출이 필요합니다.

![creategeopointcolumn](https://user-images.githubusercontent.com/42257766/49634475-2a571080-fa40-11e8-9ee9-d7ffa868105c.png)
![datagrid](https://user-images.githubusercontent.com/42257766/49634477-2cb96a80-fa40-11e8-8850-b66a21e20dc4.png)

Geo컬럼 미리보기를 지원하지 않는 경우는 2가지 상황이 있습니다.
1. Geo 의 Expression타입으로 생성할 경우
2. 연결형 데이터에서 Geo 타입으로 생성할 경우

1번의 상황은 이미 적용되었고 2번의 상황에 대한 적용이 필요합니다.

**Comment by deidera08** [comment]
@AnnieHwang  @brandon-wonjune 
Data미리보기를 지원하지 않는 경우 row를 병합하기 어려워 다음과 같이 개선하였습니다.
![스크린샷 2019-03-11 오후 4 16 15](https://user-images.githubusercontent.com/42257766/54106339-1e9d3080-4419-11e9-98fa-c8b6d50a2016.png)

**Comment by koeun222** [comment]
@AnnieHwang 디자인공유드립니다- 
1. "no preview" font color #b6b9c1
2. 공통 가이드 문구 노출 info (2개이상 뜰경우 마진 4px) 

데이터소스 > 상세(data grid) 
![image](https://user-images.githubusercontent.com/42256760/54109274-8f484b00-4421-11e9-879f-534c0c389d35.png)
데이터소스 > 생성 > 스키마설정 팝업
![image](https://user-images.githubusercontent.com/42256760/54109418-f1a14b80-4421-11e9-847a-0457a8443733.png)

**Comment by brandon-wonjune** [comment]
@kyungtaak 이 이슈 진행중 문의드립니다.
데이터저장소 > 데이터소스 상세화면 > 데이터 미리보기 화면에서 두가지 상황에 대해 서로 다른 api를 사용중에 있습니다.
![스크린샷 2019-03-11 오후 7 34 17](https://user-images.githubusercontent.com/42233627/54117775-e1df3280-4434-11e9-8556-ea0a943ed338.png)
```
// engine형 데이터소스의 경우 데이터조회시
api/datasources/query/search

// link형 데이터소스의 경우 데이터조회시
api/connections/query/data?extractColumnName=false
```
그런데 우측 상단에 row수를 수정하면 데이터를 새로 조회하는데 아래의 api를 사용하고있습니다.
```
api/datasources/query/search
```
새로 조회시 engine형일때는 제대로 조회가 되나 link형일때는 조회되지 않습니다.
다른 api를 사용해야되나요?

**Comment by kyungtaak** [comment]
@brandon-wonjune 답변드립니다. 
Q1. 데이터소스상세 조회시 includeUnloadedField 파라미터에 true 로  전달해 주시면 됩니다. 
Q2. limit 이라는 파라미터가 있어요. 기본값이 50 이네요. 이걸 조정해주시면 될것 같습니다.
