### ISSUE TITLE
Error search query including timestamp filter on map widget

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1055]
**Describe the bug**
Within the Map Widget, the search query is passed through geo server. 
An error occurs when you add a filter to a column of type timestamp in query.

**To Reproduce**
1. Go to dashboard linked datasource including geo related column
2. Create map widget on dashboard
3. Put on geo related column on shelf
4. Add timestamp type of column on filter
5. Click to 'Specific'

**Expected behavior**
It should be displayed to the specified filter conditions without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/49698710-b0bf4e00-fc0a-11e8-88f8-478f581d63c9.png)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
Fix with derived errors as below.
- Default Timestamp value did not set
![image](https://user-images.githubusercontent.com/822255/49698684-6e960c80-fc0a-11e8-9bdb-108f49d484d5.png)

- Mismatch end date time and date time of date picker component
![image](https://user-images.githubusercontent.com/822255/49698679-5faf5a00-fc0a-11e8-9093-b8557159cbc9.png)

**Comment by dave-taeho** [comment]
@kyungtaak 
맵차트의 경우 저희가 http://52.231.184.135:8180 서버를 바라보고 작업을 하고 있습니다.
다른 Testbed를 통해서라도 1055번 브랜치를 올려주실 수 있을까요?

**Comment by alchan-lee** [comment]
@dave-taeho 
해당 브랜치를 http://52.231.184.135:8180 이 쪽에다가 배포해두었습니다.

**Comment by kyungtaak** [comment]
#1060 오류도 함께 처리해두었습니다.
