### ISSUE TITLE
Problem with settings the mandatory filter in the link-type datasource

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1056]
**Describe the bug**
링크 형태의 데이터 소스를 대시보드 연결시 필수 필터 편집 화면에 필수 필터 내 항목을 가져오는데서 오류가 발생합니다.  

**To Reproduce**
(기존에 DB > Linked datasource 가 생성되었다고 가정합니다.)
1. 대시보드 생성시 링크 데이터 소스 연결 > 링크 데이터 소스 적재 작업 수행 완료
2. 연결된 데이터 소스를 클릭하면 하단에 데이터 소스 정보가 나타나는데 "필수 필터" 탭 선택
3. 탭 화면내 "수정" 버튼클릭

**Expected behavior**
필수필터 내 항목을 가져올때 오류가 발생하지 않아야 합니다. 

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/49704571-d58de280-fc57-11e8-83d9-71278eb249d2.png)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
@metatron-app/design 
1. 데이터소스 관리 항목에서 필수 필터 지정후 저장시 아래와 같은 문구가 나타나는게 정상인지 확인이 필요합니다.
![image](https://user-images.githubusercontent.com/822255/49704615-85fbe680-fc58-11e8-86d0-56e911816ede.png)

2. 링크 데이터 소스 생성 직전 필수필터 지정시 아래와 같이 All 항목이 반드시 있어야하는지요?
![image](https://user-images.githubusercontent.com/822255/49704633-b80d4880-fc58-11e8-80d6-05501ef545d2.png)

**Comment by AnnieHwang** [comment]
@kyungtaak 
1. 필수필터를 저장한다고 해서 재적재는 되지 않기 때문에, 
Title : 필수필터를 저장/변경하시겠습니까?
Sub-title : (없음)
로 변경하는게 나을 것 같습니다.
2. All항목은 필요없는것 같습니다. 기획서에도 제가 All항목 없음을 확인했었던 것 같은데 @minjung-cho 재 확인 부탁드립니다.

 @deidera08 괜찮으신지 여부 답변 부탁드려요~

**Comment by deidera08** [comment]
@AnnieHwang 
넵 기획서에 문구 수정반영 하겠습니다.

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
현재 ingested data의 경우 Alert 없이 저장완료 toast 노출되고 있습니다.
linked data가 실제 재적재되지 않는다면  Alert 자체를 삭제하고 ingested data와 마찬가지로 단순 성공 toast로 노출시겠습니다.
(기획서 수정하도록 하겠습니다)

**Comment by AnnieHwang** [comment]
@kyungtaak @deidera08 @minjung-cho 다시고민해보니 제가 위에 적은 내용과 바뀐 의견이 있어서 답글을 답니다.
1. Linked datasource인 경우, 데이터소스 상세 상에 필수필터컬럼 설정이 바뀌더라도 ingestion에 영향이 없음으로 Ingested datasource와 동일하게 UX를 처리하면 될것 같습니다. (**알럿 제거**)
2. (All)은 아니라더라도 (None)은 있어야 할것 같습니다. 필수필터의 경우 순서가 있어서, 상위 순서에서 선택한 값에 의해 하위 값이 선택되어야 하는데 선택할 값이 없는 경우가 발생할 수 있습니다. @minjung-cho 해당 부분에 대한 기획 내용이 보강되어야 할것 같습니다.


@kyungtaak 해당 이슈 재현해보면서 오류를 발견하였는데, Ingested datasource에서 필수필터컬럼이 있는경우, 대시보드 편집에서 필수필터컬럼의 첫번째 Row가 선택되어 지는데.. 현재 오더링이 예전과 바뀌어서 첫번째 Row가 선택되지 않고 있습니다. 해당 부분 첫번째 Row가 선택되도록 변경 요청드립니다.
![image](https://user-images.githubusercontent.com/6300003/49850505-0ec57e80-fe21-11e8-9286-16b4ec0c9e0f.png)

**Comment by minjung-cho** [comment]
@AnnieHwang 

> 2. (All)은 아니라더라도 (None)은 있어야 할것 같습니다. 필수필터의 경우 순서가 있어서, 상위 순서에서 선택한 값에 의해 하위 값이 선택되어야 하는데 선택할 값이 없는 경우가 발생할 수 있습니다. @minjung-cho 해당 부분에 대한 기획 내용이 보강되어야 할것 같습니다.

상위에서 필터링되어서 선택할 수 있는 값이 없을 경우, '선택할 수 있는 값이 없습니다'라는 문구를 보여주는 것이 어떨지요?

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다 
![image](https://user-images.githubusercontent.com/42256760/49982566-8cfc5f00-ffa0-11e8-88ce-b3927c245cfa.png)
