### ISSUE TITLE
Support granularity automation on ingestion stage

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1058]
**Is your feature request related to a problem? Please describe.**
현재 데이터 적재 단위인 granularity 지정시 고정된 설정으로 지정하게 됩니다. granularity 에 생소한 사용자들은 기본 설정으로 지정하여 druid 내 공간/성능에 이점을 누리지 못할 가능성이 있습니다. 이에 대해 일반적인 granularity 규칙을 넣어, 사용자가 조금이나마, granularity 를 편리하게 지정할수 있도록 자동화 할 필요성이 있습니다. (MT-38)

**Describe the solution you'd like**
- 아래 처럼 timestamp field 의 포맷을 인식하여 보편적인 Granularity 자동화 규칙을 적용합니다.
![image](https://user-images.githubusercontent.com/822255/49706613-37574800-fc6a-11e8-95fe-b7137dedfdc6.png)
- 실시간 데이터소스 질의시 필요하여 Query granularity에  Second 단위를 추가합니다. 

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by brandon-wonjune** [comment]
f#1058-granularity_automation_in_ingestion 브랜치 생성하였습니다
