### ISSUE TITLE
Set type constraint according to the type of original column and role classification

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1059]
**Is your feature request related to a problem? Please describe.**
사용자가 데이터 적재시 실수를 방지하기 위하여 Role 구분/원본 데이터의 타입에 따른 타입 지정 제약이 필요합니다.

**Describe the solution you'd like**
Role 구분에 따른 타입 지정 제약
- Timestamp Role 
  -- Date/Time Type 외  Select box를 비활성화 및 가이드 문구를 노출
![image](https://user-images.githubusercontent.com/822255/49707123-41c71100-fc6d-11e8-9843-91cf19696d93.png)

- Dimension Role
  -- 기본적으로 String, Boolean, Latitude, Longitude, Date/Time 로 변경가능
  -- 원본이 data type 이 String 인 경우 Geo related type (GEO_POINT, GEO_LINE, GEO_POLYGON) 으로 변경 가능, WKT(https://en.wikipedia.org/wiki/Well-known_text) 케이스
  -- (+) 로 지정된 GEO_POINT 타입의 경우 타 타입으로 변경이 불가, Expression 으로 지정된 컬럼의 경우, 기본값을 String 으로 지정  

- Measure Role
-- Integer, Decimal만 허용 (숫자연산이 가능한 값). String 등의 타입으로 변경 가능하나 변경시 role이 Dimension으로 자동 변경

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by deidera08** [comment]
@kyungtaak 
질문이 있습니다. 

1. Create datasource > Configure schema화면 진입시
데이터값에 따른 role과 type을 자동으로 판단하여 기본적으로 적용될 수 있는지요?

2. Geo Expression인 경우 컬럼타입이 String이 되면 해당 컬럼은 Datasource > Column Detail에서 String이 되어야할까요?
(즉 Create datasource 완료 이후 UI에서는 Expression 타입이 없는건가요?)

**Comment by brandon-wonjune** [comment]
@kyungtaak 작업중 문의드립니다.
원본 타입이 string이라는 것은 필드의 속성중 type이 STRING인 것을 의미하는것인가요?

**Comment by kyungtaak** [comment]
@brandon-wonjune 네 맞습니다. GEO 데이터를 표현하는 WKT 타입은 STRING 으로 되어 있어요.

**Comment by brandon-wonjune** [comment]
@kyungtaak @deidera08 
위 내용적용하였습니다.

1. 원본의 type이 STRING인 경우 
logicalType에서 GEO 타입이 선택이 가능
![2018-12-19 1 13 42](https://user-images.githubusercontent.com/42233627/50198724-2906db80-0390-11e9-94ec-0e08e799d490.png)
![2018-12-19 1 13 50](https://user-images.githubusercontent.com/42233627/50198760-5f445b00-0390-11e9-866f-defe543517b8.png)


2. 타임스탬프로 지정된 컬럼의 경우 아래와 같은 문구가 표시
![2018-12-19 1 13 15](https://user-images.githubusercontent.com/42233627/50198734-3754f780-0390-11e9-82f5-ba7845d2ee4a.png)
![2018-12-19 1 13 56](https://user-images.githubusercontent.com/42233627/50198737-3cb24200-0390-11e9-8b9f-3e65ef9a84fe.png)

3. add column을 통해 생성된 GEO타입과 표현식의 경우 아래와 같은 가이드 문구 표시
![2018-12-19 1 13 26](https://user-images.githubusercontent.com/42233627/50198748-4c318b00-0390-11e9-973e-d091c61b3900.png)
![2018-12-19 1 13 59](https://user-images.githubusercontent.com/42233627/50198755-55baf300-0390-11e9-8d2a-8fbd81928f5c.png)

**Comment by alchan-lee** [comment]
fixed in #1240
