### ISSUE TITLE
Gradient color of gauge chart is incorrect

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#106]
**Describe the bug**
Gauge chart 에서 Gradient mode 로 색을 선택하면 값에 따른 색 설정에 비해서 실제 부여된 색이 잘못됨
스크린샷 참조

**To Reproduce**
1. Go to 'https://discovery.metatron.app/app/v2/workbook/ceb82f31-9a99-44e2-83a0-7edbfcbd4067'
2. Gauge chart 참조

**Expected behavior**
현재 색의 표현이 offset 기준 으로 표현되고 있으나 칸의 크기로 표현되는 것이 맞음

**Screenshots**
<img width="1551" alt="gauge-chart-gradient-error" src="https://user-images.githubusercontent.com/526622/44895868-30e33700-ad31-11e8-9190-17c776582b29.png">

**Desktop (please complete the following information):**
demo site(3.0.1)

**Additional context**

**Comment by dave-taeho** [comment]
#106-gauge_chart_gradient_incorrect 브랜치 추가되었습니다.

**Comment by kyungtaak** [comment]
@dave-taeho default mode 도 추가확인후 PR 리오픈 해주세요.

**Comment by dave-taeho** [comment]
@kyungtaak #248 PR에 올렸던 내용이 정상적으로 반영되지 않았습니다.
로컬에서는 @ecoloy께서 제기하신 사항들이 재현되지 않음을 확인하였습니다.
![2018-09-18 10 57 25](https://user-images.githubusercontent.com/14234215/45660022-f8659a80-bb31-11e8-872a-60eb5dcb279d.png)
![2018-09-18 10 58 03](https://user-images.githubusercontent.com/14234215/45660028-fc91b800-bb31-11e8-869a-70865d63ce47.png)

**Comment by kyungtaak** [comment]
@dave-taeho 아.. 그 이슈였군요. 다시 PR 리오픈 해주시면 확인하도록 하겠습니다.
