### ISSUE TITLE
feature req: ldap authentication for ui logon

### ISSUE THREAD

**Issue by tooptoop4** [metatron-app/metatron-discovery#1061]
Right now am logging into the metatron ui with admin user. Would be great if the login page could bind to ldap/activedirectory so that only valid users can login to metatron ui, ideally with ability to specify only few valid activedirectory groups that you must be a memberof in order to login.

**Comment by tooptoop4** [comment]
@kyungtaak gentle ping, any idea which classes would need to change for this?

**Comment by brucemen711** [comment]
@kyungtaak , @tooptoop4  any plan for this ?
Currently, so many bigdata technology based on LDAP database user, i think metatron should too.
