### ISSUE TITLE
Maintain search result list view after moving to detailed view

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1062]
**Is your feature request related to a problem? Please describe.**
In all current list views in discovery, if you navigate to the detail view from the list screen with search conditions and then come back, the search results will not be maintained. This can be an inconvenience to the user. (MT-167)

**Describe the solution you'd like**
It should be maintained search result list view after moving to detailed view.

**Describe alternatives you've considered**
Since a common policy applies, you need to understand the impact of the entire list view.

**Additional context**
(N/A)

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang Please check the target views.

@eltriny After selecting the target views from @metatron-app/design, please calculate the development time.

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang @minjung-cho 
사실상 (필터)검색이 있는 모든 화면으로 보시면 좋을듯 합니다.
우선순위를 둬서 적용해나가면 좋을듯한데 WORKSPACEE > MANAGEMENT > ADMINISTRATOR 순으로 생각하고 있습니다.
상위 depth로 이동시 필터가 초기화 되지만 동일 depth나 하위depth로 이동시 기억하는것으로 룰을 잡으면 어떨까 합니다.
(내가 자주쓰는 필터로 항상 세팅되는 경우는 Preset기능이며 이것과는 다른 이슈인듯 합니다.)

상위 depth로 이동 예시
- 로그아웃 등 서비스를 이탈하는 경우
- 1depth간 이동시 
(예. Workspace에서 Datasource로 이동시)

동일 depth로 이동 예시
- 뒤로가기 
- 2depth간 이동시
(예. Metadata <> Code Table로 이동시)

하위 depth로 이동 예시
- 2depth메뉴에소 3depth로 이동시
(예1. Datasource <> information으로 이동시)
(예2. metadata > Create metadata > metadata로 되돌아올 경우)




아래는 필터 검색이 있는 화면 목록입니다.

1. Workspace (display type포함)
![dashboard](https://user-images.githubusercontent.com/42257766/49718512-a601c900-fc9d-11e8-9b68-76997257fc49.png)

2. Management > Metadata
- Metadata
- Column Dictionary
- Code Table

3. Management > Data Storage
- Datasource
- Data Connection

4. Management > Data Preparation
- Dataset
- Data Snapshot

5. Management > Notebook Management
- Notebook Server 

6. Management > Data Monitoring
- Log Statistic
- Job Log

7. Administration > Users
- Membership Approval
- Members
- Groups

8. Administration > Workspaces
- Workspace
- Permission schemas

**Comment by deidera08** [comment]
> 상위 depth로 이동시 필터가 초기화 되지만 동일 depth나 하위depth로 이동시 기억하는것으로 룰을 잡으면 어떨까 합니다.
> (내가 자주쓰는 필터로 항상 세팅되는 경우는 Preset기능이며 이것과는 다른 이슈인듯 합니다.)
> 
> 상위 depth로 이동 예시
> 
> * 로그아웃 등 서비스를 이탈하는 경우
> * 1depth간 이동시
>   (예. Workspace에서 Datasource로 이동시)
> 
> 동일 depth로 이동 예시
> 
> * 뒤로가기
> * 2depth간 이동시
>   (예. Metadata <> Code Table로 이동시)
> 
> 하위 depth로 이동 예시
> 
> * 2depth메뉴에소 3depth로 이동시
>   (예1. Datasource <> information으로 이동시)
>   (예2. metadata > Create metadata > metadata로 되돌아올 경우)

위의 룰은 무시해주세요. 사용자를 더욱 혼란하게 만들 여지가 있는 것 같아 삭제하도록 하겠습니다.

**Comment by minjung-cho** [comment]
공통 UX 문제로 이슈화 되었으나, 아래의 유즈케이스에 한해서 적용하기로 협의되었습니다. (깃에 히스토리가 없어서 기록차 남깁니다 ^^)
- Management/Administration > 목록(필터링) > 상세 > 목록(최근 필터링 유지)

아울러 페이지네이션 UI를 추가하여 콘텐츠가 많아졌을때 목록 불러오기가 불편했던 부분도 개선하고자 합니다. @AnnieHwang 아래 기획서 검토 부탁드립니다.
<img width="1073" alt="2019-01-15 1 20 30" src="https://user-images.githubusercontent.com/28773903/51165906-090dfd80-18e5-11e9-9566-aa5543e79d0d.png">

**Comment by koeun222** [comment]
@AnnieHwang 페이지 네비게이션 디자인 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/51222120-a4ec4780-197f-11e9-83ad-f9b9a7101908.png)

**Comment by kyungtaak** [comment]
@AnnieHwang @metatron-app/design 기획/디자인 감사합니다. 다음 이터레이션에서 개발을 진행하도록 하겠습니다.

**Comment by minjung-cho** [comment]
@kyungtaak @AnnieHwang @eltriny 
오래된 이슈라, 브라우저 Back키 이벤트에 대해서 그동안 고민을 해보았습니다. 일전에 @deidera08  님이 코멘트 주신 것도 그 내용의 일부입니다.

하지만, 글로벌로 적용되는 부분이기에 처음에 여러 규칙을 두고 수정하는 것보다 사용하면서 불편한 부분을 개선해 나가는 쪽이 효율적일 것이라 판단이 되었습니다. 예외 규칙을 두었을 때 미처 생각지 못한 부분에서 사용자에게 혼란을 주는 상황이 발생할 가능성도 배제할 수 없어서요. 사설이 길었습니다 ^^; 

결론적으로 기획 정리한 내용 공유드립니다.
Manaement/Administrator 콘텐츠 목록에서 최근 필터링이 적용된 화면을 보여줄 것인지에 대한 정책입니다.
1. 브라우저 뒤로가기 시, 최근 검색 결과를 보여줌
    (e.g. 데이터소스 목록 검색 > 검색결과 확인 > 목록 클릭 > 상세 화면 확인 > 브라우저 뒤로가기 > 최근 검색결과 확인) 
2. 콘텐츠 상세 화면 UI의 뒤로가기 시, 최근 검색 결과를 보여줌
    (e.g. 데이터소스 목록 검색 > 검색결과 확인 > 목록 클릭 > 상세 화면 확인 > UI 뒤로가기 > 최근 검색결과 확인)
3. ‘뒤로가기’ 이외의 네비게이션 버튼으로 페이지 이동 시, 화면 refresh(최근 검색 결과 보여주지 않음)
    (e.g. 데이터소스 목록 검색 > 검색결과 확인 > 목록 클릭 > 상세 화면 확인 > LNB의 데이터소스 메뉴 클릭 > 초기상태의 데이터소스 목록이 보임)
@eltriny 추가 정의가 필요한 부분이 있다면 말씀주세요

우려되는 것은... 
브라우저 뒤로가기를 계속했을때, 사용 플로우에서 이미 벗어난 화면들(사용 당시 검색 결과 화면)이 펼쳐지는 상황입니다. 
<img width="1177" alt="2019-01-17 11 36 24" src="https://user-images.githubusercontent.com/28773903/51292013-a59edf80-1a4c-11e9-86b4-007f783c8ebb.png">
현재 초기 목록과 필터가 적용된 목록이 시각적으로 차이가 크지 않아서, 사용자가 필터가 적용된 화면을 초기 화면으로 착각하면 더 문제일것 같아서 1번 부분에 디자인을 수정하고, 2번에 검색결과임을 나타내는 문구로 변경하려고 합니다. @AnnieHwang 검토 의견 부탁드립니다

**Comment by minjung-cho** [comment]
추가 : 필터링, 정렬 상태가 변경되면 1페이지로 돌아가는 것이 좋을 듯 합니다-
