### ISSUE TITLE
500 error of search query in hexagon

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#1063]
**Describe the bug**
- 특정 datasource에서 맵차트를 그릴때 hexagon타입을 선택시 500에러가 발생합니다.

**To Reproduce**
1. 차트화면에서 맵차트를 선택합니다.
2. geo dimension을 선반에 올립니다.
3. layer type에서 hexagon을 선택합니다.
4. 500에러가 발생합니다.

**Expected behavior**
layer type이 hexagon일때에도 500에러가 발생하지 않아야 합니다.

**Screenshots**
![image 1](https://user-images.githubusercontent.com/3685833/49711740-68dd0d00-fc84-11e8-948d-12da1e0dd431.png)

**Desktop (please complete the following information):**
- OS: iOS 10.12
- Browser: chrome
- Version: 71.0

**Additional context**

**Comment by juheeko9** [comment]
[API]
POST api/datasources/query/search

[Request Body]
`{"context":{"discovery.route.uri":"/workbook/f248cf49-dd5c-44e2-91e8-91276b1ef6e1","discovery.dashboard.id":"d8b815ac-8655-4b43-be75-697ad153be6f"},"userFields":[{"oriColumnName":"","useChart":false,"useFilter":false,"useChartFilter":false,"type":"user_expr","role":"MEASURE","dataSource":"scmftmast_intc_20181127","alias":"MEASURE_1","name":"MEASURE_1","expr":"\"count\"","aggregated":false}],"dataSource":{"joins":[],"temporary":false,"id":"ds-lotte-01","name":"scmftmast_intc_20181127","uiDescription":"scmftmast_intc_20181126","type":"default","connType":"ENGINE","engineName":"scmftmast_intc_20181127"},"filters":[],"pivot":{"columns":[],"rows":[],"aggregations":[]},"shelf":{"type":"geo","layers":[[{"type":"dimension","name":"location","subType":"STRUCT","subRole":"DIMENSION","alias":"location","format":{"type":"geo_hash","method":"geohex","precision":10}}]]},"limits":{"limit":5000,"sort":null},"aliases":[{"type":"value","ref":"d8b815ac-8655-4b43-be75-697ad153be6f"}],"resultFormat":{"type":"chart","mode":"map","options":{"addMinMax":true,"showCategory":true,"showPercentage":true},"columnDelimeter":"―"}}`

[Return]
`{"code":"EG0001","message":"Fail to process response : Could not extract response: no suitable HttpMessageConverter found for response type [class com.fasterxml.jackson.databind.JsonNode] and content type [application/xml]","details":"RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class com.fasterxml.jackson.databind.JsonNode] and content type [application/xml]"}`

[참고화면]
![image](https://user-images.githubusercontent.com/42233502/49711794-bfe2e200-fc84-11e8-86d1-bdfcbc087707.png)
