### ISSUE TITLE
feature req: persist data connections so they can be restored after metatron process is restarted

### ISSUE THREAD

**Issue by tooptoop4** [metatron-app/metatron-discovery#1068]
If you login to metatron ui and setup some data connections ie jdbc url/user/pass for mysql/hive but then kill the metatron pid on linux and then restart metatron pid the data connection details have to be recreated from scratch. Ideally once a connection is created it can be saved to a file and then when metatron starts it can auto-import connections from that file.

**Comment by tooptoop4** [comment]
I used: ./bin/metatron.sh --init start

ps -ef shows:
java -Dfile.encoding=UTF-8 -Xms2048m -Xmx2048m -XX:MaxPermSize=512m -cp :/home/ec2-user/metatron-discovery-3.1.0-20181210041852/discovery-server-3.1.0.jar:/home/ec2-user/metatron-discovery-3.1.0-20181210041852/conf org.springframework.boot.loader.PropertiesLauncher --loader.system=true --spring.config.location=classpath:application.yaml --spring.profiles.active=h2-default-db,logging-console-debug,scheduling,local,initial

**Comment by YooYoungmo** [comment]
@tooptoop4 `--init` deletes and initializes existing data.
Therefore, it should be used only when the Metatron is first run.
Run without `--init` arg

**Comment by kyungtaak** [comment]
@YooYoungmo Thanks for the reply. :) 
I think many users are confused about "--init". I will add this part to the readme.

**Comment by kyungtaak** [comment]
Today we will update readme file(#1067). so, I'll close this issue.
