### ISSUE TITLE
Support setting custom color for layer in map view

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#1069]
**Is your feature request related to a problem? Please describe.**
- 맵차트 color by measure의 사용자 색상 설정 기능을 추가합니다.

**Additional context**
![image](https://user-images.githubusercontent.com/3685833/49778504-e407f700-fd48-11e8-9f5e-bd2fdab78c67.png)

**Comment by juheeko9** [comment]
f#1069-custom_color_setting_map 브랜치 추가하였습니다.

**Comment by AnnieHwang** [comment]
@eltriny 이미 머지 되었긴 했는데.. 이상한 점이 있어서요

숫자가 길 경우 앞이 짤리는데.. 인풋박스 앞과 뒤 여백을 좀 줄이고 뒷 숫자부분에 (… 말 줄임) 추가해주세요
![image](https://user-images.githubusercontent.com/6300003/49931668-bc608c80-ff0a-11e8-9088-09732a174c69.png)

**Comment by koeun222** [comment]
@eltriny 인풋박스 마진 6px & 숫자뒷부분 말줄임 적용 부탁드려요
![image](https://user-images.githubusercontent.com/42256760/49977920-93cca700-ff8b-11e8-8de2-9564cd68dfc6.png)

**Comment by juheeko9** [comment]
@AnnieHwang 

> 숫자가 길 경우 앞이 짤리는데.. 인풋박스 앞과 뒤 여백을 좀 줄이고 뒷 숫자부분에 (… 말 줄임) 추가해주세요

해당건은 #1047 에서 이어서 처리하겠습니다.

**Comment by juheeko9** [comment]
@AnnieHwang 

> 숫자가 길 경우 앞이 짤리는데.. 인풋박스 앞과 뒤 여백을 좀 줄이고 뒷 숫자부분에 (… 말 줄임) 추가해주세요

#1047 이슈에서 이어서 진행하겠습니다.
