### ISSUE TITLE
Change user guide from pdf to web link

### ISSUE THREAD

**Issue by alchan-lee** [metatron-app/metatron-discovery#1076]
**Is your feature request related to a problem? Please describe.**
We give a download link for user guide into LNB.
It is always frustrated when release new feature, hard to give recent information to user.

**Describe the solution you'd like**
So, I change this to web link which is updated regularly.

**Additional context**
It will link to https://metatron.app/index.php/documents/

**Comment by alchan-lee** [comment]
@metatron-app/design 
T Map 오픈시에 요청에 따라 별도 브랜치를 통해서 급하게 제공한 내용인데요.
T Map 외 정규 브랜치에도 해당 내용 적용을 해도 되는지 검토 부탁드립니다.

![image](https://user-images.githubusercontent.com/42234141/50066984-0941ad00-0202-11e9-8d3b-97287ddb523d.png)

**Comment by kyungtaak** [comment]
@alchan-lee 진행해주세요.

**Comment by minjung-cho** [comment]
LNB에 버전 정보와 홈페이지 가이드 링크가 들어가서 정보 재배치를 다시 했습니다. 
![2019-01-08 10 50 17](https://user-images.githubusercontent.com/28773903/50804990-c4f28a00-1333-11e9-8501-440c51da060b.png)

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/50815587-fd5c8d00-1360-11e9-9149-0bff41f96145.png)
수정된 디자인 공유드립니다

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/50816071-c5eee000-1362-11e9-8aeb-9b8acd314e19.png)
수정된 안으로 디자인 공유드립니다

**Comment by kyungtaak** [comment]
@minjung-cho 이 이슈와 약간 다르지만..;; 이제야 보게 되었네요.. 
Data Manager 와 Administartor 는 어떤기준으로 보여줘야할까요? 저희 기능상 여러명이 될수 있을 텐데요.

**Comment by minjung-cho** [comment]
@kyungtaak 데이터관리자, 시스템관리자의 대표 이메일(고정 이메일 주소)이 보여지는 부분이었습니다.  오픈 소스 이후에 다시 생각해 본 적은 없습니다... @AnnieHwang 운영을 위한 페이지가 필요한 시점이 된 걸까요?

**Comment by AnnieHwang** [comment]
Contact에 Data manager 부분은 삭제 해주세요. 일단 그것만 제외하고 저 상태로 반영하는걸로 개발팀과 이야기 했습니다~
