### ISSUE TITLE
For Oracle / Tibero, there is no Limit reserved word Error occurred

### ISSUE THREAD

**Issue by steve-kyungjin** [metatron-app/metatron-discovery#1080]
**Describe the bug**
Datasource 생성시 Oracle / Tibero 의 경우 오류 발생.

**To Reproduce**
1. DB 타입으로 Datasource 를 생성한다.
2. 절차에 따라 생성한다.
3. 생성시 Limit 10000 이 쿼리에 붙어 특정 DB 에서 오류 발생.
    Oracle / Tibero는 Limit 예약어가 없음.

**Expected behavior**
정상적으로 Datasource 가 생성되어야 한다.

**Screenshots**
배치라 따로 화면이 없음.

**Desktop (please complete the following information):**
전 환경에서 발생.

**Additional context**

**Comment by kyungtaak** [comment]
@steve-kyungjin 리포트 감사합니다. 관련해서 향후 이슈 작성시 필요한 사항에 대해 말씀드리고, 이슈를 종료하겠습니다. 
1. 이슈와 관련없는 부분은  삭제해주세요. : 템플릿으로 생성한 부분 포함
2. 재현 케이스에 대해 상세히 작성해주세요. 
   "Datasource 생성시 Oracle / Tibero 의 경우 오류 발생." 은 누구도 알기 어렵습니다.

참고로, Oracle / Tibero 는 과거 지원했으나, 오픈소스로 전환하며 일단 제외하였습니다. 
내년(2019년) 1월 내로 extension 형태로 지원을 검토하고자 하오니 이후 확인 부탁드립니다.
