### ISSUE TITLE
 Error in displaying column header information in MySQL

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1081]
**Describe the bug**
- 아래 이미지 처럼 MySQL 데이터베이스에서 JOIN 등 쿼리 조합과 alias 설정 시에, 컬럼 결과를 출력해주는 헤더정보가 일정치 않음( . 앞에 DB명이 있는 경우와 없는경우 발생 등)
![header_error](https://user-images.githubusercontent.com/612173/49829441-c9c62b80-fdd1-11e8-9eda-3ae67b701029.png)

**Expected behavior**
- 하이브에서는 동일쿼리의 헤더가 정상 작동하며, 하이브 처럼 동작해야함

**Screenshots**
- 엑셀 다운로드 시에도 동일한 문제 발생
![excel_header](https://user-images.githubusercontent.com/612173/49829531-08f47c80-fdd2-11e8-891a-7630a68ac971.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : IE

**Comment by ufoscw** [comment]
데이터 소스 생성시 mysql의 컬럼명 중복케이스의 오류를 수정하는 중 발생한 side-effect로 파악되었습니다.
해당 오류 수정은 3.1.1 브랜치에 수정 반영되었습니다.
