### ISSUE TITLE
Download file or staging db snapshots as JSON files

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1086]
**Is your feature request related to a problem? Please describe.**
I would like to be able to download the contents of a snapshot as a JSON file.

_Snapshot의 내용을 JSON 파일로 받을 수 있으면 좋겠습니다._

**Describe the solution you'd like**
Now the JSON file snapshot has been implemented (https://github.com/metatron-app/metatron-discovery/issues/1074), so I would like to be able to download all the snapshot contents as a JSON file. In addition to FILE snapshots, I also want to make STAGING_DB snapshots downloadable as a CSV or JSON file.

_이제 JSON file snapshot이 구현되었기 때문에 (https://github.com/metatron-app/metatron-discovery/issues/1074) snapshot 내용을 JSON 파일로 download 받을 수 있으면 좋겠습니다. FILE snapshot 뿐만아니라, STAGING_DB 도 CSV 또는 JSON 파일로 받을 수 있게 하면 좋겠습니다._

**Additional context**
In fact, you can download JSON snapshots now (as a result of https://github.com/metatron-app/metatron-discovery/issues/1074). Although the name is .csv but, the contents are JSON. We are going to close snapshot downloading matters including STAGING_DB types in this issue.

_사실 현재 (https://github.com/metatron-app/metatron-discovery/issues/1074 의 결과로) JSON snapshot에 대해서도 download가 가능합니다. 비록 파일 이름은 .csv로 내려오지만, 그 내용은 JSON입니다. 본 이슈는 FILE 뿐만아니라 STAGING_DB snapshot도 아울러서 **snapshot download 기능**을 마감하고자 하는 이슈입니다._

**Comment by mh0203** [comment]
UI work required.
1. Add a JSON file download button in snapshot detail screen.
2. Add the "fileType" path variable for the snapshot download api.
    ex) /{ssId}/download?fileType=json

**Comment by sang-hee-lee** [comment]
@mh0203 
UI modified. Please check the server api. (staging_db type snapshot)
