### ISSUE TITLE
Support Druid SQL

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#1099]
**Is your feature request related to a problem? Please describe.**
Workbench에서 Druid SQL을 조회할 수 있는 기능

**Describe the solution you'd like**
- DataConnection 추가시 Druid Type을 추가.
- 데이터 조회를 위한 기능은 Druid JDBC를 이용(Druid에서 JDBC 옵션 enable)

**Describe alternatives you've considered**
-  Druid Data Connection은 단순히 Workbench를 위해서 만드는 DataConnection이기 때문에 Ingestion 설정 등에서는 나타나지 않아야 함

**Additional context**
- 초기에는 Workbench에 Druid SQL 기능 제공, 이후 제약 조건 등 구현

**Comment by ufoscw** [comment]
@babokim 
테스트하신 Druid는 Metatron Customizing된 Druid인가요?
아니면 Apache Druid인가요?

**Comment by babokim** [comment]
@ufoscw Metatron Customizing된 Druid인데 현재 배포된 버전은 아니고 Dev 브랜치 버전으로 테스트 했습니다. JDBC 지원을 위해 이슈 하나 패치한 버전입니다.
@navis 님에게 확인해보세요.

**Comment by deidera08** [comment]
@babokim @ufoscw @AnnieHwang 
다음과 같이 디자인 요청중입니다.

1. Workbench화면
![2019-02-07 3 54 23](https://user-images.githubusercontent.com/42257766/52395251-c066f000-2af0-11e9-9d51-9ee21fc094dc.png)

2. Create Data connection
![createdataconnection](https://user-images.githubusercontent.com/42257766/52395358-2d7a8580-2af1-11e9-8a04-4b608a97fc20.png)

3. Data connection Information
![dbconnectioninformation](https://user-images.githubusercontent.com/42257766/52395363-31a6a300-2af1-11e9-9591-35465b482032.png)

더불어 Data connection > list > filter > **DB type에 Druid 추가** 부탁드립니다.
![filter](https://user-images.githubusercontent.com/42257766/52395346-1b98e280-2af1-11e9-9464-c3f4478d0b86.png)

살펴보시고 보완해야 할 사항 있으면 가이드 부탁드립니다.

**Comment by koeun222** [comment]
@AnnieHwang @eltriny  파일은 마크업 담당자에게 전달했습니다- 

![image](https://user-images.githubusercontent.com/42256760/52609146-9e3deb00-2ebf-11e9-8be5-86d5f3691dc4.png)
(파일명 : ic_db_druid_b.svg)
적용화면 
- Workbench  > Scheme Information popup
- Create Data connection
- Data connection Information

![image](https://user-images.githubusercontent.com/42256760/52609134-98480a00-2ebf-11e9-9bf9-0221c643ad92.png)
(파일명 : ic_db_druid_w.svg)
적용화면
- Workbench

그리고 이 이슈내용은 아니지만 관련된 추가가이드도 함께 전달드립니다
DB type icon이 없는경우에는  custom icon으로 적용됩니다
![image](https://user-images.githubusercontent.com/42256760/52609367-66837300-2ec0-11e9-9ca3-ce947a874c68.png)

**Comment by alchan-lee** [comment]
3.2.0-rc2 버전에 포함되었습니다. 👍 
이슈를 종료합니다.
