### ISSUE TITLE
Exclude mismatched rows when create hive snapshot

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#110]
**Is your feature request related to a problem? Please describe.**
Hive에 스냅샷을 생성하려고 할 때 Type과 실내 데이터가 일치하지 않는 row가 존재하면 정상적인 스냅샷을 생성할 수 없음.

**Describe the solution you'd like**
Hive 스냅샷 생성 과정에서 mismatched로 설정된 데이터를 제거.

**Describe alternatives you've considered**

**Additional context**
snapshot 생성 결과에서 mismatched로 인해 변경된 row를 알려줘야 함.
mismatched 된 값을 어떤 값을로 대체 할 것인지 결정해야 함.

**Comment by mh0203** [comment]
Hive-ORC로 snapshot 생성하는 경우 mismatch/missing value가 있는 경우 해당 row를 결과에서 제외.

**Comment by joohokim1** [comment]
그런데 File snapshot인 경우mismatch, missing은 어떻게 처리되나요?

**Comment by mh0203** [comment]
File snapshot인 경우 전부 Column Type이 전부 String으로 변환됨으로 아래와 같이 적용됩니다.
missing > 공백으로 입력
mismatched > 변화 없이 내용이 그대로 입력됨
