### ISSUE TITLE
Sorting error in gauge chart

### ISSUE THREAD

**Issue by juheeko9** [metatron-app/metatron-discovery#1104]
**Describe the bug**
게이지차트의 오름차순 / 내림차순의 미동작 에러를 해결합니다.

**To Reproduce**
1. 차트화면에서 게이지차트를 선택합니다.
2. 선반에 diemsnion / measure를 각각 하나씩 올립니다.
3. measure의 오름차순 / 내림차순에 따라 차트가 정렬되는지 확인합니다.

**Expected behavior**
게이지차트의 정렬기능이 동작해야합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/42233502/50133470-0e206280-02cf-11e9-8682-d4cc3f82ee8e.png)

**Desktop (please complete the following information):**
 - OS: iOS 10.12
 - Browser : chrome
 - Version : 71.0

**Comment by juheeko9** [comment]
f#1104-sorting_error_gauge 브랜치 생성하였습니다.

**Comment by alchan-lee** [comment]
fixed into #1109
