### ISSUE TITLE
Support multi-layer on map view widget

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#1107]
**Is your feature request related to a problem? Please describe.**
- Develop Multi-Map chart layer configuration.

**Describe the solution you'd like**
- AS-IS : only one lay can be set
 TO-BE : Be able to add maximum three or remove the layer

**Describe alternatives you've considered**
- Do not able to change a layer, only the last created layer will be shown

**Additional context**
- no additional context

**Comment by choonglee170924** [comment]
@kyungtaak 
Layer 별 데이터 소스 설정을 할 수 있도록 스펙 변경 요청 드립니다

**Comment by kyungtaak** [comment]
@choonglee170924 다소 많이 바뀌었는데요. 괜찬을런지 모르겠습니다.
```
{
  "type": "page",
  "dataSource": {
    "type": "multi",
    "dataSources": [
      {
        "type": "default",
        "name": "datasource_name1"
      },
      {
        "type": "default",
        "name": "datasource_name2"
      }
    ]
  },
  "filters": [
    {
      "type": "include",
      "field": "f1",
      "valueList": [
        "v1",
        "v2",
        "v3"
      ]
    }
  ],
  "shelf": {
    "type": "geo",
    "layers": [
      {
        "name": "layer1",
        "ref": "datasource_name1",
        "fields": [
          {
            "type": "dimension",
            "name": "Geo1",
            "alias": "Geo1"
          },
          {
            "type": "dimension",
            "name": "region",
            "alias": "region"
          }
        ]
      },
      {
        "name": "layer2",
        "ref": "datasource_name2",
        "fields": [
          {
            "type": "dimension",
            "name": "Geo1",
            "alias": "Geo1"
          },
          {
            "type": "dimension",
            "name": "Geo2",
            "alias": "Geo2"
          },
          {
            "type": "measure",
            "name": "measure",
            "alias": "measure",
            "aggregationType": "NONE"
          }
        ]
      }
    ]
  },
  "chart": {
    "type": "map",
    ...
  }
}
```

**Comment by sting009** [comment]
@kyungtaak 
로컬에서 변경된 스펙으로 호출 시, 다음과 같은 서버에러가 나오는데 확인 요청드립니다. 

- request parameter 
![2019-02-13 4 06 20](https://user-images.githubusercontent.com/42328567/52694369-d0794680-2fac-11e9-93f4-2dc927347266.png)

- error log 
![2019-02-13 4 09 00](https://user-images.githubusercontent.com/42328567/52694403-f0a90580-2fac-11e9-9817-4c14a4ad2f35.png)
![2019-02-13 4 09 56](https://user-images.githubusercontent.com/42328567/52694411-facb0400-2fac-11e9-8d1d-144eda16390e.png)

디버그한 결과 restTemplate 호출하는 부분에서 에러가 발생합니다. 
GeoRepository.java (139 line)

로컬에서 호출 시, entity 값 
![image](https://user-images.githubusercontent.com/42328567/52694508-4382bd00-2fad-11e9-8106-24ba954dbd30.png)

**Comment by kyungtaak** [comment]
@sting009  다시 개발서버에 올려두었는데요. 계속 발생하나요?

**Comment by sting009** [comment]
로컬 에서 나온 에러와는 다른 케이스인데요. 현재 개발 서버쪽으로 변경 후
response가 400 Bad Request로 호출되는데 
해당 부분은 스펙 부분이 안맞아서 나오는거 아닐까 싶은데요. 캡쳐화면과 같이 호출한 스펙은 로컬과 동일합니다. 
확인 부탁드립니다. 

- request 
![image](https://user-images.githubusercontent.com/42328567/52758234-dde50e00-304a-11e9-85c6-6ba93e0a5f82.png)

**Comment by kyungtaak** [comment]
@sting009 지금어디로 테스트하고 계신지요? 그리고 layer spec 을 손보면서  hash type 에 대한 스펙도 변경하였습니다. (자주 변경되어 죄송합니다.;;) 
```
{
    "dataSource": {
        "type": "default",
        "name": "sales_geo"
    },
    "filters": [],
    "shelf": {
        "type": "geo",
        "layers": [
            {
                "name": "layer1",
                "ref": "sales_geo",
                "view": {                         // 원본 보기일 경우 view 값을 주지 않아도 됩니다. 
                    "type": "hash",
                    "method": "h3",
                    "precision": 5
                },
                "fields": [
                    {
                        "type": "dimension",
                        "name": "location",
                        "alias": "location"
                    },
                    {
                        "type": "measure",
                        "name": "Profit",
                        "alias": "AVG(Profit)",
                        "aggregationType": "AVG"
                    }
                ]
            }
        ]
    },
    "resultFormat": {
        "type": "chart",
        "mode": "map",
        "options": null,
        "columnDelimeter": "―"
    }
    ...
}

```

**Comment by sting009** [comment]
@sting009 넵, 현재 타켓은 52.231.184.135:8180 이쪽으로 테스트 한 내용입니다. 혹시 잘못된부분이 있을까요?

**Comment by choonglee170924** [comment]
@kyungtaak 
안녕하세요,

로컬에 geoServer 셋팅 후 

geoserver 에러 로그 입니다
`2019-02-15T11:43:35,266 ERROR [qtp277630005-15] org.geoserver.ows - 
org.geoserver.wfs.WFSException: Requested property: sales_geo.location.lat is not available for metatron:sales_geo.  The possible propertyName values are: [Category, City, Country, CustomerName, OrderID, PostalCode, ProductName, Quantity, Region, Segment, ShipDate, ShipMode, State, Sub-Category, ShipStatus, orderprofitable, SalesAboveTarget, latitude, longitude, Discount, Sales, SalesperCustomer, Profit, DaystoShipScheduled, ProfitRatio, count, SalesForecast, location.coord, location.lat, location.lon, DaystoShipActual, __time, __f1, __f2, __f3, __d1, __d2, __d3, __l1, __l2, __l3, __s1, __s2, __s3, __g1, __g2, __g3, __geometry]
	at org.geoserver.wfs.GetFeature.run(GetFeature.java:457) ~[gs-wfs-2.12.4.jar:2.12.4]
	at org.geoserver.wfs.DefaultWebFeatureService.getFeature(DefaultWebFeatureService.java:105) ~[gs-wfs-2.12.4.jar:2.12.4]
	at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:50) ~[gs-ows-2.12.4.jar:2.12.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]`

**propertyName 으로 인한 에러로 보입니다.
제가 propertyName 을 변경하면 geoServer에서 정상 작동합니다.**

현재 서버에서 geoServer로 request 호출을 확인해보면 body 값이 아래와 같습니다.
`2019-02-15 05:20:09.278 DEBUG [127.0.0.1-admin] [http-nio-8180-exec-6] a.m.discovery.domain.geo.GeoRepository   : Geo Server Query : <GetFeature xmlns:wstxns1="http://www.opengis.net/wfs" wstxns1:service="WFS" version="1.1.0" outputFormat="application/json" viewParams="druid:{&quot;type&quot;:&quot;view&quot;\,&quot;virtualColumns&quot;:[]\,&quot;dimensions&quot;:[]\,&quot;aggregators&quot;:[]\,&quot;postAggregators&quot;:[]}" maxFeatures="5000">
  <wstxns1:Query wstxns1:queryType="GeoQuery" typeName="metatron:sales_geo" srsName="EPSG:4326" xmlns:wstxns2="http://openstreemap.org" wstxns2:outputFormat="application/json">
    <PropertyName>sales_geo.location.lat</PropertyName>
    <PropertyName>sales_geo.location.lon</PropertyName>
    <PropertyName>sales_geo.location.coord</PropertyName>
    <Filter/>
  </wstxns1:Query>
</GetFeature>`

PropertyName 을 아래와 같이 변경 후 호출을 하게 되면 정상적으로 호출이 됩니다.
`2019-02-15 05:20:09.279 DEBUG [127.0.0.1-admin] [http-nio-8180-exec-6] a.m.discovery.domain.geo.GeoRepository   : Request to geoserver : POST, http://localhost:9090/geoserver/metatron/wfs > <GetFeature xmlns:wstxns1="http://www.opengis.net/wfs" wstxns1:service="WFS" version="1.1.0" outputFormat="application/json" viewParams="druid:{&quot;type&quot;:&quot;view&quot;\,&quot;virtualColumns&quot;:[]\,&quot;dimensions&quot;:[]\,&quot;aggregators&quot;:[]\,&quot;postAggregators&quot;:[]}" maxFeatures="5000">
  <wstxns1:Query wstxns1:queryType="GeoQuery" typeName="metatron:sales_geo" srsName="EPSG:4326" xmlns:wstxns2="http://openstreemap.org" wstxns2:outputFormat="application/json">
    <PropertyName>location.lat</PropertyName>
    <PropertyName>location.lon</PropertyName>
    <PropertyName>location.coord</PropertyName>
    <Filter/>
  </wstxns1:Query>
</GetFeature>`

확인 한번 부탁드립니다~
