### ISSUE TITLE
Null pointer error (or infinite waiting) when cannot connect to DB

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1108]
**Describe the bug**
I saw null pointer exception when I tried to load a W.DS based on a database type I.DS.
Moreover, if I try to clone it, the waiting does not end.

**To Reproduce**
1. Check the database connection is healty.
2. Import & wrangle a table.
3. Turn off the DBMS.
4. Load the W.DS. (restarting might be needed)
4. Or clone the W.DS.

**Expected behavior**
Null pointer exception and infinite waiting should be changed into showing a proper error message, like "Cannot connect the DB" or "Check the connection to DB."

**Screenshots**
![cannot connect to db](https://user-images.githubusercontent.com/42257727/50136868-8e00f980-02dc-11e9-9559-440e4261cc32.gif)
![2018-12-18 3 50 06](https://user-images.githubusercontent.com/42257727/50136879-9d804280-02dc-11e9-83fd-6ac95f2e1edd.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68.0.3440.106

**Additional context**
As you can see the screenshot above, the browser gets 500 before the inifite loop.

**Comment by ksparknot** [comment]
Not reproduced

**Comment by joohokim1** [comment]
Do not need to test more. It's probably caused by temporary state of F/E pages.
