### ISSUE TITLE
In the DataSource filter criteria, exclude the 'VOLATILITY' DataSource creator from the 'Creator' list.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#1112]
**Describe the bug**
In the DataSource filter criteria, exclude the 'VOLATILITY' DataSource creator from the 'Creator' list.

**To Reproduce**
1. Go to DataSource List
2. Click on Creator Criteria
3. See 'VOLATILITY' DataSource creator in list

**Expected behavior**
exclude 'VOLATILITY' DataSource creator in creator list

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by alchan-lee** [comment]
fixed in #1115
