### ISSUE TITLE
Workbench result tab not work properly.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#112]
**Describe the bug**
when execute multiple query on workbench, changing result tab does not work properly. .

**To Reproduce**
1. Go to Workbench
2. execute query
use polaris;
SELECT * FROM polaris.book;
use polaris;

3. change result tab serveral times.
4. "Result1" and "Result3" tab showed data grid.

**Expected behavior**
query result that has empty data just show message not grid.

**Screenshots**
NA

**Desktop (please complete the following information):**

**Additional context**
NA

**Comment by brandon-wonjune** [comment]
f#112-workbench_result_tab_bug 브렌치 생성하였습니다

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/45607841-01029600-ba8a-11e8-8378-eacd2bd9a529.png)
@brandon-wonjune "No data" 의 경우 serch / icon button / row 수 비노출 됩니다

**Comment by minjung-cho** [comment]
같은 문제가 재현됩니다  ㅠㅠ

**Comment by choonglee170924** [comment]
> 같은 문제가 재현됩니다 ㅠㅠ

쿼리 에러 발생할 경우 불필요한 Icon 및 검색창 부분 수정완료 했습니다~
