### ISSUE TITLE
Job property Guide text

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#1124]
Datasource > Create Datasource를 StagingDB으로 생성시 3번쨰 항목 설정 단계에서

What is Job properties의 가이드 문구와 Ingestion tuning의 가이드 문구가 동일하였습니다.
이에 Job properties의 가이드 문구 수정이 필요합니다.합니다.
![whatisjobproperties](https://user-images.githubusercontent.com/42257766/50202732-5eb4c000-03a2-11e9-8400-d0e770c6c400.png)

문구:
What is Job Properties?
When you Ingestion Druid, it works using MapReduce job.
So you should set properties related to MR appropriately for the environment.
Please refer to the following link...

적재 환경 옵션이란?
Druid에 적재시 MapReduce을 통해서 적재를 수행합니다. 따라서 MR에 관련된 속성을 환경에 맞게 적절하게 설정해야 합니다.
다음 링크를 참고해 주세요.

링크값: http://druid.io/docs/latest/ingestion/ingestion-spec.html

이 이슈는 MT-132와 동일합니다.

**Comment by kyungtaak** [comment]
@deidera08 링크값은 http://hadoop.apache.org/docs/stable/hadoop-mapreduce-client/hadoop-mapreduce-client-core/mapred-default.xml 입니다. 그런데 너무 기네요.;;

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
> @deidera08 링크값은 http://hadoop.apache.org/docs/stable/hadoop-mapreduce-client/hadoop-mapreduce-client-core/mapred-default.xml 입니다. 그런데 너무 기네요.;;

링크연결하는 텍스트에 마우스 오버시 툴팁으로 해당 URL의 Full path가 노출되면 어떨까 합니다.
![2019-01-01 5 35 35](https://user-images.githubusercontent.com/42257766/50571374-b95f0a80-0deb-11e9-8ad2-39cdd540c2bd.png)

**Comment by alchan-lee** [comment]
fixed in #1252
