### ISSUE TITLE
The data represented in the chart does not match the download data.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1129]
**Describe the bug**
- 차트에 표현된 데이터와 다운로드 데이터가 일치하지 않음

**To Reproduce**
1. Go to https://discovery.metatron.app/app/v2/workbook/4b826fd5-20d8-4b52-9234-441de6fd2cd3

2. 왼쪽 아래 Scatter 차트의 특정 데이터 클릭 
<img width="1430" alt="2018-12-19 4 07 32" src="https://user-images.githubusercontent.com/612173/50204607-cff77180-03a8-11e9-92ad-70cc000227a5.png">

3. 클릭 상태에서 오른쪽 아래의 Table 차트를 보면 클릭된 데이터만 표현됨(위 스크린샷에서는 Mexico City 가 선택됨)

4. 차트 데이터 다운로드 버튼 클릭
<img width="698" alt="2018-12-19 4 07 51" src="https://user-images.githubusercontent.com/612173/50204643-ed2c4000-03a8-11e9-90dd-38c51982b3b6.png">

5. 차트 데이터 다운로드를 눌러보면 위 스크린 샷과 같이 화면에 표현된 데이터 이외의 데이터도 보임(위 차트에서는 Mexico City 만 다운로드 되어야 됨)

**Expected behavior**
실제 화면에 표현된 데이터만 보여야되며, 실제 다운로드 수행 시에도 해당 데이터만 받아져야 됨

**Comment by YooYoungmo** [comment]
## 문제 확인
* 대시 보드에서 사용한 필터 조건이 차트 데이터 다운로드 시에 적용되지 않음.
* 따라서 필터링된 데이터가 아닌 전체 데이터를 표현하고 이를 기준으로 다운로드함.

**Comment by YooYoungmo** [comment]
대시보드 필터링 조건이 있는 경우 이를 차트 데이터 다운로드에 반영하는 방향으로 진행하겠습니다.

**Comment by kyungtaak** [comment]
@AnnieHwang @metatron-app/design #1164 에서 논의된 바와 같이 selection 필터의 주체가 되는 차트에 대한 다운로드 정책에 대해 검토부탁드립니다.

**Comment by YooYoungmo** [comment]
@kyungtaak #1164 PR 건은 코드 수정하고 나서 알려 드리겠습니다.(필터 기준으로 데이터 다운로드가 되도록)

**Comment by AnnieHwang** [comment]
@minjung-cho 저희 초도 기획안 올려주세요. 그 안대로 하면 오늘 이슈 된 내용 해결 될것 같아요. @YooYoungmo 저희 초도기획안 일단 보시고 코멘트 부탁드려요.

**Comment by minjung-cho** [comment]
<img width="881" alt="2019-01-18 3 52 37" src="https://user-images.githubusercontent.com/28773903/51370572-ebd26c80-1b3a-11e9-941c-a6f5829d4181.png">
초기 기획안에서 필터링 결과가 옵션으로 제공되는 UI가 있었습니다. 핑크색 마크 부분입니다.
당시의 'apply filter' 는 모든 필터링을 on/off하는 기능이긴 했습니다. 글로벌 필터, 차트 필터, 인스턴트(셀렉션) 필터를 적용/미적용하여 데이터 그리드를 확인하고 다운로드 하는 것이지요.
모든 필터가 적용(인스턴트 필터 포함)된 상태로 그리드를 확인하고 다운로드할 수 있어야 한다는 결론을 낸 이유는,
인스턴트 필터는 대시보드 열람 사용자가 유일하게 걸 수있는 필터이고 인스턴트 필터가 걸린 상태를 결과 데이터로 추출하고자 할 수 있다는 생각에서 였습니다. 
오늘 여러분들이 말씀하신 것처럼 현재 보고 있는 차트의 데이터를 받아야 하는것이 아니냐는 의견에도 공감합니다만, 그렇다면 위와 같은 케이스에 대한 니즈는 또 다른 것으로 풀어야 할듯 합니다.

**Comment by minjung-cho** [comment]
@AnnieHwang 
이 UI를 다시 살리는 안으로 어떻게 해결이 될것 같습니다만, 문제는 ‘apply filter’에서 ‘filter’를 어떻게 정의할 것이냐에 대한 논의가 또 이어질 것 같습니다.
당시에서는 글로벌 필터, 차트 필터, 인스턴트(셀렉션) 필터를 포함하는 것으로 기획된 것입니다만, 현재로선 인스턴트 필터에 대한 옵션 정도로 좁혀질 수 있을 것 같은데요. 그렇다면 좀 더 명확하게 ‘apply instant filter’라고 해야 하지 않을지요... 
오늘 회의 이후 여러 고민이 되었지만, 사실.. 제 생각은 여전히.. 초기 기획대로 'Apply filter' UI를 살리고,  
filter는 글로벌 필터, 차트 필터, 인스턴트(셀렉션) 필터를 모두 포함하는 방향이 좋을 것 같습니다.
사용자가 현재 보고 있는 차트에 대한 데이터는 셀렉션 필터를 해제하고 다운로드하면 될것이라 봅니다.
의견 부탁드립니다.

**Comment by AnnieHwang** [comment]
@minjung-cho @kyungtaak @YooYoungmo 저도 기획자분 생각에 동의하는데요. 다른분들은 어떻게 생각하시나요?

**Comment by kyungtaak** [comment]
@minjung-cho @AnnieHwang 제가 생각하기엔 "Apply filter" 는 더 혼란스러울것 같은데요. 해제하면, 모든 필터링이 해제된다..는것으로 이해하면 되나요? 흠.. 이런경우도 셀렉션 필터의 이슈에서 자유롭지 않은듯합니다. ^^; 사실 개인적으로 심플하게 무조건 셀렉션 필터/필터 위젯 선언에 맞게 해주되, 금일 보드 미팅때 나왔던것 처럼 필터 정보를 표시(아이콘 툴팁 조합 같은)하는 편이 더 나을것 같다는 생각이 듭니다.

**Comment by minjung-cho** [comment]
@kyungtaak @AnnieHwang 
apply filter는 사실 니즈가 있다면 추가해도 좋을 것 같습니다. 필터 정보를 보여주는 것에는 같은 생각을 가지고 있고요. 다만 현재 차트 위젯의 info에 필터 정보가 살짝 나오고 있는데, 이 부분이 먼저 보강되어야 할듯 합니다. 
![2019-01-21 11 05 15](https://user-images.githubusercontent.com/28773903/51457676-9b0a8000-1d95-11e9-85e9-2ecdde79c7d8.png)
현재는 차트 필터의 컬럼명만 나오고 있습니다만, 글로벌 필터 차트 필터의 세부 항목이 보여야 하지 않을지요- 글로벌 필터는 대시보드 공통 사항이라 위젯별로 다 나와야 하는지 반문할 수도 있겠지만... 사용자가 원본 데이터 소스와 비교해 볼 수도 있고, 추후 차트 위젯 하나를 공유한다고 했을 때(로드맵상에 없지만...)도 필요한 정보일 거라 생각됩니다.
실 사용 시나리오가 부족한 지라... 가능한 확장된 케이스를 생각해 보았습니다. 여러 의견 부탁드립니다.

**Comment by YooYoungmo** [comment]
@kyungtaak 이슈 시작은 버그인데요. 논의가 점점 커진다는 느낌이 듭니다.
제 생각에는 보드 미팅에서 논의된 것과 같이 PR 코드(#1164)를 수정해서 해당 건을 Close 하고
위의 논의 중인 apply filter 는 다른 이슈로 진행하는게 좋을 것 같습니다.

**Comment by kyungtaak** [comment]
@YooYoungmo 네 저도 그렇게 하는게 좋을거 같네요.  그리고, 현재 pr 은 충돌이 나고 있습니다. 관련해서 확인 부탁드립니다. (혹시 모를 화면 깨짐을 대비해서 애매한 부분은 @eltriny 님께 문의 해주세요.)
@AnnieHwang @minjung-cho   초기 기획안대로, 모든 dimmed 에 관계없이 글로벌/차트/필터 위젯/셀렉션 필터가 모두 적용된 다운로드를 먼저 적용하고, 추후 필터 정보 표시 또는 apply filter 를 진행할지 정리하면 좋을것 같은데요. 확인 부탁드립니다.

**Comment by YooYoungmo** [comment]
@kyungtaak PR 코드 수정하고 현재 master로  Rebase 하겠습니다.

**Comment by Taehui** [comment]
@YooYoungmo master 에 rebase 되면 idcube-master 에 긴급 merge 가 한번 필요합니다. ^^;

**Comment by kyungtaak** [comment]
@Taehui 해당 이슈는 수정하여 master에 머지해 두었습니다.
