### ISSUE TITLE
Can not use space-contained column name for aggregate function

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#1142]
**Describe the bug**
Aggregation function can not understand column name with space.

**To Reproduce**
1. Go to data preparation
2. Select aggregation rule
3. Add expression such as sum(\`Net profit\`)
4. See error.
5. Add expression such as "aggregate value: 'sum(\`Agency Id\`)' group: Disposition" in text editor
6. See error.

**Expected behavior**
Column name with space must be supported on aggregation function.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mh0203** [comment]
Additionally, aggregation without groupBy column will be available with this commit.
UI works required

1. Allow space contained column name for aggregate function.(ex sum(`net profit`))
2. Allow aggregation rule without group by column.
3. Prevent error when editing rule with 1&2.

**Comment by sang-hee-lee** [comment]
Fixed in #1289
