### ISSUE TITLE
Supporting polygon-based aggregation in map chart.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1154]
**Is your feature request related to a problem? Please describe.**
- 맵차트 내에서 위/경도 만으로 데이터를 표현하면, 표현할 수 있는 물리적인 point 수가 많지 않으므로 폴리곤 기준으로 집계하여 표현하는 것이 필요

**Describe the solution you'd like**
- 맵차트 내에서 폴리곤 기준으로 aggregate 하여 값을 표현하는 것을 지원
- 일반적으로 많이 사용되는 폴리곤 정보의 표현 지원 (예: 우편번호 블럭, 시/도 단위나 구/군/동 단위의 폴리곤 지원)
- Zoom in/out 에 따라 적절한  레벨의 폴리곤 매핑 및 제공 필요

**Comment by kyungtaak** [comment]
@Taehui 위와 같은 공간연산 기능은 #1107 와 같이 멀티 레이어기능이 지원이 되어야만 가능한 기능입니다. 따라서 멀티레이어 관련 기능을 개선후, 2월 중으로 기능을 구성예정입니다.

**Comment by kyungtaak** [comment]
@Taehui #1463 이슈에서 진행중이며, 3.2 릴리즈에 출시할 예정입니다. (해당이슈는 종료하겠습니다.)
