### ISSUE TITLE
 Out of bar chart x-axis range in combined chart.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1161]
**Describe the bug**
- Combination chart occurs when bar chart is out of range of x axis under certain conditions(Check "Fit to Data Scale" option).

**To Reproduce**
- https://discovery.metatron.app/app/v2/workbook/60a4fb15-d601-404f-aedf-5cf5d6badfef

**Expected behavior**
- Chart must not be out of range of x-axis.

**Screenshots**
<img width="862" alt="2018-12-27 8 28 36" src="https://user-images.githubusercontent.com/612173/50459819-a1822380-09b2-11e9-94a3-db769c1a7090.png">

**Desktop (please complete the following information):**
 - Browser : IE & Chrome

**Comment by kyungtaak** [comment]
@Taehui This issue will be resolved after the echart update. (~1m)

**Comment by AnnieHwang** [comment]
@alchan-lee 해당 내용 반영된것 같은데 클로즈 할까요?

**Comment by kyungtaak** [comment]
@Taehui 해당 내용은 이번 라이브러리 업데이트에 포함하여 해결이 되어 이슈 종료하도록 하겠습니다.
