### ISSUE TITLE
Add cache control header for static resources

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#1162]
**Describe the bug**
- 현재 `/resource/**` 아래에 있는 script 코드들도 no-cache 설정이 되어 있어 매번 페이지 로딩될 때 마다 script 파일을 서버로부터 다운받고 있음
- 이 경우 server에서는 트래픽이 많이 발생하고.  client에서는 네트워크가 느린 환경에서는 페이지 로딩이 느려짐
 
**To Reproduce**
1. 페이지 로딩
2. 브라우저의 디버그 모드에서 HTTP Response에서 cache 항목을 확인

**Expected behavior**
처음 한번만 script를 다운로드 받고 이후에는 브라우저의 cache를 사용

**Screenshots**
![response_cache](https://user-images.githubusercontent.com/321821/50465641-6b08d080-09d3-11e9-8df5-8be93f835d36.jpeg)

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
기 적용된 건이므로 이슈를 종료합니다.
