### ISSUE TITLE
Request validation removal for the valuation of properties

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#1168]
**Describe the bug**
QA진행과정에서 발생한 이슈(MT-117)로 인하여, 인풋값들의 벨리데이션을 진행하는 관정에서 '.'을 제외한 모든 특수문자를 제거 하였습니다. 하지만, 프로젝트에 적용과정에서 해당 벨류에 여러 특수문자가 사용되고 있음을 파악하고 해당 내용을 정정하고자 합니다.

데이터 커넥션과 데이터소스 영역의 프로퍼티 영역(advanced > properties) 중 value부분의 벨리데이션 처리를 모두 없애고자 합니다.

![image-4](https://user-images.githubusercontent.com/6300003/50502690-7d9f0a80-0aa4-11e9-9e97-819ec07e61db.png)

**To Reproduce**
데이터소스, 데이터 커넥션 > 생성팝업 > Advanced설정

**Comment by brandon-wonjune** [comment]
f#1168-remove_value_validation_in_source 브랜치 생성하였습니다

**Comment by brandon-wonjune** [comment]
@AnnieHwang 
데이터 커넥션, 데이터소스 property value 부분에 대한 validation을 제거하였습니다.

**Comment by AnnieHwang** [comment]
@brandon-wonjune 감사합니다.
