### ISSUE TITLE
Searching column in multi-datasource is not work properly

### ISSUE THREAD

**Issue by alchan-lee** [metatron-app/metatron-discovery#117]
**Describe the bug**
멀티데이터소스 등록/수정 화면에서 join 컬럼 검색시 검색한 내용이 명확하게 보이지 않음
검색 결과가 반영되었는지의 여부를 확인할 수 없음

**To Reproduce**
1. Go to 'Set Association' at multi-datasource edit tab
2. Input 'Search' text
3. Column highlighting at invisible area

**Expected behavior**
1. Scroll moves to target column 
2. or display only target column

**Screenshots**
![image](https://user-images.githubusercontent.com/42234141/45007043-d0a50b80-b036-11e8-98a0-c841e75ef063.png)
![image](https://user-images.githubusercontent.com/42234141/45007052-dac70a00-b036-11e8-9a3e-7d6ebeba26cb.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Additional context**
TDE: METATRON-1384

**Comment by minjung-cho** [comment]
@alchan-lee key를 검색하는 부분에 사용된 콤포넌트는 다른 화면에서는 다음과 같이 사용되고 있습니다. 
![2018-09-07 3 15 19](https://user-images.githubusercontent.com/28773903/45201675-313f7d00-b2b1-11e8-859b-cfe0cdead0d3.png)

이 부분에 검색 기능이 추가되는 시점에서 추가 정의가 부족했던 것 같습니다; 기획 보강해서 노티드리겠습니다. @dave-taeho 콤보박스에서 컬럼을 선택했을 때, 그리드가 해당 위치로 이동할 수 있을지 확인 요청 드립니다~

**Comment by minjung-cho** [comment]
@dave-taeho 이건 다른 문제인데; 아이콘이 안나오고 있습니다.^^;
<img width="228" alt="2018-09-07 3 18 21" src="https://user-images.githubusercontent.com/28773903/45201713-559b5980-b2b1-11e8-9c62-70c2937edbe8.png">

**Comment by minjung-cho** [comment]
![2018-09-12 5 41 32](https://user-images.githubusercontent.com/28773903/45413157-73066400-b6b3-11e8-9445-cb5aa5df95a8.png)

@AnnieHwang 논의한 내용을 공통 콤포넌트로 정의했습니다. 프랩>rule 편집 화면의 command 선택 부분과 동일한 인터랙션입니다. 검토 부탁드립니다~ @koeun222 이 안으로 디자인 검토 부탁드립니다.

**Comment by AnnieHwang** [comment]
@minjung-cho 해당 기획대로 반영하면 좋을 것 같습니다.

**Comment by minjung-cho** [comment]
@eltriny join 팝업의 조인키 검색+선택하는 부분과 동일하게 동작하면 됩니다. 참고 부탁드립니다. 추가로 그리드에서 선택 시에도 콤보박스에 선택된 컬럼명이 보이도록 할 수 있을지 검토 부탁드립니다.
@AnnieHwang 그런데, 해당 콤보박스가 제대로 동작하면 아래 표시한 부분과 중복인 것 같습니다. 이부분 삭제해도 되겠지요?
![2018-09-13 3 57 56](https://user-images.githubusercontent.com/28773903/45472024-e8366f80-b76d-11e8-8088-530f9e9cdf27.png)

**Comment by eltriny** [comment]
@minjung-cho 네 가능합니다. 그렇게 처리하겠습니다.
@AnnieHwang 위 문의사항 답변 부탁드리겠습니다. 위 내용 적용하고 이슈 마무리 하려 합니다.

**Comment by kyungtaak** [comment]
#234 PR 코멘트 확인 해주시고 수정후 리오픈해주세요.

**Comment by AnnieHwang** [comment]
@minjung-cho 네 삭제해도 될것 같고요(실제로 잘 안보여서..) @eltriny 감사합니다~
