### ISSUE TITLE
The dataset uploaded to HDFS has a wrong URI.

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#1170]
**Describe the bug**
The URI of a dataset uploaded to HDFS begin with "file://".

**To Reproduce**
1. Go to management > data preparation > dataset menu
2. Click 'Generate new dataset' button
3. Select the 'file' type in the data type popup
4. Import any file
5. Create a dataset with the upload location set to HDFS
6. Launch the inspector of web browser
7. Go to the detail page of the dataset just created
8. Go to the Network tab on the inspector
9. Select xhr item which just loaded on lists
10. Check the storedUri information on the Preview section.

**Expected behavior**
The URI of a dataset uploaded to HDFS should begin with "hdfs://" not "file://".

**Screenshots**
![screen shot 2018-12-28 at 3 31 13 pm](https://user-images.githubusercontent.com/28751002/50505791-ee502200-0ab8-11e9-90dd-9ae50f623a4b.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version: 71.0

**Additional context**

**Comment by sang-hee-lee** [comment]
Server program modification required

**Comment by joohokim1** [comment]
Potential risk has gone by https://github.com/metatron-app/metatron-discovery/issues/1651.
Closing.
