### ISSUE TITLE
Preview of dataset fails if the 1st column is empty

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#1176]
**Describe the bug**
Preview of dataset fails when uploading an Excel file with the first blank column

**To Reproduce**
1. Go to Management > Data Preparation > Dataset
2. Click on 'Generate new dataset'
3. Select 'File' type
4. Upload this file [test-without 1 col.xlsx](https://github.com/metatron-app/metatron-discovery/files/2720352/test-without.1.col.xlsx)
5. See preview

**Expected behavior**
Previews should work normally, such as uploading the same files to the datasource.

**Screenshots**
Datasource preview
![screen shot 2019-01-02 at 6 56 50 pm](https://user-images.githubusercontent.com/28751002/50587159-31970000-0ec0-11e9-90e6-35ef1ed79a4f.png)

Dataset preview
![screen shot 2019-01-02 at 6 41 44 pm](https://user-images.githubusercontent.com/28751002/50587166-35c31d80-0ec0-11e9-997d-3cb815a91d77.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version: 71.0

**Additional context**

**Comment by joohokim1** [comment]
@ecoloy 
I'll see first, then ask @sang-hee-lee for help if needed.

**Comment by joohokim1** [comment]
@ecoloy @sang-hee-lee 

Trying to add an element to an empty list by index.
@ksparknot will take this issue.

_인덱스로 빈 목록에 요소를 추가하려고합니다.
@ksparknot 님께서 이후 진행하실 예정입니다._

**Comment by joohokim1** [comment]
Closing with no PR.
