### ISSUE TITLE
granularity is not set properly on metatron engine

### ISSUE THREAD

**Issue by alchan-lee** [metatron-app/metatron-discovery#118]
**Describe the bug**
Granularity is not set properly on metatron engine

**To Reproduce**
1. Create datasource with 'METATRON ENGINE' type
2. Segment granularity is NONE and Query granularity is NONE

**Expected behavior**
Granularity is setted properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/42234141/45009670-70b56180-b044-11e8-8a9f-ac1dc4b042ca.png)

**Additional context**
TDE: METATRON-1383

**Comment by eltriny** [comment]
@alchan-lee 
본 이슈는 UI 상에서 처리할 수 있는 것이 없어 보이는데.. 
( 생성 시, 제공해주신 API를 호출하는 것이 전부입니다. )
저희쪽에서 작업해야 하는 내용이 있는 것인가요?

**Comment by kyungtaak** [comment]
@eltriny 이건 제가 처리하도록 하겠습니다.

**Comment by kyungtaak** [comment]
@alchan-lee 담당자를 변경합니다. 해당 이슈 확인 부탁할게요.

**Comment by alchan-lee** [comment]
@kyungtaak 넵, 그래도 내용이 좀 다르니 브랜치는 분리해서 진행할게요

**Comment by kyungtaak** [comment]
@alchan-lee 그런데, segementmetadata granularity 의 종류는 3개에요. 이게 저희 데이터소스에서 관리하는 granularity 와 일치하는지 좀더 확인이 필요할것 같은데요. 확인 부탁드립니다.

**Comment by kyungtaak** [comment]
> 넵, 그래도 내용이 좀 다르니 브랜치는 분리해서 진행할게요

@alchan-lee 네 그럼 #710  이슈를 할당해두겠습니다.^^
