### ISSUE TITLE
 Allows one column to be registered as a global and chart dependent filter duplication

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1181]
**Problem**
현재 하나의 컬럼을 글로벌과 차트 필터 중복 등록할 수 없음.
필터의 (글로벌필터>차트필터) 종속성을 사용하여 필터링을 할 수 있어야 함.

**Solution**
1.글로벌필터와 차트필터를 중복해서 등록할 수 있음
2.글로벌과 차트 필터가 중복으로 등록된 경우, 차트 화면에서 종속 관계 확인 가능함
3.이미 글로벌 필터로 설정된 값을 차트 종속 필터 값으로 변경 가능. 이때, 확인 팝업 출력 후 컨펌 과정을 거침 
![2019-01-31 11 25 46](https://user-images.githubusercontent.com/28773903/52026530-88d5d200-254b-11e9-80a5-e8728ebed199.png)

**Alternatives**
없음

**Additional context**
~~제약 사항~~
~~이미 글로벌로 등록된 컬럼에 대해서 차트 종속 필터로 추가 등록할 경우, 차트 필터 설정 씬에서 글로벌 필터 값을 확인할 수 있어야 함. 이때, 차트 화면 진입 즉시 각 필터의 글로벌 필터 값을 보여주는 것은 쿼리를 여러번 날려야 하기 때문에 화면에 무리가 갈것으로 예상됨. 따라서, 특정 버튼을 눌러서 글로벌 필터 값을 확인할 수 있도록 해야 함.~~

**Comment by minjung-cho** [comment]
@koeun222 차트 화면에서 글로벌 필터 show/hide 버튼을 제거하였습니다. 그에 따라 변경되는 디자인 재작업 부탁드립니다

**Comment by koeun222** [comment]
@AnnieHwang 화면 공유드립니다

1. 대시보드 > 오른쪽패널(필터)
![image](https://user-images.githubusercontent.com/42256760/52838038-9175fd00-3134-11e9-98b9-92564dbd3822.png)

2. 필터팝업
![image](https://user-images.githubusercontent.com/42256760/52838060-a5216380-3134-11e9-8348-11b9bda220cd.png)

**Comment by minjung-cho** [comment]
@kyungtaak @AnnieHwang 차원값>아이템 이외의 타입에 대해서 의견 여쭙니다.

[차원값>시간]
글로벌/차트 중복되었을 때
필터링 UI 타입(Unit/range,list,relative)의 변경이 열려있으면, 사용성이 매우 복잡하게 느껴 질 듯 합니다. 개발은 어떨지요-(현행 유지하는 것이 낫지 않은지 고민이 됩니다...)
시간 타입의 글로벌/차트 중복 등록 가능한 안으로 아래와 같이 생각해 보았는데, 한번 검토 부탁드립니다.
1. 글로벌/차트 중복되었을 때, 한쪽에서 UI 타입을 변경하면 다른 한쪽도 변경되고 값을 초기화 시키거나
2. 글로벌만 타입 변경 가능하도록 해야 할 것 같습니다.


[측정값]
글로벌/차트 중복하지 않도록 의견을 나누었고, 
현재 UI(글로벌/차트 중복 안되고, 변경하려고 할때 팝업을 띄움)를 유지하고자 합니다. 통일성이 없어지는 것이 우려됩니다만... 다른 의견 있으시면 부탁드립니다.

**Comment by minjung-cho** [comment]
@kyungtaak @AnnieHwang 기존에 논의되고 있던 내용에서 '글로벌 필터'의 개념이 달라지는 방향으로 정리가 되어서 신규 이슈를 등록했습니다. #1457 에서 신규 기획 내용 확인 부탁드립니다.

**Comment by eltriny** [comment]
#1457 로 내용이 변경되어 본 이슈는 종료합니다.
