### ISSUE TITLE
Add function to modify snapshot name

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#1186]
**Is your feature request related to a problem? Please describe.**
There is no method to modify snapshot name

**Describe the solution you'd like**
Add function to modify snapshot name in snapshot details

**Describe alternatives you've considered**

**Additional context**

**Comment by joohokim1** [comment]
@sang-hee-lee @paigechoi 

Currently, when I edit the name of a dataset and hit the enter, CR gets into the name.
Note please.

_현재 데이터 세트의 이름을 수정하고 Enter 키를 누르면 CR이 이름에 포함됩니다
참고하세요._

**Comment by joohokim1** [comment]
The problem of entering a CR in dataset names will be fixed in other issues.

_Dataset 이름에 CR이 들어가는 문제는 다른 이슈로 고쳐질 예정입니다._
