### ISSUE TITLE
Improved scrolling UI when creating workspace

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1198]
**Describe the bug**
1. 실제 스크롤되는 영역과 스크롤의 위치가 다릅니다

**Screenshots**
<img width="1424" alt="2019-01-07 3 38 15" src="https://user-images.githubusercontent.com/28773903/50752720-8c4ea400-1292-11e9-8a02-705434cb9743.png">

**Additional context**
#703 
https://tde.sktelecom.com/pms/browse/METATRON-1417
https://tde.sktelecom.com/pms/browse/METATRON-1226

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/51009750-b8b93780-1594-11e9-822a-2daf7c3ee5e1.png)
영역 확인부탁드립니다

**Comment by eltriny** [comment]
@kyungtaak 본 이슈는 이미 적용되어 있습니다.
