### ISSUE TITLE
Enable to edit column name editing when creating a data source

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#1202]
**Is your feature request related to a problem? Please describe.**
데이터소스 생성시 중복 컬럼명이 있을 경우 허용되지 않습니다.
File의 경우 첫번째 단계에서 잘못된 컬럼명을 체크할 수 있지만
(관련이슈: [#1057](https://github.com/metatron-app/metatron-discovery/issues/1057) Database 타입등에서는 이 과정을 거치지 않습니다.
특히 Linked data일 경우 필수필터 지정시 오류를 야기합니다.
(관련이슈: [#1175](https://github.com/metatron-app/metatron-discovery/issues/1175)

**Describe the solution you'd like**
데이터소스 생성시 configure the schema단계에서 컬럼명 수정이 가능해야합니다.
![add column name editing](https://user-images.githubusercontent.com/42257766/50756075-58797b80-129e-11e9-8fde-1c4cf3ca1a4c.png)

**Comment by kyungtaak** [comment]
@deidera08 추가로, 건의드리고 싶은 내용은 geo 컬럼이나 expression 컬럼 생성후 삭제할 방법이 현재 없습니다. 이부분에 대한 검토도 함께 부탁드립니다.

**Comment by deidera08** [comment]
> 추가로, 건의드리고 싶은 내용은 geo 컬럼이나 expression 컬럼 생성후 삭제할 방법이 현재 없습니다. 이부분에 대한 검토도 함께 부탁드립니다.

가이드 주셔서 감사합니다.
현재 유저가 생성한 Geo 컬럼을 선택시 삭제할 수 있는 UI가 노출되고 있는데요, 수정이 필요하네요
보완내용 정리해서 공유드리도록 하겠습니다.
(다른 기능인것 같아서 준비가 되면 새 이슈로 등록하도록 하겠습니다)

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
유저가 생성한 Geo-point, Geo Expression은 해당 check box를 disable 시키는것으로 보완하겠습니다.
관련이슈 PR[#1240](https://github.com/metatron-app/metatron-discovery/pull/1240)건에 반영 요청 하겠습니다.

**Comment by koeun222** [comment]
@AnnieHwang 이미 사용중인 컬럼명인경우 에러문구 추가했습니다
에러문구가 있는경우 컬럼명은 에러문구 앞에서 말줄임(...)됩니다
![image](https://user-images.githubusercontent.com/42256760/54256871-c6913600-45a0-11e9-9a62-a2788772f7a8.png)

**Comment by brandon-wonjune** [comment]
@kyungtaak 이 이슈 진행하면서 문의사항이 있습니다.
초기에 config schema 화면 진입시 중복되는 이름의 field가 존재하는 경우 numbering을 붙여서 새로 이름을 정의하는것으로 되어있는데요.
그 전 화면 (데이터베이스 선택화면) 에서 데이터 조회시
field 목록이 아닌 data 목록의 경우는 중복되는 이름의 컬럼일 경우에는 데이터 형태가 어떤 형태로 내려오나요?
```
// 사용하는 api
api/connections/query/data?extractColumnName=false
```
![스크린샷 2019-03-13 오후 4 00 31](https://user-images.githubusercontent.com/42233627/54259484-3d323180-45a9-11e9-9499-d81031fd04b9.png)

**Comment by kyungtaak** [comment]
@brandon-wonjune 답변드립니다. (그리고 3.3_rc1 으로 이동하였습니다.)
Q1. 중복된 컬럼이면 그냥 전달해주고, 중복된 컬럼일 경우 경고 아이콘을 표시합니다. 그래서 사용자에게 수정하게끔 유도하는 정책을 가지고 있는것으로 알고 있습니다. @minjung-cho @deidera08 맞지요?

> 그 전 화면 (데이터베이스 선택화면) 에서 데이터 조회시
field 목록이 아닌 data 목록의 경우는 중복되는 이름의 컬럼일 경우에는 데이터 형태가 어떤 형태로 내려오나요?

@ufoscw 이 위에건은 무슨의미인지 알수 있을까요?

**Comment by deidera08** [comment]
> 중복된 컬럼이면 그냥 전달해주고, 중복된 컬럼일 경우 경고 아이콘을 표시합니다. 그래서 사용자에게 수정하게끔 유도하는 정책을 가지고 있는것으로 알고 있습니다.

넵넵 맞습니다. (늦은 확인 죄송합니다)

**Comment by ufoscw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Datasource 생성 시, Druid로 DB 커넥션 맺어서 생성 가능하게 되어 있는데, 기능 제공하는 것이 맞는지 문의 드립니다. (생성 해보면 실패함)](https://trello.com/c/EC2GON67/86-datasource-%EC%83%9D%EC%84%B1-%EC%8B%9C-druid%EB%A1%9C-db-%EC%BB%A4%EB%84%A5%EC%85%98-%EB%A7%BA%EC%96%B4%EC%84%9C-%EC%83%9D%EC%84%B1-%EA%B0%80%EB%8A%A5%ED%95%98%EA%B2%8C-%EB%90%98%EC%96%B4-%EC%9E%88%EB%8A%94%EB%8D%B0-%EA%B8%B0%EB%8A%A5-%EC%A0%9C%EA%B3%B5%ED%95%98%EB%8A%94-%EA%B2%83%EC%9D%B4-%EB%A7%9E%EB%8A%94%EC%A7%80-%EB%AC%B8%EC%9D%98-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4-%EC%83%9D%EC%84%B1-%ED%95%B4%EB%B3%B4%EB%A9%B4-%EC%8B%A4%ED%8C%A8%ED%95%A8)

**Comment by brandon-wonjune** [comment]
#1940 이슈에서 컬럼 이름에 대해 50자 제한하여 표기되고 있습니다.
만약 현재 이슈에서 중복 컬럼명이 있을 경우 표기되는것은 중복인것처럼 보이지만 실제 데이터는 다른경우가 있을 수 있습니다.
(컬럼이름이 50자 제한이기 때문에)
이것에 대해 그대로 표기를 할 것인지 다르게 표현할 것인지가 필요합니다.

참고로 #1920 이슈에서 현재 이 이슈를 위한 변경된 디자인이 적용되고 있습니다.

**Comment by deidera08** [comment]
좌측 컬럼리스트나 우측 컬럼상세에서 모두 컬럼명이 길 경우 생략처리(...)를 하고 있습니다만, 
마우스오버시 툴팁으로 전체 컬럼명을 노출시키고 있어 괜찮을듯 합니다

**Comment by kyungtaak** [comment]
#1920 와 중복 이슈로 이슈를 종료합니다.
