### ISSUE TITLE
Show the workbench's connection information from the contents list in the workspace

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1209]
**Problem**
Difficult to identify workbench content from workspaces' list of contents.

**Solution**
Show the workbench's connection information from the contents list in the workspace.
<img width="1669" alt="workbench-improvement" src="https://user-images.githubusercontent.com/28773903/50811315-1a895f80-1351-11e9-9ff2-cf3390c2d129.png">

**Comment by minjung-cho** [comment]
커넥션 이름과 아이콘을 함께 표시하는 것이 좋겠습니다

**Comment by eltriny** [comment]
@kyungtaak 
![2019-03-05 10 15 39](https://user-images.githubusercontent.com/3685833/53773913-af62a080-3f2f-11e9-9954-7434ccf78aba.png)
위와 같이 워크스페이스내 books 정보에서 workbench의 커넥션 정보등이 없습니다. 추가 부탁드립니다.

**Comment by koeun222** [comment]
@AnnieHwang 워크스페이스 > 워크벤치 타일에 커넥션정보 추가한 안공유드립니다
24x24 size 공통으로 쓰고 있는 DB type icon (color style) 사용됩니다 
![image](https://user-images.githubusercontent.com/42256760/53781810-b7c9d400-3f4d-11e9-8cc3-e304347c5090.png)

**Comment by kyungtaak** [comment]
@eltriny 늦었네요..;; 아래와 같이 contents 영역에 정보를 넣어두었습니다.
```
...
        {
            "modifiedTime": "2019-03-07T11:14:38.629Z",
            "contents": {
                "connType": "MYSQL",
                "connName": "mysql-local-conn"
            },
            "name": "TEST-Workbench-01",
            "description": "",
            "createdTime": "2019-03-07T11:14:38.629Z",
            "id": "workbench-01",
            "tag": "",
            "type": "workbench",
            "favorite": false
        }
...
```
