### ISSUE TITLE
problem of reading some excel file occurs

### ISSUE THREAD

**Issue by ksparknot** [metatron-app/metatron-discovery#1210]
**Describe the bug**
Sometimes an error occurs when reading an Excel file
The kinds of exceptions vary from time to time.

**To Reproduce**
We are reproducing it to find the cause of the problem.
It is assumed to be the cell containing null or empty value.
if you want to test, create a dataset with an excel file has null or empty cells

**Expected behavior**
sometimes an exception occurs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Additional context**

**Comment by joohokim1** [comment]
@ksparknot 

If possible, it would be appreciated if you attach some Excel files that contain nulls or empty columns.

_가능하시다면 null이나 empty 컬럼을 포함한 엑셀파일을 첨부해주시면 감사하겠습니다._

**Comment by ksparknot** [comment]
duplicated issue with [#1176](https://github.com/metatron-app/metatron-discovery/issues/1176)
