### ISSUE TITLE
Suggest dataset naming rule 

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1223]
**Is your feature request related to a problem? Please describe.**
Currently, the dataset (esp. W.DS) naming rule is not well defined.

**Describe the solution you'd like**
<File type I.DS>
_filename_ (file-type) is suggested in the pages below.
When the suffix is well-known (like CSV, TSV, TXT, JSON) , it is removed.
Note that, if the file suffix is not one of xlsx, xls, json, then it's treated as a CSV.

_"FIFA 18 Player Ratings.csv"_
![2019-01-09 4 20 10](https://user-images.githubusercontent.com/42257727/50884352-07988d00-142e-11e9-9406-8cf7b691b133.png)

_"690.txt"_
![2019-01-09 4 23 08](https://user-images.githubusercontent.com/42257727/50884285-d455fe00-142d-11e9-842f-289bc2250f69.png)

_"colours.unix"_
![2019-01-09 4 23 37](https://user-images.githubusercontent.com/42257727/50884344-fea7bb80-142d-11e9-9b42-0cbf9916a9ab.png)

_"tmp"_
![2019-01-09 4 24 25](https://user-images.githubusercontent.com/42257727/50884655-e71d0280-142e-11e9-8664-600a1bc58cc0.png)

_"wikiticker-2015-09-12-sampled.json"_
![2019-01-09 4 53 12](https://user-images.githubusercontent.com/42257727/50884730-1af82800-142f-11e9-8fe3-1e606f9912d7.png)

For an Excel file, _filename_ - _sheetname_ (EXCEL) is suggested.

_"Annual Revenue.xlsx"_ file's _"Revenue Goal"_ tab
![2019-01-09 4 25 08](https://user-images.githubusercontent.com/42257727/50884761-2d726180-142f-11e9-9a18-e3cae7e3b542.png)

<Database type I.DS>

*tablename* (db-type) is suggested.
![2019-01-09 4 58 35](https://user-images.githubusercontent.com/42257727/50885104-1d0eb680-1430-11e9-8092-47714b59affc.png)

**WARNING**: When you see HIVE as a sub-type, it's a DATABASE type dataset, not a STAGING_DB type dataset. For STAGING_DB type, you'll see below.

<Staging DB type I.DS>

*tablename* (STAGING) is suggested.
![2019-01-09 5 04 33](https://user-images.githubusercontent.com/42257727/50885308-aaeaa180-1430-11e9-9bec-c3d889cae2ec.png)

<W.DS>
When you generate a W.DS from I.DS, the default name would be the I.DS name - sub-type.
![2019-01-09 5 08 09](https://user-images.githubusercontent.com/42257727/50885486-32d0ab80-1431-11e9-8deb-db4485153315.png)

When you clone a W.DS, the new W.DS has to have "_W.DS-name_ - copy".
![2019-01-09 5 11 48](https://user-images.githubusercontent.com/42257727/50885679-bab6b580-1431-11e9-9370-228e5c5506b5.png)

**Additional context**
When I tried to upload a TSV file, I got an error like this. It seems like a bug.
![2019-01-09 4 20 58](https://user-images.githubusercontent.com/42257727/50884395-21d26b00-142e-11e9-8459-b034f0a55027.png)

**Comment by ksparknot** [comment]
METATRON-1587

**Comment by minjung-cho** [comment]
@joohokim1 @AnnieHwang @ksparknot 문제 제기된 것은 간단해 보였는데, 화면 여기저기에서 보이는 부분이다 보니 조금 헷갈려서 문서로 정리해 보았습니다. 이해가 다른 부분이 없는지 검토 부탁드립니다-
[#1223-데이터셋네이밍.타입.아이콘-0314.pptx](https://github.com/metatron-app/metatron-discovery/files/2965446/1223-.-0314.pptx)

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang @ksparknot 

네 제안하신대로 진행하시면 될 것 같습니다. 스냅샷 타입에 대한 해결안도 1번째로 추천하신대로, 텍스트로 된 스냅샷 타입 컬럼을 제거하는 방향으로 진행하면 좋을 것 같습니다.

**Comment by koeun222** [comment]
@AnnieHwang 기획에서 정리해주신 문서에 
![image](https://user-images.githubusercontent.com/42256760/54415028-6c2ddc00-473e-11e9-9a8d-53af15d751a9.png)
딱지 붙여서 icon 관련 가이드 업데이트했습니다. 검토부탁드립니다

**Comment by minjung-cho** [comment]
@paigechoi 이름 두줄하고 말줄임 부탁드립니다- @koeun222 툴팁이 뜰 수 없고, 이름 영역이 다소 짧아서 두줄로 요청드렸습니다. 참고 부탁드립니다-

**Comment by minjung-cho** [comment]
지금까지 논의된 내용 기록차 남깁니다.
- 툴팁은 버그(간혹 큰 박스가 뜸?) 수정 후, 추가하기로 함
- 20자폭으로 2줄 후 말줄임하는 것으로 우선 진행함. 단, 아이콘이 작게 보이는 문제가 있어서 확인 후 수정될 수 있음

**Comment by gochemjackets** [comment]
@minjung-cho 
아이콘의 이름(20자폭으로 2줄) - 완료
툴팁은 버그(간혹 큰 박스가 뜸?), 20자씩 모든 툴팁의 내용 출력 - 완료
![image](https://user-images.githubusercontent.com/29448764/55064023-99727680-50bc-11e9-837e-6d4701d3a3a9.png)

**Comment by minjung-cho** [comment]
@paigechoi 세부 조정은 #1745 이슈와 함께 봐야 할것 같습니다. 기능적으로는 된것 같네요~
