### ISSUE TITLE
When using the first row as a header in the data source creation, the first value line disappears.

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1229]
**Describe the bug**
데이터소스를 생성할 때 'Use the first row as the head column.'를 체크하고 데이터소스를 생성하면 첫번째 값 행이 사라집니다.

데이터소스 생성 화면
<img width="1082" alt="2019-01-10 12 44 53" src="https://user-images.githubusercontent.com/28773903/50945986-a975b380-14da-11e9-89e0-d319a98631fe.png">
데이터소스 상세 화면 
<img width="1369" alt="2019-01-10 12 39 00" src="https://user-images.githubusercontent.com/28773903/50946025-dfb33300-14da-11e9-8b3b-ec244edc3621.png">

**Expected behavior**
데이터소스를 생설할  어떤 행도 사라지면 안됩니다.

**Comment by kyungtaak** [comment]
#1235 pr 에서 함께 수정하였습니다.
