### ISSUE TITLE
Remove 'Physical' Terminology(MDM)

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#1238]
**Is your feature request related to a problem? Please describe.**
이 이슈는 MDM 개편 이슈에서 파생되었습니다.
데이터소스와 메타데이터가 동일한 논리정보를 가져감으로써 (컬럼명을 제외한) 이름을 일일히 물리/논리명으로 나눌 필요가 없습니다. 다음과 같이 정리합니다.

Data name : 데이터소스, 메타데이터 동일한 이름 사용
Description: 데이터소스, 메타데이터 동일한 설명 사용
Role: 적재 이후에 변경할 수 없는 값입니다. 적재시점의 Role를 데이터소스/메타데이터 동일하게 사용합니다.
Type: 특정의 변경할 수 없는 타입(예. 타임스탬프)을 제외한 나머지 타입들은 변경가능합니다. 기존의 논리타입을 데이터소스/메타데이터 동일하게 사용합니다.
Column name: 컬럼명, 논리 컬럼명으로 구분. 쿼리등을 위해 (물리)컬럼명이 필요합니다. 더불어 시각화 단계에서 사용하기위한 논리컬럼명도 필요하여 이것은 기존의 형태로 유지합니다.

**Describe the solution you'd like**
아래는 수정대상 목록입니다. 빠진 화면이 있다면 위의 규칙에 의해 수정 부탁드립니다.

1. Datasource > 상세정보 > 필터 정의화면
![2019-01-10 8 37 31](https://user-images.githubusercontent.com/42257766/50967449-8c150980-151b-11e9-89c2-e6df4480462b.png)

2.Datasource > 상세정보 > 컬럼 스키마 설정
![2019-01-10 8 37 37](https://user-images.githubusercontent.com/42257766/50967538-be266b80-151b-11e9-949e-528018d7aee3.png)

3. 메타데이터 > 컬럼 스키마
![2019-01-10 8 37 43](https://user-images.githubusercontent.com/42257766/50967543-c1215c00-151b-11e9-9e6a-0b111e48e95e.png)

4. 메타데이터 > 컬럼 딕셔너리
![2019-01-10 8 37 48](https://user-images.githubusercontent.com/42257766/50967549-c54d7980-151b-11e9-9603-14aec04d05c2.png)

5. 메타데이터 > 컬럼딕셔너리 > 상세
![2019-01-10 8 37 53](https://user-images.githubusercontent.com/42257766/50967552-c8486a00-151b-11e9-85d3-018239ea73e9.png)

6. 대시보드 > 데이터소스 상세 > 컬럼 정보
![2019-01-10 8 37 58](https://user-images.githubusercontent.com/42257766/50967560-cda5b480-151b-11e9-8758-f73a03ca0c1f.png)

7. 대시보드 > 차트 > 차원/측정값 상세
![2019-01-10 8 38 10](https://user-images.githubusercontent.com/42257766/50967569-d302ff00-151b-11e9-976a-f367d93bccb8.png)

8. 워크벤치 > 데이터 스키마 상세
![2019-01-31 2 02 08](https://user-images.githubusercontent.com/42257766/52031644-e0cb0380-2560-11e9-9bd2-f413ec9c4ebc.png)
.
.
**Additional context**
관련이슈: 
- [#1237](https://github.com/metatron-app/metatron-discovery/issues/1237)
- [#344](https://github.com/metatron-app/metatron-discovery/issues/344)

**Comment by ninezero90hy** [comment]
@deidera08 `3. 메타데이터 > 컬럼 스키마` 수정했습니다

 - - -

<img width="677" alt="2019-02-18 5 24 35" src="https://user-images.githubusercontent.com/41019113/52937334-377a6f00-33a2-11e9-8d79-71b74da55f42.png">

 - - -

- 한글
<img width="1680" alt="2019-02-18 5 23 25" src="https://user-images.githubusercontent.com/41019113/52937373-4e20c600-33a2-11e9-8d5e-88ec4435497e.png">

- 영문
<img width="1680" alt="2019-02-18 5 23 46" src="https://user-images.githubusercontent.com/41019113/52937374-4eb95c80-33a2-11e9-8b09-7a48f48ca2a7.png">

- 중문
<img width="1680" alt="2019-02-18 5 24 16" src="https://user-images.githubusercontent.com/41019113/52937375-4eb95c80-33a2-11e9-8966-890fbc0f6657.png">

- `물리 컬럼 이름` 변경
  - 컬럼 이름
  - Column name
  - 科勒姆名字
- `논리 타입` 변경
  - 타입
  - Type
  - 類型

**Comment by ninezero90hy** [comment]
@deidera08 메타데이터 > 새로운 용어 사전 생성의 `Logical Type`도 `Type`으로 변경하겠습니다

 - - -

<img width="1680" alt="2019-02-18 6 28 58" src="https://user-images.githubusercontent.com/41019113/52941189-8b3d8600-33ab-11e9-806d-62941fd4451b.png">

 - - -

**Comment by brandon-wonjune** [comment]
데이터소스 > 상세화면 > 필터 수정 및 스키마 수정 팝업 변경하였습니다.
![2019-02-18 6 33 37](https://user-images.githubusercontent.com/42233627/52941326-d8215c80-33ab-11e9-880e-0245c03218ab.png)
![2019-02-18 6 33 53](https://user-images.githubusercontent.com/42233627/52941327-d8215c80-33ab-11e9-9e58-3881ad6d98cc.png)

**Comment by ninezero90hy** [comment]
@deidera08 `4. 메타데이터 > 컬럼 딕셔너리` 수정했습니다

- - -

- 한글
<img width="1680" alt="2019-02-18 6 40 12" src="https://user-images.githubusercontent.com/41019113/52942026-6f3ae400-33ad-11e9-9698-9b88842cb8fc.png">

- 영문
<img width="1678" alt="2019-02-18 6 40 33" src="https://user-images.githubusercontent.com/41019113/52942028-6fd37a80-33ad-11e9-8dd8-65efeb8f2ec6.png">

- 중문
<img width="1680" alt="2019-02-18 6 40 51" src="https://user-images.githubusercontent.com/41019113/52942029-6fd37a80-33ad-11e9-94bf-591910f2aef0.png">

- - -

**Comment by ninezero90hy** [comment]
@deidera08 `5. 메타데이터 > 컬럼딕셔너리 > 상세` 수정했습니다

- - -

- 한글
<img width="1680" alt="2019-02-18 6 49 00" src="https://user-images.githubusercontent.com/41019113/52942273-0607a080-33ae-11e9-8e41-d38b223a8d87.png">

- 영문
<img width="1680" alt="2019-02-18 6 49 18" src="https://user-images.githubusercontent.com/41019113/52942274-06a03700-33ae-11e9-9d97-e15acf01dd6a.png">

- 중문
<img width="1680" alt="2019-02-18 6 49 34" src="https://user-images.githubusercontent.com/41019113/52942275-06a03700-33ae-11e9-8e8b-3ab650b34d05.png">

- - -

**Comment by ninezero90hy** [comment]
@deidera08 `메타데이터 > 새로운 용어 사전 생성` 수정했습니다

- - -

- 한글
<img width="1679" alt="2019-02-18 6 52 16" src="https://user-images.githubusercontent.com/41019113/52942554-8a5a2380-33ae-11e9-9c72-a7f66800a66d.png">

- 영문
<img width="1680" alt="2019-02-18 6 52 52" src="https://user-images.githubusercontent.com/41019113/52942557-8af2ba00-33ae-11e9-8774-faa371a33d64.png">

- 중문
<img width="1680" alt="2019-02-18 6 53 13" src="https://user-images.githubusercontent.com/41019113/52942558-8af2ba00-33ae-11e9-8e9a-083d9d5ef52f.png">

- - -

**Comment by ninezero90hy** [comment]
@deidera08 7. 대시보드 > 차트 > 차원/측정값 상세화면에 `Logical column name`도 `Column name`으로 수정하겠습니다

<img width="1680" alt="2019-02-19 10 47 23" src="https://user-images.githubusercontent.com/41019113/52984774-2da14c00-3434-11e9-9940-f71c8aa2c76c.png">

**Comment by ninezero90hy** [comment]
@deidera08 `대시보드 > 차트 > 차원/측정값 상세화면` 수정, 기존에 메세지 다국어 처리가 되어있지 않아서 다국어 메세지도 처리했습니다

- - -

- 한글
<img width="1680" alt="2019-02-19 11 37 56" src="https://user-images.githubusercontent.com/41019113/52986641-97712400-343b-11e9-8513-7ed6694cdfbf.png">

- 영문
<img width="1679" alt="2019-02-19 11 38 39" src="https://user-images.githubusercontent.com/41019113/52986642-97712400-343b-11e9-8a36-1d1f70ff0a4c.png">

- 중문
<img width="1680" alt="2019-02-19 11 39 11" src="https://user-images.githubusercontent.com/41019113/52986643-9809ba80-343b-11e9-8c1b-5e7a88975f99.png">

**Comment by ninezero90hy** [comment]
@deidera08 `8. 워크벤치 > 데이터 스키마 상세`화면 메세지 수정했습니다

- - -

<img width="1680" alt="2019-02-19 1 19 11" src="https://user-images.githubusercontent.com/41019113/52989963-318b9900-3449-11e9-8375-aea41fa00fb2.png">

- - -

**Comment by brandon-wonjune** [comment]
@deidera08 
데이터 미리보기 화면 아래와 같이 수정하였습니다.
![2019-02-19 7 41 54](https://user-images.githubusercontent.com/42233627/53009444-e1c7c480-347e-11e9-9768-2c723e8d5966.png)
![2019-02-19 7 43 27](https://user-images.githubusercontent.com/42233627/53009447-e1c7c480-347e-11e9-8eef-3483697c057a.png)
