### ISSUE TITLE
Enable to edit column's logical information of datasource and sync with column of metadata

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#1245]
**Is your feature request related to a problem? Please describe.**
[#1237]이슈의 연장 이슈입니다.

**Describe the solution you'd like**
데이터소스의 논리정보 수정시 해당 메타데이터의 정보 또한 동반수정되며, 반대 상황도 같습니다.
더불어 메타데이터에서 데이터소스 외 Database 계열은 상세화면에 Data grid를 추가합니다.

**Describe alternatives you've considered**
1. 데이터소스 > 컬럼 상세화면
타입 변경시 메타데이터 또한 반영되며, 가이드 문구 노출
![default](https://user-images.githubusercontent.com/42257766/51020415-ccc75e00-15c1-11e9-83cd-3b87ad76f00d.png)
.
.
2. 데이터소스 > 컬럼 상세화면 > 스키마 설정
논리컬럼명, 타입, 설명 변경시 메타데이터 또한 반영되며, 가이드 문구 노출
![2019-02-26 1 24 59](https://user-images.githubusercontent.com/42257766/53387380-fd285780-39c9-11e9-8863-be902e9f65c1.png)
.
.
3. 메타데이터 > (데이터소스가 아닐경우) 데이터그리드 화면 추가
![default](https://user-images.githubusercontent.com/42257766/51020413-ccc75e00-15c1-11e9-9af5-60db8a2df532.png)
.
.
4. 메타데이터 > 컬럼 스키마
(데이터소스일 경우) 논리컬럼명, 타입, 설명 변경시 데이터소스 또한 반영되며, 가이드 문구 노출
![default](https://user-images.githubusercontent.com/42257766/51020412-cc2ec780-15c1-11e9-8bff-19a008e276b2.png)
.
.
**Additional context**
관련이슈:
- [#1237](https://github.com/metatron-app/metatron-discovery/issues/1237)

**Comment by koeun222** [comment]
@AnnieHwang 화면 공유드립니다- 
1.데이터소스 > 컬럼 상세화면 : 가이드문구 기존 공통 ui로 퍼블 적용부탁드립니다
2.데이터소스 > 컬럼 상세화면 > 스키마 설정 : 가이드문구를 공통ui로 팝업상에서의 알림 문구를 노출할수있는 영역으로 적용했습니다 (종류는 인포, 참고, 에러 3종류있습니다) 
![image](https://user-images.githubusercontent.com/42256760/52694332-ab84d380-2fac-11e9-8f82-47384589e4b1.png)

3.메타데이터 > (데이터소스가 아닐경우) 데이터그리드 화면 추가
![image](https://user-images.githubusercontent.com/42256760/52694426-09192000-2fad-11e9-8a73-2b275bee43aa.png)

4.메타데이터 > 컬럼 스키마 : 가이드문구 영역 추가. 2번화면과 통일성있게 맞춤. 
![image](https://user-images.githubusercontent.com/42256760/52694318-9c9e2100-2fac-11e9-8073-bd30ca398589.png)

**Comment by deidera08** [comment]
@kyungtaak @eltriny @brandon-wonjune 
이 이슈 작성당시 Timezone이나 Geo타입에 대한 내용이 없었는데, 현재 시점에서 Column details에서 타입을 변경할 수 있는 기능을 삭제해야 하지 않나 싶습니다.
예로 string타입을 date/time으로 바꾸면 데이터그리드에 오류가 납니다.
때문에 1번 사항은 일단 무시하시고 진행부탁드립니다.
(해당 이슈를 생성 후 공유드리도록 하겠습니다.)

**Comment by ninezero90hy** [comment]
해당 이슈는 #1237 이슈에서 같이 처리하도록 하겠습니다

**Comment by deidera08** [comment]
@kyungtaak @eltriny @ninezero90hy @AnnieHwang 
3번 사항은 Metadata에 Database계열 등록하는 부분이 선행되어야 할 듯 합니다(현재는 Hive만 지원)
이 이슈에서 다루기엔 일감이 큰 것 같아서 이 이슈에서는 3번 사항은 배제하고, 새 이슈로 등록하여 진행하면 어떨까 합니다.
(이슈 등록하여 공유드리도록 하겠습니다)

**Comment by ninezero90hy** [comment]
@deidera08 **4. 메타데이터 > 컬럼 스키마 : 가이드문구 영역 추가. 2번화면과 통일성있게 맞춤.** 수정했습니다

<img width="1678" alt="2019-02-27 3 28 27" src="https://user-images.githubusercontent.com/41019113/53470285-7ac09600-3aa4-11e9-94e5-f1852a5fd218.png">

**Comment by joohokim1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [데이터소스 생성시 메타데이터 싱크](https://trello.com/c/utlZD0Kg/1-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%86%8C%EC%8A%A4-%EC%83%9D%EC%84%B1%EC%8B%9C-%EB%A9%94%ED%83%80%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%8B%B1%ED%81%AC)
