### ISSUE TITLE
distinguish server error code in dataprep

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1253]
**Is your feature request related to a problem? Please describe.**
For undefined errors, I can not distinguish between errors from the server and errors from the UI.

_정의되지 않은 에러의 경우, 서버에서 나는 에러인지 UI에서 나는 에러인지 구분이 안갑니다._

**Describe the solution you'd like**
If an undefined error occurs, it is better to give an error of unknown **server** error.

_서버에서는 정의되지 않은 에러가 발생한 경우 unknown **server** error라고 에러를 내는 것이 좋겠습니다._

**Describe alternatives you've considered**
We can make unknown errors from UI code to show unknown ** UI ** error.
The best is to use **server**, **U ** on both sides.

_UI에서 발생하는 정의되지 않은 에러를 unknown **UI** error라고 하는 방법도 있습니다.
제일 좋은 것은 양측 모두 **server**, **UI**를 구분해서 쓰는 것입니다._

**Comment by kyungtaak** [comment]
@joohokim1 해당 사항은 공통으로 논의하는것이 좋을것 같습니다.

**Comment by joohokim1** [comment]
@eltriny This issue has been cleared by UI. UI code doesn't use unknown error anymore.
