### ISSUE TITLE
 Fail to process response error when downloading original data.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1276]
**Describe the bug**
- 원본 데이터를 다운로드 하는 경우 Fail to process response 에러 발생함

**To Reproduce**
- 아래 주소에서 재현 가능함
http://52.231.184.135:8180/app/v2/workbook/b9371961-fbe3-4321-9415-529f4da1a111

**Comment by alchan-lee** [comment]
#1297에서 해결되었으며, 
이번 이터레이션(3.2.0-rc1)에 포함됩니다.
