### ISSUE TITLE
Apply new suggestion to Window, aggregate, pivot.

### ISSUE THREAD

**Issue by nowone123** [metatron-app/metatron-discovery#1289]
**Is your feature request related to a problem? Please describe.**
 apply new autocomplete function.

**Describe the solution you'd like**
 - window, aggregate, pivot of rules.
 - multiple input box.

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by nowone123** [comment]
@joohokim1 
aggregate 및 pivot Rule에서 Column Name backtick(``)으로 감싸면 에러 가 발행합니다. 
서버에서 backtick(``) 관련 처리가 필요합니다.

**Comment by joohokim1** [comment]
@nowone123 
알겠습니다. 작업 후 알려드리겠습니다.

**Comment by joohokim1** [comment]
@nowone123 
We now have the server handle aggregate, pivot, and window expressions as expression structures.
As a note, we used to use a literal to process the expressions through a string match.

이제 서버에서 aggregate, pivot, window의 수식을 expression 구조체로 처리하도록 했습니다.
참고로, 기존에는 literal로 받아서,  string match를 통해 수식 계산을 수행했었습니다.

**Comment by joohokim1** [comment]
2nd integrated test passed.
