### ISSUE TITLE
Please support chinese currency option.

### ISSUE THREAD

**Issue by devarchi33** [metatron-app/metatron-discovery#1291]
<img width="319" alt="screen shot 2019-01-21 at 22 54 22" src="https://user-images.githubusercontent.com/7742818/51481778-995dae00-1dcf-11e9-8521-9171368da3dc.png">

위 통화선택 옵션에 중국 위안화 추가 요청드려요.

**Comment by kyungtaak** [comment]
@devarchi33 중국어도 지원하는데..;; 놓치고 있었네요. 추가해 두도록 하겠습니다. 요청 감사합니다. ^^

**Comment by kyungtaak** [comment]
@devarchi33 #1313 pr 을 통해 추가해두었습니다.
