### ISSUE TITLE
Support pluggable data connection

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#1295]
**Is your feature request related to a problem? Please describe.**
We hope to add feature extension support to metatron discovery.

**Describe the solution you'd like**
Apply extension framework to discovery

**Describe alternatives you've considered**

**Additional context**

**Comment by ufoscw** [comment]
@brandon-wonjune 
아래 사항 확인 부탁드려요.
1. extension connection 정보 조회 API가 추가되었는데 연동하는 작업이 되어 있는지 확인해주세요.
```
(GET) /api/extensions/connection
```

2. connection parameter에 sid가 누락되고 있습니다. 추가되었나요?
제가 확인한 건 아래 2건의 API 호출시 입니다. 더 있을수도 있습니다.
```
/api/connections/query/data
/api/connection/query/tables
```

3. 현재 1295 브랜치로 빌드해보면 Connection 생성시 아이콘이 하나도 안나오네요.

**Comment by brandon-wonjune** [comment]
@ufoscw 
1. extension connection 정보와 연동되어있는것 확인했습니다.
```
// api
api/extensions/connection
```
![스크린샷 2019-03-22 오후 3 32 24](https://user-images.githubusercontent.com/42233627/54804688-bde2e300-4cb7-11e9-84ec-14034725795a.png)

2. 누락된 것 추가하였습니다.

3. 현재 커넥션 목록에서 iconResource1을 바라보고있는데 해당 값이 없어서 아이콘이 나오지 않는 상태입니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
3. 음 Embedded 타입의 커넥션은 frontend에서 아이콘 처리 해주시면 될것 같습니다.
Extension의 경우는 iconResource를 속성을 사용하면 될것 같습니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 그러면 Embedded에 해당하는 DB가 어떤것이 있는지 알수있을까요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
현재 사용중인 커넥션 타입입니다.
MYSQL, HIVE, DRUID, POSTGRESQL, PRESTO

**Comment by brandon-wonjune** [comment]
@ufoscw 
Embedded의 경우 기본아이콘을 사용, 
Extension의 경우 iconResource1을 사용하되 값이 없는경우 기본이미지를 사용하도록 수정하였습니다.
![스크린샷 2019-03-22 오후 4 03 02](https://user-images.githubusercontent.com/42233627/54806003-187e3e00-4cbc-11e9-94f4-5d50ef03715a.png)

**Comment by ufoscw** [comment]
@brandon-wonjune 
workbench의 LNB, SchemaBrowser에서 iconResource1, IconResource2 속성이 존재할 경우는 custom icon이 아니라 iconResource를 사용하도록 수정이 필요합니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
authentication : dialog 인 커넥션 생성 후 워크벤치 진입하여 check api 호출할때도 sid 파라미터 누락됩니다.
<img width="264" alt="DevTools_-_localhost_8180_app_v2_index_html" src="https://user-images.githubusercontent.com/3770446/54810052-64cf7b00-4cc8-11e9-875e-163886172a80.png">

아래는 front에서 호출한 API입니다.
```
/api/connections/query/check
```

**Comment by ufoscw** [comment]
@brandon-wonjune @eltriny 
현재 까지 작업된 내용에서 추가 작업 필요한 내역입니다.
1. api에서 sid 파라미터 누락
2. workbench에서 extension 타입의 아이콘 처리
3. Datasource 생성 > database 선택시 extension connection 지원
