### ISSUE TITLE
Modify file type snapshot information

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1296]
**Describe the bug**
Some detailed information is missing in snapshot detail and list

**To Reproduce**
1. Go to snapshot detail -> check snapshot type
![image](https://user-images.githubusercontent.com/42233517/51508545-0bb6a880-1e39-11e9-90c6-f164aa9c6267.png)

2 . Show file uri (only when snapshot type is file)

**Expected behavior**
1 . Snapshot type should be FILE(CSV) or FILE(JSON)

2 . Snapshot file uri should be visible
![image](https://user-images.githubusercontent.com/42233517/51658750-6f350780-1fec-11e9-9966-a9ab03063cd1.png)

3 . Rows and column should be on the separate line
![image](https://user-images.githubusercontent.com/42233517/51658808-95f33e00-1fec-11e9-96fd-07aee27d95a0.png)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by paigechoi** [comment]
storedUri LABEL

**Comment by joohokim1** [comment]
2nd integrated test passed.
