### ISSUE TITLE
 Support for regular expressions when entering wildcard filters.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1298]
**Is your feature request related to a problem? Please describe.**
- 와일드카드로 필터링 하는 경우 정규표현식 지원이 되지 않아 필터 사용에 제한적인 상황임
![wildcard_regex](https://user-images.githubusercontent.com/612173/51510317-f133fd80-1e3f-11e9-8782-9180ed325c08.png)

**Describe the solution you'd like**
- 와일드카드에서 정규표현식을 지원함

**Comment by minjung-cho** [comment]
@Taehui @AnnieHwang 
#944에서 서버의 값을 대상으로 하는 텍스트 검색 기능이 진행되고 있습니다. 이 UI(텍스트 입력 영역)에서 와일드카드의 표현식을 지원하면 어떨지요?

**Comment by Taehui** [comment]
@minjung-cho, @kyungtaak  944 이슈는 마스터에 머지되는 시점을 언제로 봐야하나요? @YooYoungmo 기획 내용도 심플하고 좋아보이긴 한데요...

**Comment by YooYoungmo** [comment]
@kyungtaak 네 좋네요.

**Comment by YooYoungmo** [comment]
@kyungtaak @minjung-cho 
변경한 화면 공유 합니다. 마크업을 대강 맞추었는데요. @minjung-cho 님 처럼 미려하진 않습니다. 
 @minjung-cho 님 마크업 공유해 주시면 그것으로 반영하겠습니다.
![image](https://user-images.githubusercontent.com/16472109/51650709-94198280-1fcc-11e9-98dd-cf3bd203a422.png)

**Comment by minjung-cho** [comment]
@AnnieHwang 기획서에 @YooYoungmo 님이 요청하신 안을 반영하려고 합니다. 디자인 요청드렸는데, 다른 의견 있으면 부탁드립니다-

**Comment by YooYoungmo** [comment]
@kyungtaak @minjung-cho @AnnieHwang 
마크업 통합 작업을 아래 처럼 했으면 하는데 어떠신가요?
먼저 제가 임의로 만든 마크업으로 동작하는 코드를 만들어서 PR 해서 기능 검증을 합니다.(늦어도 오늘까지는 PR할 생각입니다.)
그리고 마크업 작업이 끝나시면 제가 PR한 이슈에 코멘트를 달아 주시면(마크업을 어떤식으로 바꿔라 ) 이를 제가 다시 코드에 반영하는 것입니다.

**Comment by kyungtaak** [comment]
@YooYoungmo 음. 제가 생각하기엔 모두 진행한다음에 pr 을 진행했으면 합니다. 지금 현재 마크업 담당자와 커뮤케이션이 되지않아 늦어지는것 같은데요. @eltriny 확인 부탁드립니다.

**Comment by AnnieHwang** [comment]
@YooYoungmo 저희가 저 부분 디자인 넘겨서요. 그 부분 퍼블 넘긴 후 받으면 2일 걸릴꺼 같은데 괜찮으세요? @kyungtaak 아님 일단 저 상태로 PR 하시고 다른 이슈로 디자인 마무리 할까요?

**Comment by YooYoungmo** [comment]
@AnnieHwang 네 알겠습니다~

**Comment by koeun222** [comment]
@YooYoungmo 네네 퍼블 오늘완료 된걸로 확인했습니다- 
![image](https://user-images.githubusercontent.com/42256760/52550945-a9403f00-2e1d-11e9-88dd-e6626393e1eb.png)

**Comment by YooYoungmo** [comment]
@koeun222 제가 화면 추가 작업해야 하는데 마크업 코드는 어디서 확인이 가능한가요?

**Comment by AnnieHwang** [comment]
@YooYoungmo 너무 늦게 전달되서 죄송해요. 퍼블 결과는 퍼블작업을 해주시는 개발팀 @eltriny 담당자분께서 작업 결과 위치 알려주실수 있으실꺼 같아요.

**Comment by YooYoungmo** [comment]
머지된 이슈로 Close 합니다.
