### ISSUE TITLE
Hiding aggregate tooltip

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1300]
**Describe the bug**
Tooltip message z-index error (tooltip is hidden behind list)

**To Reproduce**
Go to dataflow main grid -> choose aggregate rule -> click expression input -> hover aggregation icon
![image](https://user-images.githubusercontent.com/42233517/51513277-69ed8680-1e4d-11e9-9ffe-3ca0db0d2a09.png)

**Expected behavior**
Tooltip should be on the very top

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
2nd integrated test passed.
