### ISSUE TITLE
 Workspaces are not created under certain conditions in I.E Browser.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1308]
**Describe the bug**
- 특정 조건에서 워크스페이스가 생성되지 않는 버그

**To Reproduce**
1. 인터넷익스플로러에서 공유워크스페이스 생성화면으로 이동
2. 워크스페이스 이름입력
3. 디스크립션 입력 없이 퍼미션 스키마 선택
4. 마침 버튼 클릭

--> 수행하면 뺑글이 무한루프에 빠짐

**Comment by YooYoungmo** [comment]
# 문제 확인
IE에서 퍼미션 스키마를 선택하면 `마침` 버튼이 비활성화 상태(회색)임
이 상태애서 클릭이 가능하고 사용자가 클릭하면 로딩 이미지만 노출됨
![image](https://user-images.githubusercontent.com/16472109/52460142-45630f80-2bac-11e9-9f10-e40cdb5e7ea2.png)

하지만 `사용자의 역할` 표 부분을 클릭하면 `마침` 버튼이 활성화 되고 이 상태에서 클릭하면 정상적으로 공유 워크스페이스가 생성됨
![image](https://user-images.githubusercontent.com/16472109/52460302-f10c5f80-2bac-11e9-9fce-731e91983ab6.png)

## 테스트 환경
* IE
![image](https://user-images.githubusercontent.com/16472109/52460362-3c267280-2bad-11e9-9956-555cf68bbbbd.png)

* Metatron 3.2.0-rc2

**Comment by YooYoungmo** [comment]
# 원인
`Permission schema` 선택 시 스크립트 오류 발생
![image](https://user-images.githubusercontent.com/16472109/52460498-fb7b2900-2bad-11e9-8ce6-a7b2797397d3.png)

**Comment by YooYoungmo** [comment]
머지된 이슈이므로 Close 합니다.
