### ISSUE TITLE
Error in multi column rename popup

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1319]
**Describe the bug**
- Validation check in multiple column rename popup is wrong.
- When tab button is pressed, action should be same as click

**To Reproduce**
Go to dataflow main grid -> select command rename -> click rename multiple columns -> 
change column name to 02 -> see error

**Expected behavior**
1 . Column name accepts all characters except back tick
2 . Allow input navigation with tab

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
1st integration test checked.
