### ISSUE TITLE
Upload JSON files as JSON not CSV

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1327]
**Is your feature request related to a problem? Please describe.**
Currently, JSON files are converted into CSV files as uploading to the designated location.
It's not helping with the performance and moreover, it's confusing.

**Describe the solution you'd like**
Upload as JSON files, and apply JSON read/write library as we access later on.

**Describe alternatives you've considered**
If it's hard or there's trouble to change the code. We can just leave it alone. It works without a big problem now.

**Comment by ksparknot** [comment]
This issue has already been resolved because it is related to these issues.

https://github.com/metatron-app/metatron-discovery/issues/1376
https://github.com/metatron-app/metatron-discovery/issues/1455
