### ISSUE TITLE
Auto-add a rename rule for Hive snapshot

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1331]
**Is your feature request related to a problem? Please describe.**
Column names containing unicode and space, and so on cannot be accepted in Hive.
Currently, if there are forbidden column names, an error occurs with direction to rename them.

![2019-01-29 3 20 29](https://user-images.githubusercontent.com/42257727/51888148-7fc4f380-23d9-11e9-82ff-0d8b301de4d6.png)

**Describe the solution you'd like**
It would be better if we help to append a rename rule.
In stead of sending the request, UI should show multi-column rename pop-up.
We can fill with appropriate names in advance like below.

![2019-01-29 3 25 18](https://user-images.githubusercontent.com/42257727/51888338-201b1800-23da-11e9-88e7-5f93f081bdca.png)

**Additional context**
Hangul unicode letter -> Romanize (https://www.npmjs.com/package/aromanize)
Space -> _
Column names containing other unicode letters -> just column1, column2, etc.

**Comment by minjung-cho** [comment]
METATRON-1533에서 발췌한 추천 이름 규칙입니다.
- 한글은 로마자로 변경
- 한글 이외 유니코드가 하나라도 포함된 컬럼인 경우에는 column1, column2, ...
- 공백은 _ 로 변경
- 대문자는 소문자로 변경

**Comment by minjung-cho** [comment]
Rename 팝업에 내용 추가하였습니다.
![스크린샷 2019-03-12 오후 2 14 04](https://user-images.githubusercontent.com/28773903/54176175-228c8980-44d1-11e9-8c04-f95586c6ad1a.png)
@joohokim1 @kaypark-sk 
컬러명 자동 추천은 Rename 공통 룰에 해당할까요? 하이브 타입 스냅샷 생성시에만 적용되어야 할까요?
@paigechoi 포커스 컬럼에 따라 그리드가 이동하는 이슈를 묶어도 될듯합니다만.. 혹시 별도 이슈가 있는지요?

**Comment by paigechoi** [comment]
https://github.com/metatron-app/metatron-discovery/issues/1638 scroll이슈입니다

**Comment by minjung-cho** [comment]
@koeun222 데이터 그리드의 포커스 부분 디자인은 #1638로 분리 부탁드립니다

**Comment by joohokim1** [comment]
@minjung-cho @ksparknot 
컬럼명 자동 추천은 Hive 스냅샷을 만들다가 문제가 되는 경우만 해주면 될 것 같습니다.
Hive snapshot 생성을 요청하면 "Hive에 저장되기에 적합하지 않은 컬럼명이 있습니다. 전체 rename 창을 띄울까요?" 정도 dialog 창이 뜨면 좋겠습니다. 여기서 Yes인 경우에 한해서 컬럼명 자동 추천을 하면 좋겠습니다.

**Comment by minjung-cho** [comment]
@joohokim1 @AnnieHwang 네, 이해했습니다. 의견 주신 부분 반영한 기획서 입니다. 이해가 다른 부분이 없는지 한번 더 검토 부탁드립니다-
![스크린샷 2019-03-13 오후 4 25 13](https://user-images.githubusercontent.com/28773903/54260586-acf5eb80-45ac-11e9-8bc5-044c51c40867.png)
![스크린샷 2019-03-13 오후 4 25 13](https://user-images.githubusercontent.com/28773903/54260598-b3846300-45ac-11e9-8630-0c6f1a762f08.png)

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang @ksparknot @sang-hee-lee @paigechoi 

1. 예 / 아니오 다이얼로그 추가
2. 기존 multi-column rename 화면/코드 활용
3. 단 Hive에 적합한 컬럼명 선기입 (확인X 제약X)

전 위처럼 간단하게 처리하고 넘어가려고 했거든요. 그래서 본 SP에 할 수 있을 것으로 생각했는데, 제안하신 것처럼 새 화면이나 제약 조건 등이 들어가야한다면, 시간이 별로 없을 것 같습니다.

제가 지금까지 받은 VoC로는 위의 간단한 처리로도 괜찮은 것 같은데, 이번 마일스톤에 빨리 태우고, 다음에 더 개선하는 것은 어떨런지요?

**Comment by minjung-cho** [comment]
@joohokim1  @sang-hee-lee @paigechoi 네, 제가 보기엔 기존 화면을 활용하는 선인것 같은데 그게 아닌가 보네요 ㅎ 어떻게 끊을지 결정해서 알려주시면 참고하고 있겠습니다-

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang @ksparknot @sang-hee-lee @paigechoi 

유선으로 대화 나눈 것처럼, 이번 SP에는 간단히 진행해서, 마일스톤내에 태우기로 하고, 다음 번에 더 UX를 보완하기로 했습니다.
