### ISSUE TITLE
Workbench, Separate the number to display and the number of resultset.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#135]
**Is your feature request related to a problem? Please describe.**

. 워크벤치 쿼리 실행 시 WAS 내에 조회되는 결과에 대한 Property 설정 필요 (100만건)
. 100만건 조회된 결과 중에서 그리드로 출력되는 Output Console 에 대한 Property 설정 필요(1000건)
. 다운로드 실행 시 100만건 내의 결과는 재실행 없이 다운로드 제공

**Describe the solution you'd like**
* AS-IS
numRows 파라미터 갯수만큼 Response 전달
numRows이상의 데이터를 CSV로 다운로드 할 경우 API 재호출

* TO-BE
numRows파라미터와 상관없이 maxResultSize 갯수만큼 Response 전달하며 grid 표시할 때 numRows만큼만 표시함.
CSV 다운로드시 전체 데이터가 이미 Client에 전달되었으니 API 재호출 없이 CSV 생성가능
maxResultSize 속성 정의하지 않을 경우 기존과 같이 동작함.

* explicitResultSize 속성 추가
polaris.workbench.explicitResultSize 속성이 추가되었으며 운영자가 해당 속성을 0 이상의 값으로 지정할 경우 workbench를 통해 수행되는 모든 쿼리의 최대 row 숫자는 explicitResultSize으로 지정되며 해당 결과를 response에 포함시킨다.
클라이언트에서도 이를 판단할 수 있도록 QueryResult Response에 explicitResultSize 속성이 추가됨.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ufoscw** [comment]
@AnnieHwang 
해당 건에 대해 기획팀에서 UI 쪽 검토가 필요합니다.
추가 속성이 필요하다는건 파악되었으나 UI에 어떻게 적용할지에 대해 검토 부탁드립니다.

**Comment by AnnieHwang** [comment]
@ufoscw 그럼 전체 다운로드는 '전체 다운로드'(100만건)만 남아있게 되는건가요? 전 괜찮은거 같은데요. 그러면 전면에 화면에 뿌리는 건수(1000건) 변경 하는 UI도 없애도 좋을것 같아요. 화면에는 1000건만 뿌려지고 다운로드는 100만건 다운로드 받을 수 있으면, 기존의 요구사항에도 모두 수용될 수 있을것 같아요.

**Comment by ufoscw** [comment]
@AnnieHwang 
운영자가 클라이언트의 메모리 부담을 감수하더라도 쿼리 재수행을 최대한 막기 위해서 제공하는 옵션인데요.
기존 기능과 병행해야 하지 않을까요..

**Comment by AnnieHwang** [comment]
@ufoscw 말씀 하신 내용이 맞고요. 기존기능과 UI는 동일하게 해서 진행하도록 하겠습니다. 기획서 상에는 해당 부분에 노트 남겨두도록 하겠습니다. @eltriny 혹시 이세진님 @esezin 과 말씀해보시고 해당 기능을 개발시 UI상에서 개선할 부분이 있으면 말씀부탁드립니다.

**Comment by ufoscw** [comment]
해당 이슈는 쿼리 결과를 임시로 저장하는 요건과 함께 처리되어야 할것으로 예상됩니다.
우선 백로그로 이동하겠습니다.

**Comment by kyungtaak** [comment]
#471 이슈의 방식으로 처리를 하게 되어 이슈를 종료 합니다.
