### ISSUE TITLE
Introduce engine(druid) monitoring function

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#1373]
**Is your feature request related to a problem? Please describe.**
현재 데이터 소스를 드루이드 적재하고 쿼리를 조회하는 과정에 있어 실패했을 경우 이를 조회하기가 어렵습니다.
더불어 드루이드의 상태체크를 쉽게 접근하기 위하여 모니터링 화면이 필요합니다.

**Describe the solution you'd like**
Data Storage하위에 Engine Monitoring을 추가합니다.
![2019-02-01 3 18 45](https://user-images.githubusercontent.com/42257766/52106497-62409580-2636-11e9-9496-f3a777e9dbb8.png)

Engine Monitoring은 2단계에 걸쳐 구축 예정이며, 첫번째 단위는 Overview, Ingestion, Query를 예정하고 있습니다.
![2019-02-01 3 28 35](https://user-images.githubusercontent.com/42257766/52106501-679de000-2636-11e9-8178-0f74257899b0.png)

본 이슈는 Overview에 해당되는 내용입니다.
![2019-02-01 3 29 31](https://user-images.githubusercontent.com/42257766/52106551-95832480-2636-11e9-8eba-9fe302dd92ca.png)
![2019-02-01 3 29 41](https://user-images.githubusercontent.com/42257766/52106553-96b45180-2636-11e9-95da-4e09573c5825.png)

Overview는 1차 구축 범위 내에 기능이 더 추가될 예정입니다.
와이어프레임 파일을 첨부합니다.
[EngineMornitoringOverview이슈버전.pptx](https://github.com/metatron-app/metatron-discovery/files/2820345/EngineMornitoringOverview.pptx)
참고부탁드립니다.

관련이슈: #1405

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다
1. Overview list
![image](https://user-images.githubusercontent.com/42256760/52542498-8b55e880-2de3-11e9-8896-70c903386420.png)
2.Druid Cluster Information > common
![image](https://user-images.githubusercontent.com/42256760/52542512-b9d3c380-2de3-11e9-9a8d-9ccd3d83e822.png)

**Comment by Taehui** [comment]
@AnnieHwang, @koeun222 모니터링 항목 들은 구체화될 예정인거죠? ppt 파일에 내용은 그냥 property 정도 인 듯 하네요~

**Comment by deidera08** [comment]
@Taehui 
(일정이 촉박하여) 우선 구현할 수 있도록 내용을 많이 축소된 화면으로 이슈등록을 하였습니다.
Overview화면은 좀 더 보완/개편될 예정입니다.

**Comment by deidera08** [comment]
Cluster 정보 팝업 화면이 수정되었습니다.
각각의 node별로 탭을 구성하기 어려운 부분이 있어 삭제하고
한 화면에 Cluster의 전체 정보를 담게 되었습니다.

참고 부탁드립니다.
![2019-02-12 3 23 29](https://user-images.githubusercontent.com/42257766/52615923-32b54700-2eda-11e9-81b6-2294dfa8b5f6.png)

**Comment by ninezero90hy** [comment]
@deidera08 엔진 모니터링 메뉴 순서 확인 부탁드립니다

<img width="655" alt="2019-02-15 2 05 21" src="https://user-images.githubusercontent.com/41019113/52835679-c2e9cb00-312a-11e9-80b7-c0adb80de58e.png">

- 이슈 코멘트에는 데이터 스토리지 하위에 추가해달라고 하셨는데

<img width="470" alt="2019-02-15 2 03 44" src="https://user-images.githubusercontent.com/41019113/52835658-a9e11a00-312a-11e9-8f15-f18c2ccb3baf.png">

- 기획서에는 `엔진 모니터링`이 데이터 모니터링 하위에 있습니다. 이슈에 적어주신대로 데이터 스토리지 다음에 엔진 모니터링 메뉴 추가하면 될까요?

**Comment by deidera08** [comment]
@ninezero90hy 
제가 이슈에 잘못적었네요. 혼동을 드려서 죄송합니다.
표에 나열한대로 Management 하위에 Data Storage와 동일한 Depth로 부탁드립니다.

**Comment by ninezero90hy** [comment]
@deidera08 넵 확인 감사합니다 :)

**Comment by alchan-lee** [comment]
@ninezero90hy 
너무 지연되고 있어서 우선 Overview 화면에서의 조회용 API 먼저 공유 드립니다 😭 
궁금하시거나 더 필요하신 것 있다면 말씀해주세요.


1. Overview - 서버 타입별 상태 조회
- request :`(GET) /api/monitoring/servers/health`
- response body : 
```json
{
    "coordinator": "true",
    "historical": "true",
    "middleManager": "true",
    "broker": "warn",
    "overlord": "true"
}
```

2. Overview - 전체 서버 목록 조회 (상태 포함) 
- request :`(GET) /api/monitoring/`
- response body : 
```json
{
    "_embedded": {
        "monitorings": [
            {
                "id": "a2ba4b2d-90ac-4b7e-9abe-e67407f229c0",
                "type": "overlord",
                "port": "8090",
                "hostname": "localhost",
                "status": "true",
                "_links": {
                    "self": {
                        "href": "http://localhost:8180/api/monitoring/a2ba4b2d-90ac-4b7e-9abe-e67407f229c0"
                    },
                    "monitoring": {
                        "href": "http://localhost:8180/api/monitoring/a2ba4b2d-90ac-4b7e-9abe-e67407f229c0{?projection}",
                        "templated": true
                    }
                }
            },
            {
                "id": "c569271e-b6a7-4dfe-b133-492bcdcb1622",
                "type": "middleManager",
                "port": "8091",
                "hostname": "localhost",
                "status": "true",
                "_links": {
                    "self": {
                        "href": "http://localhost:8180/api/monitoring/c569271e-b6a7-4dfe-b133-492bcdcb1622"
                    },
                    "monitoring": {
                        "href": "http://localhost:8180/api/monitoring/c569271e-b6a7-4dfe-b133-492bcdcb1622{?projection}",
                        "templated": true
                    }
                }
            }
        ]
    },
    "_links": {
        "self": {
            "href": "http://localhost:8180/api/monitoring{?page,size,sort,projection}",
            "templated": true
        },
        "profile": {
            "href": "http://localhost:8180/api/profile/monitoring"
        }
    },
    "page": {
        "size": 20,
        "totalElements": 5,
        "totalPages": 1,
        "number": 0
    }
}
```


3. Overview - 차트 조회
- request :`(POST) /api/monitoring/query`
- request body :
```json
{
	"fromDate": string,
	"toDate": string,
	"granularity": string,
	"monitoringTarget": object,
	"resultFormat": object
}
```

resultFormat은 기존과 그대로 사용해주시면 됩니다.
monitoringTarget의 경우 filter를 간단하게 적용하기 위해 사용되는 값으로
```json
"monitoringTarget": {
		"service": string,
		"host": string,
		"metric": string
	}
```
형태로 이루어지며, metric이 가질 수 있는 값은 아래 4가지 입니다.
- "MEM_MAX"
- "MEM_USED"
- "GC_CPU"
- "GC_COUNT"


- response body : 
```json
{
    "rows": [
        "2019-02-25",
        "2019-02-26",
        "2019-02-27"
    ],
    "categories": [],
    "columns": [
        {
            "name": "value",
            "value": [
                19889536890762,
                23987421705677,
                6886588415250
            ],
            "percentage": []
        }
    ],
    "info": {
        "maxValue": 23987421705677,
        "minValue": 6886588415250
    }
}
```

**Comment by nogah12** [comment]
@alchan-lee 
안녕하세요. Engine Monitoring을 맡게된 서성준 입니다.

현재 Local에서  만들어주신 api호출 하였더니 데이터가 없습니다.
샘플데이터 넣을려면 어떻게 해야 할까요?

**Comment by nogah12** [comment]
@alchan-lee
다음 API 호출 시 서버면, node, 상태 등 필터 기능을 추가 해야 합니다. 

Overview - 전체 서버 목록 조회 (상태 포함)
request :(GET) /api/monitoring/

**Comment by alchan-lee** [comment]
@nogah12 
확인이 늦어진 점 죄송합니다..

말씀하신 API 적용되는대로 공유 드리겠습니다.

**Comment by alchan-lee** [comment]
@nogah12 
아.. 제가 헷갈렸군요 ㅠㅠ
말씀하신 API에 parameter로 조건을 주시면 됩니다.

적용가능한 값은 아래 5가지 입니다.
`id, type, port, hostname, status`

ex) 
(GET) /api/monitoring?id=305a3d69-2693-48cf-9dd0-c343476b589a
(GET) /api/monitoring?type=broker
(GET) /api/monitoring?port=8081
(GET) /api/monitoring?hostname=localhost
(GET) /api/monitoring?status=true

**Comment by alchan-lee** [comment]
그리고 처음에 말씀하신 샘플데이터는 별도로 생성하실 필요없고
10분 주기로 설정을 파싱해서 업데이트 하게 해두었습니다.

별도 설정이 없다면 application.yaml 파일을 참고해서 localhost 정보를 입력하게 되니
로컬에 druid를 실행하신 뒤 테스트하셔야 합니다

**Comment by nogah12** [comment]
@alchan-lee 
로컬에 druid를 실행 하였고 서버에서
EngineMonitoringJob     : ########### engine monitoring job : check server health
실행되는것도 확인 하였지만 polaris.engine_monitoring 테이블에 데이터가 적재가 되지 않습니다.

다른것도 확인해되 되나요?

**Comment by kyungtaak** [comment]
@alchan-lee 이 이슈 중심으로 ingestion 항목까지 포함 부탁드립니다.

**Comment by alchan-lee** [comment]
@nogah12 
EngineMonitoringSetter: ########### engine monitoring job : find target servers

이 잡이 수행된 이후에 db에 저장되는데요,
혹시 이 로그 이후에도 저장되지 않는다면 해당 시점 로그 공유 부탁드립니다.

**Comment by eltriny** [comment]
@alchan-lee 
slack 에 문의 드렸던 API 관련해서 확인 부탁드립니다.

**Comment by AnnieHwang** [comment]
@koeun222 Overview화면 디자인을 좀 수정해주실수 있으신가요?
![image](https://user-images.githubusercontent.com/6300003/64228373-927c4980-cf21-11e9-9581-0e1d1cea652d.png)
Datasource Count(노란박스)의 위젯 높이를 100%로 만들어주실수 있으신가요? 그리고 맨 앞에 GC CPU는 삭제되었어요.

**Comment by koeun222** [comment]
디자인 공유드립니다. 퍼블까지 진행되었습니다
![image](https://user-images.githubusercontent.com/42256760/65206680-33463980-daca-11e9-8d87-7a8725a5ca3f.png)

**Comment by AnnieHwang** [comment]
@minhyun2 개발 진행부탁드려요.

**Comment by AnnieHwang** [comment]
@eltriny  Beta 뺏지를 메뉴에 붙어야 할것 같은데 현재는 2depth에만 붙여지게 퍼블이 되었더라고요. 3depth(메뉴 : Management  > Engine Monitoring)에도 붙을 수 있게 퍼블 변경 부탁드려요.

![image](https://user-images.githubusercontent.com/6300003/65309685-8baf3100-dbc7-11e9-97c8-2b56020e89ab.png)
