### ISSUE TITLE
Determining column count on file datasets

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1374]
**Is your feature request related to a problem? Please describe.**
If the column count varys row by row, it's difficult to choose how to determine the column count.

Candidates was below:
1. Just the 1st row rules. (datasource way)
2. Visit all the rows, and choose the biggest. (dataprep way)

**Describe the solution you'd like**
1. Visit all rows up to upload preview limit, and choose the biggest.
2. Show to user, and the text control editable. (Not commonly)

**Describe alternatives you've considered**
1. Just the 1st row rules. (datasource way)

**Additional context**
[finefood.sample.txt](https://github.com/metatron-app/metatron-discovery/files/2820392/finefood.sample.txt)
If you import and wrangle (use colon as delimiter) the file above, you'll see 12 columns in upload preview, 34 column in I.DS preview. The bigger file (not sample) results 55 columns. (Someone used http references or just so many columns)

**Comment by minjung-cho** [comment]
![스크린샷 2019-03-13 오후 4 30 47](https://user-images.githubusercontent.com/28773903/54260847-740a4680-45ad-11e9-85ba-d5686a3f323b.png)
@joohokim1 @AnnieHwang 첨부한 안으로 요구사항이 해결될까요? 검토 부탁드립니다-

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang 

위 장표 내용 중에, paragraph로 행이 구분되고, period로 컬럼이 구분된다고 되어있는데, 이것은 미스 커뮤니케이션 인 것 같습니다. (아마 제가 unstructured data를 논하면서 했던 얘기인 것 같습니다.) 삭제하셔도 될 것 같습니다.

참고로 장표에 언급된 "데이터에 기반하여 자동으로 행과 컬럼이 구분됨"은 https://github.com/metatron-app/metatron-discovery/issues/1654 로 진행됩니다.

**Comment by minjung-cho** [comment]
@joohokim1 네, 말씀하신 기획서 오류는 기획 파일에서 삭제해 두겠습니다.

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다
1. column count 추가 : CSV,TXT,Excel 에만 보임
2. 에러 위치 수정
![image](https://user-images.githubusercontent.com/42256760/54344478-47752e00-4684-11e9-8f91-a4ba3bcab2cc.png)

**Comment by AnnieHwang** [comment]
@minjung-cho Column Count라는 레이블이... 뭔지 잘 이해가 안가는데... 좀 더 사용자가 알기쉽도록 명확하게 해줄 필요가 있을것 같아요

**Comment by minjung-cho** [comment]
<img width="1446" alt="스크린샷 2019-03-15 오후 3 43 32" src="https://user-images.githubusercontent.com/28773903/54413561-7bf6f180-4739-11e9-96de-72d737eadb5d.png">
@AnnieHwang 조금전 논의한 내용 반영했습니다. 확인 부탁드립니다- @joohokim1

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang 

네 확인했습니다. 아주 좋습니다~

**Comment by koeun222** [comment]
@AnnieHwang  변경된내용 적용한 디자인 공유드립니다- 
![image](https://user-images.githubusercontent.com/42256760/54417057-6f2bcb00-4744-11e9-96a1-8690a9bbd46c.png)
![image](https://user-images.githubusercontent.com/42256760/54417015-56bbb080-4744-11e9-8f53-13a4c034d378.png)

**Comment by joohokim1** [comment]
Closing as completed.
