### ISSUE TITLE
leave condition expression when rule change

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1377]
**Describe the bug**
Changing a rule command (keep -> delete) results in all input box cleared.
It's a critical loss if some expression was a result of long effort.

**To Reproduce**
1. Import & wrangle any dataset.
2. Edit rules.
3. Select keep command.
4. Fill in the condition box.
5. Change into delete command.
6. The contents in the box has gone.

**Expected behavior**
I wish the contents in the input box as possible. (condition -> condition, value -> value)

**Comment by paigechoi** [comment]
Won't do
