### ISSUE TITLE
Snapshot detail page grid error

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1381]
**Describe the bug**
If there is something like HTML tag in the content, a blank line is generated.

_내용에 HTML 같은 것이 있으면 빈 줄이 생겨납니다._

**To Reproduce**
1. Import [finefood.sample.txt](https://github.com/metatron-app/metatron-discovery/files/2821459/finefood.sample.txt) **with colon delimiter.**
2. Click the new generated I.DS.
3. Click Create dataflow with this dataset.
4. Edit rules.
5. Drop column3 and all after.
6. Click "Snapshot" button
7. Click "Done" (make a CSV snapshot)
8. Click the new generated snapshot.
9. Scroll down and you'll see the empty lines (in the middle)

**Expected behavior**
All contents should be shown clearly no matter what the column value is.

**Screenshots**
![2019-02-01 9 06 40](https://user-images.githubusercontent.com/42257727/52122143-4b656780-2665-11e9-901c-66724c9581e5.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68.0.3440.106

**Additional context**
@sang-hee-lee told me that this is because of HTML tags in the contents.
@ksparknot seems to have some idea about this issue.

**Comment by sang-hee-lee** [comment]
Apply METATRON-1560 issue
