### ISSUE TITLE
If the timestamp column is more than a unit of day, the time zone is meaningless

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1397]
**Is your feature request related to a problem? Please describe.**
If the timestamp column is more than a unit of day, the time zone is meaningless.

**Describe the solution you'd like**
- If the timestamp column is more than a unit of day, remove input and label component related to timezone
- For the above, we need to process separately required when generating the DRUID query.

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by kyungtaak** [comment]
@deidera08  #1193 이슈에 이어 추가 개선사항이 존재합니다. timestamp 컬럼이 일단위이상일 경우 timezone 설정이 무의미하여 이를 제거하는 방안에 대해 관련해서 검토 부탁드립니다.

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
 
우선 configure the schema 단계에서 포맷으로 판단하여 시/분/초가 포함될 경우 타임존 설정노출하는 방향으로 수정하면 좋을듯 합니다.
![2019-02-11 10 14 16](https://user-images.githubusercontent.com/42257766/52542786-b261e980-2de6-11e9-91cb-46775990ff7c.png)

더불어 인제스천 완료 후 데이터소스 > Column details화면에서 타입을 변경할 수 있습니다만, 이 화면에서 타입이나 포맷에 validation을 체크하지 않습니다.
현재는 변경시 브라우저 타임존으로 자동 설정되게끔 구현이 된 상태인데, 타입&포맷에 대한 validation을 체크는 다른 이슈인 것 같아서 Column details화면은 현안 유지하고 configure the schema 단계만 수정하시면 어떨까 싶습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak @deidera08 
그러면 시,분,초 가 아닌 (일 이상의 format)의 경우
아예 timezone 값을 생성시에 적용하지 않으면 되는건가요?
그리고 상세화면에서는 timezone이 없는경우 (field에 timezone이 적용되어있지 않는경우, == 기존에 생성된 데이터소스) 강제로 브라우저 타임존이 노출되도록 표시되고 있는데 이것은 그대로 유지하는건가요?

**Comment by deidera08** [comment]
@brandon-wonjune @kyungtaak 
'년/월/일'의 경우 타임존 영향을 받을 시간정보가 없기 때문에 어느 타임존이든 같은 값입니다.
때문에 '년/월/일' 일 때 UI상에서 타임존 정보가 노출되지 않은 것이 좋을듯 합니다.

Time/Date타입에 무조건 타임존값이 설정되어야 하는 상황이라면 '년/월/일'포맷에는 브라우저 타임존을 기본적으로 적용시키고 UI상에서 숨기면 어떨까요?
