### ISSUE TITLE
Remove staging connection api in dataprep

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1404]
**Describe the bug**
checking staging connection api is no longer used

**To Reproduce**
Go to create dataset -> click staging db -> getStagingConnection API should not be called

**Expected behavior**
/stagedb API should be used instead of /getStagingConnection

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by paigechoi** [comment]
Confirmed by @joohokim1 

use /stagedb instead !!

1 . Do not use `api/preparationdatasets/getStagingConnection` (create dataset staging type)
2 . Do not use hive_info  in `/transform/configuration`. (Create snapshot popup)

**Comment by paigechoi** [comment]
hive_info in `/transform/configuration` should be deleted soon

**Comment by paigechoi** [comment]
Related issue #1203

**Comment by joohokim1** [comment]
1st integrated test passed.
