### ISSUE TITLE
Add query information tab in engine monitoring

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#1417]
**Is your feature request related to a problem? Please describe.**
Engine Monitoring의 세번째 메뉴인 Query 화면입니다.
Query ID별 처리 시간과 상태로 이뤄지며, 각각 클릭시 상세정보는 팝업으로 노출됩니다.

**Describe the solution you'd like**
1. Query list
![list](https://user-images.githubusercontent.com/42257766/52619596-66e23500-2ee5-11e9-922c-c36680ca221f.png)
![filter](https://user-images.githubusercontent.com/42257766/52619594-66e23500-2ee5-11e9-89f9-e03a8aaaa9b1.png)
(박서은매니저님께서 의견을 주시길) 쿼리 시간은 해당 쿼리가 완료되어야 나올 수 있는 값이기 때문에 완료시점 이후 시작/종료시간 값은 계산하여 구하여야합니다.
쿼리 시작시간은 나름 주요 정보일 것 같아 삭제하지 않았습니다만 추후 불필요하다고 판단되면 삭제하도록 하겠습니다.

2. Query 상세화면(팝업)
![detailpop](https://user-images.githubusercontent.com/42257766/52619593-66499e80-2ee5-11e9-9eee-f9ebcc86a349.png)

**Comment by Taehui** [comment]
@deidera08 쿼리가 실행되었던 워크스페이스의 대시보드/차트 url 주소가 있으면, 차후 디버깅에 도움이 될 것 같습니다.

**Comment by deidera08** [comment]
@Taehui 
가이드주셔서 감사합니다 :)
대시보드나 차트 url 주소가 어떻게 표현될 수 있는지 검토 후 추가/보완 하도록 하겠습니다.

**Comment by Taehui** [comment]
@deidera08  추가하고 싶은 정보가 많은데, 누가 실행했는지도 알면 도움이 될 것 같고요, 쉽지 않은 이야기 일 수 있는데..예를들어 Broker 에서 서비스를 했는데 평소에 10ms 이내에 서비스 되던 것이 10s 걸렸다고 쳤을 때, 왜 그랬는지를 알아낼 수 있도록 발전해 나갔으면 합니다. (너무 한꺼번에 다 안하더라도 단계적으로 가면 될 듯 합니다.)

**Comment by deidera08** [comment]
@Taehui 
>예를들어 Broker 에서 서비스를 했는데 평소에 10ms 이내에 서비스 되던 것이 10s 걸렸다고 쳤을 때, 왜 그랬는지를 알아낼 수 있도록 발전해 나갔으면 합니다.

이 부분은 Query Statistics 메뉴를 따로 빼서 해당 정보를 노출하려 구상하고 있습니다.

초안이라 기본적인것부터 갖추려고 노력중입니다.
부족한 부분은 가이드주시는 부분으로 도움받아 차차 메워나가도록 하겠습니다 :)

**Comment by AnnieHwang** [comment]
@Taehui @deidera08 해당 내용을 참고 부탁드립니다.

* 실행된 쿼리로 인해 읽어진 데이터 양(레코드 건수, 사이즈, 세그먼트 수 등의 정보) => 확인해 보도록 하겠음
* 실행된 쿼리의 결과로 제공된 데이터의 양(레코드 건수, 사이즈 등) => 확인해 보도록 하겠음
* 쿼리를 서비스 한 브로커 등의 GC 발생 여부, 메모리 사용량, CPU 부하 => 반영 계획에 있음
* 여러 대의 서버에서 분산 처리 된경우 평균 응답시간과 가장 늦게 응답한 서버의 시간 등 => 반영 계획에 있음
* 엔진에서 응답한 시간과 응답한 이후에 브라우저에서 렌더링 하는데 걸린 시간 => 불가능함

**Comment by deidera08** [comment]
@alchan-lee @AnnieHwang 
기획상 수정된 부분과 검토가 필요한 부분 공유드립니다.

Query list
검토사항: Start / End time은 서버 지원 확인 필요
수정사항: Query ID별 팝업창은 내용을 더 발굴/보완하여 추후 구현할 예정
![querylist](https://user-images.githubusercontent.com/42257766/52948372-a2d13a80-33bc-11e9-9a95-90ab1dbe69e9.png)

살펴보시고 보완해야 할 사항이나 (검토사항에 대한)의견을 모쪼록 부탁드리겠습니다.

기획서 첨부합니다. 참고 부탁드립니다.
[#1417_EngineMonitoring_Query20190218.pptx](https://github.com/metatron-app/metatron-discovery/files/2875389/1417_EngineMonitoring_Query20190218.pptx)

**Comment by YiArie** [comment]
@AnnieHwang @alchan-lee 
안녕하세요. Query List 디자인입니다. 확인 부탁드립니다.
![D6-03Query-00List](https://user-images.githubusercontent.com/48543308/54333666-b8a5e880-4666-11e9-8fbf-79f365695a1b.png)

**Comment by AnnieHwang** [comment]
@YiArie 이거 혹시 상세는 나왔나요?

**Comment by YiArie** [comment]
@AnnieHwang 상세팝업은 기획서 상 tbd 상태로 아직 디자인은 진행되지 않았습니다.

**Comment by AnnieHwang** [comment]
@YiArie 팝업 말고요. 상세 페이지요. 상세 페이지는 TBD 상태가 아닌데요..

**Comment by koeun222** [comment]
쿼리정보 팝업 디자인 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/67731591-12172800-fa3c-11e9-84c7-b5c96041da7e.png)
