### ISSUE TITLE
The order of autocompletion for rule editor : function first, column next 

### ISSUE THREAD

**Issue by ksparknot** [metatron-app/metatron-discovery#142]
**Is your feature request related to a problem? Please describe.**
고급 수식입력기 팝업에서 사용자 입력에 따라 자동완성을 위한 suggestion을 할 때에,
더 나은 사용성을 위해서 함수 이름이 컬럼명보다 더 먼저 보이도록 함

**Describe the solution you'd like**
현재 컬럼명이 먼저 표시되고 있는데
사용자는 컬럼명은 모두 알고 있으나 함수명을 전부 알고 있지 않음.

위와 관련해서 일관성을 유지하는 차원에서, 서버가 지원하는 함수명을 모두 가져오는 API를 사용하는 것이 좋겠습니다.
그리고 함수명 -> 컬럼명 순서로 나오도록 해주세요.

**Describe alternatives you've considered**
추천 자체를 서버의 auto_completion을 이용하는 것도 하나의 방법입니다. 

**Additional context**
일단은 지원하는 함수명을 모두 주는 API를 먼저 만드는 것이 좋겠습니다. (@ksparknot)
그 후에 UI에서 고급 수식입력기를 수정하면 될 것 같습니다. (@eltriny)

**Comment by joohokim1** [comment]
고급 수식입력기에서 함수명이 컬럼명보다 먼저 추천되는 것으로 이슈를 바꾸어서 UI 쪽으로 담당을 옮기겠습니다.

**Comment by joohokim1** [comment]
일단 @ksparknot 님께서 함수명 리스트제공 API를 만들어 주신 후에, UI 쪽으로 담당을 넘기겠습니다.

**Comment by ksparknot** [comment]
GET /api/preparationdatasets/function_list API가 추가되었고
반환값이 _initializeFunctionList() 에서 사용되던 형태 그대로 이므로 기존과 동일하게 사용하시면 됩니다.

**Comment by joohokim1** [comment]
All PRs for this issue have been pushed.
