### ISSUE TITLE
Expression error in edit rule using column with white space

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#1420]
**Describe the bug**
An expression is truncated in an edit rule that uses a column with spaces.

**To Reproduce**
1. Menu> Data Preparation > Dataflow
2. Click a dataflow
3. Click a W.DS 
4. Edit rules
5. Add rule (aggregate) expressions that uses a column with spaces.
6. Edit rule and check expressions

**Expected behavior**
The exact expression must be set.

**Screenshots**
![default](https://user-images.githubusercontent.com/42233710/52624732-bd09a500-2ef2-11e9-87db-8c9dd800af0d.jpg)
![api](https://user-images.githubusercontent.com/42233710/52624746-c5fa7680-2ef2-11e9-9e33-b968b157c9a8.jpg)
![default](https://user-images.githubusercontent.com/42233710/52624756-cb57c100-2ef2-11e9-8d51-79d536f0da47.jpg)

**Desktop (please complete the following information):**

**Additional context**
need an array type result in the API.

As an example
"uiRuleString":{
"name": "aggregate",
"value" : ["sum(`column22`)", "sum(`column 23`)"],
"group": `column2`"
},

**Comment by joohokim1** [comment]
@paigechoi @sang-hee-lee 
Server works done.
