### ISSUE TITLE
Improve DataConnection UI/UX

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#143]
**Is your feature request related to a problem? Please describe.**
Improve UI/UX in DataConnection Config.

**Describe the solution you'd like**
Please see the screenshot.

1. Simple title
"DB Type" + "Server" -> DB Connection

![blob 1](https://user-images.githubusercontent.com/3770446/45281299-5b43aa00-b512-11e8-9e8f-230b498fddae.png)
![blob 2](https://user-images.githubusercontent.com/3770446/45281300-5d0d6d80-b512-11e8-9a5c-61a49890a712.png)

2. Highlight selected DB Type
When you create a data source, the highlight is not noticeable if you select Connection Preset.

![screenshot-1](https://user-images.githubusercontent.com/3770446/45281309-64347b80-b512-11e8-950b-6b21cb9c4f34.png)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ufoscw** [comment]
@minjung-cho 
2번 내용 확인 바랍니다.

**Comment by minjung-cho** [comment]
@ufoscw 비활성은 맞는데, 선명한게 좋겠다는 뜻인지요?

**Comment by ufoscw** [comment]
@minjung-cho 
네. 맞습니다.

**Comment by minjung-cho** [comment]
@ufoscw OK
@koeun222 기능이 비활성되더라도, 정보 열람이 필요한 경우에는 흐리게 처리하지 않는게 좋을 것 같습니다. 이슈가 된 화면을 보면 Security는 선택값이 선명하게 보입니다. 관련해서 UI 정책 정리는 함께하시죠! 퍼블리셔분께 전달 부탁드립니다

**Comment by koeun222** [comment]
- 선택한 값은 선명하게
- 그 외 버튼은 선택 못하게 dim 처리
- 선택되있는데 dim처리된 상황은 없음

@minjung-cho 이렇게 정리하겠습니다

**Comment by brandon-wonjune** [comment]
f#143-impove_data_connection_ui 브렌치 생성하였습니다
