### ISSUE TITLE
 Change the term 'Master'

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1436]
**Is your feature request related to a problem? Please describe.**
'Meta data' 의 개념과 기능이 변경됨에 따라 기존의 Meta data를 'Master data'로 변경하게 되었습니다. 
그에 따라 기존에 사용하던 'Master'를 다른 단어로 치환 또는 삭제하고자 합니다.

**Describe the solution you'd like**
현재  데이터소스와 데이터셋 조인 시, Left 데이터에 'Mater'를 사용하고 있습니다. 영역의 헤더를 보여주지 않아도 조인 수행에 대한 혼동은 없을 것 같아 삭제하는 것을 제안합니다.
![2019-02-14 5 47 26](https://user-images.githubusercontent.com/28773903/52775150-51eed880-3082-11e9-9f7c-f00e049b3406.png)
![2019-02-14 5 51 29](https://user-images.githubusercontent.com/28773903/52775153-51eed880-3082-11e9-9f16-a550d63c2e78.png)

**Additional context**
None

**Comment by minjung-cho** [comment]
@AnnieHwang 혹시 다른 의견 있으신가요~ 확인 부탁드립니다

**Comment by AnnieHwang** [comment]
@minjung-cho MDM 쪽 용어를 변경하기로 하여 해당 이슈는 클로즈 합니다.
