### ISSUE TITLE
Filters do not apply to line charts.

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#1438]
**Describe the bug**
대시보드 상에서 글로벌필터 적용 시, 라인차트에는 반영 안됨 

**To Reproduce**
1. 표차트, 막대차트, 라인차트 생성
2. 특정 차원값으로 글로벌 필터 생성
3. "터치 WAKE-UP" 선택
4. 첨부 확인 

**Expected behavior**
라인차트에 해당 값만 표출

**Screenshots**
<img width="907" alt="2019-02-15 11 19 59" src="https://user-images.githubusercontent.com/44457771/52830624-dd18ae80-3114-11e9-987f-2951e964d533.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] - chrome

**Additional context**

**Comment by alchan-lee** [comment]
@eltriny 
필터 적용시 UI에서 라인차트 갱신이 안되는 듯 합니다. 확인 부탁드립니다.

재현 해놓은 페이지 공유드립니다.
(http://metatron-web-05:8180/app/v2/workbook/f97bb0d0-669f-422c-94d5-c80ccae8262f)

**Comment by eltriny** [comment]
@alchan-lee 
서버측에서 확인해주셔야 할거 같습니다. 아래와 같이 필터값을 전달이 되고 있는 듯 합니다.
![2019-02-18 10 15 28](https://user-images.githubusercontent.com/3685833/52922678-3af00500-3366-11e9-8812-159fcd93c538.png)

**Comment by alchan-lee** [comment]
@eltriny 
앗, 서버에서는 정상적으로 리턴가고 있는 듯 한데요
참고로 사라져야 하는 line에 마우스 호버를 하면 콘솔에러 나고 있습니다.

![image](https://user-images.githubusercontent.com/42234141/52923335-a8059980-336a-11e9-8d6f-a2a659b62b5b.png)

**Comment by alchan-lee** [comment]
@jeongeunkwon 
it will be fixed in the coming version (3.2.0-rc2)
