### ISSUE TITLE
Add 'Reversed' option for general color template

### ISSUE THREAD

**Issue by esezin** [metatron-app/metatron-discovery#1442]
**Is your feature request related to a problem? Please describe.**
차트의 색상 옵션에서 측정값 기준의 단계별 그라데이션 경우, 색상을 반전해서 사용하는 필요성이 있습니다. 색상 템플릿에 Reversed 옵션을 추가해 이를 해결하려 합니다.

**Describe the solution you'd like**
색상 템플릿에 아래와 같이 옵션을 추가합니다.
![color_reversed](https://user-images.githubusercontent.com/28885462/52921013-10964b80-3356-11e9-9385-f35d74e18600.JPG)

**Additional context**
None

**Comment by koeun222** [comment]
@AnnieHwang 색상반전 ui 추가된 디자인공유드립니다
![image](https://user-images.githubusercontent.com/42256760/53062024-cb634c80-3502-11e9-965a-014d0f6a79fc.png)
