### ISSUE TITLE
Simplify color by option on mapview layer option and add cluster view mode on point layer

### ISSUE THREAD

**Issue by esezin** [metatron-app/metatron-discovery#1443]
**Is your feature request related to a problem? Please describe.**
현재의 맵뷰의 색상/크기 기준 옵션은 속성(dimension, measure)을 먼저 선택하고, 이후 다시 아래의 셀렉트 박스에서 각 속성에 해당하는 컬럼을 선택하도록 되어 있습니다. 선반에 배치한 컬럼만을 대상으로 하는 바, 그 수가 상대적으로 많지 않은 점을 고려하면 선택 가능한 컬럼을 속성 아이콘과 함께 바로 표시하는 것이 편의성이 높을 것으로 보입니다.

**Describe the solution you'd like**
아래와 같이 색상 기준 혹은 크기 기준 셀렉트 박스에서 선택 가능한 컬럼 리스트를 바로 표시 & 선택합니다.
![mapview-depth](https://user-images.githubusercontent.com/28885462/52921125-0fb1e980-3357-11e9-9d92-7b1bc45a826c.JPG)

![mapview-depth2](https://user-images.githubusercontent.com/28885462/52921127-12acda00-3357-11e9-816d-5d2ad82e8957.JPG)

**Additional context**
이후 맵뷰 외의 다른 차트 옵션에서도 공통으로 적용하는 것을 고려해 볼 수 있겠습니다.

**Comment by kyungtaak** [comment]
@eltriny 기존 맵뷰에서 측적값에 대한 색상 기준이 차원항목을 넣고 뺄때 초기화 되는 현상도 해당 이슈에서 작업시 확인 부탁드립니다.

**Comment by kyungtaak** [comment]
@eltriny 아래와 같은 이슈도 함게 확인하면서 작업 부탁드립니다.
![image](https://user-images.githubusercontent.com/822255/53147788-fa092200-35eb-11e9-93e2-b2891170a6fb.png)
