### ISSUE TITLE
Multiple filter selection error

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#1444]
**Describe the bug**
다중 필터 선택 변경 시, All 항목 선택 오류 발생함

**To Reproduce**
1. 항목이 2개인 다중필터 생성 후 대시보드상에 위치
2. 다른 항목 선택하여 All 선택된 것 확인 후, 기 선택 항목 uncheck 

**Expected behavior**
다른 항목은 남아있는 상태에서, 기 선택항목과 All 항목만 uncheck 되어야 함 
(전체 uncheck 되며, 재 선택 시 선택되지 않음)

**Screenshots**
![0218_multiplefilter](https://user-images.githubusercontent.com/44457771/52921774-fceee300-335d-11e9-8ef8-7a3f368a8f06.gif)

**Desktop (please complete the following information):**

**Additional context**

**Comment by eltriny** [comment]
@alchan-lee @kyungtaak 
본 이슈는 재현이 되지 않고 있어.. 이슈를 종료하고자 합니다.
혹시 확인해보시고 재현이 되다면 말씀해주시기 바랍니다.. 
확인이 안되시면 스프린트 종료 시점에 이슈를 종료하겠습니다.

**Comment by alchan-lee** [comment]
@eltriny 
이 건은 아래 워크스페이스에 재현해두었습니다.
http://metatron-web-05:8180/app/v2/workbook/e265b3d0-6b78-4527-a701-3bac9ec8b9b1

제가 파악해보기로는 
1. 다중선택 필터에서 전체 값보다 1건이 적게 미리 값을 세팅해둔 다음에 
   (2개인 경우 1개를 미리 선택해둠)
2. 대시보드 저장을 하고
3. 해당 대시보드 접근 후 위젯에서 필터를 선택하여 전체값이 선택되고 난 뒤 
4. 원래 선택되어 있던 값을 체크해제 하면 발생 하는 오류인 듯 합니다.

**Comment by alchan-lee** [comment]
현재 조치되었으며 다음 배포(3.2.0-rc3)에 포함됩니다.
