### ISSUE TITLE
Filter edit popup error

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#1447]
**Describe the bug**
대시보드 편집 화면에서 필터 edit 을 클릭하면 팝업이 떴다가 사라짐

**To Reproduce**
1. Edit dashboard
2. 필터위젯의 edit 클릭
3. 팝업이 떴다가 사라짐

**Expected behavior**
필터 위젯이 떠서 수정 가능한 상태여야 함

**Screenshots**
![0218_filter_edit](https://user-images.githubusercontent.com/44457771/52923631-0ed78280-336c-11e9-9d1b-bffa7bc3dbce.gif)

**Desktop (please complete the following information):**

**Additional context**

**Comment by alchan-lee** [comment]
해당건 조치되어 다음 릴리즈 (3.2.0-rc3)에 포함됩니다.
