### ISSUE TITLE
Null pointer exception with json type snapshot

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1455]
**Describe the bug**
Null pointer exception occurs in 
`/api/preparationsnapshots/{ssid}/contents?offset=0&target=10000` API
snapshot is JSON type and has null value.
![image](https://user-images.githubusercontent.com/42233517/52939078-9e018c00-33a6-11e9-8eb4-a1dc467bf575.png)

**To Reproduce**
1. Create a JSON type snapshot with null value data
2. go to snapshot detail page
3. see error
![image](https://user-images.githubusercontent.com/42233517/52939103-abb71180-33a6-11e9-9ca6-1db34f474f96.png)

**Expected behavior**
Show snapshot detail with no error

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
[jsonTest_null.json.txt](https://github.com/metatron-app/metatron-discovery/files/2939034/jsonTest_null.json.txt)
**remove .txt to test**

**Comment by joohokim1** [comment]
1st integrated test **"FAILED"**
