### ISSUE TITLE
Spatial operation functions for mapview

### ISSUE THREAD

**Issue by esezin** [metatron-app/metatron-discovery#1463]
**Is your feature request related to a problem? Please describe.**
맵뷰 내의 고급분석 패널에 공간연산 기능을 추가합니다.
공간연산은 레이어를 구성하는 각각의 Geometry간의 공간 관계(Spatial Relationship)를 기반으로,
특정 연산식의 반환된 결과값을 새로운 레이어로 생성하여 표시하는 기능입니다.

**Describe the solution you'd like**
아래와 같이 멀티레이어로 2개의 Geometry를 구성하고, 고급분석 패널을 통해 연산 결과 레이어를 생성합니다.
![mapview-spatial-operation01](https://user-images.githubusercontent.com/28885462/52992035-77009400-3452-11e9-8eae-99a8fd7cd0cd.PNG)
![mapview-spatial-operation02](https://user-images.githubusercontent.com/28885462/52992039-79fb8480-3452-11e9-9a62-98f0772a7156.PNG)

**Additional context**
연산식 관련 상세는 아래의 기획서 z2문서를 참고바랍니다.
https://tde.sktelecom.com/wiki/pages/viewpage.action?pageId=153491246

**Comment by koeun222** [comment]
@choonglee170924 @sting009 
연산영역(비교레이어) 색상및스타일 전달드립니다 

면적 :  color #ff00f / opacity 10%
라인 :  color #ff00ff / 2px Dotted / 

![image](https://user-images.githubusercontent.com/42256760/54419389-a56c4900-474a-11e9-9920-d086a571d9d3.png)

**Comment by koeun222** [comment]
@AnnieHwang Analysis(왼쪽패널) > 공간 연산 관련 ui 추가된 디자인 공유드립니다- 
![image](https://user-images.githubusercontent.com/42256760/54492186-95e62f00-4907-11e9-8f25-bfc9313b4e29.png)

**Comment by koeun222** [comment]
@choonglee170924 @sting009  클러스터링 기능을 유형 중 하나로 변경 관련 디자인 전달드립니다- 
![image](https://user-images.githubusercontent.com/42256760/55447170-a67ff000-55fd-11e9-923a-8d34d2a7f93b.png)
