### ISSUE TITLE
Hive file compression error when creating snapshot

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1468]
**Describe the bug**
Always sending NONE with hive file compression

**To Reproduce**
1. Go to create hive snapshot
2. Click on advanced setting
3. Change compression to zlib or snappy

**Expected behavior**
Hive file compression has 3 options : None, zlib, snappy

**Screenshots**
![image](https://user-images.githubusercontent.com/42233517/53004121-dae78480-3473-11e9-8e5c-f7667630f2c5.png)

**Desktop (please complete the following information):**

**Additional context**
I'm going to do some refactoring in snapshot creation popup.

**Comment by paigechoi** [comment]
confirmed by @joohokim1
- Default value of snapshot  table name is `Snapshot1`
- Only alphanumeric and _ is allowed with table name
- no white space in table name

**Comment by minjung-cho** [comment]
![2019-03-04 2 21 06](https://user-images.githubusercontent.com/28773903/53712140-e9c53280-3e88-11e9-8c65-755011033ed6.png)
Done 시, 
필수값 입력 여부 및 유효성 체크를 실행하고 입력 조건에 부합하지 않는 입력 필드가 있을 때 각 필드에 개별 메시지를 표시합니다. 
이때 Done 버튼 근처에 기존의 토스트 팝업을 대체할 수 있는 공통 문구를 띄워 줍니다. 얼마전부터 개선하고 있는 공통 UI이나 전체를 한번에 적용할 수 없는 부분이라 진행되는 화면들 부터 적용 중이니 참고 부탁드립니다.

**Comment by joohokim1** [comment]
1st integrated test passed.
