### ISSUE TITLE
Workbench can't execute query after cancel.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#147]
**Describe the bug**
Workbench can't execute query after cancel.

**To Reproduce**
1. Go to workbench with hive.
2. input a time-consuming query.

select  i,i 
from    (select 1) x lateral view posexplode (split (space (10000000-1),' ')) e as i,x;

3. query execute.
4. click cancel button
5. execute again
6. "query is running" error message.

**Expected behavior**
when user click cancel button, Keep the loading bar until client get a response from cancel API Request.
and If the status is IDLE or CANCELLED, it is considered to be query executable.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Additional context**
NA

**Comment by eltriny** [comment]
@ufoscw 
#50 번 이슈의 프로그래스 작업으로 인한 호출 구조 변경으로 cancel 작업도 같이 해야 하는 상황이므로 #50번 branch에서 함께 작업합니다.

**Comment by goodljy** [comment]
정상 동작 확인 2018.10.16
