### ISSUE TITLE
Totalbytes, totalLines missing from server response in file type imported dataset

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1477]
**Describe the bug**
TotalBytes, totalLine fields are missing in File type dataset 
![image](https://user-images.githubusercontent.com/42233517/53073653-fca44280-352b-11e9-973b-7410f998333f.png)

**To Reproduce**
Go to dataset detail -> see error (Check with file type IMPORTED dataset)

**Expected behavior**
Server response should include TotalBytes and totalLine.

**Screenshots**
![image](https://user-images.githubusercontent.com/42233517/53073860-923fd200-352c-11e9-9c48-24bc2cc211ef.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
1st integrated test passed.
