### ISSUE TITLE
Percentile menu looks strange and does not work

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#148]
**Describe the bug**
Percentile menu 가 이상하게 보이며 선택할 수 없음.

**To Reproduce**
Screenshot 참조

**Expected behavior**
메뉴 방향 그리고 선택할 수 있게 변경되야 함

**Screenshots**
<img width="1632" alt="percentile-error" src="https://user-images.githubusercontent.com/526622/45346418-1b4cf780-b5e4-11e8-8957-80c287090675.png">

**Desktop (please complete the following information):**
Demo site

**Additional context**

**Comment by minjung-cho** [comment]
METATRON-1418
