### ISSUE TITLE
A sort error occurs if the data grid contains blanks.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#1489]
**Describe the bug**
A sort error occurs if the data grid contains blanks.
The sort result is incorrect when clicking on the header.
And the arrow coordinates are wrong when clicking the header.

**To Reproduce**
1. Go to workbench
2. execute query 
```
select "1", "a"
union select "2", "b"
union select "3", "";
```
3. click second column header 3 times.
4. See 3 different sort result

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ninezero90hy** [comment]
@ufoscw 현재 메타트론 그리드의 헤더를 클릭할 때 화살표 아이콘 변경은 [SlickGrid](https://github.com/mleibman/SlickGrid) 라이브러리의 기본 동작입니다 
아래 첨부한 샘플(SlickGrid 멀티 컬럼 정렬 예제) 확인 부탁드립니다
 - [SlickGrid 멀티 컬럼 정렬 예제](https://mleibman.github.io/SlickGrid/examples/example-multi-column-sort.html)

![slickgrid-sort](https://user-images.githubusercontent.com/41019113/53706710-f2107400-3e6e-11e9-85d1-a0faca25dd66.gif)

- 메타트론 워크벤트 그리드 정렬

![metatron-slickgrid-sort](https://user-images.githubusercontent.com/41019113/53706721-fe94cc80-3e6e-11e9-9ce9-bd7645865f52.gif)

**Comment by ufoscw** [comment]
@ninezero90hy 
화살표 아이콘 관련해서 리포한 내용은 화살표의 y좌표가 클릭전과 다르게 움직이는 내용입니다.
올려주신 gif에서 클릭 후 화살표 y좌표가 "No." 컬럼에 비해 상단에 붙어 버리네요.

**Comment by ninezero90hy** [comment]
> @ninezero90hy
> 화살표 아이콘 관련해서 리포트한 내용은 화살표의 y좌표가 클릭전과 다르게 움직이는 내용입니다.
> 올려주신 gif에서 클릭 후 화살표 y좌표가 "No." 컬럼에 비해 상단에 붙어 버리네요.

@ufoscw 아이콘 위치 변화를 말하신 거군요 확인해보겠습니다

**Comment by ufoscw** [comment]
@ninezero90hy 
참고로 재현방법 3번의
```3. click second column header 3 times.```
은 마지막 컬럼의 헤더를 클릭했을때를 말합니다.

**Comment by ufoscw** [comment]
@ninezero90hy 
> 참고로 재현방법 3번의
> 3. click second column header 3 times.
> 은 마지막 컬럼의 헤더를 클릭했을때를 말합니다.

![mar-04-2019 11-41-50](https://user-images.githubusercontent.com/3770446/53707504-9811ad80-3e72-11e9-97aa-1226acd1146f.gif)

**Comment by ninezero90hy** [comment]
> @ninezero90hy
> 
> > 참고로 재현방법 3번의
> > 3. click second column header 3 times.
> > 은 마지막 컬럼의 헤더를 클릭했을때를 말합니다.
> 
> ![mar-04-2019 11-41-50](https://user-images.githubusercontent.com/3770446/53707504-9811ad80-3e72-11e9-97aa-1226acd1146f.gif)

@ufoscw 브라우저가 혹시 IE인가요?

**Comment by ufoscw** [comment]
@ninezero90hy 
mac용 크롬입니다.

**Comment by ninezero90hy** [comment]
> @ninezero90hy
> mac용 크롬입니다.

@ufoscw 네 맥/크롬인데 확인해보겠습니다

**Comment by ninezero90hy** [comment]
@ufoscw 
- 아이콘 위치 변경되는 오류 / 정렬 변경 오류 수정했습니다. 
아래와 같이 나오면 되는지 확인 부탁드립니다

```sql
select "1", "a"
union select "2", "b"
union select "", "";
```

![fix-grid](https://user-images.githubusercontent.com/41019113/53710849-9223c880-3e82-11e9-8ede-36199a59336c.gif)

**Comment by ninezero90hy** [comment]
> @ufoscw
> 
> * 아이콘 위치 변경되는 오류 / 정렬 변경 오류 수정했습니다.
>   아래와 같이 나오면 되는지 확인 부탁드립니다
> 
> ```sql
> select "1", "a"
> union select "2", "b"
> union select "", "";
> ```
> 
> ![fix-grid](https://user-images.githubusercontent.com/41019113/53710849-9223c880-3e82-11e9-8ede-36199a59336c.gif)

@ufoscw 해당 결과를 기준으로 PR 올렸습니다. 확인 부탁드립니다
