### ISSUE TITLE
Incorrect gradient color variation in grid

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#149]
**Describe the bug**
표에서 Gradient 를 선택하면 색 범위가 반대로 편성됨

**To Reproduce**
스크린샷 참조

**Expected behavior**
색 표현이 반대로 되야 함. 그리고 최소값이 0 으로 나오는데 현재 그리드에서 최소값은 181.67 또는 181 이어야 함

**Screenshots**
<img width="1552" alt="gradient-error" src="https://user-images.githubusercontent.com/526622/45346771-27858480-b5e5-11e8-877c-6a532e75a836.png">

**Desktop (please complete the following information):**
demo site

**Additional context**

**Comment by juheeko9** [comment]
#f149-incorrect_gradient_grid 브랜치 추가하였습니다.
