### ISSUE TITLE
Convert JSON string column into Map or Array column type

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1493]
**Is your feature request related to a problem? Please describe.**
If a dataset looks like this:
<img width="367" alt="2019-02-21 2 02 12" src="https://user-images.githubusercontent.com/42257727/53144881-62063b00-35e1-11e9-93fc-8afe971b15a5.png">

Someone might want to change it like this **with a convenient way**:
<img width="545" alt="2019-02-21 2 12 28" src="https://user-images.githubusercontent.com/42257727/53145235-c37ad980-35e2-11e9-8941-068c9ccf99b4.png">
so that he or she could handle the element of the collection data.

**Describe the solution you'd like**
We should enhance settype transform to support from string to map/array conversion. (Of course, the vice versa too)

**Comment by minjung-cho** [comment]
@joohokim1 @ksparknot 
디자인은 아이콘 작업만 진행하면 될것 같습니다. 지원하는 조건 정리되시면 공유 부탁드립니다-

**Comment by joohokim1** [comment]
This issue is very close to https://github.com/metatron-app/metatron-discovery/issues/2190.

**Comment by joohokim1** [comment]
@ksparknot We need to change array, map types' representation. For many reasons, array and map values are better to be written in plain JSON strings.
Belows are the behaviors of the UI when I changed server code to use plain JSON strings.

![스크린샷 2019-11-07 오전 1 17 44](https://user-images.githubusercontent.com/42257727/68316718-43a78780-00fd-11ea-9ae5-ec3a67e65218.png)

![스크린샷 2019-11-07 오전 1 15 55](https://user-images.githubusercontent.com/42257727/68316905-9123f480-00fd-11ea-917d-0648c2dbcd15.png)

@ksparknot This issue is rather urgent, and I cannot proceed without your help.
I'll be appreciate if you process with a higher priority.

**Comment by joohokim1** [comment]
This is the file I used: [json_in_column.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3817565/json_in_column.csv.txt)
