### ISSUE TITLE
When creating a temporary data source, the user does not know when the data source has been created.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#1496]
**Is your feature request related to a problem? Please describe.**
When creating a temporary data source, the user does not know when the data source has been created.
So when the user pops up a chart preview, no data is displayed.
After some time, the user has to redraw the chart to see the data.
<img width="1838" alt="temporary-datasource-error" src="https://user-images.githubusercontent.com/3770446/53145974-d17e2980-35e5-11e9-917a-49a9467a90ee.png">

**Describe the solution you'd like**
must tell the user when the data source creation is complete.

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
@eltriny 아래 이슈도 함께 확인 해주시면 좋을것 같네요.
![image](https://user-images.githubusercontent.com/822255/53148430-fa0a2180-35ed-11e9-9db3-03a826e880c5.png)
