### ISSUE TITLE
Icon overlaps the last column of query result

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#1504]
**Describe the bug**
워크벤치 쿼리 결과에서 마지막 row 의 마지막 column 값이 확인 불가함

**To Reproduce**
1. 워크벤치에서 쿼리 실행
2. 쿼리 결과의 마지막 row, 마지막 column 값이 아이콘 이미지에 가려짐 확인

**Expected behavior**
아이콘 이미지에 의해 데이터가 가려지지 않아야 함

**Screenshots**
![2019-02-22 3 37 36](https://user-images.githubusercontent.com/44457771/53226969-2ee6a900-36c0-11e9-949d-9909c24bbac4.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by koeun222** [comment]
@AnnieHwang 
디폴트 상태에는 버튼을 반투명이고 호버시 투명도가 없는 안이 어떨지 공유드려요 
다만 반투명으로 할때에 가려지는 정보가 많아서 뒤쪽에 아이콘 4개를 더보기로 숨기고 
더보기 클릭시 아래이미지처럼 펼쳐지게 넣었습니다 
검토부탁드려요

![image](https://user-images.githubusercontent.com/42256760/53717480-a45e3080-3e9b-11e9-853a-cd309951b860.png)
![image](https://user-images.githubusercontent.com/42256760/53717499-b17b1f80-3e9b-11e9-9081-76933be15def.png)

**Comment by kyungtaak** [comment]
@AnnieHwang  위 내용검토 부탁드립니다. 스크롤이 맨 아래에 있을경우 최소화 또는 투명도 설정 등으로 처리 했으며 ㄴ합니다.

**Comment by AnnieHwang** [comment]
@kyungtaak 네 괜찮을것 같아요~

**Comment by kyungtaak** [comment]
@AnnieHwang @eltriny 해당작업은 디자인이나 별도 퍼블가이드가 필요한 사항인가요? 3.3 milestone 으로 이동하였으니 작업시점에 재확인 부탁드립니다.
