### ISSUE TITLE
Edit dataset immediately after creation in Prep

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#1516]
**Is your feature request related to a problem? Please describe.**
데이터 셋 생성시 마지막 화면에 해당 데이터셋으로 바로 룰 편집으로 넘어갈수 있는 숏컷 기능 추가(METATRON-1447)
- 만들어질 데이터셋으로 자동으로 데이터 플로우를 만들고 룰 편집 화면까지 넘어가는 기능

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/6300003/53318655-51243500-3913-11e9-9464-c45e3e19ea95.png)

---------(11 Mar 2019 / Changes)---------
Single file
<img width="1164" alt="스크린샷 2019-03-11 오후 4 42 16" src="https://user-images.githubusercontent.com/28773903/54107578-ec8dcd80-441c-11e9-889d-cad73bf4d87c.png">

Multiple file
<img width="1145" alt="스크린샷 2019-03-11 오후 4 42 33" src="https://user-images.githubusercontent.com/28773903/54107580-ec8dcd80-441c-11e9-99d7-ae519b9917c9.png">

**Additional context**
#1516

**Comment by koeun222** [comment]
@AnnieHwang Single file 업로드시 화면 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/54335984-0d992d00-466e-11e9-9855-eec2f0c2ee72.png)

**Comment by paigechoi** [comment]
confirmed by @joohokim1 
@minjung-cho 

Disable the shortcut when entering dataset creation through dataflow detail.
데이터플로우 상세 화면을 통해서 데이터셋 생성 화면으로 진입한 경우 숏컷 기능 비활성화
