### ISSUE TITLE
 Error message is displayed when copying after editing name of dashboard

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#152]
**Describe the bug**
- 대시보드 목록에서 이름을 수정하여 복사를 하면 "Network Operation Error" 가 발생합니다. 
- 수정된 대시보드 명이 변경되지 않습니다.

**To Reproduce**
1. Go to Workbook and then you can see list of dashboard
2. Click on copy icon on dashboard panel
3. Edit title on copy page.

**Expected behavior**
- 위젯 복사 처럼 카피후 사용자가 제목/상세  수정을 통해 수정하도록 유도합니다.

**Screenshots**
![copy_error](https://user-images.githubusercontent.com/822255/45397677-218eb280-b67c-11e8-8926-9fe90ba813ed.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser : Chrome
 - Version : 68.0

**Additional context**
@metatron-app/design copy 전에 이름/상세 수정이 아닌 위젯 카피와 동일하게 copy 후 사용자가 수정하는 방안에 대해 검토 부탁드립니다.

**Comment by eltriny** [comment]
@kyungtaak @minjung-cho 
그럼 작업은 대시보드 복제 시 이름 입력 팝업을 띄우지 않고 바로 복사만 되게 하면 되는 것인가요?
그리고 복제되어 생성된 대시보드로 목록을 자동으로 스크롤 시키면 되는건가요?

**Comment by minjung-cho** [comment]
@eltriny 네, 두가지 다 지향하는 방향과 같습니다

**Comment by eltriny** [comment]
@kyungtaak 
대시보드 복제 관련 이슈를 216번 이슈에서 처리하고 있어 #216 이슈 브랜치에서 같이 작업해서 올리도록 하겠습니다.
