### ISSUE TITLE
Fix name input in dataprep (dataset/snapshot)

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1532]
**Describe the bug**
1. When shift key and enter key is used, new line can be included in dataset/snapshot name

**To Reproduce**
1. Go to dataflow detail => click one dataset -> click edit dataset name in the right panel  -> press enter and shift key together -> see error

**Expected behavior**
1 . Change to input box that cannot use new line

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
METATRON-1581

**Comment by joohokim1** [comment]
1st integrated test passed.
