### ISSUE TITLE
Error previewing data in link-type datasource

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#155]
**Describe the bug**
Link 타입의 데이터소스 상세 조회내,
- "Data" 탭에 데이터 조회는 정상적으로 나오지 않습니다. (grid 헤더명과, 원본의 헤더명이 일치하지 않아 발생한것으로 보입니다.)
- "Data Monitoring" 탭의 경우, 엔진에 적재되었을 경우만 사용이 가능하니, 제거가 필요합니다.

**To Reproduce**
1. Create datasource by link type (Hive 타입의 table 선택)
2. Go to datasource management.
3. Click on linked datasource in list of datasource.
4. move to "data" tab

**Expected behavior**
Link 타입의 데이터소스 상세 조회내, "Data" 탭에 데이터 조회는 정상적으로 나와야하며, "Data Monitoring" 탭은 제거가 되어야합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/45402133-0f6a3f80-b68f-11e8-8492-df789a42727e.png)

**Desktop (please complete the following information):**
<N/A>

**Additional context**
- Hive 조회의 경우, table 명이 포함되는 경우가 있어 옵셔널하게 처리할 API 구현이 필요합니다.
- @metatron-app/design monitoring 제거하는 안에 대해 검토 부탁드립니다.

**Comment by brandon-wonjune** [comment]
f#155-linked_datasource_preview_error 브랜치 생성하였습니다

**Comment by minjung-cho** [comment]
@kyungtaak Linked type인 경우, 데이터소스 상세화면에서 Monitoring 탭을 제거하기로 했습니다. 기획서에 반영할 예정입니다. 
@AnnieHwang 논의한 내용입니다

**Comment by brandon-wonjune** [comment]
@minjung-cho Linked type 인 경우 모니터링 탭 제거하였습니다.
![2018-09-12 4 16 14](https://user-images.githubusercontent.com/42233627/45408464-5ebc6a00-b6a7-11e8-9526-bef763634429.png)

**Comment by minjung-cho** [comment]
기획서 V.1.30에 반영함

**Comment by ufoscw** [comment]
@brandon-wonjune 
data 요청 API에 파라미터가 추가될 예정입니다. 
data 목록의 key를 테이블명.컬럼명일 경우 컬럼명만으로 구성하기 위한 파라미터입니다.
작업되면 알려드릴게요.

**Comment by ufoscw** [comment]
@brandon-wonjune 

`/api/connections/query/data`
`/api/connections/query/hive/data`

2가지 API에 extractColumnName querystring param이 추가되었습니다.
기본값은 false 입니다.

ex) 
`/api/connections/query/data?extractColumnName=true`
`/api/connections/query/hive/data?extractColumnName=true`

**Comment by brandon-wonjune** [comment]
해당이슈는 연결형 데이터소스를 이용한 대시보드의 데이터소스 미리보기에 대해 충돌되는 작업이 있고 디자인 변경이 있어서 #9 이슈의 브랜치에서 같이 작업하도록 하겠습니다.
