### ISSUE TITLE
It is not possible to create a new workbench by returning too many connection lists.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1564]
**Describe the bug**
- When creating a new workbench, too many connection lists are returned at the time of displaying the screen to select the connection list, resulting in an error that the web screen is not displayed normally

**To Reproduce**
- To reproduce, a lot of users and contents are needed, and problems arise in the use environment of SK Telecom

**Expected behavior**
- Performance is currently too slow for the current architecture, and the API needs to be improved to return only the list of connections that need to be shown on the screen.

**Screenshots**
- Error Screenshot in UI
![error](https://user-images.githubusercontent.com/612173/53718597-f81e4900-3e9e-11e9-8941-2fed2ed2410b.png)

**Comment by ufoscw** [comment]
@Taehui 
How many connections are you using?

**Comment by Taehui** [comment]
@ufoscw connection_response_data.txt size is 1.2MB.

**Comment by YooYoungmo** [comment]
@ufoscw 제가 확인한 부분을 공유합니다.
일단 증상은 API(`/api/workspaces/{id}/connections?size=20&page=0&sort=modifiedTime%2Cdesc`) 호출해서 응답을 정상적으로 받아오지만 응답 값이 너무 커서 오류나는 증상입니다.

원인을 찾아 보니 워크벤치 생성 할 때 데이터 커넥션 목록을 조회하는 API에서 사용하지 않는 각 커넥션에 연결된 워크벤치 목록과 워크 스페이스 목록을 함께 반환한다는 것입니다.
사용자가 수가 많은 경우 커넥션에 연결된 워크스페이스와 워크 벤치가 비례하여 커지게 됩니다.
![image](https://user-images.githubusercontent.com/16472109/53846357-e1d3d280-3fef-11e9-8daf-2b14f6cda2b2.png)

코드를 아래 처럼 수정해서 일단 해결 했습니다.
app.metatron.discovery.domain.workspace.WorkspaceController
```java
@RepositoryRestController
public class WorkspaceController {
 // ...
 @RequestMapping(path = "/workspaces/{id}/connections", method = RequestMethod.GET)
  public @ResponseBody
  ResponseEntity<?> findConnectionsInWorkspace(@PathVariable("id") String id,
                                               @RequestParam(value = "name", required = false) String name,
                                               @RequestParam(value = "type", required = false) String type,
                                               @RequestParam(value = "implementor", required = false) String implementor,
                                               @RequestParam(value = "authenticationType", required = false) String authenticationType,
                                               Pageable pageable,
                                               PersistentEntityResourceAssembler resourceAssembler) {
  // 데이터 커넥션만 반환하도록 변경 
  // return ResponseEntity.ok(this.pagedResourcesAssembler.toResource(connections, resourceAssembler));
  return ResponseEntity.ok(this.pagedResourcesAssembler.toResource(connections));
}
}
```

**Comment by ufoscw** [comment]
@YooYoungmo 님. 확인 감사합니다.
적절한 Projection을 사용하도록 수정하는게 좋을것 같습니다.

**Comment by ufoscw** [comment]
@YooYoungmo 
검토해보니 제안해주신 방안이 제일 좋아 보이네요.
수정하신 코드로 PR 올려주실 수 있나요?

**Comment by YooYoungmo** [comment]
@ufoscw 네. 제가 PR 하겠습니다.

**Comment by YooYoungmo** [comment]
머지 완료 되어 Close 합니다.
