### ISSUE TITLE
Add snapshot table name validation

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#1579]
**Is your feature request related to a problem? Please describe.**
When creating snapshot, snapshot table name should only allow 
alphanumeric and _ .
no white space in table name.
Default value of snapshot table name is Snapshot1

**Describe the solution you'd like**
When done button is clicked, validate snapshot table name.
If validation fails show error message.

**Describe alternatives you've considered**

**Additional context**

**Comment by paigechoi** [comment]
confirmed by @joohokim1

Default value of snapshot table name is Snapshot1
Only alphanumeric and _ is allowed with table name
no white space in table name

**Comment by joohokim1** [comment]
2nd integrated test passed.
