### ISSUE TITLE
Error display for calculated row on text table(grid)

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#158]
**Describe the bug**
+ 측정값이 2개 이상인 경우 연산행에 표시가 1개의 연산행으로 표시가 됩니다. 

**To Reproduce**
1. Go to Dashboard
2. Click on 'new chart' icon
3. Select text table
4. Put column on shelf (row: dimension column, aggregation: 2 or more measure )
5. Click on "Total Row" Panel and then enable "Show Calculated Row".
6. See error

**Expected behavior**
- Chart Type 이 Vertical 인 경우 연산행이 두줄로 쪼개져 각 측정값에 대한 연산을 수행해야합니다.
- Chart Type 이 Horizontal 인 경우 각 컬럼 별로 연산을 수행해야합니다. (현재 간헐적으로 연산셀이 나오고 있습니다)

**Screenshots**
- Chart Type 이 Vertical 인 경우
![image](https://user-images.githubusercontent.com/822255/45403013-7db10100-b693-11e8-9298-d79ebdf1af63.png)

- Chart Type 이 Horizontal 인 경우
![image](https://user-images.githubusercontent.com/822255/45403031-93bec180-b693-11e8-8bd3-f37f2f3e455d.png)
![image](https://user-images.githubusercontent.com/6300003/45407587-d210ac80-b6a4-11e8-97bd-89d58dcfc6dc.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser : Chrome
 - Version : 68.0

**Additional context**
+ @metatron-app/design 관련 정의를 한번더 검토해주시고요. 문제가 있는 부분에 대해 가이드 부탁드립니다.

**Comment by esezin** [comment]
@kyungtaak @AnnieHwang @eltriny 
이슈 검토 결과를 아래와 같이 정리합니다.
1번은 본문 이슈, 2번은 관련되어 발생하는 side-effect에 대한 검토입니다.

**1. (본문 이슈) 차트 타입이 가로/세로형인 경우에 대한 각각의 연산행 대응**
- 아래와 같이, 본문에 있는 기대효과와 동일하게 진행되어야 합니다.
- 세로형인 경우, 연산행에서도 세로로 cell을 측정값의 개수대로 표시 & aggregation column에는 각각의 측정값 타이틀을 표시하고, 측정값 컬럼에는 각각의 연산값을 표시합니다.
- 가로형인 경우, 중간에 누락되는 경우 없이 모두 표현되어야 합니다.

**2. (관련이슈) 연산행 내, Dimension이나 Aggregation Column에서의 표시 형식**
- Dimension, Aggregation Column의 경우, 각각 count와 연산식을 (n)형태로 보여주는 것이 기획이었으나, 사용자에게 혼동을 주는 경우가 많다는 의견이 있었습니다.
- 따라서, (측정값을 제외한) Dimension, Aggregation Column은 연산행에서 표시를 생략한 의미의 ‘-‘ (hyphen)만 표기하는 것으로 변경하려고 합니다.

**Comment by kyungtaak** [comment]
@esezin 확인 답변감사합니다. @eltriny 위의 내용에 개발적인 이슈가 있는지 검토해주시고요 이상이 없으면 개발 부탁드립니다.

**Comment by eltriny** [comment]
@kyungtaak 
내용확인했습니다. 개발 진행하며 #37 이슈의 작업과 중첩되는 부분이 있어 #37 이슈 branch에서 작업되어 적용될 예정입니다.

**Comment by esezin** [comment]
@eltriny 
방금 구두논의 했던 것 처럼, 구현이 가능하다면, Dimension을 포함한 부분은 셀을 병합하여 표시해주면 더 좋을 것 같습니다. 문제가 있으면 다시 말씀주십시오.

**Comment by eltriny** [comment]
#237 PR 에 같이 적용되었습니다.. #237 PR 에서 확인 부탁드립니다.
