### ISSUE TITLE
Unable to click cancel button and X button when generating metadata

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#159]
**Describe the bug**
Hive/StagingDB로 메타데이터 생성시 서버 응답이 느려서 로딩바가 도는 경우 '취소' 버튼과 'X' 버튼을 클릭할 수 없음

**To Reproduce**
1. Go to Metadata
2. Click on 'Create metadata'
3. Select 'Hive' or 'StagingDB'
4. Choose a DB connection and Go to Next
6. Choose a Schema and Table
7. Try click cancel button or X(exit) button when progress bar is displayed.

**Expected behavior**
로딩바의 영역이 취소버튼과 X버튼을 가리지 않게 설정하여 로딩 중이라 하더라도 취소버튼과 X 버튼을 언제든지 눌러 메타데이터 생성을 취소할수 있어야 합니다.

**Screenshots**
<img width="1276" alt="metadata-bug-create-by-hive-001" src="https://user-images.githubusercontent.com/28751002/45408134-6e877e80-b6a6-11e8-8413-bf0ee49f74bd.png">

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser : Chrome
 - Version: 68

**Additional context**
IDCUBE

**Comment by ecoloy** [comment]
@brandon-wonjune 구두로 설명드린바와 같이 로딩바의 자체 취소버튼을 추가해달라는 것이 아니라 해당 화면에 본래 있던 'Cancel'버튼과 'X' 버튼을 클릭할수 있게 해달라는 의미입니다.

**Comment by brandon-wonjune** [comment]
@ecoloy 질문드립니다.
해당 화면에서 cancel과 x버튼을 누를경우 기존에 조회 요청은 끊어야되나요?

**Comment by ecoloy** [comment]
@brandon-wonjune 네 끊어주세요.

**Comment by brandon-wonjune** [comment]
@kyungtaak 
기존에 조회 요청시 끊을 수 있을까요?

**Comment by kyungtaak** [comment]
@brandon-wonjune 클라이언트에서 끊으시면 됩니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak 
해당 api를 끊는 api는 어떤걸 호출 하면 될까요?

**Comment by kyungtaak** [comment]
@brandon-wonjune @eltriny 브라우저에서 취소하는 기능은 없나요?

**Comment by brandon-wonjune** [comment]
@kyungtaak 브라우저에는 전송한 api를 취소할수 있는 기능이 없습니다.
워크벤치에서 이와 비슷하게 요청을 끊는 api를 사용하고 있습니다.

**Comment by kyungtaak** [comment]
@ufoscw 혹시 워크벤치에서 사용하는 api 를 여기 JDBC 타입의 적재 단계중 preview 에서 활용할수 있을까요? 검토 부탁드립니다.

**Comment by ufoscw** [comment]
@kyungtaak 
워크벤치는 웹소켓을 사용중이라서 별개의 request로부터 해당 statement 취소가 가능하거든요.

**Comment by ufoscw** [comment]
@brandon-wonjune 
client에서 request를 abort 하는 방향으로 구현하는데 이슈가 있으면 알려주세요.
