### ISSUE TITLE
Resolving GEO_POINT data lookup errors in the DRUID Connection Workbench

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#1590]
**Describe the bug**
드루이드 데이터 커넥션으로 워크벤치를 생성 후 geo 컬럼을 select 하면 `java.util.ArrayList` 문자열로 표시됨.
![image](https://user-images.githubusercontent.com/16472109/53923613-49efea80-40bc-11e9-8a1e-4ca2378971e4.png)

**To Reproduce**
1. 드루이드 데이터 커넥션 생성
![image](https://user-images.githubusercontent.com/16472109/53923636-61c76e80-40bc-11e9-8c72-58768d33cebe.png)
2. 드루이드 커넥션으로 워크벤치 생성
3. geo 컬럼 select

**Expected behavior**
`java.util.ArrayList` 문자열이 아닌 실제 값이 나와야 함,

**Additional context**
* 메타트론 3.2.0-rc3, 드루이드 druid-0.9.1-SNAPSHOT.3.2.0-rc2.201902250720-hadoop-2.7.3 로 테스트 했습니다.

**Comment by ufoscw** [comment]
duplicate issue #1547 
:)

**Comment by YooYoungmo** [comment]
@ufoscw Thanks.  closed this issue.
