### ISSUE TITLE
Error when changing data to geo type

### ISSUE THREAD

**Issue by steve-kyungjin** [metatron-app/metatron-discovery#1591]
**Describe the bug**
데이터 소스에서 지오 데이터 적재시, 지오타입으로 데이터를 변경하면 오류 발생

**To Reproduce**
1. 데이터 소스로 이동
2. 파일로 데이터 올리기 선택 
3. 데이터 로드 후, 특정 데이터를 geo type 으로 변경
4. 적재시 오류 발생

**Expected behavior**
적재가 성공적으로 이루지고, 변경된 데이터가 지오타입으로 변경 되길 희망함

**Screenshots**
![2019-03-07 11 36 41](https://user-images.githubusercontent.com/42233760/53928433-78c28c80-40cd-11e9-919c-edfcabcbb76f.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
@steve-kyungjin #1625 에서 진행하는 개선건으로 진행하고자하는데요. 추가 의견이 있으시면, 해당이슈에 올려주시면 감사드리겠습니다.
