### ISSUE TITLE
Error display for counted row on text table(grid)

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#160]
**Describe the bug**
텍스트그리드의 연산행 중 항목수(Count)를 선택하면, 모든 값이 동일하게 컬럼 ROW 갯수가 반환됩니다.

**Expected behavior**
텍스트그리드의 연산행 중 항목수(Count)를 선택하면, 값이 존재하는 유효한 ROW의 수를 반환되어야 합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/45408426-43e9f580-b6a7-11e8-92b9-fd6661292ef6.png)

**Comment by esezin** [comment]
@AnnieHwang 
항목수가 잘못 표기되고 있습니다. 위 스크린샷 기준으로 첫번 째 항목인 ‘core infra 본부’의 항목수는 ‘1’이 맞습니다.

이와 관련된 이슈가 있습니다.
현재 연산자의 선택과 무관하게, 연산행의 레이블은 총합(Grand Total)로 되어 있습니다. 따라서 연산자를 합계가 아닌 것으로 변경해도 (특별히 사용자가 레이블을 수동으로 수정하지 않을 경우) 계속 ‘총합’으로 나와서 혼동을 줄 여지가 있습니다.
따라서, 아래와 같이 진행하는 것이 어떨까 합니다.

1. 연산자 선택에 따라, ‘레이블 변경’의 초기 값이 해당 연산자 이름으로 변경 (연산자 : ‘항목수’ —> 레이블 : ‘항목수’)
2. 단 사용자가 레이블을 수동으로 수정한 경우, 해당 이름으로 고정
2.1. 사용자가 레이블을 삭제한 경우, 초기 값으로 복귀 
2.2. 복귀된 초기 값은 현재의 선택된 연산자와 동일

**Comment by kyungtaak** [comment]
@esezin 저는 괜찬은것 같습니다만, @metatron-app/design  팀 내부적으로 결론을 내셨는지요?

**Comment by AnnieHwang** [comment]
@kyungtaak 네 해당내용은 내부적으로 논의한 내용입니다.
