### ISSUE TITLE
If you grant permission to a connection, you need a filter function that extracts only the given list.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1608]
**Is your feature request related to a problem? Please describe.**
 - If the workbench connection has the following permissions (1 in the figure) 
<img width="920" alt="2019-03-07 5 13 07" src="https://user-images.githubusercontent.com/612173/53942015-0bc6eb00-40fd-11e9-809f-e40640727afc.png">
 - In case there are many workspaces, to find out which workspace is granted, it must be very uncomfortable. 
<img width="915" alt="2019-03-07 5 13 26" src="https://user-images.githubusercontent.com/612173/53942030-14b7bc80-40fd-11e9-9824-427ff39d4280.png">

**Describe the solution you'd like**
 - Requires filter function to view only the list with permission checked

**Comment by kyungtaak** [comment]
@metatron-app/design please check this issue.

**Comment by deidera08** [comment]
@Taehui @kyungtaak @AnnieHwang @minjung-cho 
#668 이슈를 개선하면 이 이슈도 함께 해결될 듯 합니다.
현재 선택된 필터를 보는 부분이 개선되었는데, 같은 룰로 적용하면 어떨까 싶습니다.

**Comment by Taehui** [comment]
@deidera08  말씀하신 필터 옵션으로 체크된 리스트만 확인은 가능하네요...더보기를 매우 많이 눌러야 하는 번거로움이 있긴 하지만요..

**Comment by Taehui** [comment]
워크스페이스 소유자의 리스트를 다운로드 받는 것은 컨셉 상 어렵나요? 
단체 메일 발송이 필요할 때가 있어서요~

**Comment by deidera08** [comment]
@Taehui 
> 워크스페이스 소유자의 리스트를 다운로드 받는 것은 컨셉 상 어렵나요?

해당 팝업의 목적을 생각하면 특정 조건의 다운로드 기능은 많은 부분이 고려되어야 할 듯 합니다.
@AnnieHwang 와 논의하도록 하겠습니다.

**Comment by Taehui** [comment]
@kyungtaak, @AnnieHwang 이 이슈는 크로즈하고, 다운로드 기능은 필요하다면 별도 이슈로 등록하겠습니다.
