### ISSUE TITLE
Table header layout of column schema page is broken

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#162]
**Describe the bug**
메타데이터 상세 화면의 컬럼 스키마 탭에서 Logical Column Name 글자가 다른 컬럼을 침범함

**To Reproduce**
1. Go to Metadata
2. Click one metadata to enter detail page
3. Click on Column Schema tab

**Expected behavior**
컬럼의 제목이 길면 ... 처리 한 후 마우스 hover시 툴팁에 전체 컬럼제목을 표시해야 합니다.

**Screenshots**
<img width="1514" alt="2018-09-12 4 28 44" src="https://user-images.githubusercontent.com/28751002/45409219-90cecb80-b6a9-11e8-9ba7-162f0b729ed9.png">

**Desktop (please complete the following information):**
- OS: MacOS High Sierra
- Browser : Chrome
- Version: 68

**Additional context**
IDCUBE

**Comment by brandon-wonjune** [comment]
f#162-fix_table_header_in_metadata_column 브랜치 생성하였습니다
