### ISSUE TITLE
Some UX improvements when creating datasets with multiple file uploads.

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1631]
**Problem**
(한)
1. 멀티 파일 업로드 후, 추가 파일 업로드가 불가능함.
2. 업로드한 파일을 초기화 할 수가 없어서 팝업을 닫았다가 열어야 하는 불편함이 있음.
3. 파일 업로드 후, 2단계에서 리스트 선택 과정을 한번 더 거쳐야 해서 불편함.
4. 멀티 파일 중 일부의 데이터셋 생성에 실패한 경우, 어떤 파일이 생성되지 않았는지 확인할 수 없음.
~~5. 싱글 파일일 경우, 3단계에 멀티 파일 용 UI가 적용되어 있음.~~#1516 에서 진행

(Eng)
1. After uploading multiple files, additional files can not be uploaded.
2. I can not initialize the uploaded file, so I have to close and open the popup.
3. After uploading the file, it is inconvenient to go through the list selection process again in Step 2.
4. If the dataset generation of some of the multi-files fails, we can not confirm which file was not created.
~~5. In case of single file, the multi-file UI is applied in step 3.~~#1516

**Solution**
(한)
1. 1단계에서 추가 업로드 기능 진행. #1515 기획 및 디자인 참조.
2. 1단계에서 업로드한 파일 초기화 버튼 필요. (파일 업로드 초기 상태로 돌아가기)
![스크린샷 2019-03-13 오후 3 51 41](https://user-images.githubusercontent.com/28773903/54259113-fee84280-45a7-11e9-8159-f5957101b424.png)
3. 2단계에서 모든 데이터셋 리스트를 체크한 상태를 초기 상태로 함.
4. 3단계 Done 시, 생성 실패한 파일의 이름을 에러 메시지에 보여줌. 
-- detail : 생성에 실패한 데이터셋이 있는 경우, 랜딩화면에서 에러 토스트 출력. ☞[031.0] ‘n개의 데이터셋 생성에 실패하였습니다. (데이터셋 이름, 데이터셋 이름...)
~~5. 싱글 파일일 경우에는 테이블 형태가 아닌, 기존의 싱글 파일 용 UI를 사용해야 함.~~#1516 에서 진행

(Eng)
1. Proceed with additional upload function in step 1. See # 1515 Planning and Design.
2. You need to reset the file you uploaded in step 1. (Return to the initial state of file upload)
3. In step 2, all data set lists are checked and initialized.
4. When step 3 is done, the name of the file that failed to be created is displayed in the error message.
-- detail: Error toast output on landing screen if there is a dataset that failed to generate. ☞ [031.0] n dataset creation failed. (Dataset name, dataset name ...)
~~5. In case of single file, you should use existing single file UI instead of table format.~~#1516

**Alternatives**
None

**Additional context**
#1515

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang 

1. 1단계에서 추가 업로드 기능 -> 업로드가 진행되고 있을 때엔 추가 업로드가 불가능함을 명시해야 할 듯 (이 이유때문에 추가 업로드를 지원하지 않겠다고 결론이 났었음) 반대로 현재 진행되고 있는 업로드가 완료되면, 추가로 업로드 가능이라고 하는 것도 괜찮습니다.
2. 리셋 버튼 좋습니다.
3. 좋습니다.
4. 좋습니다.

**Comment by minjung-cho** [comment]
@minjung-cho @AnnieHwang 1번 내용 기획서 보와해서 본문에 다시 올려두었습니다. 디자인 진행합니다~

**Comment by koeun222** [comment]
@AnnieHwang 
- 상단 타이틀영역 추가 / reset 버튼 추가 
- 파일 업로드 진행중인경우 추가 업로드영역 dim (opacity 30%)
![image](https://user-images.githubusercontent.com/42256760/54357584-bad96880-46a1-11e9-8045-c3741953164f.png)

**Comment by joohokim1** [comment]
@koeun222 @minjung-cho @AnnieHwang 

전 좋습니다.

**Comment by sang-hee-lee** [comment]
4.번 기능도 #1516 에서 처리하겠습니다.

**Comment by joohokim1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [멀티파일 업로드 시 처음 초기값은 모든것이 선택되어 있어야 함](https://trello.com/c/uVgCTH5N/24-%EB%A9%80%ED%8B%B0%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C-%EC%8B%9C-%EC%B2%98%EC%9D%8C-%EC%B4%88%EA%B8%B0%EA%B0%92%EC%9D%80-%EB%AA%A8%EB%93%A0%EA%B2%83%EC%9D%B4-%EC%84%A0%ED%83%9D%EB%90%98%EC%96%B4-%EC%9E%88%EC%96%B4%EC%95%BC-%ED%95%A8)
