### ISSUE TITLE
 Logical type information in data source detail popup is incorrect

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#164]
**Describe the bug**
대시보드의 데이터소스 상세 팝업에서 특정 컬럼의 메타데이터를 확인했을때, 실제로 메타데이터에 저장되어 있는 논리 타입과 다르게 나옴

**To Reproduce**
1. Create Dashboard with datasource which connected own metadata
2. Click on Datasource detail
3. Click Column detail tab
4. Select some column which has logical type information

**Expected behavior**
메타데이터에서 입력한 논리 타입 정보가 보여야 함

**Screenshots**
메타데이터 정보
<img width="1511" alt="2018-09-12 4 51 37" src="https://user-images.githubusercontent.com/28751002/45410525-e193f380-b6ac-11e8-852c-f5384d72acbf.png">

실제 데이터소스 상세 팝업에서 보이는 정보
<img width="1514" alt="2018-09-12 4 51 45" src="https://user-images.githubusercontent.com/28751002/45410524-e193f380-b6ac-11e8-8d7f-f890b7b5e1c7.png">

**Desktop (please complete the following information):**
- OS: MacOS High Sierra
- Browser : Chrome
- Version: 68

**Additional context**
IDCUBE

**Comment by ecoloy** [comment]
본 이슈와 관련된 페이지에서 추가로 발견한 사항입니다.
메타데이터에서 입력한 개별 컬럼의 설명이 데이터소스 상세 팝업에 나타나지 않습니다.
<img width="1510" alt="2018-09-12 6 30 28" src="https://user-images.githubusercontent.com/28751002/45416168-43a72580-b6ba-11e8-934a-3f52925b98a0.png">
<img width="1510" alt="2018-09-12 6 29 51" src="https://user-images.githubusercontent.com/28751002/45416169-43a72580-b6ba-11e8-95a2-ac1b0ab345ce.png">

**Comment by brandon-wonjune** [comment]
f#164-fix_logicaltype_in_datasource_preview 브랜치 생성하였습니다

**Comment by kyungtaak** [comment]
@brandon-wonjune  #177 PR 코멘트 내용 을 포함하여 수정하신다음 PR 부탁드립니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak 적용하였습니다

**Comment by brandon-wonjune** [comment]
해당 이슈는 데이터소스 미리보기 화면 디자인 변경건과 겹치는 부분이 있어 #9 PR에서 같이 다루도록 하겠습니다.
