### ISSUE TITLE
 URI type dataset support

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1644]
**Problem**
We need to support file datasets which are not uploaded by browser, but located on designated locations like HDFS, S3, etc.

**Solution**
<img width="1449" alt="스크린샷 2019-03-15 오후 3 49 16" src="https://user-images.githubusercontent.com/28773903/54413687-f6c00c80-4739-11e9-9e3b-4be2b298e3fb.png">
<img width="1450" alt="스크린샷 2019-03-15 오후 3 51 49" src="https://user-images.githubusercontent.com/28773903/54413789-50283b80-473a-11e9-9da0-4e6127dcdd2d.png">
<img width="900" alt="스크린샷 2019-03-20 오후 1 53 13" src="https://user-images.githubusercontent.com/28773903/54660154-8be74a80-4b18-11e9-86ce-11ab35b6e1cb.png">
<img width="905" alt="스크린샷 2019-03-20 오후 1 53 22" src="https://user-images.githubusercontent.com/28773903/54660155-8c7fe100-4b18-11e9-95de-c2c474bb767a.png">
<img width="1449" alt="스크린샷 2019-03-15 오후 3 49 26" src="https://user-images.githubusercontent.com/28773903/54413693-faec2a00-4739-11e9-9978-d2638976621a.png">

**Alternatives**
None

**Additional context**
METATRON-1584

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다- 

생성화면
![image](https://user-images.githubusercontent.com/42256760/54339863-61f5da00-4679-11e9-8933-c9464eda8b50.png)

생성 > URI 1단계
![image](https://user-images.githubusercontent.com/42256760/54339942-979ac300-4679-11e9-96b0-ac0b35ebbb47.png)

생성 > URI 2단계
#1223 이슈의 디자인 레이아웃 확인부탁드립니다-

**Comment by AnnieHwang** [comment]
@minjung-cho @koen222 1번 타입 선택에서는 'URI' 였는데 2번 스텝에서 타이틀이 'Create File URI XXXX' 인 것이 이상해요. 둘다 'File URI'이거나, 'URI'여야 할것 같습니다.

**Comment by koeun222** [comment]
@AnnieHwang  네에~ 1번 타입 선택화면을 "File URI"로 명칭 통일해서 퍼블 전달합니다-

**Comment by AnnieHwang** [comment]
@koeun222 저... 아직 퍼블 넘기지 말아주세요. URI를 URL로 바꾸고 File URI만이 아니라 모든 URL로 커버 하도록 바꾸기로 해서요. 문구 정정이 필요할꺼 같아요

**Comment by koeun222** [comment]
"URI , File URI" -------->  "URL"로 변경되었습니다-

**Comment by minjung-cho** [comment]
@AnnieHwang @joohokim1 조금 전 논의한 내용 반영했습니다. 확인 부탁드립니다-

**Comment by AnnieHwang** [comment]
@minjung-cho 확인했습니다!

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang 저도 확인했습니다!

**Comment by minjung-cho** [comment]
@sang-hee-lee 누락된 화면(csv, txt, excel)에 대한 와이어프레임을 본문에 추가하였습니다. 
@joohokim1 @AnnieHwang 검토 한번 부탁드립니다-
