### ISSUE TITLE
The maximum number of characters in the dataset name is too short

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1647]
**Problem**
원소스가 엑셀인 경우, '파일명+시트명'이 데이터셋의 기본값으로 입력되는데, 꽤 길이가 긴 경우가 있습니다. 이때, 입력 가능한 문자 수가 50자로 제한되어 있어서 '데이터셋 생성 완료' 까지 매끄럽게 이어지지 않습니다.
If the source is excel, 'filename + sheet name' is entered as the dataset default, which may be quite long. At this time, since the number of characters that can be input is limited to 50 characters, it does not lead smoothly to 'dataset creation completion'.

**Solution**
(한)
1. 데이터셋 이름을 150자까지 입력 가능하도록 변경합니다. (기존 50자)
2. 데이터셋 이름 초기값이 150자를 초과할 경우, 자동으로 150자까지만 입력시켜 줍니다. 
3. 사용자가 150자를 초과하여 입력하려고 할때, 입력 박스에 '150자까지 입력할 수 있습니다'라는 메시지를 보여줍니다.

(영)
1. Change the dataset name to allow input of up to 150 characters. (Original 50 characters)
2. If the initial value of the dataset name exceeds 150 characters, it will automatically enter up to 150 characters.
3. When the user tries to input more than 150 characters, the input box shows the message 'You can enter up to 150 characters'.

**UI sample**
![스크린샷 2019-03-12 오후 6 52 19](https://user-images.githubusercontent.com/28773903/54190855-0cde8a80-44f8-11e9-9b74-4975d77d6678.png)

**Alternatives**
None

**Additional context**
설명 부분에 입력 수 제한이 있다면, 이 또한 위에서 정의한 것과 같은 UX가 적용되어야 합니다.
If there is a limit on the number of entries in the description part, this also applies to UX as defined above.

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang 
검토 완료했습니다. @sang-hee-lee 이대로 진행하시면 좋을 것 같습니다.

**Comment by minjung-cho** [comment]
@koeun222 @paigechoi  데이터 플로우 화면에서 이름에 말줄임 처리가 안되어 있는 것 같습니다. 추가 부탁드립니다-

**Comment by koeun222** [comment]
@paigechoi 에러문구는 공통ui 적용해주시고, 에러문구 노출 후 2초뒤 사라지도록 작업부탁드립니다-
