### ISSUE TITLE
There is a fatal error in Metatron UI 

### ISSUE THREAD

**Issue by kaviranga** [metatron-app/metatron-discovery#1648]
I 've hosted the metatron-discovery in our company's own server.I've experienced several times if there any server restart or server shutdown the metatron-discovery fails to save a workbook or created dashboard . The all the workbooks and created are vanised or destroyed . Is there any backup option to save workbooks or the dashboards !

**Comment by alchan-lee** [comment]
@kaviranga 
I'm sorry to hear that. 

Generally, we always save the whole data
but it looks like you are using --init option when you (re)start this application.

Please add --init argument only the first time or when you want to reset your temporary environment.

If you did not set this argument, you can share your customized configuration then we can check something wrong with. (application.yaml or any env variables. Except for sensitive information, of course.)

Please don't be depressed, you're almost there 😃

**Comment by kaviranga** [comment]
@alchan-lee
Thanks for the quick reply . After removing the --init option the metatron-discovery workbooks are not vanished :-) . So the problem solved :-) .
