### ISSUE TITLE
When creating a dataset, the user must be able to control the column count

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1650]
**Problem**
원소스가 CSV인 경우, 데이터에 기반하여 자동으로 행과 컬럼이 구분되고 있음. (Paragraph로 행이 구분되고, Period로 컬럼이 구분)
불필요한 컬럼이 지나치가 많이 생길 경우가 발생함.
If the source is CSV, the row and column are automatically separated based on the data. (Paragraph separates rows, Period separates columns)
Unnecessary columns may be overloaded.

**Solution**
1차적으로는 현재 구현 상태와 같이 데이터를 기반하여 자동으로 행과 컬럼을 구분함.
단, 자동으로 나뉘어진 컬럼 수가 7개 초과인 경우, default 값을 7로 두고 사용자가 변경할 수  있도록 함.
Primarily, rows and columns are automatically separated based on data, such as the current implementation state.
However, if the number of columns that are automatically divided exceeds 7, the default value is set to 7 so that the user can change it.
![스크린샷 2019-03-13 오후 1 19 23](https://user-images.githubusercontent.com/28773903/54253496-b5d9c380-4592-11e9-84ac-02016f18682d.png)

**Alternatives**
컬럼의 최대 수를 제한하는 방법이 있으나, 이는 사용성이 좋지 않다고 판단하여 위의 해결방안을 제안하였습니다.
There is a way to limit the maximum number of columns, but this is not good for usability and we proposed the above solution.

**Additional context**
None

**Comment by joohokim1** [comment]
@minjung-cho @AnnieHwang 

이 이슈는 좀 핀트가 안맞는 것 같습니다. 일반적인 빅데이터 파일 데이터셋은 컬럼수가 7개가 넘습니다.
제가 생각한 이 기능은, 컬럼수의 기본값은 서버에서 파악한 값이 되어야 하고, 그게 맞지 않다고 사용자가 판단을 하면 임의로 수정해서 진행하는 것입니다.

최대 컬럼수는 서버에서 설정 또는 휴리스틱으로 지정해서 내리기 때문에 기획단계에서 최대 컬럼 수를 상수로 지정할 필요는 없습니다.

https://github.com/metatron-app/metatron-discovery/issues/1374 를 한번 참고해주세요. (이 이슈를 그대로 기획이슈로 사용하셔도 될 것 같습니다만)

**Comment by minjung-cho** [comment]
본 이슈는 해당 사항이 없으므로 닫습니다
