### ISSUE TITLE
Cannot set notebook server !

### ISSUE THREAD

**Issue by hashansl** [metatron-app/metatron-discovery#1659]
I have Installed metatron our our company server and I have Installed Jupyter notebook on my laptop. I tried to connect to jupyter through metatron but it gives run time error.can someone help me. ( In metatron I have created notebook server. I gave host as my laptop IP address and gave jupyter running port )

**Comment by comefeel99** [comment]
What language do you use? python? r?

**Comment by hashansl** [comment]
I use python. I have installed Python utility module for metatron also.

![Screenshot from 2019-03-14 23-18-38](https://user-images.githubusercontent.com/45277530/54406428-87eaa100-46b0-11e9-83e6-5a4bdd7f6ce6.png)
![Screenshot from 2019-03-14 23-18-57](https://user-images.githubusercontent.com/45277530/54406429-88833780-46b0-11e9-90c1-61656f08ab05.png)
![Screenshot from 2019-03-14 23-20-03](https://user-images.githubusercontent.com/45277530/54406431-88833780-46b0-11e9-971b-6b6d461f0d39.png)

**Comment by hashansl** [comment]
Is there any document to follow Notebook Server setup procedure

**Comment by kyungtaak** [comment]
@hashansl Currently, we have only Korean documents. :( So, we will translate the guidance documents that we use internally and send you by next week.

**Comment by hashansl** [comment]
@kyungtaak Thank you..

**Comment by i1befree** [comment]
I think this issue is related #1671
@hashansl please retry your test after release 3.2.0. It will be released within 2 weeks.

**Comment by hashansl** [comment]
@i1befree Okay.. I will try. Thank you!

**Comment by kyungtaak** [comment]
@hashansl I'm sorry.. T.T so much time has passed .. I do not know if your notebook server is well connected with metatron discovery. If it's not too late, check out the comments below and there will be a guide. 

https://github.com/metatron-app/metatron-discovery/issues/2031#issuecomment-490781292
