### ISSUE TITLE
Error when calling api from notebook

### ISSUE THREAD

**Issue by steve-kyungjin** [metatron-app/metatron-discovery#1671]
**Describe the bug**
Notebook 에서 메타트론 데이터를 가져오기 위해 메타트론 API 사용시 오류 발생

**To Reproduce**
1. 메타트론에서 노트북 생성시 datasource 로 선택후 노트북을 생성한다.
2. 생성된 노트북에 접속한다.
3. print(dataset)으로 메타트론 데이터 소스를 가져온다.

**Expected behavior**
노트북에서 정상적으로 해당 데이터를 가져와 노트북 화면에 출력한다.

**Screenshots**
<img width="1100" alt="Screen Shot 2019-03-12 at 2 32 28 PM" src="https://user-images.githubusercontent.com/42233760/54423074-2af3f700-4753-11e9-953e-adfecd9aaf28.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by i1befree** [comment]
@kyungtaak I think this issue must be released in 3.2.0 version.

**Comment by alchan-lee** [comment]
it will be fixed in the coming version (3.2.0-rc4)
