### ISSUE TITLE
can we create multiple Line chart in the dashboard ?

### ISSUE THREAD

**Issue by hashansl** [metatron-app/metatron-discovery#1684]

**Comment by i1befree** [comment]
You mean multi-series bar like this?
<img width="1550" alt="multi-series-bar" src="https://user-images.githubusercontent.com/526622/54581317-735f2d80-4a4f-11e9-8882-65cd9e393ef6.png">

or

multiple bar charts in on dashboard like this?
<img width="1913" alt="multiple-bar-chart" src="https://user-images.githubusercontent.com/526622/54581329-88d45780-4a4f-11e9-947d-d82154544e6c.png">

**Comment by hashansl** [comment]
Sorry ! I want to create multiple line chart
<img width="684" alt="G50DE" src="https://user-images.githubusercontent.com/45277530/54583568-fac68580-49ea-11e9-9b6c-3c29b7e697a6.png">

**Comment by i1befree** [comment]
You can make multi series chart in two way.

1. Multi measure line chart
<img width="1839" alt="multi-series01" src="https://user-images.githubusercontent.com/526622/54585124-9ba15900-4a5c-11e9-85d0-3c412f21d0cf.png">

2. One or more measure split by Dimension
<img width="1836" alt="multiseries2" src="https://user-images.githubusercontent.com/526622/54585179-c8ee0700-4a5c-11e9-9be0-2848918a09cb.png">

**Comment by hashansl** [comment]
Thank you @i1befree .. useful stuff
