### ISSUE TITLE
Join query issue

### ISSUE THREAD

**Issue by hashansl** [metatron-app/metatron-discovery#1685]
I get this error, when I try this join query 

SELECT * FROM druid._pbngx left join druid._pbngx ON druid._pbngx.Category=druid._pbngx.Category;

Error: 

An error occurred during query execution. Please contact your system administrator. (SQLException (00000) (-1) : Error -1 (00000) : Error while executing SQL "SELECT * FROM druid._pbngx left join druid._pbngx ON druid._pbngx.Category=druid._pbngx.Category": Remote driver error: RuntimeException: org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 38 to line 1, column 49: Duplicate relation name '_pbngx' in FROM clause -> ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 38 to line 1, column 49: Duplicate relation name '_pbngx' in FROM clause -> CalciteContextException: From line 1, column 38 to line 1, column 49: Duplicate relation name '_pbngx' in FROM clause -> SqlValidatorException: Duplicate relation name '_pbngx' in FROM clause)

**Comment by i1befree** [comment]
You can modify and issue your query like this :

SELECT * FROM druid._pbngx t1 left join druid._pbngx t2 ON t1.Category=t2.Category;

**Comment by hashansl** [comment]
Thank you @i1befree It works !
