### ISSUE TITLE
Show file upload location when creating dataset with file

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#1693]
**Is your feature request related to a problem? Please describe.**
When you create a dataset with a file, the upload location for each file is not displayed.

**Describe the solution you'd like**
Once the file is uploaded, we want the upload location and file size to be displayed in the appropriate location.

**Describe alternatives you've considered**

**Additional context**

**Comment by joohokim1** [comment]
![스크린샷 2019-03-22 오후 4 40 44](https://user-images.githubusercontent.com/42257727/54807660-4a45d380-4cc1-11e9-99ca-4a5c11afa2f4.png)

@sang-hee-lee @minjung-cho @AnnieHwang 
위의 내용대로 진행을 해주시면 될 것 같습니다. Assignee 조정하겠습니다.
