### ISSUE TITLE
Dashboard filter error

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#1694]
**Describe the bug**
Please refer to demo url : https://discovery.metatron.app/app/v2/workbook/971b2ae9-1f95-45c4-b9ca-80727e580096

**To Reproduce**
1. refer to screen shot.

**Expected behavior**

**Screenshots**
<img width="1621" alt="dashboard-filter-error" src="https://user-images.githubusercontent.com/526622/54661409-5abd4900-4b1d-11e9-89ff-8ff0bfcf6c94.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by eltriny** [comment]
@kyungtaak 지난 셀렉션 필터 이슈를 처리하면서 같이 해결된 듯 합니다. 확인 부탁드립니다.

**Comment by kyungtaak** [comment]
@eltriny 확인완료하였습니다.
