### ISSUE TITLE
Entering description in detail page of metadata is difficult

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#170]
**Is your feature request related to a problem? Please describe.**
1. 메타데이터 상세 페이지의 설명 입력창에서 엔터를 누르면 줄바꿈이 되지 않고 설명 입력이 완료되어 버림
2. 글자수 제한이 150자라서 충분한 설명을 넣을수 없음
3. 입력창의 높이가 짧아서 긴 설명을 넣기에 불편함

**Describe the solution you'd like**

1. 설명 입력 하는 상태에서 엔터를 누르면 줄바꿈이 되고, 오른쪽에 체크(v)버튼을 클릭할때 입력 완료하도록 수정
2. 글자수 제한을 500자로 설정
3. 입력창의 높이를 현재보다 2배 크게 설정

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
@ecoloy 입력 관련 제안 감사합니다. 현재 공통입력 가이드가 있는데 description 가이드가 있는지 모르겠네요.  
@metatron-app/design  내부에서 존재하는지 확인해주시고요. description 관련 입력은 이 이슈를 통해 진행했으면 합니다. 가이드 부탁드립니다.

**Comment by ecoloy** [comment]
@kyungtaak 확인해보니 한줄 텍스트 인풋박스에 대한 공통 입력 가이드가 있는데, 두줄 이상의 텍스트 박스에 대한 가이드는 없네요. 기획/디자인 진행해서 본 이슈에 가이드 공유하도록 하겠습니다.

**Comment by ecoloy** [comment]
@kyungtaak @AnnieHwang 
 Common 문서에 한줄/두줄 이상 text input에 대한 정의를 추가하였습니다. 
![2018-09-13 3 33 17](https://user-images.githubusercontent.com/28751002/45471072-ec14c280-b76a-11e8-8f84-c3be95838250.png)

디자인 가이드는 아래와 같습니다.
![2018-09-13 3 32 52](https://user-images.githubusercontent.com/28751002/45471089-f767ee00-b76a-11e8-82dd-1bbda36206c5.png)

그리고 글자수 제한은 개별 페이지의 요소마다 달라질수 있으므로 메타데이터 설명에 대한 500자 제한은 아래 MDM 기획문서에 기재해두었습니다.
![2018-09-13 3 34 49](https://user-images.githubusercontent.com/28751002/45471147-28482300-b76b-11e8-9213-16bd8caaf26c.png)

관련 기획문서들은 위키에도 업데이트 해두었습니다.

**Comment by deidera08** [comment]
@kyungtaak @paigechoi @eltriny @brandon-wonjune @kyungtaak @AnnieHwang @minjung-cho 
이 이슈는 사실상 종료인듯 합니다.

담당 개발자분께서 작업하신 결과를 (local)확인하였습니다만 텍스트 입력/저장 액션이 General rule과 상이하여 holding인것으로 내부파악하였습니다.

UX개선 방향으로 텍스트 입력 후 focus out에도 저장되는 쪽으로 방향을 잡았고, 점진적으로 적용해나가려 합니다.
이에 해당하는 이슈는 [#199](https://github.com/metatron-app/metatron-discovery/issues/199)에서 진행중이므로 이 이슈는 작업하신 부분 적용시켜주시고 종료해도 무방할 듯 합니다.

(@kyungtaak @AnnieHwang @eltriny 고려해야 하는 다른 부분이 있다면 알려주세요)

**Comment by kyungtaak** [comment]
@deidera08 지금 이에 대한 이슈는 입력 공간에 대한 문제 인것 같은데요. #199 에도 관련 이슈가 포함이 되어 있나요?

**Comment by deidera08** [comment]
@kyungtaak
입력공간이 입력영역의 height를 의미하시는거라면 수정작업이 된 것을 (local에서) 확인하였습니다

**Comment by kyungtaak** [comment]
@deidera08 제가 확인을 못하고 있었네요. 위 언급하신 내용은 확인했습니다. 일단 이슈는 닫도록 하겠습니다.
