### ISSUE TITLE
Data Ingestion error

### ISSUE THREAD

**Issue by hashansl** [metatron-app/metatron-discovery#1706]
There is a datatype error when uploading csv file to the druid customized version for metaron-discovery. The problem is there is no matching datatype for double type data. The version of druid for metatron -discovery is 0.9.1.  (directly uploading to druid using json )

**Comment by i1befree** [comment]
@hashansl Would you give me your ingestion script?

**Comment by hashansl** [comment]
@i1befree 

{
  "type" : "index",
  "spec" : {
    "dataSchema" : {
      "dataSource" : "ipdr_hourly_usage_summarize_data_2",
      "parser" : {
        "type" : "string",
        "parseSpec" : {
          "format" : "csv",
          "timestampSpec" : {
            "column" : "date_time",
            "format" : "auto"
          },

          "columns" : [
            "date_time",
            "protocol_name",
            "category",
            "upload",
            "download",
            "total",
            "cell_id",
            "cell_name",
            "cell_site",
            "district",
            "longitude",
            "latitude",
            "uri"
           ],
          "dimensionsSpec" : {
            "dimensions": [
            "protocol_name",
            "category",
            {"name":"upload","type":"double"},
            {"name":"download","type":"double"},
            {"name":"total","type":"double"},
            "cell_id",
            "cell_name",
            "cell_site",
            "district",
            "longitude",
            "latitude",
            "uri"
            ],
            "dimensionExclusions" : [],
            "spatialDimensions" : []
          }
        }
      },
      "metricsSpec" : [
         {
          "name" : "count",
          "type" : "count"
        },
        {
          "name" : "value",
          "type" : "doubleSum",
          "fieldName" : "total"
        }
      ],
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "HOUR",
        "queryGranularity" : "NONE",
        "intervals" : ["2018-09-24/2019-03-25"]
      }
    },
    "ioConfig" : {
      "type" : "index",
      "firehose" : {
        "type" : "local",
        "baseDir" : "/data/2019-03-2012",
        "filter" : "*.csv",
        "parser":null
       },
       "appendToExisting":false,
       "skipFirehoseCaching":true

    },
    "tuningConfig" : {
      "type" : "index",
      "targetPartitionSize" : 10000000,
      "maxRowsInMemory" : 1000000,
      "forceExtendableShardSpecs":true
    }
  }
}

**Comment by i1befree** [comment]
Thanks. I will try this script.

**Comment by hashansl** [comment]
@i1befree Thank you

**Comment by i1befree** [comment]
@hashansl Before I evaluate your ingestion script, I found type definition in dimension spec. Druid does not support dimension type. Dimension in Druid must be string type. When using with Metatron Discovery, you can change dimension type because it treats dimension type internally. After ingesting your data, you can create custom column in Metatron Discovery like this :
<img width="959" alt="custom-column" src="https://user-images.githubusercontent.com/526622/54801502-83bf1480-4caa-11e9-9a83-4a5b57e5a95c.png">

But unless you are thinking about using double type field as a filter, I recommend ingestion as a measure.
