### ISSUE TITLE
Embedded chart implementation error when parameter is long.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1711]
**Describe the bug**
- Embedded chart implementation error when parameter is long.

**To Reproduce**
Call Example ) 
http://www.test.com/app/v2/dashboard/3f9aaf8e-d541-4187-95b3-e11bccc1460e?work_no=O190314000077&event_time=2019-03-14%2020:00:00%2F2019-03-21%2020:00:00&occr_dt=20190308&occr_dt=20190309&occr_dt=20190310&occr_dt=20190311&occr_dt=20190312&occr_dt=20190313&occr_dt=20190314&occr_dt=20190315&occr_dt=20190316&occr_dt=20190317

Error Message)

MysqlDataTruncation:Data truncation:Data too long for column 'query_from_uri' at row 1

**Comment by YooYoungmo** [comment]
# 문제 원인
위의 URL 호출 시 datasource_query 테이블 query_from_uri 컬럼(VARCHAR 255)에 URL를 저장하는데 uri가 255를 넘는 경우 오류 발생함.
![image](https://user-images.githubusercontent.com/16472109/54890099-1a7a1400-4eeb-11e9-93f5-3dfb0e98dc0c.png)

# 해결 방안
* 긴 URL을 수용할 수 있도록 app.metatron.discovery.domain.datasource.DataSourceQueryHistory 엔터티를 변경해야함.
* 이미 서비스를 운영하는 경우 데이터베이스 스키마를 변경하면 됨.
```sql
ALTER TABLE `polaris_v2`.`datasource_query`
CHANGE COLUMN `query_from_uri` `query_from_uri` TEXT NULL DEFAULT NULL;
```
*
