### ISSUE TITLE
Fail to ingest a data source with WKT point type column

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1713]
**Describe the bug**
I tried to ingest a data source that contained a WKT Point type column, but an error occurred.

**To Reproduce**
1. Attempt to load the file with the sample data below.
[geo_test.zip](https://github.com/metatron-app/metatron-discovery/files/2998968/geo_test.zip) 
2. The GeoPoint column is specified as a Point type in the data source creation process.

**Expected behavior**
A data source containing geo-type must be loaded.

**Additional context**
Druid Log : [log.txt](https://github.com/metatron-app/metatron-discovery/files/2998973/log.txt)

**Comment by navis** [comment]
ingesion spec?

**Comment by navis** [comment]
Not a bug
