### ISSUE TITLE
Metadata information is missing on data source detail popup when creating dashboard 

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#173]
**Describe the bug**
대시보드 생성시 데이터소스의 상세 팝업을 띄우면 메타데이터가 보여야 하는데 보이지 않음

**To Reproduce**
1. Create Dashboard
2. Select one datasource on datasource lists
3. Click detail button on right panel

**Expected behavior**
대시보드 생성 화면에서 띄운 데이터소스 상세 팝업에도 메타데이터 정보가 나타나야함
(생성된 대시보드의 데이터소스 상세 팝업에는 메타데이터가 정상적으로 보이고 있음)

**Screenshots**
<img width="1512" alt="2018-09-12 6 16 03" src="https://user-images.githubusercontent.com/28751002/45415427-9ed81880-b6b8-11e8-9cec-0d68bc323954.png">
<img width="1512" alt="2018-09-12 6 15 46" src="https://user-images.githubusercontent.com/28751002/45415429-9f70af00-b6b8-11e8-8f43-ec8c9c431e7f.png">

**Desktop (please complete the following information):**
- OS: MacOS High Sierra
- Browser : Chrome
- Version: 68

**Additional context**
IDCUBE

**Comment by brandon-wonjune** [comment]
f#173-fix_metadata_info_in_creating_dashboard 브랜치 생성하였습니다

**Comment by brandon-wonjune** [comment]
해당이슈는 데이터소스 미리보기 디자인 변경건도 포함되어 #9 이슈의 브랜치에서 같이 작업하도록 하겠습니다.
