### ISSUE TITLE
Creating data source problem

### ISSUE THREAD

**Issue by hashansl** [metatron-app/metatron-discovery#1730]
When we are trying to get the data from druid engine it gives "name is null"  error. How can we fix this  ?

![Screenshot from 2019-03-25 05-17-30](https://user-images.githubusercontent.com/45277530/54908252-db819980-4ebd-11e9-8c4a-ee9950127879.png)

**Comment by i1befree** [comment]
@hashansl Can I test it with a previously issued ingestion script(#1706)?

**Comment by hashansl** [comment]
yes you can. @i1befree we actually uploaded our csv files using json/curl. problem is we can't get it from metatrone druid engine.
