### ISSUE TITLE
Database connection problem

### ISSUE THREAD

**Issue by hashansl** [metatron-app/metatron-discovery#1742]
I have given my metatron login password but it gives "invalid Connection. Please check server information" error . How can I connect it ? Is there any good document to refer ?
![Screenshot from 2019-03-26 05-56-36](https://user-images.githubusercontent.com/45277530/54988885-bbb9a680-4f8d-11e9-9d81-9e6c2b789b34.png)

**Comment by hashansl** [comment]
I have given my metatron login password but it gives "nvalid Connection. Please check server information" error .

**Comment by i1befree** [comment]
@hashansl It looks like bug. At this time, you can input any characters for User name and Password. It will be fixed at #1295.

**Comment by brandon-wonjune** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [데이터소스 컬럼 변경 시, 시간타입을 String으로 변경 처리 되나, Data탭에서 에러문구뜸](https://trello.com/c/CPvbOnan/85-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%86%8C%EC%8A%A4-%EC%BB%AC%EB%9F%BC)

**Comment by kyungtaak** [comment]
@ufoscw Please check this issue.

**Comment by ufoscw** [comment]
@hashansl 
This issue was resolved in #1295.
(Included in the 3.2.0 release)
