### ISSUE TITLE
need display rules for the UI elements in the chart area of ​​the data flow.

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1745]
**Describe the bug**
![스크린샷 2019-03-19 오전 11 44 51](https://user-images.githubusercontent.com/28773903/55037327-bb3e1000-5060-11e9-87b3-f23e4056e005.png)
1. 아이콘과 선의 시작점이 겹칩니다.
2. 2nd depth 부터 행간이 좁아서 요소들이 겹칩니다.
3. 선이 아이콘을 지나갈때 겹치지 않는 것이 좋겠습니다.
4. 아이콘 아래의 데이터셋 이름과 선이 겹쳐서 이름의 가독성이 떨어집니다.
5. 1-4번 문제 해결 후, 아이콘 크기 및 데이터셋 이름 가로 영역 조정이 필요할 수 있습니다. (기존 이슈)

**Expected behavior**
(디자인 시안)
![image](https://user-images.githubusercontent.com/42256760/55045374-ed5f6a00-5080-11e9-8c86-a6c339b6031e.png)

**Solution**
(논의 필요)
1.3. imported database : normal & focus 원 흰색 채움
       dataset : normal 아이콘만 흰색 채움 /  focus 원 흰색 채움
2.4. Dataflow차트에서 세로는 fix, 가로는 flexible 요청드립니다
5-1. icon size 40 -> 55로 수정 
5-2. 이름 20자에서 줄바꿈 최대40자까지, 40자 넘으면 말줄임되고 호버시 툴팁

**Additional context**
None

**Comment by minjung-cho** [comment]
@joohokim1 디자인과 개발쪽에서 작업 중이라고 합니다~ 참고 부탁드립니다

**Comment by gochemjackets** [comment]
1.3. 아이콘 외각선 안쪽 부분을 BG와 동일한 컬러로 채웁니다
2.4. Dataflow차트에서 세로는 fix, 가로는 flexible 변경
5-1. icon 55로 변경
5-2. Tooltip: 한 줄당 20자 최대 2줄로 표시하고 초과 시 말 줄임, Hover: 한 줄당 최대 20자 전체내용표시
위 사항대로 조치하겠습니다.

**Comment by gochemjackets** [comment]
#1745 & #1223 중복되는 내용들이 있어서 #1223에서 작업하였습니다. 
1.3. 아이콘 외각선 안쪽 부분을 BG와 동일한 컬러 - 완료
2.4. Dataflow차트에서 세로는 fix, 가로는 flexible 변경 - 완료
5-1. icon 55로 변경 - 완료
5-2. Tooltip: 한 줄당 20자 최대 2줄로 표시하고 초과 시 말 줄임, Hover: 한 줄당 최대 20자 전체내용표시 - 완료
