### ISSUE TITLE
[Urgent]Need to extend the number of csv file's columns.

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#1748]
**Is your feature request related to a problem? Please describe.**
Currently, metatron discovery limits the number of columns to 512 when registering datasource with csv file. Some users, such as Samsung Heavy Industries, generate csv files with more than 1200 columns, and we should be able to support them.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
@i1befree ok I'll check it and get back to you soon
