### ISSUE TITLE
Combination chart requires secondary axis settings

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#175]
**Is your feature request related to a problem? Please describe.**
콤바인 차트의 보조축에 설정을 할 수 있어야 함

**Describe alternatives you've considered**
![idcube-12-01](https://user-images.githubusercontent.com/6300003/45416386-ce882000-b6ba-11e8-8948-280d62d13ada.PNG)

**Additional context**

**Comment by dave-taeho** [comment]
#175-combination_chart_secondary_axis 브랜치 추가하였습니다.

**Comment by dave-taeho** [comment]
@kyungtaak 
컴바인차트에 ChartAxis 타입의 보조축 필드 추가 요청드립니다. 

![2018-10-16 3 39 18](https://user-images.githubusercontent.com/14234215/46997133-dd4e7080-d159-11e8-82b5-fda769a94535.png)

**Comment by kyungtaak** [comment]
@dave-taeho "secondaryAxis" 라는 속성명으로 추가 했습니다. (그리고.. 브랜치 명명 규칙이 잘못되었네요.)

**Comment by babokim** [comment]
@kyungtaak 이 이슈에서 각 measure에 대해 primary, secondary axis 사용하는 것을 설정하는 기능이 포함되는 건가요?

**Comment by esezin** [comment]
@babokim @kyungtaak 
보조축 옵션에 대한 구현과 함께, 아래의 정책도 함께 포함될 예정입니다.
유형은 각 Measure의 Contextual Menu에서 설정하며, Bar Chart는 Primary Axis, Line Chart는 Secondary Axis를 사용하는 것이 현재의 정책입니다.
![175-01](https://user-images.githubusercontent.com/28885462/49209342-94970200-f3fd-11e8-8577-1b443649c39e.PNG)

**Comment by alchan-lee** [comment]
fixed in #1106
