### ISSUE TITLE
 Each screen has different representation for null in data grid

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1750]
**Describe the bug**
Each screen has different representation for null in data grid

Test file : [Long-Term-Unemployment-Statistics 복사본.xlsx](https://github.com/metatron-app/metatron-discovery/files/3011447/Long-Term-Unemployment-Statistics.xlsx)

<img width="679" alt="스크린샷 2019-03-27 오후 12 53 45" src="https://user-images.githubusercontent.com/28773903/55050128-8054d000-5092-11e9-8f93-a4e61ba46bc6.png">
<img width="677" alt="스크린샷 2019-03-27 오후 12 53 55" src="https://user-images.githubusercontent.com/28773903/55050129-82b72a00-5092-11e9-8e34-86ac07ee0f0f.png">

**Expected behavior**
All grids should display '(null)'.

**Additional context**
#1709

**Comment by paigechoi** [comment]
1. 데이터셋 생성씬
`api/preparationdatasets/file_grid?storedUri=file:///Development/dataprep/uploads/5f7afe29-f56a-42ec-829f-9ceb81bf2d05.xlsx
` 
![A5447772-C7B2-4656-96CC-3E4FEA124CE9](https://user-images.githubusercontent.com/42233517/55059794-39c39d80-50b3-11e9-927a-faef37c4c57c.png)

2 . 데이터셋 상세
`http://localhost:4200/api/preparationdatasets/{dsId}?preview=true`
![Uploading ED89A74C-E176-476E-BFCE-7C3B74D61CFB.png…]()

3 . 데이터플로우 상세 메인그리드
`/api/preparationdatasets/id/transform?ruleIdx=&offset=0&count=100`
![09AD987D-5F0A-4EA2-8C70-2F30438E8197](https://user-images.githubusercontent.com/42233517/55059869-68417880-50b3-11e9-92f2-d760e20b1279.png)

결론적으로 1번에서는 서버에서 null로 내려와서 null로 찍고 있음
2,3번은 null로 내려오지 않고 빈 값인 "" 로 내려와서 화면에서 "" 로 찍고 있음

하지만 2,3 번에 컬럼 타입이 TIMESTAMP 라서 date format을 적용시키는데 값이 ""이기 때문에 Invalid date 나옴.
Main grid 에서 Invalid date 가 반환되면 "" 로 보여달라고 전달받음 (예전 @joohokim1)
2,3 번엔 Invalid date 가 나오면 "" 로 변환하는 작업이 되어있지 않음

**Comment by joohokim1** [comment]
@minjung-cho @paigechoi 두 가지 문제가 섞여있어서 comm이 어렵군요.
@ksparknot 
1번의 경우, null 로 내려가지 않게 해주세요. (서버 작업)
2, 3번의 경우, invalid date가 발생하면, 내려온 내용을 그대로 string으로 보여주도록 해주세요. 이 경우면 empty string으로 나오겠네요.
