### ISSUE TITLE
A long snapshot name throws an error in attempting snapshot table generation.

### ISSUE THREAD

**Issue by gochemjackets** [metatron-app/metatron-discovery#1752]
**Describe the bug**
It happens when typing a long snapshot name attempts to generate snapshot table. Also, the snapshot name input accepts an unlimited number of characters.

**To Reproduce**
1. Go to snapshot data flow
2. Click on Edit rules
3. Click on Snapshot
4. Type a long snapshot name
5. See error

**Expected behavior**
It starts to generate a snapshot table after a popup disappeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/29448764/55051451-85b51900-5098-11e9-9449-66cfff12baed.png)

**Desktop (please complete the following information):**

**Comment by gochemjackets** [comment]
@joohokim1 needed to discuss about snapshot input text.

**Comment by joohokim1** [comment]
@gochemjackets This will be discussed in next release.

**Comment by joohokim1** [comment]
When there is Hangul (and some unicode characters) in a W.DS name, an error occurs for it's Hangul path name. I'll change the behavior this case.
One more thing, currently time string in snapshot name is UTC. I'll change to use the local time zone.

**Comment by joohokim1** [comment]
I guess this issue has already been resolved. I'll check this up again.

**Comment by joohokim1** [comment]
It's been fixed already. (Maybe with another issue)
