### ISSUE TITLE
Is it bug that it does not connect metatron dataset to jupyter when i try to make jupyter connection? 

### ISSUE THREAD

**Issue by Ntels-justinjang87** [metatron-app/metatron-discovery#1800]
**Describe the bug**
->it does not connect to dataset on jupyter notebook

**To Reproduce**
1. Go to Metatron work-space
2. Click on Notebook button
3. Create Notebook with Data-source
4. Open Jupyer Notebook 
5. Run and Check data-set connection
6. See error (see below screen-shot)

**Expected behavior**
-> To connect dataset on Jupyter notebook from metatron

**Screenshots**
![image](https://user-images.githubusercontent.com/49216609/55462491-d8ab4500-5631-11e9-87cd-ea7be176f657.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version [e.g. 22] : Chrome version 73.0.3683.86
 - Server OS: CentOS 6.10
**Additional context**

**Comment by omelas** [comment]
![image](https://user-images.githubusercontent.com/11882021/55713503-c6634980-5a2b-11e9-935d-9a8e596dfdb2.png)

3.2.0-rc4에서 확인하였습니다.
