### ISSUE TITLE
 Dataset names and connections overlap in the data flow, making them less readable.

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1804]
**Describe the bug**
Dataset names and connections overlap in the data flow, making them less readable.
<img width="549" alt="스크린샷 2019-04-04 오전 11 40 07" src="https://user-images.githubusercontent.com/28773903/55526121-c6331900-56ce-11e9-8e22-bdcfdfe8c75a.png">

**Expected behavior**
The UI elements should be well organized so there is no visual crosstalk.
![55045374-ed5f6a00-5080-11e9-8c86-a6c339b6031e](https://user-images.githubusercontent.com/28773903/55526092-9d128880-56ce-11e9-9da8-19513ee17b15.png)

**Additional context**
#1745

**Comment by joohokim1** [comment]
@minjung-cho Is this duplicated with https://github.com/metatron-app/metatron-discovery/issues/1745?

**Comment by minjung-cho** [comment]
@joohokim1 

There was an unprocessed part in # 1745, so I made another issue.

The direction I wanted was 'curved', but I was told it was difficult.
So, it seems to be finished to prevent overlapping of normal status icon and connection line.

@koeun222 Please handle this issue. thank you.

**Comment by joohokim1** [comment]
Closing this issue. It seems to be resolved in https://github.com/metatron-app/metatron-discovery/issues/1745.
