### ISSUE TITLE
Add progress bar for local file upload on ingestion stage

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1816]
**Is your feature request related to a problem? Please describe.**
- Improve the upload UI so users know intuitively about file upload status.

**Describe the solution you'd like**
- Displays the progress bar so that users can check the progress when uploading a file.

**Comment by minjung-cho** [comment]
게스트 워크스페이스를 워크스페이스 목록에서 숨겨서, 게스트 워크스페이스로 진입할 수 없도록 하면 될 것 같습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak file upload progress 상태를 알기위해서는 별도의 api가 필요합니다. 확인 부탁드립니다.

@metatron-app/design 이 화면은 어떤 변경된 UI를 적용하면되나요?

**Comment by deidera08** [comment]
@brandon-wonjune 화면 기획중입니다. 완료되는대로 공유드리도록 하겠습니다.

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang @brandon-wonjune 
화면 기획안 공유드립니다. 파일 업로드시 진행바가 추가되었습니다.
[#1816_Improve handling local file.pptx](https://github.com/metatron-app/metatron-discovery/files/3106429/1816_Improve.handling.local.file.pptx)

**Comment by koeun222** [comment]
@AnnieHwang @deidera08 디자인화면 공유드립니다- 각 상태별 알림문구(노랑) 확인부탁드려요~ 

1.초기상태
![image](https://user-images.githubusercontent.com/42256760/56578570-ec324600-6608-11e9-8618-baaa6425bf61.png)
2. 파일업로드 중
![image](https://user-images.githubusercontent.com/42256760/56578588-f6544480-6608-11e9-8a2b-237956210671.png)

3.파일 업로드 중 취소 
![image](https://user-images.githubusercontent.com/42256760/56578632-12f07c80-6609-11e9-81b2-d58498a4cff1.png)

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang @brandon-wonjune 
 파일을 1차적으로 업로드 완료 이후에 유저가 다른 파일로 올릴 경우 상황에 정리가 안되어 다음과 같이 보완합니다.

기본적으로 파일을 업로드 성공하면 Preview화면으로 자동 진입합니다.
![스크린샷 2019-04-24 오후 5 25 42](https://user-images.githubusercontent.com/42257766/56644154-1988fd80-66b6-11e9-936c-5390bb305b98.png)

본 화면에서 제공하던 '다른 파일로 업로드'기능은 삭제합니다.
다만 이전단계로 가는 버튼을 둬서 사용자가 이전화면에서 다른 파일로 올릴 수 있습니다.
![스크린샷 2019-04-24 오후 5 25 54](https://user-images.githubusercontent.com/42257766/56644162-1db51b00-66b6-11e9-9b24-ef10e3a8878c.png)

이전화면으로 진입한다고 해도 사용자가 다른 파일을 올리기 전까지 기존에 올려둔 파일의 정보는 유지해야 합니다.
