### ISSUE TITLE
JDBC batch datasource error

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#182]
**Describe the bug**
jdbc batch datasource could not execute query.

**To Reproduce**
1. create batch datasource.
- source type : Database
- Select data that does not have a timestamp field. (using current time  timestamp).
- Ingest periodically
- gets the entire data

2. wait datasource status change 'ENABLED'
3. go to datasource's detail view.
4. click batch history.
5. See error

**Expected behavior**
ingest executed periodically.

**Screenshots**
<img width="1559" alt="sc" src="https://user-images.githubusercontent.com/3770446/45460250-43993b00-b737-11e8-8fd4-ec2485ffb135.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Additional context**
NA

**Comment by ufoscw** [comment]
@metatron-app/design 
배치형 데이터 소스 생성하고 주기적으로 증분 데이터를 가져올 때 
증분 여부의 기준이 되는 필드는 time-type column입니다.
time-series형 데이터가 아닌 경우 임의로 현재 시간 Field를 추가하여 데이터를 적재하고 있는데요. 
이럴경우는 증분의 기준이 되는 Field가 존재하지 않아 증부데이터를 조회할 수가 없습니다.
그러므로 데이터 소스 생성 단계 중 schema config 단계에서 time-type column이 존재하지 않을 경우는 증분만 가져오는 옵션은 선택할 수 없고 주기적으로 전체 데이터를 갱신하는 옵션만 선택 가능하도록 수정되어야 할것 같습니다.
![image001](https://user-images.githubusercontent.com/3770446/45475863-862f3780-b778-11e8-980f-858564a74ec6.png)

**Comment by ufoscw** [comment]
@metatron-app/design 
추가적인 요청사항 중 최대 Row를 늘려달라는 이슈가 있습니다.
기본갑 10000건은 placeholder로 표시하여 입력 가능한 필드임을 유저에게 알려주고
최대값은 5백만건으로 늘리는 방안이 어떨까 합니다.

**Comment by AnnieHwang** [comment]
@ufoscw 다운로드 시 말씀이신가요? 서버에서 가능하시면 물론 가능할꺼 같습니다. 답변 달아주시면 추가 기획을 하도록 하겠습니다.

**Comment by ufoscw** [comment]
@AnnieHwang 
배치로 데이터를 가져올때 최대 row 숫자입니다.
스크린샷의 Max. query row 부분입니다.
증분 옵션 부분도 검토 해보시고 기획서 업데이트 해주시면 front-end 작업에 들어가도록 하겠습니다.

**Comment by minjung-cho** [comment]
@AnnieHwang 이건 진행할때 아래 이슈와 몇가지 UX 이슈도 함께 처리 하면 좋을 것 같습니다...
(공통)스크롤영역 : METATRON-1417

**Comment by ufoscw** [comment]
@minjung-cho 
해당 오류는 중결함으로 최대한 빨리 Front개발팀에 전달되어야 하는 건이니 빠른 피드백 바랍니다.

**Comment by minjung-cho** [comment]
@ufoscw 황매니저님과 얘기했고요. 제안주신 것과 같이 기획서에 반영해 두겠습니다. 캡쳐할만한 내용은 아니라서.. 
V.1.31에 반영해 두겠습니다.

**Comment by minjung-cho** [comment]
![2018-09-17 4 37 41](https://user-images.githubusercontent.com/28773903/45610781-1ed6f780-ba98-11e8-8b89-c1418f5ac5a9.png)
혼선이 있을지 몰라서 캡처한 기획서 올립니다. 담당자분 참고 부탁드립니다. ;)

**Comment by ufoscw** [comment]
@brandon-wonjune 위와 같이 Front 수정 해주시면 됩니다.
1. timestamp field를 현재시간으로 선택 시 증분배치 옵션 비활성화
2. Batch Max Row 값 수정

**Comment by minjung-cho** [comment]
@brandon-wonjune 아, 추가로 Batch Max Row 의 입력값을 우측 정렬해 주시고 천단위 콤마도 적용부탁드립니다. 입력 범위가 늘어나서 입력 필드의 너비도 수정되어야 할듯 합니다.

**Comment by brandon-wonjune** [comment]
@ufoscw @minjung-cho 
Batch의 Max Row 입력값의 최댓값을 5,000,000로 설정하였습니다.
5,000,000이 넘어가면 error 메세지를 표시하도록 하였습니다.
입력필드를 수정하였습니다. 

(해당 페이지의 전체적인 수정이 있어서 확인하기 위해 해당부분만 마크업을 변경하였습니다.)
![2018-09-17 9 50 06](https://user-images.githubusercontent.com/42233627/45623885-aede6680-bac3-11e8-8c04-9b0ff28c667c.png)

디자인의 모든 수정 부분은 #35 에 반영되었습니다. 
35번 이슈에서 컴포넌트를 분리하는 작업을 하여서 일부분만 수정하게 되었습니다.

schema step의 TIMESTAMP 컬럼 선택단계에서 current time을 선택하는 경우 Batch 의 INCREMENTAL을 선택할 수 없도록 변경하였습니다.
