### ISSUE TITLE
Workbench icon reordered for extended connections

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#1820]
**Describe the bug**
Workbench icon reordered for extended connections.

**To Reproduce**
1. create workbench with extended connection
2. See error

**Expected behavior**

**Screenshots**
![image (5)](https://user-images.githubusercontent.com/3770446/55692568-52518300-59e4-11e9-9121-dac47fa9bc26.png)

**Desktop (please complete the following information):**

**Additional context**
Tone adjustment of the workspace icon is also required
<img width="1248" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/55692642-ede2f380-59e4-11e9-925c-1e2a705d9213.png">

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/56198691-5893cf00-6076-11e9-844a-bd37bee82de5.png)
@eltriny 밝은배경에 쓰일일 아이콘 타입 추가했습니다- 적용부탁드립니다
