### ISSUE TITLE
Alias for value doesn't work.

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#1821]
**Describe the bug**
No action is taken when selecting field's Alias ​​for value menu in chart view or dashboard edit screen.

Return value for request is :
{"code":"GB0001","details":"NullPointerException: "}

**To Reproduce**
1. Go to workbook
2. Click on edit dashboard
3. Click on Alias for value metnu on datasource field.

**Expected behavior**
We should see a screen where you can edit the alias value for the field value.

**Screenshots**

**Desktop (please complete the following information):**
 - Version 3.2.0

**Additional context**

**Comment by kyungtaak** [comment]
@eltriny plz check as below
![image](https://user-images.githubusercontent.com/822255/55776132-a9d01b80-5ad6-11e9-9be9-fb97609b090a.png)
