### ISSUE TITLE
Create data source: fail to get list of database

### ISSUE THREAD

**Issue by wm9947** [metatron-app/metatron-discovery#1823]
PostgreSQL 을 Data connection에 등록하여 datasource를 만들고자 합니다.
데이터베이스 내에는 2개의 스키마가 있고
sample 스키마에는 4개의 테이블이 있습니다. datasource 생상을 할시 Table 로 preview를 보려고 할 때에 
JdbcDataConnectionException: Fail to get list of database : ERROR: relation "table1" does not exist

메세지와 함께 테이블을 선택 할 수 없습니다.
Query를 통해서는 4개 테이블 각각을 datasource로 등록이 가능합니다.

혹시 이유를 아실까요?

감사합니다.

**Comment by kyungtaak** [comment]
@wm9947 리포팅 주셔서 감사합니다. 내부적으로 확인해보고 답변드리도록 하겠습니다.

**Comment by alchan-lee** [comment]
여러개의 스키마를 가지는 데이터베이스의 테이블 목록을 조회할 때
문제가 있는 것으로 판단됩니다.

해당 내용 바로 수정할 예정입니다.

**Comment by kyungtaak** [comment]
@wm9947 수정되었습니다. 차주 3.2.1 릴리즈에 반영될 예정입니다.
