### ISSUE TITLE
Map chart tooltip issues

### ISSUE THREAD

**Issue by sting009** [metatron-app/metatron-discovery#1825]
**Describe the bug**
1. When the spatial analysis is executed, the value information of the tooltip is displayed differently.

2. If choropleth is the default value, no value information is displayed in the tooltip

**To Reproduce**
1. Go to mapchart 
2. Click on spatial analysis

**Expected behavior**

**Screenshots**
1. 
![image](https://user-images.githubusercontent.com/42328567/55763139-b9cd0880-5aa0-11e9-8bde-290cf5a5b935.png)

2.
![image](https://user-images.githubusercontent.com/42328567/55763169-d8cb9a80-5aa0-11e9-8079-2fea6eaf5725.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by choonglee170924** [comment]
@kyungtaak  작업중인 브렌치는 f#1825_map-chart-tooltip 입니다.
