### ISSUE TITLE
The widget is not saved when the layer created with choropleth option in Geospatial Analysis.

### ISSUE THREAD

**Issue by sting009** [metatron-app/metatron-discovery#1826]
**Describe the bug**
Type is set to multipolygon, spec is not saved

**To Reproduce**
1. Go to map chart
2. Set point and polygon type on shelf
3. Click on spatial analysis
4. Click save and see error 

**Expected behavior**
If multipolygon type, change to polygon type

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by choonglee170924** [comment]
@kyungtaak 작업중인 브렌치는 f#1826_map-chart-widget-save 입니다.
