### ISSUE TITLE
JVM option change. (permgen -> meta)

### ISSUE THREAD

**Issue by kuckjwi0928** [metatron-app/metatron-discovery#1841]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
JVM option value change.
-XX:MaxPermSize -> -XX:MaxMetaspaceSize

**Describe alternatives you've considered**
From JDK8, the permgen space has been deleted.

**Additional context**
None

**Comment by kyungtaak** [comment]
@kuckjwi0928 You are right. We missed this part. I think it needs to fix the default option in the shell file.
Thank you for your nice report :)

**Comment by kuckjwi0928** [comment]
If you are busy, i can help you :)

**Comment by kyungtaak** [comment]
welcome 👍

**Comment by ufoscw** [comment]
Thank you for your help.
