### ISSUE TITLE
Disappearing summary info in workspace folders

### ISSUE THREAD

**Issue by alchan-lee** [metatron-app/metatron-discovery#186]
**Describe the bug**
Summary information disappeared when click on logo.

**To Reproduce**
1. Go to any **folders** into workspace.
2. Click on 'Logo' 
3. Disappearing summary info.

**Expected behavior**
summary information div show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/42234141/45462582-692c4180-b743-11e8-917f-0bba55dba438.png)

**Additional context**
METATRON-1255

**Comment by kyungtaak** [comment]
@eltriny #48 이슈와 함께 처리했으면 합니다. #f48-folder_deletion_error 브랜치에서 함께 작업해주세요.

**Comment by eltriny** [comment]
@kyungtaak #48 번 이슈과 같이 처리하여 같이 묶어서 PR 을 올렸습니다.
