### ISSUE TITLE
About Custom Install

### ISSUE THREAD

**Issue by BookXHD** [metatron-app/metatron-discovery#1862]
When i Running the Metatron Binary and making the CUSTOM INSTALL, after export METATRON_HOME and shell command "sh metatron.sh --init start", there appears an error in /logs/xxx.out file :"Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher" what i wanna ask is , did you ever meet this error? Or can you give me any suggestion?

**Comment by alchan-lee** [comment]
It seems to set the wrong METATRON_HOME path.
you have to set HOME directory to the root of the application.

please refer to the image below.
![image](https://user-images.githubusercontent.com/42234141/56174640-69b8ed80-602e-11e9-81f7-8ee3765c541e.png)

**Comment by BookXHD** [comment]
@alchan-lee I noticed that "${METATRON_HOME}/discovery-server/target" in /bin/common.sh, so the 
 METATRON_HOME should mean the root catalog. So, after maven install into a TAR，i should put the TAR in root catalog, not the initial catalog？Am i right?

**Comment by BookXHD** [comment]
@alchan-lee Thanks it resloved ,but i just remembered when i make the CUSTOM INSTALL first time, i set the METATRON_HOME root catalog of the all project and then worked ,so i misunderstood ,anyway, thanks!!

**Comment by alchan-lee** [comment]
@BookXHD 
I'm glad to hear it worked well for you.

If you discuss on our forum page when you have a general question, then more people would be participating. 
[https://groups.google.com/forum/#!forum/metatron-discovery](https://groups.google.com/forum/#!forum/metatron-discovery)
(not a forced rule, just suggestion.😃)

Anyway please feel free to share your difficulties,
Thanks.

**Comment by BookXHD** [comment]
Oh , of course , i don't know that before , i will next time~
