### ISSUE TITLE
Modify GNB logo location.

### ISSUE THREAD

**Issue by alchan-lee** [metatron-app/metatron-discovery#187]
**Describe the bug**
Modify GNB logo location and fix some additional minors.

**Screenshots**
![image](https://user-images.githubusercontent.com/42234141/45463026-6599ba00-b745-11e8-9a15-eb5d91f4f055.png)

![image](https://user-images.githubusercontent.com/42234141/45463038-79452080-b745-11e8-9c14-1b7af5f9167d.png)

**Additional context**
METATRON-1293

**Comment by minjung-cho** [comment]
@AnnieHwang 현재 수정안으로 metatron.app에 반영되어 있습니다. 의도하신바대로 되어 있는지 확인 부탁드립니다~

**Comment by AnnieHwang** [comment]
@minjung-cho 해당부분 완료된 사항이네요. 이슈 클로즈 하시면 될것같습니다.
