### ISSUE TITLE
Add more examples and explanations to expressions in advanced editor 

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#188]
**Describe the bug**
- 데이터 플로우 advanced editor 팝업에서 수식의 예제와 설명이 부족함
- 유효성 체크를 하지 않으면 마침 버튼을 누를 수 없음
- 번역 틀린 부분 
- update 시 기존 수식이 입력되어있지 않음

**To Reproduce**
1. Go to dataflow main grid 화면
2. Click on command 'SET' and click on advanced editor 
3. click on function to see examples and explanation

**Expected behavior**
- 각 Function에 맞는 설명과 예제를 볼 수 있도록 수정
- 유효성 체크를 하지 않아도 마침을 누를 수 있게 변경
- formula -> expression
- update 시 다시 advanced editor를 열었을 때 기존 수식이 입력되어 있어야 함

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by goodljy** [comment]
기능 확인 함. 2018.10.16.
