### ISSUE TITLE
About Liner Predictive

### ISSUE THREAD

**Issue by BookXHD** [metatron-app/metatron-discovery#1882]
When i use Liner Predictive in a test line chart, there appears an error :"TypeError: Cannot read property '0' of undefined";How can i handle this, Or it is a bug?
![image](https://user-images.githubusercontent.com/33343442/56288401-518dbf00-6151-11e9-9f1b-7851ddeb6c36.png)

**Comment by BookXHD** [comment]
Helloooooooo anyone can help me?

**Comment by i1befree** [comment]
@BookXHD It is a bug. @kyungtaak Can you please schedule the bug fix?

**Comment by kyungtaak** [comment]
@BookXHD @i1befree 
We are planning to fix this bug to the next iteration. Maybe it will be fixed within the next week.

**Comment by BookXHD** [comment]
@i1befree @kyungtaak Thanks!! 
I will try in the next iteration
