### ISSUE TITLE
Error that do not filter selection in charts

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#189]
**Describe the bug**
1. 차트에서 셀렉션 필터링 
2. 상단의 셀렉션 필터 리스트에서 X 눌러서(혹은 초기화/Refresh) 셀렉션 취소 
3. 다른 차트에 셀렉션 필터링
4. 셀렉션 리스트로 안올라감

**To Reproduce**
http://52.231.184.135:8185/app/v2/workbook/406d4b17-b9c4-4d22-9d8e-19784e72f0e2
1. 오른쪽 차트 셀렉션 필터링 (선택 필터링)
2. 선택 필터링 삭제, 'Refresh'버튼 클릭
3. 왼쪽 차트 셀렉션 필터링
4. 선택 필터링 되지 않음

**Expected behavior**
선택필터링이 제대로 되어야 함

**Screenshots**
![2018-09-13_11-32-35](https://user-images.githubusercontent.com/6300003/45463865-d5f60a80-b748-11e8-8200-03011b2bcee8.gif)

**Comment by dave-taeho** [comment]
@AnnieHwang 3.0.3 브랜치로 로컬 및 testbed1번에서 테스트시 동일한 증상이 발견되지 않음을 확인하였습니다.

[testbed1 - 최하단 sales 대시보드 참조]
http://52.231.184.135:8185/app/v2/workbook/67bcda20-e00f-476b-a1bc-3db51eb4686c

**Comment by AnnieHwang** [comment]
@dave-taeho 아.. 저도 확인해보니 그러네요. 혹시 뭐 고친게 있으신가요? 3.0.2에서는 안되었던게 지금은 되서요..

**Comment by kyungtaak** [comment]
@AnnieHwang 이 이슈는 종료하겠습니다.
