### ISSUE TITLE
filter; if two table has same column names, it cannot apply to both table

### ISSUE THREAD

**Issue by wm9947** [metatron-app/metatron-discovery#1901]
When table1 and table2 contain same column name, the filter function can use for only one table.

ex) I made a filter for table1 column price.
But table2 also contain column which is price.
So I want to make a filter for table2 price column.
-> It does not work.

if tables contain same name of the column, not only it cannot apply both, but also it cannot make separately.

Could you check it?

Many thanks,

**Comment by kyungtaak** [comment]
@wm9947 you mean this situation?
![multi_column_samename](https://user-images.githubusercontent.com/822255/56545158-a7c78b80-65b1-11e9-9e8e-4c730c929417.gif)

**Comment by wm9947** [comment]
@kyungtaak 
yes. The table name is not changed. and this filter is not apply to both tables.

**Comment by kyungtaak** [comment]
@wm9947 ok! We'll fix this soon.

@eltriny Can you confirm and fix this bug?

**Comment by kyungtaak** [comment]
@wm9947 This error has been fixed and merged into the master. Please check it out for tomorrow's release and let me know if there's a problem. 
And I'll this issue. Thank you for your bug report! :)
