### ISSUE TITLE
fix dimension alias script, css error.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#1904]
**Describe the bug**
Entering a long alias for a dimension value causes the style to collapse.
<img width="997" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/56413734-62f6d880-62c3-11e9-9399-d22d86091690.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
(Any)

**Additional context**

**Comment by minjung-cho** [comment]
The design guide has been delivered as follows.
![image (57)](https://user-images.githubusercontent.com/28773903/57266983-54793100-70b9-11e9-8cef-68587f72335c.png)
Please refer to the job.@eltriny
