### ISSUE TITLE
Chart selection filter error

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#1907]
**Describe the bug**
1. When the data of the date type is individually selected, the filter condition refers to the data in the range.
<img width="1698" alt="metatron_Discovery_및_DevTools_-_52_231_184_135_8180_app_v2_workbook_920137b0-758a-4330-9e3e-d71a3be1d491_및_Slack_-_Polaris_및_다운로드" src="https://user-images.githubusercontent.com/3770446/56414971-3c3aa100-62c7-11e9-9b0d-d101ced90e8c.png">

2. Color changed when Gauge chart selection filter.
- Before
<img width="1164" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/56415148-d0a50380-62c7-11e9-9d00-9f0c502318f5.png">

- After selection
<img width="1164" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/56415271-2d082300-62c8-11e9-805c-44bafcb40d43.png">

3. When there is only one chart on the dashboard, when you apply the selection filter, it is invisible and appears when you click on dashboard
<img width="1453" alt="Chart_selection_filter_error_·_Issue__1907_·_metatron-app_metatron-discovery_및_metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/56415514-e49d3500-62c8-11e9-84b7-7ede5ee3a2ad.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
@eltriny Can this issue(#1694) be fixed together? please check it out.
