### ISSUE TITLE
Druid connection

### ISSUE THREAD

**Issue by wm9947** [metatron-app/metatron-discovery#1911]
Hello,

I try to use  data connection with my own druid.

![image](https://user-images.githubusercontent.com/19628618/56491136-72c02800-6522-11e9-812e-7863b204b0dc.png)

Data Connection: work
add datasource: work

add to dashboad to use datasource: not work
*datasource is Linked type

Could you check it?

Many thanks,

**Comment by ufoscw** [comment]
@wm9947 
The query generator for temporary data source generation seems to require modification of column delimiter processing.
It will be fixed soon.
