### ISSUE TITLE
Error that do not filter selection (by area point) in charts

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#192]
**Describe the bug**
1. 차트에서 셀렉션 필터링 => 상단의 셀렉션 필터 리스트에서 X 눌러서(혹은 초기화/Refresh) 셀렉션 취소 => 다른 차트에 (영역 포인트로) 영역으로 셀렉션 필터링 =>  셀렉션 리스트로 안올라감

2. 다른 차트에 (영역 포인트로) 영역으로 셀렉션 필터링 =>  차트의 다른 영역을 클릭하면 셀렉션 필터가 취소되지 않음

#189  참조

**Screenshots**
![2018-09-13_14-15-51](https://user-images.githubusercontent.com/6300003/45468548-24fb6a00-b760-11e8-9ac7-616f107a0720.gif)
![2018-09-13_14-16-38](https://user-images.githubusercontent.com/6300003/45468552-275dc400-b760-11e8-93db-9d974da52ec2.gif)

**Comment by dave-taeho** [comment]
#192-multi_selection_filter_error 브랜치 추가하였습니다.
