### ISSUE TITLE
The number of data sources in the workspace UIs are different

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#1921]
**Describe the bug**
The number of data sources in the workspace UIs are different.

1. Each UI should show the total number of data sources (do not show the number shown on the screen) 일단 각각의 UI에는 전체 데이터소스 건수가 보여져야 함 (현재 내부 팝업은 화면에 보여지는 갯수를 보여주고 있습니다)
![image](https://user-images.githubusercontent.com/6300003/56557412-da837b00-65d5-11e9-86fa-b15c6b18880e.png)

2. Two UIs should show the same value : 데이터소스 숫자를 나타내는 두 UI부분은 동일한 숫자 값(전체 데이터소스 수)이 나와야 함

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/56557517-4ebe1e80-65d6-11e9-9086-15b8e2f5cbed.png)

**Comment by minjung-cho** [comment]
이슈가 된 부분에 전체 개수만 표시되도록 하고, 리스트에 넘버열도 큰 의미가 없어서 삭제부탁드립니다.

**Comment by i1befree** [comment]
이 이슈는 위에 개수랑 아래 실제 개수가 안맞는 문제가 있습니다.
확인 바랍니다.

**Comment by i1befree** [comment]
아래 스크린샷 참조 바랍니다.
<img width="1870" alt="count-error" src="https://user-images.githubusercontent.com/526622/56568291-a322c780-65f1-11e9-8a41-b37b051a5cbc.png">

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho 위 오류의 원인은 명확하지 않는 정의에서 출발하는것 같습니다.
현재, 소스코드를 살펴보니 workspace 상단의 datasource 개수는 오픈데이터를 포함하여 workapce 에 publish 된 총 데이터소스 건수를 의미합니다. 그리고, 데이터 소스를 클릭했을때 나오는 목록은 그 상단 총 데이터소스 건수에서 현재 사용 가능한 데이터 소스를 가져오게 되있더군요.

음.. 이경우 상태와 상관없이.. 링크된 데이터 소스를 저 상단에 표현하는 게 좋을까요? 아니면, 상태가 enable 된 데이터소스 카운트로 표현하는게 좋을까요?

**Comment by minjung-cho** [comment]
@AnnieHwang @kyungtaak 제 생각에는.. 이 화면에서는 사용가능한(enable) 데이터소스만 나오고, 관리 화면(퍼블리시)에서는 퍼블리시된 데이터소스가 모두 나오되, disable 인 데이터소스에 라벨이 표시되는 것이 좋을 것 같습니다. 어떻게 생각하시나요?

**Comment by kyungtaak** [comment]
@eltriny 
- (GET) /api/workspaces/{workspace Id}/datasources  API 내  'status'  Parameter 를 추가했습니다. 
  ex. status=enabled,disabled  또는 단건 추가 status=enabled
- forListInWorkspaceView projection 내 결과값에 status 속성값을 추가했습니다. 화면 구성시 참고해주세요.

**Comment by koeun222** [comment]
@AnnieHwang @minjung-cho 수정된 디자인화면 공유드립니다
리스트영역을 더 확보하기위해 헤더부분과 버튼 영역 개선되었습니다

1. 워크스페이스 > 데이터소스 
 - 데이터소스 타이틀에 갯수 삭제
 - 검색, 필터링 타이틀 오른쪽으로 위치 수정
 - 하단 버튼 위아래 마진 수정 
![image](https://user-images.githubusercontent.com/42256760/56947516-67937a80-6b68-11e9-8a06-12ab1d4af6f4.png)

2. 워크스페이스 > 멤버&그룹
 - 타이틀과 중복되는 기존 헤더 삭제
 - 하단 버튼 위아래 마진 수정 
![image](https://user-images.githubusercontent.com/42256760/56947522-6c582e80-6b68-11e9-99eb-5b8c5487b084.png)

**Comment by minjung-cho** [comment]
해당 화면에서 Enabled과 Disabled  상태의 데이터소스 목록과 개수를 보여주는 것으로 정리되었습니다. 단, disabled인 목록에서는 상태 라벨을 붙입니다.
---
본 이슈 범위는 아니지만, 이 화면에 몇가지 개선점/오류가 있어서 덧붙입니다. (별도 이슈가 필요하면 말씀주세요)
![스크린샷 2019-05-02 오후 4 26 14](https://user-images.githubusercontent.com/28773903/57061436-c3403e00-6cf7-11e9-9af4-8ecd64efc3e2.png)
1. No. 열 삭제
2. 이 부분은 해당 데이터소스가 연결된 워크북의 개수가 표시되는 것으로 기획되었었습니다. 그래서 레이블도 'used in'이 달렸던 것이고요. 하지만, 현재 큰 의미가 없는 듯하고 레이블 오류로 오해할 수 있어서 삭제하는 것이 좋을 것 같습니다. 해당 열 삭제 부탁드립니다.
3. 여러차례 기획 변경을 거치면서 정리가 덜 된 부분이 있습니다. (특히, '메타데이터'가 보이는 부분은 삭제되어야 합니다.) 다음과 같이 정리해 주시면 감사하겠습니다.
- Enabled : 데이터소스 이름, 설명, 타입, Publish, 생성일, 수정일, 사이즈, 로우수, 컬럼 리스트, 상세보기버튼
- Disabled : 데이터소스 이름, 설명, 타입, Publish, 생성일, 수정일 
---
@AnnieHwang 다른 의견있으시면 부탁드립니다-

**Comment by koeun222** [comment]
@AnnieHwang 위 기획수정에 맞춰 수정한 디자인화면 공유드립니다

Datasource - Enabled
![image](https://user-images.githubusercontent.com/42256760/57121773-91d97800-6db4-11e9-95f8-edd245d3ab55.png)

Datasource - Disabled
![image](https://user-images.githubusercontent.com/42256760/57121777-956cff00-6db4-11e9-9e84-e7723b11e157.png)
