### ISSUE TITLE
Server error on geographic data ingestion

### ISSUE THREAD

**Issue by danigamba** [metatron-app/metatron-discovery#1932]
**Describe the bug**
Server error ingesting a csv with points

Error:
```
message : INGESTION_ENGINE_ACCESS_ERROR 
cause : QueryTimeExcetpion: [{"error":"Instantiation of [simple type, class io.druid.data.input.Evaluation] value failed: function shape_centroid_YX is not defined. (through reference chain: java.util.ArrayList[0])"}]
```

The csv
```
Opportunity number;City;CAP;Business Type;Close Date;Stage;Quantity;CodiceFast;Descrizione;Product Category;Product Name;Tender number;StatusCorrente;Venditore;Equipment Number;Order Sales Price;Tender Target Price;Discount percentage;Order CMII percentage;ProductSales Price;Product CMII percentage;DataEsportazione;Latitude;Longitude;Point
1;SELARGIUS;9047;A;2007-12-27 15:45:35.913;A;1;A;A;A;A;A;A;A;A;1.00;1.00;1.00;1.00;1.00;1.00;2007-12-27 15:45:35.913;392.839.741;913.366.095.189.599;POINT (39.2839741 9.13366095189599)
1;SELARGIUS;9047;A;2007-12-27 15:45:35.913;A;1;A;A;A;A;A;A;A;A;1.00;1.00;1.00;1.00;1.00;1.00;2007-12-27 15:45:35.913;392.839.741;913.366.095.189.599;POINT (39.2839741 9.13366095189599)
```

**To Reproduce**

1. Datasources -> New -> My Files
2. Upload the attached csv
3. Set the separator as ';'
4. Set the close date as Date dimension and Point as Point type
5. Click confirm

**Screenshots**

![image](https://user-images.githubusercontent.com/19972961/56571103-8d46df80-65bc-11e9-9775-ebf35122b088.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: 73

**Additional context**
Installed and running geoserver with getty listening on 9090 and standard user/password/workspace.

**Comment by alchan-lee** [comment]
Hi @danigamba 

function `shape_centroid_YX` is added recently.
it seems like you only using the latest discovery but you need to upgrade druid version too.

Plesae download the latest version of druid from the link below.
[latest druid](https://sktmetatronkrsouthshared.blob.core.windows.net/metatron-public/discovery-dist/latest/druid-0.9.1-latest-hadoop-2.7.3-bin.tar.gz)

**Comment by alchan-lee** [comment]
One more thing: 
We have transferred the features we used in the geoserver to the Druid's extension.
So, you don't need to run a geo server anymore.

**Comment by danigamba** [comment]
Thank you, with the latest download it works flawlessly.
