### ISSUE TITLE
Improved UI performance when column content size is long on ingestion stage

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1940]
**Is your feature request related to a problem? Please describe.**
When the data source is loaded, if the content size in the column is long at the data preview stage, the browser may hang.

**Describe the solution you'd like**
If displaying long length content on the UI affects performance, it may need to be modified in such a way that the content is shown is short, and the actual content used in other business logic is stored in the internal object.

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by brandon-wonjune** [comment]
@kyungtaak 
데이터소스 생성 > 커넥션 선택 > 데이터베이스 및 테이블 선택화면의 아래에 나오는 미리보기 그리드 화면을 의미하는것인가요?

**Comment by kyungtaak** [comment]
@brandon-wonjune 아니요. 적재 단계 중 "Please select data", "Configure schema" 에서 문제가 되네요. 특히 "Configure Schema" 에서 상세 보는 화면에서요. 
validation 체크를 위해서는 원본을 넘겨야 해서.. 서버에서 줄여서 전달하기는 어려울것 같고요. ui 에서 처리를 해주시면 좋을것 같습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak @deidera08 
해당하는 화면인데요
데이터 컨텐츠의 길이를 제한을 둬야할것같습니다. 
어느정도(문자길이) 까지만 표기하는것으로 해야할까요?
![스크린샷 2019-04-24 오후 6 24 29](https://user-images.githubusercontent.com/42233627/56648504-6d97e000-66be-11e9-86b6-8a42bca1b409.png)
![스크린샷 2019-04-24 오후 6 25 43](https://user-images.githubusercontent.com/42233627/56648505-6e307680-66be-11e9-9fb7-c4bf92e07e52.png)

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang  @brandon-wonjune 
디자인 화면을 고려해야겠지만 더 짧아야 할 듯 합니다.
참고로 컬럼명은 50자정도로 제한하고 싶습니다.

**Comment by kyungtaak** [comment]
> 더불어 컬럼명은 50자정도로 제한하고 싶습니다.

@brandon-wonjune @kyungtaak 저도 괜찬을것 같습니다. ^^

**Comment by brandon-wonjune** [comment]
> > 더불어 컬럼명은 50자정도로 제한하고 싶습니다.
> 
> @brandon-wonjune @deidera08 저도 괜찬을것 같습니다. ^^

그러면 컬럼명, 컬럼데이터 길이를 모두 50자로 제한하도록 하겠습니다.
UI에서 표시만 50자로 나오도록 하겠습니다.
다만 configure화면에서 좌측 패널 (컬럼 목록)에도 적용되면 나중에 '컬럼 이름 변경'이슈 진행시 어떻게 표기할것인지 다시 고려해야될것같습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak 작업 후 테스트 중 문의드립니다.
해당 파일로 테스트를 하였습니다.
[TL_SCCO_CTPRVN.csv.zip](https://github.com/metatron-app/metatron-discovery/files/3116035/TL_SCCO_CTPRVN.csv.zip)
해당파일로 테스트시 브라우저가 중단되는 현상은 없었으나 ingestion이 실패합니다. 확인부탁드립니다.

**Comment by kyungtaak** [comment]
@brandon-wonjune 해당 파일에 geometry 가 문제가 있는것 같습니다. 이부분은 별도로 확인해볼 예정오니 pr 올려주시면 될것 같습니다.
