### ISSUE TITLE
'ingestion configuration' screen Change to new design

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#1950]
**Is your feature request related to a problem? Please describe.**
'ingestion configuration' screen Change to new design
![image](https://user-images.githubusercontent.com/6300003/56704212-3faaae00-6747-11e9-8867-d39b31e8e0f0.png)

**Comment by kyungtaak** [comment]
#1920 과 중복이슈로 이슈를 종료합니다.
