### ISSUE TITLE
Database search does not work on the Hive Connection Workbench.

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#1956]
**Describe the bug**
Hive 커넥션으로 생성한 워크벤치에서 데이터베이스 검색이 동작하지 않음.

**To Reproduce**
1. Hive 커넥션으로 워크벤치 생성
2. 좌측 측면에서 데이터베이스 목록 펼침 
3. 검색할 데이터베이스명 입력
4. 무엇을 입력해도 결과가 같음.

**Expected behavior**
입력한 값에 일치하는 데이터베이스 목록만 노출되어야 함.

**Screenshots**
![image](https://user-images.githubusercontent.com/16472109/56780032-a3e97280-6818-11e9-974c-5c430ac18785.png)

**Desktop (please complete the following information):**
 - OS: mac OS 
 - Browser : Chrome
 - Version : 73.0.3683.103

**Additional context**
3.2.1.1 릴리즈에서 재현됩니다.

**Comment by Taehui** [comment]
Schema Information 에서도 검색이 안되는 것 같습니다.
