### ISSUE TITLE
Errors that can not be entered into a workbook or workbench in I.E

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#1959]
**Describe the bug**
- After discovery 3.2.2.1  updating the version, when trying to enter workbook or workbench in IE, "loading chunk 18 failed" error occurred.

**To Reproduce**
1. Go to 'Workspace' in I.E.
2. Click on 'Any Workbook' or 'Any Workbench'
3. Error occurred.

**Comment by Taehui** [comment]
Hot fix 가 필요한 이슈 입니다.

**Comment by YooYoungmo** [comment]
discovery-frontend/src/app/page/chart-style/color-option.component.ts 의 isNumberRegex() 하고
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts 의 isNumberRegex() 때문에 나는 오류입니다.

임시적으로 StringUtil.isNumber 로 대체하니 오류는 나지 않네요.
