### ISSUE TITLE
Not working "MultiLineString" geometry

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1965]
**Describe the bug**
"MultiLineString" geometry does not work.

**To Reproduce**
1. Go to 'Datasource Management'
2. Create Datasource using this file ([world.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3124709/world.csv.txt)) (remove '.txt')
3. Move to the workbook in your workspace
4. Create dashboard using datasource you ingested
5. Create map chart widget  
6. See error

**Expected behavior**
"MultiLineString" geometry should be properly displayed on the map.

**Screenshots**
(N/A)

**Desktop (please complete the following information):**
Any environment

**Additional context**
- In the process of creating geojson, there is a problem that does not recognize "MultiLineString" and should be fixed together.
- "MultiLineString" geometry can be a polygon type. This part should also be considered when validating the geometry type in the ingestion step.

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho @brandon-wonjune I think we need to change this phrase.

![image](https://user-images.githubusercontent.com/822255/56860928-d3de7480-69d6-11e9-974b-65fe02aaf378.png)

**Comment by kyungtaak** [comment]
@eltriny Not displayed in map view. you need confirmation.

**Comment by minjung-cho** [comment]
> @AnnieHwang @minjung-cho @brandon-wonjune I think we need to change this phrase.
> 
> ![image](https://user-images.githubusercontent.com/822255/56860928-d3de7480-69d6-11e9-974b-65fe02aaf378.png)

현재 적용되어 있는 문구의 모호함과 별개로, 다른 개선 방향을 제안드립니다.

타입 콤보박스 선택과 동시에 모든 타입에 대한 valid 체크를 해서 변경 가능한 타입만 콤보박스 리스트에 남기는 것이 가능할까요? 그렇게 된다면 스크린샷에 보이는 에러 메시지를 보는 상황은 없을 것 같습니다.

스크린 샷과 같은 케이스에서 사용시나리오를 생각해 보면 아래와 같습니다.
1. latitude 컬럼 선택
2. Type 의 콤보박스 선택 
3. (Type 유효성 체크 진행) 필요시, 로딩 애니메이션 보임.
4. 콤보박스에 유효한 타입만 남음. (예 : string, Decimal, Date/Time, Latitude, Longitude 만 목록에 남음)
5. 필터링된 타입 중 사용자가 원하는 항목 선택


(eng.)
Apart from the ambiguity of the currently applied phrases, I suggest other improvements.

Is it possible to make a type validation check for all types at the same time as selecting a type combo box, and leave only the types that can be changed on the combo box list? If so, there will be no chance of seeing the error message shown in the screenshot.

Consider the usage scenarios in the case of screen shots, as shown below.
1. Select latitude column
2. Select the Type combo box
3. (Type validation check) Show loading animation if necessary.
4. Only valid types remain in the combo box. (For example, only string, Decimal, Date / Time, Latitude, Longitude)
5. Select the item you want from among the filtered types

**Comment by sting009** [comment]
@kyungtaak 
MultiLineString 타입 추가하였습니다. 아래 캡쳐화면과같이 나옵니다.
![image](https://user-images.githubusercontent.com/42328567/57285891-24e51b80-70ef-11e9-8b88-f6aa560101d8.png)
 다만 제쪽 로컬에서 확인시, bbox필터 범위가 넓을경우 (화면에서 봤을때는 최대로 축소하였을경우에만) 일부 좌표데이터 범위가 좀 다르게 내려오는것같습니다. 확인부탁드립니다. 

(eng)
Added MultiLineString type.
However, when checking from the local side, if the bbox filter range is wide (only when it is minimized when viewed from the screen), some data range seems to come down a little differently.

**Comment by kyungtaak** [comment]
> Apart from the ambiguity of the currently applied phrases, I suggest other improvements.
> 
> Is it possible to make a type validation check for all types at the same time as selecting a type combo box, and leave only the types that can be changed on the combo box list? If so, there will be no chance of seeing the error message shown in the screenshot.

@minjung-cho Your suggestion is very interesting. However, the system only guesses the data type of the column, and I think the choice is up to the user. It seems to be unreasonable to limit the type selection by the system. What do you think? And let's discuss this through internal channels. :)

**Comment by kyungtaak** [comment]
> owever, when checking from the local side, if the bbox filter range is wide (only when it is minimized when viewed from the screen), some data range seems to come down a little differently.

@sting009 I don't understand about "bbox filter range".  Can you explain in detail through the internal channels?

**Comment by sting009** [comment]
@kyungtaak Yes, talk about the internal channel.
