### ISSUE TITLE
Error on replace rule

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1972]
**Describe the bug**
Replace does not work as expected.

**To Reproduce**
1. Import & wrangle [for_sql.txt](https://github.com/metatron-app/metatron-discovery/files/3126716/for_sql.txt)
2. Click on context menu of fltr_uid column
3. Select edit - replace
4. Put /(.*)/ into pattern, put \'$1\' into new value
![스크린샷 2019-04-29 오후 6 29 10](https://user-images.githubusercontent.com/42257727/56887570-ef1bb380-6aac-11e9-840b-97311b58c8ad.png)

5. See unwanted quotes.
![스크린샷 2019-04-29 오후 6 29 21](https://user-images.githubusercontent.com/42257727/56887579-f93db200-6aac-11e9-8471-bcc3717dcd41.png)

**Expected behavior**
Wraped by one single quotes

**Comment by ksparknot** [comment]
@joohokim1 

I just found out this
on java regex, replaceAll with (.*) has 2 groups
.* in bracket -> $1 is first 
and empty character out of bracket is second
so that is right result.
'$1''(empty string)'

replaceAll with ^(.*)$ should have only 1 group

**Comment by joohokim1** [comment]
@ksparknot 
Then how can I get "Expected behavior" with metatron?

**Comment by ksparknot** [comment]
Try ^(.*)? instead of (.*)

**Comment by ksparknot** [comment]
> @ksparknot
> Then how can I get "Expected behavior" with metatron?

Try ^(.)? instead of (.)

**Comment by joohokim1** [comment]
<img width="1337" alt="스크린샷 2019-11-13 오후 2 46 58" src="https://user-images.githubusercontent.com/42257727/68736623-79c89800-0624-11ea-9890-a346b13f6f1d.png">

@ksparknot Yes, it works. Thank you.
