### ISSUE TITLE
Snapshot as an SQL script

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#1976]
**Is your feature request related to a problem? Please describe.**
I'm trying to generate SQL insert statement using a CSV snapshot.
It's tiring to merge with comma, put "INSERT INTO _<table_name>_ VALUES (",  remove double-quotes, etc.
Moreover, if the columns' order do not match with the database schema... it's too hard work.

**Describe the solution you'd like**
If there's something like SQL script type snapshot, it'll be very convenient in this situation.

**Additional context**
We need an input form for the table name in snapshot generating pop-up.
All works can be done assuming all columns are just string. (Or we can force it.)

**Comment by AnnieHwang** [comment]
@eldorado0402 @joohokim1 아래 내용 확인 부탁드려요~ (오렌지색과 빨간색 보시면 되요)

- 화면1. 스냅샷 생성 시 팝업
![image](https://user-images.githubusercontent.com/6300003/58525887-4aee6f00-8208-11e9-872f-62de0f9dd435.png)

- 화면2. 스냅샷 상세 팝업
![image](https://user-images.githubusercontent.com/6300003/58525896-504bb980-8208-11e9-9ccf-f7633998f1a8.png)

- 화면3. 스냅샷 목록 (말씀 안하신 부분인데..원천정보 표현 부분에 SQL이라고 기술해야 할까요?)
![image](https://user-images.githubusercontent.com/6300003/58526119-ee3f8400-8208-11e9-9fcf-75b7f11416ea.png)

**Comment by eldorado0402** [comment]
@AnnieHwang 님 화면2에  8번 항목에 "데이터 소스 생성" 버튼은 disable 처리 해야 할 것 같습니다. sql 문으로 데이터 소스 생성 연결이 불가 합니다. 화면3은 말씀하신 3가지 종류만 존재합니다.
