### ISSUE TITLE
CSS is broken(2)

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1977]
**Bug&Screenshot**

14.[IE/Chrome]
![image (50)](https://user-images.githubusercontent.com/28773903/56937477-db695f00-6b37-11e9-86ba-239f9b235ab3.png)

15.[IE]
![image (52)](https://user-images.githubusercontent.com/28773903/56937517-1075b180-6b38-11e9-9eed-53f40e452eb6.png)

16.[IE]
![tooltip](https://user-images.githubusercontent.com/28773903/56937530-21262780-6b38-11e9-9a9c-0dbddfe53adb.png)

17. [IE] 잡로그 상세
![image (53)](https://user-images.githubusercontent.com/28773903/56937553-4024b980-6b38-11e9-93c2-bc3969b836cf.png)

18.[IE]
![image (54)](https://user-images.githubusercontent.com/28773903/56937568-4f0b6c00-6b38-11e9-8913-b88f2e24d425.png)

19.[IE] 로그 통계 화면에서 더보기 클릭 -> 팝업에서 이름이 길면 깜박거림 현상
![image (55)](https://user-images.githubusercontent.com/28773903/56937579-664a5980-6b38-11e9-8aa7-6fea70d01be9.png)

20.[IE/Chrome] 대시보드 계산식 컬럼 팝업 > 컬럼 타입 아이콘이 표시되지 않는 경우가 있음
![user_define_2](https://user-images.githubusercontent.com/28773903/56937675-01dbca00-6b39-11e9-8330-94ee96dcd52d.PNG)

21.[IE/Chrome]  대시보드드>데이터소스 패널. 세로 영역이 좁을 경우, 스크롤 필요(차트 화면 참고)
![column-list](https://user-images.githubusercontent.com/28773903/56937696-191ab780-6b39-11e9-96b8-a1d34f96f358.PNG)

(Writing...)

**Desktop (please complete the following information):**
 - Browser : Chrome/IE10

**Comment by minjung-cho** [comment]
@AnnieHwang 
14. 한글일때 '홈페이지'라는 번역이 잘못된 것 같습니다.
아래와 같이 변경하는게 어떨까요-

(한) 사용 가이드 : 다운로드 / 온라인
(영) User guide : Download / Online

**Comment by kyungtaak** [comment]
> 14. 한글일때 '홈페이지'라는 번역이 잘못된 것 같습니다.
> 아래와 같이 변경하는게 어떨까요-

@minjung-cho 해당 의견에 동감합니다만.. 일단 위의 이슈를 해결하고 별도 이슈로 처리했으면 합니다. "연락처.." 이런건..;;ㅠ.ㅠ  애매해요.;;

**Comment by minjung-cho** [comment]
@kyungtaak #1996 문구 이슈를 하나 땄습니다. '연락처'는 고민이 좀 되네요 ^^;
