### ISSUE TITLE
"Ingest periodically" is not working properly

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#1978]
**Describe the bug**
"Ingest once" was successfully processed when creating a datasource in the database, but "Ingest periodically" failed.

message : INGESTION_JDBC_QUERY_EXECUTION_ERROR
cause : JdbcDataConnectionException: Fail to query : Error while compiling statement: FAILED: SemanticException [Error 10004]: Line 1:566 Invalid table alias or column reference ‘sch_index_query_top_daily’: (possible column names are: query, search_type, search_type_info, qc, cc, ranking, max_result_cnt, yqc, yranking, fluctuation, rank_day, part_day)

**To Reproduce**
1. Go to the 4th step of create datasource(DB)
2. Click on 'Ingest periodically'
3. Set the granularity equal to the partition period
4. Click on 'Next;
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ufoscw** [comment]
@jeongeunkwon 
please tell me additional information.
(DB type, Query statement...)
