### ISSUE TITLE
Improve phrase and event in Connection info. view

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#1990]
**Is your feature request related to a problem? Please describe.**
- If your PC has a low resolution and you clicked the "Next" button as shown in the screen below, it will not proceed to the next step. This is because I did not check the connection like the next capture screen. If you do not confirm your connection, when you click Next, it looks like we need to adjust the scrolling.
_해상도가 낮은 PC 의 경우, 아래의 상황에서 “다음” 버튼을 누르면 넘어가지지 않습니다. 왜냐면 그 다음 캡춰 화면 처럼 연결을 체크하지 않았기 때문입니다. 이부분은 다른 사용자도 격을 고초(?) 같은데요. 다음을 누를때 연결 체크가 되지 않으면, 스크롤을 아래로 내려준다든지.. 하는 약간은 조정도 필요해 보이는데요_
![image](https://user-images.githubusercontent.com/822255/57057110-b7e21800-6ce1-11e9-8406-65b387abf297.png)
![image](https://user-images.githubusercontent.com/822255/57057111-bc0e3580-6ce1-11e9-8fb2-27eaceb58a07.png)

- The term "security"/"보안" does not seem to make sense.
ex. Account Type, Access Method

- The text below seems to require changes. for example "If you use this connection method, you can not select Batch type." 
_아래 문구는 변경이 필요해 보입니다. 예를 들면  "이 연결 방식으로 사용할 경우 Batch 방식에 적재를 선택할수 없습니다." 처럼요._
![image](https://user-images.githubusercontent.com/822255/57057165-df38e500-6ce1-11e9-9754-3abcc4a1b627.png)

**Describe the solution you'd like**
Already mentioned above.

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by AnnieHwang** [comment]
@kyungtaak @minjung-cho 
1. As far as I can see, when the browser height is below 850px, it seems that the bottom is not visible. However, if you change the design to a different resolution, you usually get the design based on the width. Therefore, the design through fixing the height seems to need anxiety.
Scrolling down to the bottom seems to reduce usability. I'd rather specify a required value for the input field.
해상도의 따른 디자인 변형은 보통 높이값이 고정이 아니라 너비값이 고정일 때 하는 경우가 많습니다. 이 경우 너비가 아닌 높이가 850px 이하의 경우가 해당됨으로 디자인을 전체적으로 바꿔야 하지 않을 까 생각됩니다.
스크롤을 하단으로 내리는 것은 오히려 사용성을 떨어트릴것 같아서.. 가장 빠른 대안은 필수값 지정을 통한 노티, 경고 등이 적당할 것 같습니다.

2. I think  'Access Method' / '접속권한' is better than 'Security'/'보안'.
3. I agree with you. ("If you use this connection method, you can not select Batch type."/"이 연결 방식으로 사용할 경우 Batch 방식에 적재를 선택할수 없습니다." )

**Comment by brandon-wonjune** [comment]
@AnnieHwang 
문구 수정하였습니다.
invalid connection인 경우 아래와 같은 룰에 따라 스크롤이 이동하도록 수정하였습니다.
- check connection 버튼을 누르지않고 next 또는 done을 누른경우 스크롤이 check connection 으로 이동
- invalid connection 인 상태에서 next 또는 done을 누른경우 스크롤이 check connection 으로 이동
- connection input을 입력하지 않은채 check connection 을 누른경우 스크롤이 해당 input으로 이동
- property가 있는경우 (데이터커넥션 생성 및 수정), property의 key가 없거나 잘못된 key를 입력한경우 스크롤이 property 목록으로 이동

**Comment by minjung-cho** [comment]
@brandon-wonjune If possible, apply the same to similar screens.
