### ISSUE TITLE
Some unnatural Korean translations

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#1996]
**Problems**
There are somewhat unnatural Korean translations at the bottom of the LNB.

**Solution**
(Kor.) 사용 가이드 : 다운로드 / 온라인
(Eng.) User guide : Download / Online
(Kor.) 문의
(Eng.) Contact

**Expected behavior**
People using Korean should not have any objection to using the service in Korean.

**Screenshots**
<img width="272" alt="스크린샷 2019-05-02 오후 11 18 50" src="https://user-images.githubusercontent.com/28773903/57082330-7bd6a380-6d31-11e9-9efc-c4c58d67a6e9.png">

**Desktop (please complete the following information):**

**Additional context**
#1977

**Comment by minjung-cho** [comment]
@deidera08 @AnnieHwang 
Someone said 'contact' was awkward. Do you have any better ideas?

**Comment by AnnieHwang** [comment]
@minjung-cho How about '문의'?
