### ISSUE TITLE
Improved chart y axis properties

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#2]
**Is your feature request related to a problem? Please describe.**
- 기존 "auto scale" 용어가 혼란스러우며, 동작이 제대로 되지 않은 문제가 있습니다.  
- 축교자점과 축 스케일 설정간 사용자 액션에 대해 명확하지 않은 부분이 있어 재검토가 필요합니다.

**Describe the solution you'd like**
- "auto scale" 용어 fmf '데이터 범위로 축 고정 (Fit to Data Scale)'로 변경, 이에 따른 차트 동작 재 검토
- 배타적인 3가지(축범위 설정, 교차점, 로그 스케일) 옵션에 대한 동작 UX 재검토
: 축 교자첨 설정은 기본값이 '0'이며, 별도 ON/OFF UI없이 사용자가 값을 입력하면 '설정 활성화' + '값 입력'이 동시에 처리되는 형태 (task의 사용 depth를 줄이려는 취지)
: 배타적으로 동작한다는 UX를 명확하게 전달하기 위해서 ON/OFF 옵션 추가 (하나의 옵션이 활성화 시, 나머지 2개의 옵션은 비활성화 처리)

**Describe alternatives you've considered**
- Line/Bar/Scatter/Combine Chart 적용 검토 

**Additional context**

**Comment by judy-exntu** [comment]
@kyungtaak f#2-improve_yaxis_properties 브랜치 생성하였습니다.

**Comment by judy-exntu** [comment]
@kyungtaak 
- auto scale용어 변경하였습니다.
- 축범위 설정, 교차점 ui 변경하였습니다.
- log scale의 경우 미개발된 사항이므로 완료후 같이 적용하겠습니다.

**Comment by esezin** [comment]
@judy-exntu 
- '축 교차점' 레이블이 '축 교차점 설정'으로 변경되어야 합니다.
- '축 교차점'의 ON/OFF는 축 교차점의 설정을 사용/사용하지 않음을 선택하는 개념이기 때문에, 만약 값을 변경한 후, OFF를 선택하면(즉, 교차점 설정을 하지 않겠다면) 기본값인 '0'으로 변경되면서 OFF되는 것이 옳은 동작입니다.
- 축 범위 설정 >데이터 범위로 축 고정 사용 시, 최댓값/최솟값 입력창은 비활성화 되어야 합니다.
- 최댓값 입력 이후, 삭제해도 값이 그대로 남아 있는 bug가 있습니다.

**Comment by esezin** [comment]
@judy-exntu 
- 축 범위 설정의 MIN, MAX 초기값을 불러올 수 있는 방법이 없다면, 초기값의 텍스트 필드를 비워 놓는 형태로 진행 부탁드립니다.
- 데이터 증감을 고려한 시나리오는 삭제합니다.

@kyungtaak 
- 라인 차트에서 MIN, MAX 변경시 발생한 이슈는 내부적으로 좀 더 살펴본 결과, 원래의 기획의도대로 처리 가능할 것으로 보입니다. (중간에 라인이 끊기는 형태가 아닌, 라인의 첨단이 가려지는 형태)
- 시간은 조금 소요될 것으로 보입니다만, 차주 초에는 적용 가능할 것으로 생각합니다.

**Comment by esezin** [comment]
@DAVE-EXNTU @judy-exntu 
금일 스프린트 회의에서 논의된 내용을 아래와 같이 정리합니다.

1. ‘Fit to data scale’의 레이아웃 행 간격을 MIN, MAX와 동일하게 조정 (현재 간격이 너무 좁음)
2. MIN / MAX의 최초 값으로 ‘데이터의 min,max 값’을 다시 넣는 것으로
3. Fit to data scale에 echart 스케일 옵션 적용
4. 레이블 변경 : Set Axis Range —> Set Axis Scale

그외의 UX issue(아래)는 PMS에 별도로 이슈를 생성하여 진행하겠습니다.
1. ‘Fit to data scale’과 ‘MIN/MAX 입력’간 우선순위 조정 
2. Set Axis scale을 ON하면, 바로 어떠한 변경이 생기는 것이 좋겠음 (Fit to data scale을 기본 체크로 적용하면 어떨지?)
3. MIN/MAX에 대한 범위 조절 등 다른 UI 고려

**Comment by kyungtaak** [comment]
@esezin @judy-exntu 위의 코멘트에 피드백드립니다. 
- 포커스 관련 내용이 빠진것 같습니다. (이건은 전체 적용이 필요한가요?)
- 2번은 바로 적용해도 좋을것 같은데요. 검토 부탁드립니다.
- #30 PR 이슈에 오류 리포팅 드린 내용도 확인 부탁드립니다.

**Comment by DAVE-EXNTU** [comment]
@kyungtaak 
Min / Max Placeholder의 수치를 아래와 같이 적용하고 있던 부분을 제거하였습니다.
계산식 : ( min - ( max - min ) * 0.05 )

@esezin 
MIN/MAX의 초기입력 상태에서, 숫자가 아닌 일반 문자 입력 시, '0'으로 반환됨 => 처리하였습니다.
