### ISSUE TITLE
Fail to download original data

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#20]
**Describe the bug**
원본데이터(차트/데이터소스 보기내) 다운로드 수행시 다운로드가 되지 않고 로딩이미지만 발생합니다. 

**To Reproduce**
1. 워크북 + 대시보드 생성후, 임의의 차트 위젯을 생성하고, 대시보드를 구성합니다. 
2. 대시보드 열람 모드내 차트 위젯 마우스 오버시 나타나는 상단 메뉴중 "Save data table" 아이콘 클릭
3. 지속적인 로딩이미지가 생성됩니다.

**Expected behavior**
- 오류가 발생시 로딩이미지가 지속적으로 표시되는게 아닌 에러 메시지가 나타나야 합니니다.
- 데이터가 정상적으로 다운로드 됩니다. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
@eltriny  f#20-fila_to_download_data 브렌치내 오류사항에 대해 수정하였습니다. 
추가로 2가지 확인사항 점검이 필요합니다.
- 오류가 발생시 로딩이미지가 지속적으로 표시되는게 아닌 에러 메시지가 나타나는 부분 
- 다운로드 클릭시 나타나는 레이아웃 위치조정 필요
  : 차트위젯 레이아웃의 경우 다른 헤더 아이콘을 클릭시 다운로드 레이아웃이 밀리는 현상
  : 데이터 소스 데이터 확인시 다운로드 레이아웃의 경우 밖으로 벗어나 있는 현상

**Comment by eltriny** [comment]
@kyungtaak 
아래의 API에 대해서 확인 부탁드립니다.
/widgets/{widgetId}/download

멀티데이터소스 환경에서 호출하였을 경우 아래와 같은 오류가 발생합니다.
![1](https://user-images.githubusercontent.com/3685833/44135368-bdb1f95e-a0a3-11e8-95bc-b99e881949a1.png)
![2](https://user-images.githubusercontent.com/3685833/44135369-bddc91e6-a0a3-11e8-92ee-50d3ad558c1d.png)
![3](https://user-images.githubusercontent.com/3685833/44135370-be0598c0-a0a3-11e8-91d0-42a3aa037790.png)

**Comment by kyungtaak** [comment]
@eltriny api 오류는 수정완료하였습니다.

**Comment by kyungtaak** [comment]
@eltriny  filter spec 내 dataSource 속성처리 변경 및 user-defined field 내 dataSource 속성도 추가하였으니 적용 검토 부탁드립니다.
