### ISSUE TITLE
How to mark specific regions in specified colour in metatron-discovery dashboard map

### ISSUE THREAD

**Issue by kaviranga** [metatron-app/metatron-discovery#2001]
When creating dashboard for specific map how we mark regions like states,boundaries in appropriate color. Is there any need to define it in CSV file before import it as data source for the dashboard ?

**Comment by kyungtaak** [comment]
@kaviranga There are two ways.
As you mentioned, there is a way to put additional columns along with the geometry column in the CSV. It will be possible to display the color through the Dimension / Measure value in the boundary area as below. (Make sure to place the columns in the layer that you want to display in color.)

![image](https://user-images.githubusercontent.com/822255/57220975-4afbb480-7038-11e9-9bfe-1d65ad810c1a.png)
![image](https://user-images.githubusercontent.com/822255/57220951-2e5f7c80-7038-11e9-9d43-a20991ece677.png)

The other way is to operate through two layers. I would like to refer to the following link.
(https://metatron.app/2019/05/02/building-a-simple-map-view/)

I don't know if it was the right answer to your question. Please let me know if you have any further questions. :)

**Comment by kaviranga** [comment]
@kyungtaak, Thanks for the quick reply
This is the on option th

**Comment by kaviranga** [comment]
@kyungtaak This the one method that I wanted
I have tested with this example [Analyzing geospatial data with Metatron Discovery](https://metatron.app/2019/03/20/analyzing-geospatial-data-with-metatron-discovery/) . So I've got the below result with that 
![Screenshot_2019-05-09_16-32-42](https://user-images.githubusercontent.com/6471174/57687471-1e0f5900-7659-11e9-8002-9460364c15d6.png)
 
I have do some corrections to the csv files that are not met with driud. The corrections to the csv files are, remove if there are blank columns in the start of the csv and the unnecessary columns that we won't need .(Sometimes these unnecessary columns and blank rows cause errors when ingesting the data).

**Comment by kaviranga** [comment]
@kyungtaak Thank for the quick reply :+1:   I've got this result using two map layers.
