### ISSUE TITLE
Improve UX for function selection area on user-defined field view

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2008]
**Is your feature request related to a problem? Please describe.**
We want to improve the calculation field definition popup UX. (Especially, function selection area) We need markup and CSS work.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/6300003/57270878-15061100-70c8-11e9-8804-8258faace1f3.png)
[계산식필드#2008.pptx](https://github.com/metatron-app/metatron-discovery/files/3150758/2008.pptx)

**Comment by deidera08** [comment]
@AnnieHwang @kyungtaak 
이 이슈에 다음 개선이 함께 이뤄지면 좋을듯 합니다.

1_ 상단 오류 문구는 Invalid 상태일때만 노출되어야 합니다.
2_ 컬럼목록의 아이콘이 잘못 표현되고 있습니다.
3_ 검색시 검색어가 함수 목록에 영향을 미쳐야 합니다.
(논의끝에 검색영역과 함수 셀렉트박스의 위치는 바꾸지 않고 현행을 유지하기로 하였습니다)
![스크린샷 2019-05-14 오후 5 01 12](https://user-images.githubusercontent.com/42257766/57681701-312b2480-766b-11e9-9527-b2c566ebd024.png)

**Comment by deidera08** [comment]
@AnnieHwang @kyungtaak @koeun222 
검색시 하위 '펑션 카테고리' 선택과 목록에 대한 디펜던시 표현이 약한것 같아 레이아웃 일부를 수정하였습니다.
기능상으로 볼때 '펑션 카테고리'와 검색이 모두 필터링이기 때문에 상단으로 배치하고
하단에는 목록과 그에 따른 설명으로 노출되면 좋을듯 합니다.
![스크린샷 2019-05-15 오후 3 37 37](https://user-images.githubusercontent.com/42257766/57753559-6e54ec80-7727-11e9-9e0f-1f3cfeb000b0.png)

**Comment by koeun222** [comment]
@AnnieHwang  디자인 수정된 화면 공유드립니다 
초기상태
![image](https://user-images.githubusercontent.com/42256760/57757448-71080f80-7730-11e9-9fc3-deebdebbe695.png)

function 항목 선택 시 
![image](https://user-images.githubusercontent.com/42256760/57757470-811fef00-7730-11e9-8229-78ebcf08fb19.png)
