### ISSUE TITLE
Error in incorrect screen change from 'Configure the schema' popup in data source detail screen

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#201]
**Describe the bug**
데이터소스 사용성 개선 작업에는 Re-ingestion을 고려하여 컬럼의 타입 변경 씬이 교체되었습니다. 하지만 현재 Re-ingestion기능 개발이 늦춰지면서.. 현재 레이블 및 표현의 오류가 있는 부분이 있어서 화면 수정을 하려고 합니다.

**To Reproduce**
1. Go to 'Mangement' > 'Datasource' > (detail) > 'column details' > 'Configure the schema' pop-up

**Expected behavior**
하단 스크린샷을 참고 부탁드립니다.
1. Name 레이블 => 'Physical column name' 
2. Logical name, description => 삭제
3. Logical type => Physical type 

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/45476962-559ccd00-b77b-11e8-94ff-ed45772d26a7.png)

**Comment by minjung-cho** [comment]
참고 : Re-Ingestion 기획 이슈 METATRON-1150

**Comment by minjung-cho** [comment]
@AnnieHwang @brandon-wonjune 추가로, Role --> Physical role 로 변경 부탁드립니다!

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho 이건 Re-Ingestion 할때 함께 진행했으면 하는데요. 
그리고 logicalType 은 메타데이터 에서만, 수정가능한가요?

**Comment by kyungtaak** [comment]
@minjung-cho 물리타입은 바꿀수 없습니다. 그리고 datasource 내에서도 logicalType 이 존재해요.

**Comment by minjung-cho** [comment]
@kyungtaak 용어에서 혼선이 있는것 같습니다. MDM 기능 들어오면서 화면에서 사용하는 '논리타입' 용어를 메타데이터상의 컬럼 타입(우편번호 등이 포함된...)으로 정의되었다고 들었습니다. @AnnieHwang 저도 좀 헷갈려서 어제 충의님께 확인하긴 했습니다만... 제가 이해하고 있는게 맞나요?

**Comment by AnnieHwang** [comment]
@kyungtaak @minjung-cho 용어가 혼재되어 있는 것 같은데.. 저희는 현재 화면에서 아래와 같은 용어로 정의하였습니다. 

1.Engine : 실제 물리데이터 (Druid 내 물리테이블) 
- Engine Name : 실제 물리데이터의 테이블명
- Engine Column Name : 실제 물리데이터의 컬럼 이름
- Engine Column Type : 실제 물리데이터의 컬럼 타입

2. Physical : 실제 물리데이터를 Metatron 내에서 잘 설명하기 위한 논리데이터 (데이터소스)
- Physical Name : 데이터소스 명
- Physical Column Name : 데이터소스 내 컬럼 이름
- Physical Column Type : 데이터소스 내 컬럼 타입

3. Logical : Metatron 내 물리데이터인 데이터소스를 잘 설명하기 위한 논리데이터 (Meta Data)
- Logical Name : 메타데이터명
- Logical Column Name : 메타데이터 컬럼 이름
- Logical Column Type : 메타데이터 컬럼 타입

위와 같이 정의한 이유는, 
. 기존에 Engine 데이터가 Metatron화면에 노출되어 있지 않았으며,
. 데이터소스 명은 기존에 마치 물리데이터 처럼 쓰여지고 있기 떄문입니다.

따라서, 해당 화면이 Re-Ingestion 할때 함께 진행하면 안되는 이유는, MDM화면이 만들어지기 전에 임시적으로 만든 화면이라 Logical 이라는 용어가 섞여있고(논리데이터는 Meta Data 메뉴에서만 확인 가능하여야 합니다. 왜냐면 데이터소스가 있다고 해서 Logical이 있는게 아니기 때문입니다)

만약 진짜 물리타입을 기재하려고 하시는 거면 'Engine Column Type'이라는 용어로 사용하여 저 자리에 Read-Only로 표현해야 할 것 같습니다. 저는 나와도 될것 같은데.. 기존에 숨겨둬서 표현을 하지 않았었습니다. 만약 필요하시다고 생각하시면 다시 화면 구성을 레이블 변경 위주로 바꾸도록 하겠습니다. (하지만 완전 개편은 Re-ingestion때 하도록 하겠습니다)

**Comment by minjung-cho** [comment]
> @kyungtaak 네, 그런데 이 팝업이 없으면 물리타입 변경 기능이 사라지게 되더라고요

이 화면 고도화가 진행되고 있는 것 확인했습니다. 미처 캐치를 못했습니다 ^^; 상세화면에서 바로 물리타입 변경이 가능합니다.

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang @minjung-cho 
이 이슈는 어떻게 결론을 내리면 좋을까요?

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang 이건은 메타데이터 개선안에 포함되어 있나요?

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 

다음과 같이 계획하고 있습니다.
1. Datasource 생성시 해당 데이터는 Metadata에 자동등록됩니다.
2. Datasource에 이름, 논리컬럼명, 타입, 설명 정의하는 부분은 기존과 같이 유지합니다.
3. Metadata 또한 이름, 논리컬럼명, 타입, 설명을 작성/수정할 수 있습니다.
4. Datasource의 데이터는 Metadata에 동일한 데이터가 존재하므로 이름, 논리컬럼명, 타입, 설명이 같습니다.
즉 한쪽에서 작성/수정할 경우 다른 한쪽에도 동반적용됩니다.
5. Physical이라는 용어를 UI상에서 가급적 사용 안하려 합니다. 때문에 라벨명이 다음과 같이 수정됩니다.
- Physical/Logical Role > Role
- Physical (Column) Name > (Column) Name
- Logical (Column) Name :유지. 쿼리나 계산식에서는 여전히  Physical Column Name을 쓰기때문에 컬럼이름은 분리하였습니다.
- Physical /Logiacl Type > Type
- Format : 유지. type에 우편번호나 전화번호와 같은 타입을 계획하고 있는데, 이 때 표현 형식을 이 영역에 노출하고자 합니다.
- Physical /Logiacl Description > Description
![201configureschema](https://user-images.githubusercontent.com/42257766/49978321-42bdb280-ff8d-11e8-93d8-3f32fcc7f51f.png)

**Comment by kyungtaak** [comment]
@deidera08 답변 감사합니다. 해당 이슈는 종료하고 위의 언급해주신 기획서를 바탕으로 이슈를 등록하도록 하겠습니다.
