### ISSUE TITLE
Need a submit button to time filter in dashboard

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#2036]
**Is your feature request related to a problem? Please describe.**
대시보드 화면에서 시간필터 사용시 from ~ to 시간 필터값을 지정해야 하며 한쪽의 필터값만 지정해도 그 즉시 차트에 반영됩니다.
편의를 위해 즉각반영되도록 설정한 UX였습니다만, 데이터가 클 경우 이는 오히려 불편을 야기합니다.
데이터가 클 경우 차트에 반영되는 시간에 로딩이 길 뿐 더러 브라우저가 멈추는 현상도 종종 발생합니다.

**Describe the solution you'd like**
사용자가 시간 필터값을 실수로 설정하거나 임의의 필터값을 즉흥적으로 설정하는것을 방지하기 위해 설정버튼을 두면 어떨까 합니다.
from ~ to 시간을 지정 후 [OK]버튼을 눌러야 차트에 반영되면 좋을듯 합니다.
![스크린샷 2019-05-10 오전 10 40 49](https://user-images.githubusercontent.com/42257766/57497009-ca2b0a00-7310-11e9-8607-d212253974e1.png)

**Comment by Taehui** [comment]
이 이슈와 상관없는 요청일 수 있는데, 시간 필터에서 날짜까지만 표현하거나, 시간까지만 표현하는 등의 포맷을 지정할 수 있었으면 좋겠습니다.

**Comment by deidera08** [comment]
@Taehui 
코멘트주신 내용은 기획 고민중이긴 합니다. 정리가 되는대로 이슈로 등록하도록 하겠습니다 :)
