### ISSUE TITLE
Information on Datasource's detail page is different to each other

### ISSUE THREAD

**Issue by 9bow** [metatron-app/metatron-discovery#204]
**Describe the bug**
(Datasource 생성 방법에 따라) Datasource의 Information Tab에 보이는 정보가 서로 다릅니다.

**To Reproduce**
1. 동일한 Hive Table에 대한 Datasource를 Ingested Data와 Linked Data로 각각 생성합니다.
2. 생성한 Datasource의 Information Tab 중, Ingestion information 섹션을 확인합니다.
3. Master data의 표시 내용(Host/Port/JDBC URL 존재 유무), 각 필드명의 **두께**가 상이합니다.

**Expected behavior**
모든 정보가 표시되어야 하며, 필드명 또한 일관되어야 합니다.

**Screenshots**
![screen shot 2018-09-13 at 21 14 40](https://user-images.githubusercontent.com/9343724/45487791-509b4600-b79a-11e8-9934-aac0a78cb0c7.png)
![screen shot 2018-09-13 at 21 14 53](https://user-images.githubusercontent.com/9343724/45487752-3a8d8580-b79a-11e8-916b-d2a9ecdfdc95.png)
![screen shot 2018-09-13 at 21 15 08](https://user-images.githubusercontent.com/9343724/45487755-3b261c00-b79a-11e8-9f14-858035925c86.png)

**Desktop (please complete the following information):**
[N/A]

**Additional context**
위 1번과 3번 스크린샷은 동일한 Table을 Ingested data로 가져온 것입니다. 재현을 위해 테스트를 진행하다보니 1번 스크린샷과 같은 형태로 보이지 않고 2,3번 스크린샷과 같은 형태로만 보이고 있어 추가적인 확인이 필요합니다.

**Comment by brandon-wonjune** [comment]
@9bow 
Linked 소스인경우 Ingested와 달리  monitoring tab이 제거되었습니다. (#155 )
Column details tab의 경우 요청사항에 의해 LInked는 제거된 상태였으나 #9 에서 변경된 건에대해 적용될 예정입니다.
#9 가 적용되면 다음과 같이 표시됩니다.
Ingested - information / data / column details / monitoring
Linked - information / data / column details

Master data의 필드명의 두께가 상이한건 수정하겠습니다.

**Comment by brandon-wonjune** [comment]
해당이슈는 연결형 데이터소스에 대해 변경건이 있어 #9 이슈의 브랜치에서 같이 작업하도록 하겠습니다
