### ISSUE TITLE
"count" does not work properly in datasource with geo type column

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#2044]
**Describe the bug**
Custom column "count" does not work properly in datasource with geo type column

**To Reproduce**
1. Select a datasource with geo type column to create a chart
2. Create custom column "count"
3. Create bar chart using the "count" column

**Expected behavior**

**Screenshots**
![스크린샷 2019-05-10 오후 6 49 03](https://user-images.githubusercontent.com/44457771/57518609-60345400-7354-11e9-9b05-0625a1b2ec58.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
Originally, the "count" column is a reserved word internally, designed to be unavailable to the user.
How about using the "countof" column? Through this issue(#1941), you'll be able to use the count column. This issue will be included in the 3.3 minor releases.
