### ISSUE TITLE
Users should be able to search for hidden value in filter widget

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#2045]
**Is your feature request related to a problem? Please describe.**
차트 필터는 항목의 수가 제한되어 있을뿐 더러 관리자가 개별 항목 노출을 제어할 수 있습니다.
그러나 일반 사용자는 그 노출여부를 알 수 없을뿐 더러 특정 항목에 대한 필터링을 하고싶은 니즈가 있습니다.

**Describe the solution you'd like**
기본적으로 관리자가 설정한 항목 노출 설정에 따라 필터목록이 나옵니다.
그러나 사용자가 특정값에 대하여 명확한 검색을 할 경우 그 항목이 'Hide' 되어 있더라도 필터로 사용할 수 있었으면 좋겠습니다.

![스크린샷 2019-05-10 오후 7 03 40](https://user-images.githubusercontent.com/42257766/57519498-64617100-7356-11e9-93ab-c434d5664cdd.png)

사용자가 필터 항목 검색시 확장검색을 할 경우 숨겨진 상태라도 결과에 노출되며, 해당 항목은 자동으로 필터목록에 추가됩니다.
그러나 임시필터이므로 해당 대시보드에 저장하지 않으며, 근본적으로 'Hide'상태를 'Show'상태로 변경할 수는 없습니다.

살펴보시고 부족한 부분이나 보완할 점이 있다면 가이드 부탁드립니다.

**Comment by Taehui** [comment]
전체 검색 버튼이 들어오는 경우와 상관없이, 현재에도 발생하는 추가적인 문제점에 대한 의견입니다.
1. All 버튼으로 인해 발생하는 문제 
 - 차트 구성하는 Manager 가 특정 Dimension 의 Value 한개를 선택해서 Line Chart 를 그립니다. 
 - 시간단위 데이터를 최근 2주로 그렸을 때, 14(일)*24(시간) 개의 점을 라인으로 그립니다. (브라우저 먹통 안됨)
 - 위 콤보 리스트에는 1000 개의 리스트가 있으며, All 클릭 하는 순간, 14*24*1000 개를 그리려고 하다가 힘들어 합니다. (브라우저 죽음)
 --> All 이라는 표현도 오해의 소지가 큽니다. 실제 cardinality 는 훨씬 큰데 그중에 1000개만 표현되고 있다는 것을 사용자가 인지할 수 있는 방법이 없어보입니다.

2. City 로 표현되어있는 위 필터위젯에서 5개가 Check 되어 있다고 가정할 때, 체크되어 있는 5개만 볼 수 있는 기능이 없습니다. 눈깔 모양 하나 추가하면 되지 않을까 싶습니다.

3. Select 박스에 아무것도 선택되지 않은 상태로 제공하는 기능이 필요합니다. 1000개가 이미 들어가 있는 형태가 아니고 아무것도 없는 것에서, 검색을하고 그 결과에서 선택을 했으면 좋겠습니다.

**Comment by deidera08** [comment]
@Taehui 의견주셔서 감사합니다 :)

문제상황과 편의개선사항으로 복합적인 이슈인듯한데
@AnnieHwang 와 논의 후 보완해야 할 사항을 정리하여 이 이슈에 덧붙이거나 또는 따로 이슈를 분리하여 개선하도록 하겠습니다.

**Comment by Taehui** [comment]
위에 City 가 예제로 있어서 생각난 부분인데, 시/도 , 구/군 , 동/리  등 하위 개념을 가지고 있는 필터들이 많습니다.
필터 Dependancy 가 적용되면 High Cardinality values 를 가진 디멘전 문제가 매우 많이 해결될 수 있습니다. 해당 이슈와 연관해서 검토해 주시면 좋겠습니다.

**Comment by deidera08** [comment]
@Taehui 필터 하이어라키일까요
MDM과 엮어서 고민하면 좋을듯 합니다. 구상해보도록 하겠습니다

**Comment by AnnieHwang** [comment]
@Taehui 
1. 일단 필터 하이어라키와 컬럼 하이어라키는 당장은 하기 곤란할꺼 같아요. (하면 좋은데 연결된 버그가 너무 많이 발생할꺼 같아서 시간이 좀 필요할것 같고요.)
2. All은 오해의 소지가 있지만 현재 사용하고 있는 기능이라 완전히 빼는건 지금 당장은 곤란해 보이고요. 대신 말씀하셨던 내용을 커버할 수 있는 다른 방법을 좀 생각해보고 말씀드리겠습니다.
감사합니다!!

**Comment by Taehui** [comment]
@AnnieHwang 요고 내용 진행 사항이 있을까요?

**Comment by AnnieHwang** [comment]
@Taehui 일단 유선으로 말씀드린것 처럼 위의 @deidera08 기획안 처럼 진행하려고 하려고 합니다. 기존에 있던 필터 기능중에 단건, 다건 필터 기능 안에 서버에 있는 데이터도 모두 검색될수 있게 하려고 하고 있어요. 다건 필터 UI중 All은 현재와 같이 놓아둘 예정입니다.

**Comment by deidera08** [comment]
@YooYoungmo @Taehui @AnnieHwang 
관리자 > 필터 패널 화면에서 기획되었으나 적용하지 못한 부분이 있습니다.
작업하실 때 이 부분을 보완해주시면 좋을듯 합니다.
![스크린샷 2019-05-21 오후 8 09 48](https://user-images.githubusercontent.com/42257766/58091395-723fad80-7c04-11e9-93a9-eb6d28654e09.png)
<img width="1919" alt="스크린샷 2019-05-21 오후 7 02 04" src="https://user-images.githubusercontent.com/42257766/58091501-a9ae5a00-7c04-11e9-817f-c0e5c2e40e8d.png">

**Comment by YooYoungmo** [comment]
@deidera08 네. 내용은 확인했습니다. 구현시 이슈 생기면 알려 드리겠습니다.
