### ISSUE TITLE
Running the Metatron with Virtual Box - ‘Metatron Discovery.ova’ image file missing

### ISSUE THREAD

**Issue by wtian** [metatron-app/metatron-discovery#2047]
At https://metatron.app/download/guide_vm/, the ‘Metatron Discovery.ova’ image file link is broken.

**Comment by alchan-lee** [comment]
@wtian 
There was a problem with our storage for a while.
It resolved and you can download the image from the link.

Thanks for your reporting.

**Comment by Hana20-ai** [comment]
The issue persists; the ‘Metatron Discovery.ova’ image file link is not working at https://www.metatron.app/download/installation-guide-vm/.

**Comment by jniemand** [comment]
The OVA is still not available.
