### ISSUE TITLE
The BBox filter does not work properly when filtering around the corner of the map

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#2061]
**Describe the bug**
I don't get in-range geometry from the engine when the corner information in the bbox filter spans the edge of the map.

![image](https://user-images.githubusercontent.com/822255/57701247-95171280-7696-11e9-813a-8cb71c971e97.png)

**To Reproduce**

Sample Data
[world.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3177884/world.csv.txt)
[ingestion_spec.json.txt](https://github.com/metatron-app/metatron-discovery/files/3177877/ingestion_spec.json.txt)

Calling engine query 
```
{
  "queryType": "select.stream",
  "dataSource": {
    "type": "table",
    "name": "world_line"
  },
  "filter": {
    "type": "and",
    "fields": [
      {
        "type": "lucene.spatial",
        "field": "WKT.shape",
        "operation": "bbox_intersects",
        "shapeFormat": "wkt",
        "shapeString": "MULTIPOINT ((180.0 -90.0), (-180.0 90.0))"
      }
    ]
  },
  "columns": [
    "WKT"
  ],
  "virtualColumns": [],
  "descending": false,
  "limit": 5000,
  "intervals": [
    "1900-01-01T00:00:00.0Z/2051-01-01T00:00:00.0Z"
  ]
}
```

**Additional context**
- Related Issue : #1965 
- Related PR : #2038

**Comment by navis** [comment]
Bounding box for `(-180.0 -90.0), (180.0 90.0)` returns empty box.. I don't know it's spec or bug of spatial4j but reverted min/max values for this specific case.
