### ISSUE TITLE
Union rule error in data preparation

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#2063]
**Describe the bug**
Please take a look at the screenshot.
The type of column A and C is double, but all columns are shown as string type.

**Screenshots**
![스크린샷 2019-05-15 오후 4 04 34](https://user-images.githubusercontent.com/44457771/57755226-4798b500-772b-11e9-9800-da954dd0336d.png)
![스크린샷 2019-05-15 오후 2 11 31](https://user-images.githubusercontent.com/44457771/57750226-5c218100-771c-11e9-9f08-b2b823169fcb.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
Cannot reproduce. @jeongeunkwon Could you attach the file you tested?

**Comment by jeongeunkwon** [comment]
@joohokim1 Here are the files.
[union_1.xlsx](https://github.com/metatron-app/metatron-discovery/files/3239246/union_1.xlsx)
[union_2.xlsx](https://github.com/metatron-app/metatron-discovery/files/3239247/union_2.xlsx)

**Comment by joohokim1** [comment]
@jeongeunkwon The files above work fine by me. Do they make problem in your environment? How about the files used when you post the screenshot? Can you give them?

**Comment by joohokim1** [comment]
@jeongeunkwon @eltriny The reason of this issue was that the column types were different, but the type icon wasn't. This is an UI bug. I'll change the assignee.

**Comment by joohokim1** [comment]
@eltriny This is not urgent. I'll remove this from 3.3.0-rc1 project.
@jeongeunkwon For now, proceed you task by appropriate settype rules.

**Comment by joohokim1** [comment]
@eltriny Let's clean up old irritating tasks in the beginning of SP.

**Comment by joohokim1** [comment]
@eltriny Let's resolve this small bug quick.

**Comment by joohokim1** [comment]
Icon bug processing is needed.
