### ISSUE TITLE
Unused wrangled datasets can not be deleted.

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#2065]
**Describe the bug**
If I try to delete unused wrangled dataset, then error occurred.

Error message:
could not execute batch; SQL [delete from pr_dataset where ds_id=? and version=?]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch

**Screenshots**
![스크린샷 2019-05-15 오후 3 46 17](https://user-images.githubusercontent.com/44457771/57754092-a6a8fa80-7728-11e9-81b1-aec79d78b044.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
@jeongeunkwon It looks like the constraint is broken in the control database. For now, the entity should be removed manually. It'll be the best if we find out the transactional problem of JPA, but it's not a good idea to retain this kind of issues. Honestly, I have no clue for now.
I'll be very happy if you reopen with a replayable scenario.
