### ISSUE TITLE
Some rules doesn't apply when create a data snapshot

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#2066]
**Describe the bug**
Setformat and set type rule doesn't apply when create a data snapshot

**To Reproduce**
1. Add a dataflow
2. Edit rule - Set format Data do 'yyyy-MM-dd'
3. Create a data snapshot

**Screenshots**
![스크린샷 2019-05-15 오후 3 48 36](https://user-images.githubusercontent.com/44457771/57754482-83327f80-7729-11e9-9699-1832679a89ac.png)

**Comment by joohokim1** [comment]
@jeongeunkwon This is because the formatting string is not applied to the snapshot detail grid. This might be considerably important, but the priority is lower than other issues. Let's handle this a bit later.

**Comment by joohokim1** [comment]
@jeongeunkwon This issue will be resolved by https://github.com/metatron-app/metatron-discovery/issues/2375.

**Comment by joohokim1** [comment]
https://github.com/metatron-app/metatron-discovery/issues/2375 has done. I'll check this up again.
