### ISSUE TITLE
Initialization function when changing value alias

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2086]
**Is your feature request related to a problem? Please describe.**
If you change multiple value aliases, you need to change them one by one because there is no initialization function.

디멘젼의 값 알리아스 팝업에서, 여러개의 값 알리아스를 변경 할 경우, 초기화 기능이 없어 다시 하나씩 변경해야 해서 번거로움. 한번에 여러개의 값 알리아스를 초기화 하는 기능이 필요함

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/6300003/57977046-ea9e4700-7a29-11e9-8360-135a0e742a01.png)

**Comment by deidera08** [comment]
@AnnieHwang 
#1185 이슈에서 초기화 버튼을 넣는 것이 고려되긴 했습니다.
본 이슈에서 초기화 기능을 추가하고 1185이슈에서 메타데이터 관련하여 적용하면 좋을듯 합니다.
![스크린샷 2019-05-21 오후 4 39 30](https://user-images.githubusercontent.com/42257766/58077258-1b77ab00-7be7-11e9-8ae7-551d8cb6a6e3.png)

**Comment by AnnieHwang** [comment]
@deidera08 버튼 디자인 진행부탁드려요

**Comment by koeun222** [comment]
'reset all' 버튼 추가한 화면 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/58228792-c6fd3880-7d6a-11e9-9299-22cf1492fb7e.png)

**Comment by AnnieHwang** [comment]
@koeun222 감사합니다~

**Comment by kyungtaak** [comment]
I think it would be good to deal with #2085 issue.
