### ISSUE TITLE
Error displaying detailed data source view on dashboard linked with two or more data sources

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#209]
**Describe the bug**
2개 이상의 데이터 소스와 링크된 대시보드 상에서 데이터 소스 상세 보기 화면 처리상 오류가 발생합니다.
Case 1. 메타데이터를 지정한 데이터 소스 1 개, 지정하지 않은 데이터 소스 1개가 있을경우 지정되지 않은 데이터 소스내 메타데이터 소스 컬럼 나타나는 부분이 나타납니다.

Case 2. 데이터 소스 컬럼 상세 보기후, 다른 데이터 소스로 전환시 전환 전 데이터 소스의 컬럼 상세 정보가 그대로 나타납니다. 

**To Reproduce**
1. 2개의 데이터 소스 생성, 1개는 메타데이터 관리 페이지에서 데이터 소스 기반으로 메타데이터 생성
2. 워크북/대시보드 생성 : 대시보드 생성시 2개의 데이터 소스 지정
3. 상단 데이터 소스 상세 보기 팝업 오픈 ("Presentaion view" 좌측 아이콘 클릭)
4-1. 메타데이터를 지정하지 않은 데이터 소스내 datagrid 탭확인 
4-2. Column Detail 탭 내 특청 컬럼 클릭, 컬럼 상세 확인 후 좌상단 콤보박스 통해 데이터 소스 전환시 그대로 상세 화면이 남아 있은 현상 확인 

**Expected behavior**
Case 1. 메타데이터를  지정하지 않은 데이터 소스일 경우 지정되지 않은 데이터 소스내 메타데이터 소스 컬럼 나타나는 부분이 나타납니다.
Case 2. 데이터 소스 전환시 전환된 데이터 소스의 첫번째 컬럼의 상세 정보가 나타나야 합니다. 

**Screenshots**
Case 1.
![image](https://user-images.githubusercontent.com/822255/45522458-25e2d900-b7fe-11e8-86e5-5bd0dadb205e.png)

Case 2.
![image](https://user-images.githubusercontent.com/822255/45522466-32673180-b7fe-11e8-9161-36ca29e27ea8.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser : Chrome
 - Version : 68.0

**Additional context**
<N/A>

**Comment by brandon-wonjune** [comment]
해당 이슈는 데이터소스 미리보기 화면 디자인 변경건이 있어서 #9 이슈의 브랜치에서 같이 작업하겠습니다

**Comment by kyungtaak** [comment]
@brandon-wonjune  진행하실때 #223 이슈도 함께 고려해주세요.
