### ISSUE TITLE
The covariance ranking of a measure is not calculated.

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2090]
**Describe the bug**
The covariance ranking of a measure is not calculated.
어느 순간부터... 매져의 Covariance Ranking이 보여지지 않고 다 0 개로 보여집니다. (모든 매져가 다 0개로 나타납니다)

**To Reproduce**
'Datasource Detail' > 'Column Detail' > Select measure > Covariance Ranking

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/57977272-d52c1b80-7a2f-11e9-97b3-ea77b9e55660.png)

**Comment by kyungtaak** [comment]
@AnnieHwang  It's solved with #2027 issue. :) I'll close this issue
