### ISSUE TITLE
When setting the missing data to discard in the ingestion setting of the measure column, the row is not discarded

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2092]
**Describe the bug**
When setting the missing data to discard in the ingestion setting of the measure column, the row is not discarded

데이터소스 인제스쳔 시 매져의 인제스쳔 속성 중 'missing'을 'discard'로 선언할 경우
실제로 해당 row가 discard되지 않는 현상이 발생함 (반면 dimension일 경우 discard가 정상적으로 수행됨)

**To Reproduce**
Create 'datasource' > Configure Scheme > Select measure > missing

**Screenshots**
![2019-05-19_12-43-55](https://user-images.githubusercontent.com/6300003/57977492-82089780-7a34-11e9-972c-153d703e8b84.gif)
![image](https://user-images.githubusercontent.com/6300003/57977501-a8c6ce00-7a34-11e9-8e2b-51f63e3fab20.png)
![image](https://user-images.githubusercontent.com/6300003/57977510-cdbb4100-7a34-11e9-80fd-f5a21cda1caa.png)

**Comment by kyungtaak** [comment]
@minhyun2 Can you check this issue?

**Comment by minhyun2** [comment]
@kyungtaak I checked that it works well.
