### ISSUE TITLE
Entering time format causes an error in Metadata column schema page

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#210]
**Describe the bug**
메타데이터 상세 페이지 내 'Column schema' 탭에서 timestamp의 시간 포멧을 입력한후 저장하려고 하면 에러가 납니다. 또는 용어 사전에서 시간 포멧을 입력한 용어를 컬럼에 지정해도 동일한 에러가 납니다.

**To Reproduce**
1. Go to Metadata
2. Click one metadata to enter detail page
3. Click on Column schema tab
4. Change any column's logical type to Timestamp
5. Enter any format string(like yyyy.MM.dd) in Format cell
6. Click Save button

or

4. Change one column's Dictionary to any column dictionary which has time format string
5. Click Save button

**Expected behavior**
입력된 시간 포맷이 정상적으로 저장되어야 합니다.

**Screenshots**
<img width="742" alt="2018-09-14 11 15 03" src="https://user-images.githubusercontent.com/28751002/45526101-d063f780-b810-11e8-9af7-5d1e8f8cebeb.png">
<img width="742" alt="2018-09-14 11 08 55" src="https://user-images.githubusercontent.com/28751002/45526102-d063f780-b810-11e8-8b09-fafcf8e8446b.png">
<img width="742" alt="2018-09-14 11 13 43" src="https://user-images.githubusercontent.com/28751002/45526106-d2c65180-b810-11e8-905c-4a560b86bae8.png">

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: chrome
 - Version: 68

**Additional context**

**Comment by brandon-wonjune** [comment]
@kyungtaak @minjung-cho 
문의사항 드립니다. 
#201 번에서 정의한 타입
> Engine : 실제 물리데이터 (Druid 내 물리테이블)
> - Engine Name : 실제 물리데이터의 테이블명
> - Engine Column Name : 실제 물리데이터의 컬럼 이름
> - Engine Column Type : 실제 물리데이터의 컬럼 타입
>
> Physical : 실제 물리데이터를 Metatron 내에서 잘 설명하기 위한 논리데이터 (데이터소스)
> - Physical Name : 데이터소스 명
> - Physical Column Name : 데이터소스 내 컬럼 이름
> - Physical Column Type : 데이터소스 내 컬럼 타입
>
> Logical : Metatron 내 물리데이터인 데이터소스를 잘 설명하기 위한 논리데이터 (Meta Data)
> - Logical Name : 메타데이터명
> - Logical Column Name : 메타데이터 컬럼 이름
> - Logical Column Type : 메타데이터 컬럼 타입

현재 데이터소스로 생성한 메타데이터 상세화면에서 내려오는 `physicalType`이 다르게 오고있는것 같습니다.
기획의 의도는 데이터소스 생성시 사용된 type이 내려오는게 맞나요?

**Comment by minjung-cho** [comment]
@brandon-wonjune 네, 첨부하신 내용과 같이 Physical column name은 데이터소스 생성시 설정한 그것이 맞습니다

**Comment by brandon-wonjune** [comment]
@kyungtaak 
해당 페이지에서 포맷을 입력하면 아래와 같은 에러가 발생합니다.
```
// api
api/metadatas/{metadataId}/columns

// params
format:"yyyy-mm"
id:1
name:"OrderDate"
op:"replace"
physicalName:"OrderDate"
physicalType:"TIMESTAMP"
popularity:0
type:"TIMESTAMP"

// error
code:"GB0001"
details:"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction"
message:"Unknown server error"
```

**Comment by kyungtaak** [comment]
@ecoloy 그런데 포맷은 timestamp 타입만 지정하나요? 다른 타입은 어떻게 지정할런지 확인 부탁드립니다.
그게 정리되어야할것 같네요.

@brandon-wonjune format 속성이 문제가 있습니다. 이건 format 지정에 대한 정의가 될때, 추가 구현을 하고 아예 막았으면하는데요.  @ecoloy 답변을 기다린후 정리를 했으면 합니다.

**Comment by ecoloy** [comment]
@kyungtaak @AnnieHwang 우선 질문하신 사항에 답변드리면, 여기서의 포맷은 (시간)포맷이기때문에 timestamp인 경우에만 입력이 활성화 됩니다. timestamp가 아닌 다른 타입인 경우에는 해당 입력창은 비활성화 되어야 합니다.

**Comment by kyungtaak** [comment]
@ecoloy @AnnieHwang 다른 메타데이터 시스템도 이렇게 타임 필드만 포맷을 정의하나요?

**Comment by ecoloy** [comment]
@kyungtaak 우선 엑셀의 경우를 살펴보니 날짜/시간이 아닌 숫자 타입의 경우 소수 자릿수를 설정하는 표시형식을 제공합니다만, 메타트론의 경우에는 차트의 숫자 패널에서 해당 기능을 수행하기때문에 MDM 내에 꼭 필요한지는 잘 모르겠습니다. 엑셀에서도 일반 텍스트의 경우에는 별도의 표시 형식은 없습니다. @AnnieHwang 매니저님께서는 어떻게 생각하시나요?

<img width="617" alt="2018-09-19 3 50 47" src="https://user-images.githubusercontent.com/28751002/45735874-58d50480-bc24-11e8-81a6-c616da7d3d10.png">
<img width="616" alt="2018-09-19 3 50 56" src="https://user-images.githubusercontent.com/28751002/45735946-86ba4900-bc24-11e8-8ae4-d38ea72aec9a.png">

**Comment by kyungtaak** [comment]
@ecoloy 금일 릴리즈 미팅에서도 논의했듯이 포맷관련 관련 내용은 별도 이슈로 관리하여 발전 시켜 나갔으면 합니다. 

@eltriny @brandon-wonjune 이 이슈는 close 를 하고 ETC 타입 관련 추가(목록 뿐만아니라 상세도 고려한) 에 대한 이슈를 추가한 후, 그곳에서 format 컬럼을 막는것을 포함하여 진행했으면 합니다.  

두개의 이슈가 생성되면 이 이슈는 종료하도록 하겠습니다. 이슈 생성후 링크 부탁드립니다.

**Comment by ecoloy** [comment]
@kyungtaak @eltriny @brandon-wonjune 본 이슈 관련하여 TDE 이슈를 생성해서 기획을 업데이트 하였습니다. 참고부탁드립니다. https://tde.sktelecom.com/pms/browse/METATRON-1478
