### ISSUE TITLE
Setting the logical type to etc causes an error in Metadata column schema page

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#211]
**Describe the bug**
메타데이터 column schema 탭에서 논리 타입을 etc (hive 메타데이터인 경우에는 more type에 들어있는 아무 타입)로 설정하고 저장을 하면 에러가 발생합니다.

**To Reproduce**
1. Go to Metadata
2. Click one metadata to enter detail page
3. Click on Column schema tab
4. Change any column's logical type to Etc (If hive metadata is selected, change column's logical type to any type under 'More types')
5. Click Save button

**Expected behavior**
Etc, More type의 논리타입을 설정했을때 정상적으로 저장되어야 한다.

**Screenshots**
<img width="742" alt="2018-09-14 11 07 54" src="https://user-images.githubusercontent.com/28751002/45526340-b1b23080-b811-11e8-8bf0-0b6f32ab3cf8.png">
<img width="742" alt="2018-09-14 11 05 51" src="https://user-images.githubusercontent.com/28751002/45526341-b1b23080-b811-11e8-99a5-bf10e8ab580b.png">
<img width="742" alt="2018-09-14 11 07 48" src="https://user-images.githubusercontent.com/28751002/45526342-b24ac700-b811-11e8-85db-2e5307a76e84.png">

**Desktop (please complete the following information):**
 - OS: MacOS high sierra
 - Browser: chrome
 - Version: 68

**Additional context**

**Comment by brandon-wonjune** [comment]
@ufoscw 
문의사항이 있습니다.
logical type 중 ETC를 제외시켜 달라고 하셨는데 컬럼사전 및 more types에 해당하는 모든 타입도 포함하여 제외시키면 될까요?

**Comment by kyungtaak** [comment]
@brandon-wonjune 급하게 추가하기 보다는 시간을두고 추가해나갔으면 해서 막아달라고 요청드렸습니다.

**Comment by brandon-wonjune** [comment]
ETC와 more types에 대한 타입들을 제거하였습니다.

**Comment by AnnieHwang** [comment]
@kyungtaak @brandon-wonjune ETC는 DT쪽 요구사항이었는데. 일단 DB로 insert하도록 하겠습니다. 지금 현재 ETC>IMAGE같은 타입을 UNKNOWN 이라는 String 값으로 해당 테이블 컬럼 안에 insert 하고 있는데.. 선택값에 없는 UNKNOWN타입이 들어갈때, 정상적으로 화면에 에러없이 보여주시면 될 것 같습니다. (아니면.. 선택값이 없는 값이 보여지면 ETC 라고 변환해서 보여주셔도 괜찮을것 같습니다)

**Comment by brandon-wonjune** [comment]
@AnnieHwang 
단순히 변경가능한 목록에 없다면 출력만 ETC로 보여주면 될까요?

**Comment by kyungtaak** [comment]
@AnnieHwang 제거하고 추후 etc 관련 내용을 추가하는것으로 진행하겠습니다.
