### ISSUE TITLE
User Delete Policy

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#2115]
![스크린샷 2019-06-03 오후 4 15 17](https://user-images.githubusercontent.com/28773903/58783026-eb82cb80-861a-11e9-843f-fc3cc98799ee.png)

사용자 삭제시 정책은 다음과 같습니다. (Inactive 상황 아니고 삭제시 상황입니다.)
해당 사용자의 개인 워크스페이스 및 하위 워크북/워크벤치 등은 삭제됩니다.
해당 사용자가 owner인 워크스페이스가 없을 경우 경고 Alert후 삭제 됩니다.(OK)
해당 사용자가 owner인 워크스페이스가 있을 경우 owner변경하는 팝업이 노출됩니다.
.
.
유저 삭제시 공유 스페이스 권한 변경 팝업에서
![스크린샷 2019-05-22 오후 3 00 36](https://user-images.githubusercontent.com/42257766/58152549-cd76ac00-7ca7-11e9-8a62-7cedf645f289.png)
그러나 소속 멤버가 없을 경우 owner변경할 수 없어 Validation check되고, 삭제할 수 없는 문제가 있습니다.
때문에 소속 멤버가 없을 경우 개인 워크스페이스와 동일 취급하여 삭제되어야 합니다.
.
.
유저 삭제 후 화면 노출에서 몇가지 수정/보완해야 합니다.
1_ 해당 유저가 등록한 게시물은 Unknown user로 노출됩니다. ('_'삭제하고, 대/소문자 맞춰주세요)
![스크린샷 2019-05-22 오후 3 21 50](https://user-images.githubusercontent.com/42257766/58152603-eed79800-7ca7-11e9-835e-025b15142573.png)

2_ 권한 등의 팝업에서 삭제된 유저는 노출되지 않아야 합니다.
![스크린샷 2019-05-22 오후 3 36 40](https://user-images.githubusercontent.com/42257766/58152608-f1d28880-7ca7-11e9-8019-4c2e44d7a253.png)

3_ Workspace관리화면 목록에서 해당 유저의 workspace는 삭제되어야 합니다.
![스크린샷 2019-05-22 오후 3 21 15](https://user-images.githubusercontent.com/42257766/58152623-f7c86980-7ca7-11e9-96e4-2b10c4a02f95.png)

-------------
>어드민은 사용자의 상태가 Inactive인 사용자만 사용자 삭제가 가능함 (기존 사용자 목록에 삭제버튼이 다 보여지던데 Inactive 사용자만 삭제버튼이 보여져야 합니다.)

위 상황 추가합니다.

1_ Members목록에서 Delete버튼은 삭제합니다.
Inactive된 사용자만 삭제할 수 있는 만큼 신중하게 삭제되었으면 좋겠고, 때문에 목록에 삭제버튼이 직접 노출되는것은 좋지 않은듯 합니다.
![스크린샷 2019-05-22 오후 4 28 15](https://user-images.githubusercontent.com/42257766/58155676-4f1e0800-7caf-11e9-8e83-e58383e63ee6.png)
.

2_ 사용자 상세화면에 상시노출되고 있는 삭제버튼을 Inactive일때만 노출되도록 수정부탁드립니다.
![스크린샷 2019-05-22 오후 4 28 44](https://user-images.githubusercontent.com/42257766/58155817-a7eda080-7caf-11e9-990b-c6df6fb55078.png)

**Comment by AnnieHwang** [comment]
@deidera08 한가지 빠진 게 있어서 추가적으로 적어요~
- 어드민은 사용자의 상태가 Inactive인 사용자만 사용자 삭제가 가능함
