### ISSUE TITLE
Dashboard thumbnail does not appear in I.E browser

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#212]
**Describe the bug**
대시보드의 섬네일 정보가 IE 에서는 정상적으로 표현되지 않는 버그 (크롬에서는 정상 동작)

**Expected behavior**
IE 에서도 대시보드 섬네일의 정상적인 표현이 필요

**Screenshots**
![ie](https://user-images.githubusercontent.com/612173/45526622-da86f580-b812-11e8-94fb-5701dfd813d6.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7 Enterprise K]
 - Browser [Internet Explorer]
 - Version [11.0.49]
![ie](https://user-images.githubusercontent.com/612173/45526758-7284df00-b813-11e8-9b8b-54613500ec77.png)

**Additional context**
IDCube

**Comment by Taehui** [comment]
@kyungtaak 해당 버그가 크리티컬 버그는 아닌데, 버그의 티가 많이 나는 버그이다보니 오픈 시연 시에 눈에 많이 뛸 듯 합니다. ^^;

**Comment by AnnieHwang** [comment]
@Taehui @kyungtaak 저희가 내부적으로 테스트 해본 결과, IE와 Chrome 모두 이미지 캡쳐는 되는데 이미지를 가져오는 호출 시 IE는 404에러로 못가져오고 Chrome은 정상적으로 이미지를 가져오는 것으로 확인되었습니다. 원인이 정확한지는 모르겠지만, IE와 Chrome의 호출 속성 시 차이가 Accept라는 속성값만 유일하게 차이가 있었습니다.(Chrome은 이미지 호출 시 Accept 속성이 'image/*'로 되어 있으나, IE는 '*/*'로 되어 있었습니다.) 
![image](https://user-images.githubusercontent.com/6300003/45666816-ac2a5280-bb51-11e8-868c-422af39bc7f2.png)

**Comment by YooYoungmo** [comment]
제가 테스트한 결과 공유합니다.
@Taehui 님과 동일한 환경에서 테스트한 결과 정상적으로 썸네일 이미지가 보입니다.
![image](https://user-images.githubusercontent.com/16472109/45671830-80af6400-bb61-11e8-9928-e4ed9a70f30c.png)
하지만 **IE '호환성 보기 설정'에 메타트론 사이트를 추가**하면 썸네일 이미지가 나오지 않습니다.
![image](https://user-images.githubusercontent.com/16472109/45671976-e7348200-bb61-11e8-8265-3d67c8d92508.png)
HTTP Request를 확인해 보니 같은 IE임에도 '호환성 보기 설정'에 추가 전/후 헤더 값이 변경되는 것을 확인 했습니다.
![image](https://user-images.githubusercontent.com/16472109/45672638-a89fc700-bb63-11e8-9ce0-72bf7651ab79.png)

**Comment by Taehui** [comment]
저도 제 환경에서 호환성보기에 추가되어 있는 sktelecom.com 을 제거했더니 섬네일이 보입니다.

**Comment by kyungtaak** [comment]
@Taehui 확인 감사합니다. 호환성보기를 고려하지 못했네요. @metatron-app/design 브라우져정책 특히 IE 에서는 어떻게 정리해야할지 정책적인 측면에서 고려부탁드립니다.

**Comment by YooYoungmo** [comment]
@kyungtaak 버그 원인을 찾아서 해당 코드를 수정하고 싶은데 혹시 어느 브랜치에 작업해서 Pull Request 하면 될까요?

**Comment by kyungtaak** [comment]
@YooYoungmo 디자인팀과 논의 결과 저희는 내부적으로 호환성 보기는 지원하지 않을 예정입니다. 
- 따라서, 호환성 보기에 따른 분기 처리라면 허용하기 어렵고요. 근본적인 원인에 대한 해결책이라면, 진행이 가능하실것 같습니다.  
- 금일이 3.0.3 개발 마감일입니다. 금일내로 해결이 가능하시면 금일 중에 PR 요청 부탁드립니다. (리뷰어로 @eltriny 님을 꼭 넣어주세요.)
- 브랜치는 3.0.3 브랜치를 기반으로 f#212-ie_dashbard_thumbnail_error 로 개별적으로 생성하여 개발 진행 부탁드립니다.

**Comment by YooYoungmo** [comment]
@kyungtaak 자세한 코멘트 감사합니다. ^^
제가 PR할 코드가 언급하신 '호환성 보기에 따른 분기 처리'에 해당 되는지는 현재 제가 판단하기 어렵네요.
PR 코드를 보시고 판단해 주시면 좋을 것 같습니다.

그리고 오늘내로 PR 드리겠습니다.
