### ISSUE TITLE
If the measure data is null, it must be able to be replaced with a negative value in the data source ingestion process.

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2120]
**Describe the bug**
If the measure data is null, it must be able to be replaced with a negative value in the data source ingestion process.
데이터소스 인제스쳔 시 매져값의  missing data가  null인 경우 음수값으로 replace 될수 있게 해야 합니다.
Integer, Decimal 모두 음수값이 적용될 수 있어야 합니다.

**To Reproduce**
Create Datasource > Configuration Scheme > missing conf > replace with

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/58220484-06fff380-7d4a-11e9-85e0-dc119167ed0f.png)

**Comment by kyungtaak** [comment]
@minhyun2 can u check this issue?

**Comment by minhyun2** [comment]
> @minhyun2 can u check this issue?

@kyungtaak Yes, I'll fix it.

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by minhyun2** [comment]
run build
deploy to 4
