### ISSUE TITLE
Aggregation of calculation field does not apply well

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#213]
**Describe the bug**
계산식 필드를 만들어 선반에 올린 후 aggregation타입을 바꾸고 저장을 한후, 다시 확인하면 변경한 aggregation 타입이 정상 반영되지 않음

**To Reproduce**
1. Go to 차트 상세화면
2. 계산식 필드를 선반에 올리고
3. Aggregation타입을 SUM에서 COUNT로 변경
4. 차트와 대시보드를 저장하고
5. 다시 차트 편집을 누리면 Aggregation 타입이 SUM으로 되어 있음

**Screenshots**
![2018-09-14_13-06-43](https://user-images.githubusercontent.com/6300003/45529250-2b9ce680-b81f-11e8-848a-f2f18c57a61b.gif)

**Comment by juheeko9** [comment]
@kyungtaak 해당 이슈는 #216 이슈에서 말씀하신대로 customFields을 userDefinedFields라는 속성명으로 변경하여야 하는 이슈입니다. 
customFields를 userDefinedFields로 변경시 해결되는 이슈입니다.

**Comment by eltriny** [comment]
@kyungtaak 
#216 이슈와 같은 내용이므로 216번 이슈 branch에서 같이 작업할 예정입니다.
