### ISSUE TITLE
Data exploration based on popularity, updated-date, catalog, tags using metadata

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2131]
**Is your feature request related to a problem? Please describe.**
Data exploration based on popularity, updated-date, catalog, tags using metadata
(Metadata Explore Data > Main Page)

**Describe the solution you'd like**
1. LNB (Catalog, Tag List)
2. Popular Data List
3. New or Update List

**Describe alternatives you've considered**

**Additional context**

**Comment by deidera08** [comment]
기획화면 공유드립니다.

1_ 메인화면
![스크린샷 2019-05-28 오후 6 13 47](https://user-images.githubusercontent.com/42257766/58466438-a4a55980-8174-11e9-8e33-7fa9e43fa5b9.png)
.

2_ 메인화면 > 카탈로그 검색
![스크린샷 2019-05-28 오후 6 14 31](https://user-images.githubusercontent.com/42257766/58466445-a707b380-8174-11e9-9884-d8f58b8e366d.png)
.

3_ 카탈로그 목록
![스크린샷 2019-05-28 오후 6 14 06](https://user-images.githubusercontent.com/42257766/58466450-a8d17700-8174-11e9-8e11-0ba6fc2f1bed.png)

**Comment by brandon-wonjune** [comment]
@AnnieHwang 
메인화면에서 질문이 있습니다.
태그나 설명이 없는경우 아래와 같이 표현이 되는데 괜찮은가요?
![스크린샷 2019-06-18 오전 10 22 37](https://user-images.githubusercontent.com/42233627/59646807-7cc57680-91b3-11e9-8cd4-dfe59865c174.png)

**Comment by brandon-wonjune** [comment]
@ufoscw 해당 화면별 api 문의입니다.
Q1. 
![스크린샷 2019-06-18 오후 2 00 17](https://user-images.githubusercontent.com/42233627/59654540-9b3a6a80-91d1-11e9-857a-d5847fccee29.png)
초기 explore data 화면 진입시 title 하단의 database, stagingDB, datasource 메타데이터 수는 어떤 api로 조회할 수 있나요?

Q2. 메타데이터 조회시 아래의 api를 사용해서 아래의 화면을 표시하고있습니다.
```
api/metadatas?page=0&size=20&projection=forListView
```
![스크린샷 2019-06-18 오후 2 00 22](https://user-images.githubusercontent.com/42233627/59654561-c02edd80-91d1-11e9-8d1b-0801017b4a53.png)
이 화면에서는 `인기도`순으로 보여줘야 될 것 같은데 저 api를 그대로 사용해야 된다면 어떤 값을 querystring으로 넘겨야 되나요?
@AnnieHwang 그리고 popular data 란에서 얼만큼의 수의 데이터를 보여줘야되나요?

Q3. 아래에 해당하는 화면들에 대해 api는 어떤 것을 사용해야되나요?
![스크린샷 2019-06-18 오후 2 04 46](https://user-images.githubusercontent.com/42233627/59654641-1b60d000-91d2-11e9-9621-1bb84958e5cb.png)
![스크린샷 2019-06-18 오후 2 00 28](https://user-images.githubusercontent.com/42233627/59654646-1f8ced80-91d2-11e9-8102-d1df5bb31b3d.png)
![스크린샷 2019-06-18 오후 2 00 24](https://user-images.githubusercontent.com/42233627/59654648-20be1a80-91d2-11e9-9a6c-1b95a7852634.png)

**Comment by ufoscw** [comment]
@brandon-wonjune 
Q1.
아래 API 추가되었습니다.
```
(GET) /api/metadatas/statistics/count/sourcetype
```
* Response Sample
```
{
    "ENGINE": 2,
    "JDBC": 5,
    "STAGEDB": 2
}
```

Q2, Q3
API 수정후 다시 알려드릴게요.

Q4
네. 위 API 사용하시면 됩니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 
카탈로그 아이디를 이용하여 메타데이터 목록 조회 api문의드립니다.
```
api/catalogs/{catalogId}/metadatas?page=0&size=20&projection=default&allSubCatalogs=true
```
이 api를 활용하여 목록을 보여주려고 하는데 아래와 같이 표기해야됩니다.
![스크린샷 2019-06-20 오후 1 13 55](https://user-images.githubusercontent.com/42233627/59818092-665b1e80-935d-11e9-8b98-22322adf3323.png)
여기서 datatype, tags, creator, popularity, createdTime이 오고있지 않습니다

**Comment by brandon-wonjune** [comment]
@AnnieHwang 여기서 하단의 페이징의 경우 변경된 페이징이 들어가야되나요 아니면 아래와 같이 더보기가 들어가야되나요?
![스크린샷 2019-06-20 오후 1 17 29](https://user-images.githubusercontent.com/42233627/59818197-c651c500-935d-11e9-906e-897df6006a48.png)

**Comment by ufoscw** [comment]
@brandon-wonjune 
> api/catalogs/{catalogId}/metadatas?page=0&size=20&projection=default&allSubCatalogs=true

projection을 forListView 사용하시면 됩니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 
```
api/catalogs/ROOT/tree
api/catalogs/{catalogId}/tree
```
이 api 문의 드립니다.
해당 api를 사용하여 아래와 같은 화면을 구현하였습니다.
![스크린샷 2019-06-21 오전 10 15 09](https://user-images.githubusercontent.com/42233627/59890831-bdb8c780-940d-11e9-93db-bdd2707d75de.png)
화면 구현한 순서는 다음과 같습니다.
1. 초기에 화면 진입시 ROOT를 보여주는 api/catalogs/ROOT/tree를 이용
2. depth가 존재하는 카탈로그 클릭시 api/catalogs/{catalogId}/tree를 이용

그러면 저 search 기능을 이용할 때는 어떤 api와 param으로 검색을 요청해야되나요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
tree view를 위한 카탈로그 검색 API sample입니다.
```
(GET) api/catalogs?nameContains={textForSearch}&projection=forSimpleTreeView
```

response sample
```
[
    {
        "name": "depth1_bbb",
        "id": "1aa1c10b-88f5-4104-8207-1c895b43d707",
        "countOfChild": 3
    },
    {
        "name": "depth2_bbb_111",
        "id": "30898d6a-36b2-4720-9ae5-180d6f898728",
        "countOfChild": 0
    },
    {
        "name": "depth2_bbb_333",
        "id": "364329ca-c2ac-4f7d-bbca-07accb1f3d18",
        "countOfChild": 0
    },
    {
        "name": "depth2_ccc",
        "id": "57d98afc-1295-44a3-ad90-bc106142959e",
        "countOfChild": 0
    },
    {
        "name": "depth3_ccc_111_222",
        "id": "857460ec-fa42-4bfa-936f-a1fd73f127fc",
        "countOfChild": 0
    },
    {
        "name": "catalog_depth1_aaaa",
        "id": "93071e18-c6e6-465d-b800-f1d1535d3422",
        "countOfChild": 3
    },
    {
        "name": "depth1_ccc",
        "id": "b9319954-6dce-4062-8b86-6d0df065c32a",
        "countOfChild": 1
    },
    {
        "name": "depth2_ccc_111",
        "id": "b998bb3d-3c88-4e72-9323-2a3f9d57d646",
        "countOfChild": 1
    },
    {
        "name": "depth2_aaa",
        "id": "c1bff0da-d0f8-44b9-ae4e-b55c9c8297e3",
        "countOfChild": 0
    },
    {
        "name": "depth2_bbb_222",
        "id": "ced585a8-6dde-4660-b0ec-5253cd97f073",
        "countOfChild": 0
    },
    {
        "name": "depth2_bbb",
        "id": "dbca04c5-60b2-4302-9187-eb84346f81f8",
        "countOfChild": 0
    }
]
```

**Comment by AnnieHwang** [comment]
@brandon-wonjune 변경된 페이징이 들어가야해요 #2166 페이징 기획안으로 정해졌어요. 기존 페이징이 기획서와 다르게 개발되어서 다시 바꾸기로 했거든요

**Comment by AnnieHwang** [comment]
@brandon-wonjune 위에 질문이 또 있어서.. 윗 댓글에 추가해두었습니다~

**Comment by ufoscw** [comment]
@brandon-wonjune 
1. 인기도 순 api 추가되었습니다.
```
(GET) /api/metadatas/popularity(?size, page)
```

* response sample
```
{
    "_embedded": {
        "metadatas": [
            {
                "name": "book",
                "id": "51066bd2-f143-46db-b592-8457c53d181d",
                "createdTime": "2019-06-27T00:18:21.000Z",
                "sourceType": "JDBC",
                "createdBy": {
                    "type": "user",
                    "username": "admin",
                    "fullName": "Administrator",
                    "email": "admin@metatron.com"
                },
                "popularity": 0.2,
                "modifiedBy": {
                    "type": "user",
                    "username": "admin",
                    "fullName": "Administrator",
                    "email": "admin@metatron.com"
                },
                "modifiedTime": "2019-06-27T00:18:21.000Z",
                "tags": [],
                "_links": {
                    "self": {
                        "href": "http://localhost:8180/api/metadatas/51066bd2-f143-46db-b592-8457c53d181d{?projection}",
                        "templated": true
                    },
                    "columns": {
                        "href": "http://localhost:8180/api/metadatas/51066bd2-f143-46db-b592-8457c53d181d/columns"
                    },
                    "catalogs": {
                        "href": "http://localhost:8180/api/metadatas/51066bd2-f143-46db-b592-8457c53d181d/catalogs"
                    }
                }
            },
            {
                "name": "sales",
                "id": "test_meta1",
                "createdTime": "2019-06-26T14:54:50.000Z",
                "sourceType": "ENGINE",
                "createdBy": {
                    "type": "user",
                    "username": "admin",
                    "fullName": "Administrator",
                    "email": "admin@metatron.com"
                },
                "popularity": 0.2,
                "modifiedBy": {
                    "type": "user",
                    "username": "admin",
                    "fullName": "Administrator",
                    "email": "admin@metatron.com"
                },
                "modifiedTime": "2019-06-26T14:54:50.000Z",
                "description": "meta description1",
                "tags": [],
                "_links": {
                    "self": {
                        "href": "http://localhost:8180/api/metadatas/test_meta1{?projection}",
                        "templated": true
                    },
                    "columns": {
                        "href": "http://localhost:8180/api/metadatas/test_meta1/columns"
                    },
                    "catalogs": {
                        "href": "http://localhost:8180/api/metadatas/test_meta1/catalogs"
                    }
                }
            }
        ]
    },
    "_links": {
        "first": {
            "href": "http://localhost:8180/api/metadatas/popularity?page=0&size=3"
        },
        "prev": {
            "href": "http://localhost:8180/api/metadatas/popularity?page=0&size=3"
        },
        "self": {
            "href": "http://localhost:8180/api/metadatas/popularity?page=1&size=3"
        },
        "last": {
            "href": "http://localhost:8180/api/metadatas/popularity?page=1&size=3"
        }
    },
    "page": {
        "size": 3,
        "totalElements": 5,
        "totalPages": 2,
        "number": 1
    }
}
```

2. my favorite, favorite creator, recommend list api가 추가되었습니다.
```
(GET) /api/metadatas/favorite/my?(size, page, projection, sort)
(GET) /api/metadatas/favorite/creator?(size, page, projection, sort)
(GET) /api/metadatas/recommended?(size, page, projection, sort)
```
현재는 metadata list와 동일한 데이터로 내려갑니다.
front에서는 위 API로 연결만 해주세요.

**Comment by ufoscw** [comment]
@brandon-wonjune 
LNB 노출 여부에 대한 로직 구현이 필요합니다.
lnb api 호출 시 아래와 같은 response가 내려갈 예정입니다.
이 경우에만 LNB에 메뉴를 표시해주세요.
```
[
   {
      "name":"Explore Data",
      "parent":"workspace"
   }
]
```

**Comment by brandon-wonjune** [comment]
@AnnieHwang 
recommended 데이터가 4개만 오는경우 아래와 같이 빈 공간이 생기는 경우가 있습니다.
![스크린샷 2019-06-27 오전 10 56 35](https://user-images.githubusercontent.com/42233627/60227473-6eb9d900-98ca-11e9-9cc5-72d253ca2841.png)

빈 공간이 생겨도 상관없나요?
1개만 오는경우는 목록 자체가 사라지고 하나의 데이터만 표기되기 때문에 빈공간이 생기지 않습니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 
업데이트된 메타데이터 목록의 api는 어느것을 써야되나요?
![스크린샷 2019-06-27 오후 1 12 36](https://user-images.githubusercontent.com/42233627/60233942-4b4c5980-98dd-11e9-8169-99bc06bab13d.png)
```
/api/metadatas?page=0&size=20
```
이 api를 써야된다면 explore data만 표시하는 param key는 어느것으로 날려야되나요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
explore data 여부는 추후 권한 처리할때 기능을 추가할 예정입니다.
현재는 그냥 modifiedTime 내림차순으로 사용하시면 됩니다.
```
(GET) /api/metadatas?projection=forListView&sort=modifiedTime%2Cdesc
```

**Comment by AnnieHwang** [comment]
@brandon-wonjune @ufoscw 
1,recommended 데이터가 4개만 오는경우 아래와 같이 빈 공간이 생기는 경우가 있습니다. 빈 공간이 생겨도 상관없나요?
==> 꼭 5개 오게 해주세요. 데이터가 5개 미만인 경우는 1개만 보여줘 빈공간이 생기지 않게 해주시고요. 데이터가 5개 이상되는 경우 무조건 추천은 서버에서 5개를 채워서 오게 해주세요 (인기도 순으로)

2. banner의 뒷 배경의 그림은 랜덤하게 표시되면 되는건가요?
=> 나중에 Admin기능에 뒷 배경을 바꾸는 기능이 기획되어 있습니다. 지금은 고정적으로 가셔도 됩니다.

Q3. 즐겨찾기 관련된 메타데이터는 몇개까지 표시해야되나요?
=> 디자인 상으로는 3개 예요. 나머지는 more 버튼으로 보는거고요.
![image](https://user-images.githubusercontent.com/6300003/60333582-6057e400-99d4-11e9-88ae-a0e84f6c7e51.png)

Q4. my favorite와 favorite creator는 한글로 뭐라고 표시하면 되나요?
=> '즐겨찾기'
=> favorite creator가 아니라 data creator 말씀이신거 맞죠? '데이터 등록자' 로 해주세요~

**Comment by brandon-wonjune** [comment]
@AnnieHwang

위 댓글남겨주신대로 적용하고, 즐겨찾기 관련 4개 이상 오는경우를 위한 more는 따로 팝업창이나 화면에 대한 디자인 또는 기획이 없는데 일단 버튼을 숨기는것으로 적용하겠습니다.

**Comment by ufoscw** [comment]
@brandon-wonjune
아래 내용까지 PR에 적용되어야 합니다.
> @brandon-wonjune
> LNB 노출 여부에 대한 로직 구현이 필요합니다.
> lnb api 호출 시 아래와 같은 response가 내려갈 예정입니다.
> 이 경우에만 LNB에 메뉴를 표시해주세요.
> 
> ```
> [
>    {
>       "name":"Explore Data",
>       "parent":"workspace"
>    }

**Comment by brandon-wonjune** [comment]
@ufoscw explore 관련이 있는경우에만 표시되도록 수정하였습니다.
