### ISSUE TITLE
The lineage view is added when viewing the metadata.

### ISSUE THREAD

**Issue by ksparknot** [metatron-app/metatron-discovery#2142]
**Is your feature request related to a problem? Please describe.**
If there is information about the relationship between table or system of metadata, we can visualize it through lineage chart.

**Describe the solution you'd like**
to implement lineage view of mdm having a directed graph

**Describe alternatives you've considered**

**Additional context**

**Comment by AnnieHwang** [comment]
@ksparknot 초안으로 그려진 기획안 올려드립니다.
![image](https://user-images.githubusercontent.com/6300003/58472624-a0336d80-8181-11e9-8540-a1bc63514b85.png)
![image](https://user-images.githubusercontent.com/6300003/58472633-a3c6f480-8181-11e9-8782-f423689ebb21.png)
![image](https://user-images.githubusercontent.com/6300003/58472639-a75a7b80-8181-11e9-9890-bc81514aef49.png)
![image](https://user-images.githubusercontent.com/6300003/58472645-a9bcd580-8181-11e9-999d-7cba501804be.png)
@koeun222 디자인 진행 부탁드려요

**Comment by joohokim1** [comment]
시스템, 인터페이스는 구현 대상에서 제외되었습니다.

**Comment by joohokim1** [comment]
@ksparknot @AnnieHwang @ufoscw @koeun222 
Issue closing. Further work will be continued with https://github.com/metatron-app/metatron-discovery/issues/2266.
