### ISSUE TITLE
Is there any capability of filtering data in shared workspace dashboard data

### ISSUE THREAD

**Issue by kaviranga** [metatron-app/metatron-discovery#2146]
I wanted to know that if there is any capability  of filtering data in shared workspace dashboards using metatron-discovery . As an example "filter the data in dashboard map included in a shared workspace" for a guest user like "metatron" .
![Screenshot_2019-05-28_17-34-15](https://user-images.githubusercontent.com/6471174/58476800-82f5a380-816f-11e9-9cee-47f67456b693.png)

Is there any capability ?

**Comment by ufoscw** [comment]
Are you asking if a user without edit permission can filter data?

Adding a filter widget to dashbaord allows the guest user to filter data.

* filter add button
<img width="659" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/58521676-33a78580-81f8-11e9-9554-79ba8606a713.png">

Add a filter and drag&drop it to the dashboard to create a widget.
<img width="1308" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/58521788-98fb7680-81f8-11e9-812f-e9715afd37a9.png">

Is it the geo column you want to filter?

**Comment by kaviranga** [comment]
@ufoscw  Thanks friend , This is the solution that I wanted  :-) . I've tried this and got the result.!
