### ISSUE TITLE
Is there any ability to connect REST api and grab data from it for view in metatron-discovery dashboard

### ISSUE THREAD

**Issue by kaviranga** [metatron-app/metatron-discovery#2147]
I wanted to know that there is any option to connect REST api and grab data from it for view in metatron-discovery dashboard ?

**Comment by ufoscw** [comment]
Currently, this feature is not supported.
To visualize data through the dashboard, only the data loaded on the metatron-engine is available.
Data loading on the engine is possible with the following data.
<img width="554" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/58522087-c5fc5900-81f9-11e9-8dbe-bcfffadec959.png">

**Comment by kaviranga** [comment]
@ufoscw Ah ,  I want to feed the realtime data stream through "rest api" and to monitor it via metatron-discovery dashboard. Waiting for it until it will be enabled in future versions :-)

**Comment by ufoscw** [comment]
@kaviranga 
I'll give you a link to a blog post related to real-time data analysis at metatron.
https://metatron.app/2018/08/02/visualize-real-time-data-with-metatron-discovery/

**Comment by kaviranga** [comment]
@ufoscw Thank you for the support . This is great . I'll try it by myself !
