### ISSUE TITLE
Need to improve control of table chart column width.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#2149]
**Is your feature request related to a problem? Please describe.**
- Depending on the pivot table settings, the width of the column may not be adjustable.

**Describe the solution you'd like**
- reproduce site : https://discovery.metatron.app/app/v2/workbook/3a4600a5-0a15-43bb-9c50-921bc650958e
- I want to adjust the column width in the image below but it is not adjusted.
![image](https://user-images.githubusercontent.com/612173/58523516-a0724e00-81ff-11e9-91fb-bed8f0fb6a3a.png)

**Comment by YooYoungmo** [comment]
머지된 이슈로 Close 합니다.
