### ISSUE TITLE
Improve 'All option' in filter in dashboard

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#2153]
필터 화면에서 All이라는 옵션은 사용자에게 다소 혼란의 여지가 있습니다.
필터 항목을 100개로 제한하는 상황에서 All의 의미가 100개의 선택을 의미하는지 또는 100개 이외의 모든 항목 선택을 의미하는지 모호합니다.

때문에 다음과 같이 상황을 정리하려 합니다.
@ All 선택의 의미 : 100개의 노출된 항목 전체 선택
@ 노출되지 않은 항목 포함한 전채 선택 상황 = 필터링 하지 않은 상황 = 전체 선택 해제 상태

위 정리사항에 맞춰 아래 화면처럼 개선하면 어떨까 합니다.
1_ 의미가 모호하던 All이라는 항목은 삭제되었습니다.
2_ 대신 '전체 선택(노출 항목 선택), 전체 해제' 라는 기능을 추가합니다.
3_ 전체 해제시 상단에 필터를 해제한 상태임을 알립니다.

이하는 개선 기획 화면입니다.

1_ 사용자의 다중 필터 위젯
![스크린샷 2019-05-29 오후 4 55 25](https://user-images.githubusercontent.com/42257766/58540222-e77a3680-8233-11e9-8675-6482289e9445.png)
.
.
2_ 사용자의 단일 필터 위젯
![스크린샷 2019-05-29 오후 4 55 31](https://user-images.githubusercontent.com/42257766/58540265-fa8d0680-8233-11e9-9e02-021253679292.png)
.
.
3_ 관리자의 다중 필터 패널
![스크린샷 2019-05-29 오후 4 55 36](https://user-images.githubusercontent.com/42257766/58540297-12fd2100-8234-11e9-9850-b446695338e4.png)
.
.
4_ 관리자의 단일 필터 패널
![스크린샷 2019-05-29 오후 4 55 41](https://user-images.githubusercontent.com/42257766/58540346-290ae180-8234-11e9-9f18-c5c7aafc2b81.png)
.
.
5_ 관리자의 다중 필터 설정 팝업
![스크린샷 2019-05-29 오후 4 55 45](https://user-images.githubusercontent.com/42257766/58540369-345e0d00-8234-11e9-9211-75b818424d62.png)
.
.
6_ 관리자의 단일 필터 설정 팝업
![스크린샷 2019-05-29 오후 4 55 50](https://user-images.githubusercontent.com/42257766/58540398-417afc00-8234-11e9-9918-758253168fea.png)

연결 이슈: #2045

**Comment by Taehui** [comment]
질문 있습니다. 
상황에 대한 가정은 아래와 같습니다.

사용자의 다중 필터 위젯에 값이 아래와 같이 있습니다.
- Value 1
- Value 2
둘다 값이 체크 되어 있고, 아래쪽에 있는 체크 기능(All/Checked)에서 All 에 되어 있는 상황
실제 드루이드에 들어가는 데이터에 Value 3 가 추가됨

>> 이 경우에 사용자의 다중 필터 위젯에서는 어떻게 동작하는 것이 맞나요? Value 3 이 추가된 상태로 체크가 되어 있어야 맞을까요? 저도 뭐 답이 있어서는 아니고,이 상황에 대한 고려가 없어 보여서 문의 드려요 ^^

**Comment by deidera08** [comment]
@Taehui 
상황을 제가 완벽하게 이해하지 못했습니다.
(하단의 'All' 체크 기능은 유저가 선택한 항목만 모아보는 기능입니다.)

추측하여 몇가지 상황에 대해 풀어보겠습니다.

상황1
a_ 원 데이터는 Value1, Value2, Value3 3개의 항목이나 관리자가 Value1, Value2 2개의 항목만 show 시켜놓은 상황
b_ 사용자는 Value1, Value2를 전부 checked한 상태이며 Value3 는 사용자에게 노출되지 않은 상태
= 위 상황에서 데이터는 Value1, Value2에 대한 필터가 걸려있는 상황이여야 합니다.
.
c_ 사용자가 Value3을 검색해서 check하는 경우(임의필터로 사용하는 경우)
= 위 상황에서 데이터는 Value1, Value2, Value3에 대한 필터가 걸려있는 상황이여야 합니다.
= 임의필터는 화면이탈시 휘발됩니다.(재사용 하기위해서는 다시 위의 절차 밟아야 함)
.
.
상황2
a_ 원 데이터는 Value1, Value2  2개의 항목이고, 관리자가 Value1, Value2 모든 항목만 show 시켜놓은 상황
b_ 사용자가 사용자는 Value1, Value2를 전부 checked한 상태이며 데이터 또한  Value1, Value2에 대한 필터가 걸려있는 상황
c_ 추가 적재(데이터 업데이트)로 의해 Value3이 추가됨
= 위 상황에서 실시간으로 Value3이 즉각 관리자나 사용자에게 노출되지 않습니다.
Value3은 관리자에 의해 Show/Hide설정이 이뤄지고 이후 사용자에게 비/노출 됩니다.
.
.
상황3
a_ 원 데이터는 Value1, Value2, Value3 3개의 항목이고 관리자가 모든 Value1, Value2, Value3 항목을 show 시켜놓은 상황
b_ 사용자 위젯에는 Value1, Value2가 checked되어 있고 2페이지에 Value3가 존재하는 상황
c_ 사용자가 상단에 'Select all'을 클릭
= 위 상황에서 페이지밖에 있더라도 모든 항목이 checked되어야 합니다. 즉 Value1, Value2, Value3이 checked되며 데이터에 모든 필터가 걸려있는 상황이여야 합니다.

제가 이해하지 못한 상황이라면 다시한번 상세히 부탁드리겠습니다.

**Comment by Taehui** [comment]
상황 설명 이해됐습니다. 이 이슈 기획은 완료 된 것 인가요?

**Comment by AnnieHwang** [comment]
@Taehui 완료된 기획안입니다. 기획은 완료해 두긴 했는데.. 개발일정은 아직 안 잡힌것 같습니다.

**Comment by Taehui** [comment]
다른 분께 Assign 된 상황이 아니라면, @YooYoungmo 님께서 검토/구현하셔도 되나요?

**Comment by kyungtaak** [comment]
@YooYoungmo 님 잘부탁드립니다. ^^;

**Comment by YooYoungmo** [comment]
@AnnieHwang @kyungtaak 마크업은 어떻게 전달 받으면 되나요?

**Comment by YooYoungmo** [comment]
@deidera08 질문 있습니다. 대시보드 필터에 보면 (All|selected) 스위치가 존재하는데요. 이건 사용자가 제어할 수 없는 건가요?
![image](https://user-images.githubusercontent.com/16472109/59411325-f34e2700-8df5-11e9-9b3c-c0bec12a7616.png)

**Comment by deidera08** [comment]
@YooYoungmo @AnnieHwang 
> 대시보드 필터에 보면 (All|selected) 스위치가 존재하는데요. 이건 사용자가 제어할 수 없는 건가요?

제어할 수 있습니다.
대시보드에 노출되는 필터를 저희는 위젯이라고 부르고 있는데요
필터 위젯에 노출되는 기능은 사용자가 전부 사용할 수 있습니다.

단, 사용자는 필터 설정 팝업이나 필터 패널은 기능 사용 뿐 아니라 접근할 수 없습니다.(관리자만 가능)

**Comment by YooYoungmo** [comment]
@deidera08 그럼 다시 질문 드리겠습니다. 
아래 '선택 항목만 보기'는 사용자가 항목(Value 가나다)은 선택 하고 나서  스위치를 selected 로 바꾸었을 때 결과 화면인가요?
![image](https://user-images.githubusercontent.com/16472109/59415838-3b257c00-8dff-11e9-845f-f6f09b47961d.png)

**Comment by deidera08** [comment]
@YooYoungmo @AnnieHwang 
>아래 '선택 항목만 보기'는 사용자가 항목(Value 가나다)은 선택 하고 나서 스위치를 selected 로 바꾸었을 때 결과 화면인가요?

네 맞습니다. 하단의 All기능은 사용자가 선택한 항목만 모아서 보여주는 기능입니다.
예시의 화면은 단일 선택(Radio)이기 때문에 결과적으로 1개만 노출되겠습니다만,
다중선택이며, 여러 페이지에 산개하여 다수의 항목이 선택되어 있을 경우 유용하게 사용되기를 기대하고 있습니다.

**Comment by YooYoungmo** [comment]
@deidera08 네 이해 했습니다. 답변 감사합니다.

**Comment by YooYoungmo** [comment]
@deidera08 혹시 slack 채널에 join해 있으신가요? join 하셨으면 아이디 알려 주시면 좋겠습니다.

**Comment by YooYoungmo** [comment]
@deidera08 @AnnieHwang 
현재 master 기준으로 보면 
필터 추가/수정 화면에서는 1000개를 제한하여 보여줍니다.
![image](https://user-images.githubusercontent.com/16472109/59586001-cca52e80-911c-11e9-8e4f-698957348cb3.png)

하지만 필터 패널과 필터 위젯은 100개로 제한하여 보여줍니다.
* 필터 패널
![image](https://user-images.githubusercontent.com/16472109/59586060-f0687480-911c-11e9-8f74-a44dcc8c4e05.png)
* 필터 위젯
![image](https://user-images.githubusercontent.com/16472109/59586073-f8c0af80-911c-11e9-9f1e-0ad7962b8f36.png)

제 예상으로 이렇게 만든 것이 필터 위젯을 목록형하게 되면 항목 값을 모두 노출하게 되는데 1000개의 경우 너무 많아서 100개로 제한 한것 같은데요.
![image](https://user-images.githubusercontent.com/16472109/59586162-358ca680-911d-11e9-838e-6a1b095f629f.png)

이렇게 일관성이 깨지는 부분은 현재 master 기준으로 진행 하면 되나요?
아니면 모두 1000개, 혹은 100개 통일하면 되나요?

**Comment by AnnieHwang** [comment]
@YooYoungmo #2229번 이슈를 못보셨군요. 검색은 일관성있게 100개로 바뀌었고요. 사용자가 100개 이상으로 검색 포함 항목을 추가시 최대 1000개까지 추가가 가능해요(보임설정) @deidera08 연임님이 6월달부터 이제 기획 안하셔서 저한테 여쭤보셨어야 했는데 ㅠㅠ

**Comment by YooYoungmo** [comment]
@AnnieHwang 네 알겠습니다.

**Comment by koeun222** [comment]
@AnnieHwang 필터 패널 & 팝업 디자인 공유드립니다- 
필터 >  패널 (대시보드 편집)
![image](https://user-images.githubusercontent.com/42256760/60004908-75690600-96a8-11e9-9cb3-a7f2c1bdf91a.png)

필터 > 팝업 
![image](https://user-images.githubusercontent.com/42256760/60004978-9b8ea600-96a8-11e9-8763-0545d4c2a502.png)

**Comment by AnnieHwang** [comment]
@YooYoungmo 디자인이 잘 반영이 안되서 다시 디자인 해서 올려요. 반영부탁드립니다.

**Comment by koeun222** [comment]
퍼블작업 완료되었습니다

**Comment by YooYoungmo** [comment]
@koeun222 
https://gitlab.com/bliex/html/2018 리파지토리 metatron 브랜치를 확인했는데
위에서 언급하신 화면하고 다릅니다.
![image](https://user-images.githubusercontent.com/16472109/60157284-5b0a6600-9829-11e9-89e5-5835b7e0cb2e.png)

**Comment by koeun222** [comment]
@YooYoungmo 퍼블 재작업이 필요해서 작업 후 방금 완료했습니다-

**Comment by YooYoungmo** [comment]
@koeun222 확인했습니다.
기획서에 있는 필터 위젯은 어디서 확인할 수 있나요?(파일명으로 알려주세요)
![image](https://user-images.githubusercontent.com/16472109/60241359-172d6480-98ee-11e9-8714-40d27d4a23bf.png)

**Comment by koeun222** [comment]
@YooYoungmo 02_워크북_02대시보드_02열람 // 에서 확인부탁드립니다 
![image (13)](https://user-images.githubusercontent.com/42256760/60243116-71c8bf80-98f2-11e9-977d-e5f663afa3c0.png)

**Comment by YooYoungmo** [comment]
@koeun222 확인 했습니다. 그런데 페이징 요소하고 선택한 값만 보여주는 버튼은 빠져 있는데. 확인 부탁 드립니다.
![image](https://user-images.githubusercontent.com/16472109/60243384-13501100-98f3-11e9-8661-10fadf66787f.png)

**Comment by koeun222** [comment]
@YooYoungmo 셀렉트박스 열면 안에 있습니다- 리스트형인경우 빨간박스부분이 기획상에도 없어서 동일하게 넣는게 맞는지 @AnnieHwang 확인부탁드립니다-
![image](https://user-images.githubusercontent.com/42256760/60311120-cc185d80-9990-11e9-8d41-bf697336da5b.png)

**Comment by YooYoungmo** [comment]
@koeun222 네. 확인했습니다. 감사합니다.

**Comment by AnnieHwang** [comment]
@koeun222 @YooYoungmo 필터 위젯 안에 리스트에는 하단 버튼이 없어요~
