### ISSUE TITLE
Add seq number to new datasets named duplicated

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#2156]
**Describe the bug**
When I click "Generate new dataset" with I.DS or "Clone dataset" with W.DS, the new name had had a seqno at the end, but now that feature has gone.

**To Reproduce**
1. Import & wrangle [a.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3235420/a.csv.txt)
2. Click "Generate new dataset" with I.DS -> exact same name comes out
3. Click "Clone dataset" with W.DS via context menu -> exact same name comes out

**Expected behavior**
(1), (2), ... should be attached at the end of the new name.

**Screenshots**
<img width="363" alt="스크린샷 2019-05-30 오후 1 25 48" src="https://user-images.githubusercontent.com/42257727/58608477-b30f8480-82de-11e9-8793-6bdc4eff9ab9.png">

**Additional context**
I work very well. Look for some fault in conflict resolves.

**Comment by joohokim1** [comment]
Now (3.3.0-rc2) it works properly. It could probably be the source conflict. Closing.

**Comment by joohokim1** [comment]
Tested /w 3.3.0-rc2.
"Clone dataet" works. (Added (1), (2), etc.)
"Generate new dataset **DOES NOT WORK** (generates duplicate-named datasets)

Reopening.

**Comment by brandon-wonjune** [comment]
@joohokim1 혹시 이 이슈는 UI에서 처리를 해야되나요?

**Comment by joohokim1** [comment]
@ksparknot 
We need to check if this issue still remains.
I think I've seen there's no problem anymore.

**Comment by ksparknot** [comment]
#2705 issue is the same
Please close this issue after the issue has been resolved.

**Comment by ksparknot** [comment]
duplicated close
