### ISSUE TITLE
Calculation field disappears when copying a dashboard that contains calculation fields

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#216]
**Describe the bug**
계산식 필드가 들어있는 대시보드를 복제하면 계산식 필드가 사라짐

**To Reproduce**
1. 계산식 필드를 생성함 (ex. 'ay_new', 'ay_test')
2. 차트를 그림
3. 대시보드를 복제함
4. 차트 상세에 들어가서 계산식 필드를 확인함. 찾을 수 없음

**Screenshots**
![2018-09-14_13-24-54](https://user-images.githubusercontent.com/6300003/45529778-ee862380-b821-11e8-8ebd-b14390779a8c.gif)

**Additional context**
복제된 대시보드 안 차트에서 계산식 필드를 동일한 이름으로 만들 경우, 이미 존재하는 계산식 필드라고 나오는 것으로 봐서.. Hide되어 있는것 같습니다.

**Comment by kyungtaak** [comment]
@eltriny 복사 기능은 계산식으로 위해서라도  자주사용하는 기능으로 알고 있습니다. 해당 버그도 우선순위를 높여주세요.

**Comment by eltriny** [comment]
@kyungtaak 
현재 대시보드 복사 기능은 제공해주신 API 를 호출하는 것으로 처리하고 있습니다. 
서버영역에서 확인 부탁드립니다.

**Comment by kyungtaak** [comment]
@eltriny 여태 속성명을 customFields 로 하고 계셨네요. **"userDefinedFields" 라는 속성명으로 하셔야합니다.** 
복사할때 서버측에서 관리하는 스펙 도메인으로 변환후 위젯 ID 를 교체하는 작업이 있는데요. 이때  customFields 무시하게 되어 발생한 것으로 보입니다.
