### ISSUE TITLE
Enhance displaying the resources associated with the item in the workspace

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2167]
**Is your feature request related to a problem? Please describe.**
Adding Permission Control UI in Workspaces
- Add warning text when deleting a data source
- Add warning statement when deleting notebook server
- Added warnings when DB connection is deleted

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/6300003/58687395-7023de80-83bc-11e9-868d-522ce59a9969.png)

**Comment by AnnieHwang** [comment]
@koeun222 Workbook, Workbench, Notebook 3개 타일 하단의 영역 디자인을 일관성 있게 맞춰주세요

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다-
- 하단타일 배경 bg #eeeeee / opacity 50%
- workbench 하단타일 수정
- error icon 추가 (hover시 에러문구는 브라우저툴팁처리 부탁드립니다)
![image](https://user-images.githubusercontent.com/42256760/59254856-f1f0f300-8c6b-11e9-9ac6-28223640f45c.png)

**Comment by AnnieHwang** [comment]
@koeun222 내용이 좀 수정된 부분이 있어서 한번더 디자인 재 작업 부탁드려요
- Notebook 의 서버명 표시와 상태 표시, Notebook 정보 나열 순서 변경
- Notebook과 Workbench의 서버를 사용할 수 없을때 진입 제한을 나타내는 background 색 변경
![image](https://user-images.githubusercontent.com/6300003/59492233-7d17f600-8ec3-11e9-81c2-c605a84bcb3e.png)
![image](https://user-images.githubusercontent.com/6300003/59492255-8d2fd580-8ec3-11e9-9781-e87fdfa07499.png)
[[M-Core]WF-C1-Workspace-v0.11-20190614.pdf](https://github.com/metatron-app/metatron-discovery/files/3289540/M-Core.WF-C1-Workspace-v0.11-20190614.pdf)

**Comment by AnnieHwang** [comment]
@minhyun2 @kyungtaak 레이블명이 변경이 있습니다. 아래 기획안을 참고 부탁드립니다. 이상하시면 말씀부탁드려요!
![image](https://user-images.githubusercontent.com/6300003/59662623-4d7d2c80-91e8-11e9-8dd5-59f69bb7193e.png)

1.워크북
(영어) Unauthorized. Please check the publish permission of the datasource (2/5).
(한글) 데이터소스(2/5)의 Publish 권한을 체크하세요.
2.노트북
(영어) Unauthorized. Please check the permission of the notebook server.
(한글) 노트북 서버의 권한을 체크하세요.
3.워크벤치
(영어) Unauthorized. Please check the publish permission of the data connection.
(한글) 데이터 커넥션의 Publish 권한을 체크하세요.

**Comment by koeun222** [comment]
@AnnieHwang 노트북 타일 수정 / 워크벤치&노트북 진입불가 dim처리 수정했습니다

- grid
![image](https://user-images.githubusercontent.com/42256760/59900041-ddfa7d80-9431-11e9-8d3d-ee551d9669f1.png)

- list
![image](https://user-images.githubusercontent.com/42256760/59900074-f36fa780-9431-11e9-95cf-3315dcc7bf64.png)
