### ISSUE TITLE
Is there any ability to use three map layers in metatron-discovery maps ?

### ISSUE THREAD

**Issue by kaviranga** [metatron-app/metatron-discovery#2169]
Is there any ability to use three map layers in metatron-discovery maps . I have used two map layers with the generated analysis map layer. Without that any possibility of adding third map layer . Here I have used following data set and I want to plot like a map as in following figure(s)

![Screenshot_2019-05-31_12-12-01](https://user-images.githubusercontent.com/6471174/58694113-dd7d4280-83af-11e9-8eaa-9bb59962aa3c.png)

This figure is from old metatron-driud documentation

![Screenshot_2019-05-31_12-07-53](https://user-images.githubusercontent.com/6471174/58689568-01875680-83a5-11e9-8f47-3d4060ea61af.png)
 
Here I'm using metatron-discovery version 3.2.1

**Comment by kaviranga** [comment]
I've see three map layers on this article's test screen. But default metatron-discovery supports only two layers. How to enable this feature ?

**Comment by kyungtaak** [comment]
@kaviranga 
Currently, the function definition for the third layer has changed as bellow reason.
First, We thought that overlapping three layers can be visually complex and can lead to performance issues.
Second, we wanted to provide an area for geospatial analysis. You can refer to this link: https://metatron.app/2019/05/02/building-a-simple-map-view/

**Comment by kaviranga** [comment]
@kyungtaak Thanks for the valuable info . Can I enable this feature by editing any configuration in appropriate config file or switching to an old version?

**Comment by kyungtaak** [comment]
@kaviranga I'm sorry that it's too many changes to switch version. Is there a lot of usability of the three layers? It seems very difficult to provide this at the current level. But, we will consider how to add the more layer internally.

**Comment by kaviranga** [comment]
@kyungtaak Ah , Yes I want to use three layers for specific purpose . But newer version 3.2.3 has limitations up to two layers . Ok I'll  experiment and try my best to solve the requirement by using only two layers.

**Comment by kaviranga** [comment]
@kyungtaak Thanks for the great support , Issue solved in another way :-) !

**Comment by kyungtaak** [comment]
@kaviranga I would rather thank you for using ours. :)
If you have any questions or want to suggest something, do not hesitate to tell me.
