### ISSUE TITLE
Initialize selection value when selecting notebook server in workspace

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2170]
**Describe the bug**
Initialize selection value when selecting notebook server in workspace
워크스페이스 내의 노트북 서버 선택 시 라디오버튼의 선택 해제 기능이 없어 버그가 발생됨

**To Reproduce**
Workspace > More button > Set Notebook Server > Selection

**Expected behavior**
마지막 라디오버튼을 선택한 값이 있으면 이전 라디오버튼 선택된 값이 선택되지 말아야 함(아무리 탭이 나눠져 있더라도..)

아래의 동영상에서 마지막에 Jupyter의 'jupyter-default'를 선택하면, 이전 선택 값인 Zeppelin의 'Zeppelin Dev'은 선택이 되지 말아야 함 => 그래야 결론적으로 하나의 선택값으로 저장이 가능함

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/58695940-82f4de00-83d1-11e9-95cb-7f7679f30dd4.png)
![2019-05-31_18-24-13](https://user-images.githubusercontent.com/6300003/58695959-93a55400-83d1-11e9-8a24-ac44e1ceccf2.gif)

**Comment by kyungtaak** [comment]
@AnnieHwang I think you should consider the function definition. Why should only one laptop server be available?

**Comment by AnnieHwang** [comment]
@kyungtaak Both Zeppelin and Jupyter can be selected ,which is what i want. I thought It is so difficult to develop to select both. If Zeppelin and Jupyter can be selected both, it should work like now (but without errors).

**Comment by AnnieHwang** [comment]
오늘 회의 결과를 정리하면 아래와 같습니다.
- 노트북 서버는 종류별로 각각 1개씩 고를수 있음 (Jupyter 1개, Zeppelin 1개)
해당 내용으로 추가 기획 진행하도록 하겠습니다.

**Comment by AnnieHwang** [comment]
@koeun222 라디오박스 상단에 Deselection 버튼 디자인 부탁드려요 (해당 부분은 필터 위젯 - 라디오 형과 동일한 UI이면 될것 같아요)
![image](https://user-images.githubusercontent.com/6300003/59497138-cc632400-8ecd-11e9-825c-847e14b873b5.png)

**Comment by koeun222** [comment]
@AnnieHwang "deselect" 버튼 추가했습니다- 
![image](https://user-images.githubusercontent.com/42256760/59835526-c31dff80-9384-11e9-81d8-ebb98f70f561.png)

**Comment by minhyun2** [comment]
![image](https://user-images.githubusercontent.com/45194478/61613514-7b98d500-ac9c-11e9-99ef-5ecfc5eb1e4b.png)

Changed to select (None) at the top of list instead of 'Deselect' button
