### ISSUE TITLE
limit is not support in oracle

### ISSUE THREAD

**Issue by gflp123** [metatron-app/metatron-discovery#2177]
Describe the bug
DB connection with oracle，But execute dataset collect error. For detail
ORA-00933: SQL command not properly ended
![image](https://user-images.githubusercontent.com/17872549/58795026-322cf180-862c-11e9-9a7b-641de5a0e55b.png)

**limit is not support in oracle**

String pattern = ".*limit\\p{Space}+[0-9]+\\p{Space}*$";
            Pattern p = Pattern.compile(pattern);
            Matcher m = p.matcher(queryStmt.toLowerCase());
            if(true==m.matches()) {
                sql = queryStmt;
            } else {
                sql = queryStmt + " LIMIT " + size;
            }
        } else {
            sql = "SELECT * FROM " + tblName + " LIMIT " + size;
        }

Desktop (please complete the following information):

OS: [linux]
Browser [chrome]
Version [3.2.3]
Additional context

**Comment by alchan-lee** [comment]
Hi, @gflp123 
It seems to be your query statements in the extension module are not compatible with Oracle, it's not related 'limit' statement.

I will check your query with my mates and will reply soon.

Thanks.

**Comment by ufoscw** [comment]
@gflp123 
We have the oracle jdbc extension source that we created.
In the meantime, I was not raising the source for distribution license issues, but I'm going to push this time.
I'll show you the branch with the source.
To build it, see the maven repository guide.

https://github.com/metatron-app/metatron-discovery/tree/f%232177-add_oracle_extension/discovery-extensions/oracle-connection

Let me know if you have any questions.

**Comment by gflp123** [comment]
[oracle-connection-1.0.0-7.3.0.zip](https://github.com/metatron-app/metatron-discovery/files/3251435/oracle-connection-1.0.0-7.3.0.zip)

Thanks reply，The bug is not  solve.
Debug in my  environment，It error in PrepDatasetDatabaseService_getPreviewLinesFromJdbcForDataFrame.
I am use oracle 11g,limit is not support.



http://localhost:8180/api/preparationdatasets/cb18af76-8b37-4ef3-b205-8211e995b835

![image](https://user-images.githubusercontent.com/17872549/58866270-d2e1e680-86ea-11e9-816f-8278875b7406.png)



   Oracle version 11g
   <dependencies>
        
        <dependency>
        <groupId>com.oracle</groupId>
        <artifactId>ojdbc6</artifactId>
        <version>11.2.0</version>
    </dependency>

**Comment by ufoscw** [comment]
@gflp123 
I thought you were a question about the workbench, but that was a question related to Preparation.
I think it 's a bug.
I'll send it to the person in charge and fix it.

**Comment by joohokim1** [comment]
@gflp123 @ufoscw @alchan-lee Yes. It's a bug. I'll fix it as soon as possible.
Besides, if the query for dataset already contains "limit n", then it fails too. I'll fix this too.
