### ISSUE TITLE
'Series Percent' needs to be modified so that the sum of the bar charts is 100 percent.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#2184]
**Describe the bug**
- In the below screenshot,
![image](https://user-images.githubusercontent.com/612173/58934633-003f9a80-87a6-11e9-94f0-a6dbada8566e.png)
- The sum of the values ​​of Series Percent is expressed by category.
- The value must be expressed as a series reference of the stacked bar in the expression

**To Reproduce**
1. Go to,
 https://discovery.metatron.app/app/v2/workbook/3fe834cb-41ad-4f4e-ab95-86e5902c3d54

**Comment by AnnieHwang** [comment]
I think it's a chart bug. Sorry about that. The contents of the plan are defined as below. Check it please. We will try solve this issue as soon as possible. Thanks :)
![image](https://user-images.githubusercontent.com/6300003/58946520-05f6a980-87c1-11e9-84f6-275eb5a0a6b1.png)
![image](https://user-images.githubusercontent.com/6300003/58946531-0b53f400-87c1-11e9-9f81-799cb71f1b69.png)
