### ISSUE TITLE
Using ApacheArrow for DataFrame

### ISSUE THREAD

**Issue by Praveen2112** [metatron-app/metatron-discovery#2196]
Hi, I was checking Metatron's source code and there we have a `Row` which maintains the data (Please correct me If I am wrong) Can we use Apache arrow to represent the underlying data of DataFrame/Row ? 

Any specific reason why do we maintain the data in memory and apply the transformations via DataFrame instead of applying them directly on Druid query ?

**Comment by kyungtaak** [comment]
> Any specific reason why do we maintain the data in memory and apply the transformations via DataFrame instead of applying them directly on Druid query?

This is not true. We are doing the query operation in the druid as much as possible and only process the necessary transformations on the UI.

> Can we use Apache arrow to represent the underlying data of DataFrame/Row ?

Actually, I don't know well about "Apache arrow". However, as mentioned above, We do not feel the need for this because most operations rely on the druid.

**Comment by Praveen2112** [comment]
@kyungtaak Thnaks..will close this issue
