### ISSUE TITLE
Add "maximum categories" property for pie chart

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#22]
**Is your feature request related to a problem? Please describe.**
파이차트 내에서 표시할 항목이 많아 질경우 기존에는 2% 미만의 항목은 "other" 처리를 진행하였으나, 이에 대한 기준이 모호하여 개선이 필요합니다. 

**Describe the solution you'd like**
기본은 모두 표시하는 것으로 하고, 사용자가 최대 표시할 개수를 지정하는 방향으로 진행합니다.
![image](https://user-images.githubusercontent.com/822255/44078349-31cefd96-9fe1-11e8-97c4-2524917b8936.png)

**Describe alternatives you've considered**
<N/A>

**Additional context**
<N/A>

**Comment by kyungtaak** [comment]
@eltriny branch 생성 후, 스펙 추가하도록 하겠습니다.

**Comment by kyungtaak** [comment]
f#22-add_max_category_property 브랜치를 추가하였고,  아래와 같이 속성을 추가하였습니다.
```
{
  "type": "pie",
  ...,
  "maxCategory": 10,
  ...
}
```

**Comment by kyungtaak** [comment]
@metatron-app/design  데이터 정렬순으로 지정하는 의미에 대해 재검토가 필요합니다. Ascending 으로 지정시에는   사이즈가 큰 부분이 "other" 영역으로 가버려 other 가 무척 커져 버립니다. #31 Pull Request 예시 사례 참고 바랍니다.

**Comment by kyungtaak** [comment]
@AnnieHwang 향후 measure 를 여러개 지원 하는 것은 여러모로 기능 제약이 생길수 있을것 같습니다. 해당 부분에 대한 추가 검토 부탁드립니다.

**Comment by AnnieHwang** [comment]
@kyungtaak 파이차트에 대해서 1 measure and 1 dimension으로 변경하기로 하겠습니다. 따라서 위의 내용을 다시 정리하면 아래와 같습니다.( 관련 프로젝트들에 확인결과 measure를 통한 분할을 사용하는 케이스가 없는 것으로 확인하였습니다.)
1.ascending ordering은 기존 대로 허용하도록 함
2.chart 생성 룰을 1 measure and 1 dimension로 변경 (향후 chart split 기능 추가시 multi measures and multi dimensions 구현예정임)

@esezin 기획서 상에 pie chart rule을 1 measure and 1 dimension로 변경해주시고, 선반의 가이드 변경 요청드립니다.

**Comment by kyungtaak** [comment]
@AnnieHwang 피드백 감사드립니다.
@judy-exntu @DAVE-EXNTU 위 기획 검토내용 확인해주시고 개발진행 부탁드립니다.
