### ISSUE TITLE
Logical type isn't displayed on metadata tooltip in Dashboard

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#221]
**Describe the bug**
대시보드 편집 화면에서 메타데이터 정보가뜨는 툴팁 내에 논리타입 정보가 표시되지 않음

**To Reproduce**
1. Go to Dashboard
2. Add new chart
3. Click on measure's ... menu for open metadata tooltip

**Expected behavior**
메타데이터에서 설정한 컬럼의 논리타입이 대시보드 편집화면의 툴팁에도 정상적으로 보여야 함

**Screenshots**
<img width="1406" alt="mdm-error-02" src="https://user-images.githubusercontent.com/28751002/45535200-a292a900-b838-11e8-9d66-97081a3c937c.png">
<img width="1401" alt="mdm-error-01" src="https://user-images.githubusercontent.com/28751002/45535202-a292a900-b838-11e8-8de9-701229c31879.png">

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: chrome
 - Version: 64

**Additional context**

**Comment by eltriny** [comment]
@ecoloy @kyungtaak 
현재 저희쪽에서는 재현이 되지 않고 있습니다...
다시 한번 확인 부탁드립니다.

**Comment by ecoloy** [comment]
@eltriny @kyungtaak @AnnieHwang 
제가 본 이슈를 리포트할 시점에 테스트한 사이트는 Tango 쪽의 discovery 였습니다. 
그런데 방금 http://52.231.191.172:8080/app/v2/index.html 에서 테스트 했을때는 재현이 되지 않는것을 확인했습니다. 아마도 Tango 쪽에 최신 코드 업데이트가 이루어지면 해당 이슈는 해결될 것으로 보여집니다. 

다만 논리타입 표현식에 대해 아래 개선사항 의견이 있습니다.

현재 Timestamp, Integer 등의 타입인 경우에는 아래 스크린샷과 같이 fullname으로 표현하고 있는데
![2018-09-17 10 25 22](https://user-images.githubusercontent.com/28751002/45603179-62177300-ba64-11e8-8ab2-6b906204e5ca.png)
![2018-09-17 10 25 15](https://user-images.githubusercontent.com/28751002/45603180-62177300-ba64-11e8-9993-917955b35d35.png)

Longitude, Latitude 는 아래와 같이 약어로 표시하여 통일성이 떨어지고 빠르게 인식이 안됩니다. 특별한 이유가 없다면 이 두가지 타입도 fullname으로 표기해주는 것이 좋을것 같습니다. (그리고 부득이 하게 약어로 표현해야한다면 latitude의 약어를 LNT가 아니라 LAT로 표현해야 합니다.) 
![2018-09-17 10 25 09](https://user-images.githubusercontent.com/28751002/45603190-87a47c80-ba64-11e8-8db0-86bfa6099d27.png)
![2018-09-17 10 25 01](https://user-images.githubusercontent.com/28751002/45603191-87a47c80-ba64-11e8-9026-c632e1f7c498.png)

**Comment by kyungtaak** [comment]
@eltriny 이 이슈를 3.0.3 릴리즈에 처리할지 결정하여 진행 부탁드립니다.
