### ISSUE TITLE
Advanced Filter Widget List Search

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2229]
**Is your feature request related to a problem? Please describe.**
- Filter Widget search UI design progress
- Search UX Improvement
- Unification of 100 existing data limit to 1000

See the issue #2045 

**Describe the solution you'd like**
1. 필터 팝업
(Process : 1. 초기 서버에서는 100개를 준다. 2.Search all을 통해 보임 설정을 추가할 수 있다(1000개까지) 3. 필터 알럿에서 경고는 ’100개까지 보여진다’로 변경)
![image](https://user-images.githubusercontent.com/6300003/59325973-042c6900-8d20-11e9-80ac-8913837d4b18.png)

2. 필터 위젯 in Dashboard
하단 기획안 참조

**Describe alternatives you've considered**

**Additional context**

**Comment by AnnieHwang** [comment]
@koeun222 5월말 대시보드 내 필터위젯 검색 추가 기획이 완료된 후 디자인 작업이 진행이 안되서 요청드려요
![image](https://user-images.githubusercontent.com/6300003/59405849-e6760700-8de6-11e9-9261-d5ad86235cb2.png)
![image](https://user-images.githubusercontent.com/6300003/59405858-f4c42300-8de6-11e9-81e1-44fadb5997b2.png)
![image](https://user-images.githubusercontent.com/6300003/59405872-01e11200-8de7-11e9-8183-308f562f9258.png)
![image](https://user-images.githubusercontent.com/6300003/59405881-102f2e00-8de7-11e9-8ab0-5fc99c8ef5cf.png)
[[M-Core]WF-C3.4-Dashboard-Filter-190613.pdf](https://github.com/metatron-app/metatron-discovery/files/3284321/M-Core.WF-C3.4-Dashboard-Filter-190613.pdf)

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/59893302-7d5e4700-9417-11e9-8a36-f7a948118447.png)
![image](https://user-images.githubusercontent.com/42256760/59893308-83ecbe80-9417-11e9-88f3-91113cd4784d.png)
![image](https://user-images.githubusercontent.com/42256760/59893312-88b17280-9417-11e9-8219-8fcdd3819ef5.png)
![image](https://user-images.githubusercontent.com/42256760/59893324-8d762680-9417-11e9-94e5-d15c7d67ce5e.png)

**Comment by AnnieHwang** [comment]
@YooYoungmo 위의 디자인이 기획 변경된 내용 반영해서 그린거거든요. 위의 기획서는 무시하시고 디자인 대로 개발 진행부탁드려요~ 퍼블은 오늘 넘겼는데 나오는대로 다시 말씀드리겠습니다!

**Comment by YooYoungmo** [comment]
@AnnieHwang 네. 받은 마크업으로 #2153 도 동일하게 수정하면 되는 건가요?

**Comment by AnnieHwang** [comment]
@YooYoungmo 네~ 맞아요. 퍼블도 지금 완료되었다고 해요!

**Comment by libran-sub** [comment]
Do K forward this to Reddit

**Comment by libran-sub** [comment]
Do I forward it togoogle
