### ISSUE TITLE
The layout is broken when the logical column name is displayed in header of data grid

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#223]
**Describe the bug**
메타데이터가 있는 데이터소스를 대시보드에서 상세팝업에서 확인할때, 물리컬럼명 아래에 표시되는 논리컬럼명 영역이 레이아웃이 깨짐

**To Reproduce**
1. Go to Dashboard
2. Click on Datasource details

**Expected behavior**
메타데이터가 있는 데이터소스의 경우 디자인과 같이 레이아웃이 나와야 함

**Screenshots**
디자인
![metadata-header-design](https://user-images.githubusercontent.com/28751002/45536215-bbe92480-b83b-11e8-929c-c1c6b2da9bbe.png)

에러 스크린샷
<img width="1529" alt="2018-09-14 4 24 59" src="https://user-images.githubusercontent.com/28751002/45536246-d4593f00-b83b-11e8-94d9-87cd69f252cb.png">

**Desktop (please complete the following information):**
 - OS: MacOS high sierra
 - Browser: chrome
 - Version: 69

**Additional context**

**Comment by kyungtaak** [comment]
#209 이슈와 동일한 화면에서 발생하는 사항입니다. 
@eltriny 함께 확인 해주시고요. 이 이슈는 종료하겠습니다.
