### ISSUE TITLE
Too much space in dataset swap pop-up

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#2230]
**Is your feature request related to a problem? Please describe.**
![Too much space in dataset swap popup](https://user-images.githubusercontent.com/42257727/59328426-5329cc80-8d27-11e9-8a97-c09488115cdb.png)

**Describe the solution you'd like**
Enlarge the grid above the space.

**Describe alternatives you've considered**
Leave it.

**Additional context**
Reported while an integrated test on 6/11.

**Comment by ksparknot** [comment]
@eltriny 공통으로 쓰는 클래스로 box-preview 높이가 고정 설정되어 있는데 퍼블리시 확인 좀 해주세요
