### ISSUE TITLE
Add re-ingestion setting with file

### ISSUE THREAD

**Issue by minhyun2** [metatron-app/metatron-discovery#2239]
**Is your feature request related to a problem? Please describe.**
When you re-ingest datasource with file, you can not set data range in case of the specific timestamp column.

**Describe the solution you'd like**
Before confirming re-ingestion, check timestamp column and set data range.

**Describe alternatives you've considered**

**Additional context**

**Comment by AnnieHwang** [comment]
@koeun222 저번 스프린트에 진행한 내용 중에 디자인 적으로 추가할 내용이 있어 작업 부탁드려요 (#2178)
![image](https://user-images.githubusercontent.com/6300003/59495577-89538180-8eca-11e9-8c28-f6b3c30b1b02.png)
실제 디자인을 반영한 화면이 아래와 같이 나왔어요.
![image](https://user-images.githubusercontent.com/6300003/59495628-a8521380-8eca-11e9-924b-831cd21c9359.png)
생각보다 내용이 눈에 잘 안들어 오는데 화면의 크기를 좀 늘리거나, 첫줄 제외한 그 다음줄은 font크기를 회색으로 바꾸고 사이즈를 줄여주시면 어떤가요?

**Comment by koeun222** [comment]
@AnnieHwang 고급설정을 눌러서 열렸을때 가운데 정렬하면 팝업위치가 바뀌는게되다보니 기존 위치는 유지하고 아래로 열리도록 잡았습니다-

![image](https://user-images.githubusercontent.com/42256760/59924922-d3f86f00-9471-11e9-97c3-cd8b2d62f745.png)
![image](https://user-images.githubusercontent.com/42256760/59924949-df4b9a80-9471-11e9-952f-f106eac87793.png)

**Comment by AnnieHwang** [comment]
@minhyun2 팝업의 가로 사이즈는 공통사이즈라 유지하고 타이틀 줄바꿈과 고급설정버튼을 우측으로 옮겨 재 디자인했습니다. 오늘 퍼블 넘길께요! @koeun222 퍼블 넘겨주세요~
![popup type e](https://user-images.githubusercontent.com/6300003/60073022-3d220000-975a-11e9-9044-48b198ce65dd.png)
![popup type e advanced](https://user-images.githubusercontent.com/6300003/60073028-414e1d80-975a-11e9-8585-8a24fd59ea5d.png)

**Comment by AnnieHwang** [comment]
@koeun222 화면이 좀 변경되어야 할것 같아요. 
![image](https://user-images.githubusercontent.com/6300003/60145821-38188b80-9802-11e9-8118-858fcfde6c93.png)

**Comment by koeun222** [comment]
@AnnieHwang 수정된 화면 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/60240301-7b9af480-98eb-11e9-92a5-b90972e04428.png)
