### ISSUE TITLE
In dataflows no other join type besides an inner join works

### ISSUE THREAD

**Issue by siepkes** [metatron-app/metatron-discovery#2241]
**Describe the bug**

Creating a join in a dataflow always seems to be an inner join regardless of the join type you select. For example if you select a left join you still get an inner join.

**To Reproduce**

Create 2 datasets and import them in a data flow. For example datasets A and B:

**Dataset A:**

| id | name    |
|----|---------|
| 1  | Pete    |
| 2  | John    |
| 3  | Carry   |
| 4  | Jenkins |

**Dataset B** (Same ID's as dataset A only there is no record with ID `4`):

| id | occupation       |
|----|------------------|
| 1  | Farmer           |
| 2  | Electrician      |
| 3  | Rocket scientist |
| 5  | Teacher          |

When selecting dataset A in the dataflow window and creating a left join on the ID column on dataset B I expect the following result:

| id | name    | occupation       |
|----|---------|------------------|
| 1  | Pete    | Farmer           |
| 2  | John    | Electrician      |
| 3  | Carry   | Rocket scientist |
| 4  | Jenkins |                  |

However the actual result is:

| id | name    | occupation       |
|----|---------|------------------|
| 1  | Pete    | Farmer           |
| 2  | John    | Electrician      |
| 3  | Carry   | Rocket scientist |

**Screenshots**

Select left join:

![select_join](https://user-images.githubusercontent.com/1428678/59569298-a71a1580-9087-11e9-9d0d-b2a3e2dd5182.png)

Result (an inner join):

![results](https://user-images.githubusercontent.com/1428678/59569302-ada88d00-9087-11e9-8b86-56d15484f2f2.png)

**Desktop:**
 - OS: CentOS Linux
 - Browser Chrome 75.0.3770.80 (latest at time of writing)
 - Version 3.2.4 (latest at time of writing)

**Comment by teamsprint** [comment]
Thank you for your sincere report.

Actually, joins other than inner join were low priority, but I’ve found out it is but that difficult.

Besides, recently I’ve changed the join code to remove potential bugs and speed up, so this is the right time to support all the join types that are shown in the join pop-up window.

I’ll finish this task by the end of June.
Thanks for your help and interest!

**Comment by joohokim1** [comment]
Thank you for your sincere report.

Actually, joins other than inner join were low priority, but I’ve found out it is but that difficult.

Besides, recently I’ve changed the join code to remove potential bugs and speed up, so this is the right time to support all the join types that are shown in the join pop-up window.

I’ll finish this task by the end of June.
Thanks for your help and interest!

**Comment by siepkes** [comment]
That's great to hear! Let me know if I can help.

**Comment by joohokim1** [comment]
@siepkes I've made a PR for this issue (https://github.com/metatron-app/metatron-discovery/pull/2255)
I'll be grateful if you double check it (at code level or UI level any).
Some minor UI issues have been reported, but they will be resolved soon.

**Comment by siepkes** [comment]
Great to hear! I'll take a look at it coming Friday (today and tomorrow I'm on the road).

**Comment by siepkes** [comment]
@joohokim1 I had some time to spare today and looked at the PR. I created a built based on master and the PR and did some basic tests with left, right and outer joins; It all seems to work fine and as expected!

I'm not really familiar with the inner workings with Metatron so commenting on the implementation itself is somewhat harder for me. However I skimmed over the code in the PR and it looked good to me!

Thanks for your speedy reaction!

**Comment by joohokim1** [comment]
All comments about lineage above are my mistake.

**Comment by joohokim1** [comment]
Works done.

**Comment by joohokim1** [comment]
Integrated test #1 passed.
A wrong patch has been made in this branch, but this will be fixed very soon by another PR.
Above problem is not related with this issue's essential.
