### ISSUE TITLE
Validation is disabled when a column dictionary of type timestamp is connected.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2242]
**Describe the bug**
Validation is disabled when a column dictionary of type timestamp is connected.
Users can not save changes because they can not validate check.

<img width="1307" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/59571476-2f2c0980-90e0-11e9-8f58-3197bfe78a7e.png">

**To Reproduce**
1. Create timestamp type column dictionary.
2. Go to Metadata detail screen of DataSource (Engine) type.
3. Column Schema Tab
4. apply TimeStamp Column Dictionary.
5. Save
6. see error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ufoscw** [comment]
@AnnieHwang 
In the case of a Timestamp type column dictionary, it is necessary to define in which step the Validation Check will be executed.
1. After selecting Column Dictionary
2. Save your edits

**Comment by AnnieHwang** [comment]
@ufoscw Please check to the UX Wireframe below :)
![image (75)](https://user-images.githubusercontent.com/6300003/59581475-fc016e80-910f-11e9-90b5-66b5a8ee3a45.png)

**Comment by ufoscw** [comment]
@eltriny 
위 기획서 중 Dictionary 추천 정책을 제외한 나머지 부분에 대해 적용 부탁드려요.

**Comment by paigechoi** [comment]
![image](https://user-images.githubusercontent.com/42233517/59903209-59146180-943b-11e9-82f7-652507b51ae5.png)

@AnnieHwang @ufoscw 데이터 소스에서 geo types는 타입을 수정하지 못하도록 정책이 잡혀있습니다.

위에 올려주신 기획서에는 geo types 관련 룰은 정의해주시지 않으셨는데요. 칼럼 딕셔너리를 적용했을 때 geo types도 칼럼 딕셔너리 타입에 맞춰서 수정되는 게 맞는지 확인 부탁 드닙니다.
![image](https://user-images.githubusercontent.com/42233517/59903285-8eb94a80-943b-11e9-859e-b082b60ed641.png)

**Comment by ufoscw** [comment]
@kyungtaak 
위 내용 관련해서 Geo Type의 경우 타입 수정이 안되게 기존 로직이 만들어져 있다고 합니다.
컬럼 딕셔너리 적용될 경우 타입이 바뀌는게 기획상으로 맞다고 하는데 이럴 경우 문제가 있나요?

**Comment by kyungtaak** [comment]
@ufoscw 문제가 있습니다. GeoType의 경우 컬럼 딕셔너리를 설정해도 큰의미가 없어요. 이건 저희가 지도를 쀼려주기 위해 인덱싱한 컬럼이라 메타데이터에서 핸들링하면 안됩니다.

**Comment by AnnieHwang** [comment]
@paigechoi 그러면 일단 GeoType의 경우 딕셔너리 선택이 불가능하게 처리부탁드려요.
