### ISSUE TITLE
Measure filter ux is broken

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#226]
**Describe the bug**
차트 그리기에서 좌측 메뉴에서 메저를 하나 골라 필터로 사용하면 우측 필터란에 표현되지 않음. 여러가지 필터 선택 방법 중 이 방법만 UX 가 깨지고 있음

**To Reproduce**
스크린샷 참조

**Expected behavior**
다른 필터 선택 때처럼 출력되야 함

**Screenshots**
<img width="1836" alt="measure-filter-error" src="https://user-images.githubusercontent.com/526622/45538751-df639d80-b842-11e8-9ee6-bef47d5e30cb.png">

**Desktop (please complete the following information):**
demo site

**Additional context**

**Comment by kyungtaak** [comment]
@eltriny  저는 재현이 되지 않는데요. @eltriny 추가로 확인 부락드릴께요.

**Comment by i1befree** [comment]
말씀 하신대로 현재 데모사이트에서 재현되지 않습니다.
