### ISSUE TITLE
MDM Lineage screen redesign. Displaying the column's relationship in the Lineage screen

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2266]
**Is your feature request related to a problem? Please describe.**
MDM Lineage screen redesign. Displaying the column's relationship in the Lineage screen.
MDM 리니지 화면 재기획. 리니지 화면 내 컬럼 연결 관계 표출

**Describe the solution you'd like**
In existing lineage planning, we will separate the relationship UIs between the tables and the columns.
기존 리니지 기획에서, 테이블간의 관계와 컬럼간의 관계 화면 영역을 분리할 예정

![image](https://user-images.githubusercontent.com/6300003/59992865-d4b71e00-9688-11e9-8f48-43c8617f9be0.png)
- 테이블 간의 관계 리니지 쉐이프
- 컬럼 간의 관계 리니지 쉐이프
- 메타 상세 정보 영역
- 메타 상세 정보가 없을 경우 No data 영역

**Comment by AnnieHwang** [comment]
@koeun222 위의 기획서의 변경사항이 있습니다. 반영부탁드려요
![image](https://user-images.githubusercontent.com/6300003/60946050-2bc71f00-a328-11e9-817f-f1625c3ad064.png)
![image](https://user-images.githubusercontent.com/6300003/60946064-3681b400-a328-11e9-80eb-ad8a0cfe4dc3.png)
![image](https://user-images.githubusercontent.com/6300003/60946085-41d4df80-a328-11e9-8a73-d802a43137f0.png)

**Comment by AnnieHwang** [comment]
@ksparknot 우선 이건 디자인 완료되었어요. 퍼블에 바로 넘길께요. ![image (79)](https://user-images.githubusercontent.com/6300003/61016557-02ab9a80-a3cb-11e9-8e90-5a10bd1cf48e.png)

**Comment by ufoscw** [comment]
@ksparknot 
MetadataSourceType (ETC) 추가되었습니다.
REST Sample입니다.

* request
```
(POST) /api/metadatas

{
  "name":"sales_legacy",
  "description":"aaa",
  "sourceType":"ETC",
  "source":{
     "name":"sales_legacy",
     "type":"ETC"
  }
}
```

**Comment by joohokim1** [comment]
https://github.com/metatron-app/metatron-discovery/issues/2266
https://github.com/metatron-app/metatron-discovery/issues/2264
https://github.com/metatron-app/metatron-discovery/issues/2468
have beem merged all together.

**Comment by joohokim1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lineage UI](https://trello.com/c/PGEsgvVB/44-lineage-ui)
