### ISSUE TITLE
Chart name is initialized when changing target data source on chart edit screen

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#227]
**Describe the bug**
멀티데이터소스 대시보드의 차트 편집 화면에서 차트의 대상 데이터소스를 변경할 경우 차트 이름이 초기화 되는 현상이 발생합니다.

**To Reproduce**
1. 멀티데이터소스로 생성된 대시보드의 편집화면으로 이동합니다.
2. 신규 차트 생성 화면으로 이동합니다.
3. 상단의 차트 이름을 수정합니다.
4. 좌측 데이터소스 목록에서 다른 데이터소스로 선택합니다.
5. 작성했던 차트 이름이 초기화 됩니다.

**Expected behavior**
작성한 이름이 초기화 되지 않고 유지되어야 합니다.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser  Chrome
 - Version 69.0

**Additional context**

**Comment by dave-taeho** [comment]
#227-datasource_change_chart_name_initialize 브랜치 생성하였습니다.
