### ISSUE TITLE
Can't configure datasource column as date/time if data set starts with null / empty values

### ISSUE THREAD

**Issue by siepkes** [metatron-app/metatron-discovery#2294]
**Describe the bug**
When a datasource (I tested this with a CSV file) has a column which starts with `null` values the column can't be configured as date/time. The "Time display format" field will always display an error saying "Please enter in the same format as the data value". The "Next" button stays greyed out.

**To Reproduce**
1. Load a CSV file as datasource with a date/time value column which starts with empty values.
1. Configure the column as data/time with the correct format.
1. Metatron shows an error and you can't press the "Next" button.

**Expected behavior**
I would expect Metatron to ignore the null/empty rows and simply use the first actual value to verify the format.

**Screenshots**
![Screenshot from 2019-07-01 09-12-53](https://user-images.githubusercontent.com/1428678/60442409-422ef580-9c19-11e9-81ad-6381654be740.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7 Linux with Gnome 3.28.2
 - Browser Chrome 
 - Version 75.0.3770.80
 - Metatron version: 3.3.0-RC1

**Additional context**
Not applicable

**Comment by kyungtaak** [comment]
@siepkes I'm sorry for the late reply. :(
The current logic will pass validation if more than half of the entries match the timestamp format. At this time, we have not considered null or empty items. I'll fix this soon. 

Note that you have to specify one column for the timestamp role because the engine is a time series database. When you specify the currently mentioned column as the timestamp role, the query may be possible, but not efficient in terms of data ingestion. please refer this link: https://metatron-app.github.io/metatron-doc-discovery/en/discovery/part01/druid_features.html#ingestion

**Comment by siepkes** [comment]
> I'm sorry for the late reply. :(

No sweat! Thanks for replying!

> The current logic will pass validation if more than half of the entries match the timestamp format. At this time, we have not considered null or empty items. I'll fix this soon.

I understand that this is conceptually somewhat of a hard problem. What if only 15% of the column has a value and the rest is `null`? What if of that 15% half of it fits the date format and the other half does not?

As an idea; Maybe instead of a hard error it should display a warning like: "Only 50% of the data in this column matches this date format. " and simply ignore the data it can't parse?

> Note that you have to specify one column for the timestamp role because the engine is a time series database. When you specify the currently mentioned column as the timestamp role, the query may be possible, but not efficient in terms of data ingestion. please refer this link: https://metatron-app.github.io/metatron-doc-discovery/en/discovery/part01/druid_features.html#ingestion

Sorry my example screenshot is a bad one in that regard. The column in which I demonstrate the issue is not the column that is to be used as the primary timeseries. I hadn't selected the primary timeseries when I made the screenshot to visualize the issue. I should have done that first to avoid confusion.

**Comment by minhyun2** [comment]
@siepkes Thank you for your kindness.
If there are null or empty items, we will validate that it is more than half the total count, excluding the count of null or empty items.
