### ISSUE TITLE
Incorrect count of dimension filter items.

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#23]
**Describe the bug**
- 우측 필터 패널에 차원값 표시 항목을 나열시 표시하는 개수가 필터 편집 화면과 맞지 않습니다. 

**To Reproduce**
1. 워크북/대시보드 생성 후, 차트 위젯을 등록합니다.
2. 10개의 항목이 넘는 차원값을 필터로 등록합니다. (ex. sales.City)
3. 필터 우 상단에 추가 메뉴 중 필터 편집을 선택합니다.
4. 필터 편집에서 상단 "filtering" 아이콘을 클릭하고 "Limitation" 항목에 TOP, 개수는 10 을 선택후 "적용" 버튼을 통해 10개의 항목만 나타나도록 합니다.  그 이후 우측 필터 패널의 개수를 확인합니다.
4. See screenshot

**Expected behavior**
- 필터링된 아이템 개수가 일치해야합니다. 

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/44078978-d9f1b6f2-9fe2-11e8-8269-d4a63c21f992.png)

**Desktop (please complete the following information):**
<N/A>

**Additional context**
- 필터 편집 상단 아이콘 배열에 문제가 있습니다. 해당 사항도 함께 검토하여 주세요.

**Comment by eltriny** [comment]
f#23-incorrect_count_filter_items branch 생성

**Comment by eltriny** [comment]
아래와 같이 수정하였습니다. 
![1](https://user-images.githubusercontent.com/3685833/44138081-b4e17fc0-a0ad-11e8-9f04-1b6550fd47e1.png)
