### ISSUE TITLE
Plan change and design will be reflected

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2300]
**Describe the bug**
1. MDM(metadata, dictionary screen) need to put the UI to sort.
딕셔너리는 기존 그대로 이름순으로 해주세요. 대신 소팅 하는 UI를 넣어야 할 것 같아요.
![image](https://user-images.githubusercontent.com/6300003/60478517-e7030e80-9cbd-11e9-8d0c-e281636d0efb.png)

2. Dictionary list screen need to go into detail after I create it, but now it is going to the list.
생성한 후에 상세로 가야 하는데 지금은 목록으로 가더라고요 (메타데이터 생성하는 씬도 마찬가지예요)

3. If it is a metadata single-item create scene it should go to detail.  And  if it is a multi-item creation, it should go to the list.
메타데이터 생성 씬의 경우, 단건이면 상세로, 다건 생성이면 목록으로 가게 해주세요.

**Comment by brandon-wonjune** [comment]
@AnnieHwang 
> Dictionary list screen need to go into detail after I create it, but now it is going to the list.
> 생성한 후에 상세로 가야 하는데 지금은 목록으로 가더라고요 (메타데이터 생성하는 씬도 마찬가지예요)

이 부분은 code table도 마찬가지인데 동일하게 적용시키면 될까요?

**Comment by AnnieHwang** [comment]
@brandon-wonjune 너무 늦게 답변 달아드려서 죄송해요.
Q1. 해당 씬이라고 하는게 Admin> Metadata 맞죠? Update가 Create보다 더 중요해서.. 저는 Update가 리스트에 나온다고 생각했어요. 기획서도 그렇고요. Update 기준으로 소팅될 수 있게 해주세요~ 
![image](https://user-images.githubusercontent.com/6300003/61613847-522c7900-ac9d-11e9-9f49-8edead632493.png)

Q2. 네 맞아요. 코드테이블도 마찬가지로 UX변경부탁드립니다~

**Comment by brandon-wonjune** [comment]
@AnnieHwang 수정하였습니다
