### ISSUE TITLE
Snapshot result error

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#2315]
**Describe the bug**
When creating a snapshot, the result of file and hive are different.

**To Reproduce**
1. Apply the "delete ismismatched" rule
2. Create snapshot

**Comment by joohokim1** [comment]
@jeongeunkwon There is code that excludes missing lines in TeddyOrcWriter:writeOrc().
I think it's a temporary code block to implement the feature quick.
If possible, would you attach the import file you tested?

**Comment by joohokim1** [comment]
@jeongeunkwon Permitting missing values in ORC files are fine, but for mismatched case, it's impossible for ORC to hold mis-typed values. It's like variable size of string into 8-byte numeric placeholder. So in this case, there're 2 options roughly.
(1) Give some rule (like skip the line or set as zero, etc.) before creating the snapshot or as general option.
(2) Stop. Notice the problem. Ask user that We could put a cleansing rule quickly (like hive-friendly rename feature)

This (2) is absolutely better, but this takes time.
I'll take care of it in the next major release.

@jeongeunkwon If someone ask, guide them to use "clean" function in the column context menu.
![스크린샷 2019-07-08 오후 10 32 24](https://user-images.githubusercontent.com/42257727/60814285-4edebb00-a1d0-11e9-89ab-9b6727749918.png)
(This is actually, a variation of *delete* rule)

**Comment by joohokim1** [comment]
@jeongeunkwon I've been thinking about this, it'll be better to save missing-valued lines.
But, of course, there is no way to save mismatch-valued lines.

**Comment by joohokim1** [comment]
I just modified ORC related code. I'll check this up again.

**Comment by joohokim1** [comment]
Currently, rows with missing values are not omitted.
But, rows with mismatched values are omitted only in hive snapshots.
This might look like a bug, so we need some indication for this behavior.

File snapshot:
<img width="1376" alt="스크린샷 2019-11-06 오전 2 01 07" src="https://user-images.githubusercontent.com/42257727/68228743-548ec500-0039-11ea-89a6-108ccce02dc8.png">

Staging DB snapshot:
<img width="1383" alt="screenshot" src="https://user-images.githubusercontent.com/42257727/68228682-3759f680-0039-11ea-8ee5-53a9414b6846.png">

@ksparknot Could you take over this issue? We need some UI-related jobs.

**Comment by AnnieHwang** [comment]
@joohokim1 @kaypark-sk I wonder how to write warning labels. Do you have an idea?
![image](https://user-images.githubusercontent.com/6300003/68286375-581b5e00-00c4-11ea-9e01-6555f599383e.png)

**Comment by joohokim1** [comment]
@AnnieHwang @ksparknot 
DB-type snapshots cannot contain mismatched values.
would be enough I think.

**Comment by AnnieHwang** [comment]
@koeun222 Please proceed to the below design.
![image](https://user-images.githubusercontent.com/6300003/68363414-1e069680-016e-11ea-993e-236317b4fcb6.png)

**Comment by AnnieHwang** [comment]
@joohokim1 @ksparknot The design is complete.
![D2-03DataSnapshot-01Detail-Success](https://user-images.githubusercontent.com/6300003/68753231-02a4fb00-0648-11ea-9260-95f07b68885a.png)

**Comment by ksparknot** [comment]
@eltriny please publish this

**Comment by joohokim1** [comment]
This issue has mutated too much that the intend is hardly understood. I'll remake a new issue that covers the original bug-like behavior and the additional requests.

**Comment by joohokim1** [comment]
Moved to https://github.com/metatron-app/metatron-discovery/issues/2938.
Closing this.
