### ISSUE TITLE
Download as CSV does not work

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#2329]
**Describe the bug**
I tested in the "Latest(3.3.0-rc2)"
After created snapshot, 
when I clicked the "Download as CSV" button, nothing happened on the screen
and only network traffic has continued.

**To Reproduce**
1. Create datasets with attachments.
2. Create dataflow with the datasets.
3. Apply header rule to the 'country_geo' dataset.
4. Join 'data2' and 'country_geo' with the key 'data2.country' and 'country_geo.admin'
5. Create snapshot.
6. Click the "Download as CSV"

**Additional context**
When I tested in the "Stable", the same thing occurred in the snapshot data preview

[testfile.zip](https://github.com/metatron-app/metatron-discovery/files/3366783/testfile.zip)

**Comment by joohokim1** [comment]
@jeongeunkwon Could you let me know the size (or lines) of the snapshot? Or if I can access the server, please reply a link to that snapshot.

![스크린샷 2019-07-09 오전 12 09 51](https://user-images.githubusercontent.com/42257727/60821142-e4347c00-a1dd-11e9-9298-173cbdc9a65b.png)

As you know, join operation consumes some memory.

**Comment by joohokim1** [comment]
@jeongeunkwon It seems like the snapshot is not a downloadable size.

![스크린샷 2019-07-09 오후 2 39 03](https://user-images.githubusercontent.com/42257727/60862297-17b3ec80-a258-11e9-9e72-575cffc85e9b.png)

I guess you'll see the download dialog pop-up in about 2 hours.

**BTW, we really need to display the size (not line count) in the snapshot detail page.**
@jeongeunkwon How about change this issue into implementing this feaure?

**Comment by joohokim1** [comment]
I'll make another issue for displaying the size of a snapshot. (Maybe, only file snapshots)
Closing this issue.
