### ISSUE TITLE
Error in metadata create from link type datasource

### ISSUE THREAD

**Issue by brandon-wonjune** [metatron-app/metatron-discovery#233]
**Describe the bug**
An error occurs when generating metadata using a linked data source

**To Reproduce**
1. Go to 'Metadata '
2. Click on 'Create new metadata'
3. Use link type datasource and create metadata

**Expected behavior**
There should be no errors when generating metadata using a linked data source

**Screenshots**
![2018-09-14 9 04 15](https://user-images.githubusercontent.com/42233627/45549162-c4545600-b861-11e8-909d-f21ed46ae69b.png)

**Desktop (please complete the following information):**
demo site

**Additional context**
None

**Comment by kyungtaak** [comment]
@brandon-wonjune 이건은 파라미터를 잘못보내어 발생한 이슈 뿐인가요?
