### ISSUE TITLE
Map view chart can not be added to the dashboard.

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#2331]
**Describe the bug**
대시보드에 맵뷰 차트를 추가하여도 대시보드에 위젯이 표시되지 않음.

**To Reproduce**
1. 대시 보드 생성(sales 데이터 소스)
2. 대시 보드 편집
3. 맵뷰 추가
4. 오류
![image](https://user-images.githubusercontent.com/16472109/60787423-b2e38e00-a194-11e9-9b56-2d39b1f9a8ec.png)

**Expected behavior**
대시 보드에 맵뷰 위젯이 표시되어야 함.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac OS Mojave
 - Browser [chrome]
 - Version [74.0.3729.169]

**Additional context**
[3.3.0-rc2 릴리즈](https://github.com/metatron-app/metatron-discovery/releases/tag/3.3.0-rc2)에서 재현됩니다.

**Comment by minhyun2** [comment]
@YooYoungmo 멀티데이터 소스 처리와 관련하여 사이드 이펙트로 확인됩니다.
수정하도록 하겠습니다.
