### ISSUE TITLE
Untranslated message present

### ISSUE THREAD

**Issue by ninezero90hy** [metatron-app/metatron-discovery#2333]
**Describe the bug**
I think the value of the message key is being viewed in the input text.

**To Reproduce**
1. Go to [Demo site > Integrator list page](https://discovery.metatron.app/app/v2/external/management_Integrator_Workflow)
2. Select one workflow from the list
3. See screenshot for the rest of the process

**Expected behavior**
The message should be visible, not the value of the message key

**Screenshots**
![Capto_Capture 2019-07-08_05-03-20_PM](https://user-images.githubusercontent.com/41019113/60794587-0958c880-a1a5-11e9-8207-3017a5926e86.png)

![Capto_Capture 2019-07-08_04-51-13_PM](https://user-images.githubusercontent.com/41019113/60794619-1d042f00-a1a5-11e9-81db-e9b19c723076.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5(18F132)
 - Browser Chrome 75.0.3770.100

**Additional context**
The key value of the **msg.board.custom.ui.placeholder** has been verified to exist in en, ko, zh JSON. But the message is not displayed.

<img width="1679" alt="스크린샷 2019-07-08 오후 5 28 43" src="https://user-images.githubusercontent.com/41019113/60795011-de22a900-a1a5-11e9-8a41-90ab3d48c8ba.png">

**Comment by kyungtaak** [comment]
@ninezero90hy Thank you for your report. :) But. this is not related to the metatron-discovery area. I'll close this issue and then I'll send it my colleague who related to it.
if you have any question or bug report about workflow integrator, please send to metatron@sk.com.

**Comment by teddyPark** [comment]
Works done.
