### ISSUE TITLE
Development of MDM Lineage Management Screen

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2341]
**Is your feature request related to a problem? Please describe.**
Development of MDM Lineage Management Screen.
Menu : Management > Explorer Data(old. metadata) > Lineage
- Lineage data can be uploaded (single & bulk) / downloaded
- Lineage data can be modified / deleted

![image](https://user-images.githubusercontent.com/6300003/61096613-2f2ae980-a493-11e9-9535-803c39e19e1e.png)
![image](https://user-images.githubusercontent.com/6300003/61096626-394ce800-a493-11e9-9a46-0f14a82d1046.png)
![image](https://user-images.githubusercontent.com/6300003/61096647-4cf84e80-a493-11e9-8d50-2ff3e04fc7e3.png)
![image](https://user-images.githubusercontent.com/6300003/61096660-5ed9f180-a493-11e9-9076-56cc269a77c0.png)
![image](https://user-images.githubusercontent.com/6300003/61096681-6b5e4a00-a493-11e9-9f66-24b2718e7a64.png)
![image](https://user-images.githubusercontent.com/6300003/61096689-7618df00-a493-11e9-9d03-e547c3d0b09f.png)

[리니지-신규기획서-190712.pptx](https://github.com/metatron-app/metatron-discovery/files/3384654/-.-190712.pptx)

**Comment by joohokim1** [comment]
@AnnieHwang @ksparknot This issue is undergoing by https://github.com/metatron-app/metatron-discovery/issues/2266. But, that issue is too big to proceed efficiently, we'll merge and close ASAP.
Afterward, this issue will be continued as a separate job.

**Comment by joohokim1** [comment]
@AnnieHwang #2266 issue has been finished. Currently @ksparknot is working on this.

**Comment by joohokim1** [comment]
File upload page done by #2266 
Edge list page __partially__ done by #2266 
Edge detail page __partially__ done by #2266 

@AnnieHwang Other tasks than 3 above have to be made as separate issues for develement.
If you let me know, I'll create as issues.

**Comment by joohokim1** [comment]
@AnnieHwang @ksparknot 
Unfinished tasks will be done by https://github.com/metatron-app/metatron-discovery/issues/2509 and https://github.com/metatron-app/metatron-discovery/issues/2510.

@AnnieHwang If there is more (about lineage tab page), please let me know.
