### ISSUE TITLE
Add sample metadata, lineage edges when initialize

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#2344]
**Is your feature request related to a problem? Please describe.**
It's a bit hard for many users to know what to do to use metadata management and lineage management.

**Describe the solution you'd like**
If sample metadata and lineage edges are installed as initializing, like sales datasource, it'll be very helpful to understand, experience and utilize those features.

**Additional context**
Data preparation also needs this kind of work.

**Comment by joohokim1** [comment]
This issue requires some sample dataprep datasets to serve with real usable samples.

The followings will be done in order.
1. Add DATASET type to Metadata. We need some UI jobs.
2. Add 2 sample datasets. They're not dummies, will be Included in deployment with CSV files.
3. Add sample metadata for them with the new UI.
4. Add sample lineage edge for them.

@AnnieHwang We need to add dataset type in metadata management.
<img width="1646" alt="스크린샷 2019-07-22 오전 1 40 40" src="https://user-images.githubusercontent.com/42257727/61594006-be699700-ac21-11e9-9681-887a19c182f5.png">

**Comment by AnnieHwang** [comment]
@joohokim1 I know. I will start working today and upload it as soon as the UX wireframe is completed.

**Comment by AnnieHwang** [comment]
@joohokim1 @kaypark-sk Please check it.
![image](https://user-images.githubusercontent.com/6300003/61770218-b7ac7100-ae27-11e9-821c-31c26e627dd0.png)
![image](https://user-images.githubusercontent.com/6300003/61770229-bc712500-ae27-11e9-8419-a92934206e22.png)
![image](https://user-images.githubusercontent.com/6300003/61770233-c1ce6f80-ae27-11e9-9517-ee2aff626bec.png)

**Comment by AnnieHwang** [comment]
@joohokim1 @kaypark-sk The design has already been completed, so please refer to the UX wireframe below.
[[M-Core]WF-E1.3-MDM-Management-v0.408-190725.pdf](https://github.com/metatron-app/metatron-discovery/files/3429781/M-Core.WF-E1.3-MDM-Management-v0.408-190725.pdf)

**Comment by joohokim1** [comment]
We decided to support JDBC, STAGING_DB, DRUID type metadata only. Therefore it's impossible to provide default sample metadata for every environments.
We'll deal with this issue when we expand the types of metadata.
