### ISSUE TITLE
Use Apache Spark as an external engine

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#2352]
**Is your feature request related to a problem? Please describe.**
Embedded engine is light and flexible, but for big data, we need something faster.

**Describe the solution you'd like**
Spark engine is very fit to handle data preparation and cleansing, because Spark optimizes many transitions with it's whole code generation feature. Step-by-step dataframe mechanism is also very alike to embedded engine.

**Describe alternatives you've considered**
MR code generation could be another choice.
That might be better when guarantee is more important than speed, like nightly batches.
It'll be the next engine.

**Additional context**
This is a follow-up to https://github.com/metatron-app/metatron-discovery/issues/2165.

**Comment by joohokim1** [comment]
@AnnieHwang We need to revive engine selection component first.

![스크린샷 2019-07-11 오후 3 29 46](https://user-images.githubusercontent.com/42257727/61028310-592ccf00-a3f3-11e9-8729-47ece65be496.png)

IMHO, it might be better to locate the engine selection component below "Advanced settings" for a while, because not many people will look for this unstable feature.

**Comment by AnnieHwang** [comment]
@joohokim1 Please, check the wireframe.
![image](https://user-images.githubusercontent.com/6300003/61117388-5b655b00-a4d1-11e9-8c12-d6c7a600e0fe.png)
![image](https://user-images.githubusercontent.com/6300003/61117410-64eec300-a4d1-11e9-9d27-1d9c6db91dde.png)

**Comment by joohokim1** [comment]
@AnnieHwang Sorry for late reply.
1. It's not necessary to change to CSV format when selecting embedded engine. (file, staging db both)
2. Spark engine also needs to be checked if available or not. When not configured (known by checking API), please make users cannot choose it.

**Comment by AnnieHwang** [comment]
@joohokim1 Ok, I understand. I will write the UX wireframe.

**Comment by joohokim1** [comment]
@AnnieHwang @ksparknot @eltriny I added an API to check if the spark engine is ready.
<img width="1267" alt="스크린샷 2019-07-22 오전 2 26 16" src="https://user-images.githubusercontent.com/42257727/61594599-929ddf80-ac28-11e9-98c5-98c0155dbabb.png">

**NOTE: The exact endpoint is /api/preparationdatasets/{dsId}/transform/configuration.
I don't know why chrome inspector shows it like that.**

@ksparknot Please let me know if you can do the UI job immediately.

**Comment by kuckjwi0928** [comment]
@joohokim1 What version of Spark do you use?

**Comment by AnnieHwang** [comment]
@joohokim1 I fixed a UX wireframe. Please, check it.
![image](https://user-images.githubusercontent.com/6300003/61620254-7a22d900-acab-11e9-9207-28fc3dce9e60.png)

**Comment by joohokim1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대용량 처리 - Spark 코드 개발](https://trello.com/c/PuGbxrJ5/5-%EB%8C%80%EC%9A%A9%EB%9F%89-%EC%B2%98%EB%A6%AC-spark-%EC%BD%94%EB%93%9C-%EA%B0%9C%EB%B0%9C)
