### ISSUE TITLE
Need to correct link error in readme file.

### ISSUE THREAD

**Issue by ninezero90hy** [metatron-app/metatron-discovery#2368]
**Describe the bug**
The link **user manual on our website** is an error.

**To Reproduce**
1.  README.md > Select the **user manual on our web site** link.

**Expected behavior**
Document must be visible.

**Screenshots**
<img width="1680" alt="스크린샷 2019-07-19 오후 3 53 08" src="https://user-images.githubusercontent.com/41019113/61515339-58241f00-aa3d-11e9-8cdf-c324f2db4a82.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
pr related to this issue was merged, I'll close this issue. :)
