### ISSUE TITLE
Use data snapshot column type when creating datasource with data snapshot

### ISSUE THREAD

**Issue by minhyun2** [metatron-app/metatron-discovery#2375]
**Is your feature request related to a problem? Please describe.**
When creating a data source with a data snapshot, the column type is set to String only.

**Describe the solution you'd like**
Use data snapshot column type when creating datasource with data snapshot.

**Describe alternatives you've considered**

**Additional context**

**Comment by joohokim1** [comment]
@minhyun2 I just made a new branch which root is the most recent master.
(f#2375-use_type_from_snapshot)
As we discussed, numeric columns are better to be metric role by default.

**Comment by joohokim1** [comment]
@minhyun2 use f#2375-use_type_from_snapshot2

**Comment by joohokim1** [comment]
Done.
