### ISSUE TITLE
Improve  in code table selection screen when creating a column dictionary

### ISSUE THREAD

**Issue by minhyun2** [metatron-app/metatron-discovery#2384]
**Describe the bug**
When creating a column dictionary, when you select a code table, if you click "detail" in the preview, it will open in the same tab, and the dictionary you were creating will disappear.

**To Reproduce**
1. Go to Column Dictionary
2. Create New Column Dictionary
3. Select a code table
4. Click 'Preview' in the list of code tables.

**Expected behavior**
When you click the Preview button, a confirmation pop-up will be displayed informing you that the column dictionary you are creating will disappear.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by AnnieHwang** [comment]
Please check the wireframe below.
![image](https://user-images.githubusercontent.com/6300003/61703697-19fc6780-ad7d-11e9-82d5-c5f21f39d64f.png)
![image](https://user-images.githubusercontent.com/6300003/61703704-1d8fee80-ad7d-11e9-8a88-f05167d4abaf.png)
![image](https://user-images.githubusercontent.com/6300003/61703714-2254a280-ad7d-11e9-9889-e23e67a54c77.png)
[[M-Core]WF-E1.3-MDM-Management-v0.407-190723.pdf](https://github.com/metatron-app/metatron-discovery/files/3421455/M-Core.WF-E1.3-MDM-Management-v0.407-190723.pdf)

**Comment by ufoscw** [comment]
@eltriny 
Please add Alert as attached above.
