### ISSUE TITLE
Performance issues when viewing a list of shared workspaces

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#2396]
**Describe the bug**
* SKT 운영 환경에서 공유 워크스페이스 목록 조회 시 40초 정도가 소요되고 있음.
![image](https://user-images.githubusercontent.com/16472109/61925141-df294800-afa5-11e9-8974-abdd5b2cd4dd.png)

**Expected behavior**
다른 목록을 조회하면 화면에 비해 비정상적으로 시간이 많이 걸림.  다른 목록 화면 정도의 시간이 걸려야 함.

**Comment by YooYoungmo** [comment]
## 원인 분석
화면에서는 아래 URL로 호출하고 하고 있으며, URL로 Projection을 'forListView'를 사용 하고 있음
http://localhost:8180/api/workspaces/my/public?projection=forListView&size=20&page=0&sort=name%2Casc

ListViewProjection은 HTTP 응답에 'workspaceService.myRoles' 호출 결과를 추가하여 반환하고 있음
```java
// app.metatron.discovery.domain.workspace.WorkspaceProjections.java

@Component
public class WorkspaceProjections extends BaseProjections {

  // ...
  @Projection(name = "forListView", types = { Workspace.class })
  public interface ListViewProjection {

    // ...
    @Value("#{@workspaceService.myRoles(target.id, target.ownerId)}")
    List<WorkspaceMember> getMyRoles();
  }
}
```

문제는 workspaceService.myRoles 을 호출하는데 약 2초가 걸리고 있는데 한번만 호출되는 것이 아니라 목록이기 때문에 '공유 스페이스 수 만큼' 호출됨.

결과적으로 현재 공유 스페이스 목록을 기본적으로 20개를 노출하고 이기 때문에 약 40초가 걸린것으로 판단됨.

**Comment by kyungtaak** [comment]
PR 이 종료됨에 따라 이슈도 종료하도록 하겠습니다. 감사합니다. ^^
