### ISSUE TITLE
Improve the Save data table action for useful download functions.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#240]
**Is your feature request related to a problem? Please describe.**
테스트 : https://discovery.metatron.app/app/v2/workbook/2462e00f-1043-4921-879f-a92dec6a00a7
1. Metatron(클라우드) 에서 Sales 데이터로 워크북 생성
2. Global 필터로 Order Date 필터링 적용
3. 두개의 데이터 테이블 차트 생성 후, 차트필터로 Ship Mode 필터링 적용(두개 값만 멀티 선택)
4. 두개의 차트 중 하나는 피봇으로, 하나는 오리지널로 뷰모드 변경

![sales](https://user-images.githubusercontent.com/612173/45593747-eb2c9c80-b9c7-11e8-8428-49d98e047e76.png)
![chart_filter](https://user-images.githubusercontent.com/612173/45593749-eec02380-b9c7-11e8-8ca4-27afc698a5af.png)

대시보드 화면에서 각각 Save data table 액션 수행
![download_pivot](https://user-images.githubusercontent.com/612173/45593769-5aa28c00-b9c8-11e8-97fa-df0d89cddcf4.png)
![download_orignal](https://user-images.githubusercontent.com/612173/45593774-5d04e600-b9c8-11e8-8513-98dc59abe594.png)

피봇 테이블과 오리지널 테이블 둘다 Download original data 만 가능하며, 다운로드 결과 데이터가 같음.

**Describe the solution you'd like**
사용자 입장에서는 첨부파일과 같은 2가지 유형의 다운로드가 필요함

[expected_download.xlsx](https://github.com/metatron-app/metatron-discovery/files/2386367/expected_download.xlsx)

- 엑셀시트 중 filtered data : 글로벌필터와 차트필터가 적용된 데이터(선반에 올려진 값과 상관없이 rawdata 에서 필터만 적용)
- 엑셀시트 중 chart data : filtered data 에서 차트를 그리기 위해 선반에 올려진 값의 결과값 데이터

현재 제공되는 Save data table 화면에서 표현되는 Csv, Excel 기능을 둘다 디폴트 값을 Excel 로 바꾸되, Chart Data, Filtered Data 로 변경
Excel 혹은 Csv 는 별도 옵션으로 선택하여 다운로드

**Describe alternatives you've considered**
Datasource 화면에서 다운로드 기능으로 보완 가능하나,
![datasource](https://user-images.githubusercontent.com/612173/45593867-5d05e580-b9ca-11e8-83b1-cc463ef8ed6c.png)

이 화면에서는 Data Source 에 등록된 Rawdata 를 보여주는 것이 필요해 보이므로 현재 기능을 유지하되, 
가장 최근 데이터가 표현되었으면 좋을 듯 하며, Datetime 정보를 필터링(From, To 날짜시간선택) 하여 필터링 된 양(row number or size) 을 제공하여 사용자가 다운로드 받을 수 있도록 제공
또한 다운로드 버튼이 좀더 강조(엑셀 아이콘등) 되었으면 함

**Additional context**
IDCube

**Comment by kyungtaak** [comment]
@Taehui 좋은 제안 감사합니다. 다운로드에 대해 정리의 필요성이 있을것 같네요.

@metatron-app/design 위 다운로드 방식에 대해 검토 부탁드립니다.

**Comment by AnnieHwang** [comment]
@kyungtaak @Taehui 저희가 검토 한 내용은 일단 차트 별로 유형이 다르다고 해서 서로 다른 데이터가 다운로드 되는건 아닌것 같고요.( 이유는 텍스트 그리드에 한해서 DT의 요구로 특별히 그 차트만 원본데이터를 표현하도록 한것인데 너무 예외케이스를 많이 만들어 두는것 같아서요.) 

현재 차트 내 데이터 다운로드는 다음과 같은 기획 내용이 나와 개발을 대기 하고 있습니다. [이슈 METATRON-1061 참조]
![image](https://user-images.githubusercontent.com/6300003/45610542-48435380-ba97-11e8-9ce9-d419e683511a.png)

위의 문제를 해결결하기 위해서, 저희끼리 논의 한 결과 차트 위젯 내 다운로드는 건드리지 않고, 아래와 같이 대시보드 내 데이터소스 팝업에서 '필터링 적용' 선택 버튼을 두어서, default값은 원본데이터가 다운로드 되고, 체크 시 글로벌/선택필터가 적용된 원본데이터가 다운로드 되도록 하는게 어떨까 싶습니다.
![image](https://user-images.githubusercontent.com/6300003/45610483-01555e00-ba97-11e8-8769-3b7f4087c4ff.png)

의견 있으시면 말씀부탁드립니다.

**Comment by Taehui** [comment]
@kyungtaak 그리고 현재 기준으로, 계산식 필드가 있는 차트는 다운로드가 안되는데, 이것은 별도 이슈로 등록을 할까요?

**Comment by Taehui** [comment]
@AnnieHwang 위 기획 구성에 대해서는 괜찮습니다만, 그리드 테이블에 대해서만 원하는 형태의 동작을 요청드린건 아닌데 정보 전달에 오류가 ^^;;
위 기획 내용대로 진행된다면 사용에 무리가 없을 듯 합니다.

**Comment by Taehui** [comment]
@AnnieHwang 오늘 설명드린 내용으로 리뷰 후 의견주세요~

**Comment by AnnieHwang** [comment]
@Taehui 아래 내용으로 정리하였고, 기획자 분과 논의 후 기획안으로 개발측과 논의하여 답변드리도록 하겠습니다.
![image](https://user-images.githubusercontent.com/6300003/46715068-5ef55880-cc99-11e8-82b8-189e15ea39dc.png)

**Comment by minjung-cho** [comment]
@Taehui @AnnieHwang 요구사항 반영한 기획서입니다. 이해가 잘못된 부분은 없는지 검토 부탁드립니다!
대시보드 > 데이터소스 정보 보기 팝업
![2018-10-10 7 43 15](https://user-images.githubusercontent.com/28773903/46732449-7d267d00-ccc8-11e8-8efc-4b8f2498b56d.png)
차트 위젯 > 차트 데이터 보기 팝업
![2018-10-10 8 08 32](https://user-images.githubusercontent.com/28773903/46732450-7dbf1380-ccc8-11e8-8765-81068da8e5de.png)

**Comment by Taehui** [comment]
@AnnieHwang , @minjung-cho 기획하신 내용 잘 봤습니다. 기능 측면에서는 요청드린 내용대로 되었는데, 한가지 고려해야할 사항이 다운로드 건수는 100만건 정도가 필요한데, 실제 웹에 표현되어야 할 숫자는 100만건이 아니라 훨씬 더 적은 숫자여야 합니다. 100만건을 다 그리는 순간 먹통...
이 내용만 반영되면 될 것 같습니다.

**Comment by AnnieHwang** [comment]
@Taehui @kyungtaak 데이터 건수의 제한에 대해서는 UI에서 해결할수 있는 건 
1. 차트 화면상 Limit 기능 탑재 (현재 해당 기능은 숨겨져 있는 상황입니다)
2. 어드민의 데이터소스 상세 씬에서 필터기능을 통한 건수 제한 (현재 해당 기능은 보완이 필요합니다)
으로 풀수 있을것 같습니다.

일전에 말씀하셨던 서버에서는 데이터를 100만건 정도 가지고 오지만 WAS 메모리 상에서 건수 제한 하여 화면에 표출하는 기술적인 방법은 개발팀과 논의가 필요할 것 같습니다. 논의 후 말씀드리도록 하겠습니다.

**Comment by babokim** [comment]
@Taehui 이 부분은 챠트에서 하기 보다는 workbench의 다운로드 기능에서 개선하는 것이 어떤가요? Table  Chart에 데이터를 많이 넣는 것은 브라우저의 성능상 좋지 않을 것 같고, 정해진 건수만 보이게 하려면 모든 Table Chart에 대해 임시 저장하는 기능으로 만들어야 하는데 챠트라는 기능의 성격상 맞지 않을 것 같아서요.

**Comment by AnnieHwang** [comment]
@Taehui 저 위의 질문하신게, 혹시 데이터소스 다운로드 관련 건수 제한인가요? 그럼 현재 그렇게 구현되고 있는 상태입니다. 걱정안하셔도... 만약 차트의 데이터 건수제한이라면, 저희가 조만간 Limit기능을 다시 재오픈할 예정입니다. 참고부탁드립니다.

@minjung-cho 개발쪽과 기획안 논의를 했는데, 아래내용 적용 부탁드려요. 
1. 대시보드 상 원본보기에서는 'Apply filters' 기능을 삭제해주시고, 시간 구간 UI로 원본데이터를 보고 다운로드받을 수 있게 수정부탁드립니다. (default는 전체 시간 범위입니다)
2. 차트 위젯 내 다운로드 시 원본데이터는 선반에 올라기 있는 컬럼들에 대해서만 보여집니다.
3. 위 내용 디자인 진행 부탁드립니다.

**Comment by minjung-cho** [comment]
@AnnieHwang UI 변경사항으로 풀어봤습니다. WF 올리고 노티 드리겠습니다~
1. 데이터그리드 상단에 기간 필터링 추가(전체 기간 default)
3. 차트 위젯에서는 선반 데이터만 보임.(위 기획서와 동일)

**Comment by Taehui** [comment]
@babokim 저희는 차트로 보다가도 결국에 엑셀로 받기를 원하는 사용자 들이 많아서, 항상 요구사항으로 위 내용이 나오고 있습니다. 또한 워크벤치는 SQL 을 알아야 하기 때문에 전체 사용자의 20% 이하만 활용이 가능한 단점이 있어서요~
@AnnieHwang 님 말씀으로는 요청 드린 내용을 감안해서 개발 하신 듯 합니다.

**Comment by minjung-cho** [comment]
@AnnieHwang WF입니다~
<img width="1448" alt="2018-10-12 3 27 51" src="https://user-images.githubusercontent.com/28773903/46851921-263db680-ce34-11e8-9f63-4f2a116ee652.png">
<img width="1448" alt="2018-10-12 3 29 23" src="https://user-images.githubusercontent.com/28773903/46851924-26d64d00-ce34-11e8-84fe-43091a8fb682.png">

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다 
데이터그리드 상단에 기간 필터링 추가(전체 기간 default) 
![image](https://user-images.githubusercontent.com/42256760/46999214-02de7880-d160-11e8-992e-679cb7dbe9ea.png)


차트 위젯에서는 선반 데이터보는 부분은 이전에 [ tde 1061] 이슈에서 디자인완료되었습니다 
퍼블 진행 부탁드려요

**Comment by kyungtaak** [comment]
@alchan-lee  @eltriny 기능 확인시 원본보기 일 경우 aggregated 타입의 function 이 포함된 userdefined 컬럼이 있는 경우에만 다운로드 제한이 되는 것이 맞는지 추가 확인 해주세요. (현재는 무조건 userdefined 컬럼이 있으면 제한이 되어 버려 사용자 문의가 빈번하게 발생하고 있습니다.)

**Comment by kyungtaak** [comment]
@alchan-lee #371 이슈도 함께 고려해서 진행 부탁드립니다.

**Comment by eltriny** [comment]
f#240-improve_save_data 브랜치 생성하였습니다.

**Comment by AnnieHwang** [comment]
@eltriny @kyungtaak @alchan-lee 저희가 기획 리뷰 하면서 해당 내용 좀 곰곰히 보았는데.. 일단 기획이 미비해서 '데이터미리보기' 부분에 검색조건을 추가하는(날짜 추가) 하는 UI는 이번 스프린트에서 제외해야 할 것 같습니다. (다운로드에 대한 사항은 기획대로 진행 부탁드립니다.

기획이 미비한 이유는.. 
1.일단 데이터 미리보기 부분이 저희는 데이터를 미리보기 할 용도로 만들었지, 데이터를 검색하기 위한 용도가 아니었습니다. (사실 그 부분은 대시보드의 기능이고요) 
2.날짜 필드만 검색이 들어오는 것도 좀 이상했던것 같습니다. 들어오려면 모든 필드의 대한 쉬운 검색 UI가 필요한것 같습니다.

그래서 @Taehui  원하셨던 '데이터 미리보기'에서 날짜로 데이터를 제한하는 케이스의 경우
데이터 검색 하는 입력창에서 ex) '2011-12' 이런식으로 데이터를 필터링 하여 제한하셔서 요구사항을 해결하셨으면 하고, 해당 검색창에 대한 기획은 내부 고민 후 재 진행하여 새로운 이슈로 만들도록 하겠습니다.

감사합니다.

**Comment by AnnieHwang** [comment]
@kyungtaak @Taehui @eltriny @alchan-lee 개발쪽과 논의해보았는데.. 일단 저 시간값으로 검색하는건 디자인 원안대로 가기로 했습니다. 의견있으시면 말씀부탁드려요.

**Comment by minjung-cho** [comment]
@eltriny 
추가 설명드리면...
이슈에서 추가되는 시간 필터링 UI는 타임스탬프 컬럼의 데이터로 필터링하기 위해한 것이기에
타임스탬프가 current time인 경우는 해당 UI가 나오지 않습니다.
어떤 컬럼을 필터링하는 것인지를 사용자에게 알려주기 위해서 필터링의 레이블을 'Date' --> '타임스탬프 컬럼 이름'으로 적용 부탁드립니다.

**Comment by kyungtaak** [comment]
@eltriny select query 에 대한 정렬에 대해 로직을 추가하였습니다. 아래 처럼 timestamp role 인 필드명을 전달해주시면 됩니다.
```
{
    "dataSource": {
        "type": "default",
        "name": "sales"
    },
    ...,
    "limits": {
        "limit": 1000,
        "sort": [
            {
                "field": "OrderDate",
                "direction": "DESC"
            }
        ]
    }
}
```

**Comment by kyungtaak** [comment]
1. @eltriny 초기 화면 로드시 : ALL, ALL 인경우 데이터 소스상 min/max 값 표기 
2. @AnnieHwang  Last 7 days 의 기준 필요 : 현재시간인지? 혹은 데이터 소스상 max 인지?
3. @eltriny Date 관련 버튼 클릭시 0 오류 확인 요청
4. @AnnieHwang 화면에 뿌릴수 있는 원본데이터 건수 조정, 제가 보기엔 10000건이 적당한것 같아 이미지상에 정책을 제안해보았습니다. 
5. @eltriny download 클릭시 건수와 사이즈를 게싱하는게 있는데 이 화면엔 적용이 안된듯합니다. 

![image](https://user-images.githubusercontent.com/822255/48744265-efb45080-eca9-11e8-8d44-eec5b4477be3.png)

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho 추가 확인 부탁드립니다.
![image](https://user-images.githubusercontent.com/822255/48744666-81708d80-ecab-11e8-9f35-4dbde76f10f0.png)

**Comment by minjung-cho** [comment]
@AnnieHwang @kyungtaak 마지막 그리드 디스플레이 문제 검토 중입니다

**Comment by minjung-cho** [comment]
@kyungtaak 데이터가 적을때 그리드 영역에 컬럼 width를 늘이는 것과 백그라운드 컬러를 더 주는 안을 테스트 해 보았는데요, 이부분 디자인은 여러 상황에서 공통적으로 들어가고 있기 때문에 지금 이슈에서 변경하는 것이 조금 부담스러웠습니다. 그래서 팝업 사이즈를 줄이는 것으로 진행하고자 합니다. 
![image 29](https://user-images.githubusercontent.com/28773903/48760814-6cffb580-ecea-11e8-9fc2-21d50160f223.png)
@eltriny 팝업 사이즈 700X500, middle, center 정렬 부탁드립니다.
이미지는 권장 사이즈 W1440에 올려 본 예시입니다.

**Comment by alchan-lee** [comment]
fixed at #791

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho 2/4 번의 답변이 안되어 개발이 안된것같은데요. 퀵하게 검토 부탁드릴게요.

**Comment by AnnieHwang** [comment]
@kyungtaak @minjung-cho 
2. Last 7 days 의 기준 필요 : 현재시간인지? 혹은 데이터 소스상 max 인지?
=> 현재시간이 맞습니다. 만약 데이터소스 상의 max를 이용한 조회가 필요하다면 다른 퀵버튼 레이블을 생각해보고 추가해야 할것 같습니다.
4. 화면에 뿌릴수 있는 원본데이터 건수 조정, 제가 보기엔 10000건이 적당한것 같아 이미지상에 정책을 제안해보았습니다.
=> 건수는 사실 다 나오면 좋으나, 개발상의 이슈라면 10000건 좋습니다. UI정책은 조민정님과 정해서 말씀드리겠습니다.

**Comment by AnnieHwang** [comment]
@kyungtaak @minjung-cho @eltriny  좀 급한거 같으셔서 제가 결정하자면 
CASE 1. 10,000건보다 데이터가 큰 경우 : 현재 보여지는 건수/10,000(‘총 or total’ 실제 총 건수) 로 표기되었으면 합니다. 
CASE 2. 10,000건보다 데이터가 작은 경우 : 현재 보여지는 건수/총건수
@minjung-cho 이상하시면 빠르게 말씀 부탁드립니다.

**Comment by kyungtaak** [comment]
@AnnieHwang 
1번은 건수를 의미하는게 아니고, 실제 로드되는 데이터 수 입니다. 
- 20,000건이 총 건수면 아무리 12000 건을 입력해도 10,000/total 20,000 이렇게 되길 원했습니다.
2번관련 계속 테스트하다보면 현재시간인 경우가 많지 않을것 같아 드린 말씀이었습니다. "last" 의 의미는 데이터를 기준으로 하는게 더 맞을것 같다는 생각이 드는데요. "Today" 도 사실 무의미 한것 같다는 생각입니다. SegmentGranulariy 기준으로 변경하거나, 아니면  지난 7일/1달 이 그나마 나아보이는데요. (이건은 별도 이슈로 정리해나가도 좋을듯합니다.)

**Comment by AnnieHwang** [comment]
@kyungtaak 아.. 그런거면 차라리 인풋박스 대신 셀렉트박스로 바꿔야 할것 같아요. 12,000건을 입력할수 있어서 입력했는데 10,000으로 갑자기 바뀌면 이상한것 같아요. 10,000을 최소로 해서.. total갑의 10,000단위까지 셀렉트 박스는 어떠신가요?

Today가 의미 없을 거 같긴한데.. max 로 하기는 좀 이상해서 그냥 놓아두었어요. 차라리 최근 검색 UI변경 하는 데이터소스 검색 패널과 비슷하게 필터링 방식으로 가면 어떨까요? (별도 이슈로 만들어서 정리하겠습니다!)

**Comment by AnnieHwang** [comment]
@eltriny 너무 늦게 죄송해요.

데이터 미리보기는 default값을 1000건 변경해주시고요(차트 리밋 default값과 동일하게..) 
10,000건 이상으로 조회한 경우는 알림 살짝 띄우고(조민정님께 문의하세요) 인풋값을 10,000건으로 돌려놓는 UX로 변경해주세요 (총 건보다 넘은 경우 인풋을 총건으로 돌려놓는 UX처럼요)

감사합니다.
