### ISSUE TITLE
Improving UX between data source and metadata

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2426]
**Is your feature request related to a problem? Please describe.**
Improving UX between data source and metadata
There is a problem that the screen is changed when the screen is switched.
- Show confirmation popup when clicking move button
- Chang the title label
- Also Change the Metadata Detail Screen Design

(1.Datasource screen)
![image](https://user-images.githubusercontent.com/6300003/62439486-f2e36400-b786-11e9-84b5-c6c53b9ecc53.png)
(2.Management > Metadata screen)
![image](https://user-images.githubusercontent.com/6300003/62439495-f971db80-b786-11e9-8027-2ee6a67bd719.png)
(3.Explore data screen)
![image](https://user-images.githubusercontent.com/6300003/62440597-cf6ee800-b78b-11e9-8dd4-27a1a5e3f39e.png)

**Comment by koeun222** [comment]
Management > Metadata > detail 
상세화면 수정된 디자인 공유드립니다
인기도 디자인 수정 및 위치 재배치 했습니다- 
![E1-02Admin-01Data-03Detail-01information Copy 2](https://user-images.githubusercontent.com/42256760/62603942-e94a2f80-b931-11e9-965f-0afccd9cb0bd.png)
![E1-02Admin-01Data-03Detail-01information Copy 5](https://user-images.githubusercontent.com/42256760/62603943-e94a2f80-b931-11e9-9800-47e974490aad.png)
