### ISSUE TITLE
[Notice] Repository reset - August 14th (Wednesday, Korean Time).

### ISSUE THREAD

**Issue by alchan-lee** [metatron-app/metatron-discovery#2431]
### [Reset completion (Aug 14, 2019)]
**As noticed below, repository reset has been completed and Stars have been initialized.
But Watch and Fork have also been initialized with Star, so please re-register it if you need.**

---

Respecting the community's voice (#2405), we keep contacting GitHub team about the repository reset procedure and any concern or comment on this issue. But we have not received the GitHub team’s response yet. We will keep informed of GitHub’s feedback and we will follow GitHub’s guidelines.

In order to minimize the impact of initialization, we have asked GitHub for the procedure. However, regardless of whether we receive a response, we will reset the repository by changing the repository from public ->  private -> public on **August 14 (Wednesday, Korean Time).**

In addition, we have found out that this method has some other outcomes which initialize the Watch release and Forks also. We will check more and re-announce it soon.

We will continuously listen to and respect the community's voice and will put our best efforts to abide by the open-source ecosystem spirit.

Once again we are deeply sorry and apologize for this issue.

[Additional Notice (Aug 9th, 2019)]
By this reset, it is expected that not only GitHub Star but also Watch and Fork will be initialized, but Issue bulletin will remain. Please re-register it after the repository reset, if you need.
We will inform you once more if there are any additional updates.

[Contact with Github (Aug 12, 2019)]
We have been contacted by GitHub and plan to conduct technical consultations and so on.
As we promised the community, the repository reset on August 14 will continue as planned.
If we receive a guide from GitHub, we will announce it and proceed further actions as needed.

---

### [완료 공지 (2019/08/14)]
**아래 공지와 같이 Repository reset이 완료되었습니다.
Star와 함께 Watch, Fork도 초기화 되었으니 필요하신 분들께서는 다시 한번 등록 부탁드립니다.**

---

지난 7월 30일 GitHub Star Issue 와 관련하여 커뮤니티 의견(#2405)에 따라 GitHub에 repository reset 절차 및 향후 조치에 대해 접촉하고 있으나 GitHub Team의 답변을 아직 못 받은 상태입니다. GitHub의 피드백이 오는 대로 알려드리고, GitHub의 가이드를 준수하겠습니다.

Repository 초기화로 인해 연계된 issue 및 타 project 에 미칠 수 있는 영향을 최소화하기 위해 GitHub 측에 절차를 문의한 상황이나, 저희는 이번 Issue에 대한 책임을 통감하고 있으며, 이에 따라 내부적으로 논의한 결과, 8월 13일(화)까지 GitHub 측의 답변이 오지 않더라도 본 Repository Reset을 한국시간(GMT+9) 8월 14일(수)에 진행할 예정입니다.

본 변경 작업에 따라 기존의 Star 수와 더불어 Watch와 Fork 또한 초기화될 수 있으며, 추가적으로 필요한 내용에 있어서는 지속적으로 업데이트 드리도록 하겠습니다.

앞으로 저희는 오픈소스 커뮤니티 여러분의 의견을 경청하고 오픈소스 취지와 진정성을 이해하며, 오픈소스 생태계에 기여할 수 있도록 고민하고 노력하겠습니다.

[Additional Notice (2019/08/09)]
본 변경 작업에 따라 기존의 Star 수와 더불어 Watch와 Fork 또한 초기화될 예정입니다.. 이에 번거로우시겠지만 필요하신 분들께서는 repository reset 후에 다시 등록 부탁드리겠으며, 추가적으로 필요한 내용에 있어서는 지속적으로 업데이트 드리도록 하겠습니다 (Issue 게시판은 그대로 유지될 예정입니다)

[Github과의 연락 공지 (2019/08/12)]
GitHub으로부터 연락이 왔으며, 기술적 협의 등을 진행할 계획입니다.
커뮤니티에 약속드렸던 8월 14일 repository reset은 계획대로 진행하고,
GitHub로부터 가이드를 받으면 공지한 후, 그에 따른 추가 작업이 필요할 시 진행하겠습니다.

**Comment by hiseob** [comment]
Just deleting all evidences and let time flow XD

common korean solution... nice job
