### ISSUE TITLE
There is a problem with the auto-complete style of the workbench

### ISSUE THREAD

**Issue by ninezero90hy** [metatron-app/metatron-discovery#2452]
**Describe the bug**
There is a problem with the autocomplete style of the workbench
The 'z-index' of the autocomplete layer appears to be lower than the area showing the results

**To Reproduce**
1. Go to Workbench screen
2. Type 'se' and press the key 'control + space bar'

**Expected behavior**
The auto-completion layer must be visible without being obscured

**Screenshots**
<img width="1680" alt="스크린샷 2019-08-13 오후 3 40 42" src="https://user-images.githubusercontent.com/41019113/62920815-c01e1900-bde1-11e9-91dc-6cac1143157f.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**
I tested it in Chrome, but the same problem occurs in IE

**Comment by ufoscw** [comment]
@ninezero90hy 
Thanks for the bug report!

**Comment by kuckjwi0928** [comment]
I think we should add the following to the workbench css
`ul.CodeMirror-hints  {
  z-index: 21;
}`

**Comment by ninezero90hy** [comment]
This problem has been forgotten.
