### ISSUE TITLE
Enhance statement parsing

### ISSUE THREAD

**Issue by devholic** [metatron-app/metatron-discovery#2459]
**Is your feature request related to a problem? Please describe.**

[Trimming query statement in `PrepDatasetStagingDbService`](https://github.com/metatron-app/metatron-discovery/blob/f019b72a69e1713e38b5e958daf2b0919b7a5d77/discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java#L365) can be done with regular expression. Also, [comment](https://github.com/metatron-app/metatron-discovery/blob/f019b72a69e1713e38b5e958daf2b0919b7a5d77/discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java#L362) in current implementation seems inappropriate.

**Describe the solution you'd like**

- Replace `substring` with `regex` group

**Comment by joohokim1** [comment]
@devholic Thank you for your generous contribution. FYI, In order to meet community's recommendation, I'm undergoing rather big scale refactoring including the code you just submitted. I wish you do not upset, even though I might amend the code again. Thank you again.
