### ISSUE TITLE
Workbench screen break at hive DB connection

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#247]
**Describe the bug**
하이브 DB 커넥션을 사용 시, 테이블에서 보여줄 하이브의 설정이 너무 많아 레이어드 팝업의 화면 깨짐 현상이 발생합니다.

**To Reproduce**
1. 워크벤치 상세화면 이동
2. DB 선택
3. 테이블 리스트 중 하나의 테이블의 i (인포메이션) 버튼을 클릭

**Screenshots**
- Hive 설정이 보여줄 경우 처음 로딩 시 화면(Hive설정이 너무 많아 화면 영역이 너무 작은것 같습니다)
![image](https://user-images.githubusercontent.com/6300003/45608518-58a30080-ba8e-11e8-8978-dcb4abab7eec.png)

- 가로 스크롤을 오른쪽으로 밀 경우 하단과 같이 화면이 깨져보입니다. (닫기 버튼은 레이어드 팝업 우측 상단에 고정적으로 존재하여야 합니다.)
![image](https://user-images.githubusercontent.com/6300003/45608534-6eb0c100-ba8e-11e8-9399-af4afe216380.png)

**Comment by kyungtaak** [comment]
@AnnieHwang 이건 깔끔하게 그리드 스타일로 가야하지 않을까 하는 개인적인 생각이 듭니다. 검토 부탁드리빈다.

**Comment by AnnieHwang** [comment]
@kyungtaak 근데.. Hive빼고 다른 DBMS는 보여줄 내용이 아주 적어서요. 고려해보겠습니다.

**Comment by minjung-cho** [comment]
@AnnieHwang 최종 디자인과 좀 다른 부분들이 있긴 하네요. 실제 나오고 있는 화면을 보니, 가이드 잡을때 정보보다 한뎁스가 더 있는것 같습니다. # Detailed Table Information <-- 이런 샵붙은 부분.. 
위에서 제안 하신 안도 고려해서 디자인 테스트 후 피드백 드리겠습니다

**Comment by AnnieHwang** [comment]
@kyungtaak @ufoscw  디자이너가 아래와 같은 디자인 이미지 시안 적용해주셨는데 어떠신가요? DB별로 사실 어떤건 양이 적고.. 어떤건 양이 많고 해서.. 텍스트 그리드로 툴팁느낌 나는 레이어드 팝업 디자인이 좀 이상할것 같아서요. 확인 부탁드려요~
![image](https://user-images.githubusercontent.com/6300003/45666561-ddeee980-bb50-11e8-87fb-2d8a640f4aea.png)

**Comment by ufoscw** [comment]
@AnnieHwang 내용이 길거나 짧을때 스크롤바가 이상하게 생기지 않도록 스타일 적용이 잘되면 될것 같습니다.

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/45670020-a7b76700-bb5c-11e8-8036-08012f539d58.png)

@eltriny 
3번의 경우 실데이터를 넣어보니 서브텍스트의 디자인이 필요하여 추가하였습니다
제플린으로 공유드리겠습니다

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/45670415-b2bec700-bb5d-11e8-9afc-6516828b65b3.png)
@eltriny 
3번의 경우 실데이터를 넣어보니 서브텍스트의 디자인이 필요하여 추가하였습니다
제플린으로 공유드리겠습니다

**Comment by choonglee170924** [comment]
#f247-Workbench_screen_break_hive_db_connection branch 생성
