### ISSUE TITLE
Incorrect value when running Metatron Druid GroupBy query

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#2475]
**Describe the bug**
메타트론에 내장된 sales 데이터 소스를 사용하여 만든 테이블 차트가 메타트론 드루이드 버전에 따라 다르게 나타남.

**To Reproduce**
현재 master 브랜치에서 재현 가능함.

* druid-metatron-3.2.0
![image](https://user-images.githubusercontent.com/16472109/63326137-8cee0380-c366-11e9-9123-030bea7ed5dc.png)

* druid-metatron-3.2.6
![image](https://user-images.githubusercontent.com/16472109/63326169-9d9e7980-c366-11e9-88e6-c3769bf1c867.png)

**Expected behavior**
druid-metatron-3.2.0 처럼 나와야 함.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
@YooYoungmo 해당이슈는 엔진 버그로 수정이 완료되었습니다. 3.3 릴리즈에 배포될 엔진 바이너리에 포함할 예정입니다. 
(This issue has been fixed due to an engine bug. It will be included in the engine binaries that will be distributed in the 3.3 release.)
