### ISSUE TITLE
Support creating chart directly from SQL databases without ingestion

### ISSUE THREAD

**Issue by GameProfessor** [metatron-app/metatron-discovery#2489]
Is it possible to connect directly to traditional SQL databases like MySQL, Postgre,... to create dashboard/charts without ingesting data?  
This will make metatron-discovery a versatile universal BI tool similar to Superset & Metabase.  
Another advantage is that it will reduce hardware requirement because not having to install Druid.
This will apply for cases when customer doesn't have much data and their data are already stored in a MySQL database.

**Comment by i1befree** [comment]
Metatron Discovery requires Druid for performance. Currently you can use linked datasource option. Please refer following url : https://metatron.app/2019/04/17/create-a-dashboard-with-presto-db-and-druid/

**Comment by GameProfessor** [comment]
I guess this will not be supported by design, so I'm closing the issues.
