### ISSUE TITLE
No value name in multi selected filter when pre-selected value exists

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#249]
**Describe the bug**
Multi select 필터에서 미리 선택된 값이 있는 경우 화면과 같이 [Object] 와 같은 형태로 나타남

**To Reproduce**
1. Go to 'Filter'
2. Click on 'Check multiple' And then select some values. Click OK.
3. See error

**Expected behavior**
선택된 값이 나타나야 함

**Screenshots**
<img width="310" alt="screen shot 2018-09-17 at 3 37 19 pm" src="https://user-images.githubusercontent.com/321821/45610828-ec290100-ba8f-11e8-9873-0e581f16d8b9.png">

**Desktop (please complete the following information):**
 - OS: OsX
 - Browser chrome
 - Version 69.0.3497.92

**Additional context**
filter-multi-select.component.ts 코드가 다음과 같이 수정되어야 함
```
  public ngOnInit() {
    // array check
    if (this.selectedArray == null || this.selectedArray.length === 0)  {
      this.selectedArray = [];
      this.viewText = this.unselectedMessage;
    } else {
      this.viewText = this.selectedArray.join(',');
      ----> this.viewText = this.selectedArray.map( item => item.name ).join(',');
    }

    // Init
    super.ngOnInit();
  }
```

**Comment by i1befree** [comment]
@babokim 현재 릴리즈마다 브랜치(현재 버전 : 3.0.3 브랜치)를 따고 거기에 merge 를 진행한 후에 최종 테스트가 끝나면 master 에 3.0.3 브랜치를 merge 하는 방식으로 진행되고 있습니다.

**Comment by babokim** [comment]
#215와 중복되어 Close 처리
