### ISSUE TITLE
Setting decimal places is not working

### ISSUE THREAD

**Issue by esezin** [metatron-app/metatron-discovery#251]
**Describe the bug**
숫자 포맷에서 소수점 자리를 설정하였을 때, 적용되지 않음

**To Reproduce**
1. (공통) 차트생성
2. 숫자 포맷 (number format)에서 소수점 자리(Decimal place) 설정
3. 스크린샷에서와 같이, 소수점 자리 설정이 '2'로 되어 있으나, 범례와 축에는 변경이 되지 않았음

**Expected behavior**
숫자 포맷의 소수점 자리 설정은 데이터 레이블, 툴팁 뿐 아니라, 범례와 축에도 모두 적용 되어야 합니다. 

**Screenshots**
![gihub-issues-decimalplace](https://user-images.githubusercontent.com/28885462/45612728-e25aca00-ba9e-11e8-8e45-aeff6775b22a.png)

**Comment by dave-taeho** [comment]
#251-decimal_places_not_working 브랜치 추가하였습니다.
