### ISSUE TITLE
Measure aliases cannot be changed.

### ISSUE THREAD

**Issue by nogah12** [metatron-app/metatron-discovery#2533]
**Describe the bug**

> In the following screenshot, the dimension values are aliased in the chart.
> Measures don't change alias

**To Reproduce**

> 1. Go to workbench 
> 2. Click on new chart
> 3. Change measure alias
> 4. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47097935/64102142-435fd880-cdaa-11e9-8b9b-025d0df82c02.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
The issue you reported happen with the original type in the table chart. The issue seems to need fixing, who can help?

**Comment by kyungtaak** [comment]
@minhyun2 👍
