### ISSUE TITLE
Support to show calculated column in table charts

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#2539]
**Is your feature request related to a problem? Please describe.**
현재 테이블 차트에는 행에 대한 연산 기능만 제공합니다. 추가로 열에 대한 연산 기능을 제공하고자 합니다.

**Describe the solution you'd like**
아래 처럼 기획해 보았습니다.
![image](https://user-images.githubusercontent.com/16472109/64138593-8f595e80-ce38-11e9-8a92-0554b8fe635a.png)

![image](https://user-images.githubusercontent.com/16472109/64138604-9b452080-ce38-11e9-8ded-6a96c868c1d9.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
@YooYoungmo 님 좋은 제안 감사합니다. 기획하신대로 진행하셔도 좋을것 같은데요. @AnnieHwang 님께서도 의견 부탁드립니다.
