### ISSUE TITLE
Network Diagram needed selection filter

### ISSUE THREAD

**Issue by esezin** [metatron-app/metatron-discovery#255]
**Describe the bug**
대시보드에서 네트워크 다이어그램은 셀랙션 필터가 동작하지 않습니다

**To Reproduce**
1. 차트선택 : 네트워트 다이어그램
2. 차트 생성 후 저장
3. 대시보드에서 네트워크 다이어그램의 노드, 연결선 클릭

**Expected behavior**
1. 대시보드에서 네트워크 다이어그램의 노드나 연결선을 클릭하면, 선택되면서 셀랙션 필터링 동작이 이루어져야 합니다.
2. 노드를 클릭시에는 해당 노드가 선택, 연결선 클릭시 에는 연결된 양쪽의 노드가 모두 선택되어야 하며, 다시 한번 클릭시에는 선택이 해제되어야 합니다.
3. 연결선 클릭을 통해 선택 해제를 하는 경우에는, 해제되는 노드가 만약 다른 연결선을 통해 선택되어 있다면, 그 선택은 계속 유지 되어야  합니다.
(생키 다이어그램의 동작 정의와 동일합니다)

**Comment by kyungtaak** [comment]
필터 위젯내에서 필터링시 이슈 입니다 서버측에서 나는 오류로 이를 수정하도록하겠습니다.
![image](https://user-images.githubusercontent.com/822255/46785711-97fefd00-cd6d-11e8-940e-d0fab0713e37.png)

**Comment by goodljy** [comment]
정상동작 확인함. 2018-10-18
