### ISSUE TITLE
Druid with Hadoop 3.1 dependicies.

### ISSUE THREAD

**Issue by Sidonet** [metatron-app/metatron-discovery#2601]
**Is your feature request related to a problem? Please describe.**

We are looking into Metatron application, and want to use HDFS as an ingestion source.

Our investigations show's us that this way is no working now.

Druid builded with 2.7.* HDP dependicies, and there is no way to launch correct application on cluster (YARN), because of HDP 3.1 used in our case.
(https://druid.apache.org/docs/latest/operations/other-hadoop.html - this recipes did not help.)

We build Druid 15 from github, and build it with HDP 3.1.1 dependicies, and it is a solution. Everything working as expected in hadoop_indexing area, but metatron.app is useless without customized Druid...

**Describe the solution you'd like**
Customized druid sources to build it with 3.1. dependicies.
Or builded druid with 3.1 dependicies.

**Comment by kyungtaak** [comment]
@Sidonet We will have a minor release early next week. At that point, we will consider providing a druid binary with 3.1 dependencies through a separate link. If the binaries are ready, I'll tell you right away.

**Comment by alchan-lee** [comment]
This issue seems to be resolved in our discussion page.
https://groups.google.com/forum/#!topic/metatron-discovery/LtDG3radneA

please feel free to re-open if you have any other problem.
Thanks.
