### ISSUE TITLE
Move when clicking on Dashboard and Workbench in Top Users

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2604]
# Move when clicking on Dashboard and Workbench in Top Users
 - Click on Dashboard Name / Workbench Name to open in new window (If you do not have permission, the Jump button will not be displayed.)
 - If there is no data usage, do not expose the area.

<img width="1471" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/64930779-bf5c2500-d86e-11e9-909f-4b5430a607ad.png">

**Comment by thinkcsww** [comment]
@ufoscw 
According to planning book, show jumping button if has permission.

![image](https://user-images.githubusercontent.com/35441780/65294972-e54d3680-db9a-11e9-9778-33b1d0fbe197.png)

hasPermission attribute in that screenshot is that permission?

**Comment by ufoscw** [comment]
@thinkcsww 
yes.

**Comment by AnnieHwang** [comment]
@ufoscw The icon should always be visible.

**Comment by ufoscw** [comment]
@thinkcsww 
please modify icon visible.
> @ufoscw The icon should always be visible.

**Comment by thinkcsww** [comment]
@ufoscw 
how about window icon in dashboard? 
![image](https://user-images.githubusercontent.com/35441780/65564126-e8736880-df86-11e9-9027-b1742bcaa8e3.png)

**Comment by thinkcsww** [comment]
@ufoscw 
Modified
