### ISSUE TITLE
Improve filtering and sorting for metadata list view

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2605]
# Metadata List filtering and sorting

### Filtering
 - Need to discuss filtering items

### Sorting 
 - Name
 - Popularity
 - Updated

### Change Column
 - Change "Modifier" to "Creator" and Column sequence must be after "Name" 

<img width="1306" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/64931123-604bdf80-d871-11e9-8c92-73416a17d039.png">

**Comment by thinkcsww** [comment]
@ufoscw 
In Exploration there user can choose multiple sourceType, but is it possible? 

![image](https://user-images.githubusercontent.com/35441780/65223132-740a7680-dafb-11e9-9358-f2da2efff2cf.png)

In Metadata management page i can't query multiple sourceType.

![image](https://user-images.githubusercontent.com/35441780/65223226-ad42e680-dafb-11e9-95fb-035f063de71a.png)

Is it possible to query multiple source type at once?

Or should i have to filter it without querying? Just process it in front side?

**Comment by thinkcsww** [comment]
@ufoscw 
I leave comment again just in case you forgot to reply.

Which filter should be used In exploration list screen for daya type? Multi or single ?

In Metadata management page multi dataType request is not working.

But in planning book select type is mulit 

![image](https://user-images.githubusercontent.com/35441780/65399338-0d38d600-ddf7-11e9-970a-1308ff49cb2d.png)

**Comment by ufoscw** [comment]
@thinkcsww 
Sorry for the late reply.
1. change sourceType parameter to List.

2. In addition to the above issue, remove the search scope before the search bar.
Basically, you can search by All scope.
<img width="616" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/65582157-d2ca6700-dfb7-11e9-8f78-61d78893b319.png">
