### ISSUE TITLE
Improved Recommended for Exploration Data

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2606]
# Improved Recommended for Exploration Data

 - Need for more efficient use of space
 - Display information to better represent metadata

<img width="1302" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/64931236-32b36600-d872-11e9-90ec-4116c1d240f5.png">

**Comment by AnnieHwang** [comment]
@ufoscw @thinkcsww The design has changed. Recommendation function UI has been removed. Details will be delivered in the Wireframe.
![image (101)](https://user-images.githubusercontent.com/6300003/65307512-e5612c80-dbc2-11e9-8a52-42195307d5cf.png)

**Comment by ufoscw** [comment]
@eltriny 
Is publishing going on?

**Comment by thinkcsww** [comment]
@ufoscw 
Publishing is scheduled to begin tomorrow

**Comment by thinkcsww** [comment]
@AnnieHwang 
![image](https://user-images.githubusercontent.com/35441780/65670350-2c966400-e080-11e9-8d33-ddd1e4ba10da.png)

According to the planniing book, Favorite creator area is filled with metadatas, 
however design is indicating something like user's information.

Api response is also metadata information not user's information. 

Can you give me some guidelines?

**Comment by AnnieHwang** [comment]
@thinkcsww  Favorite creator area has changed the contents as follows. 
![image (110)](https://user-images.githubusercontent.com/6300003/65756516-325b7a80-e150-11e9-9406-b389289feb34.png)

For more information, please refer to the wireframe "[M-Core] WF-E1.2-MDM-ExploreData-v0.417-1900927.pdf".

**Comment by thinkcsww** [comment]
@AnnieHwang 
Thanks

**Comment by thinkcsww** [comment]
@AnnieHwang
![image](https://user-images.githubusercontent.com/35441780/65851006-3e338080-e38c-11e9-86c8-0488ae2b3601.png)

All i need to do is just display creator and metadata name?

**Comment by AnnieHwang** [comment]
@thinkcsww please check to the wireframe "[M-Core] WF-E1.2-MDM-ExploreData-v0.417-1900927.pdf". It's different contents what you posted(captured)

**Comment by thinkcsww** [comment]
@AnnieHwang 
![image](https://user-images.githubusercontent.com/35441780/65862118-82cd1500-e3a8-11e9-992f-046093d832b8.png)

Is this version is wrong?

**Comment by ufoscw** [comment]
@thinkcsww 
This requires API modifications to fit the revised proposal.
I'll let you know after work.
please close pr.

**Comment by thinkcsww** [comment]
@ufoscw 
Ok

**Comment by ufoscw** [comment]
@thinkcsww 
Please open the PR after fixing the error below.
<img width="1585" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/65870302-e52d1200-e3b6-11e9-8f4e-e2d58cb2b924.png">


@AnnieHwang 
Favorite data is now coming out as an empty list.
Actual Favorite data will be added through Favorite implementation issues.
And should Carousel support the loop function in the screenshot above?
Please comment on whether the arrow is exposed.

**Comment by thinkcsww** [comment]
@ufocsw
![image](https://user-images.githubusercontent.com/35441780/65925686-c8332600-e42c-11e9-9842-6bd127de15ee.png)

show total or total -1 ?

**Comment by AnnieHwang** [comment]
@ufoscw @thinkcsww 
Carousel doesn't support the loop function.
Carousel is fixed and operated manually.
And if the data is less than 5, the button is not exposed.
Please remove the first and last arrows from the first and last page.

**Comment by thinkcsww** [comment]
@AnnieHwang 
Can user control the carousel by clicking bullet?

![image](https://user-images.githubusercontent.com/35441780/66287031-0047d680-e90f-11e9-9d03-a45dc78d51ff.png)

**Comment by ufoscw** [comment]
@thinkcsww 
This is the usual carousel behavior so make the page move on click.

**Comment by thinkcsww** [comment]
@ufoscw
Thanks

**Comment by thinkcsww** [comment]
@ufoscw 
Should i open pr first or waiting for api modification?

**Comment by ufoscw** [comment]
@thinkcsww 
The "favorite" API is going to work on each issue, so please open PR.
