### ISSUE TITLE
Operation formula is initialized in the text grid

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#262]
**Describe the bug**
연산행 설정 패널에서 '연산자 선택' 부분이 저장 후 다시 편집하려고 하면 초기화(합계) 되어 있는 현상

**To Reproduce**
1. Go to '연산 행 설정'
2. Click on '연산자 선택'을 '평균'으로 변경
3. 차트와 대시보드를 저장후 다시 차트 편집
4. '연산자 선택'이 다시 '합계'로 변경됨

**Expected behavior**
변경한 연산자 선택값으로 세팅되어야 합니다.

**Screenshots**
![2018-09-18_13-48-48](https://user-images.githubusercontent.com/6300003/45665184-a3824e00-bb4a-11e8-9f6e-375b875dbb6a.gif)

**Comment by goodljy** [comment]
정상동작 확인, 2018.10.18
