### ISSUE TITLE
Improves the Layers menu in the panel for dimension filters.

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#2625]
**Is your feature request related to a problem? Please describe.**
Change the menu form.

**Describe the solution you'd like**
Change the decision about how to sort and select to the submenu.

**Describe alternatives you've considered**

**Additional context**

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다 
![image](https://user-images.githubusercontent.com/42256760/65405022-eb9b1700-de15-11e9-8893-291400a11e6f.png)

**Comment by AnnieHwang** [comment]
@eltriny Please proceed development.
