### ISSUE TITLE
Fix when uppercase is included in postgresql table name

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2629]
**Describe the bug**
Workbench, datasource, and dataset errors when postgresql table name contains uppercase letters

**To Reproduce**
1. Create connection to postgresql
2. Create table with Upper case 
 ex) create table "Table1" (i int);
3. Create workbench, DataSource, DataSet.

**Expected behavior**
Should work normally without case sensitivity

**Screenshots**
![error_1](https://user-images.githubusercontent.com/3770446/65294874-85ef2680-db9a-11e9-955b-0480ab496b5e.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
Integrated test done.
