### ISSUE TITLE
Error in Average Calculation

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#263]
**Describe the bug**
텍스트그리드 차트에서 '연산 행 설정' 중 연산자를 '평균'으로 할 경우 값이 부정확합니다.

**To Reproduce**
0.56. 0.68, 0.8, 0.51 값의 평균은 계산해보면 0.6375 가 나와야 하지만, 지금 연산행 평균값은 0.66이 나옵니다.
값이 0.03정도 오차가 생깁니다.

1. Go to '연산행 설정'
2. Click on '연산자 선택' > '평균'선택

**Expected behavior**
평균값이 소수점 2자리까지 반올림된 0.64가 나와야 합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/45665241-eba17080-bb4a-11e8-910a-30c815e1b31c.png)

**Comment by Taehui** [comment]
@AnnieHwang, @kyungtaak 이 이슈는 오늘 패치 반영에는 포함 안되나요?

**Comment by AnnieHwang** [comment]
@Taehui 3.04에 반영될꺼 같아요. 반영예정인 이슈리스트에 현재 없거든요ㅠㅠ

**Comment by AnnieHwang** [comment]
sample link: http://52.231.184.181:8189/app/v2/workbook/abad27df-7bbe-4260-a491-dbdd41465a85
평균값을 계산한 결과에서는 값이 다르게 나오고 있으며, 합계값을 계산한 결과에서는 값이 노출되지 않는 현상이 있습니다.
AVG(SPEED 1/2), AVG(A.SPEED/FINISHER) 결과 값에서 확인 가능합니다.

**Comment by Taehui** [comment]
현재 0.64로 나오고 있습니다. 무언가 반영이 된 듯 하네요~

**Comment by eltriny** [comment]
@Taehui @kyungtaak 
본 이슈는 #37 이슈를 처리하면서 같이 수정한 내용입니다.
