### ISSUE TITLE
Error for changing column order in table chart when changing column in shelf

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#2632]
**Describe the bug**
When changing column in shelf, it changed only column order not contents in table chart 

**To Reproduce**
1. Go to 'Dashboard' linked any datasources.
2. Create chart widget and select table chart
3. Put any dimension column on row shelf
4. Put any measure column on aggregation shelf
5. Put measure column same as number 4 stage on aggregation shelf
   (It will be adjusted aggregation type automatically.) 
6. Try to change column order on aggregation shelf

**Expected behavior**
When changing column in shelf, it changed column order with contents in table chart 

**Screenshots**
![changing_order_error](https://user-images.githubusercontent.com/822255/65386635-4f233700-dd79-11e9-818b-acd52c3e08b3.gif)

**Desktop (please complete the following information):**
 - any environment

**Additional context**
(N/A)

**Comment by eltriny** [comment]
![api-response](https://user-images.githubusercontent.com/3685833/65488466-2d928e80-dee4-11e9-9ea8-1536a38731e3.png)
@kyungtaak 
Data query results come in a different order than requested.
Please check it.

**Comment by kyungtaak** [comment]
solved with #2663 :)
