### ISSUE TITLE
Unify charset detecting code

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#2640]
**Is your feature request related to a problem? Please describe.**
Detecting charset and read as the charset is very important.
Currently, datasource ingestion (a.k.a. common util) code and data preparation code both have their own implementations.

**Describe the solution you'd like**
I will modify them to use common code with as little modification as possible.

**Additional context**
Data preparation code has a lot of its own internationalized error codes, but in the unified implementation many of them would be useless. (maybe they will be deleted together)

**Comment by ksparknot** [comment]
[test_lineage.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3695573/test_lineage.csv.txt)
[test_lineage_utf32_little.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3695574/test_lineage_utf32_little.csv.txt)
[test_lineage_utf32_big.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3695575/test_lineage_utf32_big.csv.txt)
[test_lineage_utf16_little.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3695576/test_lineage_utf16_little.csv.txt)
[test_lineage_utf16_big.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3695577/test_lineage_utf16_big.csv.txt)
[test_lineage_utf8_bom.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3695578/test_lineage_utf8_bom.csv.txt)

the files for testing UTF BOM
