### ISSUE TITLE
Aggregate Function in MapView

### ISSUE THREAD

**Issue by dinhthengoc2021998** [metatron-app/metatron-discovery#2676]
**Is your feature request related to a problem? Please describe.**
I dont see the aggregation function such as SUM,COUNT,... on the shelf of Mapview.
![image](https://user-images.githubusercontent.com/39497214/66038961-bbeabe00-e53d-11e9-8e89-428f87712f46.png)

**Describe the solution you'd like**
I want to use some Aggregation Function to calculate the total of Profit for each city and show it on Mapview

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
@dinhthengoc2021998 As shown in the screen capture below, in point type, a condition that can be aggregated only in hexagon mode is established. In the point mode that you selected, the display method can be changed depending on the value of the point.
![image](https://user-images.githubusercontent.com/822255/66172504-eac07b80-e686-11e9-99cc-cc6d5cc2b12b.png)

If you want to aggregate points within a certain area, such as a city, you need to have a data source for the city, including polygon data.
Then display the polygon data on the second layer and set it as shown below in the "Analysis" tab.

![image](https://user-images.githubusercontent.com/822255/66173759-dda68b00-e68c-11e9-8fe9-236b8c7bca30.png)

And please refer to the link : https://metatron.app/2019/05/02/building-a-simple-map-view/

**Comment by dinhthengoc2021998** [comment]
Thank you so much, i followed this link which you gave me and it's met the demand what i looked for.
