### ISSUE TITLE
UI enhancements for engine (druid) monitoring

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2680]
**Describe the bug**
UI enhancements for engine (druid) monitoring (in Overview Screen)
- Add sync selection button
- General tooltip
- Segment Count tile

![image](https://user-images.githubusercontent.com/6300003/66187523-e95f7500-e6bf-11e9-9dcc-c3f523eaa495.png)

Look at pink rectangles!

**Comment by kyungtaak** [comment]
@AnnieHwang In the Ingestion tab, there is an item I want to add in the supervisor details.
There is a list of tasks that depend on Supervisor. How about displaying them together as below image?

![image](https://user-images.githubusercontent.com/822255/66298387-8f171c00-e92c-11e9-8069-edbfd3fa129a.png)

**Comment by AnnieHwang** [comment]
@kyungtaak @minhyun2 If we really need the content, i'll be fine in that location. But I have not yet heard the need for the content. Let's discuss it with the druid engineer @seoeun25 .

**Comment by AnnieHwang** [comment]
@koeun222 We have changed the 'Task' and 'Supervisor' tab details UI in the 'ingestion' menu. Please design that UIs.

**Comment by AnnieHwang** [comment]
@koeun222 We have changed the time filter widget UI. Please design that UI.
