### ISSUE TITLE
Engine Monitoring - add to show datasources information

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2681]
**Is your feature request related to a problem? Please describe.**
This is the third menu of Engine Monitoring, the Datasource screen.
It consists of the state value and the segment list of the created datasource.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/6300003/66186228-b5368500-e6bc-11e9-9c61-2f9e73473ee2.png)
and detail view..
![image](https://user-images.githubusercontent.com/6300003/68734661-6dd9d780-061e-11ea-9591-b5259ec0c9f0.png)

**Comment by koeun222** [comment]
디자인 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/67731672-5acee100-fa3c-11e9-9113-96ec510902ba.png)

**Comment by AnnieHwang** [comment]
@minhyun2 The design is complete.
![D6-03Datasource-01Detail](https://user-images.githubusercontent.com/6300003/68753166-e3a66900-0647-11ea-8c63-48907ff57bdc.png)

**Comment by AnnieHwang** [comment]
@koeun222 The UX wireframe has changed. I would like an existing design change.
![image](https://user-images.githubusercontent.com/6300003/69292465-9c246c00-0c49-11ea-99a2-e954e20f71c8.png)
![image](https://user-images.githubusercontent.com/6300003/69292562-cbd37400-0c49-11ea-8460-67fc6d80925a.png)

**Comment by AnnieHwang** [comment]
@koeun222 
There are also two screen design fixes.
1) Details of the red squares have been changed.
2) 2 dialog popups should be added. Please refer to the image.

![image](https://user-images.githubusercontent.com/6300003/69409060-9a42d180-0d4b-11ea-97e8-e1d3ac36cf14.png)

![image](https://user-images.githubusercontent.com/6300003/69409183-bfcfdb00-0d4b-11ea-8f4d-6afd8df9a0a0.png)
![image](https://user-images.githubusercontent.com/6300003/69409203-cb230680-0d4b-11ea-8573-ffe41941a763.png)

**Comment by AnnieHwang** [comment]
@minhyun2 The list screen has been redesigned. Please check it.
![D6-03Datasource-00List (1)](https://user-images.githubusercontent.com/6300003/69409488-60be9600-0d4c-11ea-949f-bbe66cb6866f.png)

**Comment by AnnieHwang** [comment]
@minhyun2 
The design is complete.. Please check it.

![D6-03Datasource-01Detail (1)](https://user-images.githubusercontent.com/6300003/69843817-7122c380-12ac-11ea-8a74-22bf1d022027.png)
![D6-03Datasource-01Detail-Scheme](https://user-images.githubusercontent.com/6300003/69843819-7122c380-12ac-11ea-90bb-75502690c40d.png)
![D6-03Datasource-01Detail-RuleEdit](https://user-images.githubusercontent.com/6300003/69843820-71bb5a00-12ac-11ea-90d9-5cbf711f4909.png)

**Comment by AnnieHwang** [comment]
@koeun222 Please add design. An additional button is required when hovering over the data source.
![image](https://user-images.githubusercontent.com/6300003/70295983-51e7e100-182c-11ea-821f-cb17b594a944.png)
![image](https://user-images.githubusercontent.com/6300003/70295989-557b6800-182c-11ea-8141-0f3447123b64.png)
