### ISSUE TITLE
If you change from a dark theme to a general theme and refresh the screen, it appears as a dark theme instead of a general theme

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#2696]
**Describe the bug**
다크 테마에서 일반 테마로 변경하고 화면을 새로고침(브라우저) 하면 일반 테마가 아닌 다크 테마로 나타남.

**To Reproduce**
1. 일반 테마에서 다크테마로 변경
![image](https://user-images.githubusercontent.com/16472109/66547213-b31b6d00-eb79-11e9-8659-6732e04168ec.png)
![image](https://user-images.githubusercontent.com/16472109/66547224-b878b780-eb79-11e9-84ba-7dab7d20cc86.png)
2. 일반 테마로 다시 변경
![image](https://user-images.githubusercontent.com/16472109/66547239-c3cbe300-eb79-11e9-85ad-c23b8107383b.png)
3. 브라우저 새로고침
일반 테마를 사용하고 있는 중임에도 불구하고 다크테마로 돌아감
![image](https://user-images.githubusercontent.com/16472109/66547259-cf1f0e80-eb79-11e9-9649-6b25591a36a4.png)

**Expected behavior**
브라우저를 새로고침 하더라도 마지막으로 사용한 테마가 유지되어야 함.

**Screenshots**

**Desktop (please complete the following information):**
 - OS : macOS Mojave
 - Browser Chrome
 - Version 77.0.3865.90

**Additional context**

**Comment by minhyun2** [comment]
@YooYoungmo I'll fix it.
