### ISSUE TITLE
Show more information for applied Column Dictionary and Code Table

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2758]
**Is your feature request related to a problem? Please describe.**
It is difficult to check the information of the Column Dictionary and Code Table applied to Metadata Column.

1. Management Metadata
<img width="1602" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/67442132-97fd3280-f63a-11e9-9c79-96e0945516d1.png">

2. Exploration Data
<img width="1609" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/67442227-d72b8380-f63a-11e9-85ee-abd91b18de5f.png">

**Describe the solution you'd like**
When hovering over it is necessary to show the summary information layer.
Like this.
<img width="218" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/67442318-443f1900-f63b-11e9-85a8-3d4a488f3b4f.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by ufoscw** [comment]
@thinkcsww 
The issue content is described in Wireframe.

1. Code Table Layer
<img width="1009" alt="_M-Core_WF-E1_2-MDM-ExploreData-v0_417-1900927_pdf_22_40페이지_" src="https://user-images.githubusercontent.com/3770446/67835644-d8264e80-fb2d-11e9-976c-9e05b559091e.png">

2. Column Dictionary Layer
Please remove the Dictionary Catalog from the scope of development.
The Detail button should only be exposed in Management and not in Exploration.
<img width="1260" alt="_M-Core_WF-E1_3-MDM-Management-v0_417-190830_pdf_20_122페이지_" src="https://user-images.githubusercontent.com/3770446/67836689-9c40b880-fb30-11e9-8d75-11d1efd766ea.png">

**Comment by thinkcsww** [comment]
@ufoscw 
1.
![image](https://user-images.githubusercontent.com/35441780/67840627-a31ff900-fb39-11e9-9a9b-dda407edb36d.png)
Is it right to show this part in layer ?

2. Do you mean implement layer except Detail button and Dictionary Catalog?

**Comment by ufoscw** [comment]
@thinkcsww 
1. yes.
2. Please except Dictionary Catalog.
and except "Detail" button in case of Exploration > Detail view Layer.

**Comment by thinkcsww** [comment]
@ufoscw 
Sorry i'm little bit confused.
Is it right?
Implement code table and dictionary layer in two screen
1. management-> exploration -> metadata -> columns
   - Except Dictionary Catalog
   - Include Detail button

2. Exploration -> detail modal -> columns
    - Except Dictionary Catalog and Detail button

**Comment by ufoscw** [comment]
@thinkcsww 
yes. right.

**Comment by thinkcsww** [comment]
@ufoscw 
thanks

**Comment by thinkcsww** [comment]
@ufoscw 
![image](https://user-images.githubusercontent.com/35441780/67913888-d9a95280-fbd1-11e9-9af8-a2d046693fae.png)
Need codeTable.codes data but i think api is not working

**Comment by ufoscw** [comment]
@thinkcsww 
please use code table detail api when layer open. 
```
(GET) /api/codetables/{id}?projection=forDetailView
```

**Comment by thinkcsww** [comment]
@ufoscw 
Thanks

**Comment by ufoscw** [comment]
@thinkcsww 
Please just disable the magnifying glass icon, not the entire text.
<img width="569" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/68005291-22d3d200-fcb8-11e9-91a6-34a5c1ac6109.png">
