### ISSUE TITLE
Embedded dashboard can set filter value with request query parameter

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#277]
**Is your feature request related to a problem? Please describe.**
Embedded dashboard의 경우 외부 시스템의 화면에서 metatron의 dashboard를 보여줄 경우 사용한다. 이 경우 외부 시스템에서는 dashboard의 필터에 특정 값을 자동으로 설정해야 하는 경우가 있는데 이를 위해 request query parameter에 값이 있으면 이 값을 이용하여 dashboard의 filter의 값을 설정한다.

**Describe the solution you'd like**
- dashboard 구성 시 filter를 추가한다.
- query parameter에 다음과 같이 요청한다.
```
http://127.0.0.1/app/v2/dashboard/573769d5-126e-450e-b4ac-b2c6491ecaba?order_date=20170101&product_code=P1234
```
- filter의 field명과 parameter의 key의 필드명이 같은 경우 자동으로 filter의 값을 설정한다. 
- 처음에 나타나는 데이터도 이 필터가 적용된 데이터가 나타난다.

**Describe alternatives you've considered**
- 구현 방식은 대략 두가지를 생각해 볼 수 있다.
   1. Server의 DashboardController에서 parameter를 처리하여 dashboard configuration의 filter 기본 값을 설정하여 전달하는 방식
  2. Front-end에서 request parameter를 이용하여 dashboard configuration을 변경하는 방식

- DashboardController에 기능을 추가하는 것은 `@RepositoryRestController` 이 기능을 사용하여 자동으로 생성되는 코드가 처리해주고 있기 때문에 이 기능을 위해 별도로 메소드를 다시 만들어야 하는 번거러움이 있음. 따라서 Front-end에서 스크립트로 처리하는 두번째 방식으로 구현

**Additional context**
- 없음

**Comment by i1befree** [comment]
+1

**Comment by kyungtaak** [comment]
@babokim 이런 상태면 멀티데이터 소스/Join 된 데이터 소스상에 대해서는 고려가 되지 않는데요. filter 속성내 ref/dataSource 의 관계를 금번 릴리즈 또는 다음 릴리즈 내로 정리할 예정이오니, 그 이후에 진행하였으면 합니다.

**Comment by babokim** [comment]
@kyungtaak 이 이슈는 일반적인 상황에서 사용하는 것이 아니라 Embedded 되는 경우에만 사용하는 거라서 스펙상 Embedded는 JOIN 관련 Filter는 추후에 적용할 예정이라고 하고 진행하면 되지 않을까요?

**Comment by kyungtaak** [comment]
@babokim 네, 확인했습니다. 3.0.4 버전에 릴리즈 될 예정입니다.
