### ISSUE TITLE
Support custom script for chart widget on dashboard

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#2803]
**Is your feature request related to a problem? Please describe.**
There are currently needs for limited event control or some chart reshaping in chart widgets placed on structured dashboards. It is an external alarm transmission when used as a dashboard, especially for monitoring purposes. It may be necessary to add event display control in the chart.

현재 정형화된 대시보드에 배치된 차트 위젯에서 제한적이나마 이벤트 제어나 일부 차트 형태 변경에 대한 니즈가 있습니다. 특히 모니터링 용도로 대시보드로 사용시 외부 알람 전송이다, 차트내 이벤트 표시 제어가 추가 될 필요할수 있습니다. 

**Describe the solution you'd like**
Users can write a custom script using the function interface we provide in the widget and make it work accordingly.
- Supported Event examples : DataLoadEvent, SelectionFilterEvent
- Chart representation examples: emphasis, baseline

**Describe alternatives you've considered**
Further discussion is needed on how to enter scripts and how to validate accordingly.
스크립트 입력을 어떻게 할지, 이에 따른 검증을 어떻게 할지 추가적인 논의가 필요합니다.

**Additional context**
(N/A)

**Comment by kyungtaak** [comment]
@AnnieHwang please help me! :)

**Comment by AnnieHwang** [comment]
@koeun222 Add an icon to the 'Dashboard> Chart Widget' and design a widget panel(text area).
![image](https://user-images.githubusercontent.com/6300003/68019427-0e570000-fcdf-11e9-883b-0b2e9330e9f7.png)

**Comment by AnnieHwang** [comment]
@eltriny @kyungtaak The design is complete. Please, check it.
![image (122)](https://user-images.githubusercontent.com/6300003/68109100-12785d00-ff2d-11e9-9260-12fd83ee19c6.png)

**Comment by i1befree** [comment]
We need to expose function parameters in script editor.
