### ISSUE TITLE
Improved overview screen on data exploration

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2805]
**Describe the bug**
Tile UI doesn't show data features too repeatedly Need improvement

1) _If data is of type datasource, the first dashboard thumbnail is shown._ (**removed**)
2) 'No data' notification label required when no data
3) The font size of the title is too large. (I think 22px seems reasonable) => it's a publishing issue.
4) _Header(Exploration header, search area) replacement - remove intro the header_ (**move to another issue #2894**)
5) Catalog panel changed
- Caroussel UI
- If there is no 1depth, no path should be indicated (In case of 'favorite catalog')
- 'All catalog' panel is activated on first entry

**To Reproduce**
1. Go to 'Exploration > Data'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/68457706-3cd75c80-0244-11ea-9809-1fecdffa6ceb.png)
![image](https://user-images.githubusercontent.com/6300003/68457794-75773600-0244-11ea-8a7c-cbe430c49e14.png)
![image](https://user-images.githubusercontent.com/6300003/68725866-17ab6b00-0603-11ea-8d3e-b3d8e0ce11a1.png)
![image](https://user-images.githubusercontent.com/6300003/68820344-50fcdd00-06ce-11ea-961f-071b71f7f83e.png)

**Comment by thinkcsww** [comment]
@AnnieHwang 
1)If data is of type datasource, the first dashboard thumbnail is shown.
-Is this a bug? or Do you mean display thumbnail of first dashboard of datasource  if type is datasource?

4) Header(Exploration header, search area) replacement - remove intro the header
- can you explain more about this?

**Comment by AnnieHwang** [comment]
@thinkcsww 1) Deleted once. I will tell you after registering a new issue.
4) It's a new issue. # 2894

**Comment by thinkcsww** [comment]
@AnnieHwang 
Then in this issue todos are 
1. No data' notification label required when no data
2. The font size of the title is too large. (I think 22px seems reasonable) => it's a publishing issue.
3. Catalog panel changed
Caroussel UI
If there is no 1depth, no path should be indicated (In case of 'favorite catalog')
'All catalog' panel is activated on first entry

Is it Right?

**Comment by AnnieHwang** [comment]
@thinkcsww The design is complete. Please, check it.
<img width="1048" alt="스크린샷 2019-11-15 오후 4 14 39" src="https://user-images.githubusercontent.com/6300003/69404517-d6246980-0d40-11ea-9ad4-93dafbeb1c71.png">

**Comment by thinkcsww** [comment]
@AnnieHwang 
The number is for which feature?
![image](https://user-images.githubusercontent.com/35441780/69515688-b8e6d980-0f92-11ea-835c-3301995471c1.png)

**Comment by AnnieHwang** [comment]
@thinkcsww This number is the number of metadata belonging to the catalog.

**Comment by ufoscw** [comment]
@thinkcsww 
Metadata numbers in catalog favorites are not included in the API. How are you counting the numbers?

**Comment by eltriny** [comment]
@ufoscw 
It is not counting. Must be provided in api

**Comment by ufoscw** [comment]
@eltriny 
Please develop without counting.
It will be added to the API later.
