### ISSUE TITLE
Exploration Catalog's CSS Bug

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2806]
**Describe the bug**
### 1. Exploration > Catalog Bold
Bold is applied to open Catalog.
Please remove bold on opened Catalog.
<img width="306" alt="metatron_Discovery_및_Slack___i1befree___metatron" src="https://user-images.githubusercontent.com/3770446/68093777-7a528780-fedc-11e9-9c95-b9ac0777dad4.png">

### 2. LNB Folding icon direction and tooltip z-index
Icon direction does not change when folded.
and toop z-index error.

 - Default
<img width="379" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/68093804-ce5d6c00-fedc-11e9-89a8-ada415ced8bc.png">

 - Folded
<img width="397" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/68093826-23997d80-fedd-11e9-87d9-407a35088035.png">

**Comment by ufoscw** [comment]
@thinkcsww 
There is another issue.
The additional information displayed when the mouse is over does not match the intention of Wireframe.
Delete the Mouse Over event and show all the information without mouse over.

<img width="430" alt="metatron_Discovery" src="https://user-images.githubusercontent.com/3770446/68173841-9bd86f80-ffbf-11e9-8a00-2b09766e16f3.png">

**Comment by thinkcsww** [comment]
@ufoscw
About  hovering issue.
Publisher told me height of each items is changed  according to the additional information.
If hover feature is removed its impossible to fit the height.
What would be the proper way?

![image](https://user-images.githubusercontent.com/35441780/68259588-8fb2e780-007d-11ea-9e46-b439f882bcd6.png)

**Comment by ufoscw** [comment]
@AnnieHwang 
Please check the comments below.
> @ufoscw
> About hovering issue.
> Publisher told me height of each items is changed according to the additional information.
> If hover feature is removed its impossible to fit the height.
> What would be the proper way?
> 
> ![image](https://user-images.githubusercontent.com/35441780/68259588-8fb2e780-007d-11ea-9e46-b439f882bcd6.png)

**Comment by AnnieHwang** [comment]
@thinkcsww @ufoscw 
1)Tag, Description in one line
2) If there is no information about tag and description, put 'no description' label and leave a fixed space line by line.
3)If there is a lot of information in the tag, compress it more than a certain width, such as '+1'.
