### ISSUE TITLE
Create one workbook with API

### ISSUE THREAD

**Issue by AlejandroITOP** [metatron-app/metatron-discovery#2817]
I have a problem and I need to create a workbook via API but I don't know if this is possible.

In the document API rest show list dashboards but no create.This is possible ?

**Comment by kyungtaak** [comment]
@AlejandroITOP Of course, there are APIs for creating workbooks. However, it is not shown due to a lack of documentation.  Actually, we need to add the necessary APIs to each domain in discovery. 
In the meantime, I will try to add the API method related to the workbook.

**Comment by AlejandroITOP** [comment]
Okei, perfect and thanks for the answer
