### ISSUE TITLE
app.metatron.discovery.prep.parser.antlr.RuleBaseVisitor not find

### ISSUE THREAD

**Issue by FourSpaces** [metatron-app/metatron-discovery#2825]
Cannot find package in source code
app.metatron.discovery.prep.parser.antlr

```  java
package app.metatron.discovery.prep.parser.preparation;

import static java.util.stream.Collectors.toList;

import app.metatron.discovery.prep.parser.antlr.RuleBaseVisitor;
import app.metatron.discovery.prep.parser.antlr.RuleLexer;
import app.metatron.discovery.prep.parser.antlr.RuleParser;
```
Code in line 19 linked below
[link](https://github.com/metatron-app/metatron-discovery/blob/b66c94f2555adca429a51cf0523efb2e303e0a94/discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/RuleVisitorParser.java)

I can't build into an app。

**Comment by ufoscw** [comment]
@FourSpaces 
The antlr package is an autogenerated package.
Running the maven build will generate an antlr package.

**Comment by FourSpaces** [comment]
> @FourSpaces
> antlr软件包是一个自动生成的软件包。
> 运行Maven构建将生成一个antlr软件包。

Compile the entire project?

**Comment by ufoscw** [comment]
@FourSpaces 
If you build only the discovery-prep-parser project, the antlr package source will be generated.
```
discovery-prep-parser $ mvn clean install -DskipTests
```
<img width="463" alt="metatron-discovery-build3____Documents_GitHub_metatron-discovery-build3__-_____discovery-prep-parser_src_main_java_app_metatron_discovery_prep_parser_preparation_RuleVisitorParser_java__discovery-prep-parser_" src="https://user-images.githubusercontent.com/3770446/68352166-e9ccaf00-0148-11ea-82a6-ae3afea44673.png">

**Comment by FourSpaces** [comment]
> @FourSpaces
> If you build only the discovery-prep-parser project, the antlr package source will be generated.
> 
> ```
> discovery-prep-parser $ mvn clean install -DskipTests
> ```
> 
> <img alt="metatron-discovery-build3____Documents_GitHub_metatron-discovery-build3__-_____discovery-prep-parser_src_main_java_app_metatron_discovery_prep_parser_preparation_RuleVisitorParser_java__discovery-prep-parser_" width="463" src="https://user-images.githubusercontent.com/3770446/68352166-e9ccaf00-0148-11ea-82a6-ae3afea44673.png">

**Comment by joohokim1** [comment]
@FourSpaces Compiling the entire project will solve the problem.
If it doesn't, please let me know with the compile output.

**Comment by FourSpaces** [comment]
Thank you very much and I've built it
