### ISSUE TITLE
Improved MDM screen (admin page)

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#2856]
**Is your feature request related to a problem? Please describe.**
1) /* move to issue 2894 */
2) Tab order changed ('Column Scheme' first, 'Data Grid' next)
3) Add data type beside data name (in metadata detail page)
4) UI align issue (in metadata detail page) - a publishing issue
5) Metadata's description must be up to 2000 characters - a development issues
6) UX change (Metadata details => Code table detail => Code table popup, Metadata details => Column dictionary detail => Column dictionary popup)

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/6300003/68732521-11bf8500-0617-11ea-80a5-7cf081f0ef16.png)

![image](https://user-images.githubusercontent.com/6300003/68741254-7cc98580-0630-11ea-97d1-05f699c7b086.png)
![image](https://user-images.githubusercontent.com/6300003/68741397-daf66880-0630-11ea-8edc-79c9e29645c9.png)
![image](https://user-images.githubusercontent.com/6300003/68745672-72ac8480-063a-11ea-9a78-2c00ba497a76.png)
![image](https://user-images.githubusercontent.com/6300003/68749199-2add2b80-0641-11ea-9032-0904a3f53be6.png)
![image](https://user-images.githubusercontent.com/6300003/68749209-2fa1df80-0641-11ea-9fc7-0bd5574b7e1e.png)

**Comment by thinkcsww** [comment]
@AnnieHwang 
3. Add data type beside data name (in metadata detail page) 
 - Will Design be changed? 
6. UX change (Metadata details => Code table detail => Code table popup, Metadata details => Column dictionary detail => Column dictionary popup)
 - Will Design be chagned?

**Comment by AnnieHwang** [comment]
@thinkcsww 
1. The detail page does not have GNB change. There is a GNB change only in the list screen.
-Only change the position of 'Column Scheme' tab and 'Data Grid' tab.
-Put the data type next to the title.
2. Your design will be available soon.

**Comment by AnnieHwang** [comment]
@thinkcsww The design is complete.Please check it. (number 6)
![D6-05Query-00List-QueryInformation (1)](https://user-images.githubusercontent.com/6300003/69843898-d8d90e80-12ac-11ea-90e5-6230ecc3c84d.png)

**Comment by thinkcsww** [comment]
@AnnieHwang 
Thanks.
Is Column Dictionary in progress?

**Comment by AnnieHwang** [comment]
@thinkcsww That's right. I added an image to the comment above.

**Comment by thinkcsww** [comment]
@AnnieHwang 
Can you explain detail about 
6.UX change (Metadata details => Code table detail => Code table popup, Metadata details => Column dictionary detail => Column dictionary popup) ?

Remove detail page and replace by popup?

What should be happend when click go to dictionaryand go to code table?

**Comment by AnnieHwang** [comment]
I've met in @thinkcsww and completed the explanation.
