### ISSUE TITLE
Improve preview stage of progress on stream Datasource creation

### ISSUE THREAD

**Issue by minhyun2** [metatron-app/metatron-discovery#2857]
Is your feature request related to a problem? Please describe.
Improve stream data source

Describe the solution you'd like
Management > Data Storage > Datasource >Create > stream
1. Improve UX preview sample data
2. CSV format sample files are supported.

**Comment by AnnieHwang** [comment]
@koeun222 We need to improve the design below.
![_M-Core_WF-D1-DataStorage-v1_50-191104](https://user-images.githubusercontent.com/6300003/68736769-ee9bd200-0624-11ea-8d28-e2f19796acae.jpg)

**Comment by kyungtaak** [comment]
@AnnieHwang @koeun222 We do not use the term schema after the topic. I hope you make a phrase that means that you can set up the schema on the next stage through the data in the topic.

**Comment by AnnieHwang** [comment]
@minhyun2 The design is complete. I will upload the label after modifying the wireframe.

![D1-01Datasource-01Create-stram1-2 (1)](https://user-images.githubusercontent.com/6300003/69395975-28a35d00-0d24-11ea-9fc6-316e6b922111.png)
