### ISSUE TITLE
How does metatron druid configure the cluster

### ISSUE THREAD

**Issue by FourSpaces** [metatron-app/metatron-discovery#2866]
How does metatron druid configure the cluster？

**Comment by kyungtaak** [comment]
@FourSpaces This document is used internally, can you try it? And please let me know if you have any problems.
[[Metatron] Druid Cluster Install Guide_ver1.1.pdf](https://github.com/metatron-app/metatron-discovery/files/3856363/Metatron.Druid.Cluster.Install.Guide_ver1.1.pdf)
