### ISSUE TITLE
Kafka + Druid in stream datasource

### ISSUE THREAD

**Issue by AlejandroITOP** [metatron-app/metatron-discovery#2880]
Hello, I am currently implementing the real-time visualization that they published in the article
[https://metatron.app/2018/08/02/visualize-real-time-data-with-metatron-discovery/](url) .
Following this tutorial I have encountered problems and I would like to know if you could help me.
1. I have executed in python the kafka producer as it is in the article only by uncommenting the option "producer = KafkaProducer (bootstrap_servers = 'localhost: 9092')", the bootstrap server is located on the local machine.
2. I have created the datasource of type "stream" through API Rest with the same body raised in the example.
3. Reviewing, both the metatron datasource and the kafka topic have been created but although the producer continues to inject data it does not show me any in the datasource or only shows three, example:
![Captura](https://user-images.githubusercontent.com/50695114/69134632-b75b7400-0aaf-11ea-9b0b-1f2987fc276d.PNG)
I don't know what the mistake may be.

**Comment by comefeel99** [comment]
Looking at the screen, the granularity, segGranularity is a bit suspicious.


From the data source screen From the detail screen

Segment granularity
Query Granularity

![post-realtime7](https://user-images.githubusercontent.com/28386734/69203635-358b4980-0b88-11ea-8ac6-8726bdfdc511.png)

Check the value.

**Comment by kyungtaak** [comment]
@AlejandroITOP I've used the data generator and request body for API we provided in that blog post. But I couldn't reproduce. So, Could you provide more information for me? 
- data generator source code
- request body (if you tried to use API)
- screen capture - schema configuration, ingestion configuration  (if you tried from UI)

**Comment by AlejandroITOP** [comment]
Thanks, here you have additional information.I did everything via API.

**Data generator code:**

import sys
import json
import math
from datetime import datetime
from time import sleep
from kafka import KafkaProducer

producer = KafkaProducer(bootstrap_servers=['localhost:9092'], value_serializer=lambda x: json.dumps(x).encode('utf-8'))

list_category = ['10', '20', '30']
for i in range(0, 100000):
        for cur_cate in list_category:
                cur_result = {};
                cur_result['time'] = datetime.strftime(datetime.utcnow(), "%Y-%m-%dT%H:%M:%SZ");
                cur_result['category'] = cur_cate
                cur_result['value_01'] = int(math.sin(i/float(cur_cate))*100)*1;
                cur_result['value_02'] = int(math.sin(i/float(cur_cate))*100)*2;
                cur_result['value_03'] = int(math.sin(i/float(cur_cate))*100)*3;
                jcur_result= json.dumps(cur_result)
                print(jcur_result)
                producer.send('realtime_sample', cur_result)
                sys.stdout.flush()
                producer.flush()
        sleep(1)

**Request body used:**

{
    "name": "metatron_realtime_sample_02",
    "description": null,
    "dsType": "MASTER",
    "connType": "ENGINE",
    "srcType": "REALTIME",
    "granularity": "SECOND",
    "segGranularity": "DAY",
    "ingestion": {
        "type": "realtime",
        "topic": "realtime_sample",
        "consumerType": "KAFKA",
        "consumerProperties": {
            "bootstrap.servers": "localhost:9092"
        },
        "format": {
            "type": "json"
        },
        "rollup": true
    },
    "fields": [
        {
            "name": "event_time",
            "alias": "event_time",
            "type": "TIMESTAMP",
            "logicalType": "TIMESTAMP",
            "role": "TIMESTAMP",
            "format":{
              "type":"time_format",
              "format":"yyyy-MM-dd'T'HH:mm:ssZ",
              "timeZone":"Asia/Seoul",
              "locale":"en"
            },
            "seq": 0
        },
        {
            "name": "category",
            "alias": "category",
            "type": "STRING",
            "logicalType": "STRING",
            "role": "DIMENSION",
            "seq": 1
        },
        {
            "name": "value_01",
            "alias": "value_01",
            "type": "DOUBLE",
            "logicalType": "DOUBLE",
            "role": "MEASURE",
            "seq": 2
        },
        {
            "name": "value_02",
            "alias": "value_02",
            "type": "DOUBLE",
            "logicalType": "DOUBLE",
            "role": "MEASURE",
            "seq": 3
        },
        {
            "name": "value_03",
            "alias": "value_03",
            "type": "DOUBLE",
            "logicalType": "DOUBLE",
            "role": "MEASURE",
            "seq": 4
        }
    ]
}

I have noticed that in some cases when I create the data source if I access the druid console there is no such data source could this be the problem? Could it be that you are not creating well in druid?

**Comment by minhyun2** [comment]
@AlejandroITOP 
In the data generator code, you set the column name of the time value to **time**.
However, the timestamp column name when creating the datasource is **event_time**.
Please set both column names the same.
