### ISSUE TITLE
Different policies should be applied for reading JSON 

### ISSUE THREAD

**Issue by ksparknot** [metatron-app/metatron-discovery#2893]
**Is your feature request related to a problem? Please describe.**
if an object is empty, the line should be passed
and the list of key name depends on the first line

**Comment by joohokim1** [comment]
By this issue,
1. column name and count is decided by the 1st row of the JSON file.
2. if a line does not compose a valid JSONObject, it's skipped without any exception.
3. if a key (=column name) is missing in the JSONObject, the column is null. So, {} makes an all-null row.
5. if the 1st row is {}, an exception is thrown. (Cannot proceed any with no column)

Closing.
