### ISSUE TITLE
Can it be Sinicization?

### ISSUE THREAD

**Issue by qinchaofeng** [metatron-app/metatron-discovery#291]
Can it be Sinicization?

**Comment by i1befree** [comment]
Sure. We welcome internationalization.
Currently we only support English and Korean. We want to expand language set. 
I would really appreciate it if you can help. I am going to write about how to extend the language support of metatron this week.

**Comment by qinchaofeng** [comment]
> Sure. We welcome internationalization.
> Currently we only support English and Korean. We want to expand language set.
> I would really appreciate it if you can help. I am going to write about how to expand the language support of metatron this week.

 one year ago, I have contributed to   Apache Zeppelin.I'm interested in this project ,also want to contribute to this project.

**Comment by kyungtaak** [comment]
Thank you for you interesting. 

Soon after we started open source, we did not have a developer guide document. 😅
If you're okay, I will arrange to provide my colleagues with a separate guide about internationalization.

And, as you know, South Korea is also on holiday(Thanksgiving Day). Please understand even if providing guide is late.

@eltriny Please check this comment.

**Comment by eltriny** [comment]
@qinchaofeng 
We will provide a whole guide later 
but we will guide you through the language setting first.
discovery-frontend / src / assets / i18n and create json with local as the name.
In the # f291-sinicization branch, Chinese related files have been added to the above path. (The contents are in English.)
After you change the contents of the file, you can change the language setting of the browser to see the changes.

**Comment by kyungtaak** [comment]
@qinchaofeng We have been supporting Chinese since 3.1.0. If you have any problems, I would appreciate it if you report it. :)

**Comment by qinchaofeng** [comment]
@kyungtaak  You should use simplified Chinese instead of traditional Chinese，Also,I will modify some of them,some like this"個共享工作空間的業主 給我吧"

**Comment by kyungtaak** [comment]
@qinchaofeng Long time no see. :) Are we now Chinese to support Traditional? I knew it was simplified Chinese.(Actually, I don't know Chinese). Anyway,  I will appreciate it if you correct the problematic content.

**Comment by qinchaofeng** [comment]
@kyungtaak  OK! Recently, I will take time to correct the problematic content
