### ISSUE TITLE
Install version 3.4.0.rc testing

### ISSUE THREAD

**Issue by AlejandroITOP** [metatron-app/metatron-discovery#2919]
We are trying to install version 3.4.0 of metatron for testing. The problem is that the compilation does not work because it returns these errors:

[WARNING] npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
[ERROR] npm notice created a lockfile as package-lock.json. You should commit this file.
[WARNING] npm WARN @fimbul/bifrost@0.21.0 requires a peer of typescript@>= 3.3.0 || >= 3.6.0-dev || >= 3.7.0-dev but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @fimbul/ymir@0.21.0 requires a peer of typescript@>= 3.3.0 || >= 3.6.0-dev || >= 3.7.0-dev but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN angular2-moment@1.9.0 requires a peer of @angular/core@>=2.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN karma-jasmine-html-reporter@1.4.0 requires a peer of jasmine-core@>=3.3 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN ng2-codemirror@1.1.3 requires a peer of @angular/core@^2.1.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN ng2-codemirror@1.1.3 requires a peer of @angular/forms@^2.1.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN ng2-codemirror@1.1.3 requires a peer of @angular/common@^2.1.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN ng2-dnd@4.2.0 requires a peer of @angular/core@^2.4.4 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
[INFO] audited 40597 packages in 22.604s
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[INFO] found 21 vulnerabilities (12 low, 2 moderate, 7 high)
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
[ERROR] 

I'm trying to download the final binary file since "mvn clean install -DskipTests" but I can't find it anywhere so I can't install metatron. Could you help me or know what the compilation failure might be?

**Comment by minhyun2** [comment]
@AlejandroITOP 
fsevents is dealt differently in mac and other linux system. Linux system ignores fsevents whereas mac install it. As the above error message states that fsevents is optional and it is skipped in installation process.
You can run **npm install --no-optional** command in linux system to avoid above warning.

**Comment by AlejandroITOP** [comment]
Even using the command that still does not work now I can not start the rpm run prod command.


[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:npm (npm run build) on project discovery-frontend: Failed to run task: 'npm run prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :discovery-frontend

**Comment by minhyun2** [comment]
@AlejandroITOP 
Could you provide node and npm version?
