### ISSUE TITLE
Fix closing is not propagated over yielder of concat sequence

### ISSUE THREAD

**Issue by navis** [metatron-app/metatron-discovery#2936]
Regression from #2810 ?

It's reported by missing metric `query/segment/time`, `query/segmentAndCache/time`

**Comment by seoeun25** [comment]
In `next()` method of ConcatSequence#wrapYielder,  `makeYielder()` is prevent to call `yielder.close`.


```
      @Override
      public Yielder<OutType> next(OutType initValue)
      {
        final Yielder<OutType> next = yielder.next(initValue);
//        if (next.isDone()) {
//          // fixing NPE
//          return makeYielder(yielderYielder.next(null), null, accumulator);
//        }
        return wrapYielder(next, yielderYielder, accumulator);
      }
```

**Comment by seoeun25** [comment]
** expected **
![segment_metric](https://user-images.githubusercontent.com/764939/70115596-96944080-16a3-11ea-8d68-3bacf9b49d96.png)

@minhyun2
