### ISSUE TITLE
Realtime segment is not visible at console

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#2937]
Regression since #2930 .

SystemSchema.segment table can not provide realtime segment.

**Describe the bug**
![segment_realtime_invisible](https://user-images.githubusercontent.com/764939/70113865-ac066c00-169d-11ea-9ab1-4e4b70bb095c.png)
![segment_unavailbale](https://user-images.githubusercontent.com/764939/70113870-b0cb2000-169d-11ea-9dcc-5da92bc287b7.png)

**Expected behavior**
Realtime segment should be visible.

![segment_expected](https://user-images.githubusercontent.com/764939/70113796-6cd81b00-169d-11ea-905f-8d49c9fc88fd.png)

**Comment by seoeun25** [comment]
@minhyun2 참고하세요.

**Comment by navis** [comment]
기존 SQL 이 부팅시 모든 세그먼트에 대해 meta query 를 날려서 결과를 저장하고 있는데, icube 같이 segment 가 많은 시스템에서는 부팅 시간도 그렇고 메모리 사용량도 많고 해서 이 부분을 통채로 날려 버리고 실제 쿼리 타임에 필요한 meta query 를 날리도록 수정하였습니다.

sys.segments 가 이 정보를 이용하던 놈인데 이것땜에 전체 segment 에 대해 meta query 를 날릴수는 없으니 broker 의 timeline view 에 있는 segment 정보를 이용하는 것으로 수정하였습니다. 그런데 아쉽게도 num_rows 같은 정보는 여기에 없어요. 요기까지 #2930 ..

historical node 의 경우 loading 시 segment announce 과정에 num_rows 을 넣어주도록 수정했는데, realtime node 는 그걸 할수가 없네요, 그래서 0 으로 나옵니다. #2937 ..

나중에 정말로 필요하면 background 로 update 하도록 수정하던가.. 해야 겠네요.
