### ISSUE TITLE
Improvements for real-time dashboard

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#2954]
**Is your feature request related to a problem? Please describe.**
- The functionality for synchronization could only be set in dashboards linked with realtime
 datasources. In addition, activating the sync feature is hidden, making it inconvenient to use.
  - When applying sync to an entire dashboard, not all widgets need to be applied.
- Requires data processing of chart widget for real time environment.

**Describe the solution you'd like**
- We need to adjust the sync-related features: Open the sync feature on all data source types, and set up something(?..button?) to limit the sync for each widget.
- In the real-time environment, the method of loading data in the chart widget brings the increment from the last view time to the current view time.

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by kyungtaak** [comment]
@AnnieHwang Can you check the design of the real-time dashboard that was considered at the beginning and design this features?

**Comment by AnnieHwang** [comment]
@kyungtaak 
Share the UI wireframe. Please tell me if there is anything strange.

![image](https://user-images.githubusercontent.com/6300003/70592344-d071c380-1c1c-11ea-8251-114f996d3750.png)
![image](https://user-images.githubusercontent.com/6300003/70592358-dcf61c00-1c1c-11ea-99d4-1f255da6277b.png)
![image](https://user-images.githubusercontent.com/6300003/70592369-e97a7480-1c1c-11ea-981b-5a7b1ef76c53.png)
![image](https://user-images.githubusercontent.com/6300003/70592385-fa2aea80-1c1c-11ea-964c-79a472875a1a.png)

**Comment by AnnieHwang** [comment]
@eltriny @kyungtaak The design is complete. After UI publishing, please proceed with development.
![image](https://user-images.githubusercontent.com/6300003/70762660-b78c1e00-1d94-11ea-92f9-23699ae26ae5.png)
