### ISSUE TITLE
fix color type script bug in pie chart

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#296]
**Describe the bug**
- 파이차트의 색상설정에서 dimension에서 measure로 변경시 스크립트 에러발생

**To Reproduce**
1. 대시보드 편집화면에서 신규차트 생성 버튼을 클릭합니다.
2. 차트 타입을 파이차트로 선택하고, dimension / measure 필드를 각각 하나씩 선택하여 선반에 등록합니다.
2. 오른쪽의 컬러 설정 패널에서 color타입을 dimension에서 measure로 변경합니다.
3. 스크립트 에러가 발생합니다.

**Expected behavior**
- 색상타입을 measure로 변경시 에러가 발생하지 않아야 합니다.

**Screenshots**

**Desktop (please complete the following information):**
- OS: iOS
- Browser : chrome
- Version : 69.0

**Additional context**

**Comment by juheeko9** [comment]
f#296-pie_chart_error 브랜치 생성하였습니다.
