### ISSUE TITLE
Column timestamp format incorrect

### ISSUE THREAD

**Issue by AlejandroITOP** [metatron-app/metatron-discovery#2971]
Hi, I have created a stream type data source to use together with druid and kafka. The fact is that I am entering data into a json like this:
[
![image](https://user-images.githubusercontent.com/50695114/70800628-a21ef000-1da4-11ea-84a3-2a7a70ec9cbe.png)
](url)

The problem is that the following is arriving in the datasource:
[
![image](https://user-images.githubusercontent.com/50695114/70800767-f9bd5b80-1da4-11ea-874b-5a85fec92a50.png)
](url)
As you can see the dates do not match at all and I always put one from the first to the last when I am putting data every minute.
The structure of the datasource that you create for the timestamp field is as follows:
{
            "name": "event_time",
            "alias": "event_time",
            "type": "TIMESTAMP",
            "logicalType": "TIMESTAMP",
            "role": "TIMESTAMP",
            "format":{
              "type":"time_format",
              "format":"yyyy-MM-dd HH:mm:ss",
              "timeZone":"Atlantic/Canary",
              "locale":"es"
            },
            "seq": 0
        }

**Comment by kyungtaak** [comment]
@AlejandroITOP The criteria for specifying the time data format and timezone should be based on the data you want to load. And, In the UI, you can see the time converted according to the browser timezone. Therefore, the time format and time zone should be specified as follows.
```
{
...,
"format":"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
"timeZone":"UTC",
"locale":"en"
}
```
