### ISSUE TITLE
Message key value is displayed. Sometimes?

### ISSUE THREAD

**Issue by ninezero90hy** [metatron-app/metatron-discovery#2972]
**Describe the bug**
Message key value is displayed. Sometimes?

**To Reproduce**
1. Continue to refresh the screen Until the problem is reproduced

**Expected behavior**
You should show the message to the user

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 79.0.3945.79

**Additional context**
https://drive.google.com/file/d/1egBaf9I_raJhG7ri9NvluEfSCks343mC/view?usp=sharing
Be patient and watch the video. The video time is one minute!

**Comment by kyungtaak** [comment]
@eltriny Could you check this issue?

**Comment by ninezero90hy** [comment]
This problem has been forgotten
