### ISSUE TITLE
Add a guide to connect muliti-datasources.

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#3]
**Is your feature request related to a problem? Please describe.**
- 대다수의 사용자가 대시보드 생성시 멀티데이터 소스를 연결하는 과정에 어려움을 느낍니다. 

**Describe the solution you'd like**
- 멀티데이터 소스를 연결하는 과정에 대한 스크린 가이드를 추가 합니다. 
![screen_guide](https://user-images.githubusercontent.com/822255/43999287-93d66536-9e44-11e8-9078-9549f5a3feed.png)

**Describe alternatives you've considered**
- 매번 나타나지 않도록 별도의 정책이 필요합니다. 

**Additional context**

**Comment by kyungtaak** [comment]
@metatron-app/design @MinjungMagenta  arrow 표시로는 부족한 느낌입니다.  모두 "Done" 을 생각할것 같아요. 
![image](https://user-images.githubusercontent.com/822255/44518350-f6f8ac00-a704-11e8-818a-7fe18512f1af.png)
X 버튼이 어색하다면, "ok" "got it" 이런 느낌을 주는것은 아이콘을 하단에 두는건 어떠실런지요? 검토 부탁드립니다.

**Comment by MinjungMagenta** [comment]
@kyungtaak 네, 시안을 보니 혼선이 있을것 같기도 합니다. @AnnieHwang  "got it!" 텍스트 버튼 넣는 것 어떨까요? 좀 가벼운 디자인으로요

**Comment by AnnieHwang** [comment]
@MinjungMagenta @kyungtaak 네 좋을것 같습니다~ 디자인 진행 부탁드려요!

**Comment by ufoscw** [comment]
@metatron-app/design 
Edit Association 버튼을 눌러 화면 진입 했다가 Done으로 돌아가면 DataSource 타원 크기가 살짝 변하네요.
의도된 부분인지 확인 바랍니다.
