### ISSUE TITLE
Docker installation can not work with volumes

### ISSUE THREAD

**Issue by heronfonsaca** [metatron-app/metatron-discovery#3025]
**Describe the bug**
Docker installation of Metatron Discovery (https://hub.docker.com/r/metatronapp/discovery) does not manage to persist data from volumes and correctly re-use them.

**To Reproduce**
1. Create docker containers using the Docker Installation Guide (https://metatron.app/download/installation-guide-docker/):
```bash
docker run -i -d --rm -m 6G -p ${HOST_DISCOVERY_PORT:=8180}:8180 \
-v /apps/host_volume/druid:/usr/local/druid-backup \
-v /apps/host_volume/mysql:/usr/local/mysql-backup \
--name metatron-discovery metatronapp/discovery:latest
```

2. Stop Metatron container.
3. Start it again.
4. It will not be able to run it again.

**Expected behavior**
After restart the container the volumes should be able to load all saved data from MySQL and Druid.
I'm pretty sure there is something wrong with the script "start-mysql.sh" but after many attempts I can't find a way to make MySQL work again manually.

**Logs**
My docker logs from the container show something wrong with MySQL after restarting the container:
```
2020-01-09 20:20:34,189 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-01-09 20:20:35,628 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140053954092712 for <Subprocess at 140053954044416 with name mysql in state RUNNING> (stdout)>
2020-01-09 20:20:35,628 INFO exited: mysql (exit status 1; not expected)
2020-01-09 20:20:35,628 DEBG received SIGCLD indicating a child quit
2020-01-09 20:20:36,631 INFO spawned: 'mysql' with pid 1781
2020-01-09 20:20:36,639 DEBG 'mysql' stdout output:
mysql data doesn't exists!!

2020-01-09 20:20:36,655 DEBG 'mysql' stdout output:
rm: cannot remove '/var/lib/mysql': Device or resource busy

2020-01-09 20:20:36,678 DEBG 'mysql' stdout output:
2020-01-09T20:20:36.678744Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2020-01-09T20:20:36.678804Z 0 [ERROR] Aborting
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Docker: Docker 19.03.5, build 633a0ea838

**Comment by alchan-lee** [comment]
@heronfonsaca Sorry for the delayed response.
I've written the [document](https://metatron.app/download/installation-guide-docker/) about docker persistence that linked to the body. 

But I noticed that important content is missing from the document,
I will contact the homepage operator and it will be added soon.

**Comment by alchan-lee** [comment]
I leave the missing contents here.
And many thanks for your very important contribution.

(TL;DR)
Add **-e PERSIST_DISCOVERY=TRUE** option when you (re)start a metatron-discovery docker.

---
One more important thing is the option for running Metatron Discovery application.
By default, Metatron Discovery run with --init option for docker container for initialize the database per every users. It is necessary for the first execution.

So, if you decide to keep the data, you must add a new environment variable from the next time you run it.

-	PERSIST_DISCOVERY=TRUE

Except for the very first time, please be sure to include this setting.



Finally, you can run a container with these options for persist data.

-v {HOST_DIR_FOR_DRUID}:/usr/local/druid-backup \
-v {HOST_DIR_FOR_MYSQL}:/usr/local/mysql-backup \
-e PERSIST_DISCOVERY=TRUE

 ‘PERSIST_DISCOVERY=TRUE’ option is required from the second run. It must be omitted for the first time in your entire environment.
At first, persist the data by just setting up the volume (-v), then add environment (-e) setting from the next run.

---

**Comment by alchan-lee** [comment]
The document has been updated.

I close this issue but if you have more queries about it, please feel free to reopen.
Thanks.

**Comment by heronfonsaca** [comment]
It works, @alchan-lee !
Thank you for the solution.

I was wondering if you have ever thought about using Docker Compose to deploy Metatron Discovery as a multiple containers composition (for each service), Lee. I guess that breaking down the single container could make the whole app more easily to manage, test and deploy.

I guess it would be something like:
```yaml
services:
    mysql:
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
    druid:
        ...
    metatron_discovery:
        ...
volumes:
    mysql_data:
    druid_data:
```
What are your thoughts about this ideia?
Thank you again for the support.
