### ISSUE TITLE
Express the loading process on the dashboard

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#304]
**Is your feature request related to a problem? Please describe.**
데이터가 너무 많은 경우 혹은 알 수 없는 이유로 대시보드의 로딩바가 계속 도는 경우가 있습니다. 이 경우 어느 프로세스까지 진행되었는지 파악이 되지 않습니다

**Describe the solution you'd like**
단계를 나누어 프로그래스바를 만들어 상태를 보여줬으면 좋겠습니다. (ex. druid에서 데이터 조회완료, 서버 로직 수행, 화면 표출중)

**Comment by Taehui** [comment]
@AnnieHwang @kyungtaak 로딩이 오래걸리는 경우가 발생하는데, 어느 단계에서 막혀있는 것인지 알고 싶습니다. 사전 논의드릴 때는 사용자 UX 에 표현되면 좋지만 컨셉이 맞지 않는 부분은 별도의 관리 기능으로 빠져도 괜찮을 듯 하다는 의견을 드렸습니다.

**Comment by minjung-cho** [comment]
@AnnieHwang 프로그래스 UI는 다른 화면에서 사용하는 것을 활용하면 됩니다만.. UI와 무관하게 일정 시간이 지나면 진행을 취소시키고 데이터가 많아서 진행할 수 없고, 데이터소스의 필수필터(또는 추천필터)를 추가하라는 메시지를 주는 것이 좋을 것 같습니다.

**Comment by kyungtaak** [comment]
@Taehui @minjung-cho @AnnieHwang 제안하신 단계별 내용으로 처리는 사실상 어려운 상황입니다.
#620 이슈와 같이 기본 차트 제한 건수 두어 차트를 좀더 빠르게 확인할수 있도록 할 예정입니다.
따라서, 이 이슈는 일단 종료시키도록하겠습니다.
