### ISSUE TITLE
Add sqlQueryId and metrics at SQL

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#3043]
현재 Query를 하는 방식은 2가지로 나눌 수 있다.
1. Native Query (json)
2. SQL  (avatica  포함)

현재 Query metrics는 Native query만 지원하였으나, 이 이슈를 통해 SQL query에 대한 metric 을 추가 하여 druid-metric datasource 에서 쿼리 정보를 조회할 수 있다.

**Metrics**
Broker에 query를 하면 다음과 같은 metric이 생긴다. 
 
dim | Native Query | SQL 
------------ | ------------- | -------------
id | O (historical metric에서 id 와 동일) | O
sqlQueryId | X | O (historical metric에서 sqlQueryId 와 동일)
nativeQueryIds | X | O (historical metric에서 id 와 동일)
query/time | O | O
query/bytes | O | O (avatica는 지원 안함)
rows | O | O (avatica는 지원 안함)

* SQL로 query 한 경우, sqlQueryId 값이 있다.
* Historical이나 middleManger에서 해당 query의 metric을 조회 할 경우, Native Query 는 id를, SQL은 sqlQueryId를 사용한다.

`SELECT  "__time",  "sqlQueryId", "id",  "type", "host","server", "service", "metric", "value", "success"
FROM "druid-metric"
WHERE 
service='druid/broker' and metric LIKE '%query/time%'
ORDER BY "__time" DESC
LIMIT 100`

**Comment by seoeun25** [comment]
@minhyun2 님 참고하세요.

**Comment by seoeun25** [comment]
* SqlLifecyle class is used by SqlResource and DruidStatement.
* Add getDataSourceNames() at DruidRel.

**Comment by navis** [comment]
이거 왜 따로 있어야 되는거죠?  id 만 있으면 안됨?

**Comment by seoeun25** [comment]
sqlQueryId와 queryId를 하나로 할까 하다가 sql 과 native query 를 구분하기 위해서 따로 뒀습니다.
두 가지 안을 생각하다 1안으로 구현했어요. (개인적으로는 2안을 많이 고민했으나 아파치쪽 구현이 1안 방식임. 물론 아파치쪽 구현방식과는 차이가 있음)

*1안*
1. broker에서 query 요청이 sql이면 sqlQueryId를 따로 생성하고 이를 sql 과 native query의 구분자로 사용한다.

*2안*
broker에서 query 요청이 생기면 sql이던 native query이던 모두 queryId를 사용하고 요청 type 을 구분할 수 있는 구분 필드를 만든다.
