### ISSUE TITLE
Schema Browser Error in Workbench

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#305]
**Describe the bug**
* 워크벤치내 데이터베이스, 메타데이터를 변경할 시 스키마 브라우저에서 오류가 발생합니다.

**To Reproduce**
1. 워크벤치 화면으로 이동합니다.
2. 좌측에 스키마 브라우저를 띄웁니다.
3. 테이블을 선택하고 다른 데이터베이스로 변경합니다.
4. 변경한 데이터베이스의 메타데이터 탭을 선택하면 오류가 발생합니다.

**Expected behavior**
오류 발생없이 정상적으로 동작해야 합니다.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 69

**Additional context**

**Comment by sting009** [comment]
#305 이슈 브랜치 생성 하였습니다.
