### ISSUE TITLE
custom color setting error in bar chart

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#307]
**Describe the bug**
- 바차트에서 color by series로 선택 후 custom color setting 색설정 후 저장 후 조회시 반영이 되지않는 오류발생

**To Reproduce**
1. 바차트를 선택 후 선반에 dimension / measure를 한개씩 등록합니다.
2. color setting에서 color by series로 선택 후 custom color setting에서 색상을 설정합니다.
3. 차트를 저장합니다.
4. 저장한 차트를 재조회시 custom color setting에서 설정한 색상이 반영되지 않습니다.

**Expected behavior**
- 선택 저장한 custom color setting 색상이 조회시 설정되어야합니다.

**Screenshots**

**Desktop (please complete the following information):**
- OS: iOS
- Browser : chrome
- Version : 69.0

**Additional context**

**Comment by juheeko9** [comment]
f#307-custom_color_setting_error 브랜치 생성하였습니다.
