### ISSUE TITLE
If the combo chart is selected, the screen will be distorted when 'fit to data scale'

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#312]
**Describe the bug**
콤보 차트를 선택한 경우 set axis range에서  fit to data scale 선택하면 콤보차트 Y축이 밀려 내려옵니다 (샘플위치: http://52.231.184.181:8189/app/v2/workbook/99ee6ac2-2399-4ac0-bed5-2b9a1aa7f9d8)

**To Reproduce**
1. 콤보차트 선택
2. 차원값 1개, 측정값 4개를 피봇팅함
3.' set axis range'패널에서  'fit to data scale' 체크

**Screenshots**
![2018-09-21_11-17-27](https://user-images.githubusercontent.com/6300003/45865612-0c6efd80-bdb9-11e8-8124-076a5114b720.gif)

**Comment by eltriny** [comment]
@kyungtaak @AnnieHwang 
확인결과 echart 최신버전에서는 해당 문제가 해결된것을 확인하였습니다.
다만 현재 echart 최신버전의 경우 현재 적용된 버전에서 단순 기능뿐 아니라
옵션의 의미가 변경된 부분이 많아 (예를들어 색상 적용 정책등) 모든 차트의 옵션을 전체적으로 다시 점검 & 수정해야 합니다.
이 작업은 본 이슈와는 별도의 이슈로 관리되어야 할 듯 하며, 작업 시간 및 영향이 크기 때문에 진행에 대해서 별도로 논의 되어야 할거 같습니다.

**Comment by eltriny** [comment]
@kyungtaak @AnnieHwang 
현재 angular 및 echart 업그레이드가 적용된 master 에서 정상적으로 실행되는 것을 확인했습니다.
확인해보시고 이상없으시면 본 이슈는 닫도록 하겠습니다.

**Comment by kyungtaak** [comment]
@eltriny 이슈를 종료합니다.
