### ISSUE TITLE
Errors that can not be color changed by series

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#313]
**Describe the bug**
시리즈의 컬러 변경이 안되는 현상

**To Reproduce**
1. 차트상세화면에서
2. 차원값 1개, 측정값 여러개를 선택
3. 색상패널로 가서
4. 시리즈 별 측정값 1개의 색을 변경
5. 차트 저장

**Screenshots**
![2018-09-21_14-22-26](https://user-images.githubusercontent.com/6300003/45865771-81423780-bdb9-11e8-9e5a-51953ffa0dfb.gif)

**Comment by juheeko9** [comment]
@AnnieHwang #307에서 진행중입니다.

**Comment by eltriny** [comment]
#307 이슈를 통해서 수정된 사항이므로 이슈를 닫겠습니다.
