### ISSUE TITLE
Chart type UI not visible

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#315]
**Describe the bug**
차트 타입 UI가 안보이는 현상

**To Reproduce**
1. Go to '차트 상세'
2. 차원값 1개, 측정값 여러개
3. 측정값의 aggregation 변경
4. 차트 저장
5. 차트 타입 UI가 깨짐

**Screenshots**
![2018-09-21_11-13-23-1](https://user-images.githubusercontent.com/6300003/45866054-7e941200-bdba-11e8-864c-cb4b10ab61db.gif)

**Comment by juheeko9** [comment]
f#315-shelve_animation_error 브랜치 생성하였습니다.
