### ISSUE TITLE
Be able to save the query results as a hive table in workbench.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#320]
**Is your feature request related to a problem? Please describe.**
Hive 쿼리 결과를 Hive Table 로 저장할 수 있는 기능
![query-result](https://user-images.githubusercontent.com/612173/45879283-d8a6ce80-bdde-11e8-8a36-de5a075db211.jpg)
현재는 Druid Datasource 로 저장하는 기능만 존재함

**Describe the solution you'd like**
스크린샷 옆에 "Save as hive table" 아이콘 추가 및 저장을 위한 UX 연결

**Additional context**
권한 문제가 있을 수 있는데, Hive 컨넥션에 유저별 권한 설정을 할 수 있으므로, 권한이 있는 컨넥션이면 저장가능하도록 구현

**Comment by Taehui** [comment]
@babokim 께서 제안해 주시기로는, Writing 권한이 있는 관리자 Connection 을 Metatron 에 주는 것에 대해서 말씀하셨는데 개인데이터베이스 생성 이슈와 더불어, 기획 내용에 포함시켜 주시면 좋을 듯 합니다. 이 경우에는 하둡 에코시스템 관리자가 컨넥션별로 모든 유저와 데이터베이스를 관리할 필요가 없어집니다.

**Comment by AnnieHwang** [comment]
@kyungtaak @Taehui 저희 개발팀에서 해당 내용 논의 결과, connection에 property (별도의 UI 없이) 로 해당 내용 설정 하면 워크벤치에서 다운로드 시 hive table로 다운로드 하는 버튼 혹은 타입 추가(이부분은 기획내용에 반영하겠습니다.)로 해결하면 어떤가 하는 답변을 들었습니다. 이렇게 진행하면 되는거 맞죠?

**Comment by YooYoungmo** [comment]
@Taehui @kyungtaak @AnnieHwang 개발된 화면 공유 합니다. 부족하거나 잘못된 부분 혹은 개선 할 부분이 있다면 알려 주세요.

---

Hive 테이블로 저장하는 기능은 워크벤치에서 질의를 하는 경우 그 결과를 HDFS(Hadoop Distributed File System)에 저장합니다. 그리고 사용자가 질의 결과를 'Save as Hive' 하면 메타트론에 로그인한 사용자의 ID로 Hive에 개인 데이터베이스를 생성하고 여기 테이블에 생성하여 HDFS에 저장되어 있는 데이터를 테이블로 LOAD 하는 방식입니다.

### 데이터 커넥션 생성 화면
워크벤치에서 Hive 테이블로 저장하는 기능을 사용하기 위해서는 데이터 커넥션에서 추가적으로 정보를 입력합니다.
![image](https://user-images.githubusercontent.com/16472109/47914606-8a0f4880-dee3-11e8-97d6-8cc4c0823726.png)
![image](https://user-images.githubusercontent.com/16472109/47914657-c773d600-dee3-11e8-8873-72a952072b48.png)
* Hive admin user, 'Hive admin password
  * Hive에서 데이터베이스 및 테이블 생성 그리고 데이터 로드 권한을 가지는 관리자 계정 정보입니다.(위의 코멘트에서 언급 되었던  'Writing 권한이 있는 관리자' 참조)
* Hive personal database prefix
  * 테이블이 만들어 질 때 메타트론에 로그인한 사용자의 ID로 데이터베이스명이 만들어지기 때문에 워크벤치에서 데이터베이스 목록에 다른 사용자의 데이터베이스까지 보일 수 있습니다. 따라서 데이터베이스를 만들 때 접두사를 붙혀 개인 데이터 베이스임을 구분하고 이를 이용하여 데이터베이스 목록에서 다른 메타트론 사용자의 데이터베이스를 제외하기 위해서  사용합니다.
* HDFS configuration path
  * HDFS(Hadoop Distributed File System에 질의 결과를 저장해야 하기 때문에 HDFS 접속 설정 정보가 필요합니다. HDFS를 HA(High Availability)로 구성하는 경우 접속 하기 위한 설정이 복잡해지기 때문에 메타트론 서버 특정 디렉토리에 HDFS 설정 파일(core-site.xml, hdfs-site.xml)을 넣어두고 이 디렉토리를 입력 받아 이를 통해 HDFS에 접근합니다.

### 워크벤치 > 질의 실행
쿼리 에디터에서 질의를 실행하면 질의 결과 HDFS에 파일로 저장합니다.
![image](https://user-images.githubusercontent.com/16472109/47915626-cdb78180-dee6-11e8-8b88-f587d6276591.png)

### 워크벤치 > Save as Hive Table
'Save as Hive Table' 버튼을 누르면 테이블 이름을 입력 받는 대화 상자가 나타납니다.
![image](https://user-images.githubusercontent.com/16472109/47915709-0e16ff80-dee7-11e8-8375-8fb7bc5640f5.png)

![image](https://user-images.githubusercontent.com/16472109/47915763-3d2d7100-dee7-11e8-90c2-24e280862d22.png)

대화 상자에서 'Done'을 클릭하면 메타트론에 로그인한 사용자의 ID로 데이터베이스를 만들고(없는 경우) 입력한 테이블을 생성합니다. 그리고  HDFS에 저장된 파일을 LOAD 합니다. 이 과정에서 테이블이 이미 존재하는 경우 사용자에게 알람으로 알려 줍니다.

**Comment by YooYoungmo** [comment]
Save as hive table 동작 방식은 아래와 같습니다.
![image](https://user-images.githubusercontent.com/16472109/48929904-0cfa5080-ef30-11e8-98f7-612c1c6e315c.png)
