### ISSUE TITLE
 Representing dimension ​​or measure values as column logical names

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#321]
**Is your feature request related to a problem? Please describe.**
차트의 차원값 또는 측정값을 MDMS 에서 관리하는 Logical 컬럼명으로 표현할 수 있어야 함
![logical_name](https://user-images.githubusercontent.com/612173/45910502-9a43fa80-be44-11e8-8a9e-21ecb3f51e06.png)
현재는 스크린샷과 같이 물리명으로만 표현이 가능하며, 논리명 확인을 위해 한번 이상의 클릭이 필요하기 때문에 차원값과 측정값이 매우 많은 Datasource 의 경우 관련정보를 확인하는데 효율적이지 못함

**Describe the solution you'd like**
- 가장 선호하는 방식은 Toggle 방식이 좋으나 대시보드 편집모드의 설정을 통해서 표현하는 것도 괜찮을듯
- 논리명이 없는 경우에 대한 고려 필요 (없으면 물리명으로 표현하는 등)

**Comment by AnnieHwang** [comment]
@Taehui  해당내용은 10월 1차 적용 후 개선사항을 도출하여 재기획 후 반영하도록 하겠습니다.

**Comment by AnnieHwang** [comment]
@kyungtaak 금주 월요일 DT포탈 인터뷰를 하였으며, 개선사항을 도출하여 10월 말 개발일정에 맞춰 기획안 재 공유해드리도록 하겠습니다. (전에 10월말부터 MDM 2차 개발 예정이라고 하셨는데.. 혹시 일정에 변경 있으신가요?)

**Comment by deidera08** [comment]
@AnnieHwang 와 논의하여 다음과 같이 기획되었습니다.

1. 대시보드 생성시 물리/논리 이름 타입을 설정 할 수 있습니다.
![01_](https://user-images.githubusercontent.com/42257766/47698050-19e99400-dc51-11e8-9622-5f454b5b9c56.png)

2. 대시보드 생성 후에도 레이아웃 설정에서 이름 타입을 설정 할 수 있습니다.
![02_](https://user-images.githubusercontent.com/42257766/47698058-1ce48480-dc51-11e8-92ff-f207db665d75.png)

3. 대시보드에서 설정된 이름타입은 대시보드 내 모든 이름 표현에 영향을 미칩니다.
![03_](https://user-images.githubusercontent.com/42257766/47698062-1eae4800-dc51-11e8-9855-01ad9b20bf2a.png)

4. 데이터 상세화면에서도 이름타입을 선택할 수 있으나, 이것은 설정은 아니고 단지 화면에서 노출명만 바꿔 볼 수 있습니다.(검색어에 영향을 미침)
![04_](https://user-images.githubusercontent.com/42257766/47698063-2110a200-dc51-11e8-88dc-8e20eb7d3a6b.png)

**Comment by AnnieHwang** [comment]
@deidera08 @Taehui 어제 내부 회의결과 재 논의된 기획 내용이 있습니다. 위의 기획 내용은 일단 삭제 혹은 무시해주시기 바랍니다. 다시 재 기획되면 해당 이슈에 남겨두겠습니다. 감사합니다.

**Comment by Taehui** [comment]
@AnnieHwang 네, 알겠습니다.

**Comment by AnnieHwang** [comment]
해당내용 클로즈 하고 신규 MDM기획 이슈로 재 생성하기로 하곘습니다. 감사합니다.
