### ISSUE TITLE
Metadata information should also be exposed to users

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#322]
**Is your feature request related to a problem? Please describe.**
현재는 메타데이터 관련정보가 MANAGEMENT 하위 구성으로 관리자에게만 노출되고 있음
![metadata](https://user-images.githubusercontent.com/612173/45913735-b7dc8880-be73-11e8-9eef-6e8323eee1a0.png)

**Describe the solution you'd like**
- 사용자에게도 메타정보가 노출되어야 함
- 수정 권한에 대해서 사용자에게 부여할지 등 권한 관리에 대한 기획 필요

**Comment by i1befree** [comment]
Meta 데이터를 위한 사용자 페이지는 별도로 개발할 예정이며, WORKSPACE, MANAGEMENT 처럼 같은 레벨로 존재하는 것으로 기획 됐습니다. @AnnieHwang 기획 문서도 올려 주시면 좋겠습니다.

**Comment by kyungtaak** [comment]
@ufoscw  metadata 사용자 뷰는 신규 이슈로 생성하여 진행 부탁드립니다.
@Taehui 다른 개발건으로 해당 개발 작업이 지연이 되고 있습니다. 별도 이슈 생성시 릴리즈 계획을 수립하여 공유 드리도록 하겠습니다.  정보전달이 되셨으면 이슈 종료 부탁드립니다.
