### ISSUE TITLE
Add map chart in supporting chart list

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#324]
**Is your feature request related to a problem? Please describe.**
- Map Chart 에 대한 신규 지원 필요
![chart](https://user-images.githubusercontent.com/612173/45918076-6c020180-bebc-11e8-9875-35e801ad7810.png)

**Describe the solution you'd like**
- Chart 기본에 Map Chart 가 추가되어 사용
- 몇가지 Map 을 선택적으로 사용

**Additional context**
- 개발 진행하고 계신 내용은 알고 있습니다. 이슈 리스트 중에 보이지 않아서 추가하였습니다.
- 기획된 내용 공유해 주시면 좋을 듯 합니다.

**Comment by kyungtaak** [comment]
@Taehui #38 에서 관리중입니다. 이슈관련 내용은 정리해서 보강할 예정입니다. 그리고 향후 이슈등록시 임의로 assingee 지정은 자제부탁드립니다.

**Comment by Taehui** [comment]
@kyungtaak 확인했습니다. assignee 는 지정하면 안되는 거였군요~ 해당 이슈는 종료합니다.
