### ISSUE TITLE
 Drops to infinite loading status when 'Prediction line' is turned on in 'Analysis'

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#325]
**Describe the bug**
라인차트에서 Analysis 기능 중 Prediction line 기능을 켰을 때, 차트 저장 후 대시보드 편집모드와 대시보드 뷰 모드에서 무한루프 도는 현상

**To Reproduce**
상태확인 : https://discovery.metatron.app/app/v2/workbook/54787fde-3e3a-4589-a53e-e46e23437cf1

**Screenshots**
![loading](https://user-images.githubusercontent.com/612173/45918396-678c1780-bec1-11e8-900e-b5146e42e052.png)

**Desktop (please complete the following information):**
 - OS: WINDOWS 10
 - Browser : Chrome
 - Version : 버전 69.0.3497.100(공식 빌드) (64비트)

**Comment by YooYoungmo** [comment]
@Taehui v3.0.3 에서 재현되는 것을 확인 했습니다.  
문제는 더 확인해 보겠습니다.

추가로 500 오류가 나는 경우 대시보드에서는 어떻게 사용자에게 '알림'을 어떻게 주어야 할지 결정이 필요합니다.
아래는 다른 화면의 예시 입니다.
![image](https://user-images.githubusercontent.com/16472109/46118657-9b10ce00-c242-11e8-9e3e-bc69c1a54be4.png)

**Comment by minjung-cho** [comment]
공통 에러 상황에 대한 가이드입니다. 참고 부탁드립니다. METATRON-16

**Comment by YooYoungmo** [comment]
@minjung-cho 감사합니다. 혹시 METATRON-16 위치가 어디인가요? 링크를 주시면 좋을 것 같습니다.

**Comment by YooYoungmo** [comment]
@kyungtaak 제 로컬 환경에서 오류 재현 결과 드루이드 쿼리 예측 결과 값이 없어서 발생한 오류로 확인 됩니다.(상세 내용은 아래를 참조 하세요) 혹시 참고할 만한 자료가 있을까요?
![image](https://user-images.githubusercontent.com/16472109/46126801-93185480-c269-11e8-8dec-f0f220f681b0.png)

# 오류 재현
## Version
* 메타트론 v3.0.3
* 드루이드 druid-0.9.1-metatron-3.0.0-hadoop-2.7.3

## 오류 화면
대시보드 -> 선형 차트 -> 예측선
![image](https://user-images.githubusercontent.com/16472109/46126568-c9090900-c268-11e8-9218-6f661b77c94d.png)

## 오류 원인
드루이드 예측 쿼리 결과에 값이 없음.

### 드루이드 Request
```json
{
  "aggregations": [
    {
      "fieldName": "sale_amt",
      "inputType": "double",
      "name": "SUM(sale_amt)",
      "type": "sum"
    }
  ],
  "context": {
    "postProcessing": {
      "confidence": 95,
      "numPrediction": 12,
      "period": 12,
      "postAggregations": [
        {
          "expression": "time_format(__time,out.format='MMM d, yyyy',out.timezone='UTC',out.locale='en')",
          "name": "date",
          "type": "math"
        }
      ],
      "type": "holtWinters",
      "values": [
        "SUM(sale_amt)"
      ]
    },
    "queryId": "QUERY-546f59b4-c78f-4a8e-b555-596d13fd97b1"
  },
  "dataSource": {
    "name": "predictds",
    "type": "table"
  },
  "dimensions": [
    {
      "dimension": "date.inner",
      "outputName": "date",
      "type": "default"
    }
  ],
  "granularity": "DAY",
  "groupingSets": {
    "names": [],
    "type": "names"
  },
  "intervals": [
    "1970-01-01T00:00:00.0Z/2051-01-01T00:00:00.0Z"
  ],
  "limitSpec": {
    "columns": [
      {
        "dimension": "date",
        "dimensionOrder": "alphanumeric",
        "direction": "ascending"
      }
    ],
    "limit": 100000,
    "type": "default",
    "windowingSpecs": [
      {
        "partitionColumns": [
          "date"
        ],
        "pivotSpec": {
          "appendValueColumn": true,
          "pivotColumns": [],
          "separator": "―",
          "tabularFormat": true,
          "valueColumns": [
            "SUM(sale_amt)"
          ]
        }
      }
    ]
  },
  "postAggregations": [],
  "queryType": "groupBy",
  "virtualColumns": [
    {
      "expression": "time_format(__time,out.format='yyyy-MM-dd',out.timezone='UTC',out.locale='en')",
      "outputName": "date.inner",
      "type": "expr"
    }
  ]
}
```
### 드루이드 응답
```json
[
    {
        "version": "v1",
        "timestamp": "2018-05-14T00:00:00.000Z",
        "event": {
            "date": "May 14, 2018",
            "SUM(sale_amt)": 143752
        }
    },
    {
        "version": "v1",
        "timestamp": "2018-05-15T00:00:00.000Z",
        "event": {
            "date": "May 15, 2018",
            "SUM(sale_amt)": 153965
        }
    },
    {
        "version": "v1",
        "timestamp": "2018-05-16T00:00:00.000Z",
        "event": {
            "date": "May 16, 2018",
            "SUM(sale_amt)": 177167
        }
    },
    {
        "version": "v1",
        "timestamp": "2018-05-17T00:00:00.000Z",
        "event": {
            "date": "May 17, 2018",
            "SUM(sale_amt)": 148295
        }
    },
    {
        "version": "v1",
        "timestamp": "2018-05-18T00:00:00.000Z",
        "event": {
            "date": "May 18, 2018",
            "SUM(sale_amt)": 191383
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-19T00:00:00.000Z",
        "event": {
            "date": "May 19, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-20T00:00:00.000Z",
        "event": {
            "date": "May 20, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-21T00:00:00.000Z",
        "event": {
            "date": "May 21, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-22T00:00:00.000Z",
        "event": {
            "date": "May 22, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-23T00:00:00.000Z",
        "event": {
            "date": "May 23, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-24T00:00:00.000Z",
        "event": {
            "date": "May 24, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-25T00:00:00.000Z",
        "event": {
            "date": "May 25, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-26T00:00:00.000Z",
        "event": {
            "date": "May 26, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-27T00:00:00.000Z",
        "event": {
            "date": "May 27, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-28T00:00:00.000Z",
        "event": {
            "date": "May 28, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-29T00:00:00.000Z",
        "event": {
            "date": "May 29, 2018"
        }
    },
    {
        "version": "predict",
        "timestamp": "2018-05-30T00:00:00.000Z",
        "event": {
            "date": "May 30, 2018"
        }
    }
]
```
## 데이터 소스 데이터(csv 파일)
date | grade | sale_amt | sale_cnt
-- | -- | -- | --
14/05/2018 | 0 | 72180 | 95
14/05/2018 | 1 | 28631 | 34
14/05/2018 | 2 | 7516 | 12
14/05/2018 | 3 | 11792 | 7
14/05/2018 | 4 | 14725 | 15
14/05/2018 | 5 | 4346 | 7
14/05/2018 | 6 | 1659 | 5
14/05/2018 | 7 | 2903 | 1
15/05/2018 | 0 | 83786 | 98
15/05/2018 | 1 | 34047 | 37
15/05/2018 | 2 | 12559 | 15
15/05/2018 | 3 | 9026 | 14
15/05/2018 | 4 | 3904 | 8
15/05/2018 | 5 | 5367 | 2
15/05/2018 | 6 | 5276 | 4
16/05/2018 | 0 | 90445 | 129
16/05/2018 | 1 | 30330 | 35
16/05/2018 | 2 | 13160 | 10
16/05/2018 | 3 | 11494 | 11
16/05/2018 | 4 | 16490 | 18
16/05/2018 | 5 | 9710 | 8
16/05/2018 | 6 | 3049 | 10
16/05/2018 | 7 | 2489 | 2
17/05/2018 | 0 | 70540 | 121
17/05/2018 | 1 | 19333 | 28
17/05/2018 | 2 | 22815 | 22
17/05/2018 | 3 | 6813 | 5
17/05/2018 | 4 | 5717 | 13
17/05/2018 | 5 | 22168 | 15
17/05/2018 | 6 | 909 | 4
18/05/2018 | 0 | 106609 | 130
18/05/2018 | 1 | 35842 | 43
18/05/2018 | 2 | 16237 | 16
18/05/2018 | 3 | 10489 | 12
18/05/2018 | 4 | 9377 | 18
18/05/2018 | 5 | 7737 | 17
18/05/2018 | 6 | 4322 | 11
18/05/2018 | 7 | 770 | 1

**Comment by YooYoungmo** [comment]
위의 건과 별도로 에러 화면 처리 먼저 진행 합니다.

**Comment by navis** [comment]
period 가 12 이면 최소 24 개의 데이터가 필요합니다. 5개 밖에 없네요.

**Comment by YooYoungmo** [comment]
@navis 확인 감사합니다.

**Comment by minjung-cho** [comment]
> @minjung-cho 감사합니다. 혹시 METATRON-16 위치가 어디인가요? 링크를 주시면 좋을 것 같습니다.

TDE 프로젝트 이슈 번호인데, 링크 걸어도 되는지 잘 모르겠어서..  ^^; 관련 내용 첨부드립니다. 

기획서이고요,
<img width="1374" alt="2018-09-28 10 25 52" src="https://user-images.githubusercontent.com/28773903/46182863-0ae98c00-c309-11e8-93bc-2057104e48e1.png">
디자인은 아래와 같이 나와 있습니다
<img width="661" alt="2018-09-27 11 08 00" src="https://user-images.githubusercontent.com/28773903/46182866-0d4be600-c309-11e8-8572-f70bdff2d7df.png">

**Comment by YooYoungmo** [comment]
@Taehui 문제 원인 찾았습니다.
문제 원인은 대시보드를 로딩하면서 라인 차트가 오류가 나면서 '대시 보드 로딩 이미지'를 제거하지 않아서 발생하는 문제입니다.

그리고 라인 차트가 오류는 예측선이 그려지기에 데이터가 충분하지 않아 발생한 오류 입니다.

---
1. `홍태희 테스트1` 대시보드에 사용된 Sales 데이터 소스는 현재 47개(월 기준)가 존재
2. 라인 차트의 경우 예측선 설정이 12 MONTH
![image](https://user-images.githubusercontent.com/16472109/46184303-fa88df80-c30f-11e8-81b2-cc0720c1fadb.png)
3. 라인 차트의 예측선이 그려지기 위해서는 최소 24개 이상의 데이터가 필요
4. `홍태희 테스트1` 대시 보드에서 Order Date 글로벌 필터로 최근 1년으로 데이터 셋을 좁힘
![image](https://user-images.githubusercontent.com/16472109/46184354-3f147b00-c310-11e8-92c0-f07f5ee70264.png)
5. 최근 1년간의 데이터로 라인 차트의 예측선이 그려지는데 필요한 데이터를 갖추기 못하기 때문에 오류
---

HTML을 편집하여 로딩 화면을 강제로 없애고 Order Date 글로벌 필터에 최근 4년으로 변경한 결과 정상적으로 라인 차트에 예측선을 그려지는 것을 확인 했습니다.
![image](https://user-images.githubusercontent.com/16472109/46184410-8ac72480-c310-11e8-9740-bcf40f6eef88.png)

대시 보드를 로딩하면서 라인 차트 예측선 오류가 나더라도 사용자가 대시 보드 편집이 가능하도록 '대시보드 로딩 이미지'를 제거 하는 방향으로 수정하겠습니다.

**Comment by eltriny** [comment]
@YooYoungmo 
수정은 현재 제쪽에서 진행하고 있습니다.

**Comment by YooYoungmo** [comment]
@eltriny 네.
