### ISSUE TITLE
Provide status for creating snapshots

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#33]
**Is your feature request related to a problem? Please describe.**
- 스냅샷을 생성 후 상태에 따라 다른 UI 가 필요합니다

**Describe the solution you'd like**
- 스냅샷이 생성이 완료된 경우 : 통계 서머리 (Valid, mismatched, missing)와 그리드를 보여줍니다.
- 스냅샷 생성이 실패한 경우 : 실패 에러 로그를 보여줍니다.
- 스냅샷 생성 중 일 경우 : 프로그래스 바를 보여주고 취소할 수 있습니다.

**Describe alternatives you've considered**

**Additional context**
스냅샷 리스트에서도 진행 중인 스냅샷을 볼 수 있습니다

**Comment by joohokim1** [comment]
All PRs merged. Issue closed.
