### ISSUE TITLE
Hive timestamp columns produce mismatched values

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#330]
**Describe the bug**
If you import a Hive table with a Timestamp, all values ​​in that column are mismatched.
In addition, unix epoch time is displayed in preview when dataset is clicked in dataflow chart.

_Timestamp가 있는 Hive 테이블을 import하면 해당 column의 모든 값이 mismatched로 표시됩니다.
또 하나, dataflow chart에서 dataset을 클릭했을 때에 나오는 미리보기에 unix epoch time이 표시됩니다._

**To Reproduce**
1. Import a Hive table which includes a timestamp column. (If you don't have, you can make one by dataprep easily)
2. Click that dataset on dataflow chart page.
3. Press "Edit rules"

**Expected behavior**
All timestamp values ​​should be marked as matched.
Hive's default representation is just fine. (Not important for a while)

_모든 timestamp 값이 잘 보이고, matched로 표시되어야 합니다.
Timestamp format은 Hive의 기본 표현 방식이면 됩니다. (현재 단계에선 중요하지 않음)_

**Screenshots**
![2018-09-28 5 44 54](https://user-images.githubusercontent.com/42257727/46197962-3dfe4080-c346-11e8-817f-f861ece57794.png)
![2018-09-28 5 44 40](https://user-images.githubusercontent.com/42257727/46197969-40609a80-c346-11e8-820d-948938dc9fa2.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68.0.3440.106

**Comment by joohokim1** [comment]
Works for main edit page has been done (4b8cc23) but, we decided to handle the formatting problem in  the dataflow chart page within this issue. @paigechoi will do and merge and close.

Main 편집화면에 대해서는 처리를 완료했습니다만 (4b8cc23),
dataflow의 preview에 대한 format 처리를 본 이슈로 처리하기로 했습니다.
@paigechoi 님께 담당자를 넘깁니다.

**Comment by joohokim1** [comment]
<img width="1914" alt="format-question" src="https://user-images.githubusercontent.com/42257727/46792475-693d5280-cd7e-11e8-90ee-812430f1a670.png">

For JDBC Date type as above, mismatch or missing occurs.

_위처럼 JDBC Date type의 경우, mismatch 또는 missing이 발생합니다._

**Comment by joohokim1** [comment]
Bugfix done. Issue closed.

**Comment by goodljy** [comment]
정상동작 확인. 2018-10-18
