### ISSUE TITLE
Cannot launch Metatron distributed Druid

### ISSUE THREAD

**Issue by tiago-as** [metatron-app/metatron-discovery#3315]
Hi,

I'm trying to install Metatron for testing. When I extract the Druid and try to launch it, as it says on the instructions, I get this message:
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000540000000, 3579117568, 0) failed; error='Cannot allocate memory' (errno=12)
```
I don't understand why this error is showing, not even with sudo the command runs.
Could someone give me some light on the subject?

Druid version: druid-0.9.1-SNAPSHOT.201911201314-hadoop-2.7.3
Java: 1.8.0_252

Thanks in advance

**Comment by kyungtaak** [comment]
@tiago-as In my opinion, you need to compare the memory size of your machine with the memory size set in the druid. If you set the memory size in the druid configuration to be larger than the free memory in your machine, you have to reduce the memory size of druid nodes. Please refer to [this link](https://druid.apache.org/docs/latest/operations/basic-cluster-tuning.html)

**Comment by tiago-as** [comment]
@kyungtaak thanks so much for the quick answer.
There are 6 files inside the druid directory with the name "runtime.properties" . I believe these files are where those configurations like the "memory size of the druid nodes". Although I'm not really sure which file I am supposed to change in order to lower the druid memory usage.

Any guidelines in this regard?

**Comment by tiago-as** [comment]
@kyungtaak changed the machine resources and I was able to launch. Closing the issue.
