### ISSUE TITLE
Dashboards created with linked data sources cannot be charted.

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#3327]
**Describe the bug**
Dashboards created with linked data sources cannot be charted.

**To Reproduce**
1. Make 'Dashboard' with 'Linked Datasource'
2. Click on 'Add Chart'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/90082721-83199900-dd4b-11ea-8cc7-bbfb90d5637e.png)

**Comment by i1befree** [comment]
In the current screen flow, there is a point in time when the name of the temporary datasource is not known to both the server and the client. I think it will be nice to take a temporary datasource naming convention and use it to compare.
