### ISSUE TITLE
Fail to check query : Unable to load authentication plugin 'client_ed25519'

### ISSUE THREAD

**Issue by tiago-as** [metatron-app/metatron-discovery#3330]
Hi,

I'm trying to connect to a remote MariaDB with SSL and ed25519. Metatron is logging this line when I try to validate the connection:
```
 WARN [127.0.0.1-admin] [http-nio-8180-exec-1] a.m.d.e.d.j.a.AbstractJdbcDataAccessor   : Fail to check query : Unable to load authentication plugin 'client_ed25519'.
```

I haven't been able to find a way to install this missing plugin and get over this issue.
Does anyone have any knowledge regarding this matter?

Thanks in advance for any feedback

**Comment by ufoscw** [comment]
The mysql jdbc connector currently used in metatron discovery is as follows.
```
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>5.1.37</version>
            </dependency>
```
The ed25519 authentication plugin is the authentication plugin added in maraidb 10.1.22 version. (https://mariadb.com/kb/en/authentication-plugin-ed25519)

I will add jdbc connection plugin for mariadb sooner or later.
If you are in a hurry, you can create a jdbc connection plugin for 10.1.22 maraidb like the guide below and add it yourself.
(https://metatron.app/2019/06/18/metatron-discoverys-connection-extension-for-microsoft-sql-server/)

Or you can modify the mysql jdbc dependency included in metatron and build it yourself.

**Comment by tiago-as** [comment]
@ufoscw thank you so much! I'll be eagerly waiting for that feature. 
(closing the issue)
