### ISSUE TITLE
Association & Join edit view does not work with linked datasource.

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#3365]
**Describe the bug**
If you use Association & Join edit screen with linked datasource, the screen displays javascript error.

**To Reproduce**
1. Create dashboard with linked datasource.
2. edit dashboard.
3. Click "Association & Join" in Dashboard tab of right pane.

**Expected behavior**
When you create a dashboard, you can view and edit association & join of datasource. It should work the same in edit view.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by minhyun2** [comment]
deploy to 2
