### ISSUE TITLE
Abbreviations number setting doesn't work when valuse is minus

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#337]
**Describe the bug**
챠트의 Y 축 Abbreviations 설정을 Automation으로 하는 경우 적용이 안됨 

**To Reproduce**
1. 라인 챠트 그리기
2. Minus 값이 있는 Measure 추가
3. Number Format -> Abbreviations -> Automation 선택

**Expected behavior**
`-10K`, `-100K` 형태로 나타나야 함

**Screenshots**
![sacle_auto_minus](https://user-images.githubusercontent.com/321821/46273568-07683600-c591-11e8-9214-3489f41c64be.jpg)

**Desktop (please complete the following information):**
 - OS: 
- Browser: chrome
- Version: 69.0.3497.100

**Additional context**
없음

**Comment by kyungtaak** [comment]
@babokim 해당이슈는 3.0.4 릴리즈브랜치에 머지되어 이슈를 Close 합니다.
