### ISSUE TITLE
If druid is shutdown anomaly, Discovery does not know temporary data source has been disabled.

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#3382]
**Describe the bug**
If Druid is shutdown anomaly after creating a temporary data source, Discovery does not know the data source has been disabled and tries to get data from it.

**To Reproduce**
1. Create linked datasource.
2. Create dashboard from created linked datasource.
3. Restart Druid.
4. The dashboard does not show data.

**Expected behavior**
Discovery needs to know the temporary datasource is disabled and reload it.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by navis** [comment]
You can check existing local (temporary) datasource names by `/druid/v2/datasources/local`
