### ISSUE TITLE
SUMOF( [Sales]  )/ COUNTD( [OrderID]  ) not right!

### ISSUE THREAD

**Issue by loooong** [metatron-app/metatron-discovery#3401]
**Describe the bug**

**To Reproduce**
1. create new custom field MEASURE_1 as SUMOF( [Sales]  )/ COUNTD( [OrderID]  )
![image](https://user-images.githubusercontent.com/8617946/93737701-70ca2f00-fc16-11ea-910c-a8734ab90079.png)
2. try to draw a chart as following
![image](https://user-images.githubusercontent.com/8617946/93737966-21383300-fc17-11ea-8d9c-9c380365e25e.png)

**Expected behavior**
no error, show the chart

**Desktop (please complete the following information):**
 - OS: windows  10 
 - Browser chrome
 - Version 85.0

**Additional context**

**Comment by i1befree** [comment]
It's a bug. Discovery generates the wrong Druid query. I'll request a pull request.

**Comment by loooong** [comment]
is there any schedual for this bug? Thank you :)
