### ISSUE TITLE
Set the data processing default for decimal places to round

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#343]
**Is your feature request related to a problem?**
현재는 소수점 자리수 설정을 했을 때, 설정된 자리수까지 숫자를 표현하고 나머지 자리를 버림

**Describe the solution you'd like**
설정된 소수점 자리수 까지 값을 표현하되, 반올림 처리된 값을 표현하는 것이 기본값 이어야 함

**Describe alternatives you've considered**
반올림을 할 것인지, 버림을 할 것인지를 선택할 수 있으면 가장 좋음(이 경우에도 기본값을 반올림으로 할 필요가 있음)

**Comment by AnnieHwang** [comment]
@Taehui 해당 이슈는 #362 에서 더 상세화 하여 이슈로 진행하겠습니다. 감사합니다.
