### ISSUE TITLE
Logical name of datasource must be represented in MDMS

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#344]
**Is your feature request related to a problem? Please describe.**
Datasource 의 설명(Description)은 MDMS UX 에서 아래와 같이 표현되고 있으나, Logical name 은 표현되고 있지 않음
![datasource_meta](https://user-images.githubusercontent.com/612173/46299675-d9a8de80-c5dc-11e8-8563-13b08fd847b1.png)

**Describe the solution you'd like**
논리명도 표현되고, 수정할 수 있어야함

**Comment by deidera08** [comment]
논리명은 이미 표현되고 있습니다. 타이틀이 논리명이며 클릭시 수정 가능합니다.
Metadata메뉴의 정보는 논리정보로 표현되고 있으며 Datasource 정보는 물리 정보입니다.
![logicalimpormation](https://user-images.githubusercontent.com/42257766/46776265-cd8ff000-cd45-11e8-8f45-b2d005e75548.png)
![physicalimfomation](https://user-images.githubusercontent.com/42257766/46776266-cd8ff000-cd45-11e8-9987-fbe2ff552ba3.png)

**Comment by kyungtaak** [comment]
@Taehui 현재 MDM 관련 고도화 기획이 진행중입니다. 위 내용도 고도화 범주에 포함이 되며,  기획및 개발일정이 확정되면 다시 말씀드리겠습니다.

**Comment by kyungtaak** [comment]
@Taehui #1238 이슈에서 관련 내용이 수정이 되었습니다. 따라서 이슈를 종료합니다.
