### ISSUE TITLE
 Must be searched with description or logical name information of datasource metadata

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#345]
**Is your feature request related to a problem? Please describe.**
Datasource 이름 뿐만 아니라 Description, Logical name 도 검색을 할때 결과에 반영되어야 함
![meta-search](https://user-images.githubusercontent.com/612173/46303040-be8e9c80-c5e5-11e8-95ad-63a11fc42219.png)

**Describe the solution you'd like**
현재는 검색 결과에 Description 정보 등은 반영이 안됨
![meta-search-result](https://user-images.githubusercontent.com/612173/46303047-c51d1400-c5e5-11e8-8df8-54bf79f5b147.png)

**Comment by AnnieHwang** [comment]
@Taehui 4월부터 시작되는 MDM 개편작업에 해당 내용이 반영됩니다. 메타데이터의 검색 기능이 신규로 추가되서, 데이터명/데이터설명/컬럼명 으로 검색됩니다.

**Comment by kyungtaak** [comment]
해당이슈는 종료하도록하겠습니다.
