### ISSUE TITLE
Improve convenience for specifying ingestion options

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#35]
**Is your feature request related to a problem? Please describe.**
- 적재 단계를 수행중 적재 옵션 입력이 단순 JSON 텍스트 입력으로 제공되어 있어 사용하기 어렵습니다. 

**Describe the solution you'd like**
- 적재 옵션에 대해 필수 적재 옵션 및 기본값을 을 사용자에게 노출하고, 이 값만 일반 텍스트 입력으로 수행할수 있도록 개선합니다. 
![image](https://user-images.githubusercontent.com/822255/44190181-782dcd00-a160-11e8-996d-df8d1d0fe163.png)

- 데이터소스 상세 화면내에서 지정한 적재 옵션에 대한 정보를 보여줍니다. 
![image](https://user-images.githubusercontent.com/822255/44190189-909de780-a160-11e8-95b9-ce281dbaaf88.png)

**Describe alternatives you've considered**
<N/A>

**Additional context**
<N/A>

**Comment by brandon-exntu** [comment]
@kyungtaak 
1. 이 ingestion 화면에 대해서는 적재옵션만 적용하면 될까요?
staging으로 생성할때 ingestion 화면에서 파티션키에 대해 읽기전용으로 바뀌었는데 그것은 빼고 적용하면 될까요?

2. 위 적재 옵션에 대해 필수 적재 옵션 및 기본값은 서버에서 내려주나요?
아니면 기획에 써있는데로 key와 value들을 고정해두면 되나요?

**Comment by kyungtaak** [comment]
@brandon-exntu 
"ingestionType" 별로 사전에 지정된 옵션을 조회하는 API 를 작성하였습니다. 아래 정보 확인 부탁드립니다.
"ingestionType" File/JDBC 인경우,  "batch" 를 지정해주시고 StageDB 일 경우 "hadoop" 을 지정해 주세요.
상세한 내용은 [API 문서](https://tde.sktelecom.com/wiki/display/METATRON/DataSource+v2)를 을 참고해주세요. 

```
(GET) /api/datasources/ingestion/options?ingestionType=batch
```

> Sample Response
```
[
    {
        "name": "ignoreInvalidRows",
        "type": "TUNING",
        "defaultValue": "true",
        "dataType": "BOOLEAN",
        "ingestionType": "BATCH"
    },
    {
        "name": "maxRowsInMemory",
        "type": "TUNING",
        "defaultValue": 75000,
        "dataType": "LONG",
        "ingestionType": "BATCH"
    }
]
```

**Comment by brandon-exntu** [comment]
@kyungtaak 
위 내용대로 적용하였습니다.
StagingDB같은 경우 다른 source 생성 과는 다르게 jobProperties가 있어서 위 api로 조회시에 `type`이 JOB인 값을 default로 설정하도록 적용하였습니다.

ingestion 페이지를 컴포넌트 분리함에 따라 complete 단계의 파일도 같이 수정하였습니다.

partitionsKey의 경우는 sample이 오는대로 추가로 적용하겠습니다.
![2018-08-20 6 48 08](https://user-images.githubusercontent.com/42233627/44333398-9cafdf00-a4a9-11e8-9efe-8d3485398acc.png)

**Comment by kyungtaak** [comment]
@brandon-exntu 피드백 감사합니다.
- 파티션 키 관련 내용은 해당 이슈와 관련이 없습니다.
- StagingDB 는 ingestionType 을 "hadoop" 으로 지정하면, type 속성이 TUNING/JOB 두개의 타입이 동시에 오게 되어 있습니다. Tuning Option/Job Properties 가 표시되도록 구성해주세요.

**Comment by kyungtaak** [comment]
@minjung-cho @brandon-wonjune linked datasource 쪽도 tuning config 가 존재하는데요. 이 부분도 고려부탁드립니다. (현재 서버에서 제공하는 옵션목록이 없으면 빈값이 나타나게 되어 있지요?)

**Comment by minjung-cho** [comment]
@kyungtaak 현재 기획은 모든 옵션 값이 필수이고 옵션마다 초기값이 있음을 전제하고 있습니다. "옵션 목록이 없으면" 이라고 한 것은 옵션 항목이 없는 것인지, 초기값이 없는 것인지, 값 입력이 필수가 아닌 것인지 궁금합니다. 알려주시면 그에 맞도록 추가 정의하겠습니다-

**Comment by minjung-cho** [comment]
@kyungtaak OK
@brandon-wonjune 
ingestion tuning config. Job property의 모든 항목을 옵셔널로 해 주시고, 값이 내려오는 항목만 초기값을 입력해 주십시요-
V.1.30 문서에 반영했습니다.
@AnnieHwang 기획 변경되었습니다

**Comment by minjung-cho** [comment]
@kyungtaak 제가 이해를 잘 못하고 있는 것 같아서 아래와 같습니다 ㅠㅠ @AnnieHwang 아래와 같이 정리했는데, 1,2,3 번 해석 부탁드려도 될까요? 제가 이해한게 맞나요? ㅠㅠ 4번은 일단 이해한 것 바탕으로한 기획 수정 방안입니다..
1. Ingestion tuning config.와 job property에 정해진 항목이 있음.
2. 항목들에 기본값이 있는것도, 없는것도 있음
3. 입력값이 없는 경우, 기본값이 있으면 기본값으로 넘기고 기본값이 없으면 빈값으로 넘어감
4. (검토)기본값이 있는 항목의 P.H를 기본값으로 함

**Comment by kyungtaak** [comment]
@minjung-cho 제가 이해하는 용어로 정리를 드리면 아래와 같습니다. 
1. "Ingestion tuning config.와 job property에 정해진 항목" 은 위 가이드 드린 api 를 통해 전달되는 pre-defined 된 설정 정보라고 이해하고 있습니다. 그리고 기본값이 반드시 존재합니다. 
2. 필수여부가 있다면, 기본값이 없을 수도있겠지만, 그런 개념은 없는게 좋을것 같습니다. 옵션이니까요.
3. 기본값이 반드시 있기때분에 고려하지 않아도 될듯합니다.
4. 기본값은 P.H 가 있는게 맞으며, @brandon-wonjune 입력하지 않는 값은 서버로 넘기지 않습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak Linked 타입으로 생성한경우 설정한 tuning option이 데이터소스 상세화면에서 나오지 않고있습니다.
```
// api
api/datasources

// 생성시 사용된 params
connType:"LINK"
description:""
dsType:"MASTER"
fields:[,…]
granularity:"MONTH"
ingestion:{
connection:{
hostname:"localhost"
implementor:"MYSQL"
password:"polaris"
port:"3306"
type:"JDBC"
username:"polaris"
}
dataType:"TABLE"
database:"polaris_v2"
expired:1800
query:"activity_stream"
rollup:true
scope:"ALL"
tuningOptions:{ignoreInvalidRows: "true", maxRowsInMemory: "75000"}
type:"link"
}
name:"test"
segGranularity:"MONTH"
srcType:"JDBC"

// 상세화면 조회시 사용된 api
datasources/{sourceId}?projection=forDetailView

// result
connType:"LINK"
contexts:{}
createdBy:{type: "user", username: "admin", fullName: "Administrator", email: "admin@metatron.com"}
createdTime:"2018-09-13T01:26:10.000Z"
description:""
dsType:"MASTER"
engineName:"test_vgvbm"
fields:[{id: 10037029, name: "id", alias: "id", type: "LONG", logicalType: "INTEGER", role: "MEASURE",…},…]
granularity:"MONTH"
id:"f30c72b3-5934-4f85-8a9f-45dcba5db8fe"
ingestion:{
connection:{implementor: "MYSQL", type: "JDBC", hostname: "localhost", port: 3306, username: "polaris",…}
dataType:"TABLE"
database:"polaris_v2"
expired:1800
query:"activity_stream"
rollup:true
tuningOptions:{}
type:"link"
}
linkedWorkspaces:0
modifiedBy:{type: "user", username: "admin", fullName: "Administrator", email: "admin@metatron.com"}
modifiedTime:"2018-09-13T01:26:10.000Z"
name:"test"
segGranularity:"MONTH"
srcType:"JDBC"
status:"ENABLED"
```

**Comment by kyungtaak** [comment]
@brandon-wonjune  오류 수정하였습니다.
