### ISSUE TITLE
Upload CSV - Connection refused

### ISSUE THREAD

**Issue by enjineerMan** [metatron-app/metatron-discovery#3508]
I'm getting this error trying to upload a csv as a datasource to metatron:
message : INGESTION_COMMON_ERROR 
cause : ConnectException: Connection refused

Steps:
1. Launch metatron on http://localhost:8180
2. Click on datasource under management tab on left
3. Press new on top right
4. Default settings for select data and configure schema
5. Select minute query granularity, month segment granularity, rollup=false
6. Finalize and see error

<img width="701" alt="image" src="https://user-images.githubusercontent.com/62212652/99271926-cf61f280-27ec-11eb-9c19-eabfd7d4e524.png">

<img width="329" alt="image" src="https://user-images.githubusercontent.com/62212652/99272026-eb659400-27ec-11eb-86f3-ad744f59c343.png">

 - OS: MacOS 10.15.7
 - Safari 14

**Comment by alchan-lee** [comment]
It seems to be not able to connect with the engine.

Have you installed druid in your environment?
If not, you need to install it by following the link below.
https://github.com/metatron-app/metatron-discovery#requirements
