### ISSUE TITLE
Error saving pie chart after setting color by measure

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#353]
**Describe the bug**
- 파이차트를 color by measure로 저장 시 format 정보가 초기화 되어 저장에러가 발생합니다.

**To Reproduce**
1. 차트 생성화면으로 이동합니다.
2. 1 dimension, 1 measure를 선반에 올린 후 파이차트를 선택합니다.
3. 색상패널에서 color by measure로 타입을 선택합니다.
4. 차트 저장 시 서버에러가 발생합니다.

**Expected behavior**
- color by measure로 파이차트를 저장 시 서버에러가 발생하지 않아야합니다.

**Screenshots**

**Desktop (please complete the following information):**
- OS: iOS
- Browser : chrome
- Version 69.0

**Additional context**

**Comment by juheeko9** [comment]
f#353-error_saving_pie_bycolor 브랜치 생성하였습니다.

**Comment by kyungtaak** [comment]
아래 두건의 이슈 확인 부탁드립니다.
-  파이차트에서 컬러셋팅을 Dimension -> Measure -> Dimension 변경시 현상
![image](https://user-images.githubusercontent.com/822255/46785796-d4caf400-cd6d-11e8-969f-8cd541ea445f.png)
- 스크린샷 확인 
![image](https://user-images.githubusercontent.com/822255/46785815-e7452d80-cd6d-11e8-9e62-a19d39083873.png)

**Comment by juheeko9** [comment]
파이차트에서 컬러셋팅을 Dimension -> Measure -> Dimension 변경시 현상 부분은 #418에서 처리하겠습니다.
