### ISSUE TITLE
Save on HDFS first for WAS clusters

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#36]
**Is your feature request related to a problem? Please describe.**
현재, WAS가 이중화 되어있는 경우 upload (import) 한 dataset의 내용을 찾을 수 없는 경우가 발생합니다.

**Describe the solution you'd like**
HDFS 연결이 가능한 경우 (이것을 체크하는 것도 일), HDFS 상의 특정 위치 (stagingBaseDir이면 될 듯)에 uploads와 previews를 저장하면 좋겠습니다.
Imported dataset의 내용을 읽을 필요가 있는 경우 (HDFS 연결이 가능한 경우) HDFS의 stagingBaseDir/uploads를 먼저 뒤지고, 거기에 없는 경우에 localBaseDir/uploads를 보면 좋겠습니다.
previews, snapshots도 마찬가지로 해야겠습니다.

**Additional context**
snapshot의 경우 애당초, HDFS로 완전 지정된 경우가 있어서 세심하게 잘 해줘야겠네요.
(HDFS 타입인 경우, stagingBaseDir에 없으면 없는 것으로. Local 파일 타입인 경우 localBaseDir도 보는 것으로)

**Comment by i1befree** [comment]
AWS 나 Azure 를 지원 예정인 만큼 저장 위치를 S3 나 Blob storage 로 하는 것도 검토 필요해 보입니다.

**Comment by joohokim1** [comment]
@i1befree 네 알겠습니다. 노트해 두겠습니다.
