### ISSUE TITLE
Policy unification for number rounding

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#362]
**Describe the bug**
반올림에 대한 정책이, 텍스트그리드 차트와 그 외의 차트 사이에 서로 다릅니다.
차트에서는 숫자표현을 예를들어 2자리로 하였을 경우, 반올림이 되어서 표현되고 있으며,
텍스트그리드 차트의 경우 숫자표현을 예를들어 2자리로 하였을 경우, 버림(숨김)으로 표현되고 있습니다.
이로 인하여, 사용자는 두개의 값에 대해 왜 다른지 의아해하고 있습니다.

**To Reproduce**
1. Go to '차트상세'
2. 소수점이 있는 매져와 디멘젼 선택 후 막대차트 생성
3. 동일한 소수점이 있는 매져와 디멘젼 선택 후 텍스트그리드 생성
4. 두 매져의 결과 값이 다르게 보여짐(ex. 막대차트 : 7.30, 텍스트그리트차트 : 7.29)

**Expected behavior**
- 기본적으로 반올림이 되어야 맞다고 생각합니다 (추후 기획에서 반올림(default)/내림/올림/버림 의 조건을 선택할 수 있는 UI가 숫자표현 패널에 나와야 합니다.)
- 텍스트그리드에서 값이 반올림된 값이 나와야 합니다.(기타 차트는 정상동작합니다.)
- 텍스트그리드에서 연산행을 추가한 경우, 반올림된 값으로 계산된 결과가 역시나 반올림 되어서 표현되어야 합니다.

**Screenshots**
대시보드 상에서 텍스트그리드 차트와 막대차트의 표현이 다릅니다( 둘다 동일하게 숫자표현은 소수점 2자리 default 값을 적용한 상태입니다.)
![image](https://user-images.githubusercontent.com/6300003/46455235-0d565500-c7e5-11e8-8c59-1bda4d8f8a18.png)

실제 서버에 보내지는 값으로 볼때, 텍스트그리드에서는 소수점 2자리 이하 값을 숨기고 있습니다. 막대차트와 동일하게 값을 반올림 하여야 합니다.
![image](https://user-images.githubusercontent.com/6300003/46455244-16dfbd00-c7e5-11e8-9723-448473861b67.png)

연산행의 경우 보여지는 값으로만 계산 부탁드립니다. (숨겨져 있는 값까지 계산하면 사용자입장에서는 오류라고 보여집니다)
![image](https://user-images.githubusercontent.com/6300003/46455495-493dea00-c7e6-11e8-8537-adfeabb8b481.png)

**Comment by AnnieHwang** [comment]
아래 내용을 샘플데이터 예로 참고부탁드립니다.
![image](https://user-images.githubusercontent.com/6300003/46772907-6ec27a80-cd35-11e8-8564-300fae629de5.png)

**Comment by alchan-lee** [comment]
@AnnieHwang @kyungtaak 
닫은 이슈이지만..

차트 퍼센트에도 동일한 반올림 정책이 적용되어야 하지 않을까요
퍼센트에서는 반올림이 아닌 버림으로 처리되고 있어서 합계가 100%가 안됩니다.

![image](https://user-images.githubusercontent.com/42234141/46852578-7158c900-ce36-11e8-89f0-f1b5c6b264c9.png)
