### ISSUE TITLE
PivotGrid Performance issue, after legacy code merge.

### ISSUE THREAD

**Issue by Sidonet** [metatron-app/metatron-discovery#3668]
**Describe the bug**
PivotGrid performance issue, after #3615 code merge.
On load, resize or any other action on pivot-grid, it takes about 5-7 seconds to apply logic from #3615.

[Profile-20210504T162705.zip](https://github.com/metatron-app/metatron-discovery/files/6421380/Profile-20210504T162705.zip)

![image](https://user-images.githubusercontent.com/39062077/117011164-3b320c00-acf6-11eb-8bee-156b6275b91c.png)

On beautified min file, i see next:
![image](https://user-images.githubusercontent.com/39062077/117012091-3c176d80-acf7-11eb-9b11-81abcf2ed860.png)

`              }).forEach(function(t) {
                b = b + Object.keys(c).reduce(function(e, r) {
                  if (r && (r === t || -1 < r.indexOf(t + "||"))) {
                    e = e + Number(c[r])
                  }
                  return e
                }, 0)
              });
`
![image](https://user-images.githubusercontent.com/39062077/117012166-55b8b500-acf7-11eb-8bb9-88d2f940abfb.png)

**To Reproduce**
1. Go to constructor and build a table chart, with one huge line (Dates, for a three years as example... 01.01.2012 to 01.01.2015), and save it.
2. Click on dashboard view, and frop table chart on dashboard.
3. Try to resize Web Browser
4. See error, whole app freezes 5-7 seconds...

**Expected behavior**
Table chart must work fast as it works before #3615 happens.

**Screenshots**

**Desktop (please complete the following information):**
Debian
 Chrome
 90.0.44

**Additional context**

pivot-grid sources do not included into this repo, so i can't fix this problem myself.

**Comment by Sidonet** [comment]
Looks like issue comes from right position calculation.

It was 
`
T.right = Math.min(this._xItems.length - 1, T.left + Math.ceil((this._elementBody.clientWidth - S + (this._scrollLeft - T.left * p)) / p) - 1), !n && this._isPivot && T.top === this._itemsRange.top && T.bottom === this._itemsRange.bottom && T.left === this._itemsRange.left && T.right === this._itemsRange.right
`

For now it is:
`
T.right = this._xItems.length - 1;
`

And this code:
`
                        for (var l = T.left; l <= T.right; l++) {
                            var v = u(l);
                            if (v === "continue") continue
                        }
`
is never works... I have about 730 columns, and all of them goes from this code without "continue" flag...

**Comment by ufoscw** [comment]
Thanks for the report.
I'll check.

**Comment by ufoscw** [comment]
@Sidonet 
The issue has been resolved.
You can check it out.
