### ISSUE TITLE
Table list must be able to sort as strings in workbench

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#368]
**Is your feature request related to a problem? Please describe.**
워크벤치의 테이블 목록이 문자열 기준으로 정렬이 되지 않으며, 별도의 정렬 기준을 설정할 수 없음
![table_list](https://user-images.githubusercontent.com/612173/46491596-1c212400-c846-11e8-8f0c-36ad85ca9142.png)

**Describe the solution you'd like**
문자열 기준으로 ASC, DESC 정렬 기능이 있어야 함

**Comment by eltriny** [comment]
#534 이슈와 내용이 중복되므로 본 이슈를 닫습니다.
