### ISSUE TITLE
Improve grid chart : support resize

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#37]
**Is your feature request related to a problem? Please describe.**
- Grid Chart 사용시 다수의 개선 요청 사항 건을 진행합니다. 

**Describe the solution you'd like**
- 차트위젯 사이즈에 따른 Grid Chart Resize 조정과, 컬럼 resize 기능을 추가합니다.
- 차트 생성 조건을 최소화 gkqslek.
: 현재 > 차트 생성 조건은, 열 또는 행 : 차원값 1개 이상, 교차 : 측정값 1개 이상  
: 개선안 > 열 또는 행 : 차원값 1개 이상 / 측정값 없는 차원값 리스트 형태도 표현 가능하도록 조건 변경

**Describe alternatives you've considered**
<N/A>

**Additional context**
<N/A>

**Comment by kyungtaak** [comment]
@judy-exntu GridChart 내에서 Aggregation 필드에 하나도 없는 경우, select query 로 전달되기 때문에 위와 같은 현상이 발생한것으로 보입니다. 별도의 예외처리가 필요한것 같은데요. 

이번에 f#37-imporve_grid_chart 브렌치를 생성하여 "count" 타입 Field 를 생성하여 커밋해두었습니다.
grid chart 에서 교차선반에 데이터가 없는 경우, 아래와 같이 임의로 alias 를 넣어서 작업을 해주시면 감사드리겠습니다. 

```
{
    ...,
    "pivot": {
        "rows": [
            {
                "type": "dimension",
                "name": "Category",
                "alias": "Category"
            }
        ],
        "aggregations": [
            {
                "type": "count",
                "alias": "CountFieldAlias"  // 임의의 Alias 지정후 결과값 파싱에 활용
            }
        ]
    },
    ...
}
```

**Comment by judy-exntu** [comment]
@kyungtaak 감사합니다.

@AnnieHwang @esezin 
- 차트 생성 조건을 최소화
=> dimension으로만 그리드차트를 그렸을때 다른옵션들에대한 고려사항이 필요한 것 같습니다.
확인부탁드립니다.
ex) aggregation column 설정, total row 설정등

**Comment by kyungtaak** [comment]
@metatron-app/design 
[METATRON-1180](https://tde.sktelecom.com/pms/browse/METATRON-1180) 이슈에 댓글에 언급드린 바와 같이 같이 교차 영역에 측정값 존재 유무에 따른 처리를 구분하는 방식에 대해서 검토부탁드립니다.

**Comment by esezin** [comment]
@kyungtaak , @AnnieHwang , @juheeko9 

우선, 차트의 최소 그리기 조건을 차원값 1개로 변경하면서, 차원값만으로 표를 구성했을 경우에 대한 고려 항목입니다.
**1. 'Aggregation Column' 표시 기능은 비활성화
2. 연산행 패널에 진입시 ON/OFF 토글 버튼 비활성화**

다음은 관련하여, 헤더와 본문 영역에 대한 구분 정책입니다.
동일한 PMS이슈가 https://tde.sktelecom.com/pms/browse/METATRON-1180 에도 있습니다.

**1. Aggregation이 포함된 경우**
- 상단과 우측에 헤더가 위치 가능
- 헤더 : 차원값 이름, 차원값 데이터 영역, Aggregation Column (이름)
- 본문 : 측정값 데이터 영역
**2. Aggregation이 포함되지 않은 경우 (차원값만으로 표를 구성)**
- 상단과 우측에 헤더가 위치 가능
- 헤더 : 차원값 이름
- 본문 : 차원값 데이터 영역

**Comment by kyungtaak** [comment]
@eltriny 위 제안내용 검토해주시고요. 개발 진행 부탁드립니다.

**Comment by kyungtaak** [comment]
@esezin @juheeko9 그리기 조건 최소화는  #156 이슈에 이어서 진행합니다.

**Comment by kyungtaak** [comment]
#237 PR 내 댓글 확인 부탁드립니다.
