### ISSUE TITLE
Error when resizing text table chart header

### ISSUE THREAD

**Issue by yovahu** [metatron-app/metatron-discovery#3719]
**Describe the bug**
Error when resizing text table chart header

**To Reproduce**
1. Go to dashboard charts and select "text table" chart
2. Choose dimension (horizontal) and measures
3. Change "Common Setting" of chart to these:
    - Chart Type: Pivot
    - Show Header: ON
    - Aggregation Column: ON (Horizontal)
4. Then try resizing first (header) column and you will see that only the header is resized

**Screenshots**
![image](https://user-images.githubusercontent.com/71209206/121112996-e1b48400-c843-11eb-92c1-532b65d8b9ce.png)
![image](https://user-images.githubusercontent.com/71209206/121113137-17596d00-c844-11eb-81ef-e815b4aebe66.png)

**There are no error reports in Chrome DevTools**
How i can do fix it ?

**Comment by ufoscw** [comment]
thank you for the report
We'll check it out.

**Comment by yovahu** [comment]
Thanks for solving my problem!
https://github.com/metatron-app/metatron-discovery/pull/3751
