### ISSUE TITLE
Problems with datasource pivot data

### ISSUE THREAD

**Issue by yovahu** [metatron-app/metatron-discovery#3724]
**Describe the bug**
When creating join between two datasource, the **pivot** table is not created in its "Manage Scheme", because we cant join one more datasource to this **pivot** table.

**To Reproduce**
1. Go to Create Dashboard, choose one of datasources
2. Then go to its "Manage Scheme" and create join
3. Choose joins keys, and create join
4. Try to add one more datasource to join from step 3
5. You will see data from the main source only, not pivot table from step 3

**Expected behavior**
Pivot data was expected when creating a join to an existing join between two datasources.

**Screenshots**
![image](https://user-images.githubusercontent.com/71209206/121451596-7946dd80-c9d0-11eb-927a-66dd12fb6d2d.png)
![image](https://user-images.githubusercontent.com/71209206/121451357-05a4d080-c9d0-11eb-8692-67c65dfadaaf.png)
![image](https://user-images.githubusercontent.com/71209206/121451755-b57a3e00-c9d0-11eb-8702-9fe07fa1b87e.png)
![image](https://user-images.githubusercontent.com/71209206/121451456-35ec6f00-c9d0-11eb-818f-7f0e305bcb18.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu) -  5.4.0-73-generic
 - Browser: Chrome
 - Version: 88.0.4324.182

**Additional context**
This error prevents the generation of specific tables.

**Comment by ufoscw** [comment]
thank you for the report
We'll check it out.

**Comment by yovahu** [comment]
Thanks for solving my problem!
