### ISSUE TITLE
Manage broken rules caused by editing previous rules

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#379]
**Is your feature request related to a problem? Please describe.**
If the rule is not executed due to the change of the previous rule, an error occurs.

_현재 앞의 룰의 변화로 인해 룰 실행이 불가한 경우 에러가 발생하게 되어있습니다._

**Describe the solution you'd like**
If a rule does not work now, we want to do the following:
1. Invert the rule to another color in the rule list
2. As a result of the rule, it returns the previous normal grid
3. Can be deleted and edited as the normal rules
4. It may be broken even if edited (in this case, it returns the previous normal grid)

_이제 어떤 룰이 실행되지 않는 경우 다음과 같이 처리하고자 합니다._
1. _룰 리스트에서 해당 룰을 다른 색으로 반전_
2. _룰의 결과 grid는 그 이전의 grid 그대로_
3. _삭제 및 편집 가능_
4. _편집해도 broken일 수도 있음 (이 경우에도 그 이전의 grid를 반환)_

**Additional context**
The server will return the result of the broken rule as valid: false in the corresponding entry in ruleStrings.

_서버에서는 broken룰의 결과에 대해 ruleStrings의 해당 항목에 valid: false로 표시해서 돌려주겠습니다._

![2018-10-08 2 03 11](https://user-images.githubusercontent.com/42257727/46593023-f83e3680-cb02-11e8-9c87-2507b10057e0.png)

**Comment by joohokim1** [comment]
Issue description에 적은 것과 같이 broken rule들에 대해 valid=false로 리턴하게 하였습니다.
정상적으로 response를 보내는 것 같은데 아래와 같은 에러가 발생하네요.
![2018-10-08 3 28 59](https://user-images.githubusercontent.com/42257727/46599766-23d11900-cb23-11e8-89d8-ae130d437fc0.png)

체크 부탁합니다. 담당자를 옮기겠습니다.

**Comment by paigechoi** [comment]
브로큰 룰을 편집할 때 이슈가 있습니다. 편집 버튼을 누르면 전 단계 그리드를 불러오는데 편집하려는 룰에 포함되어있는 칼럼이 불러온 그리드에 없을 경우 에러가 납니다.
이 부분은 UI에서 수정해서 올리겠습니다.
이번 스프린트에 우선순위가 높은 이슈들이 있어서 이 부분은 다음 스프린트에 이어서 진행하는 게 좋겠습니다.

**Comment by joohokim1** [comment]
This issue has been moved to 3.0.6

_3.0.6 으로 이동합니다._
