### ISSUE TITLE
Need to support personal database in workbench.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#385]
**Is your feature request related to a problem? Please describe.**
실질적으로 하둡 에코시스템 내에서 Hive 컨넥션 관리를 메타트론을 사용하는 모든 유저별로 관리하기가 쉽지 않음
따라서 Hive Connection 생성 시 일반 유저에게는 대부분 Write 권한이 없는 Connection 을 생성하여 제공하게 되며, 이에 따라 개인 데이터의 업로드 및 Workbench 쿼리 결과의 Table 저장을 할 수가 없음

**Describe the solution you'd like**
개인 데이터베이스를 지원하면 개인파일 업로드, Query 실행 결과의 Table 저장 시 전체 데이터베이스에 영향을 주지 않으며 개인 데이터와 전체 데이터의 연계 분석(JOIN) 지원이 가능함

**Comment by Taehui** [comment]
#320

**Comment by kyungtaak** [comment]
@Taehui #320 이슈와 중복되어 이슈를 종료합니다.
