### ISSUE TITLE
 Descending sort function required in time filter.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#389]
**Is your feature request related to a problem? Please describe.**
- 아래 스크린샷과 같이 타임필터 리스트의 정렬 보기 옵션이 ASC 만 지원함
![descending](https://user-images.githubusercontent.com/612173/46639145-70f2d080-cb9f-11e8-9462-30da4bff5514.png)

**Describe the solution you'd like**
- DESC 정렬 기능의 지원 필요

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang 현재 타임 필터 관련해서 이와 관련된 이슈가 포함되나요?

**Comment by minjung-cho** [comment]
METATRON-1038 와 동일

**Comment by minjung-cho** [comment]
@AnnieHwang @deidera08 
1번에서 현재/과거 라는 표현이 헷갈릴것 같아서, 아래와 같이 한번 더 세분화하면 어떨까요?

1.1 (Time-type)Discontinuous > Month by year
● JAN → DEC / 1월 → 12월
◎ DEC → JAN / 12월 → 1월
◎ High Frequency → low / 높은 도수 → 낮은 도수
◎ Low Frequency → high / 낮은 도수 → 높은 도수

1.2 (Time-type)Discontinuous > Day by week
● MON → SUN / 월요일 → 일요일
◎ SUN → MON / 일요일 → 월요일
◎ High Frequency → low / 높은 도수 → 낮은 도수
◎ Low Frequency → high / 낮은 도수 → 높은 도수

1.3 (Time-type)1.1/1.2번 이외의 단위
● A-Z
◎ Z-A
◎ High Frequency → low / 높은 도수 → 낮은 도수
◎ Low Frequency → high / 낮은 도수 → 높은 도수

2. Time-type 이외의 모든 타입
● In order of data / 원 데이터 순
◎ A-Z
◎ Z-A
◎ High Frequency → low / 높은 도수 → 낮은 빈도
◎ Low Frequency → high / 낮은 도수 → 높은 빈도

**Comment by kyungtaak** [comment]
@minjung-cho 님의 시간관련 의견은 디테일은 좋으나, 복잡도가 증가하는 문제가 있을것 같네요.
시간순/역순 을 의미하는 chronological/dechronological 이란것도 있던데요. 용어가 어렵긴합니다만, 검토 부탁드립니다. (@deidera08)

**Comment by minjung-cho** [comment]
@kyungtaak 제안 감사합니다. chronological/dechronological 로 사용 예제를 조사해 봤습니다. 단어가 어려운 만큼 유저 친화적이진 않아서 오더링 UI에서 사용된 사례를 찾기 어려웠고, dechronological은 사전에서 찾을 수 없어서 채택하기 어렵지 않나 싶습니다.

#651 에서 기존의 오더링 표기법도 가독성/직관성에 중점을 두고 재 검토했습니다. 특히 ascending/descending 이 영어권 사용자라 하더라도 한번더 생각하게 되는 단어인 것으로 파악되어 A-Z/Z-A로 변경되었고요. 
이와 같은 맥락에서 가능하면 시간 타입도 세분화해서 표기했으면 하는 바람입니다. 
위의 세분화한 안에서 [MON → SUN / 월요일 → 일요일] 은 월요일부터 한주가 시작된다는 작은 의미도 전달하고 있습니다. ^^; 

@AnnieHwang @deidera08 제 생각은 위와 같은데, 다른 의견 있으면 부탁드립니다

**Comment by AnnieHwang** [comment]
@kyungtaak 복잡성이 증가하는 부분이 시간값에 대해서고 Front에서 처리 가능할꺼 같아서.. 해도 괜찮을것 같은데. 논의해보시고 결정해서 말씀주세요~

**Comment by kyungtaak** [comment]
@deidera08 @minjung-cho @AnnieHwang  제가 이해가 가지 않는 부분이..나머지는 그대로 past / current 로 할건가요? 의미상 맞지 않는것 같은데요.. 흠.. 그리고 사전에 안나온다고, 대안이 없는건 아닙니다. (https://www.quora.com/What-are-some-antonyms-for-chronological)

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang @minjung-cho 

오해를 없애고자 간단한 사항 하나 말씀드립니다.
초기에 제가 제안드렸던 "past / current" 용어는 사용하지 않을 예정입니다.

제안해주신 chronological/dechronological 용어를 사용하는 1안과
JAN → DEC / MON → SUN와 같이 날짜를 월/요일로 세분화하여 표현하는 2안이 있습니다.

**Comment by kyungtaak** [comment]
@deidera08 답변 감사드립니다. 

> 2안의 경우 JAN → DEC / MON → SUN와 같이 날짜를 월/요일로 세분화를 할 경우 UI단에서 충분히 표현이 가능할 것이라고 생각했고 요일과 월을 표현하는 문자열은 이미 친숙해서 유저입장에서는 확실하게 인지할 것이라고 예상했습니다.

그렇다면,  1.1 (Time-type)Discontinuous > Month by year / 1.2 (Time-type)Discontinuous > Day by week  이외에는 ● A-Z/◎ Z-A 이렇게 표현하면 시간 순서/역순을 표현하겠다는 의도인지요? 

> Time-type 이외의 모든 타입 : ● In order of data / 원 데이터 순

이건 "원데이터 순" 이 없는것으로 알고 있습니다.

**Comment by deidera08** [comment]
@kyungtaak 
> 그렇다면, 1.1 (Time-type)Discontinuous > Month by year / 1.2 (Time-type)Discontinuous > Day by week 이외에는 ● A-Z/◎ Z-A 이렇게 표현하면 시간 순서/역순을 표현하겠다는 의도인지요?

아 네 맞습니다. 월, 일 을 제외하면 남은 날짜 표현은 년, 시, 분, 초 인데 모두 숫자값로 표현되기 때문에 문자열 순서로정렬시킨다면 0-9의 순서로 정렬되기 때문에 의도와 맞게 동작하리라 생각했습니다.

**Comment by kyungtaak** [comment]
@deidera08 네 알겠습니다. 그렇다면, "● In order of data / 원 데이터 순" 이슈만 남았군요. 이부분도 확인 부탁드립니다.

**Comment by deidera08** [comment]
@kyungtaak 
> @deidera08 네 알겠습니다. 그렇다면, "● In order of data / 원 데이터 순" 이슈만 남았군요. 이부분도 확인 부탁드립니다.

In order of data / 원 데이터 순을 빼먹었군요. 번거롭게 해드려서 죄송합니다 ㅜㅜ

컬럼/필터가 시간 타입일 경우는 In order of data가 없겠으나 그 외 타입일 경우(예 string 등)는 데이터소스의 원 데이터 순서가 필요하다고 생각했습니다.(기본값)
ingestion당시의 데이터 순서라고 생각하는데요, 이 또한 원천 데이터에 따른 순서이므로 사실상 같다고 생각합니다. 

살펴보시고 부족한 부분 있다면 말씀해주세요. 보완해나가겠습니다

**Comment by kyungtaak** [comment]
@deidera08 원데이터 순서라는게 애초에 존재하지 않습니다. "High Frequency → low" 또는 "A-Z" 가 기본이 되어야할것 같습니다.

**Comment by deidera08** [comment]
@kyungtaak 
> @deidera08 원데이터 순서라는게 애초에 존재하지 않습니다. "High Frequency → low" 또는 "A-Z" 가 기본이 되어야할것 같습니다.

피드백 감사합니다.
"In order of data / 원 데이터 순"은 기획서에서 삭제하고 기본값 A-Z로 설정하도록 하겠습니다.

**Comment by kyungtaak** [comment]
#1505 이슈와 중복으로 판단되어 해당이슈는 종료합니다.
