### ISSUE TITLE
When a specific filter value is selected, it is necessary to apply dependency between different filters.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#390]
**Is your feature request related to a problem? Please describe.**
- 두개 이상 필터 적용을 한 경우, 하나의 필터에서 특정값을 선택하면 해당 필터의 값이 적용된 데이터가 표현됨, 이 때 다른 필터에서도 값이 골라진 필터가 적용된 데이터를 기준으로 필터값 리스트가 표현되어야 함
- 테스트 주소 : https://discovery.metatron.app/app/v2/workbook/54787fde-3e3a-4589-a53e-e46e23437cf1
- 아래는 위 테스트 주소에서 월드컵 데이터소스(WorldCupMatches)를 가지고 HomeTeam, AwayTeam 을 필터로 적용한 차트
![all_filters](https://user-images.githubusercontent.com/612173/46641389-507d4300-cbac-11e8-9d40-e8cb5f0bff01.png)

- 위차트에서 HomeTeam 필터의 값을 Angola 를 고른 경우 실제 데이터는 1건만 남게되며, 이때 AwayTeam 은 Portugal 임
![angola_filter](https://user-images.githubusercontent.com/612173/46641414-7acf0080-cbac-11e8-9ffe-c5904c6f8d98.png)

**Describe the solution you'd like**
서로 다른 필터간의 디펜던시 적용 필요

**Comment by Taehui** [comment]
@kyungtaak @AnnieHwang 이 이슈를 버그로 봐야할지 기능 개선으로 봐야할 지 모르겠네요, 보는 사람에 따라 버그로 분류할 수도 있을 듯 합니다.

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang 위 이슈관련해서 검토 부탁드립니다.

**Comment by AnnieHwang** [comment]
@kyungtaak 저희 내부적으로는 글로벌필터와 차트필터 간에는 종속관계가 존재하지만, 동일레벨 간 (글로벌필터끼리, 혹은 차트필터끼리)는 종속관계를 정의하지 않는 것을 정책으로 하였습니다.  따라서 현재 위의 내용은 버그가 아닙니다. 

하지만 테스트 해 본 결과 글로벌필터와 차트필터 간에는 종속관계가 발생하지 않는 것으로 보여집니다. 해당 내용은 버그입니다. 따라서 신규 이슈로 해당 버그를 리포팅하겠습니다.

**Comment by minjung-cho** [comment]
현재로선 멀티 데이터소스의 위젯간 연결관계 설정하는 것으로 방향을 잡고 있습니다. 상세 기획이 나오면 공유드리겠습니다

**Comment by kyungtaak** [comment]
#1181 이슈로 처리할 예정입니다. 따라서 해당이슈는 닫겠습니다.
