### ISSUE TITLE
Displaying combo chart data is different from engine data

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#391]
**Describe the bug**
엔진에서 질의에 의해 전달된 데이터가 실제 Combo 차트 내  표현과 다릅니다. 

**To Reproduce**
1. Sales 데이터 소스와 연결된 대시보드를 생성한 후, 차트 위젯을 생성하고 Combo 차트를 선택합니다. 
2. (Optional) 개발자 도구를 열어, 실제 질의된 데이터가 전달 되는지 확인합니다.)
2. 선반 행 부분에 "Category" 를 교차 부분에 "Sales", "Profit" 항목 을 올려둡니다. 측정값은 편의를 위해 AVG 를 선택합니다.
3. 차트 위젯을 저장하고, 다른 차트위젯을 통해 동일한 선반조건으로 Bar 차트를 생성하여 값을 비교합니다.

**Expected behavior**
질의된 값과 차트에 표시된 값이 일치해야합니다.

**Screenshots**
- Case of combine chart
![image](https://user-images.githubusercontent.com/822255/46705816-30ad5400-cc6c-11e8-87a6-ff86a6d2afa9.png)

**Desktop (please complete the following information):**
<N/A>

**Additional context**
<N/A>

**Comment by dave-taeho** [comment]
@kyungtaak @esezin 
![sankey1](https://user-images.githubusercontent.com/14234215/46709062-ee404300-cc7c-11e8-93fd-9c29fa0829ee.png)
생키차트의 경우 Parent 노드는 Child 노드의 합계로 구성됩니다.
따라서 위의 케이스는 정상적인 케이스로 판단됩니다.

![sankey2](https://user-images.githubusercontent.com/14234215/46709089-0fa12f00-cc7d-11e8-800f-06df79fd1af6.png)
실제 데이터와의 차이는 AVG(Sales)의 결과에서 Parent 노드의 Value가 Child 노드의 합계로 내려오지 않고 있습니다. 이부분에 대해서 서버쪽 데이터 확인 요청드립니다.

**Comment by juheeko9** [comment]
f#391-display_chart_different_data 브랜치 생성하였습니다.

**Comment by ecoloy** [comment]
콤보차트는 Measure가 2개인 막대차트나 라인차트와 동일한 차트의 조건이라고 여기시면 됩니다. 그렇기때문에 콤보차트의 경우에는 데이터 레이블과 툴팁에서 Category Value/Precent를 아예 hide 해놓아야합니다. 
![2018-10-10 11 49 52](https://user-images.githubusercontent.com/28751002/46710422-ac1a0000-cc82-11e8-9843-dad3e9b44e0b.png)

**Comment by juheeko9** [comment]
@kyungtaak 바, 라인차트와 동일하게 measure가 2개인경우 Category Value, Percent가 disable되도록 처리하였습니다.

**Comment by kyungtaak** [comment]
@dave-taeho @esezin 샌키의 노드는.. 각 노드의 순수 측정값을 놓는게 아닌가요? 제가 잘못알고 있는건인지요?

**Comment by esezin** [comment]
@kyungtaak 네, 관련하여 오늘 구두논의도 있었습니다만, 간략하게 정리해보면 아래와 같습니다.
저도 더 확인해보았는데 현재 기준 (내부 데이터 처리와 무관하게) 표현은 제대로 되고 있는 상태입니다.

1. 생키 다이어그램은 여러가지 종류가 있으나, 기본적으로 노드간의 흐름(flow)의 양(amount)을 너비로 시각화하여 표현하는 것에 그 목적이 있음
2. 현재 e-chart의 생키 다이어그램은 좌/우 블럭의 총 양이 동일한 케이스를 표현하고 있으며, 즉, 100% 종속적인 카테고리 - 서브카테고리의 경우 서브 카테고리의 합이 카테고리와 동일해야 함
