### ISSUE TITLE
Give options to choose how to handle mismatched values when creating an orc snapshot

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#392]
**Is your feature request related to a problem? Please describe.**
Dataset을 hive-orc snapshot으로 만들 때 mismatched 된 값이 있는 경우 해당 row가 전부 삭제 됨.
나머지 정상적인 데이터들을 보존할 방법이 필요함
When creating an hive-orc snapshot, If there is  a single mismatched value, then entire row is deleted.
We need a way to keep other valid values.

**Describe the solution you'd like**
mismatched 된 값이 있는 경우 어떻게 처리할지 선택할 수 있는 옵션을 제공함. 기본 값이나 null로 변경.
Give options to choose how to handle mismatched values.(Ex. Set to default value or null)

**Describe alternatives you've considered**

**Additional context**

**Comment by joohokim1** [comment]
This issue will be moved to 3.0.7, and it should be changed into in-progress after the design stage.

_본 이슈는 3.0.7로 넘기고, 기획단계를 먼저 한 후에 In progress로 올려야 할 것 같습니다._

**Comment by mh0203** [comment]
this issue is closed and merged to new one.
