### ISSUE TITLE
Returning some other grid when snapshot is created with hive

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#394]
**Describe the bug**
하이브로 데이터 셋을 생성 후 데이터 데이터플로우에서 하이브 스냅샷을 생성했을 때 현재 데이터 셋의 그리드가 아닌 다른 데이터 셋의 그리드를 리턴합니다.

**To Reproduce**
Hive 로 데이터셋 생성
데이터플로우 화면에서 hive로 스냅샷 생성
see error

**Expected behavior**
현재 보고 있는 데이터셋 그리드 데이터와 같은 그리드 데이터가 스냅샷 상세에서 보여야합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/42233517/46708108-0b264780-cc78-11e8-9141-8efa792ed579.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
I guess it's a synchronization issue. Thanks for the bug report.

_일단 동기화 이슈로 판단됩니다. 버그 등록 감사드립니다._

**Comment by joohokim1** [comment]
We will check again after https://github.com/metatron-app/metatron-discovery/issues/373 is processed.

_https://github.com/metatron-app/metatron-discovery/issues/373 이슈가 처리가 된 후에 다시 체크해볼 예정입니다._

**Comment by joohokim1** [comment]
It probably happens when two or more users used the same hive table name simultaneously.
It's not reproduced. Closing the issue.
