### ISSUE TITLE
Fix advanced setting UI in datasource create step

### ISSUE THREAD

**Issue by brandon-wonjune** [metatron-app/metatron-discovery#396]
**Describe the bug**
- advanced setting는 접혀있는 것이 초기상태임. 현재는 펼친상태로 나와있음
- Job property와 Ingestion tunning config 순서가 바뀌어 있음

**Expected behavior**
- advanced setting은 접혀있는 상태가 되어야됨
- Job property와 Ingestion tunning config 순서가 바뀌어 있어야 됨

**Screenshots**
![image 24](https://user-images.githubusercontent.com/42233627/46709073-fbf5c880-cc7c-11e8-9dc0-a2caeff2b636.png)

**Desktop (please complete the following information):**
 - test server

**Comment by brandon-wonjune** [comment]
f#396-fix_advanced_setting_ui 브랜치 생성하였습니다.

**Comment by kyungtaak** [comment]
@brandon-wonjune 진행하실때, #384 이슈도 함께 확인하셔서 진행해주세요.

**Comment by brandon-wonjune** [comment]
@kyungtaak #384 이슈는 pull request에 확인사항 달아놓겠습니다.

**Comment by minjung-cho** [comment]
![2018-10-10 11 49 04](https://user-images.githubusercontent.com/28773903/46714574-176dcd00-cc97-11e8-821d-d1a39eb4fbbe.png)
데이터소스 상세화면에서도 advanced setting 초기상태와 두 항목(job property, ingestion tuning config) 순서 변경 적용 부탁드립니다. 
추가로, advanced setting에 내용이 없는 경우는 열고 닫는 UI가 보이지 않도록 해주십시요-
