### ISSUE TITLE
No vertical scroll on detail view screen of Column Dictionary

### ISSUE THREAD

**Issue by deidera08** [metatron-app/metatron-discovery#398]
**Describe the bug**
Column Dictionary의 상세화면에 스크롤이 없어서 (저해상도에서) 하단 정보를 보기 힘듭니다.

**To Reproduce**
1. Go to 'Metadata > Column Dictionary > detail view'
2. Can not see bottom contents

**Expected behavior**
Can see bottom contents by scrolling

**Screenshots**
![columndictionary](https://user-images.githubusercontent.com/42257766/46709816-517fa480-cc80-11e8-80d8-198acb9b01e0.png)

**Comment by brandon-wonjune** [comment]
f#398-fix_vertical_scroll_column_dictionary 브렌치 생성하였습니다

**Comment by kyungtaak** [comment]
@brandon-wonjune 금일회의후 정리된 사항으로 개발 진행 부탁드립니다.

**Comment by brandon-wonjune** [comment]
수정하였습니다.
![2018-11-12 11 29 05](https://user-images.githubusercontent.com/42233627/48323171-413b5a80-e66e-11e8-8044-592f245e5ef4.png)
![2018-11-12 11 29 12](https://user-images.githubusercontent.com/42233627/48323172-413b5a80-e66e-11e8-85f1-287504a39861.png)
![2018-11-12 11 29 20](https://user-images.githubusercontent.com/42233627/48323173-413b5a80-e66e-11e8-854b-639e74a19208.png)
