### ISSUE TITLE
Maven build fail

### ISSUE THREAD

**Issue by jaeminkim87** [metatron-app/metatron-discovery#4021]
**Describe the bug**
When building maven, the following error is displayed.
```
[ERROR] Failed to execute goal on project discovery-server: Could not resolve dependencies for project 
app.metatron.discovery:discovery-server:jar:2021.3-SNAPSHOT: Failed to collect dependencies at org.apache.hive:hive-
jdbc:jar:standalone:1.2.1000.2.5.5.0-157: Failed to read artifact descriptor for org.apache.hive:hive-
jdbc:jar:standalone:1.2.1000.2.5.5.0-157: Could not transfer artifact org.apache.hive:hive-jdbc:pom:1.2.1000.2.5.5.0-157 from/to 
maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [hortonworks-maven2-release-repository 
(http://repo.hortonworks.com/content/repositories/releases/, default, releases+snapshots), hortonworks-groups-public-repo 
(http://repo.hortonworks.com/content/groups/public, default, releases+snapshots)] -> [Help 1]
```

**To Reproduce**
1. git clone [master version]
2. mvn clean install -DskipTests

**Expected behavior**
Build fail

**Comment by alchan-lee** [comment]
It seems that you are using the maven 3.8.1 version or later.

Since maven version 3.8.1, the HTTP repository has been blocked. [[link](https://maven.apache.org/docs/3.8.1/release-notes.html)]

We are already aware of this issue and will be taking action soon.

**Comment by alchan-lee** [comment]
Before that, please edit your pom.xml (of root project) for the following links
(from http to **https**)

https://github.com/metatron-app/metatron-discovery/blob/master/pom.xml#L810
https://github.com/metatron-app/metatron-discovery/blob/master/pom.xml#L816
