### ISSUE TITLE
Change how to configure data preparation

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#405]
**Is your feature request related to a problem? Please describe.**
Currently, data preparation function work only when "dataprep" put as an active profile in application.yaml. Now, I want to enable the data preparation function without any additional setting after downloading from this repository.

_현재 data preparation 기능은 application.yaml에서 active profile로 dataprep을 넣어줘야 동작하도록 되어있습니다. 이제 별도의 추가 설정 없이도 repository에서 받은 상태 그대로도 data preparation 기능을 사용할 수 있도록 하고자 합니다._

**Describe the solution you'd like**
I need to change all the lines of the dataprep profile to always be set, and remove the code that raise an error when there is no profile named "dataprep" set.

_dataprep profile에 있는 부분을 모두 항상 설정되도록 바꾸고, "dataprep"이라는 profile이 없으면 설정하라고 에러를 내도록 해놓은 부분을 모두 없애야겠습니다._

**Describe alternatives you've considered**
We can just put the dataprep profile at deployment time by default.
The current plan, however, is to make the dataprep function always available at deployment time, so there is no such thing as profile, so we are changing to fixed instead of profile.

_그냥 dataprep profile을 항상 기본적으로 배포시에 넣는 방법도 있습니다.
하지만 현재 계획으로는, dataprep을 항상 배포시에 넣을 예정이기 때문에 profile 같은 것이 의미가 없고, 그래서 이렇게 아예 profile이 아닌, fixed로 변경하고 있는 중입니다._

**Comment by mh0203** [comment]
Merged
