### ISSUE TITLE
Is there any code style file available at the IntelliJ or Eclipse IDEA?

### ISSUE THREAD

**Issue by Artsiomxau** [metatron-app/metatron-discovery#41]

**Comment by kyungtaak** [comment]
Hello, Artsiomxau

We are preparing a guide for developers by the beginning of September at the latest.
Until then, I will share java code style files for intelliJ that I use internally.

Thank you for your interest in our project :)

[metatron_Java_codestyle_intellij.xml.txt](https://github.com/metatron-app/metatron-discovery/files/2295514/metatron_Java_codestyle_intellij.xml.txt)

**Comment by Artsiomxau** [comment]
@kyungtaak Thank you :)
