### ISSUE TITLE
CSV input/output enhancement (applying apache commons csv)

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#410]
**Is your feature request related to a problem? Please describe.**
If quotes exist in the current column, it is not clearly defined how single quote, double quote, back quote, etc. are handled.
The same is true for Escaping.

_현재 컬럼 내용중에 quote가 있는 경우, single quote, double quote, back quote 등이 어떻게 처리가 되는지 명확하게 정의되어있지 않습니다.
Escaping에 대해서도 마찬가지입니다._

**Describe the solution you'd like**
We will have to set up a policy for quotes and escaping characters.
It is good to see how the Spark engine produces the results, and see if it works as an external table in the hive.

_Quote와 escaping character들에 대해 정책을 정해서 구현해야하겠습니다.
Spark engine이 어떻게 결과를 내는지를 보고, hive에서 external table로 제대로 동작하는지를 참고해서 진행하는 것이 좋겠습니다._

**Additional context**
It would be nice to refer to the behavior of other data preparation products.

_다른 data preparation 제품이 어떻게 결과를 내는지도 참고해보면 좋을 것 같습니다._

**Comment by joohokim1** [comment]
@ nowone123 is going to test the behavior of Spark engine.
Assignees changed.

_@nowone123 (엑슨투 이현균) 님께서 Spark engine의 동작을 조사해서 알려주시기로 하였습니다.
담당자를 옮깁니다._

**Comment by nowone123** [comment]
1. 출력시 각 컬럼 값에 일괄적으로 quote가 붙는지
   - quote 문자열 옵션으로 지정가능( quote 옵션) 
   - 옵션으로 정의 할수 있습니다 (Writer : quoteAll 옵션)

2. 그렇다면 내용중에 quote가 있다면 어떻게 표현되는지
   - quote 의 escape 문자를 지정할수 있습니다 ( escape 옵션)

3. 혹시 일괄 quoting을 하지 않는다면 개행문자는 어떻게 출력되는지 (edited)
   - 개행된 그대로 출력이 됩니다. 

- Spark 버전의 특성을 고려해야 합니다. 최소 버전을 명확히 해야 할 것 같습니다,
- 아래의 multiLine 옵션은 spark 2.2.0 이상에서만 동작합니다.
- 입력및 출력에 대해서 명확한 정책을 정하는 것이 필요할 것 같습니다.


위의 내용에 대해서 테스트한 예제 입니다. 

**불러오기 테스트** 

quoto 처리 (source)

```
"num", "alpah", "seq" ,"date"
"0001", "A", "001" , "2017/01/01 12"
"0001", "B", "002" , "2017/01/01 13"
```

val options = Map("header" -> "true", "sep" -> ",", "quote"-> "\"","ignoreLeadingWhiteSpace" -> "true")
```
+----+-----+---+-------------+
|_c0 |_c1  |_c2|_c3          |
+----+-----+---+-------------+
|num |alpah|seq|date         |
|0001|A    |001|2017/01/01 12|
|0001|B    |002|2017/01/01 13|
+----+-----+---+-------------+
```

 **multiLine 옵션( spark 2.2.0 이상 ) --- 컬럼값에 여러줄 일 경우 (source)**  
```
'num', 'alpah', 'seq' ,'date'
'0001', '\'A\'', '001fd
kkds' , '2017/01/01 12'
'0001', 'B', '002' , '2017/01/01 13'
```
val options = Map("header" -> "true", "sep" -> ",", "quote"-> "'" "escape" ->"\\","ignoreLeadingWhiteSpace" -> "true", "multiLine" -> "true")

```
+----+-----+----------+-------------+
|num |alpah|seq       |date         |
+----+-----+----------+-------------+
|0001|'A'  |001fd
kkds|2017/01/01 12|
|0001|B    |002       |2017/01/01 13|
+----+-----+----------+-------------+
```

CSV 로드(load ) 옵션
https://spark.apache.org/docs/2.2.0/api/java/org/apache/spark/sql/DataFrameReader.html#csv-scala.collection.Seq-
주요옵션:
------------------------------------------

- sep (default ,)                         : sets the single character as a separator for each field and value.
- quote (default ")                       : sets the single character used for escaping quoted values where the separator can be part of the value. If you would like to turn off quotations, you need to set not null but an empty string. This behaviour is different from com.databricks.spark.csv.
- escape (default \)                      : sets the single character used for escaping quotes inside an already quoted value.
- header (default false)                  : uses the first line as names of columns.
- ignoreLeadingWhiteSpace (default false) : a flag indicating whether or not leading whitespaces from values being read should be skipped.
- ignoreTrailingWhiteSpace (default false): a flag indicating whether or not trailing whitespaces from values being read should be skipped.
- multiLine (default false)               : parse one record, which may span multiple lines.
- ...



**CSV 저장 테스트** 

 quote 문자열 없이 저장
```
+----+-----+----------+-------------+
|num |alpah|seq       |date         |
+----+-----+----------+-------------+
|0001|'A'  |001fd
kkds|2017/01/01 12|
|0001|B    |002       |2017/01/01 13|
+----+-----+----------+-------------+
```

val options = Map("header" -> "true", "sep" -> ",", "quote"-> "'" "escape" ->"\\","ignoreLeadingWhiteSpace" -> "true", "quoteAll" -> "false")

저장된 CSV 파일
```
num,alpah,seq,date
0001,'\'A\'','001fd
kkds',2017/01/01 12
0001,B,002,2017/01/01 13
```

quote 문자열 저장 

```
+----+-----+----------+-------------+
|num |alpah|seq       |date         |
+----+-----+----------+-------------+
|0001|'A'  |001fd
kkds|2017/01/01 12|
|0001|B    |002       |2017/01/01 13|
+----+-----+----------+-------------+
```

val options = Map("header" -> "true", "sep" -> ",", "quote"-> "'" "escape" ->"\\","ignoreLeadingWhiteSpace" -> "true", "quoteAll" -> "true")

저장된 CSV 파일
```
'num','alpah','seq','date'
'0001','\'A\'','001fd
kkds','2017/01/01 12'
'0001','B','002','2017/01/01 13'
```

CSV 저장(save)  옵션
https://spark.apache.org/docs/2.2.0/api/java/org/apache/spark/sql/DataFrameWriter.html#csv-java.lang.String-
주요옵션:
------------------------------------------

- sep (default ,)                         : sets the single character as a separator for each field and value.
- quote (default ")                       : sets the single character used for escaping quoted values where the separator can be part of the value.
- escape (default \)                      : sets the single character used for escaping quotes inside an already quoted value.
- escapeQuotes (default true)             : a flag indicating whether values containing quotes should always be enclosed in quotes. Default is to escape all values containing a quote character.
- quoteAll (default false)                : a flag indicating whether all values should always be enclosed in quotes. Default is to only escape values containing a quote character.
- header (default false)                  : writes the names of columns as the first line.
- ignoreLeadingWhiteSpace (default true)  : a flag indicating whether or not leading whitespaces from values being written should be skipped.
- ignoreTrailingWhiteSpace (default true) : a flag indicating defines whether or not trailing whitespaces from values being written should be skipped.

**Comment by joohokim1** [comment]
Now we are going to output the file snapshot with all the values ​​enclosed by " and we will also check to see if it can be queried as a Hive external table.

_이제 file snapshot에 대해 모든 값을 "로 감싸서 출력을 내고자 합니다. 또한 이 결과 Hive external 테이블로써 조회할 수 있는지도 체크할 예정입니다. 곧 진행하겠습니다._

**Comment by joohokim1** [comment]
As a result, only the input of the wrangled dataset has been changed.
Applying to snapshot will be processed by https://github.com/metatron-app/metatron-discovery/issues/811.
