### ISSUE TITLE
Add content to summary information in the last step of dashboard creation

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#411]
**Problem**
대시보드 생성 시, 마지막 스텝의 요약 정보가 다른 유사 화면에 비해 부족함 
![44500021-88dec580-a6c1-11e8-9d28-0d3caf571615](https://user-images.githubusercontent.com/28773903/46734661-f1641f00-ccce-11e8-8ff1-2274eb0f3824.png)

**Solution**
데이터소스의 조인, 연결키 정보를 추가로 보여줌
![2018-10-10 8 53 35](https://user-images.githubusercontent.com/28773903/46734670-f7f29680-ccce-11e8-8af2-0269aa2eeb01.png)

**Additional context**
#46

**Comment by minjung-cho** [comment]
@AnnieHwang @kyungtaak 첨부한 기획안과 같이 요약 정보를 추가하는건 어떠신지요?

**Comment by eltriny** [comment]
@AnnieHwang @kyungtaak 
위 내용대로 진행해도 되는지 확인 부탁드립니다.

**Comment by AnnieHwang** [comment]
@eltriny @minjung-cho @kyungtaak 일단 어제 회의 내용도 있고 하니, association 내용은 재기획후 진행하면 어떤가 싶습니다. 
(어제 회의 내용이 association기능을 대시보드 패널 내로 이동 시키면 어떠냐는 회의 의견이 있어 재 기획 할 예정입니다.) 해당 내용 일단 클로즈 하겠습니다.
