### ISSUE TITLE
Alias display error in chart data panel

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#415]
**Describe the bug**
차트 상세 화면에서 알리아스를 세팅하면 표출되지 않음

**To Reproduce**
1. Go to '차트 상세 화면'
2. 좌측 데이터 패널 이동
3. 더보기 버튼 클릭
4. 'Alias' 변경

**Expected behavior**
기획상 아래와 같이 되어야 합니다.
![image](https://user-images.githubusercontent.com/6300003/46783153-266e8100-cd64-11e8-8c7d-54485f930cae.png)

**Screenshots**
현재 이렇게 보여집니다.
![image](https://user-images.githubusercontent.com/6300003/46783158-31c1ac80-cd64-11e8-9bfe-c9c45b6d07b4.png)

**Comment by dave-taeho** [comment]
#415-chart_data_panel_alias 브랜치 추가하였습니다.
