### ISSUE TITLE
'min/max' setting fails to initialize

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#417]
**Describe the bug**
1. min/max값 설정 하면 차트가 축을 이탈한 영역까지 그려지는 현상
2. min/max값을 설정 한 후 'fit to scale' setting 을 하면 작동 안함
3. 'fit to scale' setting 을 취소하면 원래상태로 돌아가야 하지만 작동 안함

**To Reproduce**
1. Go to '차트 상세'
2. Click on 'Y Axis Setting'
3. 'Set axis range' > 'Max' 값 세팅 => (버그1. min/max값 설정 하면 차트가 축을 이탈한 영역까지 그려지는 현상발생)
4. 'Fit to Scale' 체크(on) => (버그2. min/max값을 설정 한 후 'fit to scale' setting 을 하면 작동 안함)
5. 'Fit to Scale' 체크(off) => (버그3. 'fit to scale' setting 을 취소하면 원래상태로 돌아가야 하지만 작동 안함)

**Expected behavior**

**Screenshots**
![2018-10-11_15-26-00](https://user-images.githubusercontent.com/6300003/46784732-325d4180-cd6a-11e8-81f0-fde7537d5614.gif)

**Comment by juheeko9** [comment]
해당 이슈는 #418 에서 같이 처리하겠습니다.
