### ISSUE TITLE
Changing chart pivot doesn’t apply to chart

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#418]
**Describe the bug**
- 차트의 선반에서 선반의 measure값을 제거시 차트에 반영이 안되는현상 발생

**To Reproduce**
1. 차트 상세화면으로 이동
2. 바차트를 선택하고 열선반 : dimension 1개, 교차선반 : measure 2개로 차트를 그리기
3. measure를 한개 제외
4. 차트화면에서 measure가 선반에서 제외된부분이 반여이 안되는것을 확인할 수 있음

**Expected behavior**
- 선반의 변경에 따라서 차트화면에 반영되어야합니다.

**Screenshots**
![screen shot 2018-10-11 at 1 52 32 pm](https://user-images.githubusercontent.com/3685833/46785139-d3003100-cd6b-11e8-80c6-b32265cb38ed.png)

**Desktop (please complete the following information):**
- OS: iOS
- Browser: chrome
- Version : 69.0

**Additional context**

**Comment by juheeko9** [comment]
f#418-chart_apply_bug 브랜치 생성하였습니다.

**Comment by juheeko9** [comment]
해당 이슈에서 아래의 버그들을 같이 처리하였습니다

1. 라인차트의 y축 axis range의 min / max 설정 후 fit to scale로 설정시 적용이 안되는 현상
<img width="1564" alt="fittodatascalebug" src="https://user-images.githubusercontent.com/42233502/46787014-891a4980-cd71-11e8-8248-9dc95a906dfc.png">
.
2. 파이차트의 data label을 설정 후 마우스 오버시 data label이 사라지는 현상

3. 파이차트의 dimension -> measure -> dimension으로 설정 시 범례가 겹치는 현상
![image 2](https://user-images.githubusercontent.com/42233502/46787199-f75f0c00-cd71-11e8-9fa8-76e00d2e8e44.png)

3. 센키차트의 data label의 text color를 manual로 설정 후 auto로 해제시 초기화가 되지않는 현상 (#414)
![46782955-36d22c00-cd63-11e8-8a5d-33782e611b1e](https://user-images.githubusercontent.com/42233502/46787323-44db7900-cd72-11e8-8a57-0a10283beede.png)
