### ISSUE TITLE
Error number format Abbreviations

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#420]
**Describe the bug**
- 숫자 포맷에서 약어 설정(Abbreviations) 시, 소수점 표시가 약어 뒤에 표시됩니다.

**To Reproduce**
1. 차트 생성화면으로 이동합니다.
2. 차트를 그립니다.
3. 숫자포맷 패널에서 약어 설정(Abbreviations)을 kilo로 설정하고 소수점 자리수를 변경합니다.
4. (e.g.) 2K.00 등으로 약어뒤에 소수점이 붙습니다.

**Expected behavior**
- 소수점뒤에 약어가 표현되야 합니다.

**Screenshots**

**Desktop (please complete the following information):**
- OS: iOS
- Browser : chrome
- Version 69.0

**Additional context**

**Comment by dave-taeho** [comment]
#420_number_format_abbreviations 브랜치 추가하였습니다.
