### ISSUE TITLE
Workbench query fail message not printed.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#432]
**Describe the bug**
workbench query fail message not printed.

**To Reproduce**
1. Go to workbench
2. input query
select aa;
3. no error message printed.

**Expected behavior**
error message is printed.

**Screenshots**
<img width="1281" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46841469-1eb1e980-ce03-11e8-9fc3-c40ac9171297.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Additional context**

**Comment by ufoscw** [comment]
@sting009 
퀴리를 취소하거나 use default; 와 같이 결과 없는 경우 No Data로 표시되면서 
상단 버튼들이 나옵니다. (차트 미리보기, 데이터소스 저장, csv 다운로드) 누르면 에러나니까 "로그 보기" 버튼 말고는 숨겨주세요.

**Comment by ufoscw** [comment]
@sting009 
쿼리 취소 후 View result 버튼 누르면 결과창이 모두 사라집니다.
<img width="1284" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46853938-7ae43000-ce3a-11e8-836b-8b400a1db3e6.png">

**Comment by ufoscw** [comment]
@eltriny 
1. 탭 2개 생성 (탭1, 탭2)
2. 탭1 에서 select aaa; 실행하여 에러발생
3. 탭1에서 창 최대화 후 정상사이즈로 변경
4. 탭2로 이동
5. 에디터에 엔터키 계속 입력해도 스크롤바 안생김

**Comment by ufoscw** [comment]
@eltriny 
1. 선택한 쿼리 없이 선택 쿼리 실행을 할 경우 무한 로딩바가 뜹니다.

**Comment by goodljy** [comment]
정상 동작 확인. 2018.10.16
