### ISSUE TITLE
Query excuted after cancel.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#454]
**Describe the bug**
Presto와 같이 Query 취소 처리가 정상적이지 않은 경우 취소 후에도 쿼리를 실행할수 있으나 정상적으로 수행되지 않음.

**To Reproduce**
1. 프레스토 커넥션 워크벤치로 이동
2. 다중 쿼리 수행
3. 쿼리 수행 중 취소 버튼 클릭
4. 취소 버튼 클릭 후 취소 메시지가 표시되기전 빠르게 쿼리 수행 버튼 클릭
5. 로딩바가 깜빡이며 아무런 동작 하지 않음

**Expected behavior**
취소 버튼 클릭 후 에러나 취소 메시지가 표현되기 전 쿼리 수행을 할수 없어야 합니다.
1. AS-IS
   - cancel api response 시점에 로딩바 닫힘

2. TO-BE
   - cancel api response 시점이 아니라 run api response 시점에 로딩바 닫기
   - query 수행전 status 체크시 CANCELLED 상태도 쿼리 수행 불가 상태로 판단하도록 원복

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Chrome

**Additional context**

**Comment by eltriny** [comment]
#462 issue branch 에서 같이 작업중입니다.
