### ISSUE TITLE
Empty header in Text Table

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#458]
**Describe the bug**
TextTable의 pivot에서 첫번째 dimension에 컬럼을 지정하지 않고 두번째만 지정한 경우 header에 공백이 있는 줄이 나타남

**To Reproduce**
1. Go to Create Chart
2. Click on TextChart
3. 두번째 Dimension에 추가 
4. Measure 추가
5. Chart Type에서 Pivot 선택, Vertical 또는 Horizontal 선택

**Expected behavior**
- Vertical을 선택한 경우 Header에 컬럼명 또는 Alias가 나타나야 함
- Horizontal을 선택한 경우 캡쳐한 화면에 있는 빈 공간이 나타나지 않아야 함
- dashboard 상테서는 Header의 Width가 조절이 가능해야 함

**Screenshots**
![44035535_2673386966220695_1478529357638008832_n](https://user-images.githubusercontent.com/321821/46998439-1df7bb00-d155-11e8-8894-4ec480e9121e.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser： chrome
 - Version: 69.0.3497.100 

**Additional context**
없음

**Comment by eltriny** [comment]
@esezin 
본 이슈에 대한 내용 확인 부탁드립니다.

**Comment by esezin** [comment]
@babokim @eltriny 
우선 재현경로를 좀 더 분명하게 하자면, 본문스타일 아래의 Aggregation Column이 체크되어 있어야 합니다. Chart Type의 Vertical / Horizontal 옵션은 집계를 표시하는 헤드컬럼의 보기 위치를 설정하는 것이기 때문입니다. 이 부분에서 IA와 정보 그루핑에 대한 근본적인 개선이 좀 더 필요할 것으로 보입니다만, 당 이슈에서는 좀 더 표면적인 부분만 다루는 것이 좋을 것 같습니다.

**1. Vertical(세로보기)의 경우에는, 컬럼명이 중복될 우려가 있어 현재 상태 그대로 유지하는 것이 좋겠습니다.**
![texttable-vertical](https://user-images.githubusercontent.com/28885462/48397963-ca33be00-e762-11e8-83e0-0f534aabe99d.PNG)

**2. Horizontal(가로보기)의 경우에는, 위에 비어있는 행을 삭제하는 것이 좋겠습니다.**
![texttable-horizontal](https://user-images.githubusercontent.com/28885462/48397975-d15acc00-e762-11e8-8819-aa88946c5dc0.PNG)
