### ISSUE TITLE
 Allow spaces in column names in data prep

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#460]
**Is your feature request related to a problem? Please describe.**
현재는 컬럼 이름에 공백이 허용되지 않습니다.
컬럼 이름에 공백을 허용하도록 변경합니다.

Currently, column names do not allow blank spaces.
Allow blank spaces in column names.

**Describe the solution you'd like**
현재 Dataframe 내부에서는 컬럼 이름에  공백이 포함되어도 처리가 가능합니다.
Web Interface를 통해 "공백이 포함된 컬럼 이름"을 입력하는 부분과,
Hive와 같은 외부 플랫폼에 snapshot을 내보낼 때 컬럼이름을 변경하는 부분의 개발이 필요합니다.

공백이 포함된 컬럼 이름을 입력할때는 앞뒤를 `(backticks)로 묶어서 컬럼이름임을 명시하도록 합니다.

[개발사항]
1. Rule Builder에서 공백이 포함된 컬럼이름을 선택 할 경우 `로 묶어서 rulestring을 넘겨주도록 변경.
2. Rename Rule에서 공백이 포함된 문자열을 value로 넣을 수 있도록 변경.
3. Parser에서 Rule String을 Rule로 만들 때 `로 묶인 컬럼 이름을 일반적인 컬럼 이름으로 바꿔주는 로직 추가.
4. snapsot을 생성할 때 공백이 포함된 컬럼명을 변환하여 처리하는 로직 추가.

Dataframe class can handle with column names that contain space.
We need to make it possible to input column name contains spaces through web interface,
and modify column name when creating hive snapshot.

If you need to enter a column name that contains spaces, enclose it in `(backticks) and make it clear that it is a column name

[to do]
1. In the Rule Builder, if you select a column name that contains spaces, enclose column name with ` in the rulestring.
2. In Rename rule, make it possible to enter column name that contains spaces in value field.
3. When parser create Rule object with rule-string, remove ` from column names that enclosed by `.
4. When creating the snapshot, modify column names that contains spaces.

**Describe alternatives you've considered**

**Additional context**

**Comment by mh0203** [comment]
작업은 아래 브랜치에서 해주시면됩니다.
https://github.com/metatron-app/metatron-discovery/tree/f%23460-Allow_spaces_in_column_names_in_data_prep

**Comment by mh0203** [comment]
UI에서는 개발사항 1, 2를 적용해 주시면 됩니다. 현재 서버에서는 공백이 포함된 column name이 rulestring으로 넘어와도 처리 가능하도록 변겨되어있습니다.

**Comment by sang-hee-lee** [comment]
편집시 에러나는 부분이 있습니다. ruleString을 jsonRuleString으로 변경해야 하는 작업이 남아있습니다.
우선순위가 높은 이슈 처리로 다음 스프린트로 진행하는 게 좋겠습니다.

**Comment by joohokim1** [comment]
Moved to 3.0.6

_3.0.6으로 옮깁니다._

**Comment by joohokim1** [comment]
run build
deploy to 2

**Comment by paigechoi** [comment]
컬럼명에 공백을 허용하는 것은 모든 룰 (over 20) 에 대한 처리가 필요한 일입니다.
데이터플로우 룰 쪽 UI 대부분의 코드가 수정되고 있어서 많은 테스트와 시간이 필요합니다.
이번 스프린트 내로 처리하도록 하겠습니다.
