### ISSUE TITLE
Query Editor tab must be changeable during query execution.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#462]
**Is your feature request related to a problem? Please describe.**
Query Editor tab must be changeable during query execution.

**Describe the solution you'd like**
add queryeditor id on query execute api's response and log message.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ufoscw** [comment]
@eltriny 
<img width="1273" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47197369-cb124380-d3a0-11e8-8e36-63ca9ce50c4a.png">

**Comment by ufoscw** [comment]
@eltriny 
정상적으로 캔슬이 완료 된 후 다음 쿼리 수행할때  쿼리 수행중이라서 수행불가능 메시지가 나옵니다.
이때 status response는 CANCELLED 인데 더이상 실행이 안되네요.

**Comment by eltriny** [comment]
> @eltriny
> 정상적으로 캔슬이 완료 된 후 다음 쿼리 수행할때 쿼리 수행중이라서 수행불가능 메시지가 나옵니다.
> 이때 status response는 CANCELLED 인데 더이상 실행이 안되네요.

@ufoscw 
#454 이슈에서 TO-BE 에 
"query 수행전 status 체크시 CANCELLED 상태도 쿼리 수행 불가 상태로 판단하도록 원복"
이렇게 적어주셔서 CANCELLED 수행 불가 상태로 두었는데 다시 제외해야 하나요??

**Comment by ufoscw** [comment]
로직 다시 확인해볼게요.
