### ISSUE TITLE
Errors in bar chart display when pivoting a column on a row value

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#463]
**Describe the bug**
막대차트에 행값에 컬럼을 피봇팅 하는 경우 막대차트 표출이 Stacked가 아닌, Series로 표현이 됩니다. 

**To Reproduce**
1. Go to '차트상세'
2. 막대차트 선택
3. 열 행에 각각 차원값을 피봇팅, 교차 값에 측정값을 피봇팅 함
4. 막대차트가 시리즈 형태로 화면에 표출됨

**Expected behavior**
Stacked 형태로 차트가 표출되어야 합니다.

**Screenshots**
<img width="1833" alt="barchart-question" src="https://user-images.githubusercontent.com/6300003/47055234-40d7ad00-d1f1-11e8-8cef-520487f65b07.png">

**Comment by kyungtaak** [comment]
@metatron-app/design  @AnnieHwang 해당이슈는 이미 해결되어 있으나, stacked 로 표현할 경우 기본 색상 표현을 정리할 필요가 있어 보입니다. 현재는 series 로 되어 있어 stacked 로 표현햇지만 모두 같은 색상으로 표현되어 효과가 반감되는것 같습니다. 확인 부탁드립니다.

**Comment by esezin** [comment]
@kyungtaak @AnnieHwang 
네, 기존 정책대로 구현되어 있는 상황이기는 합니다만, 말씀주신 것 처럼 UX가 반감되는 면이 있습니다.
차원값이 2개 이상 선반에 올라가는 경우(즉, 차원값 기준으로 색상 설정이 가능해지는 시점)에 자동으로 색상 설정을 잡아주는 것이 대안이 될 것 같습니다.
단, 공통 UX로 적용이 되어야 하는 사안이라 차트 전반적으로 검토를 진행해보도록 하겠습니다.

**Comment by esezin** [comment]
@kyungtaak @AnnieHwang 
다시 찾아보니, 위에서 말씀드린대로 정의되어 있었네요; 
현재 미구현되어 있는 것이 별도의 이유가 있는 것인지 내부논의를 해보겠습니다.

![463-01](https://user-images.githubusercontent.com/28885462/50715243-c287fa00-10bf-11e9-9fff-96498390835e.PNG)

**Comment by i1befree** [comment]
@kyungtaak 위에 것이 같은 색상으로 되는 것이 의미가 반감되지 않는다고 봅니다. 사용자에게 기획에서 일관된 의도대로 보여주는 것은 매우 중요합니다. 자동으로 뭔가를 바꿔줘야만 좋은 기능은 아닙니다.
