### ISSUE TITLE
Relocating information in the query history

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#465]
**Problem**
![pasted_image_at_2018-10-16__6_40_pm](https://user-images.githubusercontent.com/28773903/47058818-ab90e480-d201-11e8-8f7b-f56004ad9237.png)
1. 초기 화면 구성과 달리, 시간 정보에 실행자 정보가 포함되어 내려오고 있어서 텍스트가 잘림
2. 쿼리문이 나오는 부분의 헤더 레이블 부적합 (Action)

**Solution**
![image 25](https://user-images.githubusercontent.com/28773903/47058816-a895f400-d201-11e8-9111-a34762668b3d.png)
1. 타임과 쿼리 정보 재배치. 스크린샷 참조
2. Action --> Query 로 변경
3. 말줄임이 나타날 수 있는 부분에 인포팁이 적용되어야 합니다

**Alternatives**
None

**Additional context**
None

**Comment by ufoscw** [comment]
@minjung-cho 
elapsed time 표현 하는 부분도 개선이 필요해 보입니다.
오래 걸리는 쿼리는 30분이 넘어가기도 하고 빠르게 수행되는 쿼리는 1초만에도 수행이 되는데요.
적절하게 표현할수 있는 방법이 필요합니다.
현재 쿼리 수행시간을 보여주는 곳이 여러군데 있는데 표현 룰도 통일해야 할것 같아요.
워크벤치 결과창, 쿼리 히스토리, 데이터 모니터링 3군데 입니다.
저장된 데이터는 밀리세컨 값입니다.

**Comment by minjung-cho** [comment]
@AnnieHwang 아래와 같이 정의하면 어떨까 합니다. 아직 정리할 공통 표현법이 많네요 ^^;

@ufoscw 문의 주신 소요시간의 단위 표현에 대해서 전달드립니다.
최소 단위는 ms, 최대 단위는 hour로 하고 아래와 같이 표현합니다.
**2h 59m 59s 999ms**
<img width="842" alt="2018-11-13 12 55 54" src="https://user-images.githubusercontent.com/28773903/48390350-d872e180-e744-11e8-83b2-571d786b0fe2.png"> 

참고로...
기존 화면에서 sec, min 와 같은 축약형은 문장에서 '구' 이상의 단어 조합으로 의미가 전달될때 사용합니다. 
예를들어, 콘텐츠 목록에서 업데이트 시점을 표현할때 '1 min ago' 와 같이 표현합니다.

**Comment by ufoscw** [comment]
@minjung-cho 
최대 몇단계의 단위를 보여줄지는 스크린샷으로 봤을때는...2단계인거죠?
시간단위일 경우는 시 분,
분 단위일 경우는 분 초
초 단위일 경우는 초, ms

@eltriny 
작업하실때...기존에 서버사이드에서 포맷 변환해서 response에 내려주던 속성은 무시하고 front에서 단위 변환하도록 변경해주세요.
쿼리 수행에 걸린시간을 ms 단위로 response에 포함되어 있습니다.

**Comment by minjung-cho** [comment]
@ufoscw 넵 두개 단위만 보여줘도 될것 같습니다. 아래 단위는 버림으로 하는게 어떨까요?

**Comment by minjung-cho** [comment]
@ufoscw #538은 디자인 수정, 이 이슈는 개발 수정으로 진행한다고 하셔서 아래 내용 추가합니다.
@sting009 
![2018-11-13 4 38 33](https://user-images.githubusercontent.com/28773903/48398258-9dcc7180-e763-11e8-849b-4e3399073bec.png)
1. Fail 일때 로그 팝업 출력
2. 삭제 확인 팝업 추가
'쿼리 히스토리를 전부 삭제하시겠습니까?' 취소/삭제

**Comment by sting009** [comment]
@ufoscw 
위의 5번 에러로그 보기 부분에서 
로그 내용 부분은 

![image](https://user-images.githubusercontent.com/42328567/48402297-ac6c5600-e76e-11e8-8570-3bcbbe043f69.png)

위의 queryLog 부분 사용하도록 하겠습니다.

**Comment by kyungtaak** [comment]
@ufoscw @sting009 아래 ie11 이슈도 함께 점검부탁드립니다.
![image](https://user-images.githubusercontent.com/822255/48524631-69bc9200-e8c4-11e8-9dae-6149a87f86cb.png)

(ie11 확인하실때 스크롤도 함께 확인해주시면 좋을것 같습니다.)
