### ISSUE TITLE
Dashboard crashes when saving after performing dashboard

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#468]
**Describe the bug**
대시보드 편집 작업을 하고 저장 시 대시보드가 깨지는 현상 발생

**To Reproduce**
1. Go to 대시보드 편집 후 저장 시

**Screenshots**
![image 12](https://user-images.githubusercontent.com/6300003/47066619-a2177480-d221-11e8-8c9c-2a3237e39c80.png)
![image 13](https://user-images.githubusercontent.com/6300003/47066621-a6439200-d221-11e8-86b6-609bccacb36b.png)

공통적으로 보여지는 'importanceType' 이 undefined이라는 브라우저 에러가 납니다.

**Comment by eltriny** [comment]
#494 이슈와 중복된 내용이라 494 이슈에서 처리하고 본 이슈는 close 하겠습니다.
