### ISSUE TITLE
The description is incorrect if you did not enter a password on the login page.

### ISSUE THREAD

**Issue by Artsiomxau** [metatron-app/metatron-discovery#47]
**Describe the bug**
The description is incorrect if you did not enter a password on the login page.

**To Reproduce**
1. Click the login button without entering any information on the login page. (http://localhost:8180/app/v2/user/login)

**Expected behavior**
Please enter your password in English.

**Screenshots**
<img width="487" alt="login-page" src="https://user-images.githubusercontent.com/42443367/44310118-02e62480-a40c-11e8-81ac-9a9318710d3e.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 68.0.3440.106

**Additional context**

**Comment by kyungtaak** [comment]
@Artsiomxau 
I have confirmed that the message does not apply locale. This will be fixed soon. :)

**Comment by Artsiomxau** [comment]
Thank you :) @kyungtaak

**Comment by eltriny** [comment]
@kyungtaak word-break 수정하였습니다.
