### ISSUE TITLE
Improve query result window usability

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#471]
**Problem**
1. 쿼리 실행 취소 버튼의 가시성이 좋지 않음
2. 쿼리 실행 단계를 알수 없어서, 쿼리 실행 실패 또는 소요 시간이 길 경우의 사용자 피드백이 약함
3. 쿼리 실행 중 로그의 가독성 개선 필요
4. row 수가 중요한 정보임에도 버그 및 정책이 부족으로 정보 취득이 어려움

**Solution**
(Problem의 넘버링과 무관합니다)
1. 정보 및 버튼(UI 요소) 의 재배치
2. 실 사용자에게 익숙한 감성 및 가독성 지원
-- 콘솔창과 같은 BG 컬러 
-- 로그 하이라이트 (INFO, ERROR, 등등 특정 키가 되는 텍스트의 디자인(컬러) 적용)
3. 쿼리 실행 프로그래스 정보 추가
4. 쿼리 실행 단계 별 결과(쿼리, 결과, 로그) 확인이 용이한 UI 지원
5. 쿼리 재실행 기능 추가

**Additional context**
#135

**Comment by minjung-cho** [comment]
![2018-10-18 4 14 27](https://user-images.githubusercontent.com/28773903/47137294-27b62580-d2f1-11e8-94e4-6d0756bc3f57.png)
![2018-10-18 4 14 36](https://user-images.githubusercontent.com/28773903/47137302-2be24300-d2f1-11e8-9cb3-f4ceec136311.png)
![2018-10-18 4 14 44](https://user-images.githubusercontent.com/28773903/47137305-2edd3380-d2f1-11e8-8ae0-347aac2dcddb.png)
@AnnieHwang 결과가 나왔을 때 테이블 영역을 더 확보하기 위해서 기능 버튼을 플로팅하였는데... 어떠신가요? 좀 고민되네요.

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/47141462-b3cd4a80-d2fb-11e8-8e2d-910d5bdd08c9.png)

@AnnieHwang @ufoscw 디자인 공유드립니다

**Comment by ufoscw** [comment]
@eltriny API 수정사항입니다.
1. websocket 메시지 추가
기존 : CONNECT, DISCONNECT, LOG, DONE
변경 : CONNECT, DISCONNECT, LOG, GET_CONNECTION, CREATE_STATEMENT, EXECUTE_QUERY, GET_RESULTSET, DONE

GET_CONNECTION > CREATE_STATEMENT > EXECUTE_QUERY > GET_RESULTSET > DONE 순서대로 내려갈겁니다.

2. query 실행 결과 속성 추가
csvFilePath 속성이 추가되었습니다. 결과 페이징 및 csv 다운로드, 차트 미리보기 등에서 사용될 속성입니다.

3. query 결과 페이징 API 추가
 - API
    (POST) /queryeditors/{id}/query/result
 - request parameter
    csvFilePath   (STRING)
    fieldList         (LIST<FIELD>)
    pageSize       (INTEGER) : OPTIONAL
    pageNumber (INTEGER) : 시작은 0

4. query 다운로드 API 변경 (항상 전체 다운로드)
 - API 
    (POST) /queryeditors/{id}/query/download/csv
 - request parameter
    csvFilePath    (STRING) : query result의 csvFilePath 속성
    fileName         (STRING) : 저장할 파일명

**Comment by eltriny** [comment]
@ufoscw 
websocket 메시지 관련 확인 부탁드립니다.
MySQL 대상으로 테스트 해본 결과 
GET_CONNECTION > CREATE_STATEMENT > EXECUTE_QUERY > GET_RESULTSET 까지는 내려오는데
DONE 이 내려오지 않고 있습니다.
확인부탁드립니다.

**Comment by ufoscw** [comment]
@eltriny DONE 메시지 추가되었습니다.

**Comment by ufoscw** [comment]
@eltriny 
chart 미리보기 파라미터 변경사항입니다.
기존 JDBC 타입이 아닌 LocalFile 타입으로 변경이 필요합니다.
DataConnection Detail 정보 조회하는 부분도 불필요할것 같아요.

### 1. DataSource param
* AS-IS
```
param = {
      dsType: 'MASTER',
      connType: 'LINK',
      srcType: 'JDBC',
      granularity: 'DAY',
      segGranularity: 'MONTH',
      engineName: this.pageEngineName,
      name: this.pageEngineName,
      description: ''
    };
```
* TO-BE
```
param = {
      dsType: 'VOLATILITY',
      connType: 'ENGINE',
      srcType: 'FILE',
      granularity: 'DAY',
      segGranularity: 'MONTH',
      engineName: this.pageEngineName,
      name: this.pageEngineName,
      description: ''
    };
```

### 2. Field Param
* AS-IS
current_datetime 포함
* TO-BE
current_datetime 삭제

### 3. ingestion param
* AS-IS
```
param['ingestion'] = {
      type: 'link',
      connection: {
        implementor: connInfo.implementor,
        type: connInfo.type,
        hostname: connInfo.hostname,
        port: connInfo.port,
        url: connInfo.url,
        database: connInfo.database,
        authenticationType: this.authenticationType,
        catalog: connInfo.catalog,
        sid: connInfo.sid,
        connectUrl: this._isUrlType() ? connInfo.url : ('jdbc:' + connInfo.implementor.toString().toLowerCase() + '://' + connInfo.hostname + ':' + connInfo.port + '/' + connInfo.database),
      },
      database: connInfo.database,
      dataType: 'QUERY',
      query: currentResultTab.result.runQuery
    }
....
....
....
```
* TO-BE
```
param['ingestion'] = {
      type: 'local',
      format: {
        type: 'csv',
        delimiter: ',',
        lineSeparator: '\n',
      },
      removeFirstRow: true,
      path: currentResultTab.result['csvFilePath'],
      rollup:true
    };
```

### 4. Request Sample
```
{
   "dsType":"VOLATILITY",
   "connType":"ENGINE",
   "srcType":"FILE",
   "granularity":"DAY",
   "segGranularity":"MONTH",
   "engineName":"bulk_ingestion_1540362809721",
   "name":"bulk_ingestion_1540362809721",
   "description":"",
   "fields":[
      {
         "name":"type",
         "alias":"type",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":0
      },
      {
         "name":"id",
         "alias":"id",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":1
      },
      {
         "name":"created_by",
         "alias":"created_by",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":2
      },
      {
         "name":"created_time",
         "alias":"created_time",
         "type":"TIMESTAMP",
         "logicalType":"TIMESTAMP",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":3
      },
      {
         "name":"modified_by",
         "alias":"modified_by",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":4
      },
      {
         "name":"modified_time",
         "alias":"modified_time",
         "type":"TIMESTAMP",
         "logicalType":"TIMESTAMP",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":5
      },
      {
         "name":"version",
         "alias":"version",
         "type":"LONG",
         "logicalType":"INTEGER",
         "role":"MEASURE",
         "aggrType":"NONE",
         "biType":"MEASURE",
         "seq":6
      },
      {
         "name":"book_desc",
         "alias":"book_desc",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":7
      },
      {
         "name":"book_favorite",
         "alias":"book_favorite",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":8
      },
      {
         "name":"book_folder_id",
         "alias":"book_folder_id",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":9
      },
      {
         "name":"book_name",
         "alias":"book_name",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":10
      },
      {
         "name":"book_tag",
         "alias":"book_tag",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":11
      },
      {
         "name":"ws_id",
         "alias":"ws_id",
         "type":"STRING",
         "logicalType":"STRING",
         "role":"DIMENSION",
         "aggrType":"NONE",
         "biType":"DIMENSION",
         "seq":12
      }
   ],
   "ingestion":{
      "type":"local",
      "format":{
         "type":"csv",
         "delimiter":",",
         "lineSeparator":"\n"
      },
      "removeFirstRow":true,
      "path":"20181024063326_7bd8d67b_0.csv",
      "rollup":true
   }
}
```

**Comment by ufoscw** [comment]
@eltriny engineName도 bulk_ 로 시작하지 말고 temporary_로 시작하는게 좋을것 같습니다.

**Comment by ufoscw** [comment]
@eltriny 
테스트 결과입니다.
1. 검색 영역 레이어 좌표 오류
![image 1](https://user-images.githubusercontent.com/3770446/47485839-f5b93c00-d879-11e8-9f51-5907ec47515c.png)

2. 쿼리 수행 결과의 numRows값이 10만건일 경우 10만건+ 로 표시해야 합니다.

3. output 탭에 GET_CONNECTION 메시지가 2번 찍힙니다. Command 가 아니라 Getting Connection 등의 문장으로 변경해주세요.

4. 비정상 쿼리 수행 후 재실행하면 쿼리가 실행중이라고 나옵니다.

5. 결과 탭 마우스 호버시 레이어 좌표 수정 및 호버메시지 딜레이 추가
![pasted_image_at_2018-10-25__3_08_pm](https://user-images.githubusercontent.com/3770446/47486568-9ceaa300-d87b-11e8-95aa-46bf7cd9d9f3.png)


6. 결과탭의 Next 버튼을 빠르게 클릭하면 최대페이지를 넘어갑니다.
로딩바를 통해 Next 결과 받을때까지 막아야 할것 같아요.
<img width="420" alt="metatron_discovery 1" src="https://user-images.githubusercontent.com/3770446/47486621-b8ee4480-d87b-11e8-9425-71d2a7e4576c.png">

7. 쿼리 실행중 에디터 최대화 버튼을 누르면 output 영역이 위로 올라옴
<img width="1564" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47486575-a247ed80-d87b-11e8-86cb-1b6c14076e16.png">

8. 다중 쿼리 수행중 취소하면 이후 쿼리들은 실행되지 않아야 하는데 남아 있는 모든 쿼리가 실행됩니다.

9. 워크벤치 스키마정보 창에서 테이블 미리보기시 데이터 조회가 안됩니다
 - 스키마 브라우저에서 데이터 조회할때는 
``` /api/queryeditors/{id}/query/run ```
API가 아니라 
``` /api/connections/query/data ```
를 사용해야 합니다.

@minjung-cho 
1. 결과창 우하단 영문 텍스트 수정 (데이터 모니터링 화면과 용어를 맞추는게 좋을것 같습니다.)
Start Execution -> Started Time
Running Time -> Elapsed Time

**Comment by minjung-cho** [comment]
@eltriny 위 내용줌
5번에 추가 의견 드립니다. 결과 탭 호버시 1.5초 딜레이 후 쿼리 팝업이 뜨며, X 버튼 쪽에는 팝업 이벤트를 빼주십시요-
아래건은 메시지 담당자 분께 전달하겠습니다-
Start Execution -> Started Time
Running Time -> Elapsed Time

**Comment by koeun222** [comment]
@eltriny 

탭과 컨텐츠간의 경계가 약하다는 의견이있어 구분선 1px (#e7e7ea) 추가 했습니다. 
참고 부탁드립니다

![image](https://user-images.githubusercontent.com/42256760/47553807-ef42c700-d942-11e8-91d1-9b6851865960.png)
