### ISSUE TITLE
Query editor bug fixes

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#472]
**Problem**
1. 
![image 28](https://user-images.githubusercontent.com/28773903/47078835-1e6c8080-d23f-11e8-8048-2dc0f2cd7911.png)
도움말 팝업이 쿼리문과 겹치고, 에디터창 아래로 떠서 시선이 분산됨
2. 
<img width="710" alt="workbench-label-error" src="https://user-images.githubusercontent.com/28773903/47078940-55db2d00-d23f-11e8-8cc8-5decef724128.png">
3.
![image 27](https://user-images.githubusercontent.com/28773903/47079005-72776500-d23f-11e8-873d-892743f6de0b.png)

**Solution**
1. 도움말 팝업을 ? 버튼 위에 뜨도록 위치 이동. 레이어 뎁스는 쿼리 에디터안에 속하며, 쿼리 문 보다는 위로 올라와야 함
2. 레이블 오류 수정
![shortcuts](https://user-images.githubusercontent.com/28773903/47428911-a7e7f980-d7cf-11e8-8f99-21fbcd5dce50.PNG)
3.

**Comment by ufoscw** [comment]
MacOS 용 자동완성은 Ctrl+Shift+Spacebar 가 맞는것 같습니다.

**Comment by ufoscw** [comment]
@AnnieHwang 
요청 사항중 현재 접속중인 커넥션의 DB Type 구분이 좀 더 쉽게 해달라는 요청사항이 있습니다.
검토 부탁드려요.

**Comment by ufoscw** [comment]
<img width="596" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47338543-48a4bf00-d6d3-11e8-9bb8-5a66357e7826.png">

**Comment by minjung-cho** [comment]
@ufoscw 코멘트 남겨주신 내용까지 포함해서 에디터 부분 개선안 작성중에 있습니다. 곧 공유하겠습니다. 다른 이슈도 있으시면 알려주셔요

**Comment by minjung-cho** [comment]
> MacOS 용 자동완성은 Ctrl+Shift+Spacebar 가 맞는것 같습니다.

@ufoscw 2. 번 스크린샷에 오류가 없는지 검토부탁드립니다-

**Comment by eltriny** [comment]
@ufoscw 
초기 개발 당시 맥 버전에서는 자동완성 등의 커맨드가 한/영키 변환등과 충돌되는 경우가 발생했습니다.
현재 최선 버전이 나왔으니 본 이슈 처리하면서 다시 단축키에 대해서 확인하고 정리해서 적용해두도록 하겠습니다.

**Comment by minjung-cho** [comment]
@ufoscw 네 우선 알려주신 대로 적용해 두겠습니다 @eltriny 변경 있을시 알려주십시요-

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/47633638-f57ab280-db91-11e8-9d0b-8a96fecd6ea9.png)
@AnnieHwang 디자인화면 공유드립니다
- 단축키 팝업 위치 수정 
- 단축키 windows / mac os 구분

**Comment by AnnieHwang** [comment]
@minjung-cho 저거 윗 에디터 하이트가 줄어들면 위를 기준으로 스크롤 생기는 거 맞죠?
