### ISSUE TITLE
datasource create error staging db

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#474]
**Describe the bug**
staging db 로 데이터소스 생성이 되지 않습니다.

**To Reproduce**
1. 데이터소스 화면으로 이동합니다.
2. 데이터소스 생성 버튼을 누르고, staging db를 선택합니다.
3. 테이블을 지정하고, 데이터소스 이름을 입력 한 후 생성 버튼을 누르면 생성 오류가 발생합니다.

**Expected behavior**
정상적으로 생성되어야 합니다.

**Screenshots**
생성 시의 에러 로그입니다.
![2018-10-17 10 30 06](https://user-images.githubusercontent.com/3685833/47089688-533b0080-d25c-11e8-92f1-adde72da14c9.png)
[druid_log.log](https://github.com/metatron-app/metatron-discovery/files/2487604/druid_log.log)

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
druid single mode 에서는 수행이 되지 않습니다. 이슈를 종료합니다.
