### ISSUE TITLE
Fetch the same result over and over

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#476]
**Describe the bug**
If you scroll down in the main grid of Dataprep, the same goes down.

_Dataprep main grid에서 아래로 scroll을 했을 경우 계속 내려가도 같은 내용이 나옵니다._

**To Reproduce**
1. Import & wrangle a dataset
2. Edit rules
3. Scroll down

**Expected behavior**
The next contexts should come out.

_제대로 다음 내용이 나와야합니다._

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68.0.3440.106

**Additional context**
As a result of looking through the browser debugger, it appears that the start offset of the fetch is incorrectly specified.
It looks like the page number, please change it to row number.

_Browser debugger를 통해서 본 결과, fetch의 시작 offset이 잘못 지정되는 것으로 보입니다.
Page number인 것으로 보이는데 row number로 변경 바랍니다._

**Comment by imsaaks** [comment]
if(gridResponse.rows.size()<toIndex) {
       toIndex = subGrid.rows.size();
     }

를 아래와 같이 수정했습니다.

if(gridResponse.rows.size()<toIndex) {
       toIndex = gridResponse.rows.size();
     }

**Comment by sang-hee-lee** [comment]
PR merged. Issue closed.
