### ISSUE TITLE
Rule editing is not applied in data preparation

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#477]
**Describe the bug**
룰 편집 시 편집된 내용이 적용되지 않는 경우가 발생합니다.
Sometimes rule editing is not applied on grid.

**To Reproduce**
1. Go to Data Flow and select any Data Set.
2. Create Replace Rule.
3. Edit Replace Rule.(Grid will not be changed)
4. Click "done" and go back to data flow, and then come back to data grid.(Grid will not be changed)
5. Delete replace rule.(Grid will not be changed)
6. Delete the rule before replace. Then grid will be  changed.

**Expected behavior**
룰을 편집 했을 때 그리드에 내용이 반영 되어야 함.
Rule editing should be applied on gird immediately. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 69

**Additional context**

**Comment by joohokim1** [comment]
For the replace rule now, when transforming, the new dataframe must have completely separate rows from the existing dataframe, but it points to the existing row.
When creating a new dataframe, we need to make a deep copy of row.
In addition, we need to check whether other rules have similar problems.

_지금 replace rule의 경우, transform시 새 dataframe이 기존 dataframe과 완전 별개의 row들을 갖고 있어야 하는데, 기존 row를 그대로 가리키고 있습니다.
새 dataframe을 만들 때, row를 deep copy하도록 해야겠습니다.
아울러, 다른 rule들도 비슷한 문제를 가지고 있는지 체크할 필요가 있습니다._

**Comment by joohokim1** [comment]
Is there any modified rule besides replace rule?

_혹시 replace rule 외에 또 수정된 rule이 있나요?_

**Comment by joohokim1** [comment]
All PRs merged. Issue closed.
