### ISSUE TITLE
Wrong directory for previews

### ISSUE THREAD

**Issue by ksparknot** [metatron-app/metatron-discovery#479]
**Describe the bug**
preview directory is not valid.
it is defined as '/preivews'
but there is '/dataprep' in code

**To Reproduce**
1. create new dataset
2. see the details of dataset
3. you can get the message 'invalid filekey'

**Desktop (please complete the following information):**
OS: MacOS
Browser: Chrome
Version: 68.0.3440.106

**Comment by joohokim1** [comment]
Aborted. This will be done by another issue in a better way.
