### ISSUE TITLE
Incorrect number of workbooks cause by folder deletion error 

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#48]
**Describe the bug**
개인 워크스페이스에서 실제 워크북의 개수와 좌측 상단에 표시되는 워크북의 개수가 다름

**To Reproduce**
1. 데모 사이트에서 admin 으로 로그인
2. 개인 워크스페이스에 상단 워크스페이스 개수는 4로 나오나 아래 목록에는 3개의 워크북만 존재함

**Expected behavior**
상단 워크북 개수와 실제 워크북 개수가 일치해야 함

**Screenshots**
<img width="1200" alt="incorrect_workbook" src="https://user-images.githubusercontent.com/526622/44322146-ea672000-a486-11e8-9877-eb0f4c92a54a.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by eltriny** [comment]
#186 이슈와 같이 처리하여 PR을 올렸습니다.
