### ISSUE TITLE
Data preview error(sheet name)in Dataflow detail

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#482]
**Describe the bug**
Data preview error(sheet name)in Dataflow detail

**To Reproduce**
1. Menu > MANAGEMENT> dataflow
2. excel data click
3. data set clic
4. sheet name error

**Expected behavior**
Show sheet value

**Screenshots**
![2018-10-18 1 12 58](https://user-images.githubusercontent.com/42233710/47132115-44e0f900-d2dd-11e8-9571-9801d70a2c78.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
All PRs merged. Issue closed.
