### ISSUE TITLE
Get wrong grid when I scroll down in data preparation

### ISSUE THREAD

**Issue by joohokim1** [metatron-app/metatron-discovery#486]
**Describe the bug**
Data preparation에서 scroll down할 때에, 갑자기 이전 rule의 결과를 가져옵니다.

**To Reproduce**
1. Import & wrangle [Annual Revenue Data 2013-2016.xlsx](https://github.com/metatron-app/metatron-discovery/files/2490333/Annual.Revenue.Data.2013-2016.xlsx)
2. Click "Edit rules"
3. drop all columns after 'City'
4. delete row: City == 'New York'
5. Scroll down
6. **You can find 'New York'**

**Screenshots**
![2018-10-18 2 42 40](https://user-images.githubusercontent.com/42257727/47133573-3e09b480-d2e4-11e8-8361-f99fd3d7ec2b.png)
(ruleIdx를 안주든지, 5를 줘야 했음)

![2018-10-18 2 44 29](https://user-images.githubusercontent.com/42257727/47133591-57126580-d2e4-11e8-928f-421936710bc6.png)
(이것은 반대의 경우, stageIdx 5는 이 당시 없었음)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68.0.3440.106

**Comment by imsaaks** [comment]
#476 issue branch 에서 같이 작업중입니다.

**Comment by sang-hee-lee** [comment]
PR merged. Issue closed.
