### ISSUE TITLE
Overlapping in case many data at Dataflow detail display

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#489]
**Describe the bug**
Overlapping in case many data at Dataflow detail display

**To Reproduce**
1. menu>MANAGEMET>Data Preparation>Dataflow > Dataflow detail
2. add New dataset 
3. Overlapping 

**Expected behavior**
Activate scroll in case many data

**Screenshots**
![dataflow_overlappng](https://user-images.githubusercontent.com/42233710/47193139-4b7a7980-d38c-11e8-8e8c-b275b41410f6.GIF)

**Desktop (please complete the following information):**

**Additional context**

**Comment by ecoloy** [comment]
@sang-hee-lee 
데이터셋 간 정렬이나 조인 관계에 대한 연결선 디자인 같은 문제가 더 있지만 먼저 스크롤 문제를 마무리하고 다른 이슈에서 이 토픽들에 대해서 논의했으면 합니다.
일단 데이터셋 간의 수직 간격을 고정한 상태(최초 2개의 데이터셋 추가시 벌어지는 간격과 동일)에서 요소가 화면을 벗어날 경우 스크롤을 생성해주세요.
There are problems such as alignment between datasets or designing a connection line to a join relationship, but first I'll wrap up scrolling problems and discuss these topics on other issues.
Please proceed as scrolling occurs when there are many elements of the screen while the vertical spacing between datasets is fixed(same as when the first two data sets are added).

**Comment by ecoloy** [comment]
@sang-hee-lee 
데이터셋 간 정렬이나 조인 관계에 대한 연결선 디자인 같은 문제가 더 있지만 먼저 스크롤 문제를 마무리하고 다른 이슈에서 이 토픽들에 대해서 논의했으면 합니다.
일단 데이터셋 간의 수직 간격을 고정한 상태(최초 2개의 데이터셋 추가시 벌어지는 간격과 동일)에서 요소가 화면을 벗어날 경우 스크롤을 생성해주세요.
There are problems such as alignment between datasets or designing a connection line to a join relationship, but first I'll wrap up scrolling problems and discuss these topics on other issues.
Please proceed as scrolling occurs when there are many elements of the screen while the vertical spacing between datasets is fixed(same as when the first two data sets are added).

**Comment by joohokim1** [comment]
This is has been moved to 3.0.6

_3.0.6으로 이동합니다._

**Comment by joohokim1** [comment]
Test done in the integrated test.
