### ISSUE TITLE
Secondary indicators receive empty result

### ISSUE THREAD

**Issue by babokim** [metatron-app/metatron-discovery#495]
**Describe the bug**
KPI Chart에서 Secondary indicators 지정 시 지난월, 어제 등으로 지정할 경우 결과가 항상 0으로 나타남

**To Reproduce**
1. KPI Chart 생성  
2. Secondary indicators 클릭
3. Period에서 Daily 등 선택
4. 0 이 나타나는지 확인

**Expected behavior**
정해진 데이터가 나타나야 함

**Screenshots**
<img width="794" alt="screen shot 2018-10-19 at 2 28 35 pm" src="https://user-images.githubusercontent.com/321821/47201245-c30bd100-d3ab-11e8-92bd-e881f700f322.png">

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: chrome
 - Version: 69.0.3497.100 

**Additional context**
없음

**Comment by i1befree** [comment]
@kyungtaak 이거 저도 테스트 해봤을 때 비슷하긴 한데, Daily 로 할 경우 오늘과 어제의 비교로 되 있습니다. 일단 간단하게 라도 마지막 날과 그 전날의 비교가 더 맞지 않을까 하는 생각입니다.

**Comment by 9bow** [comment]
@kyungtaak 3.0.6에서 이 이슈가 재현되고 있습니다.
Secondary indicator 변경 시, 위와는 다르게 `https://discovery.metatron.app/api/datasources/query/search/time_compare`가 `400 Bad Request`으로 반환되고 있습니다.
`sales_geo` datasource로 시험하였으며, 스크린 샷을 아래와 같이 첨부합니다.
<img width="1920" alt="screen shot 2018-11-12 at 13 32 08" src="https://user-images.githubusercontent.com/9343724/48327095-34276700-e680-11e8-89b3-0793ffd459d5.png">
<img width="1920" alt="screen shot 2018-11-12 at 13 32 01" src="https://user-images.githubusercontent.com/9343724/48327097-3689c100-e680-11e8-95ae-717637645188.png">
<img width="1920" alt="screen shot 2018-11-12 at 13 35 08" src="https://user-images.githubusercontent.com/9343724/48327099-3a1d4800-e680-11e8-9741-3023924742b4.png">
