### ISSUE TITLE
Screen display is incorrect in tooltip of Schema information

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#499]
**Describe the bug**
Screen display is incorrect in tooltip of Schema information(Inaccurate Location)

**To Reproduce**
1. Go to workbench
2. Click on schema information(right side of select box of database in left div screen)
3. Click on "i" circle of right side of "hive"

**Expected behavior**
The tooltip screen should be displayed normally

**Screenshots**
![2018-10-21 8 05 17](https://user-images.githubusercontent.com/10334774/47261374-bbae0a00-d508-11e8-8644-8dc145739e45.png)

**Desktop (please complete the following information):**
 - Tmap-Alpha dashboard version

**Additional context**

**Comment by kyungtaak** [comment]
@eltriny Please check this bug if possible.
