### ISSUE TITLE
workbench show query progress and log for hive connection

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#50]
**Is your feature request related to a problem? Please describe.**
need query progress and log.

**Describe the solution you'd like**

## requirement
add property to hive-site.xml
```
<!-- operation log -->
 <property>
  <name>hive.async.log.enabled</name>
  <value>false</value>
 </property>
```

## guide for client
1. subscribe via websockect (already developed)
> /user/queue/workbench/{workbenchId}

2. message received 4 type command
```
CONNECT : already developed
DISCONNECT : already developed
LOG : relay log and progress
DONE : message when query executed.
```

3. message structure (command : LOG)
```
{
  "command" : "LOG",   //command
  "queryIndex" : 0,    //order of query when execute queries.
  "log" : [            //string array of log from hive
     "Hive Log...",
     "Hive Log..."
   ],
   "progress" : {       //Progress Information
     "progress" : 60,   //completed progress % (0~100)
     "message" : "Map 1: 0/1	Map 4: 0(+1)/1	Reducer 2: 0/2	Reducer 3: 0/1"
   }
}
```

4. message structure (command : DONE)
```
{
    "command" : "DONE",    //command
    "queryIndex" : 0      //order of query when execute queries.
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ufoscw** [comment]
@eltriny 
3.0.2 브랜치를 리베이스 하면 아래처럼 빌드 오류 납니다.
[ERROR] ERROR in /Users/sohncw/Documents/GitHub/metatron-discovery/discovery-frontend/src/app/workbench/workbench.component.ts (36,18): Duplicate identifier 'ConnectionType'.

**Comment by eltriny** [comment]
@ufoscw 
빌드 오류 수정해서 올렸습니다.

**Comment by ufoscw** [comment]
@sting009 
현재 여러개의 쿼리 수행시 탭 작동이 이상합니다. 아래 애니메이션 관련 정의 부분 참고하시면 됩니다.
다만 pdf의 "5.로그가 끝까지 보이고 결과가 나오면, 결과창 화면으로 전환됨" 이 부분은 결과창 화면으로 전환되는 부분만 빼고 구현해주시면 됩니다.
그리고 PR에 코멘트 달아드렸던 캔슬버튼 클릭시 API 호출 안되는 오류도 수정바랍니다.
![workbench_animation](https://user-images.githubusercontent.com/3770446/45723190-16db9c80-bbeb-11e8-9711-9dab3a5403f7.png)
[워크벤치 로그 관련 애니메이션 정의.pdf](https://github.com/metatron-app/metatron-discovery/files/2394909/default.pdf)

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/45732763-c11de900-bc18-11e8-8a29-8c701b4bc969.png)
@ufoscw 쿼리 수행시 탭작동 관련 수정 및 결과창 보여지는 시점 수정하였습니다
@minjung-cho 참고 부탁드려요

**Comment by ufoscw** [comment]
1. select query 보내면 데이터가 있는데 그리드가 안나옵니다.
<img width="1762" alt="devtools_-_52_231_184_135_8186_app_v2_workbench_338e084e-9ccb-4651-94d9-0136c76bd80d_ _metatron_discovery_ _devtools_-_localhost_8180_app_v2_workspace_ws-02" src="https://user-images.githubusercontent.com/3770446/46709655-a2db6400-cc7f-11e8-958f-6af01d35bd2d.png">

2. 코멘트가 포함된 쿼리는 쿼리가 생략되어 수행됩니다.
<img width="1000" alt="devtools_-_52_231_184_135_8186_app_v2_workbench_338e084e-9ccb-4651-94d9-0136c76bd80d_ _metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46709728-edf57700-cc7f-11e8-847f-764834545f93.png">
코멘트가 포함된 쿼리일 경우 처리에 대한 로직이 서버사이드에 포함되어 있습니다.
세미콜론으로만 split 해서 보내주시면 됩니다.

해당 건 수정해서 다시 PR 오픈 해주세요.

**Comment by ufoscw** [comment]
@sting009 
1. hive group by query 수행 시 cancel api response 수신시 캔슬 완료로 처리해달라고 했는데 해당 요건은 전혀 반영이 안되어 있네요. pending 상태인데 캔슬 완료 처럼 작동합니다.

**Comment by sting009** [comment]
@ufoscw 
1. 그리드 이슈의 경우 현재 로컬 에서 확인시 재현이 어려워, 추정되는 부분 일부 수정하였으며 테스트 베드에서 추가 확인이 필요합니다. 
2. 주석이 포함된 쿼리 호출 시, 말씀하신대로 세미콜론 split 하는 방식으로 변경 하였습니다. 
3. cancel api response success 후 성공인 경우에만 캔슬 완료 처리하는 부분으로 변경하였습니다. 
유저 노티의 경우 따로 내용이 없어서 추가 하지 않았는데, 필요 시 추가하는 방향으로 진행하겠습니다.

**Comment by ufoscw** [comment]
@sting009 
2. 주석이 포함된 쿼리에 대한 예외처리가 코드에 들어 있던데 해당 코드는 필요한가요?
예를 들어 
-- test \n select 1 --test;
위의 쿼리는 한건의 쿼리문입니다.
서버에 파라미터로 보내시면 한건의 쿼리로 처리됩니다.

@metatron-app/design 
3. 사용자가 취소 버튼을 클릭시 취소 성공 여부를 response 받기 까지는 시간이 많이 걸리는 케이스도 존재하는데요.
사용자는 현재 쿼리가 취소중이며 취소 완료된 후에도 노티가 필요해 보입니다.
관련 내용 확인 부탁드려요.

**Comment by ufoscw** [comment]
@sting009 
다중 쿼리 수행시 탭 이동 동작에 대한 정의와 실제 구현된 내용이 차이가 있는것 같습니다.
위의 koeun님의 스크린샷과 비교중인데요..

쿼리1, 쿼리2, 쿼리3 의 다중 쿼리가 수행될 경우를 예로 들어
1. 최초 로그를 전달받기 전까지 로딩바 노출 (이 부분은 구현 누락됨)
2. 쿼리1의 로그 전달 받아 쿼리1 탭 생성 및 탭의 로딩 이미지 표현 및 로그 프린트
3. 쿼리1의 결과 전달받아 쿼리1 탭의 로딩이미지 제거 후 그리드 뷰로 전환 (이 이후부터는 js 스크립트를 이용한 뷰나 탭 전환은 없음)
4. 쿼리2의 로그 전달 받아 쿼리2 탭 생성 및 탭의 로딩 이미지 표현
5. 쿼리2의 결과 전달 받고 쿼리2 탭의 로딩이미지 제거
6. 쿼리3의 로그 전달 받아 쿼리3 탭 생성 및 탭의 로딩 이미지 표현
7. 쿼리3의 로그 전달 받아 쿼리3 탭의 로딩이미지 제거

**Comment by ufoscw** [comment]
@sting009 
다중 쿼리 수행시 탭 이동 동작에 대한 정의와 실제 구현된 내용이 차이가 있는것 같습니다.
위의 koeun님의 스크린샷과 비교중인데요..

쿼리1, 쿼리2, 쿼리3 의 다중 쿼리가 수행될 경우를 예로 들어
1. 쿼리1 request 후 쿼리1 탭 생성 및 탭의 로딩 이미지 표현
2. 쿼리1 로그 전달 받아 로그 tailing
3. 쿼리1의 결과 전달받아 쿼리1 탭의 로딩이미지 제거 후 그리드 뷰로 전환 (이 이후부터는 js 스크립트를 이용한 뷰나 탭 전환은 없음)
4. 쿼리2 request 후 쿼리2 탭 생성 및 탭의 로딩 이미지 표현
5. 쿼리2의 로그 전달 받고 사용자가 쿼리2 탭을 보고 있을 경우는 쿼리2 로그 tailing
7. 쿼리2의 결과 전달 받고 쿼리2 탭의 로딩이미지 제거
8. 쿼리3 request 후 쿼리3 탭 생성 및 탭의 로딩 이미지 표현
9. 쿼리3의 로그 전달 받고 사용자가 쿼리3 탭을 보고 있을 경우는 쿼리3 로그 tailing
10. 쿼리3의 로그 전달 받아 쿼리3 탭의 로딩이미지 제거

내용이 조금 복잡해보이지만 기본적으로 다중 쿼리 실행시 스크립트를 이용한 탭전환은 없습니다.
사용자가 자유롭게 탭을 전환하여 현재까지 전달 받은 결과나 로그를 조회가 가능하다는게 기획내용입니다.

**Comment by ufoscw** [comment]
@metatron-app/design 
2가지 내용 확인 부탁드립니다.
1. 실행중인 쿼리 탭 닫기 버튼
<img width="425" alt="1" src="https://user-images.githubusercontent.com/3770446/46731687-523b2980-ccc6-11e8-9209-91ab5d6337d2.png">

2. 쿼리 취소시 탭의 최종 모습
<img width="1265" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46731712-61ba7280-ccc6-11e8-82a4-092af3a03f73.png">
<img width="1283" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46731792-98908880-ccc6-11e8-9f91-9d0d837e5bcd.png">

**Comment by esezin** [comment]
@ufoscw 
1.  X 버튼은 해당 탭을 닫는 동작이기 때문에, 쿼리 수행 중이어도 탭이 닫히는 것이 맞습니다.
2. 쿼리 취소 이후의 동작은 논의가 좀 필요할 것 같습니다만, 로딩 중의 취소이기 때문에 탭이 닫히는 동작까지 연결되는 것 보다는 로그가 표시되던 상태에서 멈춰지고, 마지막 행에 '로딩이 취소 되었습니다' 정도의 문구가 표시되는 것이 제일 명확할 것 같습니다.

위 내용은 @sting009 과도 논의해보겠습니다.

**Comment by ufoscw** [comment]
@esezin 
1. 수행중인 탭의 경우는 닫기 버튼이 없어도 될것 같습니다. 취소기능과 약간 겹치는것 같기도 하구요.
2. 네. 해당 방안이 좋은것 같습니다. 

@sting009 
다중 쿼리 수행 시 탭이 닫힐 경우 인덱스가 꼬이는 부분이 없는지도 확인 부탁드립니다.

**Comment by esezin** [comment]
@ufoscw 
1. 네, 안그래도 @sting009 과 이야기 중에, 로딩 중인 탭을 닫아버리면 꼬일 가능성이 있다고 하여, 로딩 중에는 X버튼을 표시하지 않고, 로딩 완료되면 타이틀과 X버튼을 표시하는 쪽으로 논의하였습니다.
2. 말씀드린대로, 보여줄 수 있는 로그까지 보여주고, 마지막 행에 '로딩이 취소되었습니다' 문구를 표시하는 쪽이 좋을 것 같습니다.

**Comment by sting009** [comment]
@ufoscw 
현재 위의 내용 토대로 정의 및 수정 내용 pr reopen 하였습니다.

**Comment by ufoscw** [comment]
@sting009 
몇가지 오류사항입니다.
1. 
<img width="1293" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46735898-8c122d00-ccd2-11e8-8c66-97eecf91ad77.png">

2. 
<img width="1306" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46735812-4e150900-ccd2-11e8-9a3b-505be0e84186.png">

3. 
<img width="1286" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46736251-8701ad80-ccd3-11e8-9935-aefb7afafb32.png">

4.
<img width="1294" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46736449-1018e480-ccd4-11e8-82ca-f3fa7ec2e553.png">

5.
<img width="1289" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46736659-903f4a00-ccd4-11e8-9361-be182ca19e67.png">

**Comment by sting009** [comment]
@ufoscw 
위의 수정 사항 변경하였으며, 위의 오류중 2번 부분의 상단 여백 부분은, 내용 추가 확인 후 작업 진행하겠습니다.

**Comment by ufoscw** [comment]
@sting009 
1, 3, 4, 5 번 수정 확인했습니다.
2번은 여전히 재현됩니다.
다중 쿼리 수행중 2번째 쿼리 수행중 취소시 아래처럼 나옵니다.
<img width="1272" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/46772875-489cda80-cd35-11e8-8048-df5a0c2620c1.png">

**Comment by ufoscw** [comment]
@sting009 
위 리포트한 내용까지 작업하고 merge하도록 하겠습니다.

**Comment by sting009** [comment]
@ufoscw 
수정내용 커밋하였습니다. 빌드 부탁드립니다.

**Comment by ufoscw** [comment]
@sting009 통합테스트 결과입니다.
1. 쿼리 실행 시 fail 결과가 화면에 재대로 표시 되지 않습니다.
2. 쿼리 캔슬링 도중 로그 프린트시 로딩바가 사라지고 캔슬 버튼이 다시 나타남
3. 다중 쿼리 수행중 쿼리 캔슬할 경우 cancel api response가 비정상일 경우라고 다음 쿼리 실행은 중단되어야 함.
4. 쿼리 캔슬 후 Result View 버튼을 누르면 다시 로그 뷰로 돌아오지 못함. 
5. 쿼리를 캔슬 하더라도 run api와 cancel api respose가 둘다 성공으로 올 경우는 그리드 뷰를 표현해줄 수 있어야함.

1번 결함은 중대한 결함이라 최대한 빨리 수정되어야 합니다.

**Comment by sting009** [comment]
통합 테스트 결과중 1, 4번 우선 수정 하였으며 일부 확인 및 테스트 위해 pr 진행하였습니다.

**Comment by ufoscw** [comment]
@sting009 
PR 내용을 보고 다른 리뷰어들도 테스트를 해야 합니다.
PR의 description에는 수정한 내용을 적어주시고
test 방법을 잘 기술해주셔야 다른 리뷰어들이 테스트를 할 수 있습니다.

**Comment by sting009** [comment]
@ufoscw 
3,5번  추가 수정 하였으며, 2번의 경우 현재 상황 재현이 어려워 확인 후 진행하도록 하겠습니다.

**Comment by ufoscw** [comment]
@sting009 
1번 결함은 https://github.com/metatron-app/metatron-discovery/issues/432 이슈를 생성하였으니 432 이슈에서 작업하시면 됩니다.
