### ISSUE TITLE
Do users need to be able to edit their own emails?

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#500]
**Describe the bug**
"THIS IS NOT A BUT - JUST A QUESTION OF CONCEPT"
The user receives approval to join from admin on the basis of a valid email address when signing up.
However, I can edit your email address in My profile afterwards. This section will check for duplicate checks or valid forms, but it's likely that the email is not a valid email belonging to that user.

**To Reproduce**
1. Go to My Profile
2. Click on Email
3. Edit your email information
4. I can see modified email address

**Expected behavior**
Can not change email address after signing up, or need to verify your email address again

**Screenshots**
![2018-10-21 8 20 08](https://user-images.githubusercontent.com/10334774/47261429-388db380-d50a-11e8-838e-3cefc708c3df.png)

**Desktop (please complete the following information):**
 - Tmap Alpha dashboard version

**Additional context**

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang 위의 내용 검토 부탁드립니다.

**Comment by AnnieHwang** [comment]
@kyungtaak @minjung-cho  해당 이메일 인풋 하단에 Error message 출력하여 이메일 validation 처리를 해야 할 것 같습니다. 
ex) 이메일 형식에 맞지 않습니다.

**Comment by minjung-cho** [comment]
이메일과 비밀번호는 회원 가입시와 동일하게 valid 체크가 되어야 합니다. 문서에 명시해 두겠습니다

**Comment by kyungtaak** [comment]
@alchan-lee 해당이슈가 qa 에서도 나오지 않았나요? 확인 부탁드립니다. 수정되었다면 관련 링크 pr 을 명시해주시고요. 이슈를 종료해주세요.

**Comment by alchan-lee** [comment]
@Cazen 
이 건은 이메일 주소 양식에 대한 validation 보다는 
**실제 사용 가능한 메일**인지를 확인하고 싶다는 이야기 같은데요, 맞나요?

참고로 이메일 양식에 대한 validation은 편집화면에도 이미 걸려 있습니다.

**Comment by kyungtaak** [comment]
@Cazen 답이 된것같으니 이이슈는 종료하겠습니다.
