### ISSUE TITLE
Can normal users access the Admin Workbench via a unique id?

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#502]
**Describe the bug**
"THIS IS NOT A BUT. JUST A QUESTION OF FUNCTION"
If I create a workbench in the Admin workspace, the end user will not be able to see the list. However, normal user can access and modify the page by entering url directly via the generated workbench id (eg. App / v2 / workbench / a7b68ce0-d7ea-4202-9ceb-83e158861d53)

**To Reproduce**
1. Create workbench in admin workspace and exact workbench URL(app/v2/workbench/a7b68ce0-d7ea-4202-9ceb-83e158861d53)
2. Share the unique id to normal user
3. Normal user can access and modify workbench 

**Expected behavior**
I wonder if this behavior was intended (a design concept for sharing)

**Screenshots**
<img width="1664" alt="2018-10-21 8 46 54" src="https://user-images.githubusercontent.com/10334774/47261618-f4041700-d50d-11e8-8975-eb256ed8059d.png">
![2018-10-21 8 47 01](https://user-images.githubusercontent.com/10334774/47261619-f7979e00-d50d-11e8-90fa-c7a5c5060937.png)

**Desktop (please complete the following information):**
 - Tmap Dashboard Alpla version

**Additional context**

**Comment by kyungtaak** [comment]
This is a permission error in workspace. I think we need to check this out as a whole. Thank you for your bug report.

**Comment by alchan-lee** [comment]
Malformed..

This situation can not occur in normal, but it happend by your settings.
Your personal 'Admin workspace' set to **'default permission schema'.**

I dont know why and how did you set this permission scheme, but I assume it may acted for testing.

For maintance, I close this issue and if you have any other questions, you can reopen it at any time.

**Comment by alchan-lee** [comment]
Malformed..

This situation can not occur in normal, but it happend by your settings.
Your personal 'Admin workspace' set to **'default permission schema'.**

I dont know why and how did you set this permission scheme, but I assume it may acted for testing.

For maintance, I close this issue and if you have any other questions, you can reopen it at any time.

**Comment by alchan-lee** [comment]
I attach related.

![image](https://user-images.githubusercontent.com/42234141/47275774-33edfb80-d5ed-11e8-9cc2-c97d5d31af24.png)
