### ISSUE TITLE
Question about condition of data modification search on datasource list

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#503]
**Describe the bug**
"THIS IS NOT A BUG JUST A QUESTION"
Datasource search criteria have modification date criteria. The modification date was thought to be the date the data source was modified, such as the name or description, but most data sources are searched when the modification date is retrieved in the last 7 days. 

**To Reproduce**
1. Go to datasource
2. Click on modification time on search time criteria
3. See most data sources are searched

**Expected behavior**
I'm curious about the exact meaning of the modification date.

**Screenshots**
<img width="1642" alt="2018-10-21 8 55 40" src="https://user-images.githubusercontent.com/10334774/47261718-6544c980-d510-11e8-8da9-5641629c3a15.png">

**Desktop (please complete the following information):**
 - Tmap Alpha Dashboard version

**Additional context**

**Comment by kyungtaak** [comment]
@Cazen I think this is a problem too. We will check the modification date criteria and solve this problem.

**Comment by Cazen** [comment]
Thank you very much for the quick review :)

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang Please check this issue. Would not it be appropriate to exclude revision dates that are not listed?

**Comment by AnnieHwang** [comment]
@Cazen @kyungtaak 시간에 따른 데이터 필터 기능이 수정된것으로 알고 있습니다. 따라서 해당 이슈는 Close 처리 해도 될것 같습니다.

**Comment by kyungtaak** [comment]
해당이슈는 #684  에서 처리할 예정이므로 이슈는 close 하겠습니다.
