### ISSUE TITLE
Problems displaying datasource detail screen in workbook

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#504]
**Describe the bug**

**To Reproduce**
1. Go to create new dashboard in workbook
2. Add new datasource and press detailed information on right upper side of screed
3. See error

**Expected behavior**
The screen should display normally

**Screenshots**
![2018-10-21 9 22 54](https://user-images.githubusercontent.com/10334774/47261819-f87efe80-d512-11e8-8412-4e629bafe952.png)
<img width="1666" alt="2018-10-21 9 23 01" src="https://user-images.githubusercontent.com/10334774/47261822-fcab1c00-d512-11e8-8c5a-3cedb6021f56.png">

**Desktop (please complete the following information):**
 - Tmap Alpha Dashboard version

**Additional context**

**Comment by Cazen** [comment]
Additionally, the upper right X(close) button of the second screenshot looks that does not works

**Comment by eltriny** [comment]
@Cazen 
![2018-10-22 2 14 54](https://user-images.githubusercontent.com/3685833/47269999-5a397a00-d5a0-11e8-8077-5e939e2c9ab0.png)
위 스크린린샷처럼 저희쪽에서는 정상적으로 표시가 되는데.. 테스트 환경이 어떻게 되시나요?

**Comment by kyungtaak** [comment]
Safari 는 현재 공식적으로 제공하고 있는 브라우저가 아닙니다. 추후 공식지원이 되면 전체적으로 확인하도록 하겠습니다.
