### ISSUE TITLE
Improved handling status of datasource ingestion

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#508]
**Is your feature request related to a problem? Please describe.**
데이터소스를 생성하는 시점부터 생성완료된 시점까지 사용자는 처리되는 상태에 대해 단순한 형태로 지원합니다. 
사용자는 데이터 소스를 생성하고 엔진(Druid) 에 적재하는 과정에 대해 알고 싶어합니다.

**Describe the solution you'd like**
(TBD) 추가 기획 확정 후 기재

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by alchan-lee** [comment]
Duplicated issue created, cause of Github's incident.
I close it.
