### ISSUE TITLE
Data Monitoring Feature.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#511]
# Data Monitoring feature
Data Monitoring is designed to get insights into the usage of queries performed using Discovery's Workbench tool.
This is a menu that we temporarily shut down to reveal the source of Discovery.

The Data Monitioring menu provides the following functions in detail.

## Log Statistics
Daily query success / failure rate
Daily query frequency by user
Long-running queries Top 5
Successful Query Frequency Top 5
Failed Query Frequency Top 5
Scan data Top 5
Memory Resource Usage Top 5
CPU resource usage Top 5
Top 5 Resource Usage by Queue

### * Resource Usage Statistics
The resource usage statistics in Log Statistics are intended for Hive only and are collected only when additional Hook Library is deployed on the target Hive server.
This feature will provide a follow-up guide.

## Job Log
Provides a list of all the query history performed by the workbench.
The search and filtering functions are provided under the following conditions.
Status, Elpased time, Execute date, query
Search results can be downloaded as CSV.

<img width="1479" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47471909-832f6880-d847-11e8-8d2d-cb279e172a8f.png">
<img width="1465" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47471926-99d5bf80-d847-11e8-8e00-4fd00665b870.png">

**Comment by kyungtaak** [comment]
👍

**Comment by ufoscw** [comment]
@eltriny 로그 타입 변경 시 parameter 중 size 값이 undefined로 넘어옵니다.
<img width="943" alt="devtools_-_52_231_184_135_8187_app_v2_management_monitoring_statistics_ _metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47408969-3773b500-d79c-11e8-951b-b50b74ca6c50.png">
