### ISSUE TITLE
Restore Data Monitoring menu on lnb

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#512]
**Is your feature request related to a problem? Please describe.**
Restore Data Monitoring menu on lnb. (exclude data lineage)

**Describe the solution you'd like**
Restore Data Monitoring menu on lnb. (exclude data lineage)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by alchan-lee** [comment]
Duplicated issue created, cause of Github's incident.
I close it.
