### ISSUE TITLE
Too lagre column width problem in dataflow detail

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#513]
**Describe the bug**
Too lagre column width problem in dataflow detail

**To Reproduce**
1. menu>MANAGEMET>Data Preparation>Dataflow > Dataflow detail
2. select wrangled data > click edit rules
3. See column width

**Expected behavior**
display with proper column width

**Screenshots**
![default](https://user-images.githubusercontent.com/42233710/47275309-33ebfc80-d5e9-11e8-8f77-d5ded54de81f.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by sang-hee-lee** [comment]
duplication due to Server errors

**Comment by joohokim1** [comment]
https://github.com/metatron-app/metatron-discovery/issues/515
