### ISSUE TITLE
Support unix timestamp format in field of datasource

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#516]
**Is your feature request related to a problem? Please describe.**
데이터를 엔진에 적재하기 위해서는 Timestamp 필드로 지정할 컬럼이 필요한데, 이 컬럼중 Unix timestamp 인 경우가 존재하여, 해당 컬럼으로 Timestamp 필드로 지정할수 없습니다. 

**Describe the solution you'd like**
데이터 소스 생성중 필드 설정에 아래와 같이 Unix timestamp 라는 flag 를 입력하여 인식하도록 합니다.
![image](https://user-images.githubusercontent.com/822255/47275461-ad381f00-d5ea-11e8-9d95-91c1d1edaac0.png)

**Describe alternatives you've considered**
기존 timestamp format 과 별도 format 으로 처리해야하기 때문에 기존 도메인 모델에 대한 하위 호환이 필요합니다.

**Additional context**
(N/A)

**Comment by brandon-wonjune** [comment]
f#516-support_unix_format_datasource 브랜치 생성하였습니다.

@kyungtaak 진행하면서 문의사항있습니다.
1. unix code에 대한 설정은 필드의 어느 값으로 넣어줘야되나요?
2. format의 경우 기존 사용하던 format과 동일하게 사용하면 되나요?

**Comment by kyungtaak** [comment]
@brandon-wonjune Field 내 format 속성에 변화가 있습니다. FieldFormat 을 메타데이터의 format 형태와 동일하게 구성하도록  하였는데요. 적재시 사용하는 필드 타입 구성은 2가지 입니다. 

- 기존 format 속성은  time_format 속성에 전달이 되어 하위호환이 지켜질 예정이고요. 향후 Timestamp role 의 필드의 포맷은 아래의 형태대로 구성되도록 해주세요.
- 그리고 데이터 소스 컬럼 목록 표시할때 아래 format 형태로 전달이 되오니 참고해주세요.

```
{
  "name": "time",
  "type": "TIMESTAMP",
  "logicalType": "TIMESTAMP",
  "role": "TIMESTAMP",
  "seq": 0,
  "format": {
    "type": "time_format",
    "format": "yyyy-MM-dd"
  }
}
or
{
  "name": "time",
  "type": "TIMESTAMP",
  "logicalType": "TIMESTAMP",
  "role": "TIMESTAMP",
  "seq": 0,
  "format": {
    "type": "time_unix"
  }
}
```

**Comment by brandon-wonjune** [comment]
@kyungtaak 
네
그러면 기존에 TIMESTAMP 타입의 컬럼이 replace를 선택했을 경우 validation 체크하는 로직을 제거하고
숫자만 가능하도록 변경하도록 하겠습니다. 
placeholder는 현재시간의 millisecond를 넣도록 변경하겠습니다.

**Comment by kyungtaak** [comment]
> * placeholder는 현재시간의 millisecond를 넣도록 변경

나누기 1000을 해주셔야해요~ :)

**Comment by brandon-wonjune** [comment]
@metatron-app/design 
UI 변경하였습니다

![2018-10-24 2 00 39](https://user-images.githubusercontent.com/42233627/47407353-a8639e80-d795-11e8-986e-cb95516e3ec4.png)
![2018-10-24 2 00 43](https://user-images.githubusercontent.com/42233627/47407354-a8639e80-d795-11e8-9c19-86dc7ac5ae6c.png)
![2018-10-24 2 00 47](https://user-images.githubusercontent.com/42233627/47407355-a8fc3500-d795-11e8-8f29-ae8b4e6272ed.png)

**Comment by kyungtaak** [comment]
@brandon-wonjune api request 에는 current_time 이라는게 없는데요. 보다 상세한 request 를 전달해주실수 있나요?

**Comment by brandon-wonjune** [comment]
@kyungtaak 
죄송합니다. 위 댓글에 두 케이스모두 수정하였습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak @metatron-app/design 
그리고 이 이슈가 적용되면
아래와 같은 화면에서 format을 수정할때는 어떤 방식으로 변경을 해야되나요?
단지 표시만 올바르게 나오면 되나요?


메타데이터 상세 > 컬럼 스키마 
![2018-10-24 5 14 34](https://user-images.githubusercontent.com/42233627/47418522-39963d80-d7b5-11e8-921f-39501f4d3f45.png)

데이터소스 상세 > 컬럼 디테일 > configure schema
![2018-10-24 5 15 09](https://user-images.githubusercontent.com/42233627/47418523-3a2ed400-d7b5-11e8-87db-064706df7a1d.png)
![2018-10-24 5 19 22](https://user-images.githubusercontent.com/42233627/47418524-3a2ed400-d7b5-11e8-9a43-2295d8b796a5.png)

**Comment by brandon-wonjune** [comment]
@kyungtaak 
그러면 기존타입에서 TIMESTAMP로 변경이 일어났을경우에 format의 type을 설정하는 UI가 없는데 default로 time_format을 전달하면 되나요?

**Comment by kyungtaak** [comment]
@brandon-wonjune 네 맞습니다.

**Comment by brandon-wonjune** [comment]
문구 수정하였습니다.
![2018-10-25 4 37 53](https://user-images.githubusercontent.com/42233627/47483517-6e1cfe80-d874-11e8-81c4-fee2b2d2c0cb.png)

**Comment by kyungtaak** [comment]
@brandon-wonjune 추가 요구사항이 있습니다. time_unit 내 second / millis 가 존재하는데요. 
아래 스펙이 추가되었습니다. 확인 부탁드릴게요. (f#516-support_unit_time_millis)
{
  "type": "time_unix",
  "unit": "second" // or "millisecond", default value is "millisecond"
}

**Comment by brandon-wonjune** [comment]
@kyungtaak 기존 UNIX일때 replace에 대한 ph는 second일때는 1000을 나누지 않는것으로 하면될까요?

**Comment by kyungtaak** [comment]
@brandon-wonjune millis 가 나누지 않는거요.

**Comment by brandon-wonjune** [comment]
@kyungtaak 수정하였습니다.
![2018-10-29 5 17 22](https://user-images.githubusercontent.com/42233627/47637313-a6874a00-db9e-11e8-95b9-fc04bd144af0.png)
![2018-10-29 5 17 25](https://user-images.githubusercontent.com/42233627/47637314-a6874a00-db9e-11e8-80f9-2b2b6cec429c.png)
![2018-10-29 5 17 28](https://user-images.githubusercontent.com/42233627/47637315-a6874a00-db9e-11e8-87c0-075e51ac6348.png)

**Comment by brandon-wonjune** [comment]
@alchan-lee 다시 수정하였습니다.

**Comment by alchan-lee** [comment]
@brandon-wonjune 감사합니다 👍
