### ISSUE TITLE
Add command rule(Window)

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#523]
**Is your feature request related to a problem? Please describe.**
Add Window to rule command list
룰 커맨드 목록에 Window 추가

**Describe the solution you'd like**
Add Window to rule command list
Expression (Required), Group by (Optional), Sort (Required)
룰 커맨드 목록에 Window 추가
Expression (필수), Group by (선택), Sort (필수)

**Additional context**

**Comment by joohokim1** [comment]
All PRs merged. Issue closed.

**Comment by joohokim1** [comment]
window value: [row_number(), rolling_sum(col1, 2, 2)] group: col2 order: col3
window value: [avg(col1), lead(col1, 3)] group: order: col3
