### ISSUE TITLE
Data set Swapping fuction

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#525]
**Is your feature request related to a problem? Please describe.**
데이터 원천 swapping

**Describe the solution you'd like**
Data Flow에 이미 등록된 Dataset 을 클릭한 상세 패널에서 다른 Dataset으로 변경할수 있는 기능

**Additional context**

**Comment by joohokim1** [comment]
I will notify you after I first created the API for this issue.

_본 이슈 관련해서 API를 먼저 만든 후에 알려드리겠습니다._

**Comment by joohokim1** [comment]
The next is to renew all previews of the wrangled datasets affected by swapping.
@ksparknot will continue to do so.

_다음은 swapping의 영향을 받는 모든 wrangled dataset의 preview를 갱신하는 일입니다.
@ksparknot 님께서 이어서 진행하실 예정입니다._

**Comment by ksparknot** [comment]
the code for regenerating preview lines is added.
now it will be assigned to @sang-hee-lee

**Comment by joohokim1** [comment]
Test done in the integration test.
