### ISSUE TITLE
Canceling HDFS type snapshot is failed

### ISSUE THREAD

**Issue by ecoloy** [metatron-app/metatron-discovery#528]
**Describe the bug**

**To Reproduce**
1. Go to Data Preparation > Dataset
2. Create dataset using CSV file below
[police-department-calls-for-service.csv.zip](https://github.com/metatron-app/metatron-discovery/files/2504632/police-department-calls-for-service.csv.zip)
3. Create dataflow using the dataset above
4. Click Wrangled dataset in the dataflow detail page
5. Create snapshot with HDFS location setting
6. Click 'Go to snapshot list' button in progress popup
7. Click snapshot item which preparing on lists
8. Click 'cancel' button at right side on progress bar
9. Click 'Yes' button on confirm popup
10. See warning toast

**Expected behavior**
The snapshot should be successfully canceled

**Screenshots**
<img width="1676" alt="2018-10-23 2 21 49" src="https://user-images.githubusercontent.com/28751002/47338192-ed260180-d6d1-11e8-937d-e2b7d3f5e357.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 70.3

**Additional context**

**Comment by mh0203** [comment]
테스트 해본 결과 이미 cancel 가능한 시점을 지났기 때문에 취소가 불가능한 상황인 것 같습니다.
현재 "THIS_SNAPSHOT_IS_ALREADY_CREATED_OR_FAILED"로 리턴되는 메시지에 대해서 에러 토스트 대신 다른 피드백을 주는 것이좋을 것 같습니다.

It seems to that snapshot canceling is impossible because snapshot generating process is already passed cancel point.
It would be good to give different feedback to users when "THIS_SNAPSHOT_IS_ALREADY_CREATED_OR_FALED" msg is returned.

**Comment by joohokim1** [comment]
이 건은 생각할 일이 많네요. 기획단계부터 확실히 하고 작업을 재개하는 것이 좋겠습니다.

We need more consideration about this issue. It is better to start over from the UI/UX design stage.

**Comment by joohokim1** [comment]
본 이슈는 기획부터 다시 하고 3.0.7로 옮기겠습니다.

I am going to revise this issue in 3.0.7. Planning should come first

**Comment by joohokim1** [comment]
Finished redesigning.

If the user requests cancellation, we will delete all of the following, regardless of the snapshot creation status.

1. Directory with Output
2. Hive table (if any)
3. PrepSnapshot entity

As more explanation for each status,
* SUCCESS: Even if it is completely created, remove all three of the above without any question.
* FAILURE: Do best to remove all three of the above.
* RUNNING: First, set to CANCELED, then all three of above should be cleared in the whole processing engine. The snapshot shouldn't be shown on the snapshot list. The garbage problem is not considered at this time.

Let's proceed as above.

_기획을 마쳤습니다._

_사용자가 취소를 요청한 경우, snapshot 생성 상태에 관계없이 다음 내용을 모두 지우는 것으로 하겠습니다._

_1. Output이 쌓인 directory_
_2. Hive table (if any)_
_3. PrepSnapshot entity_

_각 status에 대해 부가적으로 설명을 하자면,_
* _SUCCESS: 완벽하게 다 만들어졌더라도, 묻지도 따지지도 않고, 위의 3가지를 모두 지움_
* _FAILURE: 최선을 다해 위의 3가지를 모두 지움_
* _RUNNING: 일단 CANCELED로 해놓고, 전수처리 프로세스에서 위의 3가지를 모두 지움. Snapshot list 등에서는 이 snapshot이 없는 것으로 취급. Garbage가 남는 케이스는 현재로서는 고려하지 않기로 함._

_위처럼 진행을 합시다._

**Comment by mh0203** [comment]
This issue was fixed by below PR.
https://github.com/metatron-app/metatron-discovery/pull/784
