### ISSUE TITLE
Improve left panel and schema information popup of workbench

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#534]
**Problem**
1. 레이어드 팝업을 띄워둘 필요가 없는 정보이기 때문에 클릭이 아닌 호버로 마우스 이벤트를 변경해야 함
2. 테이블 리스트에서 이름이 길 경우, 공간이 부족하여 확인이 어려운 경우가 많음
3. 테이블 리스트에 스키마 브라우저와 동일한 정보를 제공하고 있으나, 몇가지 기능이 누락되어 있음 
4. 대부분의 사용자가 사용하는 스크린 사이즈에서 테이블 리스트 하단 부분이 비어보임. 현재 테이블 리스트 수는 페이지당 15개임.
5. 테이블 리스트에서 페이징이 없어도 될 경우에도 이전, 다음 버튼으로 시선이 감. (감성이슈)
6. 타입을 텍스트로 풀어서 보여주고 있어서 컬럼 리스트의 가독성이 떨어지고 공간이 낭비되고 있음
7. 스키마 정보 팝업 출력시, 탭의 정보 표시 영역이 비어있음. 테이블 리스트를 선택해야 정보가 표시됨
8. 스키마 정보 팝업에서 탭 이동 시, 정보를 불러올때 'No data' 텍스트가 보임. 또한, 위치도 어중간함
9. Metadata 용어를 혼용하고 있음.
10. DB 타입을 확인할 수 없어서 불편함

**Solution**
![2018-10-24 12 13 14](https://user-images.githubusercontent.com/28773903/47403906-3e8fc880-d786-11e8-8d9b-ca415164309b.png)

.1. 마우스 이벤트를 호버로 변경
.2.1 Info 아이콘 삭제. (스키마 브라우저에서 확인 가능함)
.2.2 #464 1.2 테이블 리스트 우측, 컬럼명 리스트 우측에 영역 조정 UI 추가
.2.3 #464 1.3 테이블명과 컬럼명의 '중간' 부분 말줄임 적용
.3.1 테이블 수 추가
.3.2 테이블 새로고침 버튼 추가
.3.3 #368 정렬 기능 추가. 오름차순(default) / 내림차순
.4. 페이지당 목록수 20개로 변경
.5. 불러올 목록이 없는 경우, 이전 또는 다음 버튼 숨김 (공통 정책 변경)
.6. 컬럼 타입을 아이콘으로 변경하고, 호버 시 인포팁으로 ‘타입 명(코드)’ 표시
.7. 첫 리스트가 선택된 것을 초기 상태로 함
.8. Metadata 레이블을 Information으로 변경
.9.1 정보를 불러올 때, No data 텍스트를 표시하지 않음
.9.2 No data 인 경우, 텍스트 좌표 수정  
.10. #455 DB 타입 아이콘 추가

**Comment by minjung-cho** [comment]
(3.0.6 작업분)
.3.1 테이블 수 추가
.3.2 테이블 새로고침 버튼 추가
.3.3 #368 정렬 기능 추가. 오름차순(default) / 내림차순
.10. #455 DB 타입 아이콘 추가
.7. 첫 리스트가 선택된 것을 초기 상태로 함
.8. Metadata 레이블을 Information으로 변경
.9.1 정보를 불러올 때, No data 텍스트를 표시하지 않음
.9.2 No data 인 경우, 텍스트 좌표 수정

**Comment by ufoscw** [comment]
![image 3](https://user-images.githubusercontent.com/3770446/47631371-299da580-db89-11e8-9a9b-2837833d2e2d.png)
레이어 사이즈가 너무 작고 z-index 이슈가 있습니다.

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/47633719-54402c00-db92-11e8-9101-054871d9c943.png)
.3.1 테이블 수 추가
.3.2 테이블 새로고침 버튼 추가
.3.3 #368 정렬 기능 추가. 오름차순(default) / 내림차순
.10. #455 DB 타입 아이콘 추가

![image](https://user-images.githubusercontent.com/42256760/47634084-93bb4800-db93-11e8-864c-d6df6903d70e.png)
.8. Metadata 레이블을 Information으로 변경

![image](https://user-images.githubusercontent.com/42256760/47634188-ea288680-db93-11e8-887c-9f89ae15998c.png)
.9.1 정보를 불러올 때, No data 텍스트를 표시하지 않음
.9.2 No data 인 경우, 텍스트 좌표 수정

@AnnieHwang  디자인 공유드립니다

**Comment by minjung-cho** [comment]
**추가 변경**
[좌측 테이블 리스트]
1. 목록 페이지당 30개
2. 앞/뒤 리스트가 없을때는 이전/다음 버튼 숨김
3. 페이지 내에서 정렬. (추후 전체 목록 대상으로 변경)

**Comment by ufoscw** [comment]
@minjung-cho 
해당 이슈는 3.0.6 기준으로 모두 작업이 완료된거 맞죠?
혹시 아직 적용안된 내용이 있으면 새로운 이슈로 생성바랍니다.
