### ISSUE TITLE
Need to distinguish main data source and lookup data source 

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#54]
**Is your feature request related to a problem? Please describe.**
Association 단계는 main data source 에게만 허용되는 단계이므로 레이블을 바꾸는 것이 괜찮을 것 같음

**Describe the solution you'd like**
main data source 해당 하는 레이블을 개발하고(예: Tableau 에서는 Supersotre 라는 용어를 사용함)
"You need to establish relationships between data sources so that you can link charts" 이 문구에서 data sources 앞에 main 을 붙이거나 그에 준하는 레이블로 변경이 필요함

**Describe alternatives you've considered**

**Additional context**
<img width="1360" alt="label_change" src="https://user-images.githubusercontent.com/526622/44382569-66796a80-a550-11e8-8ed4-51b1f4fa92f9.png">

**Comment by kyungtaak** [comment]
@metatron-app/design  위 제안주신 내용에 대해 레이블 검토 부탁드립니다.

**Comment by AnnieHwang** [comment]
해당 가이드 레이블을 ""You need to establish relationships between master datasources so that you can link charts" 로 변경하기로 하였습니다. 뿐만아니라, 하단 Join 레이블 "Manage Scheme"로 변경하기로 하였습니다.

**Comment by kyungtaak** [comment]
@eltriny message 변경 부탁드립니다.
