### ISSUE TITLE
 Data type information error

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#549]
**Describe the bug**
데이터소스 상세 화면에서 
데이터소스의 소스 타입과 원천 데이터의 타입 정보가 'JDBC'로 표시되고 있습니다.
![2018-10-25 4 04 55](https://user-images.githubusercontent.com/28773903/47540002-03b89c80-d90e-11e8-9d41-04029f36dbc2.png)

**Expected behavior**
데이터소스 상세화면에서 데이터 타입 정보를 확인할 수 있어야 합니다.
Ingestion type : Ingested type / Linked type
Meta data>type : File / Database(DB종류) / Staging DB

**Comment by brandon-wonjune** [comment]
f#549-fix_datasource_info 브렌치 생성하였습니다

**Comment by brandon-wonjune** [comment]
- stagingDB
![2018-11-01 1 35 43](https://user-images.githubusercontent.com/42233627/47833663-66fb7080-dddf-11e8-8776-5687efece2b6.png)

- database
![2018-11-01 1 36 00](https://user-images.githubusercontent.com/42233627/47833664-66fb7080-dddf-11e8-9c53-83d18746cadb.png)

수정사항 적용하였습니다.
FILE의 경우는 생성에 문제가 생겨 적용만 해놓은 상태입니다.

**Comment by brandon-wonjune** [comment]
#631 에서 요청에 의해 stream 타입을 추가하였습니다
