### ISSUE TITLE
Apply default name rules when creating datasets

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#550]
**Is your feature request related to a problem? Please describe.**
Apply default name rules when creating dataset

**Describe the solution you'd like**
default name 
![defaultname](https://user-images.githubusercontent.com/42233710/47538924-c7cf0880-d908-11e8-8731-66de12918cd9.png)

**Additional context**

**Comment by joohokim1** [comment]
In the integration test, the sub-type of dataset and the contents of () are different in case.
It has been well implemented by the plan document.
@ecoloy When submitting to a future plan, it is better to match it exactly with the sub-type of the dataset.

_통합테스트를 하면서 보니까, dataset의 sub-type과 ()속에 들어가는 내용이 대소문자 표기가 다르네요.
기획대로는 잘 구현이 되었습니다.
@ecoloy 차후 기획서에 반영하실 때, dataset의 sub-type과 연계해서, 정확하게 잘 맞춰보는게 좋겠습니다._
