### ISSUE TITLE
Schema browser error in requesting sample data from Presto 

### ISSUE THREAD

**Issue by sting009** [metatron-app/metatron-discovery#562]
**Describe the bug**
Schema browser error in requesting sample data from Presto 

**To Reproduce**
1.  Go to workbench (presto connect)
2. Click on schema browser
3. Select table and select data tab

**Expected behavior**
The data should be displayed normally

**Screenshots**
![image](https://user-images.githubusercontent.com/42328567/47611745-fe468800-daae-11e8-9e98-4fe8364adc84.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68.0.3440.106

**Additional context**

**Comment by sting009** [comment]
@ufoscw 
가이드 해주신대로 connection 정보 빠진 부분들 추가하였습니다. 
- host port, url 연결 등 
![image](https://user-images.githubusercontent.com/42328567/47612484-9bf58380-dabe-11e8-8512-832002fba8e9.png)

로컬에서 확인 시 connection 정보를 추가하고 Type을 'QUERY' 로 연결 시에는 정상적으로 데이터가 호출되며, 
Type을 'TABLE'로 호출 할 경우, 쿼리문이 아래와 같이 로그가 찍히는데 확인 부탁드립니다. 

![image](https://user-images.githubusercontent.com/42328567/47612520-60a78480-dabf-11e8-9100-b90c664ecdc4.png)

**Comment by ufoscw** [comment]
@sting009 
type을 TABLE로 지정할 경우 query parameter는 테이블 명으로 보내시면 됩니다.
authenticationType이 DIALOG일 경우에 대한 connection 파라미터 구성하는 코드는 기존에 사용중이던 코드가 있으니 꼭 참고해서 수정해주세요.

**Comment by sting009** [comment]
@ufoscw 
기존 사용되었던 부분을 보니 connection 정보를 따로 수정하지 않고, 조회된 connection 정보를 그대로 파라미터로 사용하고 있어서 동일하게 수정하였고, query parameter를 테이블 명으로 보낼경우 
Data Connection 정보를 host, ip 방식으로 등록 시에는 정상적으로 호출되지만
Url 정보 입력 시 다음과 같은 에러가 나오는데 확인 부탁드립니다. 
- request payload 
![image](https://user-images.githubusercontent.com/42328567/47625457-a1a7a380-db68-11e8-9db7-09f6dd8feabd.png)

- console error log 
![image](https://user-images.githubusercontent.com/42328567/47625472-bdab4500-db68-11e8-9a89-6417a2562a79.png)

**Comment by ufoscw** [comment]
@sting009 DIALOG 방식일때는 connection의 user, password정보를  dialog를 통해서 입력한 값으로 파라미터로 보내주셔야 합니다.
그리고 파라미터 속성 중 schema는 없습니다.
database로 보내주세요.
필요없는 파라미터는 안보내셔도 됩니다.
아래는 url로 저장된 request sample입니다.
<img width="347" alt="devtools_-_discovery_metatron_app_app_v2_workbench_bfc6281d-1fad-4a11-ad92-4181e3d7e63a" src="https://user-images.githubusercontent.com/3770446/47625713-2cd56900-db6a-11e8-95b1-4719e1fc1757.png">

**Comment by ufoscw** [comment]
@sting009 
DIALOG 타입의 커넥션에서 참고하실 소스 라인입니다.
workbench.component.ts 2412 라인입니다.

**Comment by sting009** [comment]
@ufoscw 
수정하였습니다. PR진행하겠습니다.

**Comment by ufoscw** [comment]
@sting009 DIALOG 타입일 경우 connection에 사용자 정보가 안넘어옵니다.
<img width="945" alt="devtools_-_52_231_184_135_8186_app_v2_workbench_0c94a790-b20c-45d9-96b8-7f62e157ea13_ _metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47628607-ade82c80-db79-11e8-8e05-741c3b145095.png">

그리고 USERINFO 타입일 경우는 username 파라미터는 빼주세요.

**Comment by ufoscw** [comment]
@sting009 
커넥션 관련 변경사항은 항상 3가지 인증 타입 모두 테스트를 해봐야 합니다.
MANUAL, USERINFO, DIALOG

**Comment by sting009** [comment]
@ufoscw 
Dialog 일 경우 사용자정보 추가 
Userinfo 일 경우 예외 처리 추가 하였습니다.
