### ISSUE TITLE
Incorrect spell of Zeppelin in README file.

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#57]
**Describe the bug**
README 파일에 Apache Zeppline 으로 표기 된 것을 Apache Zepplin 으로 바꿔야 함

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by AnnieHwang** [comment]
f#57-change-readme 브랜치에 해당 내용 반영하겠습니다.

**Comment by kyungtaak** [comment]
fixed typo. I'll close issue.
