### ISSUE TITLE
Small area of the search button of the workbench does not work

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#577]
**Describe the bug**
This is probably not the bug but maybe hope that some usability can be improved

**To Reproduce**
1. Go to workbench
2. Click on search button's lower right area
3. Check that it does not works

**Expected behavior**
The function should work on all areas of the squared search icon

**Screenshots**
![2018-10-29 8 06 26](https://user-images.githubusercontent.com/10334774/47646385-215c5f00-dbb7-11e8-9406-79624882d5ae.png)

**Desktop (please complete the following information):**
 - T-map DEV 3.0.6-20181029094533

**Additional context**

**Comment by ufoscw** [comment]
@eltriny 
돋보기 아이콘 바깥쪽을 클릭하면 작동을 안하네요.
기능상 문제라 작업 우선순위를 높여야 할것 같습니다.
