### ISSUE TITLE
error when select sample data after change database in Schema browser.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#580]
**Describe the bug**
error when select sample data after change database in Schema browser.

**To Reproduce**
1. Go to workbench
2. Click Schema browser
3. change database
4. select table
5. click data tab
6. See error

**Expected behavior**

**Screenshots**
<img width="1362" alt="devtools_-_metatron-web-05_8180_app_v2_index_html_ _metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47651034-6ab3ab00-dbc5-11e8-935c-c50b1b0176cf.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by sting009** [comment]
@ufoscw 
f#580 번 브랜치 생성하였고 
스키마 브라우저 내에서 데이터베이스 변경 시, request parameter에서 database parameter 값만 기존값으로 유지되고 있어서 해당 내용 수정하였습니다.
