### ISSUE TITLE
CSV file has BOM can be deleted

### ISSUE THREAD

**Issue by ksparknot** [metatron-app/metatron-discovery#586]
**Describe the bug**
if csv file has BOM, copying the file can be failed because of there is a mistyping
so uploaded file can be deleted.

**To Reproduce**
1. create new dataset
2. upload csv with BOM
3. there will be an error message 'illegal exception'

**Expected behavior**
cannot upload CSV file with BOM

**Screenshots**

**Desktop (please complete the following information):**
 - OS: every
 - Browser [every]
 - Version [all]

**Additional context**

**Comment by joohokim1** [comment]
It would be grateful if you attach:
- A file that can not be uploaded before resolving this issue
- A files that can be uploaded regardless of this issue

_아래 파일을 각각 attach해 주시면 감사하겠습니다._
_1. 본 이슈를 해결하기 전에는 upload되지 않는 파일_
_2. 본 이슈와 관계없이 upload되는 파일_

**Comment by ksparknot** [comment]
[police-department-calls-for-service.csv.zip](https://github.com/metatron-app/metatron-discovery/files/2532294/police-department-calls-for-service.csv.zip)
BOM 헤더가 있는 CVS입니다

**Comment by ksparknot** [comment]
[sale_bom16.csv.zip](https://github.com/metatron-app/metatron-discovery/files/2564892/sale_bom16.csv.zip)
UTF-16 BOM이 있고 null 컬럼이 없는 csv 파일 입니다.
BOM 테스트 이슈에 동작합니다
