### ISSUE TITLE
 When a new subscription is made, the identity of the user in the denied request can be duplicated.

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#589]
**Problem.**
가입 승인이 반려된 사용자는, 최초 가입 신청 시 범했던 오류를 확인하고 수정 후, 다시 동일한 정보로 회원 가입 신청을 하고 싶어하나 중복 등록이 안됨. 이럴 경우, 사용자가 자주 사용하지 않은 정보로 가입을 하게 되어 서비스에 접속이 어려운 경우가 발생할 수 있음

**Solution**
![2018-10-30 4 24 50](https://user-images.githubusercontent.com/28773903/47703795-bbc6ac00-dc64-11e8-9baf-4e214855c49f.png)
신규 가입 시 Username과 email 중복 체크에서 반려건의 정보는 제외함

**Additional context**
사용자 식별자의 용어가 아래와 같이 변경되었습니다.
* (AS-IS) User name ㅣ 사용자 이름   /   (TO-BE) Full name ㅣ 이름
* (AS-IS) ID ㅣ아이디   /    (TO-BE) Username ㅣ 사용자 이름

변경사유
* Username이 ID보다 감성적으로 사용자 친화적임
* Identification 에는 사용자 고유코드, 이메일, 전번 등이 포함됨. 사용자 고유이름만을 지칭하기에는 일반적인 단어임
* DB관리 용이

**Comment by alchan-lee** [comment]
fixed at #773
