### ISSUE TITLE
 Improve usage flow and function associated with deleting members

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#592]
**Problem.**
1. 삭제된 회원의 식별 정보 표시에 대한 대응이 되어 있지 않음 (이름 영역에 아무것도 표시되지 않고, 사용자 상세화면 이동 링크가 살아있음)
![2018-10-30 5 11 24](https://user-images.githubusercontent.com/28773903/47704442-fdf0ed00-dc66-11e8-8e1b-465e50d0f05a.png)
2. 공유 워크스페이스의 오너인 경우에 대한 대응이 되어 있지 않음. 사용자 삭제와 동시에 공유 워크스페이스의 오너가 사라질 가능성이 있으며, 이때 시스템을 통해 오너를 새로 지정할 수 없는 문제가 생김

**Solution**
1.삭제된 사용자의 이름은 '알수없는 사용자'로 표시. Username 이외의 정보 및 링크 숨김
![2018-10-30 5 14 57](https://user-images.githubusercontent.com/28773903/47704571-6dff7300-dc67-11e8-90c1-ca5e3e217bac.png)
2.사용자 삭제 시, 공유 워크스페이스의 오너일 경우 오너 변경 후 삭제할 수 있도록 UI 제공
![2018-10-30 4 24 50 2](https://user-images.githubusercontent.com/28773903/47704095-d3eafb00-dc65-11e8-9a4b-6542238e9e09.png)
(추가화면)
![2018-10-30 5 25 58](https://user-images.githubusercontent.com/28773903/47705208-3265a880-dc69-11e8-9c7b-7277f2cc7351.png)

**Additional context**
#589

**Comment by minjung-cho** [comment]
추가 정의한 내용 전달드립니다.
- 유저 비활성화 시, 워크스페이스 오너 여부를 체크하지 않습니다. 즉, 오너가 비활성화 유저인 경우가 발생할 수 있습니다. 
- 유저 삭제 시, 비활성 워크스페이스의 오너 여부는 체크하지 않습니다. 즉, 비활성 워크스페이스에 삭제된 유저가 오너인 경우가 발생할수 있습니다.
--> 추후 어드민>워크스페이스 관리 화면에 오너 변경 기능이 추가되어야 할것 같습니다.

**Comment by ninezero90hy** [comment]
@kyungtaak 
- 매니저님, 워크스페이스를 다른 사람에게 위임하는 API(/api/workspaces/{id}/delegate/{ownername}) 사용중에 궁금한 부분이 있어서 문의 드립니다.
- ownername에 실제 존재하지 않는 사용자의 이름을 파라미터로 넘기는 경우에도 성공 코드(204 NO CONTENT)가 반환 됩니다.
존재 하지 않는 사용자라면 실패하는게 맞는 동작이라고 생각합니다
아래 테스트 케이스 추가했습니다
확인 부탁드립니다

- 존재하지 않는 사용자에게 작업 공간을 위임하는 경우에 대한 테스트 케이스 추가
(WorkspaceRestIntegrationTest#delegate_workspace_with_non_existent_user)
```java
  @SuppressWarnings({"SpellCheckingInspection", "RedundantThrows"})
  @Test
  @OAuthRequest(username = "polaris", value = {"SYSTEM_USER", "PERM_WORKSPACE_MANAGE_WORKSPACE"})
  @Sql("/sql/test_shared_workspace_list.sql")
  public void delegate_workspace_with_non_existent_user() throws JsonProcessingException {

    String workspaceId = "ws-0001";
    String ownerId = "EMPTY_USER_ID";

    // @formatter:off
    given()
            .auth().oauth2(oauth_token)
            .contentType(ContentType.JSON)
            .log().all()
            .when()
            .post("/api/workspaces/{id}/delegate/{ownername}", workspaceId, ownerId)
            .then()
            .statusCode(HttpStatus.SC_BAD_REQUEST)
            .log().all();
    // @formatter:on

    // @formatter:off
    given()
            .auth().oauth2(oauth_token)
            .contentType(ContentType.JSON)
            .log().all()
            .when()
            .get("/api/workspaces/{id}", workspaceId)
            .then()
            .statusCode(HttpStatus.SC_OK)
            .log().all();
    // @formatter:on
  }
```

**Comment by kyungtaak** [comment]
@ninezero90hy 네 맞네요. 해당건은 수정해두었어요. ^^ pr 영향도를 확인해주시고요. 문제가 없다면 pr 은 그냥 진행하도록 하겠습니다.

**Comment by ninezero90hy** [comment]
@kyungtaak 넵 감사합니다 :)

**Comment by ninezero90hy** [comment]
@kyungtaak 

 - 해당 워크스페이스 멤버 목록에 존재하지 않는 멤버를 오너로 등록하려고 하는 경우 실패 코드 (BAD_REQUEST)가 반환되도록 수정했습니다.

<img width="1680" alt="2019-02-12 1 01 25" src="https://user-images.githubusercontent.com/41019113/52575559-c0a11b80-2e61-11e9-8664-d05d737b00d9.png">

<img width="1680" alt="2019-02-12 12 59 37" src="https://user-images.githubusercontent.com/41019113/52575486-a1a28980-2e61-11e9-9486-2917c3f55c8a.png">

- 공유 워크스페이스 소유자 변경 팝업에서도 해당 워크스페이스의 추가되어 있는 멤버 목록을 보여주고 있어서
유효성 검사를 추가했습니다 확인 부탁드립니다 
잘못 수정한 거라면 알려주시거나 https://github.com/metatron-app/metatron-discovery/pull/1409/commits/cc950aa7043ef3c0676495d50978c015ae96ea76 해당 커밋을 취소하셔도 됩니다

- 테스트 케이스 추가
```java
  @Test
  @OAuthRequest(username = "polaris", value = {"SYSTEM_USER", "PERM_WORKSPACE_MANAGE_WORKSPACE"})
  @Sql("/sql/test_shared_workspace_list.sql")
  public void delegate_workspace_owner_to_users_not_exist_in_the_workspace_member_list() {

    String workspaceId = "ws-0001";
    String ownerId = "guest";

    // @formatter:off
    given()
            .auth().oauth2(oauth_token)
            .contentType(ContentType.JSON)
            .log().all()
            .when()
            .post("/api/workspaces/{id}/delegate/{ownername}", workspaceId, ownerId)
            .then()
            .log().all()
            .statusCode(HttpStatus.SC_BAD_REQUEST);
    // @formatter:on

  }
```
