### ISSUE TITLE
Error creating map view when changing properties

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#594]
**Describe the bug**
Map View 사용상에 발생하는 오류들을 수정합니다.

**To Reproduce**
1. 대시보드에서 맵 차트를 추가합니다.
2. 맵 차트에 대한 옵션들을 변경합니다.
3. 옵션 변경 및 맵 차트 생성 시에 오류가 발생합니다.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version 70

**Additional context**

**Comment by eltriny** [comment]
f#594-error_map_anlysis branch 생성되었습니다.

**Comment by juheeko9** [comment]
@kyungtaak 
기획상의 요건으로는 geo(point)만 올렸을때에도 hexagon타입의 map차트가 그려져야 하는데 
현재 리턴되는 데이터로는 geo(point)를 올리고 format을 geo_hash로 요청시에도 point인 데이터가 리턴되어 차트가 그려지지 않고있습니다.

geo(point)만 올렸을때에도 format을 geo_hash로 요청시 polygon 데이터형태로 리턴되게 수정부탁드립니다.

[Request Body]
`{"context":{"discovery.route.uri":"/workbook/83e193a1-2c81-4584-be1d-cd0ee9d55a6f","discovery.dashboard.id":"21197a8f-9ebc-4054-993a-bfaa93443557"},"userFields":[],"dataSource":{"joins":[],"temporary":false,"id":"ds-gis-37","name":"sales_geo","uiDescription":"Sales data (2011~2014)","type":"default","connType":"ENGINE","engineName":"sales_geo"},"filters":[{"field":"OrderDate","dataSource":"sales_geo","type":"time_all"}],"pivot":{"columns":[{"type":"dimension","name":"location","subType":"STRUCT","subRole":"DIMENSION","layerNum":1,"alias":"location"}],"rows":[],"aggregations":[]},"limits":{"limit":5000,"sort":null},"aliases":[{"type":"value","ref":"21197a8f-9ebc-4054-993a-bfaa93443557"}],"resultFormat":{"type":"chart","mode":"map","options":{"addMinMax":true,"showCategory":true,"showPercentage":true},"columnDelimeter":"―"},"shelf":{"type":"geo","layers":[[{"type":"dimension","name":"location","alias":"location","ref":null,"format":{"type":"geo_hash","method":"h3","precision":8},"dataSource":"sales_geo"}]]}}`

[Return]
`[{"type":"FeatureCollection","totalFeatures":9994,"features":[{"type":"Feature","id":"fid--68cda626_166c8f03317_1127","geometry":{"type":"Point","coordinates":[-119.7764,39.4972]},"geometry_name":"__geometry","properties":{}},{"type":"Feature","id":"fid--68cda626_166c8f03317_1128","geometry":{"type":"Point","coordinates":[-111.9261,33.4227]},"geometry_name":"__geometry","properties":{}}
...
}]`

[참고화면]
![image](https://user-images.githubusercontent.com/42233502/47772907-8e910100-dd2b-11e8-9e03-3f24b2077b65.png)

[참고기획화면]
![image](https://user-images.githubusercontent.com/42233502/47772347-c5661780-dd29-11e8-9c38-3d5e572cefe3.png)

**Comment by Jaehyun-Jang** [comment]
작업 진행 예정 일정 (~11.7)

- heatmap option component 색상 기준 수정 | 10.31
- 툴팁 굵기, 위치 수정 | 10.31
- 맵차트 범례 색상이 차트와 일치화 작업 | 10.31
- custom color setting의 min / max value range 및 UI 수정 | 10.31
- dimension 가이드에 dimension을 넣었을때 선반에 추가 | 10.31

- 선반의 dimension 제거시 색상타입이 초기화 안되도록 수정 | 11.2
- layer type - line일때 color by dimension으로 설정시 그려지는 색상과 저장됐을때   color by dimension으로 그려지는 색상 스타일이 다른 문제 수정 | 11.2
- 3번째 layer에 geo속성에 맞는 layer option panel 생기도록 수정 | 11.2
- 3번째 layer 옵션패널에서 2layer 옵션패널 선택시 스크립트 오류 수정| 11.2
- layer 3에 값을 올렸을때 layer2의 범례와 layer3의 범례가 합쳐지는 오류 수정 | 11.2
- 원본보기를 체크한 상태로, measure를 올렸을때 color by measure의 measure 리스트가 나타나지 않는 오류 수정 | 11.2

- Alias 변경시 차트 및 범례, 옵션패널에 반영되지 않는 오류 수정 | 11.7
- Dimension, Measure 선택후에 Map chart component 선택했을때 color by measure로 자동으로 바뀌지 않는 문제 수정 | 11.7
- 툴팁 옵션패널을 열기전에는 툴팁 설정이 되지않는 오류 수정 | 11.7
