### ISSUE TITLE
Improve workbench usability

### ISSUE THREAD

**Issue by sting009** [metatron-app/metatron-discovery#598]
**Is your feature request related to a problem? Please describe.**
워크벤치 사용선 개선 

**Describe the solution you'd like**
1. 데이터베이스 타입 별 아이콘 추가 
2. 워크벤치 브라우저 뒤로가기 막기 기능 추가 
3. 에디터 탭 추가 시, 에디터 이름 변경 개선 
4. 결과 탭의 paging 관련, 최대 건 수 및 page size 변경 개선

**Comment by sting009** [comment]
금주 우선작업 이슈 중에서, 이슈가 아직 없거나 일부 내용이 포함 된 이슈가 있어서 위의 내용 토대로 이슈 생성하였습니다. 
f#598 번 branch 생성하였습니다.

**Comment by eltriny** [comment]
다른 이슈들과 중첩되어 이슈를 종료합니다.
