### ISSUE TITLE
Update README page

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#6]
**Is your feature request related to a problem? Please describe.**
Github 리포지토리 최초 페이지에 대한 업데이트가 필요합니다.  

**Describe the solution you'd like**
최초 페이지 구성에 대해 정의후 README.md 파일을 구성해주세요.

**Describe alternatives you've considered**

**Additional context**

**Comment by AnnieHwang** [comment]
@kyungtaak @ucrystal  f#6-update_readme_file 브렌치 생성하였습니다.

**Comment by kyungtaak** [comment]
master 에 바로 merge 했습니다. 이슈 종료합니다.
