### ISSUE TITLE
Cannot select option attributes even after option are turned on.

### ISSUE THREAD

**Issue by 9bow** [metatron-app/metatron-discovery#602]
**Describe the bug**
In KPI Chart, some options like 'Using graphic icons', 'Add description' in [Common Setting] or 'Use secondary indicators' in [Set up secondary indicators] are not working even after options are turned on.

**To Reproduce**
1. Select KPI chart on dashboard and choose a measure you want. 
2. Click on [Common Setting] or [Set up secondary indicators] on right.
3. Turn on option like 'Using graphic icons', 'Add description' in [Common Setting] or 'Use secondary indicators' in [Set up secondary indicators].
4. See errors on option properties cannot select / input.

**Expected behavior**
When turn on the option, properties below should be usable.

**Screenshots**
<img width="342" alt="screen shot 2018-10-31 at 10 31 36" src="https://user-images.githubusercontent.com/9343724/47761257-14e11f00-dcfb-11e8-9e45-0fcdd36d324a.png">
'Color Classification' option works well, but 'Using graphic icons', 'Add description' are turned on but not working.
<img width="324" alt="screen shot 2018-10-31 at 10 31 52" src="https://user-images.githubusercontent.com/9343724/47761258-1579b580-dcfb-11e8-8017-95c5ab5034a1.png">
'Use secondary indicators' in [Set up secondary indicators] does not work, too.
<img width="909" alt="screen shot 2018-10-31 at 10 54 27" src="https://user-images.githubusercontent.com/9343724/47761377-773a1f80-dcfb-11e8-934c-161d977d2895.png">
The '*-disabled' css class is applied, and after I delete that on in developer tool, it works.

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14)
 - Browser: Chrome (69.0.3497.100)

**Comment by eltriny** [comment]
#634 이슈에서 처리하였기 때문에 본 이슈는 닫겠습니다.
