### ISSUE TITLE
Sometimes filter disappear when combining filters

### ISSUE THREAD

**Issue by 9bow** [metatron-app/metatron-discovery#603]
**Describe the bug**
Sometimes filter disappear when combining more than two filters.

**To Reproduce**
1. Go to [demo dashboard](https://discovery.metatron.app/app/v2/dashboard/presentation/9abd2b7c-e427-422a-b4c8-52f071a66ad3/c0b68530-9704-4a2d-bae5-37439e6da631) 
2. Click on some dimension on sankey chart on top-left.
3. Click on some value on 'Sales' filter. (eg. set maximum value to 5,000)
4. Select another filter like 'Profit' and set value. (eg. set maximum value to 3,000)
5. See error - Sankey chart disappeared like screenshot below.

**Expected behavior**
Sankey chart never disappear whenever another filter is set.

**Screenshots**
<img width="1920" alt="screen shot 2018-10-31 at 11 31 54" src="https://user-images.githubusercontent.com/9343724/47762603-b3bc4a00-dd00-11e8-97b4-d07d12130f59.png">
Normal status
<img width="1920" alt="screen shot 2018-10-31 at 11 31 40" src="https://user-images.githubusercontent.com/9343724/47762786-68ef0200-dd01-11e8-80d5-37e5921df438.png">
Sankey chart disapeared after two filters are set

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14)
 - Browser: Chrome (69.0.3497.100)

**Comment by kyungtaak** [comment]
@eltriny 데이터가 있는데도 표시가 안되네요. 확인 부탁드립니다. 
![image](https://user-images.githubusercontent.com/822255/47786625-ac705d00-dd4f-11e8-8352-ef74540043b9.png)

**Comment by alchan-lee** [comment]
fixed in #945
