### ISSUE TITLE
In map chart, some point appears white

### ISSUE THREAD

**Issue by 9bow** [metatron-app/metatron-discovery#606]
**Describe the bug**
In map chart, some point (one or more) appears white. It should be colored by selected property.

**To Reproduce**
1. Go to [demo dashboard](https://discovery.metatron.app/app/v2/workbook/ce7ba830-62df-4ed2-90ce-e4b1845247f4)
2. Change map type to 'dark' on [Common Setting]
3. Select dimension and measure. Select measure more than two.
4. On [Layer Setting], select different measure on 'Color by' and 'Size by'. (e.g. Color by Profit, Size by Sales)
5. See error

**Expected behavior**
All point should be colored

**Screenshots**
![screen shot 2018-10-31 at 13 30 24](https://user-images.githubusercontent.com/9343724/47767201-e91f6280-dd15-11e8-88cd-e23269ae546a.png)
<img width="1920" alt="screen shot 2018-10-31 at 21 30 03" src="https://user-images.githubusercontent.com/9343724/47788154-3d493780-dd54-11e8-8a13-085a4fc5dd98.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14)
 - Browser: Chrome (69.0.3497.100)

**Comment by 9bow** [comment]
update missed screenshot
![ScreenShot-2](https://user-images.githubusercontent.com/9343724/47788154-3d493780-dd54-11e8-8a13-085a4fc5dd98.png)

**Comment by kyungtaak** [comment]
@9bow There is a color distribution issue and it was solved in 3.0.6(#594). Can you confirm that it is reproduced?

**Comment by 9bow** [comment]
@kyungtaak Just tried to reproduce with same data, but did not reproduced and worked well. Thank you.

<img width="1237" alt="screen shot 2018-11-11 at 21 59 57" src="https://user-images.githubusercontent.com/9343724/48313269-2ed50880-e5fd-11e8-82ea-e5affa3f009f.png">
