### ISSUE TITLE
file upload using HTML5 File API (experiment on dataprep)

### ISSUE THREAD

**Issue by ksparknot** [metatron-app/metatron-discovery#607]
**Is your feature request related to a problem? Please describe.**
 It needs to show progress bar and be able to cancel when uploading files 
파일 업로드에 진행 상태를 보는 것과 취소가능한 것이 요구됨.

**Describe the solution you'd like**
 We are going to use File API of HTML5. 
That API has onProgress event and you can count how much you have sent. 
you can stop the file transfer too.
Client is using the plupload library.
 HTML5 API를 이용해서 비동기, 백그라운드로 처리를 할 예정임.

**Describe alternatives you've considered**

**Additional context**
First applied experiment on data-preparation

**Comment by kyungtaak** [comment]
@joohokim1 이 건에 대해 혹시 공통화 처리가 가능한가요?
