### ISSUE TITLE
Map chart does not appear on dashboard preview

### ISSUE THREAD

**Issue by 9bow** [metatron-app/metatron-discovery#617]
**Describe the bug**
Map chart does not appear on dashboard preview on left sidebar

**To Reproduce**
1. Go to dashboard, and create map chart
2. Check the left sidebar, map chart preview does not appear

**Expected behavior**
Map chart preview should appear

**Screenshots**
<img width="1920" alt="screen shot 2018-10-31 at 21 33 34" src="https://user-images.githubusercontent.com/9343724/47788411-032c6580-dd55-11e8-8764-2aa4f7737cdb.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14)
 - Browser: Chrome (69.0.3497.100)

**Comment by alchan-lee** [comment]
fixed at #636
