### ISSUE TITLE
Improve usability of partition selection when ingesting stage db

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#619]
**Is your feature request related to a problem? Please describe.**
Stage DB 내 적재 단계에서 파티션이 포함된 테이블 선택시 파티션을 부분적으로 적재할수 있는 기능을 지원합니다. 
이때 입력 방식이 불편하여 파티션 개수만큼 입력해야하며, 특정한 유효성 체크도 존재하지 않아, 사용자로 하여금 실수를 유발시키고 있습니다.

**Describe the solution you'd like**
입력 편의성을 위하여,
- 파티션 입력내 표현식을 적용합니다. (Range 입력, 쉽표 구분자로 다건 입력)
- 기존 파티션 정보를 로드하거나, 표현식에 대한 유효성 체크를 위하여 특정 파티션이 존재하는지 확인합니다.

**Describe alternatives you've considered**
파티션이 많은 테이블인 경우, 성능에 영향을 줄수 있는지 확인합니다. 

**Additional context**

**Comment by ufoscw** [comment]
## 제공가능한 파티션 정보
1. 파티션명 (ex : yymm=20181101/dd=16)
2. Row Number
3. total size (byte)
4. 생성시간 (ex :  2018-06-25 02:32:17.0)

멀티 파티션인 경우도 고려가 필요합니다.

**Comment by AnnieHwang** [comment]
@ufoscw @eltriny 아래와 같이 기획내용이 반영되었습니다.
![image](https://user-images.githubusercontent.com/6300003/47959678-6fe18180-e02d-11e8-92f2-4e25139047e7.png)

**Comment by minjung-cho** [comment]
@kyungtaak @AnnieHwang 
실제 데이터(로우)가 없는거랑, 조회가 안되는거랑은 구분되겠지요??

조회가 안되는 경우 문구는..
“서버 내부 제한 조건으로 인해 테이블 모드에서 데이터 조회가 불가능합니다.
Query 모드에서 데이터를 조회할 수 있습니다.”
이렇게 하는건 어떨까요? 의미가 이게 맞을까요?

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/47985741-fc6b6d00-e11d-11e8-8274-94b0371e2220.png)

![image](https://user-images.githubusercontent.com/42256760/47985731-f37a9b80-e11d-11e8-8b6e-52819128d155.png)

**Comment by ufoscw** [comment]
### API 수정사항
## 1. Strict mode for StagingDB
```
(GET) /api/connections/query/hive/strict
```

## 2. Partition Validation for StagingDB
```
(POST) /api/connections/query/hive/partitions/validate
```

* request sample
```
{
	"database" : "default",
	"query" : "sample_ingestion_partition",
	"type" : "TABLE",
	"partitions" : [
		{
			"ym" : "201704",
			"dd" : "01"
		}
	]
}
```

* response sample
```
[
    {
        "PART_ID": 3,
        "PART_NAME": "ym=201705/dd=01",
        "NUM_ROWS": "28",
        "TOTAL_SIZE": "952",
        "CREATE_TIME": 1529894105
    },
    {
        "PART_ID": 2,
        "PART_NAME": "ym=201704/dd=21",
        "NUM_ROWS": "28",
        "TOTAL_SIZE": "952",
        "CREATE_TIME": 1529894072
    },
    {
        "PART_ID": 1,
        "PART_NAME": "ym=201704/dd=20",
        "NUM_ROWS": "1",
        "TOTAL_SIZE": "28",
        "CREATE_TIME": 1529893937
    }
]
```
* error code
```
status=404 : stageDB의 metastore 정보가 누락되었을때
status=500, code=DC0002 : stageDB 설정이 strictMode가 아닐때
status=500, code=JDC0006 : request의 partition이 stageDB에 존재하지 않을때
```

### application.yaml 설정 추가
```
polaris:
  engine:
    ingestion:
      hive:
        strict-mode: true
        metastore-host: localhost
        metastore-port: 3306
        metastore-schema: metastore
        metastore-user-name: hiveuser
        metastore-password: password
```

**Comment by ufoscw** [comment]
@brandon-wonjune 
API 추가되었습니다.
파티션 validation 체크 후 이상이 있을 경우 에러코드에 맞게 메시지를 보여주면 됩니다.
validation 체쿠거 문제 없을 경우 사용자가 입력한 파티션 파라미터가 아닌 실제 DB에 존재하는 파티션명이 response로 내려갑니다.
해당 파티션명으로 ingestion 정보를 구성해야 합니다. 
클라이언트에서 '=', '/' 으로 split해서 Object로 만들어주시면 될것 같습니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 
```
/api/connections/query/hive/partitions/validate
```
이 api는 validation 체크 버튼을 클릭시 요청하도록 하겠습니다.

그런데 
```
(GET) /api/connections/query/hive/strict
```
이  api는 언제 사용하면 되나요?

**Comment by brandon-wonjune** [comment]
@ufoscw 
그럼 validation을 사용하기 위해서는 strict mode일때만 사용이 가능하는데 
그 strict mode 설정하는 것은 
```
(GET) /api/connections/query/hive/strict
```
이 api를 요청해야 설정이 된다는 이야기 인가요?

그렇다면 현재 나온 UI에서 따로 strict mode를 설정하는 버튼이 필요할 것 같습니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
strict mode 여부는 서버사이드 설정에 들어 있습니다.
해당 API 는 서버 설정값을 프론트에서 확인하기 위한 API 입니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 아래처럼 적용하면 될까요?

1. partition field가 있는 경우
- enable 이 default
- strict 모드인 경우 disable 선택이 비활성화

2. partition field가 없는 경우
- disable이 default
- disable 선택이 비활성화

**Comment by ufoscw** [comment]
@brandon-wonjune 
1. 파티션에 공백 입력시 파라미터가 누락됩니다.
공백 입력하면 key는 포함하고 value 만 공백으로 넘겨주세요.

2. 파티션 validation 시 2가지 에러케이스의 메시지를 다르게 보여줘야 합니다.
 - GB0003 : Invalid Expression
 - JDC0006 : invalid Partition key

3. validation 후 see resule 눌러도 반응 없음

**Comment by ufoscw** [comment]
@brandon-wonjune 
validation 시 JDC00006 이외의 에러 메시지는 지금처럼 Invalid Expression 으로 표현해주시면 될것 같아요.

**Comment by brandon-wonjune** [comment]
@ufoscw 
1번 처럼 공백 입력시 key를 포함하는건 소스 생성할때도 포함시키면 될까요?
현재는 value가 없다면 key를 포함하지 않고있습니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
네 소스 생성시에도 동일합니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
그리고 기획서에는 Partition 입력 필드가 다중입력인데 구현된건 '+' 버튼과 휴지통 버튼이 없네요
이부분도 확인바랍니다.

**Comment by ufoscw** [comment]
@brandon-wonjune @AnnieHwang 
Expression 예시의 표현방식이 실제 파티션과 달라 이해가 잘 안될수 있을것 같습니다.
실제 파티션과 동일한 포맷으로 바꿔야 할것 같습니다.
<img width="406" alt="_2018__11__8__ _10_51" src="https://user-images.githubusercontent.com/3770446/48172968-22bf2180-e345-11e8-8c78-feb621f24b71.png">

**Comment by brandon-wonjune** [comment]
@ufoscw 
위 변경사항 수정하였습니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
<img width="641" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/48188356-f45f3780-e380-11e8-8a45-395ede6f3569.png">

**Comment by brandon-wonjune** [comment]
@ufoscw 
다중 파티션이 위처럼 ym만 있는것이 아닌 dd 가지 있는경우를 말씀하신건가요?
아니면 사용자가 +버튼을 클릭해서 추가했을 경우를 의미하는 건가요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
dd까지 있는 경우입니다.
제가 조금 애매하게 말했는데요. 
정확하게는 다중 파티션일때 공백이 가능한 필드는 제일 마지막 필드만입니다.
나머지 필드는 모두 필수값이어야 합니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 수정하였습니다.
다중 파티션일 경우 마지막 공백을 제외한 파티션 중 하나라도 공백이 있으면 표시되도록 수정하였습니다.
![2018-11-08 7 17 18](https://user-images.githubusercontent.com/42233627/48194824-63dd2300-e391-11e8-826b-7c9db09a5382.png)

**Comment by ufoscw** [comment]
@brandon-wonjune 
1. validation check 후 "+" 버튼을 누르면 Validation 상태가 초기화 되지 않습니다.
2. 레이어가 중첩 됩니다.
<img width="621" alt="_2018__11__8__ _8_35" src="https://user-images.githubusercontent.com/3770446/48196447-f384d080-e395-11e8-8763-a5f6c908ce46.png">

**Comment by brandon-wonjune** [comment]
@ufoscw  + - 버튼 클릭시 validation 초기화하는것 추가하였습니다.
