### ISSUE TITLE
Set limitation on chart view

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#620]
**Is your feature request related to a problem? Please describe.**
카디낼리티가 높은 컬럼을 통해 차트를 그릴때, 이에 대한 제한 정책이 존재하지 않아, 데이터를 로드부터 차트를 그리는 단계까지 많은 시간이 소요되거나 브라우져가 죽는 경우가 발생하고 있습니다. 

**Describe the solution you'd like**
이에 따라 일반적인 공통 제한정책을 두고, 
- 각 차트별로 제한 값을 지정할수 있도록 속성을 추가하고,
- 차트 보기시 제한값에 대한 정보를 표시할수 있도록 구성합니다.

**Describe alternatives you've considered**
사전에 카디낼리티 정보를 알수 있어야합니다. (Engine 내 groupBy.meta 쿼리)

**Additional context**
(N/A)

**Comment by AnnieHwang** [comment]
해당이슈는 https://tde.sktelecom.com/pms/browse/METATRON-125에 있는 내용입니다. 내용 확인차 JIRA링크 올려둡니다. 기획내용 올라오면 해당 메세지는 삭제하도록 하겠습니다!

**Comment by minjung-cho** [comment]
화면에 표시할 데이터가 많을 경우,
센키는 50건, 이외의 차트는 1,000건의 데이터까지만 표시합니다.
이때, 차트 편집화면과 대시보드의 차트 위젯의 아이콘을 통해 사용자가 확인할 수 있습니다.
<img width="1334" alt="2018-11-02 10 57 49" src="https://user-images.githubusercontent.com/28773903/47889717-a92fbb00-de8e-11e8-937a-19acf2b62094.png">
<img width="662" alt="2018-11-02 10 58 50" src="https://user-images.githubusercontent.com/28773903/47889718-a92fbb00-de8e-11e8-800a-46fdcd918528.png">

**Additional context**
METATRON-1254

**Comment by eltriny** [comment]
@kyungtaak 
각 차트별로 제한 값을 지정할수 있도록 속성은 어떻게 되는 것인가요?
그리고 차트 데이터에서 값이 제한되고 있다는 것은 어떤 내용을 확인하면 알 수 있나요?

@minjung-cho 
차트에서 제한 값을 지정할 수 있는 화면에 대한 기획 확인 부탁드립니다.

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다
![image](https://user-images.githubusercontent.com/42256760/47973557-6ec15a80-e0e8-11e8-8fb9-d2c533a804b3.png)

**Comment by minjung-cho** [comment]
@eltriny 
리밋 조정 UI를 별도로 만들지 않고, 차트 별로 정해진 값으로만 제한하기로 협의되었습니다~
센키는 50건, 이외의 차트는 1,000건

**Comment by kyungtaak** [comment]
@eltriny  limit 관련 쿼리 스펙은 아래와 같습니다.
```
{
  ...
  "limits": {
        "limit": 1000,
        "sort": [
          ...   
        ]
   },
...
}
```

**Comment by AnnieHwang** [comment]
@eltriny 차트에서 제한 값을 지정할 수 있는 화면은, 전에 차트상세 우측패널 설정인 Limit 설정 UI를 그대로 이용한다고 알고 있습니다. @esezin @minjung-cho 해당 내용 확인 부탁드립니다.

**Comment by eltriny** [comment]
@AnnieHwang 
![1](https://user-images.githubusercontent.com/3685833/48039205-1b6a0d80-e1b7-11e8-9642-a910bad6824d.png)
기존 Limit 설정 UI 가 이렇게 있었는데 그대로 사용하면 되는것인가요?

@kyungtaak 
![2](https://user-images.githubusercontent.com/3685833/48039219-2de44700-e1b7-11e8-9bd5-face016b7cee.png)
기획에서는 전체 건수와 현재 제한되고 있음을 명시적으로 보여주도록 되어 있는데, API 결과상으로는 이러한 것을 알기 어려운것 같습니다. 어떻게 해야 하나요?
아니면 Limit 설정이 되면 위 이미지의 내용을 총건수는 제외하고 Limit 건수만 표시하는 것으로 보여주면 될까요?

**Comment by kyungtaak** [comment]
@eltriny 답변이 늦어져 죄송합니다.
사전에 Cadinality 를 구하는 로직이 타 이슈에서 작업중입니다. 
작업이 완료후 차트 결과값내 info.totalCount 값으로 전달예정이오니 미리 매핑 부탁드립니다. 
만에하나, 내부 Cadinality 값 처리 오류로 값이 "-1" 값이나 값이 전달이 안될 경우가 있을수 있습니다.
이 때, 실제 건수가 1000 건인 경우 (총 1000+ 건) 이런식으로 표현했으면 하는데요. @metatron-app/design  @AnnieHwang 확인 부탁드립니다.

**Comment by eltriny** [comment]
#505 이슈와 연관있어 f505-handling_status_datasource_ingestion 브랜치에서 작업 합니다.

**Comment by kyungtaak** [comment]
@eltriny 정정합니다. info.totalCategory 가 의미상 맞을것 같네요. 그리고 엔진 업데이트가 병행되어야하기 엔진 바이너리도 별도 링크로 전달드리겠습니다.

**Comment by kyungtaak** [comment]
@eltriny 차트내 속성에 ui 가 표현되고 있던데요. 이에 따라 limit 속성을 chart spec 내에 넣어보았습니다.
```
{
  "type": "bar",
  ...,
  "limit": 1000,
  ...
}
```

**Comment by AnnieHwang** [comment]
@eltriny 약간 기능이 추가될것 같은데요. @esezin 님이 기획안 올려주실꺼예요.

**Comment by navis** [comment]
뭔가 콩구워 먹는 느낌이긴 한데, 일단 tmap 브랜치에 올렸습니다. estimation 이 불가하면 group-by 쿼리가 그대로 날아가니 timeout 값을 적절히 세팅해 주세요.

**Comment by navis** [comment]
500 은 모르겠고 exception 내도록 수정했습니다.. 그냥 cardinality -1 을 리턴하는게 나을 거 같은데요?

**Comment by kyungtaak** [comment]
네.. 생각해보니, @navis 님의 의견이 좋을것 같습니다. (수정하셨는데.. 죄송합니다만, 다시변경이 가능할가요?)

**Comment by navis** [comment]
@kyungtaak 올려놨습니다.

**Comment by kyungtaak** [comment]
@eltriny 제가 알기론 기본값으로 표시해야 맞을것 같은데요. @metatron-app/design 에게 문의하여 적용 부탁드립니다.

**Comment by kyungtaak** [comment]
@eltriny @esezin 테스트하면서 간과한 몇가지가 있네요.
- Pie Chart  : 아래 화면처럼 Pecentage 가 전체 기준으로 나와야할까요? (여기에 Limitation 아이콘이 없는건 오류인듯합니다.)
![image](https://user-images.githubusercontent.com/822255/48872740-d20ff400-ee2d-11e8-934a-7acbd1b64b4c.png)

- Gauge Chart  : 동일 조건의 Gauge 차트입니다. 여기는 전체기준으로 잡아 게이지가 모두 차지 않는데요.
![image](https://user-images.githubusercontent.com/822255/48872809-1602f900-ee2e-11e8-8038-06ec1a29c265.png)

- Tree Map 의 경우 1 Level 기준으로 limit 을 잡는게 맞겠지요? 그럼 1000건도 많고 Sankey 와 Network 차트와 동일한 수준의 기본 limitation 이 필요할것으로도 보입니다.
  
- Sankey / Network Chart 는 어떤기준으로 limit 을 잡는게 좋을까요?

**Comment by eltriny** [comment]
@kyungtaak Pie chart 에서 info의 totalCategory 값이 0으로 내려오고 있습니다. 확인 부탁드립니다.

**Comment by AnnieHwang** [comment]
@kyungtaak @esezin @eltriny  
- 실제 건수가 1000 건인 경우 (총 1000+ 건)이라고 변경하도록 하겠습니다.
- 차트 패널 Limit건수 하단 옵션으로 'Other로 묶기' 부분도 넣으려고 했는데 이번 개발건에서는 빠지는것으로 결정되었습니다.
답변이 늦어서 죄송합니다.

**Comment by esezin** [comment]
@kyungtaak, @eltriny 
UX측면에서 의견드립니다.

- Pie Chart와 Gauge Chart는 언제나 '100%'를 기준으로 표현하기 때문에, Limitation을 설정하면, 그 설정 개수 대로 100% 꽉차게 표시하는 것이 맞습니다. 위 스크린샷 기준으로는 Gauge Chart가 잘못 표현되고 있는 것입니다.

- Treemap은 모든 레벨에서 limitation이 유지되어야 하는 것 아닐까요? 2레벨로 drill-down했는데, 많은 수의 아이템이 뿌려지면서 문제가 생긴다면 원래의 이슈 취지에 맞지 않는 것 같습니다.

- 기본적으로 Sankey와 network 차트도 Aggregation 된 아이템 개수 기준으로 잡으면 될 것 같습니다. Sankey는 현재 echart 버그로 인하여 화면상으로는 50개 표현하는 것으로 알고 있습니다. 네트워크 차트도 많아지면 느려지는 대표적인 차트인데, 확인이 좀 필요할 것 같습니다.

**Comment by kyungtaak** [comment]
@AnnieHwang @esezin
답변 감사합니다. 일단 이슈가 있는 나머지 차트는 별도 이슈를 생성하여 일정을 잡고 진행하도록 하겠습니다.

**Comment by kyungtaak** [comment]
#863 에 이어진행합니다. 해당 이슈에서는 Network/Sankey/Gauge/Treemap 차트를 제외한 나머지 차트에 적용하였습니다.
