### ISSUE TITLE
Rule(setformat) editor modify

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#622]
**Is your feature request related to a problem? Please describe.**
setformat rule(timestamp) editor modify

**Describe the solution you'd like**
remove Custom format
user typing timestamp pattern and autocomplete

**Describe alternatives you've considered**

**Additional context**

**Comment by joohokim1** [comment]
This issued cannot be done in 3.0.6. Moving to 3.0.7.

**Comment by imsaaks** [comment]
fixes the problem of gaps by unit of column (union)

**Comment by imsaaks** [comment]
Focus is not possible during the initial selection step. May affect other actions.
However, after clicking the component, focus was applied.

**Comment by joohokim1** [comment]
The PR of this issue had been merged after creating the current integrated test binary.
I think it'll be effective on the 2nd integrated test, hopefully.
