### ISSUE TITLE
Fail create datasource used file type

### ISSUE THREAD

**Issue by brandon-wonjune** [metatron-app/metatron-discovery#624]
**Describe the bug**
Fail create datasource used file type

**To Reproduce**
1. Go to 'Datasource Create'
2. Click on 'File create'
3. Next create step

- used file
[sale.txt.csv.zip](https://github.com/metatron-app/metatron-discovery/files/2537259/sale.txt.csv.zip)

**Expected behavior**
Data source must be created

**Screenshots**
![2018-11-01 1 57 45](https://user-images.githubusercontent.com/42233627/47833456-2c450880-ddde-11e8-8cbe-3c8b48bf5e27.png)

```
// error 
code: "GB0001"
details: "Illegal pattern character 't'"
message: "Unknown server error"
```

**Desktop (please complete the following information):**
 - test server

**Additional context**

**Comment by alchan-lee** [comment]
current_time로 타임스탬프를 생성할때 발생하는 이슈이며
#623 에서 해결되었습니다.
