### ISSUE TITLE
In the case of series by dimension, the tooltip representation is incorrect.

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#629]
**Describe the bug**
디멘젼을 시리즈로 나눴을때 툴팁 표현이 중복적으로 잘못된 값이 노출되고 있음

**To Reproduce**
1. Go to '차트' (라인 혹은 막대)
2. 디멘젼을 교차에 올림 (디멘젼을 열에, 매져를 교차에 올림)
3. 툴팁을 확인함

**Screenshots**
![image](https://user-images.githubusercontent.com/6300003/47849948-da6ca480-de16-11e8-9217-2e8118cb9baa.png)
![image](https://user-images.githubusercontent.com/6300003/47849956-dfc9ef00-de16-11e8-8f22-522253ff62b0.png)

**부연**
저희 샘플사이트에 샘플 만들어 올려드릴께요. 
https://discovery.metatron.app/app/v2/workbook/45201034-1b16-4323-86e5-65b932ecbb8d
![image](https://user-images.githubusercontent.com/6300003/48114109-141f2e80-e2a1-11e8-931d-8e699953f37a.png)

**Comment by eltriny** [comment]
@AnnieHwang 
현재 본 이슈의 내용이 재현이 되지 않고 제공해주신 link도 대시보드가 삭제되어 있는데...
지금도 재현되시는지 확인 부탁드립니다.

**Comment by dongwoo313** [comment]
이슈 내용 확인 가능한 url 정보입니다.
https://discovery.metatron.app/app/v2/workbook/eb4c05d2-532e-4f0e-8479-ed8097466a69
차원값 1개가 교차선반에 올라간 경우 증상이 나타나며 두번째 선형차트에서 확인 가능합니다.
증상이 있는 차트의 차원값을 뺐다가 다시 올리면 증상이 사라지고 정상처럼 보이기도 합니다.
(처음 생성할 때 차원값을 교차선반에 올리면 증상을 만들 수 있습니다.)

**Comment by juheeko9** [comment]
f#629-tooltip_represent_error 브랜치 생성하였습니다.
