### ISSUE TITLE
Processing when table data can not be retrieved due to restrictions in the DB server

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#630]
**Is your feature request related to a problem? Please describe.**
DB 를 통한 적재시, 테이블 정보조회시 Preview 단계에서 DB 내부 제한 조건에 의하여 테이블 조회가 불가능한 경우가 있습니다.  (ex. Hive 내 strict 모드에 의하여 파티션이 있는 테이블 조회시 파티션을 필터조건에 포함되어야 함) 이에 대한 적절한 처리 가이드가 필요합니다. 

**Describe the solution you'd like**
단순 테이블 조회시 오류는 DB 서버내 제한조건(strict/권한) 으로 인하여 테이블 조회 제한이 있고,  대안으로 Query 모드로 전환하여 적재할수 있음을 인식시킬수 있는 메시지를 제공합니다. 
메시지 예시)
"해당 테이블은 서버내 내부 제한 조건에 의해 조회가 불가능합니다. 
 다른 테이블을 선택하거나, Query 모드로 전환해주세요."

**Describe alternatives you've considered**
토스트 메시지로 전달 할지, Preview 데이터 테이블영역에 위치할지 검토가 필요할것 같습니다.
@metatron-app/design 검토 부탁드립니다.

**Additional context**
@metatron-app/design @joohokim1  dataprep 기능에도 동일한 기능이 있으니 함께 검토가 필요합니다.

**Comment by eltriny** [comment]
@metatron-app/design 
위 내용에 대한 진행 방향 확인 부탁드립니다.

@kyungtaak 
preview 단계에서 조회 오류가 나오면 무조건 위와같이 메시지를 제공하는 방식으로 처리하면 되는 것인가요?

**Comment by minjung-cho** [comment]
@kyungtaak @AnnieHwang
실제 데이터(로우)가 없는거랑, 조회가 안되는거랑은 구분되겠지요??

조회가 안되는 경우 문구는..
“서버 내부 제한 조건으로 인해 테이블 모드에서 데이터 조회가 불가능합니다.
Query 모드에서 데이터를 조회할 수 있습니다.”
이렇게 하는건 어떨까요? 의미가 이게 맞을까요?

**Comment by minjung-cho** [comment]
@eltriny 
테이블 영역에 문구가 나타나는 것으로 진행하려고 합니다

**Comment by minjung-cho** [comment]
@eltriny @koeun222 @eltriny 최종 문구는 아래와 같습니다.
경고에 사용하는 컬러로 적용 부탁드립니다~
" 
서버 내부 제한 조건으로 인해 해당 테이블의 데이터 조회가 불가능합니다. 
다른 테이블을 선택하거나 Query 모드에서 데이터를 조회할 수 있습니다.
"

**Comment by joohokim1** [comment]
@kyungtaak @ksparknot
dataprep 쪽은 본 이슈 완료후, 후속 이슈로 진행하는 것이 더 좋을 것 같습니다.
현재 dataprep에선 PrepException (extends MetatronException) 를 정의해서 error detail 전달 및 표출하도록 되어있어서요.. dataprep쪽 코딩까지 한 이슈로 묶으면 진행이 더뎌지고, 한 이슈에 관련된 사람이 너무 많아지는 것이 우려됩니다. 동의하신다면 본 이슈 완료 직후 급행으로 이어서 진행하겠습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak 해당이슈는 #619 에서 같이 처리하겠습니다

**Comment by ufoscw** [comment]
@brandon-wonjune 
해당 케이스 에러 코드는 메시지코드로 전달될 예정입니다.
아래 코드와 다국어 리소스 번들 키를 매핑해서 보여주면 될것 같습니다.

```
http status : 500
response : 
{  
   "code":"error.dataconnection.jdbc.preview.table",
   "message":"Fail to connect",
   "details":"Fail to query : 42000, 40000, Error while compiling statement: FAILED: ParseException line 2:15 cannot recognize input near '''' ';' '<EOF>' in constant"
}
```

**Comment by brandon-wonjune** [comment]
![2018-11-07 5 42 25](https://user-images.githubusercontent.com/42233627/48121226-b3e7b700-e2b7-11e8-9521-03607726e05b.png)
작업 완료하였습니다
