### ISSUE TITLE
Stream (Realtime) type display error in datasource list

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#631]
**Describe the bug**
Stream(Realtime) 타입의 데이터 소스 목록 표시가 되지 않는 현상이 있습니다. 

**To Reproduce**
1. API 를 통한 Stream 데이터 소스 생성 
2. 데이터 매니저 권한으로 로그인 (ex. admin, polaris)
3. Management > Data Storage > Datasource 화면 이동
3. 목록내 등록한 데이터 소스 타입 확인

**Expected behavior**
화면상에서 적재는 불가능하지만, API 로 적재가 가능하여 화면상 목록에는 타입이 표시가 되어야합니다. 

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/47851616-81a00a80-de1c-11e8-80ac-06cb1956c828.png)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
- Stream(Realtime) 데이터 소스 등록 환경 필요 (Kafka 포함)

**Comment by brandon-wonjune** [comment]
f#631-add_stream_type_source_list 브랜치 생성하였습니다

**Comment by brandon-wonjune** [comment]
stream 타입 데이터소스 목록에 추가하였습니다.
상세화면의 경우는 #549 에서 수정하겠습니다
