### ISSUE TITLE
When viewing data, hide current time column

### ISSUE THREAD

**Issue by minjung-cho** [metatron-app/metatron-discovery#637]
**Problem**
1. 타임스탬프를 Current time으로 설정한 경우, 실제 사용되지 않는 불필요한 컬럼이 생김

**Solution**
1. 메타트론 모든 화면에서 Current time 컬럼이 사용자에게 보이지 않도록 해야 합니다
    1. 데이터소스 생성 씬 
        1. 타임스탬프 설정을 current time으로 설정해도 컬럼 리스트에 current time 컬럼이 보이지 않음
    2. 데이터 열람 씬
        1. 데이터소스 상세 페이지 또는 팝업 > Data / Column details
        2. 콘텐츠 생성 > Data Preview

**Comment by brandon-wonjune** [comment]
f#637-hide_current_column 브랜치 생성하였습니다

**Comment by brandon-wonjune** [comment]
@kyungtaak 
해당 이슈 문의사항있습니다.
current time으로 생성된 데이터소스를 상세조회시 해당 데이터소스가 current time을 선택했는지 실제로 컬럼을 선택했는지 구분할수가 없습니다.
단순히 ui에서 current_datetime 이란 이름으로 판단을 하면 되나요?

**Comment by kyungtaak** [comment]
@brandon-wonjune ui 에서만 숨겨주시고요. field 생성은 그대로 해서 보내주시면 될것 같습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak 
네 데이터소스 생성시에는 ui에서 숨길수 있습니다.

그런데 '데이터소스 상세화면'에서는 해당 컬럼이 current로 생성된 타임스탬프 컬럼인지 알수없습니다.

**Comment by brandon-wonjune** [comment]
그리드 화면, preview 화면에서 컬럼의 role이 TIMESTAMP이고 이름이 current_datetime인 컬럼을 hide 시켰습니다.
![2018-11-06 9 50 56](https://user-images.githubusercontent.com/42233627/48065582-7e3ac380-e20e-11e8-9168-e8972400fa31.png)
![2018-11-06 9 51 00](https://user-images.githubusercontent.com/42233627/48065583-7e3ac380-e20e-11e8-8d80-b87249043b69.png)
![2018-11-06 9 51 04](https://user-images.githubusercontent.com/42233627/48065584-7e3ac380-e20e-11e8-87d0-0620cc4add3b.png)

**Comment by eltriny** [comment]
@kyungtaak 
존재하는 필드중에서 role이 TIMESTAMP 이고 이름이 current_datetime인 컬럼인 경우도 숨겨질텐데 이 경우는 괜찮은 건가요??

**Comment by kyungtaak** [comment]
@eltriny @brandon-wonjune  format 필드에 { "type": "time_temporary" } 로 넣어주시고 이것을 활용하셔서 hide 여부를 처리하시면 어떨런지요? 확인 부탁드립니다. 저 필드는 어쩔수 없이 #505 이슈내 포함을 시켰네요. 죄송하지만 머지를 하거나, #505 브렌치에 업데이트 해주시는 방식으로 처리 부탁드립니다.

**Comment by circleGiven** [comment]
@kyungtaak 
> format 필드에 { "type": "time_temporary" } 로 넣어주시고

데이터소스 생성시에 format type을 time_temporary로 하면 되는건가요?

**Comment by brandon-wonjune** [comment]
@kyungtaak 

> format 필드에 { "type": "time_temporary" } 로 넣어주시고

데이터소스 생성시에 format type을 time_temporary로 하면 되는건가요?

**Comment by kyungtaak** [comment]
> 데이터소스 생성시에 format type을 time_temporary로 하면 되는건가요?

넵!

**Comment by brandon-wonjune** [comment]
@kyungtaak 위 변경사항 적용하였습니다

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho  이 이슈에 대해서는 추가 검토가 필요한것 같은데요 아직 피드백이 없는것 같습니다.
- current_time 에 대한 처리는 적재시 숨기지만 대시보든 상 데이터 소스 처리시에는 숨길것인지? 
- 숨긴다면, timestamp role 을 가진 필드가 global fileter 로 자동으로 지정되는 룰은 없는것인지?

위의 내용이 해결이 되지 않는다면, 그냥 기존대로 모두 노출하는 편이 나을것인지 확인이 필요합니다.

**Comment by kyungtaak** [comment]
@brandon-wonjune 현재 linked datasource 일 경우도 `{ "type": "time_temporary" } ` 를 넣어주시나요?
- 워크벤치 내 미리보기시 처리
- 링크 데이터 소스 적재시...(이건 공통이니 되겠지요?)

**Comment by brandon-wonjune** [comment]
@kyungtaak 
네 현재 데이터소스 생성시 current time에 대해서는 모두 { "type": "time_temporary" } 생성되고 있습니다

**Comment by kyungtaak** [comment]
@brandon-wonjune 미리 보기 제가 다시한번 점검해보고 필요한 내용이 있다면 요청드리도록 하겠습니다.

**Comment by kyungtaak** [comment]
@brandon-wonjune 아래처럼 미리보기시에도 current time 에 대해서 추가가 필요합니다.
![image](https://user-images.githubusercontent.com/822255/48550651-b92bae00-e916-11e8-8f44-a8d606514bfb.png)

**Comment by kyungtaak** [comment]
@eltriny @brandon-wonjune @minjung-cho current_time을 숨겨야하는 예시입니다. Linked DataSource 의 경우 이 화면에서 essential filter 가 자동으로 지정되는 바람에 candidate api 가 호출이 되면서 오류가 발생해요. 
![image](https://user-images.githubusercontent.com/822255/48550700-d496b900-e916-11e8-882b-2c431e98a962.png)

**Comment by minjung-cho** [comment]
@kyungtaak 
필수필터(추천필터), 글로벌필터에서 타임스탬프를 제거하는 것이 이 이슈 처리보다 선행되어야 할 것 같습니다.
그리고,  current time 컬럼은 데이터소스와 대시보드단 등 모든 메타트론 화면에서 숨기는 것으로 기획쪽에서는 정리되었습니다.
@AnnieHwang 기 논의된 것과 다른 내용이 있다면 말씀부탁드립니다.

**Comment by AnnieHwang** [comment]
@minjung-cho @kyungtaak 조민정님이 말씀하신 내용 맞고요. 타임스탬프는 제거 해야 하고, 대시보드나 데이터소스 상에서도 노출되지 말아야 할것 같습니다. 또한 글로벌필터에 타임스탬프가 무조건 적용되었던 기능도 제거 하는 이슈가 먼저 선행되어야 할 것 같습니다.

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho 넵 알겠습니다. 그럼 관련 정책 변경에 대해 이슈등록 부탁드릴게요. 그 이슈 이후 진행하는것으로 하겠습니다.

**Comment by AnnieHwang** [comment]
@kyungtaak 저희가 할수 있는건 current time이 쓰이는 부분을 추려내는건 할수 있을것 같은데, 별도의 이슈로 만들어야 할까요? 정책이랄께 따로 없을꺼 같아서요.

**Comment by kyungtaak** [comment]
@AnnieHwang 일단 이 이슈에서 함께 처리하는것으로 했으면 합니다. 

참고로 금일 개발 미팅시 추가로 논의했던 사항중 기존 current_datetime 으로 등록된 데이터 소스에 대한 처리입니다.
- 현재 변경된 사항 중 unload 속성을 추가하였습니다. 이 값이 true 이면, 서버내에서 대시보드 구성시 데이터소스 필드(컬럼) 정보에서 제거
- 기존 current_datetime 으로 등록된 컬럼에 대해 unload 속성을 true 로 마이그레이션 
- current_datetime 을 global filter 로 지정한 기존 대시보드는 데이터소스 필드(컬럼) 정보에 포함이 되어있지 않다면, filter 제외 (제외 처리 확인을 위한 별도 장치 고려)

@eltriny @brandon-wonjune  위 내용 확인해주시고요. 현 이슈에서 개발 진행 부탁드립니다.

**Comment by eltriny** [comment]
![1](https://user-images.githubusercontent.com/3685833/49028978-f893ad80-f1e6-11e8-811d-0cc838924690.png)
@kyungtaak @metatron-app/design 
타임스탬프를 숨김 경우에는 위의 이미지 처럼 데이터 미리보기에서 시간 필터링 하는 부분이 없게 되는데요.
이 경우에는 어떻게 처리하는 것이 좋을까요?

**Comment by AnnieHwang** [comment]
@eltriny 퍼블리셔에게 이야기해서 시간필터 영역이 없는 경우, 텍스트그리드를 상단에 border에 맞게 위로 당겨야 할것 같습니다.

**Comment by AnnieHwang** [comment]
@eltriny 어차피 current time으로 ingestion된 것만 시간 영역이 없어지는거라, current time 값인 전체가 보이면 됩니다. 즉 말씀하신 것 처럼 전체 범위 데이터가 제공되면 됩니다.
