### ISSUE TITLE
Don't change the chart zoom when changing minimap option on/off

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#64]
**Is your feature request related to a problem? Please describe.**
chart zoom 배율을 변경 한 후에 minimap 의 on/off 상태를 바꾸면 배율이 리셋되는 현상이 있음

**Describe the solution you'd like**
minimap 옵션을 켜거나 끄더라도 chart zoom 배율은 그대로 있어야 함.

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
@i1befree 해당 리셋현상에 대한 상세한 재현경로가 있다면 확인 부탁드립니다.
@eltriny 위 현상에 대해 추가 확인 부탁드립니다.

**Comment by DAVE-EXNTU** [comment]
@kyungtaak 
현재 적용된 데이터줌은 마지막 저장시점의 위치만 기억하게 되어있습니다.
그렇기에 줌위치 이동 후 미니맵 on/off시 저장시점의 위치로 돌아가기 때문에 
리셋 되는것처럼 보여지는것 같습니다.
해당 증상은 현재 수정되어 pull request 예정입니다.

**Comment by kyungtaak** [comment]
@DAVE-EXNTU 차트위젯내에서 우측 속성 변경 패널에서 속성 변경시에도 미니맵이 초기화된는데요. 유사한 이슈이면, 함께 처리가 가능할가요?

**Comment by DAVE-EXNTU** [comment]
@kyungtaak 
죄송하지만 재현방법을 조금 디테일하게 말씀해주실 수 있을까요?
현재 저희쪽에선 해당증상을 찾지 못하였습니다.

**Comment by kyungtaak** [comment]
@DAVE-EXNTU 재현 케이스입니다.
1. Bar Chart 생성 (선반 : City, 교차 : SUM(Sales) )
2. minimap 스크롤을 중간으로 이동
3. 컬러 설정을 Series 에서 Dimension 또는 Measure 로 이동

**Comment by DAVE-EXNTU** [comment]
@kyungtaak 말씀해주신 케이스에서도 작동이 확인됩니다.

**Comment by kyungtaak** [comment]
@DAVE-EXNTU 수정 전 버젼에서  다른 케이스를 확인하여 추가 확인 요청을 드렸던 내용인데요. 수정하신 내용으로 위의 케이스도 정상 동작 되는것을  확인했습니다.
