### ISSUE TITLE
Intuitive phrase change request in Job Log Detail

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#640]
**Is your feature request related to a problem? Please describe.**
Intuitive phrase change request in Job Log Detail.
The subject of the "Recent 5 queries" is unclear.
<img width="743" alt="metatron_discovery" src="https://user-images.githubusercontent.com/3770446/47888728-57386680-de89-11e8-8793-7f6f8befbf43.png">

**Describe the solution you'd like**
Need to change to mean the last 5 queries based on data connection

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang 확인 부탁드립니다.

**Comment by AnnieHwang** [comment]
@ufoscw @minjung-cho  워크벤치에서도 Query History => Query Result로 변경했는데, "Recent Query Result"로 기술하면 어떠신가요?

**Comment by minjung-cho** [comment]
@AnnieHwang 적당한 문구인것 같습니다. @ufoscw 확인해 주시면 문서에 반영하겠습니다

**Comment by ufoscw** [comment]
@AnnieHwang @minjung-cho 
제가 확인 요청 드린건 5건의 기준에 대해 레이블이 명시적이지 않은게 문제입니다.
현재 저 목록은 쿼리 상세조회 화면에 나오는 목록인데요..
저 목록의 의미는 "상세조회중인 쿼리와 동일한 커넥션을 사용해 수행된 최근 5건의 쿼리" 목록입니다.
사용자가 정확히 이런 의미의 목록이라고 현재의 레이블로는 파악하기 힘들어서 매번 사용자가 저 목록의 의미를 물어봐서요.
뭔가 명시적인 레이블로 변경하거나 아니면 저 목록을 좀더 사용자가 이해하기 쉬운 데이터로 변경하거나 하는 대안이 필요해 보입니다.

**Comment by minjung-cho** [comment]
@ufoscw 문군는 아래와 같이 하면 어떠신가요? 레이블이 길어지면 레이블 아래에 그리드를 둬야 할것 같습니다
Recent history of the same connection (동일 커넥션의 최근 사용 기록)
![image 31](https://user-images.githubusercontent.com/28773903/49129787-773a3900-f314-11e8-98dd-3014482f7bdd.png)

**Comment by ufoscw** [comment]
@eltriny 
위의 내용 반영 부탁드립니다.
문구 변경 및 그리드 위치 변경입니다.
```Recent history of the same connection (동일 커넥션의 최근 사용 기록)```
