### ISSUE TITLE
Column type change to Time/Hour is not processed properly

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#644]
**Describe the bug**
컬럼 리스트에서 컬럼 타입을 시간 타입으로 변경시, 타입 변경처리 되지 않으며, 
이후 다른 컬럼 변경 시도 시 선택창 오류 발생함 

**To Reproduce**
데이터소스 생성하기에서,
1. 컬럼명 옆 체크박스 선택
2. 타입 변경 - 날짜/시간
3. 날짜/시간 타입 변경 반영 되지 않음. 
4. 다른 컬럼의 체크박스 선택 후 타입 변경 시도시 선택창 오류 발생

<img width="1011" alt="20181102_131347" src="https://user-images.githubusercontent.com/44457771/47893906-f74eb980-dea2-11e8-84d0-a7a0ea337924.png">

**Comment by brandon-wonjune** [comment]
f#644-fix_type_change_error_datasource 브랜치 생성하였습니다

**Comment by alchan-lee** [comment]
it will be fixed into 3.0.6
