### ISSUE TITLE
Validation does not work properly when there are many types of Time/Hour columns.

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#645]
**Describe the bug**
시간표현타입이 yyyyMMddHHmmss인 컬럼과 yyyyMmddHHmmssSSS인 컬럼이 존재할 때, 시간타입 컬럼의 validation check에서 오류 팝업 발생하는 경우 있음

**To Reproduce**
tmap.log_advt
1. req_time_ss 컬럼을 yyyyMMddHHmmssSSS
2. play_start_time_ss컬럼을 yyyyMMddHHmmss
3. 다음 버튼 누름
4. 이전으로 다시 돌아옴
5. 다시 다음 버튼을 누름

**Screenshots**
<img width="1375" alt="20181102_131731" src="https://user-images.githubusercontent.com/44457771/47894406-0420dc80-dea6-11e8-8c5c-99f8b4d84517.png">

**Comment by alchan-lee** [comment]
현재 버전에서는 재현이 되지 않아 종료 처리 하겠습니다.
