### ISSUE TITLE
When creating a data source, the data range is not displayed correctly

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#646]
**Describe the bug**
데이터소스 생성하기 마지막 단계에서, 데이터범위가 올바르게 표기되지 않음

**To Reproduce**
데이터소스 생성 시에 데이터범위를 설정하면
데이터소스 생성 마지막 화면에서 확인 가능함

**Screenshots**
<img width="694" alt="20181102_131946" src="https://user-images.githubusercontent.com/44457771/47894581-00da2080-dea7-11e8-90c6-c0f9aefe31e2.png">

**Comment by kyungtaak** [comment]
@jeongeunkwon #1092 이슈가 수정되며 해당이슈도 함께 수정이되어 이슈를 종료합니다.
