### ISSUE TITLE
When I change crossing point value of area-line chart, measure based color distribution doesn't work

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#65]
**Describe the bug**
라인 차트로 차트를 그린 후에 색상 모드를 measure 로 하고 이 후 crossing point 값을 최저값에 근접하게 그리면 전체 색깔이 지정된 값 범위에 맞게 동작하지 않음.
추가적으로 areachart 에서 색 분배시 최소값과 최대값을 기준으로 색 분배가 맞는지 고려가 필요함. 개인적인 생각으로 최소값은 Crossing line 값과 최소값 중 작은 것을 선택하는 것이 맞을 것 같음.

**To Reproduce**
다음 url 참조 : https://discovery.metatron.app/app/v2/workbook/67cf1062-3fa8-453f-8be8-a737c7e67994

1. 라인차트로 년도별 Winner_s_avg_speed 의 평균값을 정의.
2. 색상을 measure 모드로 변경
3. Crossing point 를 20으로 변경
4. 스크린샷 확인

**Expected behavior**
색은 정의된 값의 범위에 맞게 처리되야 한다.

**Screenshots**
<img width="1621" alt="linechart_measure" src="https://user-images.githubusercontent.com/526622/44560679-d6c00000-a78b-11e8-8e03-2627da7f1fef.png">

**Desktop (please complete the following information):**
demo site

**Additional context**

**Comment by kyungtaak** [comment]
@eltriny 색상 처리 확인 부탁드립니다.

**Comment by judy-exntu** [comment]
f#65-cross_point_color_error 브랜치 추가하였습니다.
