### ISSUE TITLE
Can not make preparation snapshot in dataflow, before open it at least once.

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#66]
**Describe the bug**
프리퍼레이션 화면에서 스냅샷을 생성하려고 시도하면 dp.alert.no.dataset 에러 발생.

**To Reproduce**
1. 서버를 재가동한다.
2.데이터 플로우 화면에서 임의의 데이터 셋을 선택한다.
3.우측 메뉴에서 snapshot 생성을 선택한다.
4.데이터셋 편집화면으로 들어가서 Grid view를 확인한 뒤에 재시도 하면 에러가 발생하지 않음.

**Expected behavior**
msg.dp.alet.no.dataset 에러 발생

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Additional context**

**Comment by joohokim1** [comment]
이 이슈는 제가 처리하겠습니다.
Snapshot을 생성하기 전에 RevisionSet을 만들어야 하는 이유는 다음과 같습니다.
- 한 번도 룰 편집에 들어가지 않고, dataflow chart 화면에서 context menu로 snapshot 생성시 error 발생
- 룰 편집 화면에 들어 있는 상태에서, 서버가 재기동되었을 때, snapshot 생성시 error 발생
- Snapshot 생성을 실제로 실행하기 전에 컬럼명 규칙 (Hive snapshot의 경우, Hive 컬럼명이 될 수 있는지 여부 등) 체크 필요

**Comment by joohokim1** [comment]
All PRs merged. Issue closed
