### ISSUE TITLE
Change Readme.md file

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#661]
**Is your feature request related to a problem? Please describe.**
Modification of the Readme.md file is required as new functionality is introduced. Especially since the map and other functions have been introduced, I would like to supplement the screen shot accordingly.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
It is also desirable to add an additional animation gif.

**Comment by AnnieHwang** [comment]
브랜치 f#661-readme-file 로 생성하였습니다.
