### ISSUE TITLE
 In the case of the same name, identity information must be exposed.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#667]
**Is your feature request related to a problem? Please describe.**
![default](https://user-images.githubusercontent.com/612173/47999563-55e79200-e146-11e8-8ce9-ce5384de2597.png)
- 스크린 샷은 Data Connection 에 대한 Workspace 별 권한 설정 화면이며, 동명이인의 경우 권한을 부여하고자 하는 정확한 대상이 누구인지 확인할 수 있는 방법이 없음
- 유저의 정보가 표현되는 대부분의 UI 에서 위와 같은 경우가 발생하거나, 혹은 그 반대의 경우 ID 만 표현되어 누구인지 알기 힘든 경우가 발생함

**Describe the solution you'd like**
사용자 이름과 더불어 ID, 이메일 주소, 그룹 등 추가적으로 Identity 를 확인할 수 있는 부가 정보가 표현되어야 함

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang 위의 내용도 간단하게 조정하면 효과를 볼수 있는 기능이라고 생각되는데요. 검토 부탁드립니다.

**Comment by minjung-cho** [comment]
![2019-01-02 12 57 35](https://user-images.githubusercontent.com/28773903/50580080-20350000-0e8e-11e9-86fa-efdfd8ae4c49.png)
@AnnieHwang admin 쪽에 개발되어 있는 유저 정보 팝업을 적용하면 어떨지요? workspace와 management 화면에 적용한다면 view detail 링크는 뺀 상태로 넣어야 할 듯 합니다

**Comment by minjung-cho** [comment]
@Taehui 워크스페이스 소유자의 정보 부분에 'Full name (Username) ' 으로 표기하겠습니다. 필요에 따라서 이메일, 그룹과 같은 정보도 열람하고자 하는 니즈가 있을 것 같습니다만, 사용자 관리 권한이 있는 사람이라면  administration>members 메뉴에서 확인할 수 있습니다.

@koeun222 소유자 정보 부분에 (Username) 이 추가되어서 컬럼 영역 조정이 필요해 보입니다.

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho 사실 목록에 full name 이 표기되면 레이어내 full name 이 있는게 중복 데이터 같은데요. 이메일은 길기만 하고, 의미가 없어보여요. username 만 tooltip 표시하는 방안도 검토가 가능할까요?

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang @minjung-cho 
아래와 같이 보완할까 합니다.
자리가 허용하는 만큼 보조 정보로 Username을 노출하고 문자열이 길 경우 툴팁으로 전체 문자열 노출하면 어떨까 합니다.
![667permission02](https://user-images.githubusercontent.com/42257766/50749811-da5cab00-1284-11e9-8037-530704e8a525.png)
![667permission01](https://user-images.githubusercontent.com/42257766/50749812-da5cab00-1284-11e9-85d6-cccfcea5a7eb.png)

**Comment by AnnieHwang** [comment]
@kyungtaak 현재 개인워크스페이스 명이 'Owner + 워크스페이스'로 구성되어 있어, Owner만 나오는건 중복 되어 보이며, 공간 자체도 여유가 있어 툴팁보다는  Owner (Username)으로 표기하는게 나을 것 같은데 어떻게 생각하시나요?

**Comment by kyungtaak** [comment]
@AnnieHwang 네 좋습니다. 관련해서  기획/디자인을 완료해주시면 개발을 진행하도록 하겠습니다.

**Comment by Taehui** [comment]
@kyungtaak 요 이슈 3.2.0 이전에 빨리 반영이 가능할까요? 매우 불편한 상태라서 지금...권한 줘야할 때마다 DB 업데이트를 치고있는 상황이라;;

**Comment by kyungtaak** [comment]
> 3.2.0 이전에 빨리 반영이 가능할까요?

@Taehui 다음 Iteration에 개발 포함시키도록 하겠습니다.

**Comment by Taehui** [comment]
@kyungtaak 네네, 감사합니다.
