### ISSUE TITLE
overlord helpers framework and tasklog auto cleanup

### ISSUE THREAD

**Issue by seoeun25** [metatron-app/metatron-discovery#674]
**Is your feature request related to a problem? Please describe.**
수동으로 삭제 하지 않는 한 Task log가 계속 log diretory(FileSystem, HDFS, S3 등)에 적재되는 문제가 발생. 

**Describe the solution you'd like**
오래된 task log를 삭제

**Describe alternatives you've considered**

**Additional context**
Druid의 다음 이슈들을 backport
* Backport of #3677 (overlord helpers framework and tasklog auto cleanup)
* Backport of #3670 (reset-cluster command to clean up druid state stored on metadata and deep storage)
* Backport of #3182 (DumpSegment tool)

**Configuration**
common.runtime.properties  에서 수정
- task log clean 기능에 대한 enable 설정
druid.indexer.logs.kill.enabled=true
- task log 유지 기간 설정. in milliseconds 
druid.indexer.logs.kill.durationToRetain=3600000

overlord 콘솔의 recently completed task  리스트는 다음 항목으로 recent 를 정의하여 쿼리 범위를 줄일 수 있다.
overlord/runtime.properties
- 최근 1시간의 completed task를 보고 싶다면
druid.indexer.storage.recentlyFinishedThreshold=PT1H

**Comment by seoeun25** [comment]
@kyungtaak 
1. tasklog cleaner
overlord.log 에서 다음과 같은 메시지 확인. config는 실제 설정값.
```
Scheduling TaskLogAutoCleaner with config [TaskLogAutoCleanerConfig{enabled=true, initialDelay=215051, delay=21600000, durationToRetain=604800000}].
```
2. recentlyFinishedThreshold
recentlyFinishedThreshold를 설정했다면(default를 사용하지 않고) overlord.log 에서 다음과 같은 메시지 확인
```
druid.indexer.storage.recentlyFinishedThreshold: PT72H
```

**Comment by kyungtaak** [comment]
추가로 메타 정보도 삭제할 필요가 있다면 아래와 같은 조건으로 삭제가 필요할것 같습니다.
```
delete * from druid_tasks where active=false and created_data < ‘{yyyy-MM-dd}’
```

**Comment by kyungtaak** [comment]
@seoeun25 지원에 감사드립니다. 현재 수행중인 클러스터에 적용하여 정상동작을 확인하였습니다. 이슈를 종료하겠습니다.
