### ISSUE TITLE
Need to show progress of Druid ingestion

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#687]
**Is your feature request related to a problem? Please describe.**
Datasource detail view must be able to display ingestion log for datasource in preparing status. This will help identify the datasource ingestion state and the cause of the failure. It would be even better if the detail screen shows the progress bar for Druid ingestion.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
@i1befree Beginning with release 3.0.6, we have started to support to display ingestion status. It would be good to check #505  issue. So I will close this issue.
