### ISSUE TITLE
Dataset preview is not displayed

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#701]
**Describe the bug**
Sometimes dataset previews is not displayed.

**To Reproduce**

Case A.
1. Import a csv file to dataset
2. If some rows in the csv has less column than others, the preview is not displayed.

Case B.
1. After import a csv file as dataset.
2. Select created imported dataset in dataset list.
3. In the detail screen, auto heading and typing is not applied.

Case C.
1. Import an excel file to dataset
2. Auto heading and typing is no applied.

**Expected behavior**

**Screenshots**
correct upper 3 problems.

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
Integrated test passed.
