### ISSUE TITLE
Missing message and broken screen error

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#702]
**Describe the bug**
메시지가 정상적으로 표시되지 않거나 화면이 어긋나는 케이스를 수정합니다.

**To Reproduce**
1.  아래의 스크린샷에서와 같이 어긋나는 화면들이 나타납니다.

**Expected behavior**

**Screenshots**
![1](https://user-images.githubusercontent.com/3685833/48182356-37fc7600-e36e-11e8-8224-7d645199a812.png)
![2](https://user-images.githubusercontent.com/3685833/48182358-38950c80-e36e-11e8-951c-db17fd1f603b.png)
![3](https://user-images.githubusercontent.com/3685833/48182360-38950c80-e36e-11e8-8b0f-fa1b407dc242.png)
![4](https://user-images.githubusercontent.com/3685833/48182362-38950c80-e36e-11e8-825e-739ae78f3dbb.png)
![5](https://user-images.githubusercontent.com/3685833/48182363-392da300-e36e-11e8-9170-c59e7d14bc32.png)
![6](https://user-images.githubusercontent.com/3685833/48182364-392da300-e36e-11e8-9f1b-eedd3bb55623.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 70

**Additional context**

**Comment by kyungtaak** [comment]
3.0.6 릴리즈 머지 작업의 Side effect 로 발생한 현상의 이슈로, 수정완료하여 종료하도록 하겠습니다.
