### ISSUE TITLE
Improved Scroll UI usability

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#703]
**Is your feature request related to a problem? Please describe.**
페이지 마다 스크롤 영역이 일관성이 없음
![image 23](https://user-images.githubusercontent.com/6300003/48182896-4cda0900-e370-11e8-82f5-9199faeabe12.png)
![2018-08-29 2 16 04](https://user-images.githubusercontent.com/6300003/48182863-32a02b00-e370-11e8-8d64-f9bd0a7c5ffa.png)
![2018-08-29 2 16 08](https://user-images.githubusercontent.com/6300003/48182867-359b1b80-e370-11e8-8475-17396ea529af.png)
![2018-09-14 2 43 33](https://user-images.githubusercontent.com/6300003/48182870-38960c00-e370-11e8-96d7-05f7dddd64ae.png)
<img width="863" alt="2018-08-30 12 00 34" src="https://user-images.githubusercontent.com/6300003/48182873-3af86600-e370-11e8-9af3-8249e0f73585.png">
<img width="713" alt="2018-08-30 2 01 24" src="https://user-images.githubusercontent.com/6300003/48182875-3d5ac000-e370-11e8-87d8-29e764e5b2b1.png">

**Describe the solution you'd like**
[개선방안. 정책]
1. 내용이 영역을 넘어갈때 스크롤이 생김 
NOTE. 프랩의 데이터플로우 화면과 같은 외부 라이브러리를 사용할 때 특히 유의해 주세요.

2. 화면의 메인 콘텐츠가 박스형인 경우, 화면 크기에 따라 박스 height 가변. 이때, 하단 마진 유지.
NOTE. 박스형 디자인은 데이터 그리드나 컬럼리스트와 같이 표시할 내용이 매우 많아질 수 있는 경우 사용합니다.
NOTE. 단, 박스 하단에 다른 입력 콤포넌트가 있을 경우, 박스의 Height를 min.사이즈가 있고 박스 내용에 따라 가변되도록함 (예.생성 마지막 단계 팝업)

3. 헤더 영역이 사라졌을 때 혼선이 생길 수 있는 경우, 헤더 영역 유지.
NOTE. 테이블의 헤더. 타이틀 영역 등

참고페이지 
https://tde.sktelecom.com/pms/browse/METATRON-1417
https://tde.sktelecom.com/pms/browse/METATRON-1226

**Comment by minjung-cho** [comment]
@eltriny 제 기억으로는 다른 이슈로 인한 개선이 진행되는 화면부터 순차적으로 진행하기로 했던 것 같은데, 잊혀지고 있는 것 같습니다 ^^; 이건은 어떻게 처리하는게 효율적일까요?

**Comment by minjung-cho** [comment]
@kyungtaak 네, 그렇게 하는게 좋을 것 같습니다. 페이지가 많아서 이슈 만들고, 각 화면 담당자 분들이 수고해 주셔야 할것 같네요

**Comment by kyungtaak** [comment]
@eltriny 연관된 4개의 이슈를 확인해주시고요. 금번 Iteration 개발에 얼마만큼 포함이 될수 있을런지 확인 부탁드립니다.
