### ISSUE TITLE
Error in querying a specific column statistics in data source

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#710]
**Describe the bug**
특정 데이터 소스내 컬럼정보 조회시 오류가 발생합니다.

**To Reproduce**
※ 데이터 소스 등록은 기존 엔진에 존재했던 데이터 소스를 discovery 데이터 소스에 import 방식으로 등록함.

1. 데이터 스토리지 > 데이터 소스 관리 >  데이터 소스 상세 조회
2. "Column details" 탭 클릭
3. 특정 컬럼 선택 

**Expected behavior**
- 컬럼 정보가 정상적으로 measure 형태로 저장되고, 컬럼값 통계 조회시 오류가 없어야합니다. 

**Screenshots**
- 실제 엔진(Druid) 내 저장되어 있는 datasource 내 matric 으로 등록되어 있음
![image](https://user-images.githubusercontent.com/822255/48194819-617ac900-e391-11e8-8129-81b8355026a5.png)

- Segmentmeta 조회 결과 columns 속성 정보 오류 내용이 있고, Type 이 STRING 으로 지정됨
![image](https://user-images.githubusercontent.com/822255/48194899-a141b080-e391-11e8-8f68-dd2327b1d8dc.png)

-  데이터 소스를 Import 한후 해당 컬럼 값 조회
![image](https://user-images.githubusercontent.com/822255/48194988-dbab4d80-e391-11e8-8c29-1c4df2c3da93.png)
 

**Desktop (please complete the following information):**
 (N/A)

**Additional context**
(N/A)

**Comment by navis** [comment]
"merge" : false 로 하고 한번 돌려봐 주세요.

**Comment by navis** [comment]
09-01~09-07 에 dimension 으로 들어갔네요. 다른데는 다 double 인데..

**Comment by kyungtaak** [comment]
@alchan-lee 오류가 있는 field 는 저장시 등록은 하되 unloaded 를 true 로 설정하여 처리하는게 좋을것 같네요. 
#777 이슈 참고해주세요. 이슈를 할당 드립니다.

**Comment by alchan-lee** [comment]
fixed in #856
