### ISSUE TITLE
Not show partition keys in datasource create step and detail

### ISSUE THREAD

**Issue by brandon-wonjune** [metatron-app/metatron-discovery#725]
**Describe the bug**
데이터소스 생성시 파티션이 있는경우 생성 마지막 단계와 데이터소스 상세화면에서 설정된 파티션키가 보이지 않습니다

**To Reproduce**
1. stagingDB 데이터소스 생성(생성시 partition key가 있는 데이터로 생성)
2. 생성 완료단계에서 설정된 파티션 키 목록이 나오지 않음
3. 데이터소스 상세화면에서 설정된 파티션 키 목록이 나오지 않음

**Expected behavior**
정상적으로 파티션키 목록이 나와야합니다.

**Screenshots**
![2018-11-09 4 15 12](https://user-images.githubusercontent.com/42233627/48248442-a9095f80-e43a-11e8-9c97-8542df54a10d.png)

**Desktop (please complete the following information):**
test server

**Additional context**

**Comment by ufoscw** [comment]
@brandon-wonjune 
표현 방식은 아래와 같습니다.

```
Response (JSON)
[  
   {  
      "ym":"201704",
      "dd":"20"
   },
  {  
      "ym":"201704",
      "dd":"21"
   }
]
```


```
to String
ym=201704/dd=20
ym=201704/dd=21
```

**Comment by brandon-wonjune** [comment]
![2019-01-07 11 29 22](https://user-images.githubusercontent.com/42233627/50745911-f9047700-126f-11e9-9aec-9fa08b642f6d.png)
수정하였습니다
