### ISSUE TITLE
Add GEO type column when loading datasource

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#728]
**Is your feature request related to a problem? Please describe.**
맵타입(포인트)에 대해서 데이터소스 적재 시 해당 타입의 컬럼을 신규로 추가할 수 있어야 함

- 해당 포인트 데이터 타입은 위도, 경도의 조합으로 이루어짐
- 새로운 컬럼이 추가되는 형태임
- 새로운 컬럼은 컬럼 이름이 바뀔수 있음

**Describe the solution you'd like**
1. + --> X 토글버튼이 있음
1. 새로운 컬럼 만들기 라는 버튼을 누른다
2. 기본적으로 해당 컬럼의 타입은 ‘포인트’타입이다
3. ‘포인트’타입이면.. 위도, 경도를 선택하게 한다
![2018-11-09 7 46 11](https://user-images.githubusercontent.com/28773903/48258704-2217af80-e459-11e8-9e5f-244565b12eee.png)

**Describe alternatives you've considered**
인터랙션은. 워크벤치>변수 추가하는 부분 참고하도록함(이번에 변경되어서 테스트서버2에서 확인가능함)
설정할 값도 많지 않고, 다른 타입 언제 들어올지 몰라서 본격적으로 모달 팝업 쓰는것 보다는 기존에 있는 UI 활용해서 가볍게 가는게 좋을 것 같음

**Additional context**

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유들드려요
![image](https://user-images.githubusercontent.com/42256760/48323334-0a197900-e66f-11e8-9fee-9df2b379b610.png)

**Comment by kyungtaak** [comment]
@AnnieHwang 
- Type 이라는 용어보다는 Method? 이게 낫지 않을까...하는데요.;;;
  : 그리고 종류도 2개로..하는건 어떨까요? Geo Point(기존 Point 에서..), Expression 
    ※ 나중에 실시간 Json 타입일 경우 JsonFlatten 까지 포함하면 좋을것 같아요.
- 좌표계 변환을 지원해야합니다. @navis 님 좌표계 변환을 위한 입력값을 받으려고 하는데요. 혹시 druid 에서 좌표계 지원이 가능한지 알수 있을가요?
- 그리고 기존 WKT type 의 컬럼이 들어오면, 이에 따라 Geo Point, Geo Line, Geo Polygon 설정이 가능한 부분이 있어야합니다.

**Comment by navis** [comment]
일단 latlon 타입에 대해서 crs 값을 넣었습니다. 되는지 확인하고 다른 타입으로 확대하지요.
```json
"strategies": [
 {"type": "latlon", "fieldName": "coord", "latitude": "lat", "longitude": "lon", "crs": "EPSG:4301"},
 {"type": "text", "fieldName": "addr"}
]
```

**Comment by koeun222** [comment]
@AnnieHwang @kyungtaak 수정된 디자인 공유드립니다 
- 헤더영역이 좁아서 'add column' 버튼 우측상단으로 이동
- 추가팝업은 컬럼 리스트에서 밀리는 형태가 리스트를 많이 가리고있어서 팝업으로 수정 
- Expression 추가
![image](https://user-images.githubusercontent.com/42256760/48398310-c3597b00-e763-11e8-944b-4f2a141286c2.png)
![image](https://user-images.githubusercontent.com/42256760/48398336-d3715a80-e763-11e8-9284-036be2da9f76.png)
![image](https://user-images.githubusercontent.com/42256760/48398320-cbb1b600-e763-11e8-8999-24c949cbd97f.png)

**Comment by i1befree** [comment]
사전 준비된 Shape 또는 Geo 정보에 따라 도시 또는 지역명에 따라 자동으로 Geo 값을 추가해 주는 기능을 넣었으면 좋겠습니다.

**Comment by navis** [comment]
geometry 가 차원값은 아닌 것 같은데요..?

**Comment by kyungtaak** [comment]
@navis 현재는 discovery 내부적으로는 차원값으로 처리하고, druid 에 질의할때는 metric 으로 인식하여 전달합니다. 

@i1befree 이번 진행할때는 적재만 고려할 예정이며, 코멘트 주신 방향이 추후 View 와 관련기획이 정리되면 추가 이슈를 통해 진행하도록 하겠습니다. ^^

**Comment by kyungtaak** [comment]
@brandon-wonjune 문서화 이전에 아래 신규 스펙 샘플을 먼저 전달드립니다. 신규로 생성한 내용은 주석을 달아두었으니 참고해주세요. 
```
{
    "name": "localFileIngestion_geo",
    "dsType": "MASTER",
    "connType": "ENGINE",
    "srcType": "FILE",
    "granularity": "DAY",
    "segGranularity": "MONTH",
    "ingestion": {
        "type": "local",
        "path": "/tmp/sample_ingestion_estate.csv",
        "removeFirstRow": false,
        "format": {
            "type": "csv",
            "delimeter": ",",
            "lineSeparator": "\n"
        }
    },
    "fields": [
        {
            "name": "current_time",
            "type": "TIMESTAMP",
            "role": "TIMESTAMP",
            "seq": 0,
            "format": {
                "type": "time_temporary"
            },
            "derived": true           // 원본상 물리 컬럼에 포함되지 않고, 임의로 생성된 컬럼임을 표시
        },
        {
            "name": "idx",
            "type": "STRING",
            "role": "DIMENSION",
            "seq": 1
        },
        {
            "name": "gu",
            "type": "STRING",
            "role": "DIMENSION",
            "seq": 2
        },
        {
            "name": "py",
            "type": "DOUBLE",
            "role": "MEASURE",
            "seq": 3
        },
        {
            "name": "amt",
            "type": "DOUBLE",
            "role": "MEASURE",
            "seq": 4
        },
        {
            "name": "x",
            "type": "DOUBLE",
            "role": "DIMENSION",
            "unloaded": true,
            "seq": 4
        },
        {
            "name": "y",
            "type": "DOUBLE",
            "role": "DIMENSION",
            "unloaded": true,
            "seq": 4
        },
        {
            "name": "addr",
            "type": "STRING",
            "role": "DIMENSION",
            "seq": 5
        },
        {
            "name": "location",
            "type": "STRUCT",
            "logicalType": "GEO_POINT",
            "role": "DIMENSION",
            "seq": 4,
            "ingestionRule": {          // 컬럼 생성 Rule 지정
                "type": "geo_point",   
                "latField": "y",
                "lonField": "x"
            },
            "format": {                 // GEO Type 임을 지정
                "type": "geo_point",    // geo_point, geo_line, geo_polygon
                "dataType": "STRUCT"    // STRUCT, WKT
                "originalSrsName": null // 원본 좌표계 명 지정, discovery 내 제공하는 표준좌표와 다를 경우 지정
            },
            "derived": true           // 원본상 물리 컬럼에 포함되지 않고, 임의로 생성된 컬럼임을 표시
        }
    ]
}
```

**Comment by brandon-wonjune** [comment]
@kyungtaak 
Q1. GEO_POINT로 생성한 컬럼에 대해서는 아래와 같이 전달하는것은 이해했습니다.
```
{
            "name": "location",
            "type": "STRUCT",
            "logicalType": "GEO_POINT",
            "role": "DIMENSION",
            "seq": 4,
            "ingestionRule": {          // 컬럼 생성 Rule 지정
                "type": "geo_point",   
                "latField": "y",
                "lonField": "x"
            },
            "format": {                 // GEO Type 임을 지정
                "type": "geo_point",    // geo_point, geo_line, geo_polygon
                "dataType": "STRUCT"    // STRUCT, WKT
                "originalSrsName": null // 원본 좌표계 명 지정, discovery 내 제공하는 표준좌표와 다를 경우 지정
            },
            "derived": true           // 원본상 물리 컬럼에 포함되지 않고, 임의로 생성된 컬럼임을 표시
        }
```
그런데 여기서 위 UI는 실제 있는 컬럼을 선택하는 란(latitude column, longitude column)이 있는데 그것은 어떤 프로퍼티로 전달하면 되나요?

Q2. 앞으로 current_time으로 임의로 생성한 컬럼은 `derived`를 true로 전달하면 되나요?

Q3. Expression에 대해선 어떤 형태로 전달해야 되나요?

**Comment by kyungtaak** [comment]
@brandon-wonjune 
Q1.  "add Column" ingestionRule 과 연관이 있습니다. 따라서, latField <-> latitude, lonField <-> lonField 로 매핑해주시고요. method "point" 는 geopoint,  이고, 아래 처럼 method "expression" 은 "user_defined" 로 지정해주시면 됩니다.
```
{
  "type": "user_defined",   
  "expr": "test+'a'"
}
```
Q1-1, 좌표계 선택항목은 EPSG:4326 (기본값), EPSG:4301 두가지로 해주세요. 이것은 originalSrsName 에 입력해주세요. 데이터 타입은 무시해주세요.

Q2. 네 원본의 물리적인 컬럼이 아닌 컬럼은 무조건 derived 를 true 로 지정하도록 합니다.

Q3. 의 경우는 Q1 에서 답변을 드린것 같습니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak 네 답변주신대로 반영하겠습니다.

- GEO 인경우 
```
{
            "name": "location",
            "type": "GEO_POINT",  // GEO_POINT, GEO_LINE, GEO_POLYGON
            "logicalType": "GEO_POINT",  // GEO_POINT, GEO_LINE, GEO_POLYGON
            "role": "DIMENSION",
            "seq": 4,
            "ingestionRule": {
                "type": "geo_point",    // geo_point, geo_line, geo_polygon
                "latField": "y",
                "lonField": "x"
            },
            "format": {                
                "type": "geo_point",    // geo_point, geo_line, geo_polygon
                "originalSrsName": "EPSG:4326" // EPSG:4326, EPSG:4301
            },
            "derived": true
        }
```

- expression 인경우
```
{
            "name": "location",
            "type": "STRING", 
            "logicalType": "STRING",
            "role": "DIMENSION",
            "seq": 4,
            "ingestionRule": {
               "type": "user_defined",   
                "expr": "test+'a'"
            },
            "derived": true
 }
```

**Comment by brandon-wonjune** [comment]
@kyungtaak 
ingestionRule 지정시 문의사항입니다.
위에서 두 가지 대해서는 ingestionRule의 type 이 geo_point와 user_defined로 적용이 되는데요
기존의  missing에 대해서 아래의 화면에서 ingestionRule의 type에 대해 설정하고있습니다.
그래서 위 두가지로 생성된 컬럼에 대해서는 missing쪽에서 맞는 type이 없어서 error가 발생하는데요.
missing을 hide시키면 될까요?
![2018-11-20 4 53 30](https://user-images.githubusercontent.com/42233627/48758999-29567d00-ece5-11e8-8cd4-b41f3c1b6a23.png)

**Comment by kyungtaak** [comment]
@brandon-wonjune 일부 도메인 스펙을 변경합니다. 필드를 추가하는 케이스는 derivationRule 속성을 활용하도록 합니다. 
```
{
    "name": "location",
    "type": "STRUCT",
    "logicalType": "GEO_POINT",
    "role": "DIMENSION",
    "seq": 4,
    "derived": true,
    "derivationRule": {
        "type": "geo_point",
        "latField": "y",
        "lonField": "x"
    },
    "ingestionRule": {
        "type": "discard"
    },
    "format": {
        "type": "geo_point",
        "originalSrsName": "EPSG:4326"
    }
}
```

**Comment by brandon-wonjune** [comment]
@deidera08 수정하였습니다.
![2018-11-23 3 41 32](https://user-images.githubusercontent.com/42233627/48931372-4e432e00-ef39-11e8-92eb-71a6741510e3.png)
![2018-11-23 3 41 38](https://user-images.githubusercontent.com/42233627/48931373-4e432e00-ef39-11e8-9334-65078bbfd232.png)

**Comment by brandon-wonjune** [comment]
@kyungtaak 
GEO_* 형태의 logicalType의 경우 stats api조회와 stats를 사용하는 UI를 hide 시켰습니다.
![2018-11-23 6 06 12](https://user-images.githubusercontent.com/42233627/48935685-d7636080-ef4b-11e8-9f9a-741e8c379edf.png)
