### ISSUE TITLE
When api to find filter entry call fails, the dashboard stops load

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#732]
**Describe the bug**
필터 항목 찾기 호출(Cadidate API) 오류 시 스크립트 오류로 대시보드 로드가 중단되는 현상이 발생됩니다.

**To Reproduce**
1. Go to Dashboard in [Dev Site](http://52.231.184.135:8180/app/v2/workbook/659b7b33-a8dc-4943-a48b-8e04e36df996)
2. See error

**Expected behavior**
대시보드 구성 중 오류 발생에 대해 사용자에게 알려주어야합니다. 

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/48310788-0555b600-e5d8-11e8-83d4-b756b2732f18.png)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
@metatron-app/design 대시보드 로드시 위젯 별 오류 표시 방법이 있는데요. 필터 호출이나 예상치 못한 대시보드 로드 오류 표시 방법이 있다면 가이드 부탁드립니다.

**Comment by kyungtaak** [comment]
@metatron-app/design  @AnnieHwang 위젯 내부가 아닌 대시보드 구성시 예상치 못한 오류가 발생하였을 경우 표시할수 있는 방안에 대해 답변 부탁드립니다.

**Comment by minjung-cho** [comment]
Failed to load dashboard 상황에 대한 간단한 이미지가 필요할 것 같습니다.

**Comment by kyungtaak** [comment]
@minjung-cho 현재는 스크립트 오류인지..api 오류후 아무것도 표현이 되지 않습니다. 순서가 어떻게 되는지 모르겠지만, global filter candidate api 를 호출하다 오류가 난것 같은데요. 먼저 @eltriny 호출순서가 어떻게 되는지 확인이 필요합니다.

**Comment by eltriny** [comment]
@kyungtaak 
필터들에 대한 설정 먼저 진행하고 위젯 설정을 진행합니다. 
필터 설정 과정에서 오류가 발생하여 위젯 설정이 이루이지지 않은 상태입니다.

필터 설정에 오류가 발생해도 위젯은 표시되도록 수정하고, 그 외에 대시보드 자체를 그릴 수 없는 상황에 대해서는 @minjung-cho 말씀대로 오류 이미지를 표시하는것으로 처리하겠습니다.

**Comment by minjung-cho** [comment]
@kyungtaak @eltriny님과 아래와 같이 처리하는 것으로 의논했는데, 어떠신지요? 
1. 필터 오류가 있을 때, 위젯 배치를 보여주고 문제가 되는 위젯에 #733 과 같이 처리합니다. 디자인은 위젯 중 필터와 매개변수 아이콘이 추가되어야 합니다.
![2018-11-20 2 20 07](https://user-images.githubusercontent.com/28773903/48753719-66654400-ecd2-11e8-9667-0fab3a7ab8f0.png)
2. 알 수 없는 이유로 대시보드를 그릴 수 없는 상황
![2018-11-20 2 46 49](https://user-images.githubusercontent.com/28773903/48753922-310d2600-ecd3-11e8-8ad2-10cd36144a59.png)

**Comment by kyungtaak** [comment]
@minjung-cho 네 이대로 진행하면 좋을것 같습니다.
