### ISSUE TITLE
When api to search data for widget call fails, edit button in widget not worked.

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#733]
**Describe the bug**
열람 모드 내 widget 구성중 searh api 호출시 오류가 발생한 후, 위젯 편집화면으로 이동하려고 위젯내 편집 버튼이 동작하지 않습니다. 편집 모드에서의 위젯내 편집 버튼은 제대로 동작합니다. 

**To Reproduce**
1. Go to Dev Dashabord [Link](http://52.231.184.135:8180/app/v2/workbook/6f9b8a81-6e45-471a-8265-26c6ce8431c0)

**Expected behavior**
열람 모드내 위젯 구성 중 오류 발생시 편집모드 동작을 활성화 해야합니다. 
또한 위젯 매뉴에 대한 enable/disable 조정이 필요합니다. (ex. 편집 모드만 활성화)
※ 추가 : 오류 메시지 처리 포함

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/48311044-726b4a80-e5dc-11e8-89c6-6f82f284d60b.png)

**Desktop (please complete the following information):**
 (환경 영향은 없음)

**Additional context**
@metatron-app/design  팀의 검토가 필요합니다. 확인 부탁드립니다.

**Comment by eltriny** [comment]
@minjung-cho @AnnieHwang

**Comment by kyungtaak** [comment]
@minjung-cho 
> 데이터소스 문제로 차트가 그려지지 않는 상황에서는 지금과 같이 모든 버튼이 안보여도 됩니다.

첫번째 @eltriny 님께 가이드한 내용중에 데이터 소스 문제라는 에러를 내기 참 어려워요. 그냥 오류가 나면 모든 경우 편집 버튼만 활성화 되는게 나을것 같습니다. 

그리고, 예상치 못한 오류가 있을수 있어 
적재쪽에서 보이는 "details" 같은 버튼이 있어.. 일단 접고 펴면 확인할수 있는게 깔끔할것 같기도해요. (팝업은 너무 클것 같아..두렵습니다.)

**Comment by minjung-cho** [comment]
@kyungtaak 
네 @eltriny 님과 에딧 버튼에 대해서 케이스 나누지 않기로 얘기했습니다

현재 디자인에서는 에러 메시지 영역이 확장되는 것은 메시지 영역을 확보하기 어려울 것 같아서, 위젯 영역 전체에 레이어드 되는 팝업으로 고민하고 있습니다. 디자인 시안 올리고 검토 요청드리겠습니다

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/48539102-8fb05980-e8f9-11e8-82f0-6a9f60addb01.png)
![image](https://user-images.githubusercontent.com/42256760/48539152-af478200-e8f9-11e8-9d14-09142bdefc8f.png)
@AnnieHwang 디자인 공유드립니다 error message가 더 길어지면 영역안에서 스크롤됩니다

**Comment by kyungtaak** [comment]
@minjung-cho 디자인까지 나왔는데 죄송하지만, 굳이 에러코드를 밖에 내보내는건 부담되지 않을까요? 에러코드별로 뭔가 다른메시지 또는 다른 이미지 아이콘이 나와야 좀더 사용자 친화적이 되지 낳을까 싶습니다. 그러지 않을바에 아이콘을 누르면 상세한 정보가 나타난다던지 하는게 필요할것 같아요.

**Comment by minjung-cho** [comment]
@eltriny @koeun222 에러코드를 전면에 노출하지 않는 것이 좋을 것 같아서, 'Error code:000 >' 이부분을 'Error details>' 로 변경 부탁드립니다!

**Comment by koeun222** [comment]
![Uploading image.png…]()
![image](https://user-images.githubusercontent.com/42256760/48681453-dc3fb180-ebe5-11e8-9193-d2c70ae2055d.png)
@minjung-cho @AnnieHwang  수정안 공유드립니다

**Comment by kyungtaak** [comment]
@minjung-cho 기획안에는 위젯내 에러메시지를 덮는 화면내 "X" 표시가 있는데요. 디자인 안에는 없습니다. 실제 구현도 그렇고요. 어떤게 맞나요?

@eltriny @minjung-cho 실제 위젯 편집창에는 에러메시지가 표출이 안되던데요. 여기도 신경을 써야할듯합니다.
일단 토스트창으로 이번 릴리즈에서 처리하고 추후 별도 기획후 진행하는것으로 하면 좋을것 같은데요. 두분다 확인부탁드립니다.
(에러 케이스 는 #831 PR 에 보강해 두겠습니다.)

**Comment by minjung-cho** [comment]
@kyungtaak 네, 위젯에서 에러 케이스 표시에 대한 내용 확인했습니다. 기획 진행 후 검토 요청드리겠습니다-

**Comment by AnnieHwang** [comment]
@eltriny 지금 에러 상황 시에 Edit 버튼만 있는게 다소 어색해보이고, 에러 상황에서도 information과 확장 버튼은 필요한것 같아 수정을 요청드립니다.

![image 32 32](https://user-images.githubusercontent.com/6300003/48925969-f1ca1980-ef0c-11e8-85e1-254fd45e4651.png)

![pasted_image_at_2018-11-23__10_01_am](https://user-images.githubusercontent.com/6300003/48925952-dced8600-ef0c-11e8-9cd9-625c12937bd7.png)

너무 늦게 알려드려서 죄송합니다.
