### ISSUE TITLE
Add custom properties in DataConnection 

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#738]
**Is your feature request related to a problem? Please describe.**
데이터 커넥션의 종류도 다양하고 해당 커넥션에 대한 별도의 액션에 대한 요구도 다양합니다. 
이를 모든 Data Connection 정보 화면내 담아 내기 어려워 각 커넥션별로 처리가능한 옵션에 대해 추가 할수 있도록 구성합니다. 

**Describe the solution you'd like**
- DataConnection 등록/수정/조회 화면내 Custom Property 를 입력/조회할수 있는 화면을 제공합니다.
  @metatron-app/design 검토 부탁드립니다.
- DataConnection 에 Custom Property 의 종류는 두가지로 제한합니다. (Rule
  : JDBC 자체 속성 처리 (native.xxxx.xxx ) 
  : metatron 내 자체 속성 처리 (metatron.xxxx.xxx. ex. 커넥션 관리자의 요구로 특정 database 숨김)

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang 위 내용에 대해 예전에 논의했던 바 있었던것 같은데요 혹시 디자인이나 기획된 사항이 있으면 공유 부탁드립니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
DataConnection에 properties 속성이 추가되었습니다.

1. DataConnection 등록
```
(POST) /api/connections

request sample
{  
   "authenticationType":"MANUAL",
   "implementor":"MYSQL",
   "username":"polaris",
   "password":"polaris",
   "hostname":"localhost",
   "published":true,
   "name":"mysql_custom",
   "type":"JDBC",
   "port":"3306",
   "properties" : {
      "native.socketTimeout" : "5000",
      "native.connectTimeout" : "10000",
      "metatron.excludeTable" : "aaa,bbb"
   }
}
```

2. DataConnection 상세조회
```
(GET) /api/connections/{connectionId}?projection=default

response sample
{
    "name": "mysql_custom",
    "properties": {
        "native.socketTimeout": "5000",
        "native.connectTimeout": "10000",
        "metatron.excludeTable": "aaa,bbb"
    },
    "id": "a2486e8b-7608-40aa-906a-15f47a573025",
    "type": "JDBC",
    "port": "3306",
    "hostname": "localhost",
    "authenticationType": "MANUAL",
    "username": "polaris",
    "createdTime": "2018-11-13T06:18:36.000Z",
    "createdBy": {
        "type": "user",
        "username": "admin",
        "fullName": "Administrator",
        "email": "admin@metatron.com"
    },
    "linkedWorkspaces": 0,
    "published": true,
    "implementor": "MYSQL",
    "modifiedTime": "2018-11-13T06:18:36.000Z",
    "modifiedBy": {
        "type": "user",
        "username": "admin",
        "fullName": "Administrator",
        "email": "admin@metatron.com"
    },
    "password": "polaris",
    "_links": {
        "self": {
            "href": "http://localhost:8180/api/mySQLConnection/a2486e8b-7608-40aa-906a-15f47a573025"
        },
        "mySQLConnection": {
            "href": "http://localhost:8180/api/mySQLConnection/a2486e8b-7608-40aa-906a-15f47a573025{?projection}",
            "templated": true
        },
        "workspaces": {
            "href": "http://localhost:8180/api/mySQLConnection/a2486e8b-7608-40aa-906a-15f47a573025/workspaces"
        },
        "dataSources": {
            "href": "http://localhost:8180/api/mySQLConnection/a2486e8b-7608-40aa-906a-15f47a573025/dataSources"
        },
        "workbenches": {
            "href": "http://localhost:8180/api/mySQLConnection/a2486e8b-7608-40aa-906a-15f47a573025/workbenches"
        }
    }
}
```

**Comment by brandon-wonjune** [comment]
@ufoscw @metatron-app/design 
질문이 있습니다.

1. properties에 대한 validation은 따로 필요하지 않은가요?
(ex. key와 value가 모두 있어야 함)

2. 위의 화면은 데이터커넥션 생성/수정에 대한 화면인데요
`데이터소스> 생성화면` 과 `메타데이터>hive연결 화면`에도 커넥션 데이터를 확인하는 화면이 있는데 이 화면도 동일하게 적용되는건가요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
1. key나 value 둘중 하나만 입력은 불가능합니다. 
2. 예로 들어주신 데이터소스> DB생성 화면 과 메타데이터>hive생성 화면 은 DataConnection 생성과 동일한 UI 컴퍼넌트 사용하나요?

**Comment by brandon-wonjune** [comment]
@ufoscw 완전히 동일한 컴포넌트를 사용하지는 않습니다.
이 화면에서는 표시하지 않으면 될까요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
네 adhoc 한 화면에서는 해당 옵션의 사용성이 크게 필요하지 않아서 생략하겠습니다.

**Comment by brandon-wonjune** [comment]
@metatron-app/design 
property key 중 중복되는 key가 존재하는 경우 따로 표시를 해줘야되나요?

**Comment by brandon-wonjune** [comment]
@ufoscw 질문있습니다.
1. 처음 커넥션 생성시 property를 입력하지 않아도 파라메터에 값을 던져야되나요?
(ex. property: {})
2. 커넥션 수정시 기존의 프로퍼티가 존재하고있었는데 (ex. "properties": {"native.socketTimeout": "5000", })
여기서 프로퍼티를 제거하고 커넥션 수정을 요청할때는 `property: {}`라고 파라메터에 요청하면 되나요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
1. 큰 상관없을 것 같습니다. 
2. properties는 Map 타입이라 method를 patch가 아닌 put으로 보내야 합니다.
method를 put으로 바꾸면  connection parameter 그대로 저장됩니다.

**Comment by brandon-wonjune** [comment]
@ufoscw 
기존에 수정시 변경된 파라메터만 전달해서 patch를 사용하고있었는데요
properties 수정시에는 모든 커넥션 정보와 함께 put으로 전달해야되나요?

**Comment by ufoscw** [comment]
@brandon-wonjune 
네 put으로 변경하면 모든 정보가 파라미터에 포함되어야 합니다.

**Comment by deidera08** [comment]
@brandon-wonjune 
1. validation check
  : UI단에서 이뤄지는 중복체크이기 때문에 validation check는 key input창에서 focus out시 체크하는것으로 부탁드립니다.
  : 기존의 입력 key 문자열과 비교되기 때문에 사실상 두번째 key부터 validation check가 이뤄집니다.
  : key, value값 모두 있어야하며, 한쪽이라도 값이 없을 경우 required 체크가 필요합니다.
  : 공백문자열(empty)는 허용하지 않습니다.

2. custom property에 물음표 아이콘 hover시 안내문구
  : 해당 문구는 준비중입니다. 현재는 문구가 없으므로 물음표 아이콘을 hide시켜주세요
(문구를 마련하는대로 정리해서 드리겠습니다)

**Comment by brandon-wonjune** [comment]
@deidera08 
property validation check 를 focusout시 체크하는것으로 변경하였습니다.
property에 대한 아이콘을 hide 시켰습니다.

**Comment by ufoscw** [comment]
@AnnieHwang @brandon-wonjune 
네. 중복키어도 크게 문제 없을것 같습니다.

**Comment by brandon-wonjune** [comment]
@AnnieHwang @ufoscw 그러면 특수문자만 허용하지 않도록 하면될까요?

**Comment by ufoscw** [comment]
@brandon-wonjune @AnnieHwang 
죄송합니다. Connection Property는 Map이라서 중복키는 허용이 안될것 같습니다.
특수문자는 escape만 하면 크게 문제 없어 보이는데요. 이건 좀더 확인 후 다시 말씀드릴게요.

**Comment by ufoscw** [comment]
@brandon-wonjune 
특수문자, 중복키 모두 막아주시고 개발 진행하시면 될듯 합니다.
이 이슈 작업 후 #744를 이어서 진행해야 하므로 진행상태 확인 부탁드려요.

**Comment by brandon-wonjune** [comment]
@ufoscw 
property key 에서 .(dot)을 제외한 특수문자, 중복키를 막았습니다.
현재 작업이 끝난상태고 남은것은 프로퍼티 키에 대한 가이드 문구(?아이콘 hover시 나오는 문구)만 남은상태입니다.
가이드 문구는 아직 전달받지 못했습니다.

**Comment by ufoscw** [comment]
@brandon-wonjune 
가이드 문구는 전달 받은 후 추가하기로 하고 PR 오픈 해주시면 될것 같습니다.

**Comment by brandon-wonjune** [comment]
@ufoscw
focusout을 거치지 않고 Done버튼을 누를경우 validation이 체크가 되지 않던 문제와 기존 PUT을 사용하던 것을 PATCH로 사용하도록 수정하였습니다. 
PR 재오픈하겠습니다
