### ISSUE TITLE
URI Format Adress Not Seen Consistently in the Data Connection List

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#740]
**Describe the bug**
If Data Connection Address is entered in URI format, Link(URI Link, Blue color) is displayed in List.

**To Reproduce**
1. Create Data Connection with URI formed address
2. Go to Data Storage -> Data Connection
3. See link in the list

**Expected behavior**
The URI-formatted Adress must also be viewed consistently in the Data Connection List (even if the link does not work)

**Screenshots**
See the following screenshot with jdbc:presto://172.27....
![metatron discovery 2018-11-12 09-19-49](https://user-images.githubusercontent.com/10334774/48320389-0b41aa80-e65d-11e8-93da-9a02f5b2472e.png)

**Desktop (please complete the following information):**
 - Tmap DEV 20181110 Version

**Comment by ufoscw** [comment]
@AnnieHwang 
클릭시 실제 링크 여부와 관계없이 URI 포맷은 파란색 텍스트가 공통정책인지 확인 바랍니다.

**Comment by deidera08** [comment]
@AnnieHwang @ufoscw 
URL 연결로 될 필요는 없어보입니다.

@eltriny 순수하게 텍스트로 노출시켜주세요(링크 제거)

**Comment by brandon-wonjune** [comment]
![2019-01-07 2 33 51](https://user-images.githubusercontent.com/42233627/50750666-45a87c00-1289-11e9-970a-28fb9ebacfa4.png)

텍스트로 표시되도록 수정하였습니다
