### ISSUE TITLE
Add clean menu in context menu

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#747]
**Is your feature request related to a problem? Please describe.**
Add `clean` option  in context menu. Clean has two sub buttons missing and mismatch. 

**Describe the solution you'd like**
Event when gauge bar isn't clicked, allow user to easily add rule about mismatched or missing value.
![image](https://user-images.githubusercontent.com/42233517/48335772-0c48fb00-e6a2-11e8-8c14-6c99f0f8532e.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by ecoloy** [comment]
@paigechoi 
On the new storyboard above, action for 'replace/fill with custom value' menu is not a replace rule but a set rule. Sorry.
