### ISSUE TITLE
Show rule in colour red when rule is broken (dataflow panel)

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#749]
**Describe the bug**
In dataflow panel, even when rule is broken, colour is black

**To Reproduce**
Go to dataflow main grid -> make broken rule -> click done and move to dataflow detail -> click on 
edited wrangled dataset -> see error

**Expected behavior**
When rule is broken, broken rule colour should be red. (Same as dataflow main grid rule list)

**Screenshots**
![image](https://user-images.githubusercontent.com/42233517/48336998-0d2f5c00-e6a5-11e8-8a7e-8f39e5891575.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
Passed (integrated test)
