### ISSUE TITLE
Show snapshot type in list and detail page

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#750]
**Describe the bug**
Show snapshot type (Local, HDFS, StagingDB) in snapshot list and in snapshot detail popup.

**To Reproduce**
1. Go to snapshot tab -> See error
2. Go to snapshot detail popup -> See error

**Expected behavior**
User should be able to see the type of snapshot 

**Screenshots**
![image](https://user-images.githubusercontent.com/42233517/48337739-220cef00-e6a7-11e8-86ce-e60ff167f01f.png)
![image](https://user-images.githubusercontent.com/42233517/48337751-2fc27480-e6a7-11e8-8673-e0a6ea27db4c.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
I will make the data snapshot list to contain snapshot types.

_Data snapshot list에 snapshot type을 내리는 작업을 하겠습니다._

**Comment by joohokim1** [comment]
Works done. Changed the assignee.
