### ISSUE TITLE
Add API to handle status and options for real-time ingestion

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#752]
**Is your feature request related to a problem? Please describe.**
현재 실시간 데이터소스 관련하여 API 가 제공되지만, 엔진의 Real-Time Task를 확인할 상태 정보를 확인할수 없습니다. 
또한  configuration (ioConfig/tuningConfig) 정보가 제한적으로 이를 추가할 필요가 있습니다.

**Describe the solution you'd like**
- 엔진에서 제공하는 API / Configuration 를 Wrapping 하여 처리합니다. 
※ 참고링크 : http://druid.io/docs/latest/development/extensions-core/kafka-ingestion

- 지원 가능한 IO/Tuning Configuration 추가 

**Describe alternatives you've considered**
(N/A)

**Additional context**
기존 제공된 옵션 정보가 변경되는 부분에 대한 하위 호환성을 고려합니다.

**Comment by AnnieHwang** [comment]
@kyungtaak 혹시 실시간으로 만들어진 데이터소스 상세 화면을 볼 수 있을까요? 저희가 기획이 안된 내용이라 어떻게 구현되었는지 확인이 안되서요. 해당 내용 확인되면 그 안에 위에 주신 링크 참고해서 설정 UI를 추가하도록 하곘습니다.

**Comment by kyungtaak** [comment]
@AnnieHwang 테스트 서버에 준비해놓겠습니다.
