### ISSUE TITLE
display partition totalSize in partition validation result view.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#753]
**Is your feature request related to a problem? Please describe.**
display partition totalSize in partition validation result view.

**Describe the solution you'd like**
display total size after num rows.
ex) part_hour=2018111309 (7 rows / 5,854,123 bytes) or part_hour=2018111309 (7 rows / 5.8 MB)
<img width="961" alt="devtools_-_172_27_106_146_11000_app_v2_management_storage_datasource_ _metatron_discovery" src="https://user-images.githubusercontent.com/3770446/48384878-9be8bb00-e72f-11e8-80bd-b3e04aa1b256.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by brandon-wonjune** [comment]
f#753-fix_partition_size_in_result_view 브렌치 생성하였습니다

**Comment by ufoscw** [comment]
@brandon-wonjune 
hive 테이블의 통계 계산이 지연될수도 있기 때문에 해당값이 null이나 undefined 일수 있습니다.
이럴경우 에러나지 않도록만 작업되면 될것 같습니다. 이럴경우 0으로 표시하지 말고 아래처럼 표시되어야 합니다.
ex : part_hour=2018111309 ( rows / bytes)
