### ISSUE TITLE
empty message in ingestion details

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#755]
**Describe the bug**

**To Reproduce**
1. 데이터소스를 생성합니다.
2. 데이터소스 생성이 실패한 데이터소스의 상세 화면에서 적재에 대한 상세 로그를 확인합니다.
3. 아무런 내용이 표시되지 않습니다.

**Expected behavior**
실패에 대한 내용이 표시되어야 합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/3685833/48387203-27fee080-e738-11e8-983c-d7ab4a8f2bc3.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 70

**Additional context**

**Comment by kyungtaak** [comment]
> @kyungtaak
> 위쪽의 history는
> 만약 초기에 historyId를 조회할때 history가 있다면 그 내부에있는 message와 cause를 주면되고
> historyId가 없다면 webSocket 통신중 fail이 났을때 results에 있는 history 내부의 message 와 cause를 주면 되는건가요?

네 맞습니다.
