### ISSUE TITLE
excution time is wrong when query executes using retrying button

### ISSUE THREAD

**Issue by eldorado0402** [metatron-app/metatron-discovery#762]
**Describe the bug**
excution time is wrong when query executes using retrying button. excution time is not update. 
**To Reproduce**
1. Go to 'workbench'
2. execute query
3. cancle
4. excute query againg using retrying button

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kyungtaak** [comment]
@ufoscw 위의 이슈 확인 부탁드립니다.

**Comment by ufoscw** [comment]
@eldorado0402 
제가 테스트한 내용과는 조금 다른데 확인 부탁드려요.
제가 테슽해보니 취소 후 재시도할 경우 완료 후에도 Running 숫자가 계속 증가되는데...
적어주신 내용은 숫자가 갱신이 안된다고 되어 있네요.

**Comment by eldorado0402** [comment]
네 이전에 실행한 실행 타임에서 계속 증가가 되는 현상이 맞습니다
