### ISSUE TITLE
Save Chart Image - not working

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#766]
**Describe the bug**
Save Chart Image 기능이 동작하지 않음

**To Reproduce**
차트 상에서 save chart image를 누름

**Comment by kyungtaak** [comment]
@jeongeunkwon 과거 버젼 내부 관련 옵션 처리시 side effect 로 발생한 사항으로 판단됩니다. 3.0.7 에서는 재현되지 않으니 확인 부탁드립니다.
