### ISSUE TITLE
ToolTip error in line chart

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#769]
**Describe the bug**
툴 팁 상에 동일 잘못된 항목이 추가로 표기됨

**To Reproduce**
1. bar chart 생성
2. bar chart를 line chart로 변경
3. 툴팁에서 표시 레이블을 모두 uncheck
4. 잘못된 값이 표시됨

**Expected behavior**

**Screenshots**
카테고리명, 시리즈명, 시리즈값 표시한 상태로, 
sum of uv가 두개 표시되며, 두개의 값이 다름
<img width="903" alt="2018-11-14 1 33 55" src="https://user-images.githubusercontent.com/44457771/48460511-9ca64d80-e812-11e8-880d-08668ccc5364.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 70.0

**Comment by juheeko9** [comment]
629번 이슈와 동일한 이슈로 629 이슈에서 처리하겠습니다.

**Comment by kyungtaak** [comment]
@jeongeunkwon #629 이슈는 처리되었습니다. 관련 수정내용 확인해주시고요. 확인이 되셨으면 이슈 종료부탁드립니다.
