### ISSUE TITLE
Delete snapshot results when snapshot cancelation requested

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#770]
**Is your feature request related to a problem? Please describe.**
Sometimes, canceling snapshot creation fails because snapshot has already been created.

**Describe the solution you'd like**
When the unwanted snapshot has been created, then just delete it.

**Describe alternatives you've considered**
-

**Additional context**

**Comment by joohokim1** [comment]
Integrated test passed.
