### ISSUE TITLE
hive table constraint for creating data source

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#771]
**Is your feature request related to a problem? Please describe.**
Hive 테이블을 orc로 생성하지 않은 경우, 데이터소스 생성이 실패하는 경우 있음

**Describe the solution you'd like**
데이터소스 생성 가능한 hive 테이블의 orc 관련 제약조건 문의

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
stageDB 모드로 적재시 현재 hive table 내 orc/csv 타입인 경우만 처리가 됩니다. 나머지 형식에 대해서는 추가로 검토하여 진행할 예정입니다.
