### ISSUE TITLE
fix auto complete in command

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#774]
**Describe the bug**
fix auto complete of command in case of typing in Hangul

**To Reproduce**
1. menu MANAGEMENT>Data Preparation>Dataflow 
2. click Wrangled Data
3. click Wrangled dataset > click Edit Rules
4. typing in Hangul at command input   ㄱㄷ,ㅇㄱ

**Expected behavior**
ㄱㄷ -> rename 
ㅇㄱ -> drop

**Comment by joohokim1** [comment]
Integrated test passed.
