### ISSUE TITLE
Multi-column split and extract on dataprep

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#790]
**Is your feature request related to a problem? Please describe.**
Currently, split and extract rules can be applied to only one column at a time.

**Describe the solution you'd like**
Allow multiple column as a target column parameter for split/extract rules.
Delete original columns after split rule applied.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by mh0203** [comment]
UI work repquests
1. Allow multi column select for Split rule
2. Allow multi column select for Extract rule
3. Check rule editng for split and extract

Rule examples
1) split col: column1, column2 on: '-' limit : 2 ignoreCase: false
2) extract col: column2, column3 on: /[a-z]+/ limit : 2 ignoreCase: false

**Comment by joohokim1** [comment]
Integrated test 1 passed

**Comment by joohokim1** [comment]
Integrated test 2 passed
