### ISSUE TITLE
When you add a filter in the dashboard, no custom columns should appear.

### ISSUE THREAD

**Issue by steve-kyungjin** [metatron-app/metatron-discovery#792]
**Describe the bug**
대시보드에서 필터 추가시 사용자 정의 컬럼이 표현되지 않아야 한다.

**To Reproduce**
1. 대시보드에서 사용자 정의 Dimension 추가해서 차트를 그린다.
2. 대시보드 편집화면에서 필터 추가 버튼을 누른다.
3. 필터 리스트에 사용자 정의 컬럼이 목록에 나타나 해당 컬럼 클릭시 오류 발생

**Expected behavior**
필터 목록에서 사용자 정의 목록이 나타나지 않아야 한다.

**Screenshots**
![image](https://user-images.githubusercontent.com/42233760/48554425-b4b8c280-e921-11e8-8462-56398700e301.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by AnnieHwang** [comment]
못올리게 하는건 아닌것 같고(지금도 잘쓰고 있어서요) 버그를 패치해야 할것 같아요~

**Comment by alchan-lee** [comment]
@steve-kyungjin 
현재 버전에서는 재현이 되지 않는듯 한데요,
혹시 재현 가능한 조건을 더 상세히 제공해주실수 있으신지요?

**Comment by steve-kyungjin** [comment]
재현되지 않아 Close 합니다.
