### ISSUE TITLE
Fail to edit split rule

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#798]
**Describe the bug**
Fail to edit split rule. See screen shot below

**To Reproduce**
Add split rule -> click edit button -> see error
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42233517/48598810-23d8fa00-e9a8-11e8-8042-c4a1be96538b.png)

**Desktop (please complete the following information):**

**Additional context**
- rule countpattern and extract has the same issue
- fix issue where back tick is added to column name when fails to add/edit rule

**Comment by joohokim1** [comment]
Integrated test passed.
