### ISSUE TITLE
The results of the query executed in workbench should be visible when you exit the browser and run it back into the workbench

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#814]
**Is your feature request related to a problem? Please describe.**
워크벤치에서 쿼리를 실행하면 쿼리 결과가 나타남
![image](https://user-images.githubusercontent.com/16472109/48756105-1e96ea80-ecdb-11e8-8adf-e67a7448b007.png)
브라우저 종료 하거나 워크벤치에서 빠져나와 다시 워크벤치에 들어가면 이전 쿼리 결과가 나타나지 않음.
![image](https://user-images.githubusercontent.com/16472109/48756173-6158c280-ecdb-11e8-9508-cff6776db4cf.png)

**Describe the solution you'd like**
현재 메타트론 워크벤치에서는 질의 결과를 csv 파일로 남기고 있기 때문에 이를 사용하여 쿼리 결과를 복구할 수 있음.

**Comment by kyungtaak** [comment]
@YooYoungmo 님, 위 제안은 좋은 아이디어 같습니다. 혹시 직접 진행해주실수 있나요?

**Comment by YooYoungmo** [comment]
@kyungtaak 네 제가 진행 하겟습니다.

**Comment by kyungtaak** [comment]
@AnnieHwang @metatron-app/design 이 기능에 대해 기획검토를 간단히 부탁드립니다. 
일단 제가 생각하는 제약사항은 파일이 시간이 지나면 없어져 볼수가 없는데요. 이에 대해서 문구 처리 같은게 필요할런지.. 
@ufoscw 추가적인 개발 또는 디자인 요소가 있는지 검토해주시고, @YooYoungmo 님께 피드백 주시면 좋을것 같아요.

**Comment by AnnieHwang** [comment]
@kyungtaak @minjung-cho 대시보드에서 Linked Datasource가 날라가면 나오는 경고과 비슷하게 아래와 같이 기술하면 어떨까 해요 @minjung-cho 이상하시면 말씀부탁드립니다.
main : Result is missing
sub : 일정시간이 지나 결과 이력이 삭제되었습니다. 다시 조회하시기 바랍니다.

아래는 Linked datasource에서 나오는 메세지 문구입니다. 참고하시라고 올려드려요.
![image](https://user-images.githubusercontent.com/6300003/49052959-72e91f80-f231-11e8-9e96-cbbf1689703f.png)

**Comment by minjung-cho** [comment]
@kyungtaak 
일정 시간 내 화면을 나갔다 들어와도 결과를 확인할 수 있고(csv파일로 자동 복구)
일정 시간이 지나면 결과창에 문구를 보여주는 것으로 이해하면 될까요?
@AnnieHwang 
제안 주신 문구로 화면 진행하겠습니다

**Comment by minjung-cho** [comment]
@AnnieHwang @ufoscw 화면 기획 확인 부탁드립니다.
![2018-11-27 1 02 20](https://user-images.githubusercontent.com/28773903/49057836-bc8f3580-f244-11e8-90a5-7003f2a01b8b.png)
@koeun222 '쿼리 실행 전' 화면만 탭 영역에 문구가 적히는 디자인인데, 통일성을 위해서 메인 영역에 문구가 표시되는 걸로 변경하는건 어떨까요?

**Comment by ufoscw** [comment]
@minjung-cho @AnnieHwang  
1. 설명 부분에 약간 수정할 부분이 있어서 알려드립니다.
화면을 벗어나도 백그라운드에서 계속 쿼리를 돌리는 개선안이 아닙니다.
현재 개선하는 방안은 페이지를 벗어나도 쿼리를 계속 수행하는게 아니라.. 
한번 결과를 받아온 적이 있다면 다시 워크벤치 진입 시 마지막 결과를 보여주는 방안입니다.
@YooYoungmo님 혹시 이 부분은 생각하시는 개선안과 차이가 있는지 확인 부탁드립니다.

2. "일정 시간이 지나서" 라는 문구는 모호하고 사용자가 "일정 시간"에 대해 궁금할것 같아서 그냥 빼도 될것 같습니다.

3. Reload 버튼이 있으려면 실제 수행될 쿼리에 대한 안내가 필요해 보입니다.
결과탭 마우스 오버시 실제 수행될 쿼리문이 팝업이 떠야 겠지요?
그리고 마지막 수행 시점과 재수행할 시점에 글로벌 변수가 변경되었다면 수정된 변수 기준인지 아니면 마지막 수행된 기준인지..등도 기획서에 보강이 필요해보입니다.
제 개인적인 의견은 마지막 쿼리 수행시와 항상 동일한 세션 상태가 아니기 때문에 동일한 쿼리 결과를 보장하기 힘들어 보여서요...
Reload 버튼은 빼는것도 좋아보입니다.

P.S :
그리그 이건 개인적인 의견이니 참고만 해주시면 됩니다.
한번도 쿼리를 수행한적이 없는 경우와 쿼리를 수행한적이 있지만 결과가 삭제된 경우를 굳이 구분해야 할까요?
그냥 현재 처럼 빈 결과탭이면 될것 같은데 사용자에게 과거 이력이 삭제되었다고 안내를 하는게 좋을까요?

**Comment by YooYoungmo** [comment]
@ufoscw  언급하신 '한번 결과를 받아온 적이 있다면 다시 워크벤치 진입 시 마지막 결과를 보여주는 방안' 입니다.

> 화면을 벗어나도 백그라운드에서 계속 쿼리를 돌리는 개선안이 아닙니다.
> 현재 개선하는 방안은 페이지를 벗어나도 쿼리를 계속 수행하는게 아니라..
> 한번 결과를 받아온 적이 있다면 다시 워크벤치 진입 시 마지막 결과를 보여주는 방안입니다.

제 생각에도 @ufoscw 님의 의견처럼 그냥 현재 처럼 빈 결과탭이면 될것 같습니다.

**Comment by minjung-cho** [comment]
@ufoscw 
1. 말씀 주신 것과 같이 이해했는데, 오해의 여지가 있었나 봅니다. TO-BE 부분에 '**쿼리 실행 후,** 일정시간 내 화면을 ...' 라고 하면 될지요?
3. Reload 시점에 쿼리문이 달라질 수 있다는 걸 간과했습니다. 추가 의견 주신것와 @YooYoungmo 님 의견으로 봤을 때, 별도 UI는 필요하지 않아보이네요. '워크벤치' 툴 사용 시, 쿼리 결과 조회 유무와 마지막 쿼리 결과를 확인하는 것이 사용자에게 중요한 정보가 되지 않는다면.. 굳이 케이스를 구분하지 않아도 될것 같습니다. @AnnieHwang 의견 부탁드립니다.

**Comment by AnnieHwang** [comment]
@minjung-cho 네 전 별 이견 없습니다
