### ISSUE TITLE
Fix misaligned grid

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#818]
**Describe the bug**
For horizontal scrolling, column headers misaligned with data

**To Reproduce**
1. Go to Menu > MANAGEMENT > Data Preparation > Dataflow
2. Click dataflow
2. Click Wrangled dataset
3. Click rdit rule
3. Scroll right or left
4. See misaligned grid

**Expected behavior**
After Scrolled right or left, Header and data must be aligned

**Screenshots**
<img width="1347" alt="_" src="https://user-images.githubusercontent.com/42233710/48760107-66703e80-ece8-11e8-9d2a-94ab1b3be3b5.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by imsaaks** [comment]
Problem while scrolling the grid to the touchpad.
Check the grid scroll horizontal value, and run the timer once.

**Comment by imsaaks** [comment]
Not scrolling to the left is separate from the symptom in the stomach.
The symptom are under review.
