### ISSUE TITLE
error occured when datasource search with date range.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#820]
**Describe the bug**
error occured when datasource search with date range.

**To Reproduce**
1. Go to DataSource List Page
2. Click on 'Last 7 days'
3. See error

**Expected behavior**

**Screenshots**
<img width="393" alt="devtools_-_localhost_8180_app_v2_workbench_71c41565-6ce9-4ded-9423-74cd8173fb33" src="https://user-images.githubusercontent.com/3770446/48769182-58c5b380-ecfe-11e8-8fb8-59840bc8a64e.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by alchan-lee** [comment]
It seems duplicated #501 
It is already merged into 3.0.7 branch.
