### ISSUE TITLE
Create dataset with JSON file

### ISSUE THREAD

**Issue by mh0203** [metatron-app/metatron-discovery#841]
**Is your feature request related to a problem? Please describe.**
Now we support dataset creation with excel, csv and txt files.
Let's also support json files.

**Describe the solution you'd like**
Allow Json file when making file type imported dataset.

**Describe alternatives you've considered**

**Additional context**
We should support json file type snapshot soon.

**Comment by mh0203** [comment]
Serve side job: JSON parsing and JSON to CSV converting logic.
Clinet side job: Allow json file type upload and change some phrases.

**Comment by mh0203** [comment]
<img width="1630" alt="screen shot 2018-11-22 at 10 02 12 am" src="https://user-images.githubusercontent.com/8232266/48875744-26bb6b00-ee3e-11e8-8b94-bdbb769dc008.png">

**Comment by mh0203** [comment]
<img width="1630" alt="screen shot 2018-11-22 at 10 06 20 am" src="https://user-images.githubusercontent.com/8232266/48875820-8b76c580-ee3e-11e8-87b6-66f981a7acfb.png">

**Comment by mh0203** [comment]
![screen shot 2018-11-26 at 2 55 33 pm](https://user-images.githubusercontent.com/8232266/48995517-89d53680-f18b-11e8-90fa-979b7c7c8163.png)

**Comment by joohokim1** [comment]
During the 2nd integration test, JSON was not able to import.
Maybe there was some problem while merging # 908.
@Ksparknot is working on it.
PR will be created with a new branch.

_2번째 통합테스트 중에 JSON이 import가 안되는 문제가 발생했습니다.
아마 #908을 merge하는 중에 문제가 생긴 것 같습니다.
관련해서 @ksparknot 님께서 작업 중입니다.
새로운 branch로 PR이 만들어질 예정입니다._
