### ISSUE TITLE
display error in widget/datasource download

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#846]
**Describe the bug**
대시보드에서의 위젯 및 데이터소스 다운로드에 대한 화면 오류를 수정합니다.

**To Reproduce**
1. 대시보드 및 위젯을 생성합니다.
2. 대시보드의 데이터 미리보기를 클릭하고 데이터 다운로드를 실행합니다.
3. 위젯의 데이터 미리 보기 및 다운로드를 실행합니다.
4. 화면상에 오류를 확인합니다.

**Expected behavior**

**Screenshots**
![2](https://user-images.githubusercontent.com/3685833/48891231-2ba00f00-ee7e-11e8-909a-75aca724794f.png)
![3](https://user-images.githubusercontent.com/3685833/48891233-2ba00f00-ee7e-11e8-8afc-414cc6bb56e5.png)
![4](https://user-images.githubusercontent.com/3685833/48891236-2ba00f00-ee7e-11e8-9138-4793d4b6a687.png)
![5](https://user-images.githubusercontent.com/3685833/48891237-2c38a580-ee7e-11e8-8c04-c8f3cb42cb72.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 70

**Additional context**

**Comment by kyungtaak** [comment]
#240 이슈와 연결되어 해당 이슈는 종료시키겠습니다.
