### ISSUE TITLE
Screen blank when browser size is reduced in full screen

### ISSUE THREAD

**Issue by sting009** [metatron-app/metatron-discovery#852]
**Describe the bug**
When the browser size is reduced while the editor window is enlarged, a blank space appears on the right side

**To Reproduce**
1. Go to workbench 
2. full size button click 
3. browser size reduce 

**Expected behavior**
Area is drawn normally

**Screenshots**
![image](https://user-images.githubusercontent.com/42328567/48898765-f9e47380-ee90-11e8-969a-db97a823d56e.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by ufoscw** [comment]
@sting009 
LNB 클릭 이슈는 여기에 포함되나요?

**Comment by sting009** [comment]
@ufoscw 
LNB 클릭이슈는 기획확인이 필요하여 포함되어있지 않고, 해당 이슈만 선작업하였습니다.
