### ISSUE TITLE
Dashboard selection error when using 2-depth chart selection

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#87]
**Describe the bug**
대시보드에서 2번의 차트 선택 후 마지막 차트의 선택을 취소하면 상단의 모든 필터가 사라지나 필터는 남아 있음

**To Reproduce**
다음 URL 에 접속해서 스크린샷 순서 대로 진행한다.
https://discovery.metatron.app/app/v2/workbook/57cad565-7616-40ba-a81d-a92fece63d99

1. 천번째 차트 선택
2. 두번째 차트 선택
3. 두번째 차트 선택 취소
4. 모든 필터가 다 사라짐

**Expected behavior**
첫번째 필터가 남아 있어야 함

**Screenshots**
1. 1번 차트 선택
<img width="1915" alt="selection-error1" src="https://user-images.githubusercontent.com/526622/44769747-9227d080-aba0-11e8-80c0-cfd52cbd9d59.png">

2. 2번 차트 선택
<img width="1915" alt="selection-error2" src="https://user-images.githubusercontent.com/526622/44769761-9e139280-aba0-11e8-8120-263f3d26ff3c.png">

3. 2번 차트 선택 취소
<img width="1917" alt="selection-error3" src="https://user-images.githubusercontent.com/526622/44769780-b08dcc00-aba0-11e8-8b4f-fc10126cd7e7.png">

**Desktop (please complete the following information):**
데모 사이트

**Additional context**

**Comment by kyungtaak** [comment]
@esezin @eltriny  대시보드 셀렉션 필터 액션 정의 부분 확인해주시고요. 문제가 있는 부분에 해대 조치 부탁드립니다.

**Comment by dave-taeho** [comment]
@kyungtaak 해당 증상은 버그로 판단되어 조치하도록 하겠습니다.
