### ISSUE TITLE
Workbench LNB screen related issues

### ISSUE THREAD

**Issue by sting009** [metatron-app/metatron-discovery#874]
**Describe the bug**
1. Presto, if mysql type, split bar is reduced, sort is broken
2. Right side of search area is truncated when searching database name
3. If there is no connection authorization information, the default value is displayed as MANUAL.

**To Reproduce**
1. Go to workbench 
2. LNB information, split bar reduce, database click

**Expected behavior**
Fixed to look normal

**Screenshots**
1. 
![image](https://user-images.githubusercontent.com/42328567/48931911-34571a80-ef3c-11e8-9e70-70fd791c1aad.png)

2.
![image](https://user-images.githubusercontent.com/42328567/48931873-083b9980-ef3c-11e8-9961-167c50a6d78d.png)

3. 
![image](https://user-images.githubusercontent.com/42328567/48931959-65cfe600-ef3c-11e8-8e10-c795d710bc17.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by minjung-cho** [comment]
1. 컬럼 리스트 열었을 때 같은 문제가 발생합니다. 물리/논리 정보 표시에 대한 이슈가 있습니다만.. 지금은 Physical table name 부분에 말줄임 넣어서 처리하면 어떨까 합니다
<img width="346" alt="2018-11-29 1 28 18" src="https://user-images.githubusercontent.com/28773903/49199355-baf77600-f3da-11e8-864f-c4aa9b2a95e4.png">
