### ISSUE TITLE
No title when deleting global variables, eliminating upper margin when editing

### ISSUE THREAD

**Issue by sting009** [metatron-app/metatron-discovery#883]
**Describe the bug**
No title when deleting global variables, eliminating upper margin when editing

**To Reproduce**
1. Go to workbench 
2. Click on Global variable delete or edit  
3. Cracked Screen

**Expected behavior**
Fixed to make screen normal

**Screenshots**
![image](https://user-images.githubusercontent.com/42328567/48933701-a2074480-ef44-11e8-8288-8cd92390d8c6.png)

![image](https://user-images.githubusercontent.com/42328567/48933718-afbcca00-ef44-11e8-893d-f9f4492b99f3.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by sting009** [comment]
등록된 변수가 없을경우 텍스트가 붙어버리는 부분 추가하였습니다. 

![image](https://user-images.githubusercontent.com/42328567/49192211-73aebc80-f3bd-11e8-9216-0a704b874482.png)

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/49199443-30fbdd00-f3db-11e8-8bfe-c5abb9967be5.png)
디자인 첨부드립니다. 
등록된 변수가 없을경우 문구와 라인 간격 15px 적용 부탁드립니다

**Comment by sting009** [comment]
@AnnieHwang @koeun222 
넵 지난번 수정하다가 나온 추가 이슈가 있어서 코멘트를 달았던 건데,  코멘트가 혼돈이 있었던것같습니다. 

현재 PR 진행한 버전은 아래 캡쳐화면과 같이, 15px로 유지한 버전입니다. 

![image](https://user-images.githubusercontent.com/42328567/49200125-b765ee00-f3de-11e8-93ea-4178c0880fe2.png)

**Comment by ufoscw** [comment]
@sting009 
삭제시 제목은 여전히 안나오네요.

**Comment by sting009** [comment]
@minjung-cho @ufoscw 
글로벌 변수 삭제 팝업 부분은, 해당 부분은 팝업 사이즈 위치 부분등이 맞지 않고,  코멘트 자체가 서브타이틀 영역에서 있어서 타이틀 영역으로 수정한 부분인데요. 확인한번 부탁드립니다.

**Comment by AnnieHwang** [comment]
@sting009  감사합니다~

**Comment by minjung-cho** [comment]
@sting009 네, 해당 이슈로 인해서 새로운 팝업 가이드가 추가되었습니다. 퍼블쪽에서 전달 받으셔서 적용해 주시면 됩니다~
