### ISSUE TITLE
Missing checking catalog name duplication when creating the catalog

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#901]
**Describe the bug**
메타데이터 카탈로그 생성시 동일 레벨에서 이름을 중복해서 입력하면 등록이 되고 있습니다. 반면에 중복된 이름으로 수정하려고 하면 입력오류를 발생시킵니다. 

**To Reproduce**
1. Go to 메타데이터 관리
2. Click on 'catalog' tab
3. Create 2 catalog same name through "New Catatalog" button
4. One of catalog to have same name edit name to same name
5. see error

**Expected behavior**
생성/수정 모두 동일 레벨에서의 이름 중복에 대해 오류 처리를 해야합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/48986612-c472ab00-f15a-11e8-83f7-f45a9f29bb55.png)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
(N/A)

**Comment by alchan-lee** [comment]
f#901-duplicated_catalog_name 브랜치에
중복된 카탈로그명으로 생성시, 서버 에러나게 해두었습니다.

`{
"code":"MD002",
"message":"Duplicated Catalog Name",
"details":"CatalogException: Duplicated Catalog Name"
}`
