### ISSUE TITLE
Need to fix displaying list of Text widget

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#904]
**Describe the bug**
대시보드내 텍스트 위젯 목록을 표현할때 텍스트 위젯의 내용을 보고 리스트에 표시하게 되는데, 
이에 대한 기준이 명확치 않아 텍스트 위젯내 텍스트가 많을 경우 그대로 표현되기도 합니다. 
이에 대한 수정이 필요합니다.

**To Reproduce**
1. Go to edit mode of dashboard
2. Click on creation button(+) on text wiget panel
3. Input long~ long~ text in text widget and save
4. See list of widget on left panel

**Expected behavior**
최대 2줄까지 위젯목록에 표현합니다. 

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/48994955-1fbb9200-f189-11e8-9bff-ba7f60dc5917.png)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
(N/A)

**Comment by minjung-cho** [comment]
퍼블 확인 후 적용 부탁드립니다-
