### ISSUE TITLE
Error display folder depth in workspace

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#905]
**Describe the bug**
워크스페이스 내 폴더에 진입하면 현재 위치를 표현하는 depth 정보를 나타낼수 있는데, 이 부분에 폴더 명이 길어지고 depth가 많아지면 folder depth 표현이 어긋나고 버튼 클릭이 되지 않는 경우가 있습니다.

**To Reproduce**
1. Go to workspace view
2. Click on 'creation folder' icon 
3. Input folder name (long~~) and save.
4. Enter folder
5. Repeat 10 times (3 -> 4 )
6. See error

**Expected behavior**
- 폴더 뎁스는 10개까지 제한합니다.
- 전체 width는 반응형으로 스크린의 크기에 따라 너비 비율을 둡니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/48995184-39110e00-f18a-11e8-89f1-a4e2fff9926d.png)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
(N/A)

**Comment by koeun222** [comment]
![image](https://user-images.githubusercontent.com/42256760/48995524-935e9e80-f18b-11e8-81a8-a4b82197ae56.png)

화면크기에 따라 text 영역이 가변적으로 적용 
min-width : 70px
max-width : 200px 
(첨부이미지는 최소너비일경우 화면입니다)
