### ISSUE TITLE
feature req: Ability to query an API data source

### ISSUE THREAD

**Issue by tooptoop4** [metatron-app/metatron-discovery#912]
Can metatron query results from a URL? ie like redash can: https://redash.io/help/data-sources/querying-urls

**Comment by kyungtaak** [comment]
Of course we also have the Search API. But I have to translate in English.  I think I will be able to provide it in two weeks at the latest. Are you okay?

**Comment by tooptoop4** [comment]
Any link to 'Search API'? I am looking at ability to query results from an API (ie https://jsonplaceholder.typicode.com/posts?userId=1) but instead of just GET requests would like to send POST request and query the response.

**Comment by tooptoop4** [comment]
@kyungtaak gentle ping

**Comment by kyungtaak** [comment]
@tooptoop4 
Oh.. I'm so sorry for the late reply.
When I checked your question again, I think I didn't understand your question properly.

You mean "metatron query" in your question is a query that you have performed in the workbench?
If so, we do not provide saving the query like redash. But, similar to this, we manage the query execution history.

Using this history information, you can use the query execution api that we use internally. 

I hope it would be the answer you want. and if you need a guide, reply to me.

**Comment by tooptoop4** [comment]
I am talking about different thing, I want to say here is an API (ie 
https://jsonplaceholder.typicode.com/posts?userId=1) then metatron is able to query the results of that  API
