### ISSUE TITLE
Change login screen to feel seasonal

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#914]
**Is your feature request related to a problem? Please describe.**
로그인화면을 크리스마스 분위기 느껴지게 변경하고 싶습니다.
3.1 버젼 ~ 3.1.2 버젼에서만 사용할 로그인화면이었으면 좋겠습니다.

**Describe the solution you'd like**
1. 배경화면을 크리스마스  느낌나는 이미지로 교체합니다.
2. jquery snow 라이브러리(js, css)를 탑재하여 눈이 내려지는 이미지가 보여지게 합니다.
3. 로그인 html 과 typescript 상에 jquery snow 라이브러리를 연결합니다.
4. 로그인 창의 class의 scroll 를 hidden 합니다. (css)
5. 로그인 시 ID, PW 의 placeholder 색상을 조금 더 진하게 바꿉니다. (css)

![2018-11-27_13-25-19](https://user-images.githubusercontent.com/6300003/49058575-f0b82580-f247-11e8-8b50-714b92d8dfad.gif)

**Additional context**
테스트로 만든 소스
[christmas.zip](https://github.com/metatron-app/metatron-discovery/files/2618342/christmas.zip)

**Comment by kyungtaak** [comment]
시즌이 종료되어 이슈를 종료합니다.
