### ISSUE TITLE
index.html 404 is not found

### ISSUE THREAD

**Issue by tooptoop4** [metatron-app/metatron-discovery#916]
I built metatron from source using intellij and pom.xml in github. But when i go to my browser it shows :8180/app/v2/index.html 404 is not found and below page. When I look at the 'fat jar' (discovery-server-3.0.7.jar) it is a bit smaller than the one provided insde https://sktmetatronkrsouthshared.blob.core.windows.net/metatron-public/discovery-dist/Discovery/3.0.7/metatron-discovery-3.0.7-bin.tar.gz. When I inspect the 2 jars I notice mine is missing discovery-frontend-3.0.7.jar within the jar. What is the fix?

Default metatron Error Page

Occurred: Tue Nov 27 05:20:27 UTC 2018

Response Status: 404 (Not Found)

Cause: No message available
Note: You would never generate a page that displays a Java exception to an end-user in a real application
You are seeing this error page due to Spring Boot (which returns a view called "error" in response to uncaught exceptions. Since we are using Thymeleaf this corresponds to the template error.html )

**Comment by alchan-lee** [comment]
@tooptoop4 
I'm using intellij too but I cannot reproduce this issue.

Could you add more information about how did you set **maven scope**?

**Comment by tooptoop4** [comment]
@alchan-lee I cloned the github repo exactly, no changes to pom. What i noticed is that the discovery-frontend-3.0.7.jar generated is only 3KB and I get popup warnings about access to nodejs denied due to no admin privileges on local machine. Maven logs below mention jar will be empty:


"C:\Program Files\Java\jdk1.8.0_152\bin\java" -Dmaven.multiModuleProjectDirectory=$M2_HOME -Dclassworlds.conf=C:\Users\user\Downloads\apache-maven-3.5.3-bin\apache-maven-3.5.3\bin\m2.conf -Dmaven.home=C:\Users\user\Downloads\apache-maven-3.5.3-bin\apache-maven-3.5.3 -Didea.launcher.port=7534 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 12.0.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\user\Downloads\apache-maven-3.5.3-bin\apache-maven-3.5.3\boot\plexus-classworlds-2.5.2.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 12.0.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher --no-plugin-registry --fail-fast --strict-checksums --update-snapshots -DskipTests=true package
[WARNING] Command line option -npr is deprecated and will be removed in future Maven versions.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for app.metatron.discovery:discovery-frontend:jar:3.0.6
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ app.metatron.discovery:metatron-discovery:3.0.6, C:\Users\user\Downloads\metatron-discovery-3.0.6\pom.xml, line 98, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] -------------< app.metatron.discovery:discovery-frontend >--------------
[INFO] Building discovery-frontend 3.0.6
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- frontend-maven-plugin:1.4:install-node-and-npm (install node and npm) @ discovery-frontend ---
[INFO] Node  was installed, but we need version v8.1.2
[INFO] Installing node version v8.1.2
[INFO] Copying node binary from C:\Users\user\.m2\repository\com\github\eirslett\node\8.1.2\node-8.1.2-win-x64.exe to C:\Users\user\Downloads\metatron-discovery-3.0.6\discovery-frontend\node\node.exe
[INFO] Installed node locally.
[INFO] NPM 5.0.3 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.4:npm (npm install) @ discovery-frontend ---
[INFO] Running 'npm run prebuild' in C:\Users\user\Downloads\metatron-discovery-3.0.6\discovery-frontend
[INFO] 
[INFO] --- frontend-maven-plugin:1.4:npm (npm run build) @ discovery-frontend ---
[INFO] Running 'npm run prod' in C:\Users\user\Downloads\metatron-discovery-3.0.6\discovery-frontend
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ discovery-frontend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\user\Downloads\metatron-discovery-3.0.6\discovery-frontend\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ discovery-frontend ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ discovery-frontend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\user\Downloads\metatron-discovery-3.0.6\discovery-frontend\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ discovery-frontend ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ discovery-frontend ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ discovery-frontend ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.996 s
[INFO] Finished at: 2018-11-28T13:51:17+11:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
