### ISSUE TITLE
Fixed error deleting multiple expressions

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#917]
**Describe the bug**
Deletes the last expression when deleting an expression.

**To Reproduce**
1. menu > MANAGEMENT > DataPreparation
2. click Dataflow > click Wrangled Data > Edit rules
3. add rule : window, pivot, aggregate
4. Add two or more expressions and click the Delete Expression button

**Expected behavior**
If you press the delete button, the corresponding location expression is deleted

**Screenshots**

**Additional context**

**Comment by joohokim1** [comment]
Integrated test 2 passed.
