### ISSUE TITLE
Sorting error in dataset list 

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#918]
**Describe the bug**
Sorting doesn't work after sorting by `used in`.

**To Reproduce**
Dataset Tab> click used in sorting button > click created sorting button > see error 

**Expected behavior**
Sort should work in dataset list.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
Integrated test 1 passed

**Comment by joohokim1** [comment]
Integrated test 2 passed
