### ISSUE TITLE
fix settype editor

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#923]
**Describe the bug**
"Set pattern" error when changing numeric type column to timestamp type

**To Reproduce**
1. menu > MANAGEMENT > DataPreparation > Dataflow
2. Click Dataflow > Click Wrangled Data > Edit Rule
3. Add Rule
4. Command : Settype > Column : numeric type column > New type : timestamp
5. See "Set pattern" 

**Expected behavior**
"Set pattern" input box should be output normally.

**Screenshots**
![181127_dataflow_rule_settype_pattern_01](https://user-images.githubusercontent.com/42233710/49074359-e3b32a80-f277-11e8-8f60-38d064b0ccd5.JPG)

**Desktop (please complete the following information):**

**Additional context**

**Comment by imsaaks** [comment]
#923 close

**Comment by joohokim1** [comment]
Integrated test 2 passed.
