### ISSUE TITLE
Split rule error in dataprep

### ISSUE THREAD

**Issue by paigechoi** [metatron-app/metatron-discovery#929]
**Describe the bug**
When applying `split` rule in dataprep, `Number of times` is mandatory field but still works without it

**To Reproduce**
Dataflow main grid -> select `split` -> add rule without `Number of times` -> see error

**Expected behavior**
If `Number of times` is empty user should be warned with an alert saying Number of times is mandatory field

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Similar `Unpivot`  &  `move` error will be be resolved here.

**Comment by joohokim1** [comment]
Integrated test 1 passed.

**Comment by joohokim1** [comment]
Integrated test 2 passed.
