### ISSUE TITLE
how to upload hdfs file?

### ISSUE THREAD

**Issue by tooptoop4** [metatron-app/metatron-discovery#935]
i see HdfsConnection class but nowhere in the UI do i see hdfs

**Comment by i1befree** [comment]
@tooptoop4 I think it would be better to use a user group for these questions. Can I move this issue to google user group? I want metatron discovery user groups to be more active.

**Comment by i1befree** [comment]
For reference, below is the user group URL.
https://groups.google.com/forum/#!forum/metatron-discovery

**Comment by kyungtaak** [comment]
I close this issue because we are responding on the google groups
