### ISSUE TITLE
Add displaying error message when failing query (step of JDBC data source creation)

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#941]
**Is your feature request related to a problem? Please describe.**
현재 아래와 같이 Query 로 Preview 조회시 오류가 발생하면 오류내용을 알수 있는 방업이 없습니다.

![image](https://user-images.githubusercontent.com/822255/49145776-e4b18e00-f343-11e8-89eb-ffa4e4daee47.png)

**Describe the solution you'd like**
쿼리 수행 중 오류 발생시 오류의 내용에 대해 DB 에서 전달되는 오류 메시지를 처리했으면 합니다.  
@metatron-app/design 에서 검토 부탁드립니다. 

**Describe alternatives you've considered**
(N/A)

**Additional context**
워크벤치내에서 쿼리오류 표시와 유사한 형태로 진행했으면 합니다.

**Comment by AnnieHwang** [comment]
@kyungtaak 개선에 여지가 있어보입니다. @deidera08 워크벤치를 참고하여 해당 화면을 좀 바꿔보면 좋을 것 같습니다.
![image](https://user-images.githubusercontent.com/6300003/49240665-16604d00-f449-11e8-9d01-20780dfa91b7.png)

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
쿼리 실행시 서버 오류 메세지는 데이터 미리보기 화면에 노출하면 좋을듯합니다.
![941queryerrormsg](https://user-images.githubusercontent.com/42257766/49269015-13477a00-f4a6-11e8-9fca-baa80544daeb.png)

워크벤치의 경우 output탭을 분리하여 log등을 노출하는데, 그 정도의 기능까지는 필요하지 않은 듯 하고, 단순히 오류메세지 정도라면 미리보기 화면이면 적당할 듯 합니다.

**Comment by deidera08** [comment]
@kyungtaak @AnnieHwang 
[#1175](https://github.com/metatron-app/metatron-discovery/issues/1175)이슈를 정리하면서 화면이 보완되었습니다. 참고부탁드립니다.

**Comment by brandon-wonjune** [comment]
@deidera08 
#630 이슈에서 사용된 code가 동일하게 내려오고있는데요.
지금은 현재 #630 이슈에서 설정된 message로 표기하고있는데 이것도 서버에서 내려주는 message를 그대로 보여주는되는건가요? 
아니면 별개의 상황으로 봐야되나요?

**Comment by deidera08** [comment]
@brandon-wonjune 
별개의 상황은 아닙니다만 Query화면에서는 서버에서 내려주는 message를 그대로 보여주는쪽이 좋을듯 합니다.
