### ISSUE TITLE
Improve filter functions for high cardinality columns.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#944]
**Is your feature request related to a problem? Please describe.**
- High cardinality 컬럼에 대한 필터를 적용을 해야하는 경우, 표현되는 갯수의 제한에 의해 필터를 적용할 수 없는 값이 발생 (예를들어 10만개의 cardinality 를 가지고 있는 컬럼을 필터를 걸면 이중 일부만 필터에 리스트로 표현됨, 나머지 값은 필터를 적용할 수 있는 방법이 없음) 

**Describe the solution you'd like**
- 필터를 적용할 모든 원소를 가져와서 미리 리스트 필터로 보여주는 형태의 필터가 아닌 검색 필터 지원이 필요함(색인 기능 필요)

2019.01.09 추가
**상세기획**
제약 사항 : 필터의 값 목록은 1000개로 유지되어야 함.

주요 정책 :
<필터 패널>
-- '보임' 목록만 표시
-- '숨김' 항목과 서버의 항목은 search all 버튼을 클릭하여 팝업에서 검색 결과 확인 가능
<필터 팝업>
-- 초기 상태 : ‘보임' 목록 100개 / '숨김' 목록 900개  
-- 필터 팝업 화면에서 열람 가능한 항목 최대 1000개

와이어프레임 :
![2019-01-09 4 47 22](https://user-images.githubusercontent.com/28773903/50884476-53e3cd00-142e-11e9-808f-15daca60fd92.png)
![2019-01-09 4 47 29](https://user-images.githubusercontent.com/28773903/50884478-547c6380-142e-11e9-9222-b2d1e42bfbe4.png)

**Comment by Taehui** [comment]
데이터가 많은 경우, 차트 구성 시 빈번하게 발생하는 문제입니다. 빠른 검토 및 반영이 필요해 보입니다.

**Comment by AnnieHwang** [comment]
@Taehui  해당 내용 필터에 조회 기능을 추가하는 것으로 기획하도록 하겠습니다. @kyungtaak 빠른시간 안에 기획안 올려드릴께요.

**Comment by minjung-cho** [comment]
디자인에서 바로 진행할 예정입니다.
- 리스트 형의 필터일 때, 필터 패널에 검색 UI 추가
- 필터 패널에 folding 기능 추가. 첫번째 필터가 펼쳐진 상태가 초기 상태이며, 하나의 필터만 펼칠 수 있습니다.

**Comment by koeun222** [comment]
디자인공유드립니다
![image](https://user-images.githubusercontent.com/42256760/49926371-bebce980-fefe-11e8-87c2-8792d4fd0228.png)

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang #390 와 함께 고려되어야할것 같은데요. 검토부탁드릴게요.

**Comment by minjung-cho** [comment]
**초기 요구사항**
필터 패널에 Value 검색 기능 추가

**상세 개발사항**
- 제약 사항 : 필터의 값 목록은 1000개 정도로 유지되어야 함. 
-- 필터 패널/팝업에서 ‘눈’이 켜진 목록만 표시. Default 최대 1000개
- 요구 사항 : 화면 목록 내에 있는 값 및 서버에 있는 값을 검색할 수 있어야 함
-- 검색어 입력 즉시 검색으로 화면에 표시된 목록 내에서 검색 가능
-- 검색 버튼 클릭으로 서버 검색 결과 호출
-- 필터 패널에서는 서버 검색 시도 시, 필터 팝업을 출력함

<img width="1240" alt="2019-01-02 6 40 07" src="https://user-images.githubusercontent.com/28773903/50576640-7176cc80-0e59-11e9-80f0-fe4cf909a31e.png">

<img width="1368" alt="2019-01-02 6 40 18" src="https://user-images.githubusercontent.com/28773903/50576638-6754ce00-0e59-11e9-9ee7-aa6b4500de36.png">

**Comment by kyungtaak** [comment]
@minjung-cho @AnnieHwang  그런데, 필터 항목이 한번에 보일수 있는 항목이 1000개까지 필요할까요? 100개 정도로 축소를 해보는것은 어떠실런지요? 검토 부탁드립니다.

**Comment by minjung-cho** [comment]
@kyungtaak 화면에 보이는 목록에서는 '즉시 검색'이 지원되기 때문에 최대한 많은 목록을 보여주는 것이 좋을 것 같습니다. 
그리고 엄밀히 말하면... 한번에 보일수 있는 항목이 1000개인 것은 아니고요, '보임' 목록의 초기 개수가 최대 1000개입니다. 그러니까 '보임''숨김'(눈) 기능으로 화면에 보이는 목록이 1000개 이하 또는 1000개 이상이 될수 있는 것입니다. 개발 진행 시 오해가 있을 까봐 한번 더 전달 드렸습니다 ^^

**Comment by koeun222** [comment]
@AnnieHwang @minjung-cho  디자인 공유드립니다 

1. 필터패널
- 검색 ui 추가 
- 필터 패널에 folding 기능 추가
- 페이징 기존과 동일 (한페이지에 리스트 10개) 
- 리스트 행간 수정

2. 필터팝업
- 검색 ui 변경
- 리스트 행간 수정
- 선택된 항목만 보는 switch 버튼 메타포&위치 변경

![image](https://user-images.githubusercontent.com/42256760/50585478-833b8c80-0eb8-11e9-9391-665863a7e7f4.png)

**Comment by minjung-cho** [comment]
> @kyungtaak 화면에 보이는 목록에서는 '즉시 검색'이 지원되기 때문에 최대한 많은 목록을 보여주는 것이 좋을 것 같습니다.
> 그리고 엄밀히 말하면... 한번에 보일수 있는 항목이 1000개인 것은 아니고요, '보임' 목록의 초기 개수가 최대 1000개입니다. 그러니까 '보임''숨김'(눈) 기능으로 화면에 보이는 목록이 1000개 이하 또는 1000개 이상이 될수 있는 것입니다. 개발 진행 시 오해가 있을 까봐 한번 더 전달 드렸습니다 ^^

**Comment by Taehui** [comment]
@minjung-cho 이 이슈는 개발이 종료되었나요?

**Comment by minjung-cho** [comment]
@Taehui 제가 실수로 클로즈한것 같습니다 ^^; 혼선을 드려 죄송합니다

**Comment by minjung-cho** [comment]
> @kyungtaak 화면에 보이는 목록에서는 '즉시 검색'이 지원되기 때문에 최대한 많은 목록을 보여주는 것이 좋을 것 같습니다.
> 그리고 엄밀히 말하면... 한번에 보일수 있는 항목이 1000개인 것은 아니고요, '보임' 목록의 초기 개수가 최대 1000개입니다. 그러니까 '보임''숨김'(눈) 기능으로 화면에 보이는 목록이 1000개 이하 또는 1000개 이상이 될수 있는 것입니다. 개발 진행 시 오해가 있을 까봐 한번 더 전달 드렸습니다 ^^

라고, 위에 댓글을 달았었습니다만... 취소하고 한가지 문의 드리겠습니다. 말로 전달하기 어려워 플로우를 그려봤습니다. 이해가 안가시면 문의부탁드립니다. 아래 이미지에 궁금한 것을 초록색으로 표시해 두었습니다.
<img width="1417" alt="2019-01-05 8 05 17" src="https://user-images.githubusercontent.com/28773903/50723842-6b694000-1126-11e9-89b3-ee9602baefeb.png">
'보임' 설정 최대치를 100개, 서버에서 내려주는 값의 최대치를 1000개 로 잡으면 필터 패널에서는 최대 100개, 팝업에서는 1000개 & 추가 검색 가능한 형태가 될것 같습니다.

**Comment by AnnieHwang** [comment]
@kyungtaak 
- 오더링을 A-Z로 기본값으로 했는데 보임설정한 항목부터 보는건 이상한것 같습니다. @minjung-cho 예제로 설명하신 결과로 보여지면 좋을것 같습니다~
- 기본값을 100개로 하고 서버에서 추가할 수 있는 값은 900개, 즉 화면에 총 1000개까지 보여질수 있도록 결정된 것 같습니다(맞죠? 전 좋아요.)

**Comment by minjung-cho** [comment]
@AnnieHwang 
필터 패널에서는 기본 보임 100개 목록이 보이는 것 맞고요.
필터 팝업에서 보임 기본값 100개, 숨김 기본값 900개. 화면에 총 1000개까지 보여주는 것으로 기획되었습니다.

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho 네 이 기획안으로 개발을 진행하도록 하겠습니다.

**Comment by minjung-cho** [comment]
@kyungtaak @eltriny 최종 기획안을 이슈 본문에 추가하였습니다.

**Comment by minjung-cho** [comment]
@kyungtaak 한가지 더 문의 드립니다. 'search all'(서버통신 검색)하는 기능이 필수 필터 설정화면에도 들어갈 수 있는 지요? (참고로.. 필수 필터 설정 화면에서는 보입/숨김 기능은 없습니다.)

**Comment by koeun222** [comment]
@AnnieHwang 추가된 디자인 공유드립니다 
필터 패널에 check switch button 추가했습니다.
![image](https://user-images.githubusercontent.com/42256760/50951943-44c65300-14f2-11e9-9cf8-b34ae256cef6.png)

**Comment by kyungtaak** [comment]
@eltriny 
1. selected value 표시에대하 filter spec.
```
{
  "type": "include",
  ...,
  "showSelectedItem": true
}
```

2. search word property
```
{
    "dataSource": {
        "type": "default",
        "name": "sales"
    },
    "filters": [
        ...    
    ]
    "targetField": {
        "type": "dimension",
        "name": "Category",
        ...
    },
    "searchWord": "Off",
    "sortBy": "COUNT",
    "limit": 1000
}
```

**Comment by minjung-cho** [comment]
@eltriny 
서버 검색 시, 즉시 검색된 결과 아래에 서버 검색된 부분이 붙는 방식(아래의 핑크색 박스 부분)으로 기획서를 전달드린
건데, 설명이 부족했나 봅니다. 
![2019-01-16 5 18 58](https://user-images.githubusercontent.com/28773903/51235475-f3670980-19b2-11e9-87a9-9308faf0fd78.png)
그러나 원래 안으로 간다고 했을때도 (지금보니) 이부분에 영역을 분리하는 디자인이 추가되어야 할것 같아서 
현재 구현 상태를 유지하는 안에서 우려하신 상황에 대한 정책 전달드립니다. 아래 내용 참고 부탁드립니다.

1.1 서버 검색 후, 검색어를 삭제/추가 > 서버 검색 결과 내에서 즉시 필터링
1.2 서버 검색 후, 검색어 삭제(X) 버튼 클릭 > 목록 초기화 (초기 상태로 돌아감)

**Comment by minjung-cho** [comment]
@eltriny 
조금전 전달 했듯이, 아래와 같은 기획변경으로 사용성을 보강하려고 합니다. 
1. 패널에서 search all 시, 편집 팝업뜨지 않고 바로 서버 검색 결과 를 받아 오는 것으로 변경
2. 팝업에서 '보임''숨김' 설정 부분에 전체 보임 / 전체 숨김 기능 추가
그에 따라 정의되어야 할 부수적인 것들이 있을 것 같은데, 구두로 더 논의 드리겠습니다.

**Comment by minjung-cho** [comment]
@AnnieHwang 
2번 내용에 대한 WF입니다. 그린색 부분 확인 부탁드립니다.
<img width="476" alt="2019-02-12 10 53 14" src="https://user-images.githubusercontent.com/28773903/52606068-94fb5100-2eb4-11e9-90f8-c7def1711773.png">

**Comment by koeun222** [comment]
@AnnieHwang 디자인 공유드립니다- 
![image](https://user-images.githubusercontent.com/42256760/52759088-03bfe200-304e-11e9-9567-b3af7ba8c5e9.png)

**Comment by koeun222** [comment]
디자인 공유드립니다- 
![image](https://user-images.githubusercontent.com/42256760/52772943-21587000-307d-11e9-9ab6-b9fa2cb3cac4.png)

**Comment by minjung-cho** [comment]
@eltriny 
하단에 선택 값만 필터링 하는 UI의 문구가 조금 헷갈린다는 의견이 있었습니다. 문구를 아래와 같이 변경 부탁드립니다.
![2019-02-15 6 01 25](https://user-images.githubusercontent.com/28773903/52846064-ff79ee80-314b-11e9-9ed9-18a0dfd86931.png)
