### ISSUE TITLE
Improve the filter condition when selecting the connection line of the sankey diagram

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#95]
**Is your feature request related to a problem? Please describe.**
sankey diagram 의 연결선을 선택하면 현재 시작노드의 값이 필터로 사용 되는데, 시작과 종료 노드의 값을 필터로 사용하는 것이 좋아 보임

**Describe the solution you'd like**
스크린샷 참조

**Describe alternatives you've considered**

**Additional context**
<img width="1918" alt="improve-sankey-filter" src="https://user-images.githubusercontent.com/526622/44832721-9f0ef780-ac66-11e8-9899-331564c7592b.png">

**Comment by kyungtaak** [comment]
@metatron-app/design  검토 부탁드립니다.

**Comment by esezin** [comment]
@kyungtaak  
셀랙션 필터는 echart dependency가 좀 있는 것으로 알고 있어서.. 개발쪽과의 논의도 필요할 것 같습니다. 논의 하고 추가로 답변 드리겠습니다.

**Comment by esezin** [comment]
@kyungtaak 
개발팀과 논의 후 구현 가능여부를 테스트한 결과를 공유드립니다.
결과부터 말씀드리면, A-B간의 연결선을 선택했을 때 노드A/B 모두 선택되도록 구현이 가능합니다.

다만. 다시 선택을 해지할 때, 공통적으로 선택된 노드가 해지되는 문제가 있는데요.
예를 들면 아래와 같습니다.
1. A-B 와 함께 A-C도 연결되어 있는 생키 다이어그램에서
2. A-B간 연결선과 A-C간 연결선을 연이어 클릭하면, 노드 A/B/C가 선택됨
3. A-C간 연결선을 클릭하여 선택을 해제하면, 노드 A,C가 선택해지되고 B만 선택된 상태로 남음
4. 위 3번의 경우 A는 공통으로 선택된 노드이기 때문에 A-B의 연결이 유효한 이상 A도 선택 상태로 남아야 함

상기 이슈는 해결에 시간이 좀 더 소요 될 것으로 보이며, 개발 일정을 별도로 논의해야 할 것 같습니다.
그리고, 노드-노드간 연결선을 선택하여 노드를 모두 선택 가능한 형태로 정책을 가져갈 경우.
생키 다이어그램과 유사한 네트워크 다이어그램에도 동일한 적용을 검토해야 할 것 같습니다.
현재 네트워크 다이어그램은 연결선의 선택 자체가 막혀있는 상태입니다.

@juheeko9 @dave-taeho 
이해가 잘못된 부분이 있거나 보충이 필요한 내용이 있으면 의견 부탁드립니다.

**Comment by i1befree** [comment]
@esezin 하나 추가로 말씀 드리자면 현재 상태에서 필터가 다 빠지지만 첫번째 차트는 여전히 필터가 적용된 상태입니다. 이 부분은 위에 필터가 다 빠지는 상태라면 적어도 첫번째 차트도 필터가 빠져야 정상이라고 봅니다.

**Comment by juheeko9** [comment]
@kyungtaak 
노드-노드 연결선을 선택하여 노드를 모두 선택가능한 형태로 변경되어야하는 정책적인부분이 변경된사항입니다.
해당 부분은 이번스프린트내로 완료할 예정입니다.

**Comment by juheeko9** [comment]
f#95-edit_sankey_filter 브랜치 추가하였습니다.
