### ISSUE TITLE
Under the personal workspace, the "Hide / Show" function for dashboards is meaningless

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#955]
**Describe the bug**
개인 워크스페이스 하의 워크북 에서는  내 대시보드를 가리기 위해 지정된  "Shown Only" 기능이 무의미해 보입니다.
해당 기능은 워크스페이스 멤버내 워크북을 보기/수정 권한이 있는 경우에만 동작을 하는데, 개인 워크스페이스는 그러한 멤버가 존재하지 않기 때문에 사용자로 하여금 혼란을 가져다 주고 있습니다. 

**To Reproduce**
1. Go to "Private Workspace"
2. Click on any workbooks.
3. See show/hide butten on dashboard list

**Expected behavior**
사용자의 혼란을 방지하기 위해, 개인 워크스페이스의 경우 무의미한 show/hide 버튼을 제거하고, "Shown Only" 필터링 조건도 제거합니다.

**Screenshots**
(N/A)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
(N/A)

**Comment by kyungtaak** [comment]
@AnnieHwang @metatron-app/design 위의 내용 검토 부탁드립니다.

**Comment by AnnieHwang** [comment]
@kyungtaak  제가 보기엔 의미상 있으면 참 좋은 기능 같습니다. 하지만 현재 기능자체가 기획과 다르게 적용되고 있는것 같습니다(하단 동영상을 참고 부탁드립니다) 

해당기획의 취지는.. 아무리 개인사용자라도 작업중이거나 노출하고 싶지 않은 경우 '보임기능'을 OFF하고 프리젠테이션을 하면, 해당 대시보드가 보이지 않은채 프리젠테이션을 할 수 있어야 합니다. (개인사용자도 개인이 만든 대시보드로 외부에 프리젠테이션을 할수 있다는 시나리오로 만든 것입니다)

현재 해당 기능이 기획의도대로 동작하지 않고 있어 많이 무의미해보이는게 아닌가 싶습니다. @minjung-cho 내용이 맞는지 확인부탁드립니다.

![2018-11-29_23-14-10](https://user-images.githubusercontent.com/6300003/49227734-2833f700-f42d-11e8-9d28-3aa9519ad79b.gif)

**Comment by kyungtaak** [comment]
@AnnieHwang @minjung-cho 제 생각에는 보임/숨김기능과 Presetation 기능에 보이고 숨기는 기능을 분리해도 나쁘지 않아 보입니다. 
본 이슈는 그대로 진행하고, 추가 이슈를 생성하여.. 아래와 같이 전환해보심이 어떨런지요?
- 공유워크스페이스내 대시보드 목록에 권한에 따른 보임/숨김 (사실 권한에 권한이라.. 또다른 여지가 있을수 있어 개발자입장에서는 없앳으면 하는 바램도 있습니다.)
- 개인/공유 워크스페이스에서 프리젠테이션 모드에서 보여줄 대시보드 선택하는 셀렉션 컴포넌트 추가.

**Comment by minjung-cho** [comment]
@AnnieHwang 님 말처럼 '눈'에 두개의 기능이 있습니다.
1. 공유워크스페이스 워크북 열람자에게 대시보드 숨김
2. 프리젠테이션 뷰에서 대시보드 숨김

@kyungtaak 
우려하시는 부분은 개인 워크스페이스에서 굳이 1번 기능이 필요하냐는 것과 개발 로직의 복잡함?정도로 이해가 됩니다. 
- 개인 워크스페이스에서 1번 기능 사실 불필요합니다만, 2번 기능은 여전히 필요하므로, 유지하는 것이 좋을 것 같습니다. 개인워크스페이스에서 1번 기능에 대한 코드를 제거하는 것에는 어떤 이견도 없습니다.
또한, 제안 주신 기능을 분리하는 것은.. 특히 2번째 부분을 어느 화면에서 하게 할것인지에 대해서 잘 떠오르지 않아서 위와 같은 의견 드렸습니다.

다만,, '눈'모양의 메타포나 토글 버튼으로 처리하는 것이 1,2번 기능을 표현하는데 적당하다고 생각했습니다만, 많은 사람들에게 직관적이지 않아서 이슈가 계속 제기되는 것 같습니다. 
대시보드 썸네일에 컨텍스트 메뉴를 두어서 레이블 버튼으로 기능에 대해 명확히 보여주거나, 키노트의 '슬라이드 숨기기'와 같이 다른 UI를 검토해 보는게 어떨까 하는 생각입니다.

**Comment by kyungtaak** [comment]
@minjung-cho 제가 생각하기에.. 사실 1번과 2번은 용도가 달리 활용될수 있어 동일하게 기능을 유지시키기엔 무리가 있어 보입니다. 
-  1번에서 열람자에게 숨기고 싶지만, 수정자인 본인이 2번 프리젠테이션 뷰를 오픈시에서는 보이고 싶다면?
- 혹은 1번 열람자에도 숨기고 오픈된것 중에 2번 프리젠테이션에서 보이고 싶지 않는게 있다면?  

3.1 내의 프리젠테이션 기능은 권한이 있는 대시보드만 볼수 있는 기능으로 한정하고,(개인은 전체, 공유는 권한에 따름)
추후 위의 내용에 대해서는 개선안을 내어 개발하는게 좋을것 같아보입니다.

지금현재 개인 워크스페이이스에서는 의도하신 2번 기능이 동작이 안되요. 
2번 동작을 개발하는 것보다 일단 기능을 막고, 이후 개선에 따라 진행하는 편이 더 좋을것 같다는 개발 담당자로써의 의견입니다.

**Comment by kyungtaak** [comment]
@AnnieHwang 제가 가리려는 의도를 이해 못하신것 같네요.
현재 기능이 동작하지 않는 문제입니다. 따라서 일단 가리고 신규로 기획해주시면 개발하겠다는데  문제가 있으신가요?

**Comment by AnnieHwang** [comment]
@kyungtaak 제가 의도를 착각했나봐요. 일단 현재기능막고 개선안을 찾도록 하겠습니다.

**Comment by kyungtaak** [comment]
@eltriny 위의내용에 대해 개인워크스페이스인경우 보임/숨김 기능을 막아주시면 감사드리겠습니다. 
추후 개선안 적용시 위의 논의 내용을 반영하여 개발하겠습니다.
