### ISSUE TITLE
Hiding notebook-specific features in workspace that no assigned notebook server

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#958]
**Is your feature request related to a problem? Please describe.**
노트북 서버를 연결하지 않은 워크스페이스의 경우 노트북 관련 기능을 사용할수 없는데도, 노트북 등록버튼이나, 노트북 개수 등, 사용자에게 혼란을 가져다 줄수 있습니다. 

**Describe the solution you'd like**
아래와 같이 노트북 서버 연결이 되지 않은 워크스페이스의 경우 관련 기능을 숨겼으면 합니다.
![image](https://user-images.githubusercontent.com/822255/49217923-56580d80-f412-11e8-9675-75fd89929793.png)
 
**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by kyungtaak** [comment]
@AnnieHwang @metatron-app/design 위의 내용 검토부탁드립니다.

**Comment by AnnieHwang** [comment]
@kyungtaak @minjung-cho 사실 없애도 되는데.. 염려스러운 점이 있어요.지금도 노트북 설정을 잘 찾지 못하는데.. 저것도 없으면 노트북이 있다는 사실을 아예 인지를 못할까봐요. 차라리 비활성화 느낌이 나게 처리하면 어떨까요?  

노트북 설정을 잘 찾을수 있게 하면 사실 저 버튼을 없애도 좋을 것 같은데, 현재로서는 딱히 방법을 못찾겠어요.

**Comment by Taehui** [comment]
@AnnieHwang 어차피 설정을 관리자가 하는 거라서, 사용자는 노트북이 있다는것을 몰라도 상관없을 듯 해요..안보이는 것이 낳을듯..

**Comment by AnnieHwang** [comment]
@Taehui 노트북 설정은.. 관리자가 아니라 워크스페이스 오너가 하고 있습니다.
![image](https://user-images.githubusercontent.com/6300003/49239188-6d642300-f445-11e8-8da8-a30da8ff540e.png)

@kyungtaak @minjung-cho 차라리..워크스페이스에 선택한 퍼미션에 노트북 퍼미션으로 hide 유/무 여부를 결정하면 어떤가요?
1) 워크스페이스 생성 시 선택한 퍼미션스키마에 노트북 퍼미션이 없으면 => 버튼과 갯수 노티 UI hide
2) 워크스페이스 생성 시 선택한 퍼미션스키마에 노트북 퍼미션이 있지만, 노트북 설정을 안한 경우 => 버튼과 갯수 노티 UI show
![image](https://user-images.githubusercontent.com/6300003/49239327-dc417c00-f445-11e8-9f1a-c9b541cf3a92.png)

**Comment by kyungtaak** [comment]
@AnnieHwang 위 코멘트에 대한 저의 생각입니다.
- 먼저 노트북의 할당체계는 왜 데이터소스나 커넥션과 다른지 모르겠어요. 이건 동일하게 맞춰져야한다고 생각됩니다. 
  (따라서 관리자 중심 체계로 가야하는게 맞다고 봅니다.)
- 현재 공유 워크스페이스 상에는 그렇게 하고 있습니다. 버튼은 숨기고 있고, (View 권한이 없을땐 개수 보이는 ui 도 숨겨
야하는데 버그네요..)

그럼 제 입장을 말씀드리면, 
- 고객이 왜 이걸 숨겨달라고 요구했을까요? 사용자가 처음 접하는 화면이 개인 워크스페이스인데 "노트북" 버튼이 있어요. 저희 제품을 적용하고 운영하는 롤으 가진 사용자들은 사용자 롤을 가진 사용자에게 질문을 받게 될거죠. 저희가 제공하는 노트북 서버를 연결하지 못해서 그렇다고 한다면,  곤란하죠. 제공되지 못하는 기능을 노출하는게 과연 맞나라는 측면에서본다면, 어떻게는 비활성화 보다는 숨겨지는게 맞다고 봅니다.
- 데이터소스나 커넥션은? 할당이 없으면 워크북이나 워크벤치는 숨겨야 되는것이 아니냐 할수 도 있겠지요..(사실 할말이 없습니다.) 하지만, 워크북이나 워크벤치는 저희의 메인 기능이고 언제든 활용할수 있게 준비가 잘되어 잇지만, 현재 노트북의 완성도 나 사용성을 따진다면? 숨김을 통해 노출을 최소화하는게 저희로서 부담이 덜할것으로 보고 있습니다. 
- 따라서 3.1 에서는 이렇게 숨겨지고, 추후 타 금융권에서 활용하던 워크스페이스 타입 과 같은 방식을 ui 를 통해 풀어낸다면 더 좋을것 같은데요. 어떻게 생각하시는지요?

**Comment by AnnieHwang** [comment]
@kyungtaak 이게 처음 서비스 기획하셨던 분(김매니저님^^)이 저희에게 준 요구사항이
- 노트북 서버는 디스커버리가 깔리면 default로 zeppelin, jupytor가 1개씩 깔려 있다. 따라서, 모든 사용자는 노트북을 이용 할 수 있다. 
이게 사실 시작이었습니다. 따라서 할당체계가 데이터소스와 커넥션과 다른 이유였고요.

정책이 바뀌어서 노트북에 default 서버가 필수적으로 깔리지 않는다면, 말씀하신것 처럼 데이터소스와 커넥션과 같은 할당체계로 바꿔야 할 것 같아요. 노트북 서버 세팅하는 위치도 지금은 워크스페이스 내인것도 Data Manager 안으로 옮기고, 워크스페이스에 권한을 주는 방식으로 UI가 바꿔야 할 것 같습니다.

저는 사실 막는거 고민이 되는데.. 일단 막고 빨리 개편하는 방향으로 가면 좋을 것 같습니다.

**Comment by kyungtaak** [comment]
@AnnieHwang 노트북 기능도 정리가 될 필요가 있어 보여요 :) 관리부분은 개선건으로 이슈를 할당하여 진행을 하고요. 그럼 원 이슈 내용대로 정리 하도록 하겠습니다. 

@eltriny 해당 이슈 개발 계획수립후 진행 부탁드릴게요.
