### ISSUE TITLE
Support to connect hive with zookeeper for connection pool.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#963]
**Is your feature request related to a problem? Please describe.**
 - 워크벤치에서 데이터 조회 시 하이브 서버의 OOE 로 장애가 나는 경우가 자주 발생하며, 안정성을 높이기 위해 여러대로 Connection Pool 을 워크벤치에서 컨넥션을 지원할 필요가 있음 
 - 아래 과정으로 실행 시 에러 발생
 1. Connection 생성 화면
 2. Hive 선택
 3. Url Only 선택
 4. jdbc:hive2://server-1:2181,server-2:2181,server-3:2181/serviceDiscoveryMode=zooKeeperNameSpace=hiveserver2 입력
 5. 유효성 체크 --> 성공
 6. 컨넥션 저장 시 실행 시 'dc_hostname' can not be null 에러 발생

**Describe the solution you'd like**
- 정상적인 Connection 저장

**Comment by babokim** [comment]
아래 기능으로 URL 직접 입력하면 되지 않나요?
![image](https://user-images.githubusercontent.com/321821/49269196-12fbae80-f4a7-11e8-9842-d245019a0e18.png)

**Comment by Taehui** [comment]
기능이 있었네요 ㅡ.ㅡ

**Comment by Taehui** [comment]
기능은 있는데 에러가 발생하여 이슈 내용 수정 후 재 오픈 합니다.

**Comment by ufoscw** [comment]
@Taehui 
dc_hostname 필수값 조건은 관련 기능이 추가되면서 삭제되었습니다.
수정된 속성이 DB에 제대로 업데이트가 되지 않은것으로 보입니다.
hibernate의 ddl auto update 기능 동작이 간혹 꼬일때가 있었거든요.

**Comment by Taehui** [comment]
@ufoscw 네, 패치가 필요한 내용 맞나요?

**Comment by ufoscw** [comment]
@Taehui 
discovery meta db의 컬럼 속성만 업데이트 해주시면 됩니다.
```
alter table dataconnection
modify column dc_hostname varchar(255);
```
Domain 속성 변경이 제대로 안되는 문제에 대해서는 방안을 좀 찾아보겠습니다.

**Comment by Taehui** [comment]
@ufoscw 저희 쪽 Meta DB 에는 위에 가이드 주신 내용이 이미 반영이 되어 있다고 하는데요...위에 문제랑 다른 이유로 안되는 것 같습니다.

**Comment by YooYoungmo** [comment]
@ufoscw 제가 알고 있기로는 하이버네이트 ddl auto update는 엔티티 코드에 추가한 필드에만 적용되고 필드를 수정하거나 삭제하는 경우 db에 반영 되지 않는 것으로 알고 있습니다.
Flyway db 같은 버전 관리 도구를 고려해 보는 것도 좋을 것 같습니다.
