### ISSUE TITLE
Decimal point setting required for all charts

### ISSUE THREAD

**Issue by AnnieHwang** [metatron-app/metatron-discovery#964]
**Is your feature request related to a problem? Please describe.**
Combine 차트에서 막대, 라인 모두 소수점 자릿수 설정이 각각 필요함
현재 하나의 차트에만 적용됨

![image](https://user-images.githubusercontent.com/6300003/49269801-3aa04600-f4aa-11e8-9c7c-764b23364c2d.png)

**Comment by dave-taeho** [comment]
#175 이슈와 동일한 이슈라 해당 브랜치에서 진행하겠습니다.
