### ISSUE TITLE
 The records in the data table do not match the actual data.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#968]
**Describe the bug**
- 데이터 테이블의 표현된 전체 레코드가 실제 데이터 레코드 갯수와 일치하지 않음

**To Reproduce**
- 재현주소 : http://52.231.184.135:8180/app/v2/workbook/ad7ca205-1839-4705-b5e0-4529b9b2ef6c
- <img width="1435" alt="2018-11-30 4 21 56" src="https://user-images.githubusercontent.com/612173/49274852-f8cccb00-f4bc-11e8-8c1b-434cfc8aab5d.png">
- 위 스크린샷의 두번째 차트(Data Table) 에서 레코드 건수가 100개까지 표현됨 --> 실제 데이터는 125건 

**Expected behavior**
- 차트의 Limitation 보다 적은 레코드 건수에 대해서는 Data Table 에 표현되는 레코드 갯수와 실제 데이터가 일치해야함

**Desktop (please complete the following information):**

**Comment by alchan-lee** [comment]
@eltriny 
그리드 차트에서 유형을 "원본 데이터"로 설정하면 limitation 설정이 적용되지 않고 있습니다.
(무조건 100으로 되고 있네요)

관련해서 확인 부탁드립니다

![image](https://user-images.githubusercontent.com/42234141/50946983-771a8500-14df-11e9-993f-fc196c24005a.png)
