### ISSUE TITLE
Calculated value of 'Total Row' filter differs from actual value.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#969]
**Describe the bug**
- 데이터 테이블의 Total Row 필터 설정 후 집계된 값이, 실제 데이터 값과 일치하지 않는 버그

**To Reproduce**
- 재현주소 : http://52.231.184.135:8180/app/v2/workbook/b9c7f506-ea5f-4fb2-8118-cff632231ce5
- <img width="1136" alt="2018-11-30 4 34 56" src="https://user-images.githubusercontent.com/612173/49275359-747b4780-f4be-11e8-8b34-d0856722d116.png">
- 위 스크린샷의 합계 47, 항목수 15 모두 실제 값과 일치하지 않음

**Expected behavior**
- 값이 일치해야 함

**Desktop (please complete the following information):**

**Comment by kyungtaak** [comment]
@Taehui 현재는 count distinct 를 구할때 Cardinality aggregator 를 사용합니다. (http://druid.io/docs/latest/querying/aggregations) 원래 오픈소스 준비 당시 좀더 정확한 DataSketches aggregator를 사용하였지만, 3.0 내 포팅하지 않은 상태인데요. 이 DataSketches aggregator (http://druid.io/docs/latest/development/extensions-core/datasketches-aggregators.html) 자체도 아래와 같이 명시하고 있습니다. 이번 이슈에서는 DataSketches aggregator 를 적용하는 것을 먼저 진행하고 정확도가 떨어진다면, 추가로 검토하도록 하겠습니다. 

> Note that sketch algorithms are approximate;

**Comment by eltriny** [comment]
f#969-calculated_value_total_row 브렌치 생성했습니다.

**Comment by eltriny** [comment]
@kyungtaak 
위 재현 주소에서 3번재 그리드 차트와 같이 서버에서 COUNTD([City]) 와 같이 카운트를 한 경우에 대해서 확인 부탁드립니다.
아래의 이미지와 같이 내려오는 항목 수가 60개이고, 그리드의 합계도 60으로 나오는데 서버에서 카운트를 센 것은 61로 표시되고 있습니다.
![2018-12-04 3 15 36](https://user-images.githubusercontent.com/3685833/49392990-6a35a380-f773-11e8-8367-fce0dcb90e72.png)

그리드 수정은 완료하여 본 이슈의 브랜치에 커밋해두었습니다.
