### ISSUE TITLE
 Error when selecting a specific dimension in the "Column Detail" tab

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#97]
**Describe the bug**
특정 데이터 소스 상세 화면 내 Column Detail 탭내 특정 Diminsion을 선택하면 스크립트 오류 발생합니다.

**To Reproduce**
1. Go to [DemoSite](https://discovery.metatron.app/app/v2/management/storage/datasource/ff971c55-1e9a-4e99-a596-d3ee83d7a75e)
2. Click on 'Column Details' Tab
2. Click on 'Row ID' Dimension Field

**Expected behavior**
정정상적으로 컬럼 상세 화면이 나타납니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/822255/44832369-979b1e80-ac65-11e8-83ce-38df5fd67e61.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser : Chrome
 - Version : 68.0

**Additional context**

**Comment by eltriny** [comment]
@kyungtaak @alchan-lee 
위 데모사이트에서 확인을 해봤습니다만.. 재현이 되지 않고 있습니다..
혹시 확인할 수 있는 다른 케이스는 없는 것인가요?

**Comment by i1befree** [comment]
@eltriny 
https://discovery.metatron.app/app/v2/management/storage/datasource/ff971c55-1e9a-4e99-a596-d3ee83d7a75e

여기서 재현 되시지 않나요? 지금 들어가 봐도 재현이 되는데요.

**Comment by kyungtaak** [comment]
@eltriny 해상도를 높여서 확인해주세요.

**Comment by kyungtaak** [comment]
@eltriny 스크립트 이슈보다는 높이 조절 문제입니다.

**Comment by brandon-wonjune** [comment]
@kyungtaak 데모사이트 버젼이 낮은것 같습니다.

데모사이트 
![2018-10-02 11 32 00](https://user-images.githubusercontent.com/42233627/46326639-aac05600-c638-11e8-9305-7867ebe2f594.png)


3.0.4
![2018-10-02 11 44 35](https://user-images.githubusercontent.com/42233627/46326642-ac8a1980-c638-11e8-9812-a83142b2a449.png)

**Comment by kyungtaak** [comment]
@brandon-wonjune 확인했습니다.

해당 수정건은 다른 이슈내에서 퍼블리싱 처리중 해결된것으로 보이네요. 
정상동작을 확인하였으니, 이슈를 종료하겠습니다.
