### ISSUE TITLE
Legend selection (selection through dimension of color setting) is not possible when there are two dimension values.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#970]
**Describe the bug**
- 차원값이 2개인 경우 범례 선택(색상 설정의 dimension을 통한 선택)이 안됨
- 첫번째 차원값을 선택하려해도 두번째값으로만 지정됨(저장하면 원복됨)

**To Reproduce**
1. Go to http://52.231.184.135:8180/app/v2/workbook/df3af1d9-8d86-45f9-9eaf-0962ad381c9c
2. 위 주소 첫번째 차트에서 Edit 모드 실행
3. Color Setting 필터 클릭
4. 'City' 를 'Country' 로 변경
5. Save
--> 적용안되고 원복

**Expected behavior**
- 적용되어야 함

**Desktop (please complete the following information):**

**Comment by alchan-lee** [comment]
fixed in #1011
