### ISSUE TITLE
Sorting function of data table does not work properly.

### ISSUE THREAD

**Issue by Taehui** [metatron-app/metatron-discovery#973]
**Describe the bug**
- 테이블의 x축을 데이터 정렬하고자 하는 경우 동작 안함
- 테이블차트 복수의 데이터 정렬 안됨
  --> X, Y축 무관 A컬럼 정렬하고 B컬럼 정렬 추가하면 A컬럼 정렬이 풀리는 증상

**Expected behavior**
- 정렬이 정상적으로 동작해야 함

**Desktop (please complete the following information):**

**Comment by YooYoungmo** [comment]
## X 축 데이터 정렬 문제
### 문제 재현
`ShipMode`를 정렬을 변경해도 테이블에 보이는 데이터가 변함 없음
![image](https://user-images.githubusercontent.com/16472109/49987548-fc7d4900-ffb6-11e8-9e7f-209e939f3054.png)

### 원인
메타트론 API를 호출시 X 축에 대한 정렬값을 정상적으로 보내고 있으나, 메타트론에서 엔진(드루이드)에 조회시 X 축에 대한 정렬이 ascending으로 고정되어 있음

**Comment by YooYoungmo** [comment]
먼저 X축에 데이터 정렬 오류 진행 합니다.

**Comment by YooYoungmo** [comment]
## 테이블차트 복수의 데이터 정렬 안됨
### 문제 재현
![image](https://user-images.githubusercontent.com/16472109/50072425-8bd56700-0218-11e9-8ef6-36fd6c1a019a.png)

### 원인
* 메타트론에서 엔진(드루이드)에 조회시 화면에서 설정한 것 처럼 Y 축의 정렬 순서(`City`, `State`)로 요청해야 원하는 결과를 얻을 수 있음.
* 테스트 결과 만약 사용자가 화면에서 `State` 정렬을 변경하게 되면 메타트론 서버에서 `State`, `City` 순서로 드루이드에 요청하기 때문에 사용자가 원하는 순서 데이터가 조회되지 않음.
* 결과적으로는 사용자가 화면에서 설정한 순서대로 드루이드에 정렬 요청을 해야함.
