### ISSUE TITLE
Partition column as timestamp role didn't recognized  in StageDB(Hive) ingestion

### ISSUE THREAD

**Issue by kyungtaak** [metatron-app/metatron-discovery#983]
**Describe the bug**
특정 사이트에서 stagedb 적재시 hive 내 timestamp role 로 지정한 partition column 을 제대로 인식하지 못해 적재가 제대로 되지 않는 현상이 발생합니다. 

**To Reproduce**
Steps to reproduce the behavior: Overlord 로그내 전달된 쿼리 내용 
- Input Spec 내 hive 타입
![image](https://user-images.githubusercontent.com/822255/49349309-62332080-f6ed-11e8-89aa-49cd1c274cfd.png)
![image](https://user-images.githubusercontent.com/822255/49414663-8eb36f00-f7b7-11e8-9c51-9a42947c45c3.png)
![image](https://user-images.githubusercontent.com/822255/49349322-70813c80-f6ed-11e8-8961-cd9bcb9bb559.png)

- Input Spec 내 hadoop 타입으로 변환 결과
![image](https://user-images.githubusercontent.com/822255/49349357-960e4600-f6ed-11e8-81f0-9284422c8f40.png)
![image](https://user-images.githubusercontent.com/822255/49349363-9c9cbd80-f6ed-11e8-9715-218223ad6296.png)

- 결과 : druid.internal 에 oob-row-num 에 값 표시
![image](https://user-images.githubusercontent.com/822255/49349393-b9d18c00-f6ed-11e8-84a3-a62a5b2bacce.png)

**Expected behavior**
partition column 내 값을 인식하여 적재가 정상적으로 동작해야합니다.

**Screenshots**
(N/A)

**Desktop (please complete the following information):**
(N/A)

**Additional context**
(N/A)

**Comment by navis** [comment]
위에 사진도 그렇고 아래 사진도 그렇고.. io config 만 잘 안보이게 보내는건 일부러 그러는 건가요..? -_-+

**Comment by navis** [comment]
하둡 로그 파일에 "Reading from path " 로 시작하는 로그 메시지를 한번 찾아봐 주세요.

**Comment by kyungtaak** [comment]
#1000 의 엔진 이슈에서 처리하여 이상없음을 확인했습니다.
