### ISSUE TITLE
Close context menu when scrolling

### ISSUE THREAD

**Issue by sang-hee-lee** [metatron-app/metatron-discovery#986]
**Describe the bug**
Context menu does not close when scrolling

**To Reproduce**
1. menu MANAGEMENT > DataPreparation
2. Dataflow > click dataflow
3. click Edit rules > Click on any column Context menu button
4. scroll

**Expected behavior**
Context menu close when scrolling

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by imsaaks** [comment]
done

**Comment by joohokim1** [comment]
Integrated test 2 passed.
